function CHelpPanel(){var a,d,b,e,f,g,c,h,m,k,l;this._init=function(){k=createBitmap(s_oSpriteLibrary.getSprite("bg_help"));s_oStage.addChild(k);m=!1===s_bMobile?TEXT_HELP1:TEXT_HELP_MOB1;d=new createjs.Text(m,"bold 18px walibi","#000000");d.textAlign="left";d.x=74;d.y=224;d.textBaseline="alphabetic";d.lineWidth=380;a=new createjs.Text(m,"bold 18px walibi","#fcff00");a.textAlign="left";a.x=70;a.y=220;a.textBaseline="alphabetic";a.lineWidth=380;e=new createjs.Text(TEXT_HELP2,"bold 22px walibi","#000000");
e.textAlign="left";e.x=324;e.y=414;e.textBaseline="alphabetic";e.lineWidth=250;b=new createjs.Text(TEXT_HELP2,"bold 22px walibi","#fcff00");b.textAlign="left";b.x=320;b.y=410;b.textBaseline="alphabetic";b.lineWidth=250;g=new createjs.Text(TEXT_HELP3,"bold 22px walibi","#000000");g.textAlign="left";g.x=74;g.y=544;g.textBaseline="alphabetic";g.lineWidth=250;f=new createjs.Text(TEXT_HELP3,"bold 22px walibi","#fcff00");f.textAlign="left";f.x=70;f.y=540;f.textBaseline="alphabetic";f.lineWidth=250;h=new createjs.Text(TEXT_HELP4,
"bold 22px walibi","#000000");h.textAlign="left";h.x=244;h.y=716;h.textBaseline="alphabetic";h.lineWidth=350;c=new createjs.Text(TEXT_HELP4,"bold 22px walibi","#fcff00");c.textAlign="left";c.x=240;c.y=712;c.textBaseline="alphabetic";c.lineWidth=350;l=new createjs.Container;l.addChild(k,d,a,e,b,g,f,h,c);s_oStage.addChild(l);var n=this;l.on("pressup",function(){n._onExitHelp()})};this.unload=function(){s_oStage.removeChild(l);var a=this;l.off("pressup",function(){a._onExitHelp()})};this._onExitHelp=
function(){this.unload();s_oGame._onExitHelp()};this._init()}
function CGfxButton(a,d,b,e){var f,g,c;this._init=function(a,b,d,e){f=[];g=[];c=createBitmap(d);c.x=a;c.y=b;c.scaleX=e;c.scaleY=e;c.regX=d.width/2;c.regY=d.height/2;s_oStage.addChild(c);this._initListener()};this.unload=function(){c.off("mousedown",this.buttonDown);c.off("pressup",this.buttonRelease);s_oStage.removeChild(c)};this.setVisible=function(a){c.visible=a};this._initListener=function(){c.on("mousedown",this.buttonDown);c.on("pressup",this.buttonRelease)};this.addEventListener=function(a,
b,d){f[a]=b;g[a]=d};this.buttonRelease=function(){c.scaleX=e;c.scaleY=e;f[ON_MOUSE_UP]&&f[ON_MOUSE_UP].call(g[ON_MOUSE_UP])};this.buttonDown=function(){c.scaleX=.9*e;c.scaleY=.9*e;f[ON_MOUSE_DOWN]&&f[ON_MOUSE_DOWN].call(g[ON_MOUSE_DOWN])};this.setPosition=function(a,b){c.x=a;c.y=b};this.setX=function(a){c.x=a};this.setY=function(a){c.y=a};this.getButtonImage=function(){return c};this.getX=function(){return c.x};this.getY=function(){return c.y};this._init(a,d,b,e);return this}
function CGame(a){var d,b,e,f;function g(a){h&&(k=!1)}function c(a){a||(a=window.event);if(!k)switch(k=!0,a.keyCode){case 37:s_oGame.onLeftPress();break;case 38:s_oGame.onUpPress();break;case 39:s_oGame.onRightPress();break;case 40:s_oGame.onDownPress()}}var h,m,k,l,n,r,p,z,t,y,x,K,F,u,A,H,w,v,B,C,L,D,G,M=null,E,q,J,P,I,Q,N,O,R;this._init=function(){k=m=!0;r=0;p=LIVES;D=[];x=SINK_TURTLE_OCCURRENCY;F=0;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundtrack.volume=.6;z=17;t=15;e=(CANVAS_WIDTH-11)/
z;f=(CANVAS_HEIGHT-386)/t;var a=5.5+e/2;u=[];for(var b=0;b<t;b++){u[b]=[];for(var d=0;d<z;d++)u[b][d]={x:a+e*d,y:808-f*b}}P=new createjs.Container;s_oStage.addChild(P);Q=new createjs.Container;s_oStage.addChild(Q);I=new createjs.Container;s_oStage.addChild(I);a=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(a);O=new createjs.Container;s_oStage.addChild(O);N=new createjs.Container;s_oStage.addChild(N);G=new CInterface;this._initLevel();!1===s_bMobile&&(document.onkeydown=c,document.onkeyup=
g);new CHelpPanel};this._initLevel=function(){n=l=h=!1;K=y=0;E=new CWater(u[9][0].y,f,F,P);J=new CStreet(u[3][0].y,f,F);A=[];for(var a=0;5>a;a++)A[a]=J.getLaneInfo(a).occur;H=[];for(a=0;5>a;a++)H[a]=E.getLaneInfo(a).occur;w=[];for(var e,c,a=0;a<STREET_LANE_OCCURENCE.length;a++)e=Math.random()*CANVAS_WIDTH/2,c=Math.floor(10*Math.random()),w.push(new CCar(J.getLaneInfo(a),c,N)),w[a].instantCar(e+CANVAS_WIDTH/4,J.getLaneInfo(a).pos);v=[];B=[,,"free",,,"free",,,"free",,,"free",,,"free"];C=[];L=[];D[0]=
x;D[1]=x;d=FROG_STARTING_LOGIC_POS.row;b=FROG_STARTING_LOGIC_POS.col;q=new CFrog(u[d][b].x,u[d][b].y,O)};this.onUpPress=function(){if(!m){m=!0;var a=q.getPos().y-V_MOVE;a<u[t-1][0].y&&(a=u[t-1][0].y);q.move(q.getPos().x,a,"up",a)}};this.onDownPress=function(){if(!m){m=!0;var a=q.getPos().y+V_MOVE;a>u[0][0].y&&(a=u[0][0].y);q.move(q.getPos().x,a,"down",a)}};this.onLeftPress=function(){if(!m){m=!0;var a=q.getPos().x-H_MOVE;a<u[0][0].x&&(a=u[0][0].x);q.move(a,q.getPos().y,"left",a)}};this.onRightPress=
function(){if(!m){m=!0;var a=q.getPos().x+H_MOVE;a>u[0][z-1].x&&(a=u[0][z-1].x);q.move(a,q.getPos().y,"right",a)}};this.updateLogicPos=function(){for(var a=0;a<t;a++)for(var c=0;c<z;c++)q.getPos().x>=u[a][c].x-e/2&&q.getPos().x<=u[a][c].x+e/2&&(b=c),q.getPos().y>=u[a][c].y-f/2&&q.getPos().y<=u[a][c].y+f/2&&(d=a)};this.updateScore=function(a){r+=a;0>r&&(r=0);G.refreshScore(r)};this.unload=function(){G.unload();null!==M&&M.unload();for(var a=0;a<w.length;a++)w[a].unload();for(a=0;a<v.length;a++)v[a].unload();
createjs.Tween.removeAllTweens();s_oStage.removeAllChildren()};this.onExit=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundtrack.volume=1;this.unload();s_oMain.gotoMenu();$(s_oMain).trigger("restart")};this._onExitHelp=function(){n=h=!0;m=k=!1;G.refreshBar()};this.gameOver=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundtrack.volume=.3;for(var a=0;a<v.length;a++)v[a].stopAnim();n=!1;createjs.Tween.removeAllTweens();M=CEndPanel(s_oSpriteLibrary.getSprite("msg_box"));
M.show(r)};this._updateLives=function(a){"add"===a?p++:p--;G.refreshLives(p);0===p&&(q.setTextVisible(!1),this.gameOver())};this.reset=function(){for(var a=0;a<w.length;a++)w[a].unload();for(a=0;a<v.length;a++)v[a].unload();for(a=0;a<L.length;a++)L[a].unload();0===F%NUM_LEVEL_INCREASE_SINK&&x--;0>x&&(x=0);G.refreshBar();this._initLevel();h=n=!0};this._checkNewLevel=function(){y++;5===y&&(F++,q.setTextVisible(!1),G.stopBar(),h=!1,k=m=!0,(new CLevelPanel(F)).show(r))};this.addElemToRemoveList=function(a){var b,
d;if("car"===a.getType())for(var c=0;c<w.length;c++)w[c]===a&&(b=c,d="car");else for(c=0;c<v.length;c++)v[c]===a&&(b=c,d="support");C.push({elem:a,index:b,type:d})};this.freeCell=function(a){B[a]="free"};this._generateFly=function(){K+=s_iTimeElaps;if(K>TIME_FLY_TO_SPAWN){K=0;for(var a=[],b=0;b<B.length;b++)"free"===B[b]&&a.push(b);0<a.length&&(shuffle(a),R=new CFly(u[14][a[0]].x,u[14][a[0]].y,a[0]),B[a[0]]="fly")}};this._generateNewFrog=function(){0!==p&&(d=FROG_STARTING_LOGIC_POS.row,b=FROG_STARTING_LOGIC_POS.col,
q=new CFrog(u[d][b].x,u[d][b].y,O),G.refreshBar(),h=!0,m=!1)};this._generateCar=function(){for(var a=0;a<A.length;a++)if(A[a]+=s_iTimeElaps,A[a]>J.getLaneInfo(a).occur){A[a]=0;var b=Math.floor(10*Math.random());w.push(new CCar(J.getLaneInfo(a),b,N));w[w.length-1].playHornet(d)}};this._generateSupport=function(){for(var a=0;a<H.length;a++)if(H[a]+=s_iTimeElaps,H[a]>E.getLaneInfo(a).occur)if(H[a]=0,0===a){if(0===D[0]){for(var b=0;b<NUM_CONSECUTIVE_TURTLE_0;b++)v.push(new CTurtle(E.getLaneInfo(a),1,
b*TURTLE_OFFSET,I));D[0]=x+1}else for(b=0;b<NUM_CONSECUTIVE_TURTLE_0;b++)v.push(new CTurtle(E.getLaneInfo(a),0,b*TURTLE_OFFSET,I));D[0]--}else if(3===a){if(0===D[1]){for(b=0;b<NUM_CONSECUTIVE_TURTLE_3;b++)v.push(new CTurtle(E.getLaneInfo(a),1,b*TURTLE_OFFSET,I));D[1]=x+1}else for(b=0;b<NUM_CONSECUTIVE_TURTLE_3;b++)v.push(new CTurtle(E.getLaneInfo(a),0,b*TURTLE_OFFSET,I));D[1]--}else v.push(new CTrunk(E.getLaneInfo(a),I))};this.update=function(){if(h){var a=q.getLogicRect();if(14===d)"free"===B[b]||
"fly"===B[b]?(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("frog_arrived"),a=!1,"fly"===B[b]&&(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("eat_fly"),a=!0,R.unload()),a?this.updateScore(SCORE_WITH_FLY):this.updateScore(SCORE_IN_NEST),this._checkNewLevel(),B[b]="taken",q.setPos(u[d][b].x,u[d][b].y),d=0,L.push(q),q.great(),5>y&&this._generateNewFrog()):"taken"===B[b]?(q.unload(),this._generateNewFrog()):(q.crash(),this._updateLives("sub"),h=!1,this._generateNewFrog(),
this.updateScore(SCORE_DEATH));else if(8<d&&14>d&&!m){for(var c=0;c<v.length;c++)if(null!==v[c].getLogicRect()&&v[c].getLogicRect().intersects(a)){var e=v[c].getSpeed();q.getPos().x>=u[0][0].x&&q.getPos().x<=u[0][16].x?q.carry(e):q.getPos().x<u[0][0].x?q.setPos(u[0][0].x,q.getPos().y):q.setPos(u[0][16].x,q.getPos().y);l=!0}l||(m=!0,this._updateLives("sub"),q.drown(),q.unload(),Q.addChild(q.getContainer()),h=!1,this._generateNewFrog(),this.updateScore(SCORE_DEATH))}else for(c=0;c<w.length;c++)w[c].getLogicRect().intersects(a)&&
(m=!0,this._updateLives("sub"),h=!1,q.splat(),this._generateNewFrog(),this.updateScore(SCORE_DEATH));q.getDead()||q.isJumping()||(m=!1);l=!1}if(n){this._generateCar();this._generateSupport();this._generateFly();E.update();for(c=0;c<w.length;c++)w[c].update();for(c=0;c<v.length;c++)v[c].update();C.sort(compare);for(c=0;c<C.length;c++)C[c].elem.unload(),"car"===C[c].type?w.splice(C[c].index,1):v.splice(C[c].index,1);C=[]}};s_oGame=this;LIVES=a.lives;LEVEL_TIME=a.crossing_time;SCORE_IN_NEST=a.score_in_nest;
SCORE_WITH_FLY=a.score_with_fly;SCORE_DEATH=a.score_death;FROG_SPEED=a.frog_speed;SINK_TURTLE_OCCURRENCY=a.sink_turtle_occurrency;NUM_LEVEL_INCREASE_SINK=a.num_level_increase_sink;TIME_FLY_TO_SPAWN=a.time_fly_to_spawn;TIME_FLY_TO_DISAPPEAR=a.time_fly_to_disappear;STREET_LANE_TIMESPEED=a.street_lane_timespeed;STREET_TIMESPEED_DECREASE_PER_LEVEL=a.street_timespeed_decrease_per_level;STREET_LANE_OCCURENCE=a.street_lane_occurrence;STREET_OCCURENCE_DECREASE_PER_LEVEL=a.street_occurrence_decrease_per_level;
WATER_LANE_TIMESPEED=a.water_lane_timespeed;WATER_TIMESPEED_DECREASE_PER_LEVEL=a.water_timespeed_decrease_per_level;WATER_LANE_OCCURENCE=a.water_lane_occurrence;WATER_OCCURENCE_INCREASE_PER_LEVEL=a.water_occurrence_increase_per_level;this._init()}var s_oGame;
function CFrog(a,d,b){var e,f,g,c,h,m,k,l,n;this._init=function(a,b,d){c=g=!1;h=!0;m=FROG_SPEED;e=10;f=25;n=new createjs.Container;n.x=a;n.y=b;d.addChild(n);a={images:[s_oSpriteLibrary.getSprite("frog")],frames:{width:50,height:75,regX:25,regY:37.5},animations:{idle:[0],jump:[1,5,"idle"],splat:[6],drown:[7,44,"drown_stop"],drown_stop:[44],skid_marks:[45]}};a=new createjs.SpriteSheet(a);k=createSprite(a,"jump",0,0,50,75);n.addChild(k);l=createBitmap(s_oSpriteLibrary.getSprite("skid_rows"));l.regX=
25;l.regY=37.5;l.visible=!1;n.addChild(l)};this.unload=function(){b.removeChild(n)};this._disappear=function(){var a=this;createjs.Tween.get(n).wait(2E3).to({alpha:0},2E3,createjs.Ease.linear).call(function(){a.unload()})};this.move=function(a,b,d,e){c=!0;!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("jump");switch(d){case "up":k.rotation=0;break;case "down":k.rotation=180;break;case "left":k.rotation=270;break;case "right":k.rotation=90}k.gotoAndPlay("jump");createjs.Tween.get(n).to({x:a,
y:b},m,createjs.Ease.linear).call(function(){s_oGame.updateLogicPos();c=!1});createjs.Tween.get(n).to({scaleX:1.5,scaleY:1.5},m/2,createjs.Ease.quintIn).to({scaleX:1,scaleY:1},m/2,createjs.Ease.quintIn)};this.isJumping=function(){return c};this.setTextVisible=function(a){h=a};this.drown=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("drown");g=!0;k.gotoAndPlay("drown");(new CWinText(TEXT_DROWN,this.getPos().x,this.getPos().y,h)).drown();this._disappear()};this.splat=function(){!1!==
DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("splat");k.gotoAndPlay("splat");g=l.visible=!0;(new CWinText(TEXT_SPLAT,this.getPos().x,this.getPos().y,h)).splat();this._disappear()};this.crash=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("splat");k.gotoAndPlay("splat");g=!0;(new CWinText(TEXT_SPLAT,this.getPos().x,this.getPos().y,h)).splat();this._disappear()};this.great=function(){(new CWinText(TEXT_GREAT,this.getPos().x,this.getPos().y,h)).great()};this.getDead=
function(){return g};this.setPos=function(a,b){n.x=a;n.y=b};this.getPos=function(){return{x:n.x,y:n.y}};this.getContainer=function(){return n};this.getLogicRect=function(){return new createjs.Rectangle(n.x-e/2,n.y-f/2,e,f)};this.carry=function(a){n.x+=a};this._init(a,d,b)}
function CFly(a,d,b){var e;this._init=function(a,b,c){var d=s_oSpriteLibrary.getSprite("fly");e=createBitmap(d);e.x=a;e.y=b;e.regX=d.width/2;e.regY=d.height/2;s_oStage.addChild(e);var m=this;createjs.Tween.get(e).wait(TIME_FLY_TO_DISAPPEAR).call(function(){m.unload();s_oGame.freeCell(c)})};this.unload=function(){createjs.Tween.removeTweens(e);s_oStage.removeChild(e)};this._init(a,d,b)}
function CEndPanel(a){var d,b,e,f,g,c;this._init=function(a){d=createBitmap(a);d.x=0;d.y=0;e=new createjs.Text("","bold 60px walibi","#000000");e.x=CANVAS_WIDTH/2+4;e.y=CANVAS_HEIGHT/2-160;e.textAlign="center";f=new createjs.Text("","bold 60px walibi","#fcff00");f.x=CANVAS_WIDTH/2;f.y=CANVAS_HEIGHT/2-164;f.textAlign="center";g=new createjs.Text("","bold 40px walibi","#000000");g.x=CANVAS_WIDTH/2+4;g.y=CANVAS_HEIGHT/2+54;g.textAlign="center";c=new createjs.Text("","bold 40px walibi","#fcff00");c.x=
CANVAS_WIDTH/2;c.y=CANVAS_HEIGHT/2+50;c.textAlign="center";b=new createjs.Container;b.alpha=0;b.visible=!1;b.addChild(d,g,c,e,f);s_oStage.addChild(b)};this.unload=function(){b.off("mousedown",this._onExit)};this._initListener=function(){b.on("mousedown",this._onExit)};this.show=function(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("game_over");e.text=TEXT_GAMEOVER;f.text=TEXT_GAMEOVER;g.text=TEXT_SCORE+": "+a;c.text=TEXT_SCORE+": "+a;b.visible=!0;var d=this;createjs.Tween.get(b).to({alpha:1},
500).call(function(){d._initListener()});$(s_oMain).trigger("save_score",a)};this._onExit=function(){b.off("mousedown",this._onExit);s_oStage.removeChild(b);s_oGame.onExit()};this._init(a);return this}
function CCar(a,d,b){var e,f,g,c,h,m,k,l,n,r,p;this.init=function(a,b,d){h=!1;k=0;e=a.pos;f=a.start;g=a.end;c=a.speed;a=s_oSpriteLibrary.getSprite("car_"+b);l=a.width;n=a.height;p=createBitmap(a);p.x=f;p.y=e;p.regX=l/2;p.regY=n/2;f<g?(p.rotation=180,r=CANVAS_WIDTH+UNLOAD_OFFSET,m="right"):(r=-UNLOAD_OFFSET,m="left");d.addChild(p)};this.unload=function(){b.removeChild(p)};this.playHornet=function(a){var b=Math.random();(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)&&.66>b&&2<a&&8>a&&(0===d||1===d?createjs.Sound.play("big_hornet"):
createjs.Sound.play("small_hornet"))};this.instantCar=function(b){c=a.speed/2;f=b};this.setPos=function(a,b){p.x=a;p.y=b};this.getType=function(){return"car"};this.setGone=function(a){h=a};this.getGone=function(){return h};this.getLogicRect=function(){return new createjs.Rectangle(p.x-l/2,p.y-n/2,l,n)};this.update=function(){if(!h){k+=s_iTimeElaps;var a=easeLinear(k,0,1,c),a=tweenVectorsOnX(f,r,a);p.x=a;if("right"===m&&p.x>r||"left"===m&&p.x<r)h=!0,s_oGame.addElemToRemoveList(this)}};this.init(a,
d,b)}
function CSpriteLibrary(){var a,d,b,e,f,g;this.init=function(c,h,m){b=d=0;e=c;f=h;g=m;a={}};this.addSprite=function(b,e){a.hasOwnProperty(b)||(a[b]={szPath:e,oSprite:new Image},d++)};this.getSprite=function(b){return a.hasOwnProperty(b)?a[b].oSprite:null};this._onSpritesLoaded=function(){f.call(g)};this._onSpriteLoaded=function(){e.call(g);++b==d&&this._onSpritesLoaded()};this.loadSprites=function(){for(var b in a)a[b].oSprite.oSpriteLibrary=this,a[b].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},a[b].oSprite.src=
a[b].szPath};this.getNumSprites=function(){return d}}
var CANVAS_WIDTH=640,CANVAS_HEIGHT=1136,FPS_TIME=1E3/24,DISABLE_SOUND_MOBILE=!1,STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,H_MOVE=37,V_MOVE=50,LEVEL_TIME,MAX_LEVEL_DIFFICULTY=20,SCORE_IN_NEST,SCORE_WITH_FLY,SCORE_DEATH,UNLOAD_OFFSET=100,TURTLE_OFFSET=74,NUM_CONSECUTIVE_TURTLE_0=3,NUM_CONSECUTIVE_TURTLE_3=2,SINK_TURTLE_OCCURRENCY,NUM_LEVEL_INCREASE_SINK,TIME_FLY_TO_SPAWN,TIME_FLY_TO_DISAPPEAR,FROG_STARTING_LOGIC_POS=
{row:0,col:8},LIVES,FROG_SPEED,STREET_LANE_SPEED=[],STREET_SPEED_DECREASE_PER_LEVEL=[],STREET_LANE_OCCURENCE=[],STREET_OCCURENCE_DECREASE_PER_LEVEL=[],WATER_LANE_TIMESPEED=[],WATER_TIMESPEED_DECREASE_PER_LEVEL=[],WATER_LANE_OCCURENCE=[],WATER_OCCURENCE_INCREASE_PER_LEVEL=[];
function CWinText(a,d,b,e){var f,g,c;this._init=function(a,b,d,e){c=new createjs.Container;c.x=b;c.y=d-60;c.alpha=0;c.visible=e;s_oStage.addChild(c);f=new createjs.Text("","bold 30px walibi","#fcff00");f.textAlign="center";f.text=a;f.textBaseline="alphabetic";c.addChild(f);g=new createjs.Text("","bold 30px walibi","#000000");g.textAlign="center";g.text=a;g.outline=3;g.textBaseline="alphabetic";c.addChild(g)};this.great=function(){c.scaleX=0;c.scaleY=0;c.alpha=1;var a=this;createjs.Tween.get(c).to({scaleX:1,
scaleY:1},100,createjs.Ease.linear).wait(2E3).call(function(){a.unload()})};this.splat=function(){var a=this;createjs.Tween.get(c).to({alpha:1},300,createjs.Ease.linear).to({alpha:0},2500,createjs.Ease.linear);createjs.Tween.get(c).wait(2E3).to({alpha:0},500,createjs.Ease.linear).call(function(){a.unload()})};this.crash=function(){var a=this;createjs.Tween.get(c).to({alpha:1},300,createjs.Ease.linear).to({alpha:0},2500,createjs.Ease.linear);createjs.Tween.get(c).wait(2E3).to({alpha:0},500,createjs.Ease.linear).call(function(){a.unload()})};
this.drown=function(){c.scaleX=0;c.scaleY=0;c.alpha=0;c.y=b;var a=this;createjs.Tween.get(c).to({alpha:1},2500,createjs.Ease.linear).to({alpha:0},2500,createjs.Ease.linear);createjs.Tween.get(c).to({scaleX:1,scaleY:1},5E3,createjs.Ease.linear).call(function(){a.unload()})};this.unload=function(){s_oStage.removeChild(c)};this._init(a,d,b,e)}
function CWater(a,d,b,e){var f,g,c,h,m,k,l,n;this._init=function(a,b,d,e){f=!0;g=0;c=9;k=[];n=new createjs.Container;n.y=a-280;e.addChild(n);var y;for(e=0;10>e;e++)y="water_anim_"+e,k[e]=createBitmap(s_oSpriteLibrary.getSprite(y)),k[e].visible=!1,n.addChild(k[e]);k[0].visible=!0;l=[];h=-UNLOAD_OFFSET;m=CANVAS_WIDTH+UNLOAD_OFFSET;d>MAX_LEVEL_DIFFICULTY&&(d=MAX_LEVEL_DIFFICULTY);y=[];for(e=0;e<WATER_LANE_TIMESPEED.length;e++)y[e]=WATER_LANE_TIMESPEED[e]+d*WATER_TIMESPEED_DECREASE_PER_LEVEL[e];var x=
[];for(e=0;e<WATER_LANE_OCCURENCE.length;e++)x[e]=WATER_LANE_OCCURENCE[e]+d*WATER_OCCURENCE_INCREASE_PER_LEVEL[e];l[0]={pos:a-0*b,start:m,end:h,speed:y[0],occur:x[0]};l[1]={pos:a-1*b,start:h,end:m,speed:y[1],occur:x[1]};l[2]={pos:a-2*b,start:h,end:m,speed:y[2],occur:x[2]};l[3]={pos:a-3*b,start:m,end:h,speed:y[3],occur:x[3]};l[4]={pos:a-4*b,start:h,end:m,speed:y[4],occur:x[4]}};this.getLaneInfo=function(a){return l[a]};this.update=function(){f=!f;0===g?(k[c].visible=!1,k[0].visible=!0):(k[g-1].visible=
!1,k[g].visible=!0);f&&g++;g>c&&(g=0)};this._init(a,d,b,e)}
function CTurtle(a,d,b,e){var f,g,c,h,m,k,l,n,r,p,z,t;this.init=function(a,b,d,e){c=!1;l=0;f=70;g=50;z=a;t=e;a=0===b?{idle:[0,33]}:{idle:[0,99]};a={images:[s_oSpriteLibrary.getSprite("turtle")],frames:{width:74,height:74,regX:37,regY:37},animations:a};a=new createjs.SpriteSheet(a);p=createSprite(a,"idle",0,0,74,74);p.y=z.pos;m=z.start+d;z.start<z.end?(p.rotation=180,k=CANVAS_WIDTH+UNLOAD_OFFSET+d,h="right"):(k=-100-UNLOAD_OFFSET+d,h="left");t.addChild(p)};this.unload=function(){t.removeChild(p)};
this.stopAnim=function(){p.stop()};this.getType=function(){return"support"};this.getPos=function(){return{x:p.x,y:p.y}};this.getSpeed=function(){return n};this.setGone=function(a){c=a};this.getGone=function(){return c};this.getLogicRect=function(){return 40>p.currentAnimationFrame||90<p.currentAnimationFrame?new createjs.Rectangle(p.x-f/2,p.y-g/2,f,g):null};this.update=function(){if(!c){l+=s_iTimeElaps;var b=easeLinear(l,0,1,a.speed),b=tweenVectorsOnX(m,k,b);r=p.x;p.x=b;n=b-r;if("right"===h&&p.x>
k||"left"===h&&p.x<k)c=!0,s_oGame.addElemToRemoveList(this)}};this.init(a,d,b,e)}
function CTrunk(a,d){var b,e,f,g,c,h,m,k,l,n,r;this.init=function(a,d){f=!1;h=0;b=190;e=40;n=a;r=d;var k={images:[s_oSpriteLibrary.getSprite("trunk")],frames:{width:222,height:50,regX:111,regY:25},animations:{idle:[0,14]}},k=new createjs.SpriteSheet(k);l=createSprite(k,"idle",0,0,222,50);l.x=n.start;l.y=n.pos;n.start<n.end?(l.rotation=180,c=CANVAS_WIDTH+UNLOAD_OFFSET,g="right"):(c=-UNLOAD_OFFSET,g="left");r.addChild(l)};this.unload=function(){r.removeChild(l)};this.stopAnim=function(){l.stop()};this.getType=
function(){return"support"};this.getPos=function(){return{x:l.x,y:l.y}};this.getSpeed=function(){return m};this.setGone=function(a){f=a};this.getGone=function(){return f};this.getLogicRect=function(){return new createjs.Rectangle(l.x-b/2,l.y-e/2,b,e)};this.update=function(){if(!f){h+=s_iTimeElaps;var b=easeLinear(h,0,1,a.speed),b=tweenVectorsOnX(a.start,c,b);k=l.x;l.x=b;m=b-k;if("right"===g&&l.x>c||"left"===g&&l.x<c)f=!0,s_oGame.addElemToRemoveList(this)}};this.init(a,d)}
function CToggle(a,d,b,e){var f,g,c,h;this._init=function(a,b,d,e){g=[];c=[];var r=new createjs.SpriteSheet({images:[d],frames:{width:d.width/2,height:d.height,regX:d.width/2/2,regY:d.height/2},animations:{state_true:[0],state_false:[1]}});f=e;h=createSprite(r,"state_"+f,d.width/2/2,d.height/2,d.width/2,d.height);h.x=a;h.y=b;h.stop();s_oStage.addChild(h);this._initListener()};this.unload=function(){h.off("mousedown",this.buttonDown);h.off("pressup",this.buttonRelease);s_oStage.removeChild(h)};this._initListener=
function(){h.on("mousedown",this.buttonDown);h.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,d){g[a]=b;c[a]=d};this.setActive=function(a){f=a;h.gotoAndStop("state_"+f)};this.buttonRelease=function(){h.scaleX=1;h.scaleY=1;!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");f=!f;h.gotoAndStop("state_"+f);g[ON_MOUSE_UP]&&g[ON_MOUSE_UP].call(c[ON_MOUSE_UP],f)};this.buttonDown=function(){h.scaleX=.9;h.scaleY=.9;g[ON_MOUSE_DOWN]&&g[ON_MOUSE_DOWN].call(c[ON_MOUSE_DOWN])};
this._init(a,d,b,e)}var s_iScaleFactor=1,s_oCanvasLeft,s_oCanvasTop;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,4))})(navigator.userAgent||
navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}
function getSize(a){var d=a.toLowerCase(),b=window.document,e=b.documentElement;if(void 0===window["inner"+a])a=e["client"+a];else if(window["inner"+a]!=e["client"+a]){var f=b.createElement("body");f.id="vpw-test-b";f.style.cssText="overflow:scroll";var g=b.createElement("div");g.id="vpw-test-d";g.style.cssText="position:absolute;top:-1000px";g.innerHTML="<style>@media("+d+":"+e["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+d+":7px!important}}</style>";f.appendChild(g);e.insertBefore(f,b.head);
a=7==g["offset"+a]?e["client"+a]:window["inner"+a];e.removeChild(f)}else a=window["inner"+a];return a}$(window).ready(function(){sizeHandler()});window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a=CANVAS_WIDTH,d=CANVAS_HEIGHT,b=window.innerWidth<document.documentElement.clientWidth?window.innerWidth:document.documentElement.clientWidth,e=window.innerHeight<document.documentElement.clientHeight?window.innerHeight:document.documentElement.clientHeight,b=getSize("Width"),e=getSize("Height");multiplier=s_iScaleFactor=Math.min(e/d,b/a);a*=multiplier;d*=multiplier;$("#canvas").css("width",a+"px");$("#canvas").css("height",d+"px");
$("#canvas").css("left",b/2-a/2+"px");s_oCanvasLeft=$("#canvas").offset().left;s_oCanvasTop=$("#canvas").offset().top}}function createBitmap(a,d,b){var e=new createjs.Bitmap(a),f=new createjs.Shape;d&&b?f.graphics.beginFill("#fff").drawRect(0,0,d,b):f.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);e.hitArea=f;return e}
function createSprite(a,d,b,e,f,g){a=null!==d?new createjs.Sprite(a,d):new createjs.Sprite(a);d=new createjs.Shape;d.graphics.beginFill("#000000").drawRect(-b,-e,f,g);a.hitArea=d;return a}function randomFloatBetween(a,d,b){"undefined"===typeof b&&(b=2);return parseFloat(Math.min(a+Math.random()*(d-a),d).toFixed(b))}function tweenVectorsOnX(a,d,b){return a+b*(d-a)}function shuffle(a){for(var d=a.length,b,e;0!==d;)e=Math.floor(Math.random()*d),--d,b=a[d],a[d]=a[e],a[e]=b;return a}
function bubbleSort(a){var d;do{d=!1;for(var b=0;b<a.length-1;b++)a[b]>a[b+1]&&(d=a[b],a[b]=a[b+1],a[b+1]=d,d=!0)}while(d)}function compare(a,d){return a.index>d.index?-1:a.index<d.index?1:0}function easeLinear(a,d,b,e){return b*a/e+d}function easeInQuad(a,d,b,e){return b*(a/=e)*a+d}function easeInSine(a,d,b,e){return-b*Math.cos(a/e*(Math.PI/2))+b+d}function easeInCubic(a,d,b,e){return b*(a/=e)*a*a+d}
function getTrajectoryPoint(a,d){var b=new createjs.Point,e=(1-a)*(1-a),f=a*a;b.x=e*d.start.x+2*(1-a)*a*d.traj.x+f*d.end.x;b.y=e*d.start.y+2*(1-a)*a*d.traj.y+f*d.end.y;return b}function formatTime(a){a/=1E3;var d=Math.floor(a/60);a=parseFloat(a-60*d).toFixed(1);var b="",b=10>d?b+("0"+d+":"):b+(d+":");return b=10>a?b+("0"+a):b+a}function degreesToRadians(a){return a*Math.PI/180}function checkRectCollision(a,d){var b,e;b=getBounds(a,.9);e=getBounds(d,.98);return calculateIntersection(b,e)}
function calculateIntersection(a,d){var b,e,f,g,c,h,m,k;b=a.x+(f=a.width/2);e=a.y+(g=a.height/2);c=d.x+(h=d.width/2);m=d.y+(k=d.height/2);b=Math.abs(b-c)-(f+h);e=Math.abs(e-m)-(g+k);return 0>b&&0>e?(b=Math.min(Math.min(a.width,d.width),-b),e=Math.min(Math.min(a.height,d.height),-e),{x:Math.max(a.x,d.x),y:Math.max(a.y,d.y),width:b,height:e,rect1:a,rect2:d}):null}
function getBounds(a,d){var b={x:Infinity,y:Infinity,width:0,height:0};if(a instanceof createjs.Container){b.x2=-Infinity;b.y2=-Infinity;var e=a.children,f=e.length,g,c;for(c=0;c<f;c++)g=getBounds(e[c],1),g.x<b.x&&(b.x=g.x),g.y<b.y&&(b.y=g.y),g.x+g.width>b.x2&&(b.x2=g.x+g.width),g.y+g.height>b.y2&&(b.y2=g.y+g.height);Infinity==b.x&&(b.x=0);Infinity==b.y&&(b.y=0);Infinity==b.x2&&(b.x2=0);Infinity==b.y2&&(b.y2=0);b.width=b.x2-b.x;b.height=b.y2-b.y;delete b.x2;delete b.y2}else{var h,m;a instanceof createjs.Bitmap?
(f=a.sourceRect||a.image,c=f.width*d,h=f.height*d):a instanceof createjs.Sprite?a.spriteSheet._frames&&a.spriteSheet._frames[a.currentFrame]&&a.spriteSheet._frames[a.currentFrame].image?(f=a.spriteSheet.getFrame(a.currentFrame),c=f.rect.width,h=f.rect.height,e=f.regX,m=f.regY):(b.x=a.x||0,b.y=a.y||0):(b.x=a.x||0,b.y=a.y||0);e=e||0;c=c||0;m=m||0;h=h||0;b.regX=e;b.regY=m;f=a.localToGlobal(0-e,0-m);g=a.localToGlobal(c-e,h-m);c=a.localToGlobal(c-e,0-m);e=a.localToGlobal(0-e,h-m);b.x=Math.min(Math.min(Math.min(f.x,
g.x),c.x),e.x);b.y=Math.min(Math.min(Math.min(f.y,g.y),c.y),e.y);b.width=Math.max(Math.max(Math.max(f.x,g.x),c.x),e.x)-b.x;b.height=Math.max(Math.max(Math.max(f.y,g.y),c.y),e.y)-b.y}return b}function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}function shuffle(a){for(var d=a.length,b,e;0<d;)e=Math.floor(Math.random()*d),d--,b=a[d],a[d]=a[e],a[e]=b;return a}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3==a.nodeType&&(a=a.parentNode);var d=document.createEvent("MouseEvents");d.initEvent("click",!0,!0);a.dispatchEvent(d)}}};
(function(){function a(a){var e={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};a=a||window.event;a.type in e?document.body.className=e[a.type]:(document.body.className=this[d]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var d="hidden";d in document?document.addEventListener("visibilitychange",a):(d="mozHidden")in document?document.addEventListener("mozvisibilitychange",a):(d="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",a):(d="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a})();
function CTextButton(a,d,b,e,f,g,c){var h,m,k,l,n;this._init=function(a,b,d,e,c,f,g){h=[];m=[];var F=createBitmap(d),u=Math.ceil(g/20);n=new createjs.Text(e,"bold "+g+"px "+c,"#000000");n.textAlign="center";n.textBaseline="alphabetic";var A=n.getBounds();n.x=d.width/2+u+1;n.y=Math.floor(d.height/2)+A.height/3+u+1;l=new createjs.Text(e,"bold "+g+"px "+c,f);l.textAlign="center";l.textBaseline="alphabetic";A=l.getBounds();l.x=d.width/2;l.y=Math.floor(d.height/2)+A.height/3;k=new createjs.Container;k.x=
a;k.y=b;k.regX=d.width/2;k.regY=d.height/2;k.addChild(F,n,l);s_oStage.addChild(k);this._initListener()};this.unload=function(){k.off("mousedown");k.off("pressup");s_oStage.removeChild(k)};this.setVisible=function(a){k.visible=a};this._initListener=function(){oParent=this;k.on("mousedown",this.buttonDown);k.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,d){h[a]=b;m[a]=d};this.buttonRelease=function(){k.scaleX=1;k.scaleY=1;h[ON_MOUSE_UP]&&h[ON_MOUSE_UP].call(m[ON_MOUSE_UP])};this.buttonDown=
function(){k.scaleX=.9;k.scaleY=.9;h[ON_MOUSE_DOWN]&&h[ON_MOUSE_DOWN].call(m[ON_MOUSE_DOWN])};this.setTextPosition=function(a){l.y=a;n.y=a+2};this.setPosition=function(a,b){k.x=a;k.y=b};this.setX=function(a){k.x=a};this.setY=function(a){k.y=a};this.getButtonImage=function(){return k};this.getX=function(){return k.x};this.getY=function(){return k.y};this._init(a,d,b,e,f,g,c);return this}
function CStreet(a,d,b){var e,f,g;this.init=function(a,b,d){e=[];f=-UNLOAD_OFFSET;g=CANVAS_WIDTH+UNLOAD_OFFSET;d>MAX_LEVEL_DIFFICULTY&&(d=MAX_LEVEL_DIFFICULTY);for(var k=[],l=0;l<STREET_LANE_TIMESPEED.length;l++)k[l]=STREET_LANE_TIMESPEED[l]+d*STREET_TIMESPEED_DECREASE_PER_LEVEL[l];shuffle(k);for(var n=[],l=0;l<STREET_LANE_OCCURENCE.length;l++)n[l]=STREET_LANE_OCCURENCE[l]+d*STREET_OCCURENCE_DECREASE_PER_LEVEL[l];shuffle(n);for(var r,l=0;5>l;l++)d=l%2,0===d?(d=g,r=f):(d=f,r=g),e[l]={pos:a-l*b,start:d,
end:r,speed:k[l],occur:n[l]}};this.getLaneInfo=function(a){return e[a]};this.init(a,d,b)}
function CPreloader(){var a,d,b,e,f,g,c;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.loadSprites();c=new createjs.Container;s_oStage.addChild(c)};this.unload=function(){c.removeAllChildren()};this.hide=function(){var a=this;setTimeout(function(){createjs.Tween.get(g).to({alpha:1},500).call(function(){a.unload();
s_oMain.gotoMenu()})},1E3)};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var h=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));c.addChild(h);h=s_oSpriteLibrary.getSprite("progress_bar");e=createBitmap(h);e.x=CANVAS_WIDTH/2-h.width/2;e.y=CANVAS_HEIGHT-170;c.addChild(e);a=h.width;d=h.height;f=new createjs.Shape;f.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(e.x,e.y,1,d);c.addChild(f);e.mask=
f;b=new createjs.Text("","30px ZombieA","#fff");b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT-125;b.shadow=new createjs.Shadow("#000",2,2,2);b.textBaseline="alphabetic";b.textAlign="center";c.addChild(b);g=new createjs.Shape;g.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);g.alpha=0;c.addChild(g)};this.refreshLoader=function(c){b.text=c+"%";f.graphics.clear();c=Math.floor(c*a/100);f.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(e.x,e.y,c,d)};this._init()}
function CMenu(){var a,d,b,e;this._init=function(){a=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(a);var f=s_oSpriteLibrary.getSprite("but_play");d=new CTextButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-200,f,TEXT_PLAY,"walibi","#fcff00",40);d.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)f=s_oSpriteLibrary.getSprite("audio_icon"),e=new CToggle(CANVAS_WIDTH-f.height/2-10,f.height/2+10,f,s_bAudioActive),e.addEventListener(ON_MOUSE_UP,
this._onAudioToggle,this);b=new createjs.Shape;b.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(b);createjs.Tween.get(b).to({alpha:0},1E3).call(function(){b.visible=!1})};this.unload=function(){d.unload();d=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)e.unload(),e=null;s_oStage.removeChild(a);a=null};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onButPlayRelease=function(){this.unload();!1!==
DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");s_oMain.gotoGame()};this._init()}
function CMain(a){var d,b=0,e=0,f=STATE_LOADING,g,c,h;this.initContainer=function(){s_oCanvas=document.getElementById("canvas");s_oStage=new createjs.Stage(s_oCanvas);createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&(s_oStage.enableMouseOver(20),$("body").on("contextmenu","#canvas",function(a){return!1}));s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.setFPS(24);navigator.userAgent.match(/Windows Phone/i)&&(DISABLE_SOUND_MOBILE=
!0);s_oSpriteLibrary=new CSpriteLibrary;c=new CPreloader};this.preloaderReady=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();this._loadImages();d=!0};this.soundLoaded=function(){b++;c.refreshLoader(Math.floor(b/e*100));if(b===e){c.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundtrack=createjs.Sound.play("soundtrack",{loop:-1});this.gotoMenu()}};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&(0<navigator.userAgent.indexOf("Opera")||0<
navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=["m4a"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/fr_soundtrack.ogg","soundtrack"),createjs.Sound.registerSound("./sounds/press_button.ogg","click"),createjs.Sound.registerSound("./sounds/fr_game_over.ogg","game_over"),createjs.Sound.registerSound("./sounds/fr_frog_arrived.ogg","frog_arrived"),createjs.Sound.registerSound("./sounds/fr_frog_death_road.ogg",
"splat"),createjs.Sound.registerSound("./sounds/fr_frog_death_water.ogg","drown"),createjs.Sound.registerSound("./sounds/fr_frog_jump.ogg","jump",5),createjs.Sound.registerSound("./sounds/fr_power_up.ogg","eat_fly"),createjs.Sound.registerSound("./sounds/fr_win_level.ogg","win_level"),createjs.Sound.registerSound("./sounds/fr_horn_1.ogg","big_hornet"),createjs.Sound.registerSound("./sounds/fr_horn_2.ogg","small_hornet")):(createjs.Sound.alternateExtensions=["ogg"],createjs.Sound.addEventListener("fileload",
createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/fr_soundtrack.m4a","soundtrack"),createjs.Sound.registerSound("./sounds/press_button.m4a","click"),createjs.Sound.registerSound("./sounds/fr_game_over.m4a","game_over"),createjs.Sound.registerSound("./sounds/fr_frog_arrived.m4a","frog_arrived"),createjs.Sound.registerSound("./sounds/fr_frog_death_road.m4a","splat"),createjs.Sound.registerSound("./sounds/fr_frog_death_water.m4a","drown"),createjs.Sound.registerSound("./sounds/fr_frog_jump.m4a",
"jump",5),createjs.Sound.registerSound("./sounds/fr_power_up.m4a","eat_fly"),createjs.Sound.registerSound("./sounds/fr_win_level.m4a","win_level"),createjs.Sound.registerSound("./sounds/fr_horn_1.m4a","big_hornet"),createjs.Sound.registerSound("./sounds/fr_horn_2.m4a","small_hornet")),e+=11)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");
s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.png");s_oSpriteLibrary.addSprite("gui_panel_bottom","./sprites/gui_panel_bottom.png");s_oSpriteLibrary.addSprite("gui_panel_top","./sprites/gui_panel_top.png");s_oSpriteLibrary.addSprite("life","./sprites/life.png");s_oSpriteLibrary.addSprite("time_bar_frame","./sprites/time_bar_frame.png");s_oSpriteLibrary.addSprite("time_bar_fill","./sprites/time_bar_fill.png");s_oSpriteLibrary.addSprite("bg_help",
"./sprites/bg_help.png");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("but_up","./sprites/but_up.png");s_oSpriteLibrary.addSprite("but_down","./sprites/but_down.png");s_oSpriteLibrary.addSprite("but_left","./sprites/but_left.png");s_oSpriteLibrary.addSprite("but_right","./sprites/but_right.png");s_oSpriteLibrary.addSprite("skid_rows","./sprites/skid_rows.png");for(var a,b=0;10>b;b++)a=
"water_anim_"+b,s_oSpriteLibrary.addSprite(a,"./sprites/"+a+".jpg");for(var d,b=1;11>b;b++)a="car_"+b,d="car_"+(b-1),s_oSpriteLibrary.addSprite(d,"./sprites/"+a+".png");s_oSpriteLibrary.addSprite("trunk","./sprites/trunk.png");s_oSpriteLibrary.addSprite("turtle","./sprites/turtle.png");s_oSpriteLibrary.addSprite("fly","./sprites/fly.png");s_oSpriteLibrary.addSprite("frog","./sprites/frog.png");e+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){b++;
c.refreshLoader(Math.floor(b/e*100));if(b===e){c.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundtrack=createjs.Sound.play("soundtrack",{loop:-1});this.gotoMenu()}};this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this.gotoMenu=function(){new CMenu;f=STATE_MENU};this.gotoGame=function(a){s_bEasyMode=a;h=new CGame(g);f=STATE_GAME;$(s_oMain).trigger("game_start")};this.gotoHelp=function(){new CHelp;f=STATE_HELP};this.stopUpdate=function(){d=
!1};this.startUpdate=function(){d=!0};this._update=function(a){if(!1!==d){var b=(new Date).getTime();s_iTimeElaps=b-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=b;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);f===STATE_GAME&&h.update();s_oStage.update(a)}};s_oMain=this;g=a;this.initContainer()}
var s_bMobile,s_bEasyMode,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oSoundTrack,s_oCanvas;
function CLevelPanel(a){var d,b,e,f,g,c;this._init=function(a){d=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));d.x=0;d.y=0;e=new createjs.Text("","bold 45px walibi","#000000");e.x=CANVAS_WIDTH/2+4;e.y=CANVAS_HEIGHT/2-100;e.textAlign="center";f=new createjs.Text("","bold 45px walibi","#fcff00");f.x=CANVAS_WIDTH/2;f.y=CANVAS_HEIGHT/2-104;f.textAlign="center";g=new createjs.Text("","bold 40px walibi","#000000");g.x=CANVAS_WIDTH/2+4;g.y=CANVAS_HEIGHT/2+4;g.textAlign="center";c=new createjs.Text("",
"bold 40px walibi","#fcff00");c.x=CANVAS_WIDTH/2;c.y=CANVAS_HEIGHT/2;c.textAlign="center";b=new createjs.Container;b.alpha=0;b.visible=!1;b.addChild(d,g,c,e,f);s_oStage.addChild(b)};this.unload=function(){b.off("mousedown",this._onExit)};this._initListener=function(){b.on("mousedown",this._onExit)};this.show=function(d){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("win_level");this._initListener();e.text=TEXT_LEVELEND+a+TEXT_COMPLETEEND;f.text=TEXT_LEVELEND+a+TEXT_COMPLETEEND;g.text=
TEXT_SCORE+" "+d;c.text=TEXT_SCORE+" "+d;b.visible=!0;createjs.Tween.get(b).to({alpha:1},500);$(s_oMain).trigger("save_score",d)};this._onExit=function(){b.off("mousedown",this._onExit);s_oStage.removeChild(b);s_oGame.reset()};this._init(a);return this}TEXT_GAMEOVER="GAME OVER";TEXT_SCORE="SCORE";TEXT_PLAY="PLAY";TEXT_RESTART="RESTART";TEXT_TIME="TIME";TEXT_SCORE="SCORE";TEXT_LEVELEND="LEVEL ";TEXT_COMPLETEEND=" COMPLETE";TEXT_SPLAT="SPLAT!";TEXT_DROWN="GLU GLU..";TEXT_CRASH="BONK!";TEXT_GREAT="GREAT!!";
TEXT_HELP1="USE ARROWS KEYS OR TAP ARROWS BUTTONS TO REACH THE OTHER SIDE OF THE RIVER BEFORE THE TIME EXPIRES. TO COMPLETE A LEVEL, YOU HAVE TO PUT A FROG ON EACH OF THE 5 COVES";TEXT_HELP2="DON\u2019T GET DRIVEN OVER BY CARS ALONG THE STREET";TEXT_HELP3="USE THE FLOATING TRUNKS OR TURTLE SHELLS TO CROSS THE RIVER";TEXT_HELP4="IF YOU CATCH A FLY, YOU GET EXTRA POINTS";TEXT_HELP_MOB1="TAP ARROWS BUTTONS TO REACH THE OTHER SIDE OF THE RIVER BEFORE THE TIME EXPIRES. TO COMPLETE A LEVEL, YOU HAVE TO PUT A FROG ON EACH OF THE 5 COVES";
function CInterface(){var a,d,b,e,f,g,c=null,h,m,k,l,n,r,p;this._init=function(){var c=s_oSpriteLibrary.getSprite("gui_panel_top"),t=createBitmap(c);s_oStage.addChild(t);c=s_oSpriteLibrary.getSprite("but_exit");d=new CGfxButton(CANVAS_WIDTH-c.height/2-5,c.height/2+5,c,!0);d.addEventListener(ON_MOUSE_UP,this._onExit,this);t=CANVAS_WIDTH-c.width/2-80;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)c=s_oSpriteLibrary.getSprite("audio_icon"),a=new CToggle(t,5+c.height/2,c,s_bAudioActive),a.addEventListener(ON_MOUSE_UP,
this._onAudioToggle,this);c=s_oSpriteLibrary.getSprite("life");t=createBitmap(c);t.x=14;t.y=14;s_oStage.addChild(t);p=new createjs.Text("X"+LIVES,"bold 40px walibi","#fcff00");p.x=70;p.y=48;p.textAlign="left";p.textBaseline="alphabetic";p.lineWidth=200;s_oStage.addChild(p);t=new createjs.Container;t.x=20;t.y=940;s_oStage.addChild(t);l=new createjs.Text(TEXT_TIME,"bold 40px walibi","#fcff00");l.x=10;l.y=0;l.textAlign="left";l.textBaseline="alphabetic";l.lineWidth=200;t.addChild(l);c=new createjs.Text(TEXT_TIME,
"bold 40px walibi","#000000");c.x=10;c.y=0;c.textAlign="left";c.textBaseline="alphabetic";c.lineWidth=200;c.outline=3;t.addChild(c);c=s_oSpriteLibrary.getSprite("time_bar_fill");n=createBitmap(c);n.x=10;n.y=18;t.addChild(n);r=new createjs.Shape;r.graphics.beginFill("rgba(255,0,0,0.01)").drawRect(0,0,c.width,c.height);r.x=10;r.y=18;t.addChild(r);n.mask=r;c=s_oSpriteLibrary.getSprite("time_bar_frame");c=createBitmap(c);c.x=7;c.y=15;t.addChild(c);h=new createjs.Text(TEXT_SCORE,"bold 40px walibi","#fcff00");
h.x=10;h.y=110;h.textAlign="left";h.textBaseline="alphabetic";h.lineWidth=200;t.addChild(h);c=new createjs.Text(TEXT_SCORE,"bold 40px walibi","#000000");c.x=10;c.y=110;c.textAlign="left";c.textBaseline="alphabetic";c.lineWidth=200;c.outline=3;t.addChild(c);m=new createjs.Text("0","bold 36px walibi","#fcff00");m.x=10;m.y=155;m.textAlign="left";m.textBaseline="alphabetic";m.lineWidth=200;t.addChild(m);k=new createjs.Text("0","bold 36px walibi","#000000");k.x=10;k.y=155;k.textAlign="left";k.textBaseline=
"alphabetic";k.lineWidth=200;k.outline=3;t.addChild(k);t=CANVAS_HEIGHT-190;c=s_oSpriteLibrary.getSprite("but_up");b=new CGfxButton(505,t-5,c,1.2,!0);b.addEventListener(ON_MOUSE_DOWN,this._onButUpPress,this);c=s_oSpriteLibrary.getSprite("but_down");e=new CGfxButton(505,t+135,c,1.2,!0);e.addEventListener(ON_MOUSE_DOWN,this._onButDownPress,this);c=s_oSpriteLibrary.getSprite("but_left");f=new CGfxButton(426,t+65,c,1.2,!0);f.addEventListener(ON_MOUSE_DOWN,this._onButLeftPress,this);c=s_oSpriteLibrary.getSprite("but_right");
g=new CGfxButton(582,t+65,c,1.2,!0);g.addEventListener(ON_MOUSE_DOWN,this._onButRightPress,this)};this.unload=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)a.unload(),a=null;d.unload();b.unload();e.unload();f.unload();g.unload()};this.refreshScore=function(a){m.text=a;k.text=a};this.refreshLives=function(a){p.text="X"+a};this.refreshBar=function(){r.scaleX=1;createjs.Tween.get(r,{override:!0}).to({scaleX:0},LEVEL_TIME,createjs.Ease.linear).call(function(){s_oGame.gameOver()})};this.stopBar=
function(){createjs.Tween.removeTweens(r)};this._onButUpPress=function(){s_oGame.onUpPress()};this._onButDownPress=function(){s_oGame.onDownPress()};this._onButLeftPress=function(){s_oGame.onLeftPress()};this._onButRightPress=function(){s_oGame.onRightPress()};this._onButHelpRelease=function(){c=new CHelpPanel};this._onButRestartRelease=function(){s_oGame.restartGame()};this.onExitFromHelp=function(){c.unload()};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=
!s_bAudioActive};this._onExit=function(){s_oGame.onExit()};this._init();return this};