TEXT_GAMEOVER="GAME OVER";TEXT_SCORE="SCORE";TEXT_LEVEL="LEVEL";TEXT_PLAY="PLAY";TEXT_HELP="MATCH ALL COLOURED FUNNY FACES TO CLEAR THE LEVEL!!!";
function CInterface(a,b){var d,e,f,g,c,m,l,k,n,h;this._init=function(a,b){var r=s_oSpriteLibrary.getSprite("but_exit");d=new CGfxButton(CANVAS_WIDTH-r.width/2-120,60,r,!0);d.addEventListener(ON_MOUSE_UP,this._onExit,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)e=new CToggle(CANVAS_WIDTH-60,60,s_oSpriteLibrary.getSprite("audio_icon")),e.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);f=new createjs.Text(TEXT_SCORE+": 0","bold 40px Arial","#000000");f.x=CANVAS_WIDTH-160;f.y=CANVAS_HEIGHT-
63;f.textAlign="center";s_oStage.addChild(f);g=new createjs.Text(TEXT_SCORE+": 0","bold 40px Arial","#ffffff");g.x=CANVAS_WIDTH-158;g.y=CANVAS_HEIGHT-65;g.textAlign="center";s_oStage.addChild(g);r=s_oSpriteLibrary.getSprite("life");m=createBitmap(r);m.x=10;m.y=CANVAS_HEIGHT-r.height-10;s_oStage.addChild(m);l=new createjs.Text("X"+b,"bold 40px Arial","#000000");l.x=m.x+r.width+7;l.y=CANVAS_HEIGHT-r.height+5;s_oStage.addChild(l);k=new createjs.Text("X"+b,"bold 40px Arial","#ffffff");k.x=m.x+r.width+
5;k.y=CANVAS_HEIGHT-r.height+3;s_oStage.addChild(k);n=new createjs.Text(TEXT_LEVEL+" "+a,"bold 40px Arial","#000000");n.x=122;n.y=42;n.textAlign="center";s_oStage.addChild(n);h=new createjs.Text(TEXT_LEVEL+" "+a,"bold 40px Arial","#ffffff");h.x=120;h.y=40;h.textAlign="center";s_oStage.addChild(h);c=new CEndPanel(s_oSpriteLibrary.getSprite("msg_box"))};this.unload=function(){d.unload();d=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)e.unload(),e=null;s_oStage.removeChild(h);s_oStage.removeChild(l);
s_oStage.removeChild(k);s_oStage.removeChild(m);s_oStage.removeChild(g);s_oStage.removeChild(f)};this.refreshScore=function(a){g.text=TEXT_SCORE+": "+a;f.text=TEXT_SCORE+": "+a};this.refreshLives=function(a){k.text="X"+a;l.text="X"+a};this.refreshLevel=function(a){h.text=TEXT_LEVEL+" "+a;n.text=TEXT_LEVEL+" "+a};this.gameOver=function(a){c.show(a)};this._onExit=function(){s_oGame.onExit()};this._onAudioToggle=function(){createjs.Sound.setMute(!s_bAudioActive)};this._init(a,b);return this}
function CHelpPanel(a){var b,d,e,f;this._init=function(a){e=createBitmap(a);d=new createjs.Text(TEXT_HELP,"bold 46px Arial","#000000");d.textAlign="center";d.lineWidth=550;d.x=CANVAS_WIDTH/2+2;d.y=312;b=new createjs.Text(TEXT_HELP,"bold 46px Arial","#ffffff");b.textAlign="center";b.lineWidth=550;b.x=CANVAS_WIDTH/2;b.y=310;f=new createjs.Container;f.addChild(e,d,b);s_oStage.addChild(f);var c=this;f.on("pressup",function(){c._onExitHelp()})};this.unload=function(){s_oStage.removeChild(f);var a=this;
f.off("pressup",function(){a._onExitHelp()})};this._onExitHelp=function(){this.unload()};this._init(a)}
function CGfxButton(a,b,d,e){var f,g,c;this._init=function(a,b,d,e){f=[];g=[];c=createBitmap(d);c.x=a;c.y=b;c.regX=d.width/2;c.regY=d.height/2;e&&s_oStage.addChild(c);this._initListener()};this.unload=function(){c.off("mousedown",this.buttonDown);c.off("pressup",this.buttonRelease);s_oStage.removeChild(c)};this.setVisible=function(a){c.visible=a};this._initListener=function(){c.on("mousedown",this.buttonDown);c.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){f[a]=b;g[a]=c};
this.buttonRelease=function(){c.scaleX=1;c.scaleY=1;f[ON_MOUSE_UP]&&f[ON_MOUSE_UP].call(g[ON_MOUSE_UP])};this.buttonDown=function(){c.scaleX=.9;c.scaleY=.9;f[ON_MOUSE_DOWN]&&f[ON_MOUSE_DOWN].call(g[ON_MOUSE_DOWN])};this.setPosition=function(a,b){c.x=a;c.y=b};this.setX=function(a){c.x=a};this.setY=function(a){c.y=a};this.getButtonImage=function(){return c};this.getX=function(){return c.x};this.getY=function(){return c.y};this._init(a,b,d,e);return this}
function CGame(a){var b,d,e=0,f,g,c,m,l,k,n,h,q=[],w,r,y,x,u,v,t;this._init=function(){this.createBoard()};this.unload=function(){s_oStage.removeChild(y);s_oStage.removeChild(x);for(var a=0;a<BOARD_ROWS;a++)for(var b=0;b<BOARD_COLS;b++)l[a][b].unload()};this.createBoard=function(){l=[];var a=BOARD_OFFSET_X,h=BOARD_OFFSET_Y;b=GAME_STATE_NO_MOVE;d=0;c=1;g=BOARD_ROWS*BOARD_COLS;m=2;f=NUM_LIVES;y=createBitmap(s_oSpriteLibrary.getSprite("game_bg"));s_oStage.addChild(y);x=new createjs.Shape;x.graphics.beginFill("rgba(0,0,0,0.5)").drawRoundRect(BOARD_OFFSET_X,
BOARD_OFFSET_Y,BOARD_COLS*ELEM_SIZE,BOARD_ROWS*ELEM_SIZE,10);s_oStage.addChild(x);var p,e={};for(p=0;p<NUM_COLORS;p++)e["elem_"+p]=[p,p+1];e.invisible=[NUM_COLORS,NUM_COLORS+1];p={images:[s_oSpriteLibrary.getSprite("elems")],frames:{width:ELEM_SIZE,height:ELEM_SIZE,regX:0,regY:0},animations:e};w=new createjs.SpriteSheet(p);for(p=0;p<BOARD_ROWS;p++){l[p]=[];for(e=0;e<BOARD_COLS;e++){var k=Math.floor(Math.random()*m);l[p][e]=new CBoardElem(p,e,a,h,k,w);a+=ELEM_SIZE}a=BOARD_OFFSET_X;h+=ELEM_SIZE}t=new CInterface(c,
NUM_LIVES);u=new createjs.Shape;u.graphics.beginFill("red").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);u.alpha=0;s_oStage.addChild(u);new CHelpPanel(s_oSpriteLibrary.getSprite("bg_help"))};this.initNextLevel=function(){b=GAME_STATE_NO_MOVE;g=BOARD_ROWS*BOARD_COLS;m<NUM_COLORS&&m++;for(var a=0;a<BOARD_ROWS;a++)for(var e=0;e<BOARD_COLS;e++){var d=Math.floor(Math.random()*m);l[a][e].reset(d)}t.refreshLevel(c)};this._findSimilarAdjacent=function(a,b,c,g,e){var d=a,f=b;do{switch(c){case 0:d=a-1;c++;if(0>
d)continue;break;case 1:d=a+1;c++;if(d>=BOARD_ROWS)continue;break;case 2:d=a;f=b-1;c++;if(0>f)continue;break;case 3:if(d=a,f=b+1,c++,f>=BOARD_COLS)continue}l[d][f].getType()===g&&!1===this.findElemInArray(l[d][f],e)&&(e.push(l[d][f]),this._findSimilarAdjacent(d,f,0,g,e))}while(4>c)};this.elemClicked=function(a,c,e){if(b===GAME_STATE_NO_MOVE){!1===s_bMobile&&this.elemOut();k=[];this._findSimilarAdjacent(a,c,0,e,k);if(1<k.length)d+=SCORE_PER_ELEM*k.length*k.length,t.refreshScore(d),!1!==DISABLE_SOUND_MOBILE&&
!1!==s_bMobile||createjs.Sound.play("matching");else{f--;t.refreshLives(f);if(0===f){this.gameOver();return}this.showHurt();k.push(l[a][c])}for(a=0;a<k.length;a++)k[a].remove(),g--;this.compactGridVertically();this.moveElemsDown()}};this.elemOver=function(a,c,g){if(b===GAME_STATE_NO_MOVE)for(n=[],this._findSimilarAdjacent(a,c,0,g,n),a=0;a<n.length;a++)n[a].highlight(!0)};this.elemOut=function(){for(var a=0;a<n.length;a++)n[a].highlight(!1)};this.findElemInArray=function(a,b){for(var c=0;c<b.length;c++)if(b[c]===
a)return!0;return!1};this.compactGridVertically=function(){var a=[];h=[];q=[];for(var b=BOARD_ROWS-1;-1<b;b--)for(var c=0;c<BOARD_COLS;c++)-1===l[b][c].getType()&&!1===this.findElemInArray(c,a)&&(this.findElemsToMoveVertically(b,c),a.push(c))};this.findElemsToMoveVertically=function(a,b){for(var c=a,g=0;-1<c;)-1!==l[c][b].getType()?h.push({row:c,col:b,type:l[c][b].getType(),dist:g}):g+=ELEM_SIZE,c--};this.moveElemsDown=function(){if(0<h.length){b=GAME_STATE_MOVE_VERTICAL;e=h.length;for(var a=0;a<
h.length;a++){var c=BOARD_OFFSET_Y+h[a].row*ELEM_SIZE,g=new CMovingElem(BOARD_OFFSET_X+h[a].col*ELEM_SIZE,c,h[a].type,w);q.push(g);c+=h[a].dist;l[h[a].row][h[a].col].hide();g.moveDown(c,Math.floor((c-BOARD_OFFSET_Y)/ELEM_SIZE),h[a].col)}}else b=GAME_STATE_NO_MOVE,q=[],this.compactGridHorizontally(),this.moveElemRight()};this.compactGridHorizontally=function(){h=[];for(var a=BOARD_COLS-1;-1<a;a--){for(var c=!0,g=0;g<BOARD_ROWS;g++)if(-1!==l[g][a].getType()){c=!1;break}c&&(b=GAME_STATE_MOVE_HORIZONTAL,
this.findElemsToMoveHorizontally(a))}};this.findElemsToMoveHorizontally=function(a){for(var b=0;b<BOARD_ROWS;b++)for(var c=0;c<a;c++)if(-1!==l[b][c].getType()){var g=this.checkElemToMove(b,c);-1<g?h[g].dist+=ELEM_SIZE:h.push({row:b,col:c,type:l[b][c].getType(),dist:ELEM_SIZE})}};this.checkElemToMove=function(a,b){for(var c=0;c<h.length;c++)if(h[c].row===a&&h[c].col===b)return c;return-1};this.moveElemRight=function(){if(0===h.length)b=GAME_STATE_NO_MOVE,q=[],0===g&&this.showNextLevel();else{e=h.length;
for(var a=0;a<h.length;a++){var c=BOARD_OFFSET_X+h[a].col*ELEM_SIZE,d=new CMovingElem(c,BOARD_OFFSET_Y+h[a].row*ELEM_SIZE,h[a].type,w);q.push(d);c+=h[a].dist;l[h[a].row][h[a].col].hide();d.moveSide(c,h[a].row,Math.floor((c-BOARD_OFFSET_X)/ELEM_SIZE))}}};this.updateElemValue=function(a,c,d,f){l[a][c].updateType(d);s_oStage.removeChild(f);e--;0===e&&(q=[],b===GAME_STATE_MOVE_VERTICAL?(b=GAME_STATE_NO_MOVE,this.compactGridHorizontally(),this.moveElemRight()):b===GAME_STATE_MOVE_HORIZONTAL&&(b=GAME_STATE_NO_MOVE,
0===g&&this.showNextLevel()))};this.gameOver=function(){r=CEndPanel(s_oSpriteLibrary.getSprite("msg_box"));r.show(d)};this.showNextLevel=function(){c++;v=new CNextLevelPanel(s_oSpriteLibrary.getSprite("msg_box"));v.show(c)};this.showHurt=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("life_lost");createjs.Tween.get(u).to({alpha:.5},300).call(function(){this.alpha=0})};this.onExit=function(){t.unload();this.unload();s_oMain.gotoMenu();$(s_oMain).trigger("restart")};this.update=
function(){for(var a=0;a<q.length;a++)q[a].update(SPEED_MOVE)};s_oGame=this;BOARD_COLS=a.col;BOARD_ROWS=a.row;SCORE_PER_ELEM=a.score_per_elem;SPEED_MOVE=a.speed_move;NUM_LIVES=a.num_lives;this._init()}var s_oGame;
function CEndPanel(a){var b,d,e,f,g,c;this._init=function(a){b=createBitmap(a);g=new createjs.Text("","bold 70px Arial","#000");g.x=CANVAS_WIDTH/2+2;g.y=CANVAS_HEIGHT/2-78;g.textAlign="center";f=new createjs.Text("","bold 70px Arial","#ffffff");f.x=CANVAS_WIDTH/2;f.y=CANVAS_HEIGHT/2-80;f.textAlign="center";d=new createjs.Text("","bold 44px Arial","#000");d.x=CANVAS_WIDTH/2+1;d.y=CANVAS_HEIGHT/2+32;d.textAlign="center";e=new createjs.Text("","bold 44px Arial","#ffffff");e.x=CANVAS_WIDTH/2;e.y=CANVAS_HEIGHT/
2+30;e.textAlign="center";c=new createjs.Container;c.alpha=0;c.visible=!1;c.addChild(b,d,e,g,f);s_oStage.addChild(c)};this._initListener=function(){c.on("mousedown",this._onExit)};this.show=function(a){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundTrackSnd.volume=0,createjs.Sound.play("gameover").addEventListener("complete",createjs.proxy(function(){s_oSoundTrackSnd.volume=.5},this));g.text=TEXT_GAMEOVER;f.text=TEXT_GAMEOVER;d.text=TEXT_SCORE+": "+a;e.text=TEXT_SCORE+": "+a;c.visible=!0;var b=
this;createjs.Tween.get(c).to({alpha:1},500).call(function(){b._initListener()});$(s_oMain).trigger("save_score",a)};this._onExit=function(){c.off("mousedown");s_oStage.removeChild(c);s_oGame.onExit()};this._init(a);return this}
function CBoardElem(a,b,d,e,f,g){var c,m,l,k,n,h;this._init=function(a,b,g,d,e,f){l=e;c=a;m=b;k=createSprite(f,"elem_"+e,0,0,ELEM_SIZE,ELEM_SIZE);k.stop();k.x=g;k.y=d;n=createBitmap(s_oSpriteLibrary.getSprite("highlight"));n.x=g;n.y=d;n.visible=!1;h=new createjs.Container;h.addChild(k,n);s_oStage.addChild(h);h.on("pressup",this._onElemClick);!1===s_bMobile&&(h.on("mouseover",this._onElemOver),h.on("mouseout",this._onElemOut))};this.unload=function(){h.off("pressup",this._onElemClick);!1===s_bMobile&&
(h.off("mouseover",this._onElemOver),h.off("mouseout",this._onElemOut));s_oStage.removeChild(h)};this.reset=function(a){l=a;k.gotoAndStop("elem_"+a);k.alpha=1;k.visible=!0};this.hide=function(){k.visible=!1;l=-1};this.remove=function(){k.alpha=0;l=-1};this.highlight=function(a){n.visible=a};this.updateType=function(a){l=a;k.gotoAndStop("elem_"+a);k.alpha=1;k.visible=!0};this._onElemClick=function(){s_oGame.elemClicked(c,m,l)};this._onElemOver=function(){s_oGame.elemOver(c,m,l)};this._onElemOut=function(){s_oGame.elemOut(c,
m,l)};this.getPos=function(){return{row:c,col:m}};this.getRow=function(){return c};this.getCol=function(){return m};this.getType=function(){return l};this._init(a,b,d,e,f,g);return this}
function CSpriteLibrary(){var a,b,d,e,f,g;this.init=function(c,m,l){d=b=0;e=c;f=m;g=l;a={}};this.addSprite=function(c,g){a.hasOwnProperty(c)||(a[c]={szPath:g,oSprite:new Image},b++)};this.getSprite=function(c){return a.hasOwnProperty(c)?a[c].oSprite:null};this._onSpritesLoaded=function(){f.call(g)};this._onSpriteLoaded=function(){e.call(g);++d==b&&this._onSpritesLoaded()};this.loadSprites=function(){for(var c in a)a[c].oSprite.oSpriteLibrary=this,a[c].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
a[c].oSprite.src=a[c].szPath};this.getNumSprites=function(){return b}}var CANVAS_WIDTH=768,CANVAS_HEIGHT=1024,FPS_TIME=1E3/24,DISABLE_SOUND_MOBILE=!0,STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,BOARD_COLS,BOARD_ROWS,ELEM_SIZE=88,NUM_COLORS=6,SCORE_PER_ELEM,SPEED_MOVE,NUM_LIVES,GAME_STATE_NO_MOVE=0,GAME_STATE_MOVE_VERTICAL=1,GAME_STATE_MOVE_HORIZONTAL=2,BOARD_OFFSET_X=40,BOARD_OFFSET_Y=130;
function CTweenController(a){var b=0,d=a.oNode.getX(),e=a.oNode.getY(),f=!1;this.tweenValue=function(a,c,b){return a+b*(c-a)};this.start=function(){f=!0};this.easeLinear=function(a,c,b,d){return b*a/d+c};this.easeInCubic=function(a,c,b,d){d=(a/=d)*a*a;return c+b*d};this.easeBackInQuart=function(a,b,d,e){e=(a/=e)*a;return b+d*(2*e*e+2*e*a+-3*e)};this.updateDown=function(){if(!1===f)return!1;var d;b+=s_iTimeElaps;b>=a.iDuration&&(b=a.iDuration,f=!1);d=this.easeInCubic(b,0,1,a.iDuration);a.oNode.setY(this.tweenValue(e,
a.iFinalY,d));return!0};this.updateRight=function(){if(!1===f)return!1;var e;b+=s_iTimeElaps;b>=a.iDuration&&(b=a.iDuration,f=!1);e=this.easeInCubic(b,0,1,a.iDuration);a.oNode.setX(this.tweenValue(d,a.iFinalX,e));return!0}}
function CToggle(a,b,d){var e,f,g;this._init=function(a,b,d){e=[];f=[];var k=new createjs.SpriteSheet({images:[d],frames:{width:d.width/2,height:d.height,regX:d.width/2/2,regY:d.height/2},animations:{on:[0,1],off:[1,2]}});g=s_bAudioActive?createSprite(k,"on",d.width/2/2,d.height/2,d.width/2,d.height):createSprite(k,"off",d.width/2/2,d.height/2,d.width/2,d.height);g.x=a;g.y=b;g.stop();s_oStage.addChild(g);this._initListener()};this.unload=function(){g.off("mousedown",this.buttonDown);g.off("pressup",
this.buttonRelease);s_oStage.removeChild(g)};this._initListener=function(){g.on("mousedown",this.buttonDown);g.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,d){e[a]=b;f[a]=d};this.buttonRelease=function(){g.scaleX=1;g.scaleY=1;(s_bAudioActive=!s_bAudioActive)?g.gotoAndStop("on"):g.gotoAndStop("off");e[ON_MOUSE_UP]&&e[ON_MOUSE_UP].call(f[ON_MOUSE_UP])};this.buttonDown=function(){g.scaleX=.9;g.scaleY=.9;e[ON_MOUSE_DOWN]&&e[ON_MOUSE_DOWN].call(f[ON_MOUSE_DOWN])};this._init(a,b,
d)}
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,4))})(navigator.userAgent||
navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}$(window).ready(function(){sizeHandler()});window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a=CANVAS_WIDTH,b=CANVAS_HEIGHT,d=window.innerWidth;multiplier=Math.min(window.innerHeight/b,d/a);a*=multiplier;b*=multiplier;$("#canvas").css("width",a+"px");$("#canvas").css("height",b+"px");$("#canvas").css("left",d/2-a/2+"px")}}
function createBitmap(a,b,d){var e=new createjs.Bitmap(a),f=new createjs.Shape;b&&d?f.graphics.beginFill("#fff").drawRect(0,0,b,d):f.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);e.hitArea=f;return e}function createSprite(a,b,d,e,f,g){a=null!==b?new createjs.Sprite(a,b):new createjs.Sprite(a);b=new createjs.Shape;b.graphics.beginFill("#000000").drawRect(-d,-e,f,g);a.hitArea=b;return a}
function randomFloatBetween(a,b,d){"undefined"===typeof d&&(d=2);return parseFloat(Math.min(a+Math.random()*(b-a),b).toFixed(d))}function shuffle(a){for(var b=a.length,d,e;0!==b;)e=Math.floor(Math.random()*b),--b,d=a[b],a[b]=a[e],a[e]=d;return a}function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3==a.nodeType&&(a=a.parentNode);var b=document.createEvent("MouseEvents");b.initEvent("click",!0,!0);a.dispatchEvent(b)}}};
function CTextButton(a,b,d,e,f,g,c){var m,l,k;this._init=function(a,b,c,d,e,g,f){m=[];l=[];var u=createBitmap(c),v=Math.ceil(f/20),t=new createjs.Text(d,"bold "+f+"px "+e,"#000000");t.textAlign="center";var z=t.getBounds();t.x=c.width/2+v;t.y=(c.height-z.height)/2+v;d=new createjs.Text(d,"bold "+f+"px "+e,g);d.textAlign="center";z=d.getBounds();d.x=c.width/2;d.y=(c.height-z.height)/2;k=new createjs.Container;k.x=a;k.y=b;k.regX=c.width/2;k.regY=c.height/2;k.addChild(u,t,d);s_oStage.addChild(k);this._initListener()};
this.unload=function(){k.off("mousedown");k.off("pressup")};this.setVisible=function(a){k.visible=a};this._initListener=function(){oParent=this;k.on("mousedown",this.buttonDown);k.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){m[a]=b;l[a]=c};this.buttonRelease=function(){k.scaleX=1;k.scaleY=1;m[ON_MOUSE_UP]&&m[ON_MOUSE_UP].call(l[ON_MOUSE_UP])};this.buttonDown=function(){k.scaleX=.9;k.scaleY=.9;m[ON_MOUSE_DOWN]&&m[ON_MOUSE_DOWN].call(l[ON_MOUSE_DOWN])};this.setPosition=function(a,
b){k.x=a;k.y=b};this.setX=function(a){k.x=a};this.setY=function(a){k.y=a};this.getButtonImage=function(){return k};this.getX=function(){return k.x};this.getY=function(){return k.y};this._init(a,b,d,e,f,g,c);return this}
function CPreloader(){var a;this._init=function(){this._onAllPreloaderImagesLoaded()};this._onPreloaderImagesLoaded=function(){};this._onAllPreloaderImagesLoaded=function(){a=new createjs.Text("","bold 44px Arial center","#ffffff");a.x=CANVAS_WIDTH/2-40;a.y=CANVAS_HEIGHT/2;s_oStage.addChild(a)};this.unload=function(){s_oStage.removeChild(a)};this.refreshLoader=function(b){a.text=b+"%"};this._init()}
function CNextLevelPanel(a){var b,d,e,f;this._init=function(a){d=createBitmap(a);f=new createjs.Text("","bold 70px Arial","#000000");f.x=CANVAS_WIDTH/2+2;f.y=CANVAS_HEIGHT/2-28;f.textAlign="center";e=new createjs.Text("","bold 70px Arial","#ffffff");e.x=CANVAS_WIDTH/2;e.y=CANVAS_HEIGHT/2-30;e.textAlign="center";b=new createjs.Container;b.alpha=0;b.visible=!1;b.addChild(d,f,e);s_oStage.addChild(b);b.on("mousedown",this._onExit)};this.show=function(a){f.text=TEXT_LEVEL+" "+a;e.text=TEXT_LEVEL+" "+a;
b.visible=!0;createjs.Tween.get(b).to({alpha:1},500).call(function(){s_oGame.initNextLevel()})};this._onExit=function(){b.off("mousedown",this._onExit);s_oStage.removeChild(b)};this._init(a)}
function CMovingElem(a,b,d,e){var f,g,c,m,l,k,n,h,q=null;this._init=function(a,b,d,e){g=f=!1;c=a;m=b;l=d;h=createSprite(e,"elem_"+d,0,0,ELEM_SIZE,ELEM_SIZE);h.stop();h.x=a;h.y=b;s_oStage.addChild(h)};this.moveDown=function(a,b,c){m=a;k=b;n=c;this.initTween(h.x,m);f=!0};this.moveSide=function(a,b,d){c=a;k=b;n=d;this.initTween(a,h.y);g=!0};this.initTween=function(a,b){q=new CTweenController({oNode:this,iFinalX:a,iFinalY:b,iDuration:SPEED_MOVE});q.start()};this.setY=function(a){h.y=a};this.setX=function(a){h.x=
a};this.getX=function(){return h.x};this.getY=function(){return h.y};this.update=function(a){f&&!1===q.updateDown()&&(f=!1,h.y=m,s_oGame.updateElemValue(k,n,l,h));g&&!1===q.updateRight()&&(g=!1,h.x=c,s_oGame.updateElemValue(k,n,l,h))};this._init(a,b,d,e)}
function CMenu(){var a,b,d,e;this._init=function(){a=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(a);var f=s_oSpriteLibrary.getSprite("but_play");b=new CTextButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-100,f,TEXT_PLAY,"Arial","#ffffff",44);b.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)d=new CToggle(CANVAS_WIDTH-60,60,s_oSpriteLibrary.getSprite("audio_icon")),d.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);e=new createjs.Shape;
e.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(e);createjs.Tween.get(e).to({alpha:0},1E3).call(function(){e.visible=!1})};this.unload=function(){b.unload();b=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)d.unload(),d=null;s_oStage.removeChild(a);a=null};this._onButPlayRelease=function(){this.unload();s_oMain.gotoGame()};this._onAudioToggle=function(){createjs.Sound.setMute(!s_bAudioActive)};this._init()}
function CMain(a){var b=0,d=0,e=STATE_LOADING,f,g,c;this.initContainer=function(){var a=document.getElementById("canvas");s_oStage=new createjs.Stage(a);createjs.Touch.enable(s_oStage);s_iPrevTime=(new Date).getTime();s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&s_oStage.enableMouseOver(20);createjs.Ticker.addEventListener("tick",this._update);navigator.userAgent.match(/Windows Phone/i)&&(DISABLE_SOUND_MOBILE=!0);s_oSpriteLibrary=new CSpriteLibrary;g=new CPreloader;!1!==DISABLE_SOUND_MOBILE&&!1!==
s_bMobile||this._initSounds();this._loadImages()};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&(0<navigator.userAgent.indexOf("Opera")||0<navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=["mp3"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.handleFileLoad,this)),createjs.Sound.registerSound("./sounds/gameover.ogg","gameover"),createjs.Sound.registerSound("./sounds/soundtrack.ogg","soundtrack"),createjs.Sound.registerSound("./sounds/matching.ogg",
"matching"),createjs.Sound.registerSound("./sounds/life_lost.ogg","life_lost")):(createjs.Sound.alternateExtensions=["ogg"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.handleFileLoad,this)),createjs.Sound.registerSound("./sounds/gameover.mp3","gameover"),createjs.Sound.registerSound("./sounds/soundtrack.mp3","soundtrack"),createjs.Sound.registerSound("./sounds/matching.mp3","matching"),createjs.Sound.registerSound("./sounds/life_lost.mp3","life_lost")),d+=4)};this.handleFileLoad=
function(){b++;if(b===d){g.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundTrackSnd=createjs.Sound.play("soundtrack",{interrupt:createjs.Sound.INTERRUPT_ANY,loop:-1,volume:.5});this.gotoMenu()}};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("game_bg",
"./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("bg_help","./sprites/bg_help.png");s_oSpriteLibrary.addSprite("elems","./sprites/elems.png");s_oSpriteLibrary.addSprite("life","./sprites/life.png");s_oSpriteLibrary.addSprite("highlight","./sprites/highlight.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");d+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){b++;
g.refreshLoader(Math.floor(b/d*100));if(b===d){g.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundTrackSnd=createjs.Sound.play("soundtrack",{interrupt:createjs.Sound.INTERRUPT_ANY,loop:-1,volume:.5});this.gotoMenu()}};this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this.gotoMenu=function(){new CMenu;e=STATE_MENU};this.gotoGame=function(){c=new CGame(f);e=STATE_GAME;$(s_oMain).trigger("game_start")};this.gotoHelp=function(){new CHelp;
e=STATE_HELP};this._update=function(a){var b=(new Date).getTime();s_iTimeElaps=b-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=b;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);e===STATE_GAME&&c.update();s_oStage.update(a)};s_oMain=this;f=a;this.initContainer()}var s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_bMobile,s_bAudioActive=!0,s_oSoundTrackSnd,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary;