function CSpriteLibrary(){var a,g,b,f,h,d;this.init=function(k,m,c){b=g=0;f=k;h=m;d=c;a={}};this.addSprite=function(b,d){a.hasOwnProperty(b)||(a[b]={szPath:d,oSprite:new Image},g++)};this.getSprite=function(b){return a.hasOwnProperty(b)?a[b].oSprite:null};this._onSpritesLoaded=function(){h.call(d)};this._onSpriteLoaded=function(){f.call(d);++b==g&&this._onSpritesLoaded()};this.loadSprites=function(){for(var b in a)a[b].oSprite.oSpriteLibrary=this,a[b].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
a[b].oSprite.src=a[b].szPath};this.getNumSprites=function(){return g}}
var CANVAS_WIDTH=768,CANVAS_HEIGHT=1024,DISABLE_SOUND_MOBILE=!0,FPS_TIME=1E3/24,STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,HERO_START_X=CANVAS_WIDTH/2,HERO_ACCELLERATION,HERO_FRICTION,MAX_HERO_SPEED,START_Y_FALLING_OBJ=-50,TIME_OCCURENCE_FALLING_OBJ,SPEED_FALLING_OBJ,MAX_SPEED_FALLING_OBJ,NUM_FALLING_OBJ=4,NUM_LIVES,SPEED_PLAYER_BULLET,SCORE_HIT,PARALLAX1_SPEED=1,PARALLAX2_SPEED=10,MIN_SHOT_OCCURENCE,
MAX_SHOT_OCCURENCE;
function CToggle(a,g,b,f){var h,d,k,m;this._init=function(c,a,b,f){d=[];k=[];b=new createjs.SpriteSheet({images:[b],frames:{width:b.width/2,height:b.height,regX:b.width/2/2,regY:b.height/2},animations:{state_true:[0],state_false:[1]}});h=f;m=new createjs.Sprite(b,"state_"+h);m.x=c;m.y=a;m.stop();s_oStage.addChild(m);this._initListener()};this.unload=function(){m.off("mousedown",this.buttonDown);m.off("pressup",this.buttonRelease);s_oStage.removeChild(m)};this._initListener=function(){m.on("mousedown",this.buttonDown);
m.on("pressup",this.buttonRelease)};this.addEventListener=function(c,b,a){d[c]=b;k[c]=a};this.setActive=function(c){h=c;m.gotoAndStop("state_"+h)};this.buttonRelease=function(){m.scaleX=1;m.scaleY=1;!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");h=!h;m.gotoAndStop("state_"+h);d[ON_MOUSE_UP]&&d[ON_MOUSE_UP].call(k[ON_MOUSE_UP],h)};this.buttonDown=function(){m.scaleX=.9;m.scaleY=.9;d[ON_MOUSE_DOWN]&&d[ON_MOUSE_DOWN].call(k[ON_MOUSE_DOWN])};this._init(a,g,b,f)}
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,
4))})(navigator.userAgent||navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}$(window).ready(function(){sizeHandler()});window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}

function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a=CANVAS_WIDTH,b=CANVAS_HEIGHT,c,d;!0===inIframe()&&"ios"==getMobileOperatingSystem()?top.location.href=document.location.href:(c=window.innerWidth,d=window.innerHeight,console.log("h: "+d),multiplier=Math.min(d/b,c/a),a*=multiplier,b*=multiplier,$("#canvas").css("width",a+"px"),$("#canvas").css("height",b+"px"),$("#canvas").css("left",c/2-a/2+"px"))}}
function getMobileOperatingSystem(){var a=navigator.userAgent||navigator.vendor||window.opera;return a.match(/iPad/i)||a.match(/iPhone/i)||a.match(/iPod/i)?"ios":a.match(/Android/i)?"android":"unknown"}function inIframe(){try{return window.self!==window.top}catch(a){return!0}};

function randomFloatBetween(a,g,b){"undefined"===typeof b&&(b=2);return parseFloat(Math.min(a+Math.random()*(g-a),g).toFixed(b))}
function shuffle(a){for(var g=a.length,b,f;0!==g;)f=Math.floor(Math.random()*g),g-=1,b=a[g],a[g]=a[f],a[f]=b;return a}function formatTime(a){a/=1E3;var g=Math.floor(a/60);a=parseFloat(a-60*g).toFixed(1);var b="",b=10>g?b+("0"+g+":"):b+(g+":");return b=10>a?b+("0"+a):b+a}function degreesToRadians(a){return a*Math.PI/180}function checkRectCollision(a,g){var b,f;b=getBounds(a,.9);f=getBounds(g,.98);return calculateIntersection(b,f)}
function calculateIntersection(a,g){var b,f,h,d,k,m,c,l;b=a.x+(h=a.width/2);f=a.y+(d=a.height/2);k=g.x+(m=g.width/2);c=g.y+(l=g.height/2);b=Math.abs(b-k)-(h+m);f=Math.abs(f-c)-(d+l);return 0>b&&0>f?(b=Math.min(Math.min(a.width,g.width),-b),f=Math.min(Math.min(a.height,g.height),-f),{x:Math.max(a.x,g.x),y:Math.max(a.y,g.y),width:b,height:f,rect1:a,rect2:g}):null}
function getBounds(a,g){var b={x:Infinity,y:Infinity,width:0,height:0};if(a instanceof createjs.Container){b.x2=-Infinity;b.y2=-Infinity;var f=a.children,h=f.length,d,k;for(k=0;k<h;k++)d=getBounds(f[k],1),d.x<b.x&&(b.x=d.x),d.y<b.y&&(b.y=d.y),d.x+d.width>b.x2&&(b.x2=d.x+d.width),d.y+d.height>b.y2&&(b.y2=d.y+d.height);Infinity==b.x&&(b.x=0);Infinity==b.y&&(b.y=0);Infinity==b.x2&&(b.x2=0);Infinity==b.y2&&(b.y2=0);b.width=b.x2-b.x;b.height=b.y2-b.y;delete b.x2;delete b.y2}else{var m,c;a instanceof createjs.Bitmap?
(h=a.sourceRect||a.image,k=h.width*g,m=h.height*g):a instanceof createjs.Sprite?a.spriteSheet._frames&&a.spriteSheet._frames[a.currentFrame]&&a.spriteSheet._frames[a.currentFrame].image?(h=a.spriteSheet.getFrame(a.currentFrame),k=h.rect.width,m=h.rect.height,f=h.regX,c=h.regY):(b.x=a.x||0,b.y=a.y||0):(b.x=a.x||0,b.y=a.y||0);f=f||0;k=k||0;c=c||0;m=m||0;b.regX=f;b.regY=c;h=a.localToGlobal(0-f,0-c);d=a.localToGlobal(k-f,m-c);k=a.localToGlobal(k-f,0-c);f=a.localToGlobal(0-f,m-c);b.x=Math.min(Math.min(Math.min(h.x,
d.x),k.x),f.x);b.y=Math.min(Math.min(Math.min(h.y,d.y),k.y),f.y);b.width=Math.max(Math.max(Math.max(h.x,d.x),k.x),f.x)-b.x;b.height=Math.max(Math.max(Math.max(h.y,d.y),k.y),f.y)-b.y}return b}function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3==a.nodeType&&(a=a.parentNode);var g=document.createEvent("MouseEvents");g.initEvent("click",!0,!0);a.dispatchEvent(g)}}};
(function(){function a(b){var a={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};b=b||window.event;b.type in a?document.body.className=a[b.type]:(document.body.className=this[g]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var g="hidden";g in document?document.addEventListener("visibilitychange",a):(g="mozHidden")in document?document.addEventListener("mozvisibilitychange",a):(g="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",a):(g="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a})();
function CTextButton(a,g,b,f,h,d,k){var m,c,l;this._init=function(b,a,e,q,d,f,k){m=[];c=[];var h=new createjs.Bitmap(e),g=Math.ceil(k/20),r=new createjs.Text(q,"bold "+k+"px "+d,"#000000");r.textAlign="center";r.textBaseline="alphabetic";var v=r.getBounds();r.x=e.width/2+g;r.y=Math.floor(e.height/2)+v.height/3+g;q=new createjs.Text(q,"bold "+k+"px "+d,f);q.textAlign="center";q.textBaseline="alphabetic";v=q.getBounds();q.x=e.width/2;q.y=Math.floor(e.height/2)+v.height/3;l=new createjs.Container;l.x=
b;l.y=a;l.regX=e.width/2;l.regY=e.height/2;l.addChild(h,r,q);s_oStage.addChild(l);this._initListener()};this.unload=function(){l.off("mousedown");l.off("pressup");s_oStage.removeChild(l)};this.setVisible=function(c){l.visible=c};this._initListener=function(){oParent=this;l.on("mousedown",this.buttonDown);l.on("pressup",this.buttonRelease)};this.addEventListener=function(b,a,e){m[b]=a;c[b]=e};this.buttonRelease=function(){l.scaleX=1;l.scaleY=1;m[ON_MOUSE_UP]&&m[ON_MOUSE_UP].call(c[ON_MOUSE_UP])};this.buttonDown=
function(){l.scaleX=.9;l.scaleY=.9;m[ON_MOUSE_DOWN]&&m[ON_MOUSE_DOWN].call(c[ON_MOUSE_DOWN])};this.setPosition=function(c,b){l.x=c;l.y=b};this.setX=function(c){l.x=c};this.setY=function(c){l.y=c};this.getButtonImage=function(){return l};this.getX=function(){return l.x};this.getY=function(){return l.y};this._init(a,g,b,f,h,d,k);return this}
function CScrollingMultipleBg(a){var g,b,f;this._init=function(a){b=[];var d=-a[0].height;f=a[0].height;for(var k=0;d<2*CANVAS_HEIGHT;){var m=new createjs.Bitmap(a[k]);m.y=d;d+=f;b.push(m);s_oStage.addChild(m);k++}g=0};this.update=function(a){for(var d=0;d<b.length;d++)b[d].y>CANVAS_HEIGHT&&(b[d].y=b[g].y-f,g=d),b[d].y+=a,b[d].visible=b[d].y>-f&&b[d].y<CANVAS_HEIGHT?!0:!1};this._init(a)}
function CScrollingBg(a){var g,b,f;this._init=function(a){f=a;b=[];for(var d=-a.height;d<CANVAS_HEIGHT;){var k=new createjs.Bitmap(a);k.y=d;d+=a.height;b.push(k);s_oStage.addChild(k)}g=0};this.update=function(a){for(var d=0;d<b.length;d++)b[d].y>CANVAS_HEIGHT&&(b[d].y=b[g].y-f.height,g=d),b[d].y+=a};this._init(a)}
function CPreloader(){var a;this._init=function(){this._onAllPreloaderImagesLoaded()};this._onPreloaderImagesLoaded=function(){};this._onAllPreloaderImagesLoaded=function(){a=new createjs.Text("","bold 22px Arial center","#ffffff");a.x=CANVAS_WIDTH/2-40;a.y=CANVAS_HEIGHT/2;s_oStage.addChild(a)};this.unload=function(){s_oStage.removeChild(a)};this.refreshLoader=function(g){a.text=g+"%"};this._init()}
function CMenu(){var a,g,b,f;this._init=function(){a=new createjs.Bitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(a);var h=s_oSpriteLibrary.getSprite("but_play");g=new CTextButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-80,h,TEXT_PLAY,"space_marinenominal","#ffffff",40);g.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)h=s_oSpriteLibrary.getSprite("audio_icon"),f=new CToggle(CANVAS_WIDTH-h.height/2-10,h.height/2+10,h,s_bAudioActive),f.addEventListener(ON_MOUSE_UP,
this._onAudioToggle,this);b=new createjs.Shape;b.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(b);createjs.Tween.get(b).to({alpha:0},1E3).call(function(){b.visible=!1})};this.unload=function(){g.unload();g=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)f.unload(),f=null;s_oStage.removeChild(a);a=null};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onButPlayRelease=function(){this.unload();!1!==
DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");s_oMain.gotoGame()};this._init()}
function CMain(a){var g,b=0,f=0,h=STATE_LOADING,d,k,m;this.initContainer=function(){var c=document.getElementById("canvas");s_oStage=new createjs.Stage(c);createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&(s_oStage.enableMouseOver(20),$("body").on("contextmenu","#canvas",function(c){return!1}));s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.setFPS(30);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();
s_oSpriteLibrary=new CSpriteLibrary;k=new CPreloader;this._loadImages();g=!0};this.soundLoaded=function(){b++;if(b===f){k.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundtrack=createjs.Sound.play("soundtrack",{loop:100});this.gotoMenu()}};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&(0<navigator.userAgent.indexOf("Opera")||0<navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=["mp3"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,
this)),createjs.Sound.registerSound("./sounds/bullet1.ogg","bullet1",10),createjs.Sound.registerSound("./sounds/bullet2.ogg","bullet2",10),createjs.Sound.registerSound("./sounds/bullet4.ogg","bullet4",10),createjs.Sound.registerSound("./sounds/click.ogg","click"),createjs.Sound.registerSound("./sounds/explosion.ogg","explosion"),createjs.Sound.registerSound("./sounds/final_explosion.ogg","final_explosion"),createjs.Sound.registerSound("./sounds/soundtrack.ogg","soundtrack")):(createjs.Sound.alternateExtensions=
["ogg"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/bullet1.mp3","bullet1",10),createjs.Sound.registerSound("./sounds/bullet2.mp3","bullet2",10),createjs.Sound.registerSound("./sounds/bullet4.mp3","bullet4",10),createjs.Sound.registerSound("./sounds/click.mp3","click"),createjs.Sound.registerSound("./sounds/explosion.mp3","explosion"),createjs.Sound.registerSound("./sounds/final_explosion.mp3","final_explosion"),createjs.Sound.registerSound("./sounds/soundtrack.mp3",
"soundtrack")),f+=7)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("parallax_1_1","./sprites/parallax_1_1.jpg");s_oSpriteLibrary.addSprite("parallax_1_2","./sprites/parallax_1_2.jpg");s_oSpriteLibrary.addSprite("parallax_1_3","./sprites/parallax_1_3.jpg");
s_oSpriteLibrary.addSprite("parallax_2","./sprites/parallax_2.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("bg_help","./sprites/bg_help.png");s_oSpriteLibrary.addSprite("hero","./sprites/hero.png");s_oSpriteLibrary.addSprite("but_left","./sprites/but_left.png");s_oSpriteLibrary.addSprite("but_right","./sprites/but_right.png");s_oSpriteLibrary.addSprite("enemies","./sprites/enemies.png");s_oSpriteLibrary.addSprite("life","./sprites/life.png");s_oSpriteLibrary.addSprite("bullet",
"./sprites/bullet.png");s_oSpriteLibrary.addSprite("bullet2","./sprites/bullet2.png");s_oSpriteLibrary.addSprite("bullet3","./sprites/bullet3.png");s_oSpriteLibrary.addSprite("explosion","./sprites/explosion.png");s_oSpriteLibrary.addSprite("explosion_hero","./sprites/explosion_hero.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");f+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){b++;k.refreshLoader(Math.floor(b/f*100));if(b===
f){k.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundtrack=createjs.Sound.play("soundtrack",{loop:100});this.gotoMenu()}};this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this.gotoMenu=function(){new CMenu;h=STATE_MENU};this.gotoGame=function(){m=new CGame(d);h=STATE_GAME;$(s_oMain).trigger("game_start")};this.gotoHelp=function(){new CHelp;h=STATE_HELP};this.stopUpdate=function(){g=!1};this.startUpdate=function(){g=!0};this._update=
function(c){if(!1!==g){var a=(new Date).getTime();s_iTimeElaps=a-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=a;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);h===STATE_GAME&&m.update();s_oStage.update(c)}};s_oMain=this;d=a;this.initContainer()}var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oSoundTrackSnd,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oSoundTrack;TEXT_GAMEOVER="GAME OVER";TEXT_SCORE="SCORE";
TEXT_PLAY="PLAY";TEXT_HELP1="USE ARROW\nBUTTONS OR\nKEYS TO MOVE\nTHE STARSHIP";TEXT_HELP2="CLICK SPACEBAR\nOR SHOOT BUTTON\nTO SHOOT!!";TEXT_SHOOT="SHOOT";
function CInterface(){var a,g,b,f,h,d,k,m,c,l,p,n;this._init=function(){a=new createjs.Shape;a.graphics.beginFill("rgba(0,0,0,0.5)").drawRect(0,0,CANVAS_WIDTH,100);s_oStage.addChild(a);d=new createjs.Text(TEXT_SCORE+": 0","bold 40px space_marinenominal","#000");d.y=32;s_oStage.addChild(d);k=new createjs.Text(TEXT_SCORE+": 0","bold 40px space_marinenominal","#ffffff");k.y=30;s_oStage.addChild(k);d.x=CANVAS_WIDTH/2+1;k.x=CANVAS_WIDTH/2;d.textAlign="center";k.textAlign="center";b=new CGfxButton(70,CANVAS_HEIGHT-
70,s_oSpriteLibrary.getSprite("but_left"),!0);b.addEventListener(ON_MOUSE_DOWN,this._onLeftPressed,this);b.addEventListener(ON_MOUSE_UP,this._onLeftReleased,this);f=new CGfxButton(220,CANVAS_HEIGHT-70,s_oSpriteLibrary.getSprite("but_right"),!0);f.addEventListener(ON_MOUSE_DOWN,this._onRightPressed,this);f.addEventListener(ON_MOUSE_UP,this._onRightReleased,this);h=new CTextButton(CANVAS_WIDTH-130,CANVAS_HEIGHT-70,s_oSpriteLibrary.getSprite("but_play"),TEXT_SHOOT,"space_marinenominal","#ffffff",34);
h.addEventListener(ON_MOUSE_DOWN,this._onShot,this);c=new createjs.Bitmap(s_oSpriteLibrary.getSprite("life"));c.x=10;c.y=10;s_oStage.addChild(c);p=new createjs.Text("x"+NUM_LIVES,"bold 30px space_marinenominal","#000000");p.x=76;p.y=42;s_oStage.addChild(p);l=new createjs.Text("x"+NUM_LIVES,"bold 30px space_marinenominal","#ffffff");l.x=74;l.y=40;s_oStage.addChild(l);m=new CHelpPanel(0,0,s_oSpriteLibrary.getSprite("bg_help"));var e;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile){var q=s_oSpriteLibrary.getSprite("audio_icon");
n=new CToggle(CANVAS_WIDTH-q.height/2-10,q.height/2+10,q,s_bAudioActive);n.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);e=CANVAS_WIDTH-q.width/2-60}else q=s_oSpriteLibrary.getSprite("but_exit"),e=CANVAS_WIDTH-q.height/2-10;q=s_oSpriteLibrary.getSprite("but_exit");g=new CGfxButton(e,10+q.height/2,q,!0);g.addEventListener(ON_MOUSE_UP,this._onExit,this)};this.unload=function(){g.unload();g=null;b.unload();b=null;f.unload();f=null;h.unload();h=null;m.unload();if(!1===DISABLE_SOUND_MOBILE||!1===
s_bMobile)n.unload(),n=null};this.refreshScore=function(e){d.text=TEXT_SCORE+": "+e;k.text=TEXT_SCORE+": "+e};this.refreshLives=function(e){l.text="x"+e;p.text="x"+e};this._onLeftPressed=function(){s_oGame.onLeft()};this._onLeftReleased=function(){s_oGame.onKeyReleased()};this._onRightPressed=function(){s_oGame.onRight()};this._onRightReleased=function(){s_oGame.onKeyReleased()};this._onShot=function(){s_oGame.onShot()};this.onExitFromHelp=function(){m.unload()};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);
s_bAudioActive=!s_bAudioActive};this._onExit=function(){s_oGame.onExit()};this._init();return this}
function CHero(a,g,b){var f,h=!1,d=!1,k,m,c,l,p,n,e;this._init=function(a,b,d){c=0;l=1;p=0;f=!1;d={images:[d],frames:{width:65,height:100,regX:32,regY:50},animations:{idle:[0],move_right:[1,5,"idle_right"],idle_right:[5],back_right:[6,10,"idle"],move_left:[11,15,"idle_left"],idle_left:[15],back_left:[16,20,"idle"]}};d=new createjs.SpriteSheet(d);n=new createjs.Sprite(d,"idle");n.x=a;n.y=b;n.stop();s_oStage.addChild(n);k=32.5;m=50;d={images:[s_oSpriteLibrary.getSprite("explosion_hero")],frames:{width:200,
height:200,regX:100,regY:100},animations:{show:[0,19,"hide"],hide:[20,21]}};a=new createjs.SpriteSheet(d,"hide");e=new createjs.Sprite(a);e.addEventListener("animationend",this.onAnimationEnd);e.stop();e.visible=!1;s_oStage.addChild(e)};this.unload=function(){createjs.Tween.removeTweens(n);e.removeEventListener("animationend",oParent.onAnimationEnd)};this.moveLeft=function(){n.gotoAndPlay("move_left");h=!0};this.moveRight=function(){n.gotoAndPlay("move_right");d=!0};this.onAnimationEnd=function(){e.stop();
s_oGame.gameOver()};this.stop=function(){h?n.gotoAndPlay("back_left"):n.gotoAndPlay("back_right");d=h=!1};this.hurt=function(){l=1===l?0:1;p++;if(6>p){f=!0;var e=this;createjs.Tween.get(n).to({alpha:l},150,createjs.Ease.cubicOut).call(function(){e.hurt()})}else f=!1,p=0,l=1,createjs.Tween.get(n).to({alpha:l},150,createjs.Ease.cubicOut)};this.gameOver=function(){n.visible=!1;e.x=n.x;e.y=n.y;e.visible=!0;e.gotoAndPlay("show");!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("final_explosion")};
this.getPos=function(){return{x:n.x,y:n.y}};this.getHeadY=function(){return n.y-m};this.getRadius=function(){return k};this.isHurting=function(){return f};this.getBulletStartPoint=function(){return{x:n.x,y:this.getHeadY()}};this.getSprite=function(){return n};this.update=function(){h&&(c-=HERO_ACCELLERATION);d&&(c+=HERO_ACCELLERATION);n.x+=c;c*=HERO_FRICTION;c>MAX_HERO_SPEED&&(c=MAX_HERO_SPEED);c<-MAX_HERO_SPEED&&(c=-MAX_HERO_SPEED);.1>Math.abs(c)&&(c=0);n.x+k+c>CANVAS_WIDTH&&(n.x=CANVAS_WIDTH-k-
c);0>n.x-k+c&&(n.x=k-c)};this._init(a,g,b)}
function CHelpPanel(a,g,b){var f,h,d,k,m,c;this._init=function(a,b,g){m=new createjs.Bitmap(g);h=new createjs.Text(TEXT_HELP1,"bold 24px space_marinenominal","#000000");h.textAlign="center";h.x=CANVAS_WIDTH/2+152;h.y=322;f=new createjs.Text(TEXT_HELP1,"bold 24px space_marinenominal","#ffffff");f.textAlign="center";f.x=CANVAS_WIDTH/2+150;f.y=320;k=new createjs.Text(TEXT_HELP2,"bold 24px space_marinenominal","#000000");k.textAlign="center";k.x=CANVAS_WIDTH/2+152;k.y=642;d=new createjs.Text(TEXT_HELP2,
"bold 24px space_marinenominal","#ffffff");d.textAlign="center";d.x=CANVAS_WIDTH/2+150;d.y=640;c=new createjs.Container;c.x=a;c.y=b;c.addChild(m,h,f,k,d);s_oStage.addChild(c);var e=this;c.on("pressup",function(){e._onExitHelp()})};this.unload=function(){s_oStage.removeChild(c);var a=this;c.off("pressup",function(){a._onExitHelp()})};this._onExitHelp=function(){this.unload();s_oGame._onExitHelp()};this._init(a,g,b)}
function CGfxButton(a,g,b){var f,h,d;this._init=function(a,b,c){f=[];h=[];d=new createjs.Bitmap(c);d.x=a;d.y=b;d.regX=c.width/2;d.regY=c.height/2;s_oStage.addChild(d);this._initListener()};this.unload=function(){d.off("mousedown",this.buttonDown);d.off("pressup",this.buttonRelease);s_oStage.removeChild(d)};this.setVisible=function(a){d.visible=a};this._initListener=function(){d.on("mousedown",this.buttonDown);d.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){f[a]=b;h[a]=c};
this.buttonRelease=function(){d.scaleX=1;d.scaleY=1;f[ON_MOUSE_UP]&&f[ON_MOUSE_UP].call(h[ON_MOUSE_UP])};this.buttonDown=function(){d.scaleX=.9;d.scaleY=.9;f[ON_MOUSE_DOWN]&&f[ON_MOUSE_DOWN].call(h[ON_MOUSE_DOWN])};this.setPosition=function(a,b){d.x=a;d.y=b};this.setX=function(a){d.x=a};this.setY=function(a){d.y=a};this.getButtonImage=function(){return d};this.getX=function(){return d.x};this.getY=function(){return d.y};this._init(a,g,b);return this}
function CGame(a){function g(e){if(!1!==f)if(h=!1,32===e.keyCode)s_oGame.onShot();else s.stop()}function b(e){if(!1!==f&&!h)switch(e||(e=window.event),e.keyCode){case 37:h=!0;s_oGame.onLeft();break;case 39:h=!0,s_oGame.onRight()}}var f=!1,h=!1,d,k,m,c,l,p,n=-1,e,q,u,t=[],y,z,s,r,v,w,x=null;this._init=function(){d=0;y=new CScrollingMultipleBg([s_oSpriteLibrary.getSprite("parallax_1_1"),s_oSpriteLibrary.getSprite("parallax_1_2"),s_oSpriteLibrary.getSprite("parallax_1_3")]);z=new CScrollingBg(s_oSpriteLibrary.getSprite("parallax_2"));
var c=s_oSpriteLibrary.getSprite("hero");s=new CHero(HERO_START_X,CANVAS_HEIGHT-200,c);e=[];c=50;do e.push(c),c+=100;while(c<CANVAS_WIDTH-50);p=NUM_LIVES;v=new createjs.Container;s_oStage.addChild(v);this._initFallingObj();this._initBullets();r=new createjs.Shape;r.graphics.beginFill("red").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);r.alpha=.1;r.visible=!1;s_oStage.addChild(r);w=new CInterface;!1===s_bMobile&&(document.onkeydown=b,document.onkeyup=g)};this.unload=function(){f=!1;s_oStage.removeAllChildren();
s.unload();w.unload();null!==x&&x.unload();for(var e=0;e<q.length;e++)q[e].unload();for(e=0;e<u.length;e++)u[e].unload();for(e=0;e<t.length;e++)t[e].unload()};this._initFallingObj=function(){m=0;l=SPEED_FALLING_OBJ;q=[];for(var e=0;10>e;e++)q[e]=new CEnemy(START_Y_FALLING_OBJ,v)};this._initBullets=function(){c=0;u=[];for(var e=0;50>e;e++)u[e]=new CBullet1(v,"bullet2",!0)};this._showNextObj=function(){var c=Math.floor(Math.random()*e.length),a=Math.floor(Math.random()*NUM_FALLING_OBJ)+1;q[m].show(e[c],
l,a);m===q.length-1?(m=0,l<=MAX_SPEED_FALLING_OBJ&&(l+=1,TIME_OCCURENCE_FALLING_OBJ=6>l?2E3:7>l?1700:10>l?1500:15>l?1E3:700)):m++};this.addEnemyBullets=function(e){t.push(e)};this.removeBullet=function(e){for(var c=0;c<t.length;c++)t[c]===e&&(n=c)};this._lostLife=function(){r.visible=!0;var e=this;createjs.Tween.get(r).to({alpha:.6},400).call(function(){e._resetHurt()});s.hurt();p--;w.refreshLives(p);0===p&&(f=!1,s.gameOver())};this.gameOver=function(){x=CEndPanel(s_oSpriteLibrary.getSprite("msg_box"));
x.show(d)};this.checkCollision=function(e){!1===s.isHurting()&&checkRectCollision(e.getSprite(),s.getSprite())&&(e.reset(),this._lostLife())};this._checkBulletPlayerCollision=function(e){if(!1!==e.isUpdating())for(var c=e.getPos(),a=0;a<c.length;a++){for(var b=c[a],f=0;f<q.length;f++)if(q[f].isMoving()){var g=q[f].getPos(),k=q[f].getRadius(),g=Math.sqrt((g.x-b.x)*(g.x-b.x)+(g.y-b.y)*(g.y-b.y));if(g<k){q[f].reset();e.reset(a);d+=SCORE_HIT;w.refreshScore(d);break}}for(f=0;f<t.length;f++)for(var k=t[f].getPos(),
h=0;h<k.length;h++){var g=k[h],l=s.getRadius(),g=Math.sqrt((b.x-g.x)*(b.x-g.x)+(b.y-g.y)*(b.y-g.y));if(g<l){t[f].reset(h);e.reset(a);break}}}};this.checkBulletEnemyCollision=function(e){for(var c=e.getPos(),a=0;a<c.length;a++){var b=c[a],d=s.getPos(),q=s.getRadius();if(Math.sqrt((d.x-b.x)*(d.x-b.x)+(d.y-b.y)*(d.y-b.y))<q){this._lostLife();e.reset(a);break}}};this._resetHurt=function(){r.visible=!1;r.alpha=.5};this.onLeft=function(){s.moveLeft()};this.onRight=function(){s.moveRight()};this.onShot=
function(){var e=s.getBulletStartPoint();u[c].show(e.x,e.y,8);c===u.length-1?c=0:c++};this.onKeyReleased=function(){s.stop()};this.onExit=function(){this.unload();s_oMain.gotoMenu();$(s_oMain).trigger("restart")};this._onExitHelp=function(){w.onExitFromHelp();k=TIME_OCCURENCE_FALLING_OBJ;f=!0};this._updateParallaxes=function(){y.update(PARALLAX1_SPEED);z.update(PARALLAX2_SPEED)};this.update=function(){if(f){k+=s_iTimeElaps;k>TIME_OCCURENCE_FALLING_OBJ&&(k=0,this._showNextObj());s.update();for(var e=
0;e<q.length;e++)q[e].update();for(e=0;e<u.length;e++)u[e].update(),this._checkBulletPlayerCollision(u[e]);for(e=0;e<t.length;e++)t[e].update(),this.checkBulletEnemyCollision(t[e]);-1!==n&&(t[n].unload(),t.splice(n,1),n=-1);this._updateParallaxes()}};s_oGame=this;HERO_ACCELLERATION=a.hero_accelleration;HERO_FRICTION=a.hero_friction;MAX_HERO_SPEED=a.max_hero_speed;TIME_OCCURENCE_FALLING_OBJ=a.time_occurence_falling_obj;SPEED_FALLING_OBJ=a.speed_enemy;MAX_SPEED_FALLING_OBJ=a.max_speed_enemy;NUM_LIVES=
a.num_lives;SPEED_PLAYER_BULLET=a.speed_player_bullet;SCORE_HIT=a.score_hit;MIN_SHOT_OCCURENCE=a.min_shot_occurence;MAX_SHOT_OCCURENCE=a.max_shot_occurence;this._init()}var s_oGame;
function CEnemy(a,g){var b=!1,f,h,d,k,m,c,l,p,n;this._init=function(e,c){f=e;n=c;var a={images:[s_oSpriteLibrary.getSprite("enemies")],frames:{width:100,height:100,regX:50,regY:50},animations:{enemy_1:[0],enemy_2:[1],enemy_3:[2],enemy_4:[3]}},a=new createjs.SpriteSheet(a);l=new createjs.Sprite(a,"enemy_1");l.y=f;l.stop();s_oStage.addChild(l);a={images:[s_oSpriteLibrary.getSprite("explosion")],frames:{width:149,height:149,regX:74,regY:74},animations:{show:[0,19,"hide"],hide:[20,21]}};a=new createjs.SpriteSheet(a,
"hide");p=new createjs.Sprite(a);p.addEventListener("animationend",this.onAnimationEnd);p.stop();p.visible=!1;s_oStage.addChild(p);d=44};this.unload=function(){s_oStage.removeChild(l)};this.reset=function(){b=!1;!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("explosion");p.x=l.x;p.y=l.y;p.visible=!0;p.gotoAndPlay("show");l.y=f};this.show=function(e,c,a){l.alpha=1;l.x=e;l.y=f;h=c;l.gotoAndStop("enemy_"+a);this._assignBulletType(a);b=!0};this._assignBulletType=function(e){m=Math.floor(Math.random()*
MAX_SHOT_OCCURENCE)+MIN_SHOT_OCCURENCE;c=0;k=e};this._shot=function(){var e;switch(k){case 1:e=new CBullet1(n,"bullet",!1);break;case 2:e=new CBullet2(n,"bullet",!1);break;case 3:e=new CBullet3(n,"bullet3",!1);break;case 4:e=new CBullet4(n,"bullet",!1)}e.show(l.x,l.y+40,h);s_oGame.addEnemyBullets(e)};this.onAnimationEnd=function(){p.x=l.x;p.y=l.y};this.getPos=function(){return{x:l.x,y:l.y}};this.getRadius=function(){return d};this.isMoving=function(){return b};this.getSprite=function(){return l};
this.update=function(){b&&(l.y+=h,s_oGame.checkCollision(this),c+=s_iTimeElaps,c>m&&(c=0,this._shot()))};this._init(a,g)}
function CEndPanel(a){var g,b,f,h,d,k;this._init=function(a){g=new createjs.Bitmap(a);g.x=0;g.y=0;d=new createjs.Text("","bold 60px space_marinenominal","#000");d.x=CANVAS_WIDTH/2+1;d.y=CANVAS_HEIGHT/2-160;d.textAlign="center";h=new createjs.Text("","bold 60px space_marinenominal","#ffffff");h.x=CANVAS_WIDTH/2;h.y=CANVAS_HEIGHT/2-162;h.textAlign="center";b=new createjs.Text("","bold 40px space_marinenominal","#000");b.x=CANVAS_WIDTH/2+1;b.y=CANVAS_HEIGHT/2+50;b.textAlign="center";f=new createjs.Text("",
"bold 40px space_marinenominal","#ffffff");f.x=CANVAS_WIDTH/2;f.y=CANVAS_HEIGHT/2+52;f.textAlign="center";k=new createjs.Container;k.alpha=0;k.visible=!1;k.addChild(g,b,f,d,h);s_oStage.addChild(k)};this.unload=function(){k.off("mousedown",this._onExit)};this._initListener=function(){k.on("mousedown",this._onExit)};this.show=function(a){createjs.Sound.play("game_over");d.text=TEXT_GAMEOVER;h.text=TEXT_GAMEOVER;b.text=TEXT_SCORE+": "+a;f.text=TEXT_SCORE+": "+a;k.visible=!0;var c=this;createjs.Tween.get(k).to({alpha:1},
500).call(function(){c._initListener()});$(s_oMain).trigger("save_score",a)};this._onExit=function(){k.off("mousedown",this._onExit);s_oStage.removeChild(k);s_oGame.onExit()};this._init(a);return this}
function CBullet4(a,g,b){var f=!1,h,d,k,m,c,l,p,n;this._init=function(e,a,b){n=e;k=(h=b)?-1:1;c=[];e=s_oSpriteLibrary.getSprite(a);a=new createjs.Bitmap(e);a.regX=e.width/2;a.regY=e.height/2;a.x=-100;a.y=-100;!1===b?(a.scaleY=-1,a.rotation=45):a.rotation=-45;n.addChild(a);c.push(a);a=new createjs.Bitmap(e);a.x=-100;a.y=-100;a.regX=e.width/2;a.regY=e.height/2;!1===b?(a.scaleY=-1,a.rotation=-45):a.rotation=45;n.addChild(a);c.push(a);d=[];p=[];for(b=0;b<c.length;b++)d.push({x:-100,y:-100}),p[b]=!0,c[b].visible=
!1;m=Math.floor(e.width/2)};this.unload=function(){for(var e=0;e<c.length;e++)n.removeChild(c[e])};this.reset=function(e){p[e]=!1;c[e].x=d[e].x;c[e].y=d[e].y;!0===this._checkIfAllBulletInactive()&&(f=!1,!1===h&&s_oGame.removeBullet(this))};this._checkIfAllBulletInactive=function(){for(var e=!0,a=0;a<p.length;a++)if(!0===p[a]){e=!1;break}return e};this.show=function(e,a,b){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("bullet4");l=[];for(var d=0;d<c.length;d++){c[d].x=e;c[d].y=a;var g=
parseFloat(Math.cos(degreesToRadians(c[d].rotation*c[d].scaleY-90))).toFixed(2),h=Math.sin(degreesToRadians(c[d].rotation*c[d].scaleY+90));l[d]={x:g*(3+b),y:h*(3+b)*k};c[d].visible=!0}f=!0};this.getPos=function(){return c};this.getSprite=function(e){return c[e]};this.getSprites=function(){return c};this.isUpdating=function(){return f};this.getRadius=function(){return m};this.update=function(){if(f)for(var e=0;e<c.length;e++)c[e].x+=l[e].x,c[e].y+=l[e].y,(0>c[e].x||c[e].x>CANVAS_WIDTH||0>c[e].y||c[e].y>
CANVAS_HEIGHT)&&this.reset(e)};this._init(a,g,b)}
function CBullet3(a,g,b){var f=!1,h,d,k,m,c,l,p,n;this._init=function(e,a,b){n=e;k=(h=b)?-1:1;c=[];e=s_oSpriteLibrary.getSprite(a);a=new createjs.Bitmap(e);a.regX=e.width/2;a.regY=e.height/2;a.x=-100;a.y=-100;n.addChild(a);c.push(a);a=new createjs.Bitmap(e);a.x=-100;a.y=-100;a.regX=e.width/2;a.regY=e.height/2;n.addChild(a);c.push(a);d=[];p=[];for(a=0;a<c.length;a++)d.push({x:-100,y:-100}),p[a]=!0,c[a].visible=!1;m=Math.floor(e.width/2)};this.unload=function(){for(var a=0;a<c.length;a++)n.removeChild(c[a])};
this.reset=function(a){p[a]=!1;c[a].x=d[a].x;c[a].y=d[a].y;!0===this._checkIfAllBulletInactive()&&(f=!1,!1===h&&s_oGame.removeBullet(this))};this._checkIfAllBulletInactive=function(){for(var a=!0,c=0;c<p.length;c++)if(!0===p[c]){a=!1;break}return a};this.show=function(a,b,d){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("bullet3");l=[];c[0].x=a-40;c[0].y=b;l[0]={x:0,y:(8+d)*k};c[0].visible=!0;c[1].x=a+40;c[1].y=b;l[1]={x:0,y:(8+d)*k};f=c[1].visible=!0};this.getPos=function(){return c};
this.getSprite=function(a){return c[a]};this.getSprites=function(){return c};this.isUpdating=function(){return f};this.getRadius=function(){return m};this.update=function(){if(f)for(var a=0;a<c.length;a++)c[a].x+=l[a].x,c[a].y+=l[a].y,(0>c[a].x||c[a].x>CANVAS_WIDTH||0>c[a].y||c[a].y>CANVAS_HEIGHT)&&this.reset(a)};this._init(a,g,b)}
function CBullet2(a,g,b){var f=!1,h,d,k,m,c,l,p,n;this._init=function(a,b,f){n=a;k=(h=f)?-1:1;c=[];a=s_oSpriteLibrary.getSprite(b);b=new createjs.Bitmap(a);b.regX=a.width/2;b.regY=a.height/2;b.x=-100;b.y=-100;!1===f?(b.scaleY=-1,b.rotation=45):b.rotation=-45;n.addChild(b);c.push(b);b=new createjs.Bitmap(a);!1===f&&(b.scaleY=-1);b.x=-100;b.y=-100;b.regX=a.width/2;b.regY=a.height/2;n.addChild(b);c.push(b);b=new createjs.Bitmap(a);b.x=-100;b.y=-100;b.regX=a.width/2;b.regY=a.height/2;!1===f?(b.scaleY=
-1,b.rotation=-45):b.rotation=45;n.addChild(b);c.push(b);d=[];p=[];for(f=0;f<c.length;f++)d.push({x:-100,y:-100}),p[f]=!0,c[f].visible=!1;m=Math.floor(a.width/2)};this.unload=function(){for(var a=0;a<c.length;a++)n.removeChild(c[a])};this.reset=function(a){p[a]=!1;c[a].x=d[a].x;c[a].y=d[a].y;!0===this._checkIfAllBulletInactive()&&(f=!1,!1===h&&s_oGame.removeBullet(this))};this._checkIfAllBulletInactive=function(){for(var a=!0,b=0;b<p.length;b++)if(!0===p[b]){a=!1;break}return a};this.show=function(a,
b,d){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("bullet2");l=[];for(var g=0;g<c.length;g++){c[g].x=a;c[g].y=b;var h=parseFloat(Math.cos(degreesToRadians(c[g].rotation*c[g].scaleY-90))).toFixed(2),m=Math.sin(degreesToRadians(c[g].rotation*c[g].scaleY+90));l[g]={x:h*(3+d),y:m*(3+d)*k};c[g].visible=!0}f=!0};this.getPos=function(){return c};this.getSprite=function(a){return c[a]};this.getSprites=function(){return c};this.isUpdating=function(){return f};this.getRadius=function(){return m};
this.update=function(){if(f)for(var a=0;a<c.length;a++)c[a].x+=l[a].x,c[a].y+=l[a].y,(0>c[a].x||c[a].x>CANVAS_WIDTH||0>c[a].y||c[a].y>CANVAS_HEIGHT)&&this.reset(a)};this._init(a,g,b)}
function CBullet1(a,g,b){var f=!1,h,d,k,m,c,l,p,n;this._init=function(a,b,f){n=a;k=(h=f)?-1:1;c=[];a=s_oSpriteLibrary.getSprite(b);b=new createjs.Bitmap(a);!1===f&&(b.scaleY=-1);b.x=-100;b.y=-100;b.regX=a.width/2;b.regY=a.height/2;n.addChild(b);c.push(b);d=[];p=[];for(f=0;f<c.length;f++)d.push({x:-100,y:-100}),p[f]=!0,c[f].visible=!1;m=Math.floor(a.width/2)};this.unload=function(){for(var a=0;a<c.length;a++)n.removeChild(c[a])};this.reset=function(a){p[a]=!1;c[a].x=d[a].x;c[a].y=d[a].y;!0===this._checkIfAllBulletInactive()&&
(f=!1,!1===h&&s_oGame.removeBullet(this))};this._checkIfAllBulletInactive=function(){for(var a=!0,b=0;b<p.length;b++)if(!0===p[b]){a=!1;break}return a};this.show=function(a,b,d){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("bullet1");l=[];for(var g=0;g<c.length;g++){c[g].x=a;c[g].y=b;var h=parseFloat(Math.cos(degreesToRadians(c[g].rotation*c[g].scaleY-90))).toFixed(2),m=Math.sin(degreesToRadians(c[g].rotation*c[g].scaleY+90));l[g]={x:h*(3+d),y:m*(3+d)*k};c[g].visible=!0}f=!0};this.getPos=
function(){return c};this.getSprite=function(a){return c[a]};this.getSprites=function(){return c};this.isUpdating=function(){return f};this.getRadius=function(){return m};this.update=function(){if(f)for(var a=0;a<c.length;a++)c[a].x+=l[a].x,c[a].y+=l[a].y,(0>c[a].x||c[a].x>CANVAS_WIDTH||0>c[a].y||c[a].y>CANVAS_HEIGHT)&&this.reset(a)};this._init(a,g,b)};