function CInterface(){var a,c,b,d,h=null,g,l,e,k,m,u;this._init=function(){var h,n=s_oSpriteLibrary.getSprite("but_exit");c=new CGfxButton(CANVAS_WIDTH-n.height/2-10,n.height/2+10,n,!0);c.addEventListener(ON_MOUSE_UP,this._onExit,this);h=CANVAS_WIDTH-n.width/2-80;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)n=s_oSpriteLibrary.getSprite("audio_icon"),a=new CToggle(h,10+n.height/2,n,s_bAudioActive),a.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);h-=68;n=s_oSpriteLibrary.getSprite("but_help");
b=new CGfxButton(h,10+n.height/2,n,!0);b.addEventListener(ON_MOUSE_UP,this._onButHelpRelease,this);b.setVisible(!1);h-=120;n=s_oSpriteLibrary.getSprite("but_restart");d=new CTextButton(h,10+n.height/2,n,TEXT_RESTART,"Arial","#ffffff",26);d.addEventListener(ON_MOUSE_UP,this._onButRestartRelease,this);d.setTextPosition(35);g=new createjs.Text(TEXT_TIME,"bold 24px Arial","#ffffff");g.x=30;g.y=45;g.textAlign="left";g.textBaseline="alphabetic";g.lineWidth=200;s_oStage.addChild(g);n=s_oSpriteLibrary.getSprite("time_display");
l=createBitmap(n);l.scaleX=1.4;l.x=100;l.y=15;s_oStage.addChild(l);e=new createjs.Text("00:00","bold 24px Arial","#ffffff");e.x=175;e.y=45;e.textAlign="right";e.textBaseline="alphabetic";e.lineWidth=200;s_oStage.addChild(e);m=new createjs.Text(TEXT_SCORE,"bold 24px Arial","#ffffff");m.x=202;m.y=45;m.textAlign="left";m.textBaseline="alphabetic";m.lineWidth=200;s_oStage.addChild(m);n=s_oSpriteLibrary.getSprite("score_display");k=createBitmap(n);k.x=290;k.y=15;s_oStage.addChild(k);u=new createjs.Text("0",
"bold 24px Arial","#ffffff");u.x=363;u.y=45;u.textAlign="right";u.textBaseline="alphabetic";u.lineWidth=200;s_oStage.addChild(u)};this.unload=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)a.unload(),a=null;c.unload();b.unload();d.unload();null!==h&&h.unload()};this.refreshScore=function(b){u.text=b};this.refreshTime=function(b){e.text=b};this.setVisibleButHelp=function(){b.setVisible(!0)};this._onButHelpRelease=function(){h=new CHelpPanel};this._onButRestartRelease=function(){s_oGame.restartGame()};
this.onExitFromHelp=function(){h.unload()};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onExit=function(){s_oGame.onExit()};this._init();return this}
function CHelpPanel(){var a,c,b,d,h,g,l,e,k,m,u,v,n,y,C,D,z,B,r,w,q;this._init=function(){var q=this;C=createBitmap(s_oSpriteLibrary.getSprite("bg_help"));c=new createjs.Text(TEXT_HELP1," 30px Arial","#000000");c.x=CANVAS_WIDTH/2-148;c.y=CANVAS_HEIGHT/2-178;c.textAlign="center";c.lineWidth=400;a=new createjs.Text(TEXT_HELP1," 30px Arial","#ffffff");a.x=CANVAS_WIDTH/2-150;a.y=CANVAS_HEIGHT/2-180;a.textAlign="center";a.lineWidth=400;d=new createjs.Text(TEXT_HELP2," 30px Arial","#000000");d.x=CANVAS_WIDTH/
2-148;d.y=CANVAS_HEIGHT/2+52;d.textAlign="center";d.lineWidth=400;b=new createjs.Text(TEXT_HELP2," 30px Arial","#ffffff");b.x=CANVAS_WIDTH/2-150;b.y=CANVAS_HEIGHT/2+50;b.textAlign="center";b.lineWidth=400;r=new createjs.Container;r.addChild(C,c,a,d,b);r.alpha=0;s_oStage.addChild(r);createjs.Tween.get(r).to({alpha:1},700).call(function(){s_oGame.pauseGame()});r.on("pressup",function(){q._onExitHelp()});D=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));h=new createjs.Text(TEXT_HELP1_PAGE2," 30px Arial",
"#000000");h.x=CANVAS_WIDTH/2+2;h.y=CANVAS_HEIGHT/2-200;h.textAlign="center";h.lineWidth=400;g=new createjs.Text(TEXT_HELP1_PAGE2," 30px Arial","#ffffff");g.x=CANVAS_WIDTH/2;g.y=CANVAS_HEIGHT/2-202;g.textAlign="center";g.lineWidth=400;l=new createjs.Text(TEXT_HELP2_PAGE2," 28px Arial","#000000");l.x=CANVAS_WIDTH/2-328;l.y=CANVAS_HEIGHT/2-98;l.textAlign="left";l.lineWidth=670;e=new createjs.Text(TEXT_HELP2_PAGE2," 28px Arial","#ffffff");e.x=CANVAS_WIDTH/2-330;e.y=CANVAS_HEIGHT/2-100;e.textAlign="left";
e.lineWidth=670;m=new createjs.Text("+"+POINTS_TO_SUIT+TEXT_WIN_PAGE2," 28px Arial","#000000");m.x=CANVAS_WIDTH/2-328;m.y=CANVAS_HEIGHT/2-48;m.textAlign="left";m.lineWidth=670;k=new createjs.Text("+"+POINTS_TO_SUIT+TEXT_WIN_PAGE2," 28px Arial","#ffffff");k.x=CANVAS_WIDTH/2-330;k.y=CANVAS_HEIGHT/2-50;k.textAlign="left";k.lineWidth=670;v=new createjs.Text("+"+POINTS_TO_BOARD+TEXT_WIN2_PAGE2," 28px Arial","#000000");v.x=CANVAS_WIDTH/2-328;v.y=CANVAS_HEIGHT/2+32;v.textAlign="left";v.lineWidth=670;u=new createjs.Text("+"+
POINTS_TO_BOARD+TEXT_WIN2_PAGE2," 28px Arial","#ffffff");u.x=CANVAS_WIDTH/2-330;u.y=CANVAS_HEIGHT/2+30;u.textAlign="left";u.lineWidth=670;var N=formatTime(LOSEPOINTS_TIMER);y=new createjs.Text(TEXT_LOSE1_PAGE2+POINTS_TO_LOSE+TEXT_LOSE2_PAGE2+N+TEXT_LOSE3_PAGE2," 28px Arial","#000000");y.x=CANVAS_WIDTH/2-328;y.y=CANVAS_HEIGHT/2+132;y.textAlign="left";y.lineWidth=670;n=new createjs.Text(TEXT_LOSE1_PAGE2+POINTS_TO_LOSE+TEXT_LOSE2_PAGE2+N+TEXT_LOSE3_PAGE2," 28px Arial","#ffffff");n.x=CANVAS_WIDTH/2-330;
n.y=CANVAS_HEIGHT/2+130;n.textAlign="left";n.lineWidth=670;w=new createjs.Container;w.addChild(D,h,g,l,e,m,k,v,u,y,n);w.visible=0;s_oStage.addChild(w);w.on("pressup",function(){q._onExitHelp()});createjs.Tween.get(w).to({alpha:1},700);z=createBitmap(s_oSpriteLibrary.getSprite("arrow"));z.x=1E3;z.y=500;z.alpha=0;z.on("click",q._changePageTo2);s_oStage.addChild(z);B=createBitmap(s_oSpriteLibrary.getSprite("arrow"));B.scaleX=-1;B.x=140;B.y=500;B.visible=!1;B.on("click",q._changePageTo1);s_oStage.addChild(B);
createjs.Tween.get(z).to({alpha:1},700)};this.unload=function(){s_oStage.removeChild(r,w,z,B);var b=this;r.off("pressup",function(){b._onExitHelp()})};this._changePageTo1=function(){w.visible=!1;B.visible=!1;r.visible=!0;z.visible=!0};this._changePageTo2=function(){r.visible=!1;z.visible=!1;w.visible=!0;B.visible=!0};this._onExitHelp=function(){q.unload();s_oGame._onExitHelp()};q=this;this._init()}
function CGfxButton(a,c,b){var d,h,g;this._init=function(b,a,c){d=[];h=[];g=createBitmap(c);g.x=b;g.y=a;g.regX=c.width/2;g.regY=c.height/2;s_oStage.addChild(g);this._initListener()};this.unload=function(){g.off("mousedown",this.buttonDown);g.off("pressup",this.buttonRelease);s_oStage.removeChild(g)};this.setVisible=function(b){g.visible=b};this._initListener=function(){g.on("mousedown",this.buttonDown);g.on("pressup",this.buttonRelease)};this.addEventListener=function(b,a,c){d[b]=a;h[b]=c};this.buttonRelease=
function(){g.scaleX=1;g.scaleY=1;d[ON_MOUSE_UP]&&d[ON_MOUSE_UP].call(h[ON_MOUSE_UP])};this.buttonDown=function(){g.scaleX=.9;g.scaleY=.9;d[ON_MOUSE_DOWN]&&d[ON_MOUSE_DOWN].call(h[ON_MOUSE_DOWN])};this.setPosition=function(b,a){g.x=b;g.y=a};this.setX=function(b){g.x=b};this.setY=function(b){g.y=b};this.getButtonImage=function(){return g};this.getX=function(){return g.x};this.getY=function(){return g.y};this._init(a,c,b);return this}
function CGame(a){var c,b,d,h,g,l,e=!0,k,m=!0,u=!1,v,n,y,C,D,z,B,r,w,q,A,N,F,G,x,t,H,L,J,p,M,P,I,E,Q,O,R=null,K,U,S,T,V,W;this._init=function(){m=e=!0;k=u=!1;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)W=createjs.Sound.play("card_dealing",{loop:-1});G=[];t=[];x=[];E=[];Q=[];for(var f=0;4>f;f++)Q[f]=1;I=[];for(f=0;4>f;f++)I[f]=1;M=[];for(f=0;7>f;f++)M[f]=null;for(f=0;7>f;f++);D=y=n=v=0;A=26;w=0;F=q=-1;N=2;C=0;H=[];for(f=0;7>f;f++)for(var b=f;7>b;b++)H[C]={x:392+111*b,y:166+11*f},C++;L=[{x:80,y:389},
{x:191,y:389},{x:80,y:546},{x:191,y:546}];P=[];for(f=0;f<L.length;f++)P[f]=new createjs.Rectangle(L[f].x-CARD_WIDTH/2,L[f].y-CARD_HEIGHT/2,CARD_WIDTH,CARD_HEIGHT);J=[{x:80,y:167},{x:191,y:167},{x:211,y:177},{x:231,y:187}];p=[];for(f=0;19>f;f++)for(p[f]=[],b=0;7>b;b++)p[f][b]={status:LABEL_EMPTY,oCard:null};O=new CInterface;f=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(f);f=createBitmap(s_oSpriteLibrary.getSprite("but_return_cards"));f.x=43;f.y=130;s_oStage.addChild(f);K=
new createjs.Container;s_oStage.addChild(K);_oDeckContainer=new createjs.Container;s_oStage.addChild(_oDeckContainer);U=new createjs.Container;f=(new createjs.Graphics).beginFill("rgba(158,158,158,0.01)").drawRect(35,95,90,140);T=new createjs.Shape(f);if(s_bEasyMode)T.on("click",this._turnCard);else T.on("click",this._turn3Card);U.addChild(T);s_oStage.addChild(U);this._shuffleCard();this._setBoard();O=new CInterface;s_bMobile?window.navigator.msPointerEnabled?(s_oCanvas.addEventListener("MSPointerMove",
this.onTouchMoveMS,!1),s_oCanvas.addEventListener("MSPointerUp",this.releaseCard,!1)):(s_oCanvas.addEventListener("touchmove",this.onTouchMove,!1),s_oCanvas.addEventListener("touchend",this.releaseCard,!1)):(s_oStage.addEventListener("stagemousemove",this.dragCard,!1),s_oStage.addEventListener("stagemouseup",this.releaseCard,!1))};this._calculateScore=function(f,b){(new CScore).showScore(f.getPos(),b)};this._calculateScoreOnDeck=function(f,b){Q[f.getSuit()]===f.getRank()&&(!1!==DISABLE_SOUND_MOBILE&&
!1!==s_bMobile||createjs.Sound.play("snap"),(new CScore).showScore(f.getPos(),b),Q[f.getSuit()]++)};this.updateScore=function(f){v+=f;0>v&&(v=0);O.refreshScore(v)};this._shuffleCard=function(){for(var f=-1,b=[],a=0;52>a;a++){var c=(a+1)%13;1===c?f++:0===c&&(c=13);b.push({fotogram:a,rank:c,suit:f})}f=[];for(a=0;a<b.length;a++)f[a]=b[a];for(b=[];0<f.length;)b.push(f.splice(Math.round(Math.random()*(f.length-1)),1)[0]);for(a=0;a<b.length;a++)G[a]=new CCard(J[0].x-a/8,J[0].y-a/8,K,b[a].fotogram,b[a].rank,
b[a].suit)};this.blockGame=function(f){m=f};this._setBoard=function(){for(var f=0,b=G.length-1,a=0;28>a;a++)G[51-a].moveCard(H[a].x,H[a].y,100,f),G[51-a].setType("board"),f+=100;for(a=0;7>a;a++)for(f=a;7>f;f++)p[a][f].oCard=G[b],p[a][f].status=LABEL_HIDDEN,b--;for(a=28;52>a;a++)t[51-a]=G[51-a]};this.pickCard=function(f,a){if(!m)if(m=!0,g=f.getPos().x,l=f.getPos().y,z=K.getChildIndex(f.getSprite()),d=a.stageX-g,h=a.stageY-l,"deck"===f.checkType()){var e=f.saveInfo();x[0]=new CCard(g,l,K,e.szFotogram,
e.iRank,e.iSuit);x[0].setPointValue(f.saveInfo().bValue);x[0].instantShow();V=f;f.setVisible(!1)}else if("board"===f.checkType()){for(var k=0;7>k;k++)for(e=p.length-1;0<=e;e--)p[e][k].oCard===f&&(c=e,b=k);k=0;for(e=c;e<p.length;e++)p[e][b].status===LABEL_SHOWN&&k++;for(var n=[],e=0;e<k;e++)n[e]=p[c+e][b].oCard.saveInfo(),x[e]=new CCard(g,l+e*A,K,n[e].szFotogram,n[e].iRank,n[e].iSuit),x[e].setPointValue(n[e].bValue),p[c+e][b].oCard.unload(),x[e].setType("board"),x[e].instantShow()}else e=f.saveInfo(),
x[0]=new CCard(g,l,K,e.szFotogram,e.iRank,e.iSuit),x[0].setPointValue(f.saveInfo().bValue),x[0].setType("suit"),x[0].instantShow(),V=f,f.setVisible(!1)};this.dragCard=function(f){if(!e&&0<x.length)for(var b=0;b<x.length;b++)x[b].setPos(f.stageX-d,f.stageY-h+b*A)};this.setPreviousCardVisible=function(){0!==x.length&&(x[0].unload(),x=[],V.setVisible(!0))};this.releaseCard=function(f){!1===e&&0<x.length&&(m=!1,1===x.length&&S._snapOnSuit(x),13===x[0].getRank()&&S._snapOnBoardKing(x),u||S._checkCardCollision(x),
"deck"!==x[0].checkType()&&(x=[]),u=!1)};this._snapOnSuit=function(f){for(var a=0,d=-1,e=f[0].getLogicRect(),g=0;g<P.length;g++){var h=e.intersection(P[g]);null!==h&&a<h.width*h.height&&(a=h.width*h.height,d=g)}0>d||(f[0].getRank()===I[f[0].getSuit()]&&d===f[0].getSuit()&&"suit"!==f[0].checkType()&&(f[0].stackInPlace(L[d].x,L[d].y),u=!0,I[f[0].getSuit()]++,"deck"===f[0].checkType()?(t[q].unload(),t.splice(q,1),f[0].setType("suit"),s_bEasyMode||this._setActiveCard(),this._calculateScoreOnDeck(f[0],
POINTS_TO_SUIT),f[0].setPointValue(!1)):"board"===f[0].checkType()&&(p[c][b].status=LABEL_EMPTY,f[0].setType("suit"),this._checkBoard(f),this._calculateScoreOnDeck(f[0],POINTS_TO_SUIT),f[0].setPointValue(!1))),14===I[0]&&14===I[1]&&14===I[2]&&14===I[3]&&s_oGame.gameOver())};this._snapOnBoardKing=function(f){for(var a=0,d=-1,e=f[0].getLogicRect(),g=0;g<M.length;g++)if(null!==M[g]){var h=e.intersection(M[g]);null!==h&&a<h.width*h.height&&(a=h.width*h.height,d=g)}if(!(0>d)){if("deck"===f[0].checkType())f[0].stackInPlace(H[d].x,
H[d].y),p[0][d].status=LABEL_SHOWN,p[0][d].oCard=f[0],p[0][d].oCard.setType("board"),t[q].unload(),t.splice(q,1),s_bEasyMode||this._setActiveCard(),!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("snap"),this._calculateScore(f[0],POINTS_TO_BOARD),u=!0;else if("board"===f[0].checkType()){for(g=a=0;g<f.length;g++)f[g].stackInPlace(H[d].x,H[d].y+g*A),p[g][d].status=LABEL_SHOWN,p[g][d].oCard=f[g],p[g][d].oCard.setType("board"),p[c+g][b].status=LABEL_EMPTY,u=!0,!0===f[g].getPointValue()&&
(f[g].setPointValue(!1),a+=POINTS_TO_BOARD);0<a&&(this._calculateScore(f[0],a),!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("snap"))}else f[0].stackInPlace(H[d].x,H[d].y),p[0][d].status=LABEL_SHOWN,p[0][d].oCard=f[0],p[0][d].oCard.setType("board"),I[f[0].getSuit()]--;p[0][b].status===LABEL_EMPTY&&(M[b]=new createjs.Rectangle(H[b].x-CARD_WIDTH/2,H[b].y-CARD_HEIGHT/2,CARD_WIDTH,CARD_HEIGHT));this._checkBoard(f);M[d]=null}};this._checkCardCollision=function(f){for(var a=0,d=[],e=[],
h=0;7>h;h++)for(var k=p.length-1;0<=k;k--)if(p[k][h].status===LABEL_SHOWN){d[a]=p[k][h].oCard.getLogicRect();e[a]={oCard:p[k][h].oCard,x:p[k][h].oCard.getPos().x,y:p[k][h].oCard.getPos().y,row:k,column:h};a++;break}for(var h=0,a=-1,m=f[0].getLogicRect(),k=0;k<d.length;k++){var n=m.intersection(d[k]);null!==n&&h<n.width*n.height&&(h=n.width*n.height,a=k)}if(0>a)if("deck"===f[0].checkType())f[0].returnInPlace(g,l,z);else if("board"===f[0].checkType())for(k=0;k<f.length;k++)f[k].stackInPlace(g,l+k*A),
p[c+k][b].oCard=f[k];else{f[0].returnInPlace(g,l,z);return}else if(1===e[a].oCard.getRank()-f[0].getRank()&&e[a].oCard.getColor()!==f[0].getColor()){if("deck"===f[0].checkType()){f[0].stackInPlace(e[a].x,e[a].y+A);p[e[a].row+1][e[a].column].status=LABEL_SHOWN;p[e[a].row+1][e[a].column].oCard=f[0];p[e[a].row+1][e[a].column].oCard.setType("board");t[q].unload();t.splice(q,1);s_bEasyMode||this._setActiveCard();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("snap");this._calculateScore(f[0],
POINTS_TO_BOARD);f[0].setPointValue(!1);return}if("board"===f[0].checkType()){for(k=d=0;k<f.length;k++)f[k].stackInPlace(e[a].x,e[a].y+A+k*A),p[e[a].row+1+k][e[a].column].status=LABEL_SHOWN,p[c+k][b].status=LABEL_EMPTY,p[e[a].row+1+k][e[a].column].oCard=f[k],!0===f[k].getPointValue()&&(f[k].setPointValue(!1),d+=POINTS_TO_BOARD);0<d&&(this._calculateScore(f[0],d),!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("snap"))}else{f[0].stackInPlace(e[a].x,e[a].y+A);p[e[a].row+1][e[a].column].status=
LABEL_SHOWN;p[e[a].row+1][e[a].column].oCard=f[0];p[e[a].row+1][e[a].column].oCard.setType("board");I[f[0].getSuit()]--;return}}else{if("board"!==f[0].checkType()){f[0].returnInPlace(g,l,z);return}for(k=0;k<f.length;k++)f[k].stackInPlace(g,l+k*A),p[c+k][b].oCard=f[k]}this._checkBoard(f)};this._checkBoard=function(a){if("deck"!==a[0].checkType()){a=b;for(var c=p.length-1;0<=c&&p[c][a].status!==LABEL_SHOWN;c--)if(p[c][a].status===LABEL_HIDDEN){p[c][a].oCard.showCard();p[c][a].status=LABEL_SHOWN;break}p[0][a].status===
LABEL_EMPTY&&(M[a]=new createjs.Rectangle(H[a].x-CARD_WIDTH/2,H[a].y-CARD_HEIGHT/2,CARD_WIDTH,CARD_HEIGHT))}};this.autoMoveAce=function(a){var d=[];d[0]=a;if(d[0].getRank()===I[a.getSuit()]&&"board"===d[0].checkType()){d[0].stackInPlace(L[d[0].getSuit()].x,L[d[0].getSuit()].y);for(var e=0;7>e;e++)for(var g=p.length-1;0<=g;g--)p[g][e].oCard===a&&(c=g,b=e);p[c][b].status=LABEL_EMPTY;d[0].setType("suit");this._checkBoard(d);I[a.getSuit()]++;!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("snap");
this._calculateScoreOnDeck(a,POINTS_TO_SUIT);a.setPointValue(!1)}else a.getRank()===I[a.getSuit()]&&"deck"===a.checkType()&&1===t[q].getRank()&&(d[0].stackInPlace(L[a.getSuit()].x,L[a.getSuit()].y),d[0].setType("suit"),t.splice(q,1),I[a.getSuit()]++,s_bEasyMode||this._setActiveCard(),!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("snap"),this._calculateScoreOnDeck(a,POINTS_TO_SUIT),a.setPointValue(!1));m=!1};this.scaleDepth=function(a){K.setChildIndex(a,D);D++};this._turn3Card=function(){if(0!==
t.length&&!m){if(0>F){for(var a=0;a<t.length;a++)t[a].setBack(),K.setChildIndex(t[a].getSprite(),a),t[a].setVisible(!0),t[a].setPos(J[0].x-a/8,J[0].y-a/8);E=[];for(a=0;a<t.length/3;a++)E[a]=t.length-1-3*a;F=E.length-1;bubbleSort(E)}if(!(3>t.length&&0===E.length-1)){q=E[F]-2;3>t.length&&(q=E[F]);m=!0;if(F===E.length-1){if(4>t.length){for(a=t.length-1;0<=a;a--)t[E[F]-a].moveCard(J[a+1].x,J[a+1].y,150,0),t[E[F]-a].showCard(),t[E[F]-a].setActive(!1),K.setChildIndex(t[E[F]-a].getSprite(),a);t[q].setActive(!0);
return}a=2}else{for(var b=N+1,a=0;a<b;a++)t[E[F]+a+1].setVisible(!1);0===F?(a=E[F]+1,q=0):a=3;--a}for(;0<=a;a--)t[E[F]-a].moveCard(J[a+1].x,J[a+1].y,150,0),t[E[F]-a].showCard(),t[E[F]-a].setActive(!1),K.setChildIndex(t[E[F]-a].getSprite(),a);N=2;t[q].setActive(!0);F--}}};this._setActiveCard=function(){N--;t.length!==q&&(t[q].setActive(!0),1===t[q].getRank()&&this.autoMoveAce(t[q]))};this._turnCard=function(){if(0!==t.length&&!m){q--;if(0>q){q=t.length-1;for(var a=0;a<t.length;a++)t[a].setBack(),K.setChildIndex(t[a].getSprite(),
a),t[a].setPos(J[0].x-a/8,J[0].y-a/8)}q===t.length-1&&(D=0);m=!0;t[q].moveCard(J[1].x,J[1].y,150,0);t[q].showCard()}};this.onTouchMove=function(a){a.preventDefault();if(!e&&0<x.length)for(B=parseInt((a.touches[0].pageX-s_oCanvasLeft)/s_iScaleFactor),r=parseInt((a.touches[0].pageY-s_oCanvasTop)/s_iScaleFactor),a=0;a<x.length;a++)x[a].setPos(B-d,r-h+a*A)};this.onTouchMoveMS=function(a){if(!window.navigator.msPointerEnabled||a.isPrimary)if(a.preventDefault(),!e&&0<x.length)for(B=parseInt(((a.pageX||
a.targetTouches[0].pageX)-s_oCanvasLeft)/s_iScaleFactor),r=parseInt(((a.pageY||a.targetTouches[0].pageY)-s_oCanvasTop)/s_iScaleFactor),a=0;a<x.length;a++)x[a].setPos(B-d,r-h+a*A)};this.unload=function(){e=!1;for(var a=0;a<G.length;a++)G[a].unload();O.unload();null!==R&&R.unload();createjs.Tween.removeAllTweens();s_oStage.removeAllChildren()};this.restartGame=function(){this.unload();this._init()};this.pauseGame=function(){k=!k};this.onExit=function(){this.unload();s_oMain.gotoMenu();$(s_oMain).trigger("restart")};
this._onExitHelp=function(){this.pauseGame()};this.gameOver=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("game_over");R=CEndPanel(s_oSpriteLibrary.getSprite("msg_box"));R.show(v)};this.update=function(){e&&G[24].getPlaced()&&(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||W.stop(),w++,1===w?(G[51].showCard(),p[0][0].status=LABEL_SHOWN):10===w?(G[44].showCard(),p[1][1].status=LABEL_SHOWN):20===w?(G[38].showCard(),p[2][2].status=LABEL_SHOWN):30===w?(G[33].showCard(),p[3][3].status=
LABEL_SHOWN):40===w?(G[29].showCard(),p[4][4].status=LABEL_SHOWN):50===w?(G[26].showCard(),p[5][5].status=LABEL_SHOWN):60===w&&(G[24].showCard(),p[6][6].status=LABEL_SHOWN,m=e=!1,k=!0,O.setVisibleButHelp(),s_iTimeElaps=0));k&&(y+=s_iTimeElaps,5999E3<y&&(y=5999E3),O.refreshTime(formatTime(y)),n+=s_iTimeElaps,n>LOSEPOINTS_TIMER&&(n=0,(new CScore).removeScore(POINTS_TO_LOSE)))};s_oGame=this;LOSEPOINTS_TIMER=a.timer_losepoint;POINTS_TO_LOSE=a.points_to_lose;POINTS_TO_SUIT=a.points_to_suit;POINTS_TO_BOARD=
a.points_to_board;S=this;this._init()}var s_oGame;
function CEndPanel(a){var c,b,d,h,g,l;this._init=function(a){c=createBitmap(a);c.x=0;c.y=0;d=new createjs.Text("","bold 60px Arial","#000");d.x=CANVAS_WIDTH/2+1;d.y=CANVAS_HEIGHT/2-160;d.textAlign="center";h=new createjs.Text("","bold 60px Arial","#ffffff");h.x=CANVAS_WIDTH/2;h.y=CANVAS_HEIGHT/2-162;h.textAlign="center";g=new createjs.Text("","bold 40px Arial","#000");g.x=CANVAS_WIDTH/2+1;g.y=CANVAS_HEIGHT/2+50;g.textAlign="center";l=new createjs.Text("","bold 40px Arial","#ffffff");l.x=CANVAS_WIDTH/
2;l.y=CANVAS_HEIGHT/2+52;l.textAlign="center";b=new createjs.Container;b.alpha=0;b.visible=!1;b.addChild(c,g,l,d,h);s_oStage.addChild(b)};this.unload=function(){b.off("mousedown",this._onExit)};this._initListener=function(){b.on("mousedown",this._onExit)};this.show=function(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("game_over");d.text=TEXT_GAMEOVER;h.text=TEXT_GAMEOVER;g.text=TEXT_SCORE+": "+a;l.text=TEXT_SCORE+": "+a;b.visible=!0;var c=this;createjs.Tween.get(b).to({alpha:1},
500).call(function(){c._initListener()});$(s_oMain).trigger("save_score",a)};this._onExit=function(){b.off("mousedown",this._onExit);s_oStage.removeChild(b);s_oGame.onExit()};this._init(a);return this}
function CCard(a,c,b,d,h,g){var l=!1,e=!0,k,m,u,v,n,y,C,D,z,B,r,w,q,A;this._init=function(a,b,c,d,e,g){w=c;v=d;n=e;y=g;k=!1;m="deck";u=0===y||2===y?"red":"black";r=new createjs.Container;r.x=a;r.y=b;w.addChild(r);a={images:[s_oSpriteLibrary.getSprite("card_spritesheet")],frames:{width:CARD_WIDTH,height:CARD_HEIGHT,regX:CARD_WIDTH/2,regY:CARD_HEIGHT/2},animations:{card_1_1:[0],card_1_2:[1],card_1_3:[2],card_1_4:[3],card_1_5:[4],card_1_6:[5],card_1_7:[6],card_1_8:[7],card_1_9:[8],card_1_10:[9],card_1_J:[10],
card_1_Q:[11],card_1_K:[12],card_2_1:[13],card_2_2:[14],card_2_3:[15],card_2_4:[16],card_2_5:[17],card_2_6:[18],card_2_7:[19],card_2_8:[20],card_2_9:[21],card_2_10:[22],card_2_J:[23],card_2_Q:[24],card_2_K:[25],card_3_1:[26],card_3_2:[27],card_3_3:[28],card_3_4:[29],card_3_5:[30],card_3_6:[31],card_3_7:[32],card_3_8:[33],card_3_9:[34],card_3_10:[35],card_3_J:[36],card_3_Q:[37],card_3_K:[38],card_4_1:[39],card_4_2:[40],card_4_3:[41],card_4_4:[42],card_4_5:[43],card_4_6:[44],card_4_7:[45],card_4_8:[46],
card_4_9:[47],card_4_10:[48],card_4_J:[49],card_4_Q:[50],card_4_K:[51],back:[52]}};a=new createjs.SpriteSheet(a);z=createSprite(a,"back",0,0,CARD_WIDTH,CARD_HEIGHT);z.stop();r.addChild(z);B=new createjs.Shape;B.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(-CARD_WIDTH/2,-CARD_HEIGHT/2,CARD_WIDTH,CARD_HEIGHT);B.on("mousedown",this._mouseDown);r.addChild(B);C=[];D=[]};this.unload=function(){B.off("mousedown",this._mouseDown);w.removeChild(r)};this.addEventListener=function(a,b,c){C[a]=b;D[a]=
c};this.saveInfo=function(){return{szFotogram:v,iRank:n,iSuit:y,bValue:e}};this.changeInfo=function(a,b,c){v=a;n=b;y=c};this.instantShow=function(){z.gotoAndStop(v)};this.setValue=function(){z.gotoAndStop(v);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("card");var a=this;createjs.Tween.get(r).to({scaleX:1},200).call(function(){a.cardShown();A._aceInPlace()})};this._aceInPlace=function(){1===n&&s_oGame.autoMoveAce(this)};this.setType=function(a){m=a};this.checkType=function(){return m};
this.setActive=function(a){a?r.addChild(B):r.removeChild(B)};this._void=function(){};this.setVisible=function(a){r.visible=!0===a?!0:!1};this.moveCard=function(a,b,c,d){createjs.Tween.get(r).wait(d).to({x:a,y:b},c,createjs.Ease.linear).call(function(){A.setPlaced()})};this.returnInPlace=function(a,b,c){"board"===m?createjs.Tween.get(r).to({x:a,y:b},150,createjs.Ease.cubicOut).call(function(){k=!0}):createjs.Tween.get(r).to({x:a,y:b},150,createjs.Ease.cubicOut).call(function(){k=!0}).call(function(){s_oGame.setPreviousCardVisible()});
w.setChildIndex(r,c)};this.stackInPlace=function(a,b){createjs.Tween.get(r).to({x:a,y:b},150,createjs.Ease.cubicOut).call(function(){k=!0})};this.setPlaced=function(){l=!0;s_oGame.scaleDepth(this.getSprite())};this._sendCard=function(){s_oGame.dblClickMove(A)};this._mouseDown=function(a){!1!==k&&(w.getChildIndex(r),s_oGame.pickCard(A,a))};this.getPlaced=function(){return l};this.showCard=function(){s_oGame.blockGame(!0);var a=this;createjs.Tween.get(r).to({scaleX:.1},200).call(function(){a.setValue()}).call(function(){k=
!0})};this.hideCard=function(){var a=this;createjs.Tween.get(r).to({scaleX:.1},200).call(function(){a.setBack()})};this.setOldPos=function(a,b,c){};this.setPos=function(a,b){r.x=a;r.y=b};this.setBack=function(){k=!1;z.gotoAndStop("back");var a=this;createjs.Tween.get(r).to({scaleX:1},200).call(function(){a.cardHidden()})};this.cardShown=function(){s_oGame.blockGame(!1)};this.cardHidden=function(){C[ON_CARD_HIDE]&&C[ON_CARD_HIDE].call(D[ON_CARD_HIDE],this)};this._onSelected=function(){s_oGame.onCardSelected(q)};
this.getPointValue=function(){return e};this.setPointValue=function(a){e=a};this.getRank=function(){return n};this.getSuit=function(){return y};this.getColor=function(){return u};this.getFotogram=function(){return v};this.getPos=function(){return{x:r.x,y:r.y}};this.getSprite=function(){return r};this.getLogicRect=function(){return new createjs.Rectangle(r.x-CARD_WIDTH/2,r.y-CARD_HEIGHT/2,CARD_WIDTH,CARD_HEIGHT)};q=this;A=this;this._init(a,c,b,d,h,g)}
function CSpriteLibrary(){var a,c,b,d,h,g;this.init=function(l,e,k){b=c=0;d=l;h=e;g=k;a={}};this.addSprite=function(b,d){a.hasOwnProperty(b)||(a[b]={szPath:d,oSprite:new Image},c++)};this.getSprite=function(b){return a.hasOwnProperty(b)?a[b].oSprite:null};this._onSpritesLoaded=function(){h.call(g)};this._onSpriteLoaded=function(){d.call(g);++b==c&&this._onSpritesLoaded()};this.loadSprites=function(){for(var b in a)a[b].oSprite.oSpriteLibrary=this,a[b].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
a[b].oSprite.src=a[b].szPath};this.getNumSprites=function(){return c}}
var CANVAS_WIDTH=1136,CANVAS_HEIGHT=640,FPS_TIME=1E3/24,DISABLE_SOUND_MOBILE=!1,STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,STATE_GAME_WAITING_FOR_BET=0,STATE_GAME_DEAL=1,STATE_GAME_CHOOSE_HOLD=2,STATE_GAME_DRAW=3,STATE_GAME_EVALUATE=4,ON_CARD_SHOWN="ON_CARD_SHOWN",ON_CARD_HIDE="ON_CARD_HIDE",ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,SUIT_HEARTS=0,SUIT_SPADES=1,SUIT_DIAMONDS=2,SUIT_CLUBS=3,LABEL_EMPTY=0,LABEL_HIDDEN=1,LABEL_SHOWN=2,CARD_WIDTH=
87,CARD_HEIGHT=134,LOSEPOINTS_TIMER,POINTS_TO_LOSE,POINTS_TO_SUIT,POINTS_TO_BOARD;
function CToggle(a,c,b,d){var h,g,l,e;this._init=function(a,b,c,d){g=[];l=[];var n=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_true:[0],state_false:[1]}});h=d;e=createSprite(n,"state_"+h,c.width/2/2,c.height/2,c.width/2,c.height);e.x=a;e.y=b;e.stop();s_oStage.addChild(e);this._initListener()};this.unload=function(){e.off("mousedown",this.buttonDown);e.off("pressup",this.buttonRelease);s_oStage.removeChild(e)};this._initListener=
function(){e.on("mousedown",this.buttonDown);e.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){g[a]=b;l[a]=c};this.setActive=function(a){h=a;e.gotoAndStop("state_"+h)};this.buttonRelease=function(){e.scaleX=1;e.scaleY=1;!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");h=!h;e.gotoAndStop("state_"+h);g[ON_MOUSE_UP]&&g[ON_MOUSE_UP].call(l[ON_MOUSE_UP],h)};this.buttonDown=function(){e.scaleX=.9;e.scaleY=.9;g[ON_MOUSE_DOWN]&&g[ON_MOUSE_DOWN].call(l[ON_MOUSE_DOWN])};
this._init(a,c,b,d)}var s_iScaleFactor=1,s_oCanvasLeft,s_oCanvasTop;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,4))})(navigator.userAgent||
navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}$(window).ready(function(){sizeHandler()});window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a=CANVAS_WIDTH,c=CANVAS_HEIGHT,b=window.innerWidth;multiplier=s_iScaleFactor=Math.min(window.innerHeight/c,b/a);a*=multiplier;c*=multiplier;$("#canvas").css("width",a+"px");$("#canvas").css("height",c+"px");$("#canvas").css("left",b/2-a/2+"px");s_oCanvasLeft=$("#canvas").offset().left;s_oCanvasTop=$("#canvas").offset().top}}
function createBitmap(a,c,b){var d=new createjs.Bitmap(a),h=new createjs.Shape;c&&b?h.graphics.beginFill("#fff").drawRect(0,0,c,b):h.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);d.hitArea=h;return d}function createSprite(a,c,b,d,h,g){a=null!==c?new createjs.Sprite(a,c):new createjs.Sprite(a);c=new createjs.Shape;c.graphics.beginFill("#000000").drawRect(-b,-d,h,g);a.hitArea=c;return a}
function randomFloatBetween(a,c,b){"undefined"===typeof b&&(b=2);return parseFloat(Math.min(a+Math.random()*(c-a),c).toFixed(b))}function shuffle(a){for(var c=a.length,b,d;0!==c;)d=Math.floor(Math.random()*c),--c,b=a[c],a[c]=a[d],a[d]=b;return a}function bubbleSort(a){var c;do{c=!1;for(var b=0;b<a.length-1;b++)a[b]>a[b+1]&&(c=a[b],a[b]=a[b+1],a[b+1]=c,c=!0)}while(c)}function easeLinear(a,c,b,d){return b*a/d+c}function easeInQuad(a,c,b,d){return b*(a/=d)*a+c}
function easeInSine(a,c,b,d){return-b*Math.cos(a/d*(Math.PI/2))+b+c}function easeInCubic(a,c,b,d){return b*(a/=d)*a*a+c}function getTrajectoryPoint(a,c){var b=new createjs.Point,d=(1-a)*(1-a),h=a*a;b.x=d*c.start.x+2*(1-a)*a*c.traj.x+h*c.end.x;b.y=d*c.start.y+2*(1-a)*a*c.traj.y+h*c.end.y;return b}function formatTime(a){a/=1E3;var c=Math.floor(a/60);a=Math.floor(a-60*c);var b="",b=10>c?b+("0"+c+":"):b+(c+":");return 10>a?b+("0"+a):b+a}function degreesToRadians(a){return a*Math.PI/180}
function checkRectCollision(a,c){var b,d;b=getBounds(a,.9);d=getBounds(c,.98);return calculateIntersection(b,d)}function calculateIntersection(a,c){var b,d,h,g,l,e,k,m;b=a.x+(h=a.width/2);d=a.y+(g=a.height/2);l=c.x+(e=c.width/2);k=c.y+(m=c.height/2);b=Math.abs(b-l)-(h+e);d=Math.abs(d-k)-(g+m);return 0>b&&0>d?(b=Math.min(Math.min(a.width,c.width),-b),d=Math.min(Math.min(a.height,c.height),-d),{x:Math.max(a.x,c.x),y:Math.max(a.y,c.y),width:b,height:d,rect1:a,rect2:c}):null}
function getBounds(a,c){var b={x:Infinity,y:Infinity,width:0,height:0};if(a instanceof createjs.Container){b.x2=-Infinity;b.y2=-Infinity;var d=a.children,h=d.length,g,l;for(l=0;l<h;l++)g=getBounds(d[l],1),g.x<b.x&&(b.x=g.x),g.y<b.y&&(b.y=g.y),g.x+g.width>b.x2&&(b.x2=g.x+g.width),g.y+g.height>b.y2&&(b.y2=g.y+g.height);Infinity==b.x&&(b.x=0);Infinity==b.y&&(b.y=0);Infinity==b.x2&&(b.x2=0);Infinity==b.y2&&(b.y2=0);b.width=b.x2-b.x;b.height=b.y2-b.y;delete b.x2;delete b.y2}else{var e,k;a instanceof createjs.Bitmap?
(h=a.sourceRect||a.image,l=h.width*c,e=h.height*c):a instanceof createjs.Sprite?a.spriteSheet._frames&&a.spriteSheet._frames[a.currentFrame]&&a.spriteSheet._frames[a.currentFrame].image?(h=a.spriteSheet.getFrame(a.currentFrame),l=h.rect.width,e=h.rect.height,d=h.regX,k=h.regY):(b.x=a.x||0,b.y=a.y||0):(b.x=a.x||0,b.y=a.y||0);d=d||0;l=l||0;k=k||0;e=e||0;b.regX=d;b.regY=k;h=a.localToGlobal(0-d,0-k);g=a.localToGlobal(l-d,e-k);l=a.localToGlobal(l-d,0-k);d=a.localToGlobal(0-d,e-k);b.x=Math.min(Math.min(Math.min(h.x,
g.x),l.x),d.x);b.y=Math.min(Math.min(Math.min(h.y,g.y),l.y),d.y);b.width=Math.max(Math.max(Math.max(h.x,g.x),l.x),d.x)-b.x;b.height=Math.max(Math.max(Math.max(h.y,g.y),l.y),d.y)-b.y}return b}function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}function shuffle(a){for(var c=a.length,b,d;0<c;)d=Math.floor(Math.random()*c),c--,b=a[c],a[c]=a[d],a[d]=b;return a}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3==a.nodeType&&(a=a.parentNode);var c=document.createEvent("MouseEvents");c.initEvent("click",!0,!0);a.dispatchEvent(c)}}};
(function(){function a(a){var d={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};a=a||window.event;a.type in d?document.body.className=d[a.type]:(document.body.className=this[c]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var c="hidden";c in document?document.addEventListener("visibilitychange",a):(c="mozHidden")in document?document.addEventListener("mozvisibilitychange",a):(c="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",a):(c="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a})();
function CTextButton(a,c,b,d,h,g,l){var e,k,m,u,v;this._init=function(a,b,c,d,g,h,l){e=[];k=[];var w=createBitmap(c),q=Math.ceil(l/20);v=new createjs.Text(d,"bold "+l+"px "+g,"#000000");v.textAlign="center";v.textBaseline="alphabetic";var A=v.getBounds();v.x=c.width/2+q;v.y=Math.floor(c.height/2)+A.height/3+q;u=new createjs.Text(d,"bold "+l+"px "+g,h);u.textAlign="center";u.textBaseline="alphabetic";A=u.getBounds();u.x=c.width/2;u.y=Math.floor(c.height/2)+A.height/3;m=new createjs.Container;m.x=a;
m.y=b;m.regX=c.width/2;m.regY=c.height/2;m.addChild(w,v,u);s_oStage.addChild(m);this._initListener()};this.unload=function(){m.off("mousedown");m.off("pressup");s_oStage.removeChild(m)};this.setVisible=function(a){m.visible=a};this._initListener=function(){oParent=this;m.on("mousedown",this.buttonDown);m.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){e[a]=b;k[a]=c};this.buttonRelease=function(){m.scaleX=1;m.scaleY=1;e[ON_MOUSE_UP]&&e[ON_MOUSE_UP].call(k[ON_MOUSE_UP])};this.buttonDown=
function(){m.scaleX=.9;m.scaleY=.9;e[ON_MOUSE_DOWN]&&e[ON_MOUSE_DOWN].call(k[ON_MOUSE_DOWN])};this.setTextPosition=function(a){u.y=a;v.y=a+2};this.setPosition=function(a,b){m.x=a;m.y=b};this.setX=function(a){m.x=a};this.setY=function(a){m.y=a};this.getButtonImage=function(){return m};this.getX=function(){return m.x};this.getY=function(){return m.y};this._init(a,c,b,d,h,g,l);return this}
function CScore(){this.showScore=function(a,c){var b=new createjs.Text("+"+c,"bold 24px Arial","#000000");b.x=a.x;b.y=a.y;b.scaleX=2;b.scaleY=2;b.textAlign="right";b.textBaseline="alphabetic";b.outline=4;s_oStage.addChild(b);var d=new createjs.Text("+"+c,"bold 24px Arial","#fff");d.x=a.x;d.y=a.y;d.scaleX=2;d.scaleY=2;d.textAlign="right";d.textBaseline="alphabetic";s_oStage.addChild(d);createjs.Tween.get(d).to({x:363,y:45},1E3,createjs.Ease.cubicIn).call(function(){s_oGame.updateScore(c);s_oStage.removeChild(d)});
createjs.Tween.get(d).to({scaleX:1,scaleY:1},1E3,createjs.Ease.linear);createjs.Tween.get(b).to({x:363,y:45},1E3,createjs.Ease.cubicIn).call(function(){s_oStage.removeChild(b)});createjs.Tween.get(b).to({scaleX:1,scaleY:1},1E3,createjs.Ease.linear)};this.removeScore=function(a){s_oGame.updateScore(a);var c=new createjs.Text(a,"bold 24px Arial","#ffffff");c.x=363;c.y=45;c.textAlign="right";c.textBaseline="alphabetic";s_oStage.addChild(c);createjs.Tween.get(c).to({x:420},2E3,createjs.Ease.cubicOut).call(function(){s_oStage.removeChild(c)});
createjs.Tween.get(c).to({alpha:0},4E3,createjs.Ease.linear)}}
function CPreloader(){var a,c,b,d,h,g,l;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.loadSprites();l=new createjs.Container;s_oStage.addChild(l)};this.unload=function(){l.removeAllChildren()};this.hide=function(){var a=this;setTimeout(function(){createjs.Tween.get(g).to({alpha:1},500).call(function(){a.unload();
s_oMain.gotoMenu()})},1E3)};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var e=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));l.addChild(e);e=s_oSpriteLibrary.getSprite("progress_bar");d=createBitmap(e);d.x=CANVAS_WIDTH/2-e.width/2;d.y=CANVAS_HEIGHT-170;l.addChild(d);a=e.width;c=e.height;h=new createjs.Shape;h.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(d.x,d.y,1,c);l.addChild(h);d.mask=
h;b=new createjs.Text("","30px ZombieA","#fff");b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT-125;b.shadow=new createjs.Shadow("#000",2,2,2);b.textBaseline="alphabetic";b.textAlign="center";l.addChild(b);g=new createjs.Shape;g.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);g.alpha=0;l.addChild(g)};this.refreshLoader=function(e){b.text=e+"%";h.graphics.clear();e=Math.floor(e*a/100);h.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(d.x,d.y,e,c)};this._init()}
function CModeMenu(){var a,c,b,d,h,g,l,e,k,m,u,v,n,y,C,D,z,B,r,w;this._init=function(){a=createBitmap(s_oSpriteLibrary.getSprite("bg_difficulty"));s_oStage.addChild(a);var q=s_oSpriteLibrary.getSprite("layout_panel"),A=CANVAS_WIDTH/4;c=new createjs.Container;c.x=A;c.y=310;b=new createjs.Container;b.x=CANVAS_WIDTH-A-q.width;b.y=310;q=s_oSpriteLibrary.getSprite("layout_panel");d=createBitmap(q);c.addChild(d);h=createBitmap(s_oSpriteLibrary.getSprite("layout_1_card"));h.x=35;h.y=115;c.addChild(h);g=
new createjs.Text(TEXT_MODE_1,"bold 28px Arial","#000000");g.x=124;g.y=90;g.textBaseline="alphabetic";g.textAlign="center";g.lineWidth=300;g.alpha=.6;c.addChild(g);l=new createjs.Text(TEXT_MODE_1,"bold 28px Arial","#ffffff");l.x=122;l.y=88;l.textBaseline="alphabetic";l.textAlign="center";l.lineWidth=300;c.addChild(l);e=new createjs.Text(TEXT_EASY,"bold 34px Arial","#000000");e.x=124;e.y=37;e.textBaseline="alphabetic";e.textAlign="center";e.lineWidth=300;e.alpha=.6;c.addChild(e);k=new createjs.Text(TEXT_EASY,
"bold 34px Arial","#ffffff");k.x=122;k.y=35;k.textBaseline="alphabetic";k.textAlign="center";k.lineWidth=300;c.addChild(k);q=s_oSpriteLibrary.getSprite("layout_panel");m=createBitmap(q);b.addChild(m);u=createBitmap(s_oSpriteLibrary.getSprite("layout_3_card"));u.x=22;u.y=115;b.addChild(u);v=new createjs.Text(TEXT_MODE_3,"bold 28px Arial","#000000");v.x=124;v.y=90;v.textBaseline="alphabetic";v.textAlign="center";v.lineWidth=300;v.alpha=.6;b.addChild(v);n=new createjs.Text(TEXT_MODE_3,"bold 28px Arial",
"#ffffff");n.x=122;n.y=88;n.textBaseline="alphabetic";n.textAlign="center";n.lineWidth=300;b.addChild(n);y=new createjs.Text(TEXT_NORMAL,"bold 34px Arial","#000000");y.x=124;y.y=37;y.textBaseline="alphabetic";y.textAlign="center";y.lineWidth=300;y.alpha=.6;b.addChild(y);C=new createjs.Text(TEXT_NORMAL,"bold 34px Arial","#ffffff");C.x=125;C.y=35;C.textBaseline="alphabetic";C.textAlign="center";C.lineWidth=300;b.addChild(C);D=new createjs.Text(TEXT_TOP_MODE,"bold 52px Arial","#000000");D.x=CANVAS_WIDTH/
2+4;D.y=CANVAS_HEIGHT/2-96;D.textAlign="center";D.lineWidth=800;D.alpha=.6;s_oStage.addChild(D);z=new createjs.Text(TEXT_TOP_MODE,"bold 52px Arial","#ffffff");z.x=CANVAS_WIDTH/2;z.y=CANVAS_HEIGHT/2-100;z.textAlign="center";z.lineWidth=800;s_oStage.addChild(z);s_oStage.addChild(c);s_oStage.addChild(b);q=(new createjs.Graphics).beginFill("rgba(158,158,158,0.01)").drawRect(4,0,240,250);A=new createjs.Shape(q);c.addChild(A);A.on("mousedown",this._resizeEasy);A.on("pressup",this._selectEasy);q=new createjs.Shape(q);
b.addChild(q);q.on("mousedown",this._resizeNormal);q.on("pressup",this._selectNormal);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)q=s_oSpriteLibrary.getSprite("audio_icon"),w=new CToggle(CANVAS_WIDTH-q.height/2-10,q.height/2+10,q,s_bAudioActive),w.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);r=new createjs.Shape;r.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(r);createjs.Tween.get(r).to({alpha:0},1E3).call(function(){r.visible=!1})};this._resizeEasy=
function(){c.x+=10;c.y+=10;c.scaleX=.9;c.scaleY=.9;!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click")};this._selectEasy=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");B.unload();s_oMain.gotoGame(!0)};this._resizeNormal=function(){b.x+=10;b.y+=10;b.scaleX=.9;b.scaleY=.9;!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click")};this._selectNormal=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");
B.unload();s_oMain.gotoGame(!1)};this.unload=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)w.unload(),w=null;s_oStage.removeChild(a,c,b);a=null};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onButPlayRelease=function(){this.unload();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");s_oMain.gotoGame()};B=this;this._init()}
function CMenu(){var a,c,b,d;this._init=function(){a=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(a);var h=s_oSpriteLibrary.getSprite("but_play");c=new CTextButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-80,h,TEXT_PLAY,"Arial","#ffffff",40);c.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)h=s_oSpriteLibrary.getSprite("audio_icon"),d=new CToggle(CANVAS_WIDTH-h.height/2-10,h.height/2+10,h,s_bAudioActive),d.addEventListener(ON_MOUSE_UP,
this._onAudioToggle,this);b=new createjs.Shape;b.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(b);createjs.Tween.get(b).to({alpha:0},1E3).call(function(){b.visible=!1})};this.unload=function(){c.unload();c=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)d.unload(),d=null;s_oStage.removeChild(a);a=null};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onButPlayRelease=function(){this.unload();!1!==
DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");s_oMain.goToModeMenu()};this._init()}
function CMain(a){var c,b=0,d=0,h=STATE_LOADING,g,l,e;this.initContainer=function(){s_oCanvas=document.getElementById("canvas");s_oStage=new createjs.Stage(s_oCanvas);createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&(s_oStage.enableMouseOver(20),$("body").on("contextmenu","#canvas",function(a){return!1}));s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.setFPS(30);navigator.userAgent.match(/Windows Phone/i)&&(DISABLE_SOUND_MOBILE=
!0);s_oSpriteLibrary=new CSpriteLibrary;l=new CPreloader};this.preloaderReady=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();this._loadImages();c=!0};this.soundLoaded=function(){b++;if(b===d){l.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundtrack=createjs.Sound.play("soundtrack",{loop:100});this.gotoMenu()}};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&(0<navigator.userAgent.indexOf("Opera")||0<navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=
["m4a"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/soundtrack.ogg","soundtrack"),createjs.Sound.registerSound("./sounds/card_dealing.ogg","card_dealing"),createjs.Sound.registerSound("./sounds/snap.ogg","snap"),createjs.Sound.registerSound("./sounds/press_button.ogg","click"),createjs.Sound.registerSound("./sounds/game_over.ogg","game_over"),createjs.Sound.registerSound("./sounds/card.ogg","card")):(createjs.Sound.alternateExtensions=
["ogg"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/soundtrack.mp3","soundtrack"),createjs.Sound.registerSound("./sounds/card_dealing.mp3","card_dealing"),createjs.Sound.registerSound("./sounds/snap.mp3","snap"),createjs.Sound.registerSound("./sounds/press_button.m4a","click"),createjs.Sound.registerSound("./sounds/game_over.mp3","game_over"),createjs.Sound.registerSound("./sounds/card.mp3","card")),d+=6)};this._loadImages=
function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("bg_difficulty","./sprites/bg_difficulty.jpg");s_oSpriteLibrary.addSprite("layout_panel","./sprites/layout_panel.png");s_oSpriteLibrary.addSprite("layout_1_card","./sprites/layout_1_card.png");s_oSpriteLibrary.addSprite("layout_3_card",
"./sprites/layout_3_cards.png");s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("bg_help","./sprites/bg_help.png");s_oSpriteLibrary.addSprite("arrow","./sprites/arrow.png");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("but_help","./sprites/but_help.png");s_oSpriteLibrary.addSprite("but_restart","./sprites/but_restart.png");s_oSpriteLibrary.addSprite("time_display",
"./sprites/time_display.png");s_oSpriteLibrary.addSprite("score_display","./sprites/score_display.png");s_oSpriteLibrary.addSprite("card_spritesheet","./sprites/cards.png");s_oSpriteLibrary.addSprite("but_return_cards","./sprites/but_return_cards.png");d+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){b++;l.refreshLoader(Math.floor(b/d*100));if(b===d){l.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundtrack=createjs.Sound.play("soundtrack",
{loop:100});this.gotoMenu()}};this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this.gotoMenu=function(){new CMenu;h=STATE_MENU};this.goToModeMenu=function(){new CModeMenu;h=STATE_MENU};this.gotoGame=function(a){s_bEasyMode=a;e=new CGame(g);h=STATE_GAME;$(s_oMain).trigger("game_start")};this.gotoHelp=function(){new CHelp;h=STATE_HELP};this.stopUpdate=function(){c=!1};this.startUpdate=function(){c=!0};this._update=function(a){if(!1!==c){var b=(new Date).getTime();
s_iTimeElaps=b-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=b;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);h===STATE_GAME&&e.update();s_oStage.update(a)}};s_oMain=this;g=a;this.initContainer()}var s_bMobile,s_bEasyMode,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oSoundTrack,s_oCanvas;TEXT_GAMEOVER="YOU WIN";TEXT_SCORE="SCORE";TEXT_PLAY="PLAY";TEXT_RESTART="RESTART";
TEXT_TIME="TIME";TEXT_SCORE="SCORE";TEXT_HELP1="THE CARD PILES IN BOARD, CAN BE BUILD DOWN BY DECRESCENT CARD RANK WITH ALTERNATE COLORS";TEXT_HELP2="THE GOAL IS TO BUILD UP FOUR FOUNDATION BY SUIT, FROM ACE TO KING ";TEXT_HELP1_PAGE2="SCORE SYSTEM";TEXT_HELP2_PAGE2="YOU CAN EARN POINT BY DIFFERENT ACTION:";TEXT_WIN_PAGE2=" Points for any card you drop on Foundation for the first time";TEXT_WIN2_PAGE2=" Points for any card you snap on Board for the first time";TEXT_LOSE1_PAGE2="Time is your enemy! You lose ";
TEXT_LOSE2_PAGE2=" Points every ";TEXT_LOSE3_PAGE2=" seconds";TEXT_MODE_1="1 card showing";TEXT_MODE_3="3 cards showing";TEXT_EASY="EASY";TEXT_NORMAL="NORMAL";TEXT_TOP_MODE="CHOSE GAME MODE";