function CInterface(){var a,c,b,f,d,e,g,h,k,l;this._init=function(){var m,n=s_oSpriteLibrary.getSprite("but_exit");b=CANVAS_WIDTH-n.height/2-20;f=n.height/2+10;g=new CGfxButton(b,f,n,!0);g.addEventListener(ON_MOUSE_UP,this._onExit,this);m=CANVAS_WIDTH-n.width/2-125;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)n=s_oSpriteLibrary.getSprite("but_settings"),a=m,c=10+n.height/2,h=new CGfxButton(a,c,n,!0),h.addEventListener(ON_MOUSE_UP,this._onButConfigRelease,this);l=new CInfoTurn(815,1645,PAWN_BLACK,
s_oStage);k=new CInfoTurn(490,300,PAWN_WHITE,s_oStage);d=[];for(m=0;m<TOT_CELL;m++)d[m]=createBitmap(s_oSpriteLibrary.getSprite("white_chip")),d[m].x=300+10.5*m,d[m].y=422,s_oStage.addChild(d[m]);e=[];for(m=0;m<TOT_CELL;m++)e[m]=createBitmap(s_oSpriteLibrary.getSprite("black_chip")),e[m].x=960-10.5*m,e[m].y=1422,s_oStage.addChild(e[m]);this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){g.unload();h.unload();l.unload();k.unload();for(var a=0;a<TOT_CELL;a++)s_oStage.removeChild(d[a]),
s_oStage.removeChild(e[a]);s_oInterface=null};this.refreshButtonPos=function(e,d){g.setPosition(b-e,d+f);h.setPosition(a-e,d+c)};this.refreshWhitePawnNumber=function(a){k.refreshPawnNumber(a);for(var b=0;b<a;b++)d[b].visible=!1;for(b=a;b<TOT_CELL;b++)d[b].visible=!0};this.refreshWhiteTime=function(a){50<a&&k.refreshTime(formatTime(a))};this.refreshBlackPawnNumber=function(a){l.refreshPawnNumber(a);for(var b=0;b<a;b++)e[b].visible=!1;for(b=a;b<TOT_CELL;b++)e[b].visible=!0};this.refreshBlackTime=function(a){50<
a&&l.refreshTime(formatTime(a))};this.activePlayer=function(a){a===PAWN_WHITE?(l.active(!1),k.active(!0)):(k.active(!1),l.active(!0))};this.setInfoVisible=function(a){k.setPanelVisible(a);l.setPanelVisible(a)};this._onButConfigRelease=function(){new CConfigPanel};this._onButRestartRelease=function(){s_oGame.restartGame()};this.onExitFromHelp=function(){null.unload()};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onExit=function(){s_oGame.onExit()};
s_oInterface=this;this._init();return this}var s_oInterface=null;
function CInfoTurn(a,c,b,f){var d,e,g,h,k,l,m,n;this._init=function(a,b,c,f){d=new createjs.Container;d.x=a;d.y=b;f.addChild(d);a=s_oSpriteLibrary.getSprite("bg_turn");b={images:[a],framerate:58,frames:{width:a.width/2,height:a.height,regX:a.width/2/2,regY:a.height/2},animations:{off:[0,0,"on"],on:[1,1,"off"]}};b=new createjs.SpriteSheet(b);e=createSprite(b,0,a.width/2/2,a.height/2,a.width/2,a.height);e.stop();d.addChild(e);g=createSprite(b,1,a.width/2/2,a.height/2,a.width/2,a.height);g.stop();g.x=
10;g.alpha=0;d.addChild(g);a=s_oSpriteLibrary.getSprite("pawn");b={images:[a],frames:{width:a.width/2,height:a.height,regX:a.width/2/2,regY:a.height/2},animations:{off:[0],on:[1]}};b=new createjs.SpriteSheet(b);l=createSprite(b,c,a.width/2/2,a.height/2,a.width/2,a.height);l.stop();l.x=c===PAWN_WHITE?110:-220;l.y=-10;d.addChild(l);m=new createjs.Text("x2","bold 68px arialrounded","#ffffff");m.x=c===PAWN_WHITE?160:-160;m.y=-5;m.textAlign="left";m.textBaseline="middle";m.lineWidth=200;d.addChild(m);
a=s_oSpriteLibrary.getSprite("time_icon");h=createBitmap(a);h.regX=a.width/2;h.regY=a.height/2;h.scaleX=.8;h.scaleY=.8;h.x=c===PAWN_WHITE?-230:225;h.y=-5;d.addChild(h);k=new createjs.Text("00:00","bold 58px arialrounded","#ffffff");c===PAWN_WHITE?(k.x=-180,k.textAlign="left"):(k.x=175,k.textAlign="right");k.textBaseline="middle";k.lineWidth=200;d.addChild(k)};this.refreshPawnNumber=function(a){m.text="x"+a};this.refreshTime=function(a){k.text=a};this.active=function(a){a?(createjs.Tween.get(e).to({alpha:0},
750,createjs.Ease.cubicOut).to({alpha:1},750,createjs.Ease.cubicIn).call(function(){n.active(a)}),createjs.Tween.get(g).to({alpha:1},750,createjs.Ease.cubicOut).to({alpha:0},750,createjs.Ease.cubicIn)):(e.alpha=1,g.alpha=0,createjs.Tween.removeAllTweens())};this.unload=function(){f.removeChild(d)};this.setBgVisible=function(a){e.visible=a};this.setPanelVisible=function(a){d.visible=a};this.setPawn=function(a){l.gotoAndStop(a)};n=this;this._init(a,c,b,f)}
function CHelpPanel(){var a,c,b,f,d,e;this._init=function(){var e=this;f=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));var h={images:[s_oSpriteLibrary.getSprite("pawn")],frames:{width:PAWN_SIZE,height:PAWN_SIZE,regX:PAWN_SIZE/2,regY:PAWN_SIZE/2},animations:{black:[0],white:[1]}},h=new createjs.SpriteSheet(h);a=[];for(var k=0;4>k;k++)a[k]=createSprite(h,k%2,PAWN_SIZE/2,PAWN_SIZE/2,PAWN_SIZE,PAWN_SIZE),a[k].stop(),2>k?(a[k].y=850,a[k].x=0===k%2?CANVAS_WIDTH/2+50:CANVAS_WIDTH/2-50):(a[k].y=950,
a[k].x=0===k%2?CANVAS_WIDTH/2-50:CANVAS_WIDTH/2+50);h=CANVAS_WIDTH/2;k=CANVAS_HEIGHT/2-300;c=new createjs.Text(TEXT_HELP1," 40px arialrounded","#ffffff");c.x=h;c.y=k;c.textAlign="center";c.textBaseline="alphabetic";c.lineWidth=600;h=CANVAS_WIDTH/2;k=CANVAS_HEIGHT/2+100;b=new createjs.Text(TEXT_HELP2," 40px arialrounded","#ffffff");b.x=h;b.y=k;b.textAlign="center";b.textBaseline="alphabetic";b.lineWidth=600;d=new createjs.Container;d.addChild(f,c,b,a[0],a[1],a[2],a[3]);d.alpha=0;s_oStage.addChild(d);
createjs.Tween.get(d).to({alpha:1},700);d.on("pressup",function(){e._onExitHelp()})};this.unload=function(){s_oStage.removeChild(d);var a=this;d.off("pressup",function(){a._onExitHelp()})};this._onExitHelp=function(){e.unload();s_oGame._onExitHelp()};e=this;this._init()}
function CGfxButton(a,c,b){var f,d,e;this._init=function(a,b,c){f=[];d=[];e=createBitmap(c);e.x=a;e.y=b;e.regX=c.width/2;e.regY=c.height/2;s_oStage.addChild(e);this._initListener()};this.unload=function(){e.off("mousedown",this.buttonDown);e.off("pressup",this.buttonRelease);s_oStage.removeChild(e)};this.setVisible=function(a){e.visible=a};this._initListener=function(){e.on("mousedown",this.buttonDown);e.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){f[a]=b;d[a]=c};this.buttonRelease=
function(){e.scaleX=1;e.scaleY=1;f[ON_MOUSE_UP]&&f[ON_MOUSE_UP].call(d[ON_MOUSE_UP])};this.buttonDown=function(){e.scaleX=.9;e.scaleY=.9;f[ON_MOUSE_DOWN]&&f[ON_MOUSE_DOWN].call(d[ON_MOUSE_DOWN])};this.setPosition=function(a,b){e.x=a;e.y=b};this.setX=function(a){e.x=a};this.setY=function(a){e.y=a};this.getButtonImage=function(){return e};this.getX=function(){return e.x};this.getY=function(){return e.y};this._init(a,c,b);return this}
function CGame(a){var c,b,f,d,e,g,h,k,l,m,n,p,q,t=null,r,u,v=null;this._init=function(){b=c=!1;f=PAWN_BLACK;m=l=h=k=e=0;var a=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(a);q=new CInterface;u=new createjs.Container;u.x=CANVAS_WIDTH/2;u.y=CANVAS_HEIGHT/2;s_oStage.addChild(u);this._initGrid();this.calcFlipCounts();new CHelpPanel};this._initGrid=function(){var a=NUM_CELL,b=CELL_LENGTH,c=-BOARD_LENGTH/2+b/2;n=[];for(var f=0;f<a;f++){n[f]=[];for(var e=0;e<a;e++)n[f][e]={x:c+e*
b,y:c+f*b}}p=[];for(f=0;f<a;f++)for(p[f]=[],e=0;e<a;e++)p[f][e]=new CCell(n[f][e].x,n[f][e].y,-1,f,e,u);p[3][3].setColor(PAWN_WHITE);p[4][4].setColor(PAWN_WHITE);p[3][4].setColor(PAWN_BLACK);p[4][3].setColor(PAWN_BLACK);g=4;this.countPawn();q.activePlayer(PAWN_BLACK)};this.changeTurn=function(){if(g===TOT_CELL)this.resetFlips(),this.gameOver();else if(f=f===PAWN_BLACK?PAWN_WHITE:PAWN_BLACK,q.activePlayer(f),this.calcFlipCounts(),!b)e++,2===e?new CAlertPanel(TEXT_STALL,f,ALERT_TYPE_STALL):new CAlertPanel(TEXT_NOMOVES,
f,ALERT_TYPE_NOMOVES);else if(f===PAWN_WHITE&&s_iGameType===MODE_COMPUTER){v=new CThinking;var a=MIN_AI_THINKING+Math.random()*(MAX_AI_THINKING-MIN_AI_THINKING);setTimeout(function(){v.unload();v=null;r.othelloAI()},a)}};this.cellClicked=function(a,b,c){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click_cell");this.resetFlips();g++;d=c;p[a][b].setColor(f);this.cellFlips(a,b);this.countPawn()};this.setShowNumFlip=function(){this.calcFlipCounts()};this.restartGame=function(){this.unload();
this._init()};this.pauseGame=function(a){c=!a};this.unload=function(){c=!1;q.unload();null!==t&&t.unload();createjs.Tween.removeAllTweens();s_oStage.removeAllChildren()};this.onExit=function(){this.unload();s_oMain.gotoMenu();$(s_oMain).trigger("restart")};this._onExitHelp=function(){c=!0};this.gameOver=function(){t=CEndPanel(s_oSpriteLibrary.getSprite("msg_box"));t.show(k,h,l,m);q.setInfoVisible(!1)};this.update=function(){c&&(null!==v&&v.update(),f===PAWN_WHITE?(m+=s_iTimeElaps,q.refreshWhiteTime(m)):
(l+=s_iTimeElaps,q.refreshBlackTime(l)))};this.numFlips=function(a,b){var c,e,d,g,h,l=0;for(e=-1;1>=e;e++)for(c=-1;1>=c;c++)for(d=1;;d++){g=a+d*c;h=b+d*e;if(0>g||g>=NUM_CELL||0>h||h>=NUM_CELL)break;if(p[g][h].getType()===PAWN_NULL)break;if(p[g][h].getType()===f){l+=d-1;break}}return l};this.cellFlips=function(a,b){var c,e,d,g,h;for(e=-1;1>=e;e++)for(c=-1;1>=c;c++)for(d=1;;d++){g=a+d*c;h=b+d*e;if(0>g||g>=NUM_CELL||0>h||h>=NUM_CELL)break;if(p[g][h].getType()===PAWN_NULL)break;if(p[g][h].getType()===
f){for(d--;0<d;d--)g=a+d*c,h=b+d*e,p[g][h].reversi();break}}return 0};this.onFlipsEnd=function(){d--;0===d&&this.changeTurn()};this.calcFlipCounts=function(){for(var a=0;a<NUM_CELL;a++)for(var c=0;c<NUM_CELL;c++)p[a][c].setNumFlips(0),p[a][c].getType()===PAWN_NULL&&(p[a][c].setNumFlips(this.numFlips(a,c)),0<p[a][c].getNumFlips()&&(b=!0,e=0,f===PAWN_WHITE&&s_iGameType===MODE_COMPUTER?p[a][c].setClickableArea(!1,!1,f):p[a][c].setClickableArea(!0,s_bShowFlip,f)))};this.resetFlips=function(){for(var a=
0;a<NUM_CELL;a++)for(var c=0;c<NUM_CELL;c++)p[a][c].setClickableArea(!1);b=!1};this.countPawn=function(){for(var a,b=h=k=0;b<NUM_CELL;b++)for(var c=0;c<NUM_CELL;c++)a=p[b][c].getType(),0===a?k++:1===a&&h++;q.refreshBlackPawnNumber(k);q.refreshWhitePawnNumber(h)};this.rate=function(a,b){var c;if(p[a][b].getType()!==PAWN_NULL||0>a||a>=NUM_CELL||0>b||b>=NUM_CELL)return 0;c=p[a][b].getNumFlips();s_bWeightSquares||(c=0<c?1:0);if(s_bEdgeSensitive&&0<c){c+=10;if(0===a||a===NUM_CELL-1)c+=4;if(0===b||b===
NUM_CELL-1)c+=4;if(1===a||a===NUM_CELL-2)c-=5;if(1===b||b===NUM_CELL-2)c-=5;1>c&&(c=1)}return c};this.othelloAI=function(){var a,b,c=0,e=0,f,d,g;for(b=0;b<NUM_CELL;b++)for(a=0;a<NUM_CELL;a++)f=this.rate(a,b),p[a][b].setWeight(f),f===c?e++:f>c&&(c=f,e=1);for(;0<e;)for(d=Math.floor(Math.random()*e),b=g=0;b<NUM_CELL;b++)for(a=0;a<NUM_CELL;a++)if(f=p[a][b].getWeight(),f===c){if(g===d){this.cellClicked(a,b,p[a][b].getNumFlips());return}g++}};s_oGame=this;r=this;this._init()}var s_oGame;
function CEndPanel(a){var c,b,f,d,e;this._init=function(a){s_oGame.pauseGame(!0);c=createBitmap(a);c.x=0;c.y=0;e=new createjs.Text("","bold 60px Arial","#ffffff");e.x=CANVAS_WIDTH/2;e.y=CANVAS_HEIGHT/2+200;e.textAlign="center";e.textBaseline="alphabetic";e.lineWidth=500;b=new createjs.Container;b.alpha=0;b.visible=!1;b.addChild(c,e);f=new CInfoTurn(CANVAS_WIDTH/2,820,PAWN_BLACK,b);f.setBgVisible(!1);d=new CInfoTurn(CANVAS_WIDTH/2,670,PAWN_BLACK,b);d.setBgVisible(!1);d.setPawn(PAWN_WHITE);s_oStage.addChild(b)};
this.unload=function(){b.off("mousedown",this._onExit)};this._initListener=function(){b.on("mousedown",this._onExit)};this.show=function(a,c,k,l){f.refreshTime(formatTime(k));d.refreshTime(formatTime(l));f.refreshPawnNumber(a);d.refreshPawnNumber(c);if(a>c)!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("win"),e.text=TEXT_BLACK+" "+TEXT_GAMEOVER;else if(a<c){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_iGameType===MODE_COMPUTER?createjs.Sound.play("game_over"):createjs.Sound.play("win");
e.text=TEXT_WHITE+" "+TEXT_GAMEOVER}else!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("game_over"),e.text=TEXT_DRAW;b.visible=!0;var m=this;createjs.Tween.get(b).to({alpha:1},500).call(function(){m._initListener()});$(s_oMain).trigger("save_score",[a,c,k,l])};this._onExit=function(){b.off("mousedown",this._onExit);f.unload();d.unload();s_oStage.removeChild(b);s_oGame.onExit()};this._init(a);return this}
function CConfigPanel(){var a,c=null,b,f,d,e;this._init=function(){s_oGame.pauseGame(!0);a=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));s_oStage.addChild(a);var g=s_oSpriteLibrary.getSprite("but_exit");f=new CGfxButton(993,640,g,!0);f.addEventListener(ON_MOUSE_UP,this._onExit,this);!1===DISABLE_SOUND_MOBILE||!1===s_bMobile?(g=s_oSpriteLibrary.getSprite("audio_icon_big"),c=new CToggle(350,860,g,s_bAudioActive),c.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this),b=new createjs.Text(TEXT_AUDIO,
"bold 60px arialrounded","#ffffff"),b.x=460,b.y=860,b.textAlign="left",b.textBaseline="middle",b.lineWidth=600,s_oStage.addChild(b),g=s_oSpriteLibrary.getSprite("but_boh"),d=new CToggle(350,1130,g,s_bShowFlip),d.addEventListener(ON_MOUSE_UP,this._onShowNumFlip,this),e=new createjs.Text(TEXT_COUNT,"bold 60px arialrounded","#ffffff"),e.x=460,e.y=1130):(g=s_oSpriteLibrary.getSprite("audio_icon_big"),d=new CToggle(350,860,g,s_bShowFlip),d.addEventListener(ON_MOUSE_UP,this._onShowNumFlip,this),e=new createjs.Text(TEXT_COUNT,
"bold 60px arialrounded","#ffffff"),e.x=460,e.y=860);e.textAlign="left";e.textBaseline="middle";e.lineWidth=600;s_oStage.addChild(e)};this.unload=function(){s_oStage.removeChild(e);s_oStage.removeChild(a);f.unload();d.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oStage.removeChild(b),c.unload();s_oGame.pauseGame(!1)};this._onExit=function(){this.unload()};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onShowNumFlip=function(){s_bShowFlip=
!s_bShowFlip;s_oGame.setShowNumFlip()};this._init()}
function CCell(a,c,b,f,d,e){var g,h,k,l=0,m,n,p,q,t,r;this._init=function(a,b,c,e,f,d){g=c;h=e;k=f;n=new createjs.Container;n.x=a;n.y=b;d.addChild(n);a={images:[s_oSpriteLibrary.getSprite("pawn")],frames:{width:PAWN_SIZE,height:PAWN_SIZE,regX:PAWN_SIZE/2,regY:PAWN_SIZE/2},animations:{black:[0],white:[1]}};a=new createjs.SpriteSheet(a);p=createSprite(a,c,PAWN_SIZE/2,PAWN_SIZE/2,PAWN_SIZE,PAWN_SIZE);p.stop();n.addChild(p);t=new createjs.Shape;t.graphics.setStrokeStyle(8);t.graphics.beginStroke("rgba(255,255,255,1)").drawCircle(0,
0,35);t.visible=!1;n.addChild(t);r=new createjs.Text(l,"bold 50px arialrounded","#ffffff");r.textAlign="center";r.textBaseline="middle";r.visible=!1;n.addChild(r);q=new createjs.Shape;q.graphics.beginFill("rgba(158,0,0,0.01)").drawRect(-CELL_LENGTH/2,-CELL_LENGTH/2,CELL_LENGTH,CELL_LENGTH);q.on("mousedown",this._onCellClick);q.visible=!1;n.addChild(q)};this.unload=function(){e.removeChild(n);q.off("mousedown",this._onCellClick)};this.setClickableArea=function(a,b,c){q.visible=a;r.text=l;c===PAWN_WHITE?
(r.color="white",t.graphics.beginStroke("rgba(255,255,255,1)").drawCircle(0,0,35)):(r.color="black",t.graphics.beginStroke("rgba(0,0,0,1)").drawCircle(0,0,35));b?(t.visible=a,r.visible=a):(t.visible=!1,r.visible=!1)};this.setColor=function(a){g===PAWN_NULL&&(p.gotoAndStop(a),g=a)};this.reversi=function(){g===PAWN_WHITE?(g=PAWN_BLACK,createjs.Tween.get(n).to({scaleX:.1},200).call(function(){p.gotoAndStop(PAWN_BLACK)}).to({scaleX:1},200).call(function(){s_oGame.onFlipsEnd()})):(g=PAWN_WHITE,createjs.Tween.get(n).to({scaleX:.1},
200).call(function(){p.gotoAndStop(PAWN_WHITE)}).to({scaleX:1},200).call(function(){s_oGame.onFlipsEnd()}))};this._onCellClick=function(){s_oGame.cellClicked(h,k,l)};this.getType=function(){return g};this.setNumFlips=function(a){l=a};this.getNumFlips=function(){return l};this.setWeight=function(a){m=a};this.getWeight=function(){return m};this._init(a,c,b,f,d,e)}
function CAlertPanel(a,c,b){var f,d,e,g;this._init=function(a,c){s_oGame.pauseGame(!0);f=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));s_oStage.addChild(f);if(b===ALERT_TYPE_NOMOVES){var l=s_oSpriteLibrary.getSprite("pawn"),l=new createjs.SpriteSheet({images:[l],frames:{width:PAWN_SIZE,height:PAWN_SIZE,regX:PAWN_SIZE/2,regY:PAWN_SIZE/2},animations:{black:[0],white:[1]}});g=createSprite(l,c,PAWN_SIZE/2,PAWN_SIZE/2,PAWN_SIZE,PAWN_SIZE);g.stop();g.x=CANVAS_WIDTH/2;g.y=800;s_oStage.addChild(g)}l=
s_oSpriteLibrary.getSprite("but_exit");d=new CGfxButton(993,640,l,!0);d.addEventListener(ON_MOUSE_UP,this._onExit,this);e=new createjs.Text(a,"bold 80px arialrounded","#ffffff");e.x=CANVAS_WIDTH/2;e.y=CANVAS_HEIGHT/2;e.textAlign="center";e.textBaseline="midlle";e.lineWidth=600;s_oStage.addChild(e)};this.unload=function(){d.unload();s_oStage.removeChild(f);s_oStage.removeChild(e);s_oStage.removeChild(g);s_oGame.pauseGame(!1)};this._onExit=function(){this.unload();b===ALERT_TYPE_NOMOVES?s_oGame.changeTurn():
s_oGame.gameOver()};this._init(a,c)}
function CSpriteLibrary(){var a,c,b,f,d,e;this.init=function(g,h,k){b=c=0;f=g;d=h;e=k;a={}};this.addSprite=function(b,e){a.hasOwnProperty(b)||(a[b]={szPath:e,oSprite:new Image},c++)};this.getSprite=function(b){return a.hasOwnProperty(b)?a[b].oSprite:null};this._onSpritesLoaded=function(){d.call(e)};this._onSpriteLoaded=function(){f.call(e);++b==c&&this._onSpritesLoaded()};this.loadSprites=function(){for(var b in a)a[b].oSprite.oSpriteLibrary=this,a[b].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
a[b].oSprite.src=a[b].szPath};this.getNumSprites=function(){return c}}
var CANVAS_WIDTH=1280,CANVAS_HEIGHT=1920,EDGEBOARD_X=190,EDGEBOARD_Y=220,FPS_TIME=1E3/24,DISABLE_SOUND_MOBILE=!1,STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,MODE_HUMAN=0,MODE_COMPUTER=1,EASY_MODE=0,MEDIUM_MODE=1,HARD_MODE=2,PAWN_BLACK=0,PAWN_WHITE=1,PAWN_NULL=-1,ALERT_TYPE_NOMOVES=0,ALERT_TYPE_STALL=1,BOARD_LENGTH=784,NUM_CELL=8,TOT_CELL=64,CELL_LENGTH=BOARD_LENGTH/NUM_CELL,PAWN_SIZE=96,TIME_LOOP_WAIT=
1E3,MIN_AI_THINKING=1E3,MAX_AI_THINKING=1500;
function CToggle(a,c,b,f){var d,e,g,h,k=[];this._init=function(a,b,c,f){e=[];g=[];var k=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_true:[0],state_false:[1]}});d=f;h=createSprite(k,"state_"+d,c.width/2/2,c.height/2,c.width/2,c.height);h.x=a;h.y=b;h.stop();s_oStage.addChild(h);this._initListener()};this.unload=function(){h.off("mousedown",this.buttonDown);h.off("pressup",this.buttonRelease);s_oStage.removeChild(h)};
this._initListener=function(){h.on("mousedown",this.buttonDown);h.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){e[a]=b;g[a]=c};this.addEventListenerWithParams=function(a,b,c,f){e[a]=b;g[a]=c;k=f};this.setActive=function(a){d=a;h.gotoAndStop("state_"+d)};this.buttonRelease=function(){h.scaleX=1;h.scaleY=1;!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");d=!d;h.gotoAndStop("state_"+d);e[ON_MOUSE_UP]&&e[ON_MOUSE_UP].call(g[ON_MOUSE_UP],k)};this.buttonDown=
function(){h.scaleX=.9;h.scaleY=.9;e[ON_MOUSE_DOWN]&&e[ON_MOUSE_DOWN].call(g[ON_MOUSE_DOWN],k)};this.setPosition=function(a,b){h.x=a;h.y=b};this._init(a,c,b,f)}var s_iScaleFactor=1,s_oCanvasLeft,s_oCanvasTop;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,
4))})(navigator.userAgent||navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}
function getSize(a){var c=a.toLowerCase(),b=window.document,f=b.documentElement;if(void 0===window["inner"+a])a=f["client"+a];else if(window["inner"+a]!=f["client"+a]){var d=b.createElement("body");d.id="vpw-test-b";d.style.cssText="overflow:scroll";var e=b.createElement("div");e.id="vpw-test-d";e.style.cssText="position:absolute;top:-1000px";e.innerHTML="<style>@media("+c+":"+f["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+c+":7px!important}}</style>";d.appendChild(e);f.insertBefore(d,b.head);
a=7==e["offset"+a]?f["client"+a]:window["inner"+a];f.removeChild(d)}else a=window["inner"+a];return a}$(window).ready(function(){sizeHandler()});window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}
function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a;a=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var c=getSize("Width"),b=Math.min(a/CANVAS_HEIGHT,c/CANVAS_WIDTH),f=CANVAS_WIDTH*b,b=CANVAS_HEIGHT*b,d=0;b<a?(d=a-b,b+=d,f+=CANVAS_WIDTH/CANVAS_HEIGHT*d):f<c&&(d=c-f,f+=d,b+=CANVAS_HEIGHT/CANVAS_WIDTH*d);var d=a/2-b/2,e=c/2-f/2,g=CANVAS_WIDTH/f;if(e*g<-EDGEBOARD_X||d*g<-EDGEBOARD_Y)b=Math.min(a/(CANVAS_HEIGHT-2*EDGEBOARD_Y),c/(CANVAS_WIDTH-2*
EDGEBOARD_X)),f=CANVAS_WIDTH*b,b*=CANVAS_HEIGHT,d=(a-b)/2,e=(c-f)/2,g=CANVAS_WIDTH/f;s_iOffsetX=-1*e*g;s_iOffsetY=-1*d*g;0<=d&&(s_iOffsetY=0);0<=e&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oModeMenu&&s_oModeMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);$("#canvas").css("width",f+"px");$("#canvas").css("height",b+"px");0>d?$("#canvas").css("top",d+"px"):$("#canvas").css("top","0px");
$("#canvas").css("left",e+"px")}}function createBitmap(a,c,b){var f=new createjs.Bitmap(a),d=new createjs.Shape;c&&b?d.graphics.beginFill("#fff").drawRect(0,0,c,b):d.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);f.hitArea=d;return f}function createSprite(a,c,b,f,d,e){a=null!==c?new createjs.Sprite(a,c):new createjs.Sprite(a);c=new createjs.Shape;c.graphics.beginFill("#000000").drawRect(-b,-f,d,e);a.hitArea=c;return a}
function pad(a,c,b){a+="";return a.length>=c?a:Array(c-a.length+1).join(b||"0")+a}function randomFloatBetween(a,c,b){"undefined"===typeof b&&(b=2);return parseFloat(Math.min(a+Math.random()*(c-a),c).toFixed(b))}function rotateVector2D(a,c){var b=c.getX()*Math.cos(a)+c.getY()*Math.sin(a),f=c.getX()*-Math.sin(a)+c.getY()*Math.cos(a);c.set(b,f)}function tweenVectorsOnX(a,c,b){return a+b*(c-a)}
function shuffle(a){for(var c=a.length,b,f;0!==c;)f=Math.floor(Math.random()*c),--c,b=a[c],a[c]=a[f],a[f]=b;return a}function bubbleSort(a){var c;do{c=!1;for(var b=0;b<a.length-1;b++)a[b]>a[b+1]&&(c=a[b],a[b]=a[b+1],a[b+1]=c,c=!0)}while(c)}function compare(a,c){return a.index>c.index?-1:a.index<c.index?1:0}function easeLinear(a,c,b,f){return b*a/f+c}function easeInQuad(a,c,b,f){return b*(a/=f)*a+c}function easeInSine(a,c,b,f){return-b*Math.cos(a/f*(Math.PI/2))+b+c}
function easeInCubic(a,c,b,f){return b*(a/=f)*a*a+c}function getTrajectoryPoint(a,c){var b=new createjs.Point,f=(1-a)*(1-a),d=a*a;b.x=f*c.start.x+2*(1-a)*a*c.traj.x+d*c.end.x;b.y=f*c.start.y+2*(1-a)*a*c.traj.y+d*c.end.y;return b}function formatTime(a){a/=1E3;var c=Math.floor(a/60);a=Math.floor(a-60*c);var b="",b=10>c?b+("0"+c+":"):b+(c+":");return 10>a?b+("0"+a):b+a}function degreesToRadians(a){return a*Math.PI/180}
function checkRectCollision(a,c){var b,f;b=getBounds(a,.9);f=getBounds(c,.98);return calculateIntersection(b,f)}function calculateIntersection(a,c){var b,f,d,e,g,h,k,l;b=a.x+(d=a.width/2);f=a.y+(e=a.height/2);g=c.x+(h=c.width/2);k=c.y+(l=c.height/2);b=Math.abs(b-g)-(d+h);f=Math.abs(f-k)-(e+l);return 0>b&&0>f?(b=Math.min(Math.min(a.width,c.width),-b),f=Math.min(Math.min(a.height,c.height),-f),{x:Math.max(a.x,c.x),y:Math.max(a.y,c.y),width:b,height:f,rect1:a,rect2:c}):null}
function getBounds(a,c){var b={x:Infinity,y:Infinity,width:0,height:0};if(a instanceof createjs.Container){b.x2=-Infinity;b.y2=-Infinity;var f=a.children,d=f.length,e,g;for(g=0;g<d;g++)e=getBounds(f[g],1),e.x<b.x&&(b.x=e.x),e.y<b.y&&(b.y=e.y),e.x+e.width>b.x2&&(b.x2=e.x+e.width),e.y+e.height>b.y2&&(b.y2=e.y+e.height);Infinity==b.x&&(b.x=0);Infinity==b.y&&(b.y=0);Infinity==b.x2&&(b.x2=0);Infinity==b.y2&&(b.y2=0);b.width=b.x2-b.x;b.height=b.y2-b.y;delete b.x2;delete b.y2}else{var h,k;a instanceof createjs.Bitmap?
(d=a.sourceRect||a.image,g=d.width*c,h=d.height*c):a instanceof createjs.Sprite?a.spriteSheet._frames&&a.spriteSheet._frames[a.currentFrame]&&a.spriteSheet._frames[a.currentFrame].image?(d=a.spriteSheet.getFrame(a.currentFrame),g=d.rect.width,h=d.rect.height,f=d.regX,k=d.regY):(b.x=a.x||0,b.y=a.y||0):(b.x=a.x||0,b.y=a.y||0);f=f||0;g=g||0;k=k||0;h=h||0;b.regX=f;b.regY=k;d=a.localToGlobal(0-f,0-k);e=a.localToGlobal(g-f,h-k);g=a.localToGlobal(g-f,0-k);f=a.localToGlobal(0-f,h-k);b.x=Math.min(Math.min(Math.min(d.x,
e.x),g.x),f.x);b.y=Math.min(Math.min(Math.min(d.y,e.y),g.y),f.y);b.width=Math.max(Math.max(Math.max(d.x,e.x),g.x),f.x)-b.x;b.height=Math.max(Math.max(Math.max(d.y,e.y),g.y),f.y)-b.y}return b}function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}function shuffle(a){for(var c=a.length,b,f;0<c;)f=Math.floor(Math.random()*c),c--,b=a[c],a[c]=a[f],a[f]=b;return a}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3==a.nodeType&&(a=a.parentNode);var c=document.createEvent("MouseEvents");c.initEvent("click",!0,!0);a.dispatchEvent(c)}}};
(function(){function a(a){var f={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};a=a||window.event;a.type in f?document.body.className=f[a.type]:(document.body.className=this[c]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var c="hidden";c in document?document.addEventListener("visibilitychange",a):(c="mozHidden")in document?document.addEventListener("mozvisibilitychange",a):(c="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",a):(c="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a})();
function CThinking(){var a,c,b,f,d,e;this._init=function(){a=!0;c=0;b=new createjs.Container;var g=(new createjs.Graphics).beginFill("rgba(0,0,0,0.01)").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);e=new createjs.Shape(g);e.on("click",function(){});f=new createjs.Text(TEXT_THINKING,"bold 60px arialrounded","#ffffff");f.x=.5*CANVAS_WIDTH;f.y=.5*CANVAS_HEIGHT-100;f.textAlign="center";f.textBaseline="alphabetic";f.lineWidth=800;d=new createjs.Text("","bold 180px arialrounded","#ffffff");d.x=.5*CANVAS_WIDTH-
76;d.y=.5*CANVAS_HEIGHT-50;d.textAlign="left";d.textBaseline="alphabetic";d.lineWidth=800;b.addChild(e,f,d);s_oStage.addChild(b)};this.unload=function(){a=!1;e.off("click",function(){});s_oStage.removeChild(b)};this.update=function(){a&&(c+=s_iTimeElaps,0<=c&&c<TIME_LOOP_WAIT/4?d.text="":c>=TIME_LOOP_WAIT/4&&c<2*TIME_LOOP_WAIT/4?d.text=".":c>=2*TIME_LOOP_WAIT/4&&c<3*TIME_LOOP_WAIT/4?d.text="..":c>=3*TIME_LOOP_WAIT/4&&c<TIME_LOOP_WAIT?d.text="...":c=0)};this._init()}
function CTextButton(a,c,b,f,d,e,g){var h,k,l,m,n;this._init=function(a,b,c,e,f,d,g){h=[];k=[];var y=createBitmap(c),x=Math.ceil(g/20);n=new createjs.Text(e,"bold "+g+"px "+f,"#000000");n.textAlign="center";n.textBaseline="alphabetic";var w=n.getBounds();n.x=c.width/2+x;n.y=Math.floor(c.height/2)+w.height/3+x;m=new createjs.Text(e,"bold "+g+"px "+f,d);m.textAlign="center";m.textBaseline="alphabetic";w=m.getBounds();m.x=c.width/2;m.y=Math.floor(c.height/2)+w.height/3;l=new createjs.Container;l.x=a;
l.y=b;l.regX=c.width/2;l.regY=c.height/2;l.addChild(y,n,m);s_oStage.addChild(l);this._initListener()};this.unload=function(){l.off("mousedown");l.off("pressup");s_oStage.removeChild(l)};this.setVisible=function(a){l.visible=a};this._initListener=function(){oParent=this;l.on("mousedown",this.buttonDown);l.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){h[a]=b;k[a]=c};this.buttonRelease=function(){l.scaleX=1;l.scaleY=1;h[ON_MOUSE_UP]&&h[ON_MOUSE_UP].call(k[ON_MOUSE_UP])};this.buttonDown=
function(){l.scaleX=.9;l.scaleY=.9;h[ON_MOUSE_DOWN]&&h[ON_MOUSE_DOWN].call(k[ON_MOUSE_DOWN])};this.setTextPosition=function(a){m.y=a;n.y=a+2};this.setPosition=function(a,b){l.x=a;l.y=b};this.setX=function(a){l.x=a};this.setY=function(a){l.y=a};this.getButtonImage=function(){return l};this.getX=function(){return l.x};this.getY=function(){return l.y};this._init(a,c,b,f,d,e,g);return this}
function CPreloader(){var a,c,b,f,d,e,g;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.loadSprites();g=new createjs.Container;s_oStage.addChild(g)};this.unload=function(){g.removeAllChildren()};this.hide=function(){var a=this;setTimeout(function(){createjs.Tween.get(e).to({alpha:1},500).call(function(){a.unload();
s_oMain.gotoMenu()})},1E3)};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var h=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));g.addChild(h);h=s_oSpriteLibrary.getSprite("progress_bar");f=createBitmap(h);f.x=CANVAS_WIDTH/2-h.width/2;f.y=CANVAS_HEIGHT-370;g.addChild(f);a=h.width;c=h.height;d=new createjs.Shape;d.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(f.x,f.y,1,c);g.addChild(d);f.mask=
d;b=new createjs.Text("","30px Arial","#fff");b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT-325;b.shadow=new createjs.Shadow("#000",2,2,2);b.textBaseline="alphabetic";b.textAlign="center";g.addChild(b);e=new createjs.Shape;e.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);e.alpha=0;g.addChild(e)};this.refreshLoader=function(e){b.text=e+"%";d.graphics.clear();e=Math.floor(e*a/100);d.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(f.x,f.y,e,c)};this._init()}
function CModeMenu(){var a,c,b,f,d=MEDIUM_MODE,e,g,h,k,l,m=null,n,p,q;this._init=function(){var d=createBitmap(s_oSpriteLibrary.getSprite("bg_mod_menu"));s_oStage.addChild(d);d=s_oSpriteLibrary.getSprite("but_exit");a=CANVAS_WIDTH-d.height/2-20;c=d.height/2+10;l=new CGfxButton(a,c,d,!0);l.addEventListener(ON_MOUSE_UP,this._onExit,this);b=CANVAS_WIDTH-d.width/2-125;f=d.height/2+10;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)d=s_oSpriteLibrary.getSprite("audio_icon"),m=new CToggle(b,f,d,s_bAudioActive),
m.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);e=new createjs.Text(TEXT_MODE,"bold 80px arialrounded","#ffffff");e.x=CANVAS_WIDTH/2;e.y=300;e.textAlign="center";e.textBaseline="middle";e.lineWidth=600;s_oStage.addChild(e);d=s_oSpriteLibrary.getSprite("but_vs_man");h=new CGfxButton(CANVAS_WIDTH/2,700,d,!0);h.addEventListener(ON_MOUSE_UP,this._onButHumanRelease,this);d=s_oSpriteLibrary.getSprite("but_vs_pc");k=new CGfxButton(CANVAS_WIDTH/2,1200,d,!0);k.addEventListener(ON_MOUSE_UP,this._onButComputerRelease,
this);var d=s_oSpriteLibrary.getSprite("difficulty_panel"),r=createBitmap(d);r.regX=d.width/2;r.regY=d.height/2;r.x=CANVAS_WIDTH/2;r.y=1510;s_oStage.addChild(r);g=new createjs.Text(TEXT_DIFFICULTY,"bold 40px arialrounded","#ffffff");g.x=CANVAS_WIDTH/2;g.y=1440;g.textAlign="center";g.textBaseline="middle";g.lineWidth=600;s_oStage.addChild(g);d=s_oSpriteLibrary.getSprite("toggle_easy");n=new CToggle(CANVAS_WIDTH/2-170,1525,d,!1);n.addEventListenerWithParams(ON_MOUSE_UP,this._onDifficultyToggle,this,
EASY_MODE);d=s_oSpriteLibrary.getSprite("toggle_medium");p=new CToggle(CANVAS_WIDTH/2-5,1525,d,!0);p.addEventListenerWithParams(ON_MOUSE_UP,this._onDifficultyToggle,this,MEDIUM_MODE);d=s_oSpriteLibrary.getSprite("toggle_hard");q=new CToggle(CANVAS_WIDTH/2+165,1525,d,!1);q.addEventListenerWithParams(ON_MOUSE_UP,this._onDifficultyToggle,this,HARD_MODE);this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){h.unload();k.unload();l.unload();n.unload();p.unload();q.unload();if(!1===DISABLE_SOUND_MOBILE||
!1===s_bMobile)m.unload(),m=null;s_oModeMenu=null;s_oStage.removeAllChildren()};this.refreshButtonPos=function(d,e){l.setPosition(a-d,e+c);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||m.setPosition(b-d,e+f)};this._onDifficultyToggle=function(a){switch(a){case EASY_MODE:n.setActive(!0);p.setActive(!1);q.setActive(!1);d=EASY_MODE;break;case MEDIUM_MODE:n.setActive(!1);p.setActive(!0);q.setActive(!1);d=MEDIUM_MODE;break;case HARD_MODE:n.setActive(!1),p.setActive(!1),q.setActive(!0),d=HARD_MODE}};this._onAudioToggle=
function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onExit=function(){this.unload();s_oMain.gotoMenu()};this._onButHumanRelease=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");this.unload();s_oMain.gotoGame(MODE_HUMAN)};this._onButComputerRelease=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");this.unload();s_oMain.gotoGame(MODE_COMPUTER,d)};s_oModeMenu=this;this._init()}var s_oModeMenu=null;
function CMenu(){var a,c,b,f,d,e;this._init=function(){b=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(b);var g=s_oSpriteLibrary.getSprite("but_play");f=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-500,g);f.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)g=s_oSpriteLibrary.getSprite("audio_icon"),a=CANVAS_WIDTH-g.height/2-10,c=g.height/2+10,e=new CToggle(a,c,g,s_bAudioActive),e.addEventListener(ON_MOUSE_UP,this._onAudioToggle,
this);d=new createjs.Shape;d.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(d);createjs.Tween.get(d).to({alpha:0},1E3).call(function(){d.visible=!1});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){f.unload();f=null;d.visible=!1;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)e.unload(),e=null;s_oStage.removeChild(b);s_oMenu=b=null};this.refreshButtonPos=function(b,d){e.setPosition(a-b,d+c)};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);
s_bAudioActive=!s_bAudioActive};this._onButPlayRelease=function(){this.unload();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");s_oMain.gotoModeMenu()};s_oMenu=this;this._init()}var s_oMenu=null;
function CMain(a){var c,b=0,f=0,d=STATE_LOADING,e,g,h;this.initContainer=function(){s_oCanvas=document.getElementById("canvas");s_oStage=new createjs.Stage(s_oCanvas);createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&(s_oStage.enableMouseOver(20),$("body").on("contextmenu","#canvas",function(a){return!1}));s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.setFPS(30);navigator.userAgent.match(/Windows Phone/i)&&(DISABLE_SOUND_MOBILE=
!0);s_oSpriteLibrary=new CSpriteLibrary;g=new CPreloader};this.preloaderReady=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();this._loadImages();c=!0};this.soundLoaded=function(){b++;g.refreshLoader(Math.floor(b/f*100));if(b===f){g.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundtrack=createjs.Sound.play("soundtrack",{loop:-1});this.gotoMenu()}};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&(0<navigator.userAgent.indexOf("Opera")||0<
navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=["mp3"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/ot_soundtrack.ogg","soundtrack"),createjs.Sound.registerSound("./sounds/press_button.ogg","click"),createjs.Sound.registerSound("./sounds/ot_game_over.ogg","game_over"),createjs.Sound.registerSound("./sounds/ot_click_cell.ogg","click_cell")):(createjs.Sound.alternateExtensions=["ogg"],createjs.Sound.addEventListener("fileload",
createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/ot_soundtrack.mp3","soundtrack"),createjs.Sound.registerSound("./sounds/press_button.mp3","click"),createjs.Sound.registerSound("./sounds/ot_game_over.mp3","game_over"),createjs.Sound.registerSound("./sounds/ot_click_cell.mp3","click_cell")),createjs.Sound.registerSound("./sounds/ot_win.mp3","win"),f+=5)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_play",
"./sprites/but_play.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("bg_mod_menu","./sprites/bg_mod_menu.jpg");s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("but_vs_man","./sprites/but_vs_man.png");s_oSpriteLibrary.addSprite("but_vs_pc","./sprites/but_vs_pc.png");s_oSpriteLibrary.addSprite("difficulty_panel","./sprites/difficulty_panel.png");s_oSpriteLibrary.addSprite("toggle_easy",
"./sprites/toggle_easy.png");s_oSpriteLibrary.addSprite("toggle_medium","./sprites/toggle_medium.png");s_oSpriteLibrary.addSprite("toggle_hard","./sprites/toggle_hard.png");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("but_settings","./sprites/but_settings.png");s_oSpriteLibrary.addSprite("white_chip","./sprites/chip_vertical_white.png");s_oSpriteLibrary.addSprite("black_chip","./sprites/chip_vertical_black.png");
s_oSpriteLibrary.addSprite("bg_turn","./sprites/bg_turn.png");s_oSpriteLibrary.addSprite("time_icon","./sprites/time_icon.png");s_oSpriteLibrary.addSprite("audio_icon_big","./sprites/audio_icon_big.png");s_oSpriteLibrary.addSprite("but_boh","./sprites/but_boh.png");s_oSpriteLibrary.addSprite("pawn","./sprites/pawn.png");f+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){b++;g.refreshLoader(Math.floor(b/f*100));if(b===f){g.unload();if(!1===DISABLE_SOUND_MOBILE||
!1===s_bMobile)s_oSoundtrack=createjs.Sound.play("soundtrack",{loop:-1});this.gotoMenu()}};this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this.gotoMenu=function(){new CMenu;d=STATE_MENU};this.gotoModeMenu=function(){new CModeMenu;d=STATE_MENU};this.gotoGame=function(a,b){s_iGameType=a;switch(b){case EASY_MODE:s_bEdgeSensitive=s_bWeightSquares=!1;break;case MEDIUM_MODE:s_bWeightSquares=!1;s_bEdgeSensitive=!0;break;case HARD_MODE:s_bEdgeSensitive=
s_bWeightSquares=!0}h=new CGame(e);d=STATE_GAME;$(s_oMain).trigger("game_start")};this.gotoHelp=function(){new CHelp;d=STATE_HELP};this.stopUpdate=function(){c=!1};this.startUpdate=function(){c=!0};this._update=function(a){if(!1!==c){var b=(new Date).getTime();s_iTimeElaps=b-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=b;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);d===STATE_GAME&&h.update();s_oStage.update(a)}};s_oMain=this;e=a;this.initContainer()}
var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oSoundTrack,s_oCanvas,s_iGameType,s_bShowFlip=!0,s_bWeightSquares=!1,s_bEdgeSensitive=!1;TEXT_GAMEOVER="WINS";TEXT_DRAW="DRAW";TEXT_SCORE="SCORE";TEXT_PLAY="PLAY";TEXT_RESTART="RESTART";TEXT_MOVES="MOVES";TEXT_THINKING="THINKING";TEXT_MODE="CHOOSE GAME MODE";TEXT_DIFFICULTY="DIFFICULTY";TEXT_AUDIO="MUTE/PLAY AUDIO";TEXT_COUNT="SHOW/HIDE FLIP NUMBER";
TEXT_BLACK="BLACK";TEXT_WHITE="WHITE";TEXT_STALL="STALL";TEXT_NOMOVES="NO MORE MOVES";TEXT_HELP1="FLIP YOUR OPPONENT'S PIECES BY TRAPPING THEM BETWEEN TWO OF YOUR OWN.";TEXT_HELP2="YOUR AIM IS TO OWN MORE PIECES THAN YOUR OPPONENT WHEN THE GAME IS OVER.";