function CInterface(){var b,c,a,d,h=null,f,e,g,m,k,u,t,A,q,n;this._init=function(){var h,p=s_oSpriteLibrary.getSprite("but_exit");c=new CGfxButton(CANVAS_WIDTH-p.height/2-10,p.height/2+10,p,!0);c.addEventListener(ON_MOUSE_UP,this._onExit,this);h=CANVAS_WIDTH-p.width/2-80;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)p=s_oSpriteLibrary.getSprite("audio_icon"),b=new CToggle(h,10+p.height/2,p,s_bAudioActive),b.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);h-=68;p=s_oSpriteLibrary.getSprite("but_help");
a=new CGfxButton(h,10+p.height/2,p,!0);a.addEventListener(ON_MOUSE_UP,this._onButHelpRelease,this);a.setVisible(!1);h-=120;p=s_oSpriteLibrary.getSprite("but_shuffle");d=new CTextButton(h,10+p.height/2,p,TEXT_RESTART,"Arial","#ffffff",26);d.addEventListener(ON_MOUSE_UP,this._onButRestartRelease,this);d.setTextPosition(35);p=s_oSpriteLibrary.getSprite("score_moves_display");e=createBitmap(p);e.x=330;e.y=15;s_oStage.addChild(e);g=new createjs.Text("0","bold 24px Arial","#ffffff");g.x=380;g.y=45;g.textAlign=
"right";g.textBaseline="alphabetic";g.lineWidth=200;s_oStage.addChild(g);f=new createjs.Text(TEXT_MOVES,"bold 24px Arial","#ffffff");f.x=237;f.y=45;f.textAlign="left";f.textBaseline="alphabetic";f.lineWidth=200;s_oStage.addChild(f);p=s_oSpriteLibrary.getSprite("score_moves_display");m=createBitmap(p);m.scaleX=1.4;m.x=120;m.y=15;s_oStage.addChild(m);u=new createjs.Text("0","bold 24px Arial","#ffffff");u.x=193;u.y=45;u.textAlign="right";u.textBaseline="alphabetic";u.lineWidth=200;s_oStage.addChild(u);
k=new createjs.Text(TEXT_SCORE,"bold 24px Arial","#ffffff");k.x=30;k.y=45;k.textAlign="left";k.textBaseline="alphabetic";k.lineWidth=200;s_oStage.addChild(k);A=createBitmap(s_oSpriteLibrary.getSprite("hintpanel"));A.scaleX=.42;A.scaleY=.25;t=new createjs.Text(TEXT_HELP4,"bold 16px Arial","#ffffff");t.x=10;t.y=20;t.textAlign="left";t.textBaseline="alphabetic";t.lineWidth=200;q=new createjs.Container;q.addChild(A,t);q.x=900;q.y=400;q.alpha=0;s_oStage.addChild(q);n=[];n[0]={x:980-CARD_WIDTH/2,y:156-
CARD_HEIGHT/2};n[1]={x:1070-CARD_WIDTH/2,y:156-CARD_HEIGHT/2};n[2]={x:980-CARD_WIDTH/2,y:286-CARD_HEIGHT/2};n[3]={x:1070-CARD_WIDTH/2,y:286-CARD_HEIGHT/2};h=createBitmap(s_oSpriteLibrary.getSprite("hearts_suit"));h.x=n[0].x;h.y=n[0].y;p=createBitmap(s_oSpriteLibrary.getSprite("spades_suit"));p.x=n[1].x;p.y=n[1].y;var y=createBitmap(s_oSpriteLibrary.getSprite("diamonds_suit"));y.x=n[2].x;y.y=n[2].y;var r=createBitmap(s_oSpriteLibrary.getSprite("clubs_suit"));r.x=n[3].x;r.y=n[3].y;switch(s_iMode){case 0:s_oStage.addChild(p);
break;case 1:s_oStage.addChild(p);s_oStage.addChild(h);break;case 2:s_oStage.addChild(p),s_oStage.addChild(h),s_oStage.addChild(y),s_oStage.addChild(r)}};this.unload=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)b.unload(),b=null;c.unload();a.unload();d.unload();null!==h&&h.unload()};this.refreshScore=function(a){u.alpha=1;u.text=a};this.fadeScore=function(a,b){var c=this;createjs.Tween.get(u).to({alpha:0},b,createjs.Ease.linear).call(function(){c.refreshScore(a)})};this._refreshMove=function(a){g.alpha=
1;g.text=a};this.fadeMove=function(a,b){var c=this;createjs.Tween.get(g).to({alpha:0},b,createjs.Ease.linear).call(function(){c._refreshMove(a)})};this.showHint=function(){createjs.Tween.get(q,{override:!0}).to({alpha:1},3E3,createjs.Ease.linear).call(function(){createjs.Tween.get(q).to({alpha:0},3E3,createjs.Ease.linear)})};this.setVisibleButHelp=function(){a.setVisible(!0)};this._onButHelpRelease=function(){h=new CHelpPanel};this._onButRestartRelease=function(){s_oGame.restartGame()};this.onExitFromHelp=
function(){h.unload()};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onExit=function(){s_oGame.onExit()};this._init();return this}
function CHelpPanel(){var b,c,a,d,h,f,e,g,m,k,u,t,A,q,n,v,p,y,r;this._init=function(){var r=this;A=createBitmap(s_oSpriteLibrary.getSprite("bg_help"));var z=CANVAS_WIDTH/2,w=CANVAS_HEIGHT/2-190;c=new createjs.Text(TEXT_HELP1," 24px Arial","#000000");c.x=z+2;c.y=w+2;c.textAlign="center";c.lineWidth=400;b=new createjs.Text(TEXT_HELP1," 24px Arial","#ffffff");b.x=z;b.y=w;b.textAlign="center";b.lineWidth=400;z=CANVAS_WIDTH/2-180;w=CANVAS_HEIGHT/2-50;d=new createjs.Text(TEXT_HELP2," 24px Arial","#000000");
d.x=z+2;d.y=w+2;d.textAlign="center";d.lineWidth=300;a=new createjs.Text(TEXT_HELP2," 24px Arial","#ffffff");a.x=z;a.y=w;a.textAlign="center";a.lineWidth=300;z=CANVAS_WIDTH/2;w=CANVAS_HEIGHT/2+100;f=new createjs.Text(TEXT_HELP3," 24px Arial","#000000");f.x=z+2;f.y=w+2;f.textAlign="center";f.lineWidth=400;h=new createjs.Text(TEXT_HELP3," 24px Arial","#ffffff");h.x=z;h.y=w;h.textAlign="center";h.lineWidth=400;p=new createjs.Container;p.addChild(A,c,b,d,a,f,h);p.alpha=0;s_oStage.addChild(p);createjs.Tween.get(p).to({alpha:1},
700).call(function(){s_oGame.pauseGame()});p.on("pressup",function(){r._onExitHelp()});q=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));e=new createjs.Text(TEXT_HELP1_PAGE2," 30px Arial","#000000");e.x=CANVAS_WIDTH/2+2;e.y=CANVAS_HEIGHT/2-200;e.textAlign="center";e.lineWidth=400;g=new createjs.Text(TEXT_HELP1_PAGE2," 30px Arial","#ffffff");g.x=CANVAS_WIDTH/2;g.y=CANVAS_HEIGHT/2-202;g.textAlign="center";g.lineWidth=400;k=new createjs.Text(TEXT_HELP2_PAGE2+"+"+POINTS_TO_WIN+TEXT_WIN_PAGE2," 28px Arial",
"#000000");k.x=CANVAS_WIDTH/2-328;k.y=CANVAS_HEIGHT/2-88;k.textAlign="left";k.lineWidth=670;m=new createjs.Text(TEXT_HELP2_PAGE2+"+"+POINTS_TO_WIN+TEXT_WIN_PAGE2," 28px Arial","#ffffff");m.x=CANVAS_WIDTH/2-330;m.y=CANVAS_HEIGHT/2-90;m.textAlign="left";m.lineWidth=670;t=new createjs.Text(TEXT_LOSE1_PAGE2+POINTS_TO_LOSE+TEXT_LOSE2_PAGE2," 28px Arial","#000000");t.x=CANVAS_WIDTH/2-328;t.y=CANVAS_HEIGHT/2+32;t.textAlign="left";t.lineWidth=670;u=new createjs.Text(TEXT_LOSE1_PAGE2+POINTS_TO_LOSE+TEXT_LOSE2_PAGE2,
" 28px Arial","#ffffff");u.x=CANVAS_WIDTH/2-330;u.y=CANVAS_HEIGHT/2+30;u.textAlign="left";u.lineWidth=670;y=new createjs.Container;y.addChild(q,e,g,k,m,t,u);y.visible=0;s_oStage.addChild(y);y.on("pressup",function(){r._onExitHelp()});createjs.Tween.get(y).to({alpha:1},700);n=createBitmap(s_oSpriteLibrary.getSprite("arrow"));n.x=1E3;n.y=500;n.alpha=0;n.on("click",r._changePageTo2);s_oStage.addChild(n);v=createBitmap(s_oSpriteLibrary.getSprite("arrow"));v.scaleX=-1;v.x=140;v.y=500;v.visible=!1;v.on("click",
r._changePageTo1);s_oStage.addChild(v);createjs.Tween.get(n).to({alpha:1},700)};this.unload=function(){s_oStage.removeChild(p,y,n,v);var a=this;p.off("pressup",function(){a._onExitHelp()})};this._changePageTo1=function(){y.visible=!1;v.visible=!1;p.visible=!0;n.visible=!0};this._changePageTo2=function(){p.visible=!1;n.visible=!1;y.visible=!0;v.visible=!0};this._onExitHelp=function(){r.unload();s_oGame._onExitHelp()};r=this;this._init()}
function CGfxButton(b,c,a){var d,h,f;this._init=function(a,b,c){d=[];h=[];f=createBitmap(c);f.x=a;f.y=b;f.regX=c.width/2;f.regY=c.height/2;s_oStage.addChild(f);this._initListener()};this.unload=function(){f.off("mousedown",this.buttonDown);f.off("pressup",this.buttonRelease);s_oStage.removeChild(f)};this.setVisible=function(a){f.visible=a};this._initListener=function(){f.on("mousedown",this.buttonDown);f.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){d[a]=b;h[a]=c};this.buttonRelease=
function(){f.scaleX=1;f.scaleY=1;d[ON_MOUSE_UP]&&d[ON_MOUSE_UP].call(h[ON_MOUSE_UP])};this.buttonDown=function(){f.scaleX=.9;f.scaleY=.9;d[ON_MOUSE_DOWN]&&d[ON_MOUSE_DOWN].call(h[ON_MOUSE_DOWN])};this.setPosition=function(a,b){f.x=a;f.y=b};this.setX=function(a){f.x=a};this.setY=function(a){f.y=a};this.getButtonImage=function(){return f};this.getX=function(){return f.x};this.getY=function(){return f.y};this._init(b,c,a);return this}
function CGame(b){var c,a,d,h,f,e,g,m,k,u,t,A,q,n,v,p,y,r,D,z,w,C,x,F,l,E,H,I,L=null,J,B,M,G,N,O,K;this._init=function(){n=23;r=p=v=q=A=0;g=START_SCORE;m=0;f=e=!0;B=null;I=new CInterface;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)O=createjs.Sound.play("card_dealing",{loop:-1});var a=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(a);I=new CInterface;I.refreshScore(g);x=[];F=[];E=[];t=0;z=[];for(a=0;7>a;a++)for(var b=0;10>b;b++)z[t]={x:67+81*b,y:156+10*a},4<b&&(z[t]={x:68+81*
b,y:156+10*a}),t++;J=new createjs.Container;s_oStage.addChild(J);w=[];w[SUIT_HEARTS]={x:980,y:156};w[SUIT_SPADES]={x:1070,y:156};w[SUIT_DIAMONDS]={x:980,y:286};w[SUIT_CLUBS]={x:1070,y:286};a=(new createjs.Graphics).beginFill("rgba(158,158,158,0.01)").drawRect(w[SUIT_HEARTS].x-CARD_WIDTH/2,w[SUIT_HEARTS].y-CARD_HEIGHT/2,170,250);N=new createjs.Shape(a);N.on("click",function(){});s_oStage.addChild(N);C=[];for(a=0;5>a;a++)C[a]={x:980+22*a,y:550};l=[];for(a=0;40>a;a++)for(l[a]=[],b=0;10>b;b++)l[a][b]=
{status:LABEL_EMPTY,oCard:null};var c;switch(s_iMode){case 0:c=this._initCards(0);break;case 1:c=this._initCards(1);break;case 2:c=this._initCards(2)}this._shuffleCard(c,!0);this._setBoard();a=(new createjs.Graphics).beginFill("rgba(158,158,158,0.01)").drawRect(C[v].x-CARD_WIDTH/2,C[v].y-CARD_HEIGHT/2,CARD_WIDTH,CARD_HEIGHT);G=new createjs.Shape(a);G.on("click",this._turnDeck);G.visible=!1;s_oStage.addChild(G);a=(new createjs.Graphics).beginFill("rgba(158,158,158,0.01)").drawRect(C[v].x-CARD_WIDTH/
2,C[v].y-CARD_HEIGHT/2,CARD_WIDTH,CARD_HEIGHT);K=new createjs.Shape(a);K.on("click",this._hintForDeck);K.visible=!1;s_oStage.addChild(K);s_bMobile?window.navigator.msPointerEnabled?(s_oCanvas.addEventListener("MSPointerMove",this.onTouchMoveMS,!1),s_oCanvas.addEventListener("MSPointerUp",this.releaseCard,!1)):(s_oCanvas.addEventListener("touchmove",this.onTouchMove,!1),s_oCanvas.addEventListener("touchend",this.releaseCard,!1)):(s_oStage.addEventListener("stagemousemove",this.dragCard,!1),s_oStage.addEventListener("stagemouseup",
this.releaseCard,!1))};this._initCards=function(a){var b,c;0===a?(a=13,b=25,c=1):(1===a?(a=0,b=25):(a=0,b=51),c=0);for(var d=c,f=a,h=[],g=0;104>g;g++){var e=(g+1)%13;0===e&&(e=13);h.push({fotogram:f,rank:e,suit:d});13===e&&d++;f++;f>b&&(f=a,d=c)}return h};this._shuffleCard=function(a,b){for(var c=[],d=0;d<a.length;d++)c[d]=a[d];for(var f=[];0<c.length;)f.push(c.splice(Math.round(Math.random()*(c.length-1)),1)[0]);if(b)for(d=0;d<f.length;d++)x[d]=new CCard(C[0].x,C[0].y,J,f[d].fotogram,f[d].rank,f[d].suit);
else for(d=0;d<f.length;d++)x[d]=new CCard(C[0].x,C[0].y,J,a[d].fotogram,a[d].rank,a[d].suit)};this._setBoard=function(){for(var a=0,b=x.length-1,c=x.length-1;50<=c;c--)x[c].moveCard(z[x.length-1-c].x,z[x.length-1-c].y,150,a),x[c].setType("board"),a+=50;for(c=0;6>c;c++)for(a=0;10>a&&(l[c][a].oCard=x[b],l[c][a].status=LABEL_HIDDEN,b--,5!==c||3!==a);a++);for(c=54;c<x.length;c++)F[x.length-1-c]=x[x.length-1-c]};this.scaleDepth=function(a){J.setChildIndex(a,A);A++};this.pickCard=function(b,g){if(0===
E.length&&!f){f=!0;d=b.getPos().x;h=b.getPos().y;c=g.stageX-d;a=g.stageY-h;for(var e=0;10>e;e++)for(var k=l.length-1;0<=k;k--)l[k][e].oCard===b&&(B={row:k,column:e});for(var e=0,m=b.getRank(),k=B.row;k<l.length;k++)if(l[k][B.column].status===LABEL_SHOWN&&l[k][B.column].oCard.getSuit()===b.getSuit())if(l[k][B.column].oCard.getRank()===m)e++,m--;else{e=0;break}else if(l[k][B.column].status===LABEL_EMPTY)break;else if(l[k][B.column].oCard.getSuit()!==b.getSuit()){e=0;break}m=[];for(k=0;k<e;k++)m[k]=
l[B.row+k][B.column].oCard.saveInfo(),E[k]=new CCard(d,h+k*n,J,m[k].szFotogram,m[k].iRank,m[k].iSuit),E[k].setPointValue(m[k].bValue),l[B.row+k][B.column].oCard.unload(),E[k].setType("board"),E[k].instantShow()}};this.dragCard=function(b){if(!e&&f)for(var d=0;d<E.length;d++)E[d].setPos(b.stageX-c,b.stageY-a+d*n)};this.releaseCard=function(a){!1===e&&0<E.length?(f=!1,M._checkCardCollision(E),B=null,E=[]):f=!1};this._checkCardCollision=function(a){for(var b=0,c=[],f=[],g=0;10>g;g++)for(var e=l.length-
1;0<=e;e--)if(l[e][g].status===LABEL_SHOWN){c[b]=l[e][g].oCard.getLogicRect();f[b]={oCard:l[e][g].oCard,x:l[e][g].oCard.getPos().x,y:l[e][g].oCard.getPos().y,row:e,column:g};b++;break}else 0===e&&(c[b]=new createjs.Rectangle(z[g].x-CARD_WIDTH/2,z[g].y-CARD_HEIGHT/2,CARD_WIDTH,CARD_HEIGHT),b++);for(var b=0,g=-1,k=a[0].getLogicRect(),e=0;e<c.length;e++){var m=k.intersection(c[e]);null!==m&&b<m.width*m.height&&(b=m.width*m.height,g=e)}if(0>g)for(e=0;e<a.length;e++)a[e].stackInPlace(d,h+e*n,200),l[B.row+
e][B.column].oCard=a[e];else if(l[0][g].status===LABEL_EMPTY){for(e=0;e<a.length;e++)a[e].stackInPlace(z[g].x,z[g].y+e*n,200),l[e][g].status=LABEL_SHOWN,l[B.row+e][B.column].status=LABEL_EMPTY,l[e][g].oCard=a[e];this._updateMoves();this._removeScore();this._checkBoard(a[0],g)}else if(1===f[g].oCard.getRank()-a[0].getRank()){for(e=0;e<a.length;e++)a[e].stackInPlace(f[g].x,f[g].y+n+e*n,200),l[f[g].row+1+e][f[g].column].status=LABEL_SHOWN,l[B.row+e][B.column].status=LABEL_EMPTY,l[f[g].row+1+e][f[g].column].oCard=
a[e];this._updateMoves();this._removeScore();this._checkBoard(a[0],g)}else for(e=0;e<a.length;e++)a[e].stackInPlace(d,h+e*n,200),l[B.row+e][B.column].oCard=a[e]};this._checkBoard=function(a,b){this._turnCard(B.column);y=b;var c=1,d;H=[];for(var e=l.length-1;0<=e;e--)if(l[e][b].status===LABEL_EMPTY)d=e;else if(l[e][b].oCard.getRank()===c&&l[e][b].oCard.getSuit()===a.getSuit()&&l[e][b].status===LABEL_SHOWN)c++,d=e,H.push(l[e][b].oCard);else break;c=a.getSuit();if(13===H.length){f=!0;D=0;!1!==DISABLE_SOUND_MOBILE&&
!1!==s_bMobile||createjs.Sound.play("snap");for(e=0;13>e;e++)l[d+12-e][b].status=LABEL_EMPTY,l[d+12-e][b].oCard=null;H[D].moveToSuit(w[c].x,w[c].y,210)}this._checkIfActiveDeck()};this._turnCard=function(a){for(var b=l.length-1;0<=b&&l[b][a].status!==LABEL_SHOWN;b--)if(l[b][a].status===LABEL_HIDDEN){l[b][a].oCard.showCard();l[b][a].status=LABEL_SHOWN;break}};this.stackInSuit=function(a){D++;13>D?(a=H[D].getSuit(),1<D&&H[D-2].setVisible(!1),J.swapChildren(H[D].getSprite(),H[D-1].getSprite()),H[D].moveToSuit(w[a].x,
w[a].y,0)):(r++,f=!1,this._turnCard(y),this._calculateScore(a,POINTS_TO_WIN),8===r?this.gameOver():f=!1)};this._checkIfActiveDeck=function(){for(var a=0,b=0;10>b;b++)l[0][b].status===LABEL_EMPTY&&a++;0<a?(G.visible=!1,K.visible=!0,K.visible=5===v?!1:!0):(K.visible=!1,G.visible=!0)};this._hintForDeck=function(){I.showHint()};this._turnDeck=function(){if(!f&&5!==v){f=!0;M.activeDeck();v++;G.x=22*v;K.x=22*v;for(var a=[],b=0;10>b;b++)for(var c=l.length-1;0<=c;c--)if(l[c][b].status===LABEL_SHOWN){a[b]=
{x:l[c][b].oCard.getPos().x,y:l[c][b].oCard.getPos().y+n,row:c+1,column:b};break}else 0===c&&(a[b]={row:0,column:b});for(var b=100,d=[],e=[],c=0;10>c;c++)d[c]=F[F.length-10+c].saveInfo(),F[F.length-10+c].unload(),F.splice(F.length-10+c,1),e[c]=new CCard(C[v-1].x,C[v-1].y,J,d[c].szFotogram,d[c].iRank,d[c].iSuit);for(c=0;10>c;c++)e[9-c].setType("board"),l[a[c].row][c].oCard=e[9-c],l[a[c].row][c].status=LABEL_SHOWN,e[9-c].moveDeckCard(a[c].x,a[c].y,200,b),b+=100}};this.activeDeck=function(){p++;11===
p?(f=!1,G.visible=!0,p=0,this._checkScaleAllColumn()):G.visible=!1};this._checkScaleAllColumn=function(){for(var a=0;10>a;a++){for(var b=1,c=l.length-1,d,e,f=l.length-1;0<=f;f--)if(l[f][a].status===LABEL_SHOWN){d=l[f][a].oCard.getSuit();e=f;break}for(f=e;0<=f;f--)if(l[f][a].oCard.getRank()===b&&l[f][a].oCard.getSuit()===d&&l[f][a].status===LABEL_SHOWN)b++;else break;var g=300;if(14===b)for(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("snap"),y=a,c=e-12,b=l[c][a].oCard.getSuit(),
f=0;13>f;f++)l[c+12-f][a].oCard.moveToSuit(w[b].x,w[b].y,100,g),l[c+12-f][a].status=LABEL_EMPTY,l[c+12-f][a].oCard=null,g+=100}this._checkIfActiveDeck()};this.onTouchMove=function(b){b.preventDefault();if(!e&&f)for(k=parseInt((b.touches[0].pageX-s_oCanvasLeft)/s_iScaleFactor),u=parseInt((b.touches[0].pageY-s_oCanvasTop)/s_iScaleFactor),b=0;b<E.length;b++)E[b].setPos(k-c,u-a+b*n)};this.onTouchMoveMS=function(b){if(!window.navigator.msPointerEnabled||b.isPrimary)if(b.preventDefault(),!e&&f)for(k=parseInt(((b.pageX||
b.targetTouches[0].pageX)-s_oCanvasLeft)/s_iScaleFactor),u=parseInt(((b.pageY||b.targetTouches[0].pageY)-s_oCanvasTop)/s_iScaleFactor),b=0;b<E.length;b++)E[b].setPos(k-c,u-a+b*n)};this.unload=function(){for(var a=0;a<x.length;a++)x[a].unload();I.unload();null!==L&&L.unload();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||O.stop();createjs.Tween.removeAllTweens();s_oStage.removeAllChildren()};this.onExit=function(){this.unload();s_oMain.gotoMenu();$(s_oMain).trigger("restart")};this._onExitHelp=function(){};
this.gameOver=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("game_over");L=CEndPanel(s_oSpriteLibrary.getSprite("msg_box"));L.show(g)};this.restartGame=function(){this.unload();this._init()};this.pauseGame=function(){};this._calculateScore=function(a,b){(new CScore).showScore(a.getPos(),b)};this._removeScore=function(){g-=POINTS_TO_LOSE;0>g&&(g=0);(new CScore).removeScore(g,750);I.fadeScore(g,750)};this.updateScore=function(a){g+=a;I.refreshScore(g)};this._updateMoves=
function(){m++;(new CScore).displayMoves(m,750);I.fadeMove(m,750)};this.update=function(){if(e&&x[51].getPlaced())if(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||O.stop(),q++,4===q)x[59].showCard(),l[4][4].status=LABEL_SHOWN;else if(8===q)x[58].showCard(),l[4][5].status=LABEL_SHOWN;else if(12===q)x[57].showCard(),l[4][6].status=LABEL_SHOWN;else if(16===q)x[56].showCard(),l[4][7].status=LABEL_SHOWN;else if(20===q)x[55].showCard(),l[4][8].status=LABEL_SHOWN;else if(24===q)x[54].showCard(),l[4][9].status=
LABEL_SHOWN;else if(28===q)x[53].showCard(),l[5][0].status=LABEL_SHOWN;else if(32===q)x[52].showCard(),l[5][1].status=LABEL_SHOWN;else if(36===q)x[51].showCard(),l[5][2].status=LABEL_SHOWN;else if(40===q)x[50].showCard(),l[5][3].status=LABEL_SHOWN;else if(44===q)for(var a=0;10>a;a++)F[39-a].stackAndDeactive(C[1].x,C[1].y,1E3);else if(56===q)for(a=0;10>a;a++)F[29-a].stackAndDeactive(C[2].x,C[2].y,1E3);else if(68===q)for(a=0;10>a;a++)F[19-a].stackAndDeactive(C[3].x,C[3].y,1E3);else if(80===q){for(a=
0;10>a;a++)F[9-a].stackAndDeactive(C[4].x,C[4].y,1E3);f=e=!1;G.visible=!0;I.setVisibleButHelp()}};s_oGame=this;POINTS_TO_LOSE=b.points_to_lose;POINTS_TO_WIN=b.points_to_win;START_SCORE=b.starting_score;M=this;this._init()}var s_oGame;
function CEndPanel(b){var c,a,d,h,f,e;this._init=function(b){c=createBitmap(b);d=new createjs.Text("","bold 60px Arial","#000");d.x=CANVAS_WIDTH/2+1;d.y=CANVAS_HEIGHT/2-160;d.textAlign="center";h=new createjs.Text("","bold 60px Arial","#ffffff");h.x=CANVAS_WIDTH/2;h.y=CANVAS_HEIGHT/2-162;h.textAlign="center";f=new createjs.Text("","bold 40px Arial","#000");f.x=CANVAS_WIDTH/2+1;f.y=CANVAS_HEIGHT/2+50;f.textAlign="center";e=new createjs.Text("","bold 40px Arial","#ffffff");e.x=CANVAS_WIDTH/2;e.y=CANVAS_HEIGHT/
2+52;e.textAlign="center";a=new createjs.Container;a.alpha=0;a.visible=!1;a.addChild(c,f,e,d,h);s_oStage.addChild(a)};this.unload=function(){a.off("mousedown",this._onExit)};this._initListener=function(){a.on("mousedown",this._onExit)};this.show=function(b){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("game_over");d.text=TEXT_GAMEOVER;h.text=TEXT_GAMEOVER;f.text=TEXT_SCORE+": "+b;e.text=TEXT_SCORE+": "+b;a.visible=!0;var c=this;createjs.Tween.get(a).to({alpha:1},500).call(function(){c._initListener()});
$(s_oMain).trigger("save_score",b)};this._onExit=function(){a.off("mousedown",this._onExit);s_oStage.removeChild(a);s_oGame.onExit()};this._init(b);return this}
function CCard(b,c,a,d,h,f){var e=!1,g=!0,m,k,u,t,A,q,n,v,p,y,r,D,z,w;this._init=function(a,b,c,d,e,f){D=c;t=d;A=e;q=f;m=!1;k="deck";u=0===q||2===q?"red":"black";r=new createjs.Container;r.x=a;r.y=b;D.addChild(r);a={images:[s_oSpriteLibrary.getSprite("card_spritesheet")],frames:{width:CARD_WIDTH,height:CARD_HEIGHT,regX:CARD_WIDTH/2,regY:CARD_HEIGHT/2},animations:{card_1_1:[0],card_1_2:[1],card_1_3:[2],card_1_4:[3],card_1_5:[4],card_1_6:[5],card_1_7:[6],card_1_8:[7],card_1_9:[8],card_1_10:[9],card_1_J:[10],
card_1_Q:[11],card_1_K:[12],card_2_1:[13],card_2_2:[14],card_2_3:[15],card_2_4:[16],card_2_5:[17],card_2_6:[18],card_2_7:[19],card_2_8:[20],card_2_9:[21],card_2_10:[22],card_2_J:[23],card_2_Q:[24],card_2_K:[25],card_3_1:[26],card_3_2:[27],card_3_3:[28],card_3_4:[29],card_3_5:[30],card_3_6:[31],card_3_7:[32],card_3_8:[33],card_3_9:[34],card_3_10:[35],card_3_J:[36],card_3_Q:[37],card_3_K:[38],card_4_1:[39],card_4_2:[40],card_4_3:[41],card_4_4:[42],card_4_5:[43],card_4_6:[44],card_4_7:[45],card_4_8:[46],
card_4_9:[47],card_4_10:[48],card_4_J:[49],card_4_Q:[50],card_4_K:[51],back:[52]}};a=new createjs.SpriteSheet(a);p=createSprite(a,"back",0,0,CARD_WIDTH,CARD_HEIGHT);p.stop();r.addChild(p);y=new createjs.Shape;y.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(-CARD_WIDTH/2,-CARD_HEIGHT/2,CARD_WIDTH,CARD_HEIGHT);y.on("mousedown",this._mouseDown);r.addChild(y);n=[];v=[]};this.unload=function(){y.off("mousedown",this._mouseDown);D.removeChild(r)};this.addEventListener=function(a,b,c){n[a]=b;v[a]=
c};this.saveInfo=function(){return{szFotogram:t,iRank:A,iSuit:q,bValue:g}};this.changeInfo=function(a,b,c){t=a;A=b;q=c};this.instantShow=function(){p.gotoAndStop(t)};this.setValue=function(a){p.gotoAndStop(t);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("card");createjs.Tween.get(r).to({scaleX:1},200)};this.setType=function(a){k=a};this.checkType=function(){return k};this.setActive=function(a){a?r.addChild(y):r.removeChild(y)};this._void=function(){};this.setVisible=function(a){r.visible=
!0===a?!0:!1};this.moveCard=function(a,b,c,d){createjs.Tween.get(r).wait(d).to({x:a,y:b},c,createjs.Ease.linear).call(function(){w.setPlaced()})};this.moveDeckCard=function(a,b,c,d){createjs.Tween.get(r).wait(d).to({x:a,y:b},c,createjs.Ease.linear).call(function(){s_oGame.activeDeck();w.showCard()})};this.moveToSuit=function(a,b,c){createjs.Tween.get(r).wait(c).to({x:a,y:b},200,createjs.Ease.cubicOut).call(function(){s_oGame.stackInSuit(w)})};this.setPlaced=function(){e=!0;s_oGame.scaleDepth(this.getSprite())};
this.stackInPlace=function(a,b,c){createjs.Tween.get(r).to({x:a,y:b},c,createjs.Ease.cubicOut).call(function(){m=!0})};this.stackAndDeactive=function(a,b,c){createjs.Tween.get(r).to({x:a,y:b},c,createjs.Ease.cubicOut)};this._sendCard=function(){s_oGame.dblClickMove(w)};this._mouseDown=function(a){!1!==m&&(D.getChildIndex(r),s_oGame.pickCard(w,a))};this.getPlaced=function(){return e};this.showCard=function(){var a=this;createjs.Tween.get(r).to({scaleX:.1},200).call(function(){a.setValue()}).call(function(){m=
!0})};this.hideCard=function(){var a=this;createjs.Tween.get(r).to({scaleX:.1},200).call(function(){a.setBack()})};this.setOldPos=function(a,b,c){};this.setPos=function(a,b){r.x=a;r.y=b};this.setBack=function(){m=!1;p.gotoAndStop("back");var a=this;createjs.Tween.get(r).to({scaleX:1},200).call(function(){a.cardHidden()})};this.setTurned=function(a){m=a};this.cardHidden=function(){n[ON_CARD_HIDE]&&n[ON_CARD_HIDE].call(v[ON_CARD_HIDE],this)};this._onSelected=function(){s_oGame.onCardSelected(z)};this.getPointValue=
function(){return g};this.setPointValue=function(a){g=a};this.getRank=function(){return A};this.getSuit=function(){return q};this.getColor=function(){return u};this.getFotogram=function(){return t};this.getPos=function(){return{x:r.x,y:r.y}};this.getSprite=function(){return r};this.getLogicRect=function(){return new createjs.Rectangle(r.x-CARD_WIDTH/2,r.y-CARD_HEIGHT/2,CARD_WIDTH,CARD_HEIGHT)};z=this;w=this;this._init(b,c,a,d,h,f)}
function CSpriteLibrary(){var b,c,a,d,h,f;this.init=function(e,g,m){a=c=0;d=e;h=g;f=m;b={}};this.addSprite=function(a,d){b.hasOwnProperty(a)||(b[a]={szPath:d,oSprite:new Image},c++)};this.getSprite=function(a){return b.hasOwnProperty(a)?b[a].oSprite:null};this._onSpritesLoaded=function(){h.call(f)};this._onSpriteLoaded=function(){d.call(f);++a==c&&this._onSpritesLoaded()};this.loadSprites=function(){for(var a in b)b[a].oSprite.oSpriteLibrary=this,b[a].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
b[a].oSprite.src=b[a].szPath};this.getNumSprites=function(){return c}}
var CANVAS_WIDTH=1136,CANVAS_HEIGHT=640,FPS_TIME=1E3/24,DISABLE_SOUND_MOBILE=!1,STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,STATE_GAME_WAITING_FOR_BET=0,STATE_GAME_DEAL=1,STATE_GAME_CHOOSE_HOLD=2,STATE_GAME_DRAW=3,STATE_GAME_EVALUATE=4,ON_CARD_SHOWN="ON_CARD_SHOWN",ON_CARD_HIDE="ON_CARD_HIDE",ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,SUIT_HEARTS=0,SUIT_SPADES=1,SUIT_DIAMONDS=2,SUIT_CLUBS=3,LABEL_EMPTY=0,LABEL_HIDDEN=1,LABEL_SHOWN=2,CARD_WIDTH=
76,CARD_HEIGHT=117,POINTS_TO_LOSE,POINTS_TO_WIN,START_SCORE;
function CToggle(b,c,a,d){var h,f,e,g;this._init=function(a,b,c,d){f=[];e=[];var A=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_true:[0],state_false:[1]}});h=d;g=createSprite(A,"state_"+h,c.width/2/2,c.height/2,c.width/2,c.height);g.x=a;g.y=b;g.stop();s_oStage.addChild(g);this._initListener()};this.unload=function(){g.off("mousedown",this.buttonDown);g.off("pressup",this.buttonRelease);s_oStage.removeChild(g)};this._initListener=
function(){g.on("mousedown",this.buttonDown);g.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){f[a]=b;e[a]=c};this.setActive=function(a){h=a;g.gotoAndStop("state_"+h)};this.buttonRelease=function(){g.scaleX=1;g.scaleY=1;!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");h=!h;g.gotoAndStop("state_"+h);f[ON_MOUSE_UP]&&f[ON_MOUSE_UP].call(e[ON_MOUSE_UP],h)};this.buttonDown=function(){g.scaleX=.9;g.scaleY=.9;f[ON_MOUSE_DOWN]&&f[ON_MOUSE_DOWN].call(e[ON_MOUSE_DOWN])};
this._init(b,c,a,d)}var s_iScaleFactor=1,s_oCanvasLeft,s_oCanvasTop;
(function(b){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(b)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(b.substr(0,4))})(navigator.userAgent||
navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(b){console.log(b)}$(window).ready(function(){sizeHandler()});window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var b=CANVAS_WIDTH,c=CANVAS_HEIGHT,a=window.innerWidth;multiplier=s_iScaleFactor=Math.min(window.innerHeight/c,a/b);b*=multiplier;c*=multiplier;$("#canvas").css("width",b+"px");$("#canvas").css("height",c+"px");$("#canvas").css("left",a/2-b/2+"px");s_oCanvasLeft=$("#canvas").offset().left;s_oCanvasTop=$("#canvas").offset().top}}
function createBitmap(b,c,a){var d=new createjs.Bitmap(b),h=new createjs.Shape;c&&a?h.graphics.beginFill("#fff").drawRect(0,0,c,a):h.graphics.beginFill("#ff0").drawRect(0,0,b.width,b.height);d.hitArea=h;return d}function createSprite(b,c,a,d,h,f){b=null!==c?new createjs.Sprite(b,c):new createjs.Sprite(b);c=new createjs.Shape;c.graphics.beginFill("#000000").drawRect(-a,-d,h,f);b.hitArea=c;return b}
function randomFloatBetween(b,c,a){"undefined"===typeof a&&(a=2);return parseFloat(Math.min(b+Math.random()*(c-b),c).toFixed(a))}function shuffle(b){for(var c=b.length,a,d;0!==c;)d=Math.floor(Math.random()*c),--c,a=b[c],b[c]=b[d],b[d]=a;return b}function bubbleSort(b){var c;do{c=!1;for(var a=0;a<b.length-1;a++)b[a]>b[a+1]&&(c=b[a],b[a]=b[a+1],b[a+1]=c,c=!0)}while(c)}function easeLinear(b,c,a,d){return a*b/d+c}function easeInQuad(b,c,a,d){return a*(b/=d)*b+c}
function easeInSine(b,c,a,d){return-a*Math.cos(b/d*(Math.PI/2))+a+c}function easeInCubic(b,c,a,d){return a*(b/=d)*b*b+c}function getTrajectoryPoint(b,c){var a=new createjs.Point,d=(1-b)*(1-b),h=b*b;a.x=d*c.start.x+2*(1-b)*b*c.traj.x+h*c.end.x;a.y=d*c.start.y+2*(1-b)*b*c.traj.y+h*c.end.y;return a}function formatTime(b){b/=1E3;var c=Math.floor(b/60);b=parseFloat(b-60*c).toFixed(1);var a="",a=10>c?a+("0"+c+":"):a+(c+":");return a=10>b?a+("0"+b):a+b}function degreesToRadians(b){return b*Math.PI/180}
function checkRectCollision(b,c){var a,d;a=getBounds(b,.9);d=getBounds(c,.98);return calculateIntersection(a,d)}function calculateIntersection(b,c){var a,d,h,f,e,g,m,k;a=b.x+(h=b.width/2);d=b.y+(f=b.height/2);e=c.x+(g=c.width/2);m=c.y+(k=c.height/2);a=Math.abs(a-e)-(h+g);d=Math.abs(d-m)-(f+k);return 0>a&&0>d?(a=Math.min(Math.min(b.width,c.width),-a),d=Math.min(Math.min(b.height,c.height),-d),{x:Math.max(b.x,c.x),y:Math.max(b.y,c.y),width:a,height:d,rect1:b,rect2:c}):null}
function getBounds(b,c){var a={x:Infinity,y:Infinity,width:0,height:0};if(b instanceof createjs.Container){a.x2=-Infinity;a.y2=-Infinity;var d=b.children,h=d.length,f,e;for(e=0;e<h;e++)f=getBounds(d[e],1),f.x<a.x&&(a.x=f.x),f.y<a.y&&(a.y=f.y),f.x+f.width>a.x2&&(a.x2=f.x+f.width),f.y+f.height>a.y2&&(a.y2=f.y+f.height);Infinity==a.x&&(a.x=0);Infinity==a.y&&(a.y=0);Infinity==a.x2&&(a.x2=0);Infinity==a.y2&&(a.y2=0);a.width=a.x2-a.x;a.height=a.y2-a.y;delete a.x2;delete a.y2}else{var g,m;b instanceof createjs.Bitmap?
(h=b.sourceRect||b.image,e=h.width*c,g=h.height*c):b instanceof createjs.Sprite?b.spriteSheet._frames&&b.spriteSheet._frames[b.currentFrame]&&b.spriteSheet._frames[b.currentFrame].image?(h=b.spriteSheet.getFrame(b.currentFrame),e=h.rect.width,g=h.rect.height,d=h.regX,m=h.regY):(a.x=b.x||0,a.y=b.y||0):(a.x=b.x||0,a.y=b.y||0);d=d||0;e=e||0;m=m||0;g=g||0;a.regX=d;a.regY=m;h=b.localToGlobal(0-d,0-m);f=b.localToGlobal(e-d,g-m);e=b.localToGlobal(e-d,0-m);d=b.localToGlobal(0-d,g-m);a.x=Math.min(Math.min(Math.min(h.x,
f.x),e.x),d.x);a.y=Math.min(Math.min(Math.min(h.y,f.y),e.y),d.y);a.width=Math.max(Math.max(Math.max(h.x,f.x),e.x),d.x)-a.x;a.height=Math.max(Math.max(Math.max(h.y,f.y),e.y),d.y)-a.y}return a}function NoClickDelay(b){this.element=b;window.Touch&&this.element.addEventListener("touchstart",this,!1)}function shuffle(b){for(var c=b.length,a,d;0<c;)d=Math.floor(Math.random()*c),c--,a=b[c],b[c]=b[d],b[d]=a;return b}
NoClickDelay.prototype={handleEvent:function(b){switch(b.type){case "touchstart":this.onTouchStart(b);break;case "touchmove":this.onTouchMove(b);break;case "touchend":this.onTouchEnd(b)}},onTouchStart:function(b){b.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(b){this.moved=!0},onTouchEnd:function(b){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){b=document.elementFromPoint(b.changedTouches[0].clientX,b.changedTouches[0].clientY);3==b.nodeType&&(b=b.parentNode);var c=document.createEvent("MouseEvents");c.initEvent("click",!0,!0);b.dispatchEvent(c)}}};
(function(){function b(a){var b={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};a=a||window.event;a.type in b?document.body.className=b[a.type]:(document.body.className=this[c]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var c="hidden";c in document?document.addEventListener("visibilitychange",b):(c="mozHidden")in document?document.addEventListener("mozvisibilitychange",b):(c="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",b):(c="msHidden")in document?document.addEventListener("msvisibilitychange",b):"onfocusin"in document?document.onfocusin=document.onfocusout=b:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=b})();
function CTextButton(b,c,a,d,h,f,e){var g,m,k,u,t;this._init=function(a,b,c,d,e,f,h){g=[];m=[];var D=createBitmap(c),z=Math.ceil(h/20);t=new createjs.Text(d,"bold "+h+"px "+e,"#000000");t.textAlign="center";t.textBaseline="alphabetic";var w=t.getBounds();t.x=c.width/2+z;t.y=Math.floor(c.height/2)+w.height/3+z;u=new createjs.Text(d,"bold "+h+"px "+e,f);u.textAlign="center";u.textBaseline="alphabetic";w=u.getBounds();u.x=c.width/2;u.y=Math.floor(c.height/2)+w.height/3;k=new createjs.Container;k.x=a;
k.y=b;k.regX=c.width/2;k.regY=c.height/2;k.addChild(D,t,u);s_oStage.addChild(k);this._initListener()};this.unload=function(){k.off("mousedown");k.off("pressup");s_oStage.removeChild(k)};this.setVisible=function(a){k.visible=a};this._initListener=function(){oParent=this;k.on("mousedown",this.buttonDown);k.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){g[a]=b;m[a]=c};this.buttonRelease=function(){k.scaleX=1;k.scaleY=1;g[ON_MOUSE_UP]&&g[ON_MOUSE_UP].call(m[ON_MOUSE_UP])};this.buttonDown=
function(){k.scaleX=.9;k.scaleY=.9;g[ON_MOUSE_DOWN]&&g[ON_MOUSE_DOWN].call(m[ON_MOUSE_DOWN])};this.setTextPosition=function(a){u.y=a;t.y=a+2};this.setPosition=function(a,b){k.x=a;k.y=b};this.setX=function(a){k.x=a};this.setY=function(a){k.y=a};this.getButtonImage=function(){return k};this.getX=function(){return k.x};this.getY=function(){return k.y};this._init(b,c,a,d,h,f,e);return this}
function CScore(){this.showScore=function(b,c){var a=new createjs.Text("+"+c,"bold 24px Arial","#000000");a.x=b.x;a.y=b.y;a.scaleX=2;a.scaleY=2;a.textAlign="right";a.textBaseline="alphabetic";a.outline=4;s_oStage.addChild(a);var d=new createjs.Text("+"+c,"bold 24px Arial","#fff");d.x=b.x;d.y=b.y;d.scaleX=2;d.scaleY=2;d.textAlign="right";d.textBaseline="alphabetic";s_oStage.addChild(d);createjs.Tween.get(d).to({x:193,y:45},1E3,createjs.Ease.cubicIn).call(function(){s_oGame.updateScore(c);s_oStage.removeChild(d)});
createjs.Tween.get(d).to({scaleX:1,scaleY:1},1E3,createjs.Ease.linear);createjs.Tween.get(a).to({x:193,y:45},1E3,createjs.Ease.cubicIn).call(function(){s_oStage.removeChild(a)});createjs.Tween.get(a).to({scaleX:1,scaleY:1},1E3,createjs.Ease.linear)};this.removeScore=function(b,c){var a=new createjs.Text(b,"bold 24px Arial","#ffffff");a.x=193;a.y=45;a.alpha=0;a.textAlign="right";a.textBaseline="alphabetic";a.lineWidth=200;s_oStage.addChild(a);createjs.Tween.get(a).to({alpha:1},c,createjs.Ease.linear).call(function(){s_oStage.removeChild(a)})};
this.displayMoves=function(b,c){var a=new createjs.Text(b,"bold 24px Arial","#ffffff");a.x=380;a.y=45;a.alpha=0;a.textAlign="right";a.textBaseline="alphabetic";a.lineWidth=200;s_oStage.addChild(a);createjs.Tween.get(a).to({alpha:1},c,createjs.Ease.linear).call(function(){s_oStage.removeChild(a)})}}
function CPreloader(){var b,c,a,d,h,f,e;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.loadSprites();e=new createjs.Container;s_oStage.addChild(e)};this.unload=function(){e.removeAllChildren()};this.hide=function(){var a=this;setTimeout(function(){createjs.Tween.get(f).to({alpha:1},500).call(function(){a.unload();
s_oMain.gotoMenu()})},1E3)};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var g=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));e.addChild(g);g=s_oSpriteLibrary.getSprite("progress_bar");d=createBitmap(g);d.x=CANVAS_WIDTH/2-g.width/2;d.y=CANVAS_HEIGHT-170;e.addChild(d);b=g.width;c=g.height;h=new createjs.Shape;h.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(d.x,d.y,1,c);e.addChild(h);d.mask=
h;a=new createjs.Text("","30px ZombieA","#fff");a.x=CANVAS_WIDTH/2;a.y=CANVAS_HEIGHT-125;a.shadow=new createjs.Shadow("#000",2,2,2);a.textBaseline="alphabetic";a.textAlign="center";e.addChild(a);f=new createjs.Shape;f.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);f.alpha=0;e.addChild(f)};this.refreshLoader=function(e){a.text=e+"%";h.graphics.clear();e=Math.floor(e*b/100);h.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(d.x,d.y,e,c)};this._init()}
function CModeMenu(){var b,c,a,d,h,f,e,g,m,k,u,t,A,q,n,v,p;this._init=function(){b=createBitmap(s_oSpriteLibrary.getSprite("bg_layout"));s_oStage.addChild(b);q=new createjs.Text(TEXT_TOP_MODE,"bold 60px Arial","#ffffff");q.x=CANVAS_WIDTH/2;q.y=CANVAS_HEIGHT/2-170;q.shadow=new createjs.Shadow("#000000",3,3,3);q.textAlign="center";q.lineWidth=800;s_oStage.addChild(q);c=new createjs.Container;c.x=125;c.y=305;a=new createjs.Container;a.x=CANVAS_WIDTH/2-120;a.y=305;d=new createjs.Container;d.x=768;d.y=
305;h=new createjs.Text(TEXT_MODE_1,"bold 28px Arial","#01ff8f");h.x=122;h.y=88;h.shadow=new createjs.Shadow("#000000",3,3,3);h.textBaseline="alphabetic";h.textAlign="center";h.lineWidth=300;c.addChild(h);f=new createjs.Text(TEXT_EASY,"bold 34px Arial","#ffffff");f.x=122;f.y=35;f.shadow=new createjs.Shadow("#000000",3,3,3);f.textBaseline="alphabetic";f.textAlign="center";f.lineWidth=300;c.addChild(f);e=new createjs.Text(TEXT_MODE_2,"bold 28px Arial","#01ff8f");e.x=122;e.y=88;e.shadow=new createjs.Shadow("#000000",
3,3,3);e.textBaseline="alphabetic";e.textAlign="center";e.lineWidth=300;a.addChild(e);g=new createjs.Text(TEXT_NORMAL,"bold 34px Arial","#ffffff");g.x=125;g.y=35;g.shadow=new createjs.Shadow("#000000",3,3,3);g.textBaseline="alphabetic";g.textAlign="center";g.lineWidth=300;a.addChild(g);m=new createjs.Text(TEXT_MODE_3,"bold 28px Arial","#01ff8f");m.x=122;m.y=88;m.shadow=new createjs.Shadow("#000000",3,3,3);m.textBaseline="alphabetic";m.textAlign="center";m.lineWidth=300;d.addChild(m);k=new createjs.Text(TEXT_HARD,
"bold 34px Arial","#ffffff");k.x=125;k.y=35;k.shadow=new createjs.Shadow("#000000",3,3,3);k.textBaseline="alphabetic";k.textAlign="center";k.lineWidth=300;d.addChild(k);s_oStage.addChild(c);s_oStage.addChild(a);s_oStage.addChild(d);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile){var n=s_oSpriteLibrary.getSprite("audio_icon");p=new CToggle(CANVAS_WIDTH-n.height/2-10,n.height/2+10,n,s_bAudioActive);p.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this)}n=(new createjs.Graphics).beginFill("rgba(158,158,158,0.01)").drawRect(4,
0,240,250);u=new createjs.Shape(n);c.addChild(u);u.on("pressup",this._selectEasy);t=new createjs.Shape(n);a.addChild(t);t.on("pressup",this._selectNormal);A=new createjs.Shape(n);d.addChild(A);A.on("pressup",this._selectHard);v=new createjs.Shape;v.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(v);createjs.Tween.get(v).to({alpha:0},1E3).call(function(){v.visible=!1})};this._selectEasy=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");
n.unload();s_oMain.gotoGame(0)};this._selectNormal=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");n.unload();s_oMain.gotoGame(1)};this._selectHard=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");n.unload();s_oMain.gotoGame(2)};this.unload=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)p.unload(),p=null;u.off("pressup",this._selectEasy);t.off("pressup",this._selectNormal);A.off("pressup",this._selectHard);s_oStage.removeAllChildren();
b=null};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onButPlayRelease=function(){this.unload();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");s_oMain.gotoGame()};n=this;this._init()}
function CMenu(){var b,c,a,d;this._init=function(){b=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(b);var h=s_oSpriteLibrary.getSprite("but_play");c=new CTextButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-80,h,TEXT_PLAY,"Arial","#ffffff",40);c.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)h=s_oSpriteLibrary.getSprite("audio_icon"),d=new CToggle(CANVAS_WIDTH-h.height/2-10,h.height/2+10,h,s_bAudioActive),d.addEventListener(ON_MOUSE_UP,
this._onAudioToggle,this);a=new createjs.Shape;a.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(a);createjs.Tween.get(a).to({alpha:0},1E3).call(function(){a.visible=!1})};this.unload=function(){c.unload();c=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)d.unload(),d=null;s_oStage.removeChild(b);b=null};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onButPlayRelease=function(){this.unload();!1!==
DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");s_oMain.goToModeMenu()};this._init()}
function CMain(b){var c,a=0,d=0,h=STATE_LOADING,f,e,g;this.initContainer=function(){s_oCanvas=document.getElementById("canvas");s_oStage=new createjs.Stage(s_oCanvas);createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&(s_oStage.enableMouseOver(20),$("body").on("contextmenu","#canvas",function(a){return!1}));s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.setFPS(30);navigator.userAgent.match(/Windows Phone/i)&&(DISABLE_SOUND_MOBILE=
!0);s_oSpriteLibrary=new CSpriteLibrary;e=new CPreloader};this.preloaderReady=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();this._loadImages();c=!0};this.soundLoaded=function(){a++;if(a===d){e.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundtrack=createjs.Sound.play("soundtrack",{loop:100});this.gotoMenu()}};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&(0<navigator.userAgent.indexOf("Opera")||0<navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=
["m4a"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/soundtrack.ogg","soundtrack"),createjs.Sound.registerSound("./sounds/card_dealing.ogg","card_dealing"),createjs.Sound.registerSound("./sounds/snap.ogg","snap"),createjs.Sound.registerSound("./sounds/press_button.ogg","click"),createjs.Sound.registerSound("./sounds/game_over.ogg","game_over"),createjs.Sound.registerSound("./sounds/card.ogg","card")):(createjs.Sound.alternateExtensions=
["ogg"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/soundtrack.mp3","soundtrack"),createjs.Sound.registerSound("./sounds/card_dealing.mp3","card_dealing"),createjs.Sound.registerSound("./sounds/snap.mp3","snap"),createjs.Sound.registerSound("./sounds/press_button.m4a","click"),createjs.Sound.registerSound("./sounds/game_over.mp3","game_over"),createjs.Sound.registerSound("./sounds/card.mp3","card")),d+=6)};this._loadImages=
function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("bg_layout","./sprites/bg_layout.jpg");s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("bg_help","./sprites/bg_help.png");s_oSpriteLibrary.addSprite("arrow","./sprites/arrow.png");
s_oSpriteLibrary.addSprite("hintpanel","./sprites/hintpanel.png");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("but_help","./sprites/but_help.png");s_oSpriteLibrary.addSprite("but_shuffle","./sprites/but_shuffle.png");s_oSpriteLibrary.addSprite("score_moves_display","./sprites/score_moves_display.png");s_oSpriteLibrary.addSprite("card_spritesheet","./sprites/cards.png");s_oSpriteLibrary.addSprite("hearts_suit",
"./sprites/hearts_suit.png");s_oSpriteLibrary.addSprite("diamonds_suit","./sprites/diamonds_suit.png");s_oSpriteLibrary.addSprite("clubs_suit","./sprites/clubs_suit.png");s_oSpriteLibrary.addSprite("spades_suit","./sprites/spades_suit.png");d+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){a++;e.refreshLoader(Math.floor(a/d*100));if(a===d){e.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundtrack=createjs.Sound.play("soundtrack",{loop:100});
this.gotoMenu()}};this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this.gotoMenu=function(){new CMenu;h=STATE_MENU};this.goToModeMenu=function(){new CModeMenu;h=STATE_MENU};this.gotoGame=function(a){s_iMode=a;g=new CGame(f);h=STATE_GAME;$(s_oMain).trigger("game_start")};this.gotoHelp=function(){new CHelp;h=STATE_HELP};this.stopUpdate=function(){c=!1};this.startUpdate=function(){c=!0};this._update=function(a){if(!1!==c){var b=(new Date).getTime();
s_iTimeElaps=b-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=b;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);h===STATE_GAME&&g.update();s_oStage.update(a)}};s_oMain=this;f=b;this.initContainer()}var s_bMobile,s_iMode,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oSoundTrack,s_oCanvas;TEXT_GAMEOVER="YOU WIN";TEXT_SCORE="SCORE";TEXT_PLAY="PLAY";TEXT_RESTART="RESTART";
TEXT_MOVES="MOVES";TEXT_SCORE="SCORE";TEXT_HELP1="THE CARD PILES IN BOARD CAN BE BUILD DOWN BY DECRESCENT CARD RANK";TEXT_HELP2="YOU CAN PICK AND DRAG ONLY CARDS STACK WITH SAME SUIT";TEXT_HELP3="THE GOAL IS TO REMOVE ALL CARD FROM BOARD BY SCORING ROYAL FLUSHES (SAME SUIT), FROM KING TO ACE";TEXT_HELP4="DECK CAN BE USED ONLY IF THERE ARE AT LAST ONE CARD IN EACH COLUMN";TEXT_HELP1_PAGE2="SCORE SYSTEM";TEXT_HELP2_PAGE2="You can earn ";TEXT_WIN_PAGE2=" Points by scoring a royal flush";
TEXT_LOSE1_PAGE2="Don't use too many moves. You lose ";TEXT_LOSE2_PAGE2=" Point every move";TEXT_MODE_1="1 SUIT";TEXT_MODE_2="2 SUIT";TEXT_MODE_3="4 SUIT";TEXT_EASY="EASY";TEXT_NORMAL="MEDIUM";TEXT_HARD="HARD";TEXT_TOP_MODE="CHOSE GAME MODE";