function CSpriteLibrary(){var e={},c,a,b,g,f,d;this.init=function(e,h,q){c={};b=a=0;g=e;f=h;d=q};this.addSprite=function(b,d){e.hasOwnProperty(b)||(e[b]=c[b]={szPath:d,oSprite:new Image,bLoaded:!1},a++)};this.getSprite=function(b){return e.hasOwnProperty(b)?e[b].oSprite:null};this._onSpritesLoaded=function(){a=0;f.call(d)};this._onSpriteLoaded=function(e){g.call(d,e);++b===a&&this._onSpritesLoaded()};this.loadSprites=function(){for(var b in c)c[b].oSprite.oSpriteLibrary=this,c[b].oSprite.szKey=b,
c[b].oSprite.onload=function(){this.oSpriteLibrary.setLoaded(this.szKey);this.oSpriteLibrary._onSpriteLoaded(this.szKey)},c[b].oSprite.src=c[b].szPath};this.setLoaded=function(b){e[b].bLoaded=!0};this.isLoaded=function(b){return e[b].bLoaded};this.getNumSprites=function(){return a}}
var CANVAS_WIDTH=690,CANVAS_HEIGHT=960,EDGEBOARD_X=75,EDGEBOARD_Y=75,FPS=30,DISABLE_SOUND_MOBILE=!1,STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,IDLE_DELAY=1,ENEMY_ATTACK_OCCURR,ENEMY_MIN_ACTION_TIME,ENEMY_MAX_ACTION_TIME,ENEMY_MIN_GUARD_TIME,ENEMY_MAX_GUARD_TIME,ENEMY_HP,PLAYER_HP,PLAYER_STAMINA,STAMINA_PUNCH_LIMIT,ENEMY_KO=30,PLAYER_KO=30,PLAYER_MIN_HP_KO=15,STAMINA_REGEN_TIME=120,KO_REGEN_TIME=
2E3,ENEMY_MIN_HP_KO=15,IDLE="idle",GUARD="guard",JAB="jab",HOOK_R="hook_r",HOOK_L="hook_l",UPPERCUT="uppercut",GETPUNCHED="get_punched",KO="ko",s_aBw_Frame=[];s_aBw_Frame[IDLE]=9;s_aBw_Frame[GUARD]=10;s_aBw_Frame[JAB]=10;s_aBw_Frame[HOOK_R]=9;s_aBw_Frame[HOOK_L]=9;s_aBw_Frame[UPPERCUT]=10;s_aBw_Frame[GETPUNCHED]=5;s_aBw_Frame[KO]=13;var s_aBb_En_Frame=[];s_aBb_En_Frame[IDLE]=9;s_aBb_En_Frame[GUARD]=10;s_aBb_En_Frame[JAB]=10;s_aBb_En_Frame[HOOK_R]=9;s_aBb_En_Frame[HOOK_L]=10;
s_aBb_En_Frame[UPPERCUT]=11;s_aBb_En_Frame[GETPUNCHED]=5;s_aBb_En_Frame[KO]=24;var s_aBb_Frame=[];s_aBb_Frame[IDLE]=9;s_aBb_Frame[GUARD]=10;s_aBb_Frame[JAB]=10;s_aBb_Frame[HOOK_R]=9;s_aBb_Frame[HOOK_L]=9;s_aBb_Frame[UPPERCUT]=10;s_aBb_Frame[GETPUNCHED]=5;s_aBb_Frame[KO]=13;var s_aBw_En_Frame=[];s_aBw_En_Frame[IDLE]=9;s_aBw_En_Frame[GUARD]=10;s_aBw_En_Frame[JAB]=10;s_aBw_En_Frame[HOOK_R]=9;s_aBw_En_Frame[HOOK_L]=10;s_aBw_En_Frame[UPPERCUT]=11;s_aBw_En_Frame[GETPUNCHED]=5;s_aBw_En_Frame[KO]=24;
var s_aSt_Decrese=[];s_aSt_Decrese[JAB]=15;s_aSt_Decrese[HOOK_R]=17;s_aSt_Decrese[HOOK_L]=20;s_aSt_Decrese[UPPERCUT]=30;var s_aFrameHit=[];s_aFrameHit[JAB]=4;s_aFrameHit[HOOK_R]=4;s_aFrameHit[HOOK_L]=5;s_aFrameHit[UPPERCUT]=6;var s_aDamage=[];s_aDamage[JAB]=4;s_aDamage[HOOK_R]=5;s_aDamage[HOOK_L]=6;s_aDamage[UPPERCUT]=8;var ANIMATION_OFFSET_ENEMY=[];ANIMATION_OFFSET_ENEMY[IDLE]={xb:0,yb:0,xw:0,yw:0};ANIMATION_OFFSET_ENEMY[GUARD]={xb:0,yb:0,xw:0,yw:0};ANIMATION_OFFSET_ENEMY[JAB]={xb:5,yb:0,xw:0,yw:0};
ANIMATION_OFFSET_ENEMY[HOOK_R]={xb:-20,yb:0,xw:0,yw:0};ANIMATION_OFFSET_ENEMY[HOOK_L]={xb:-20,yb:0,xw:0,yw:0};ANIMATION_OFFSET_ENEMY[UPPERCUT]={xb:-30,yb:0,xw:0,yw:0};ANIMATION_OFFSET_ENEMY[GETPUNCHED]={xb:20,yb:0,xw:0,yw:0};var PARTICLE_OFFSET_PLAYER=[];PARTICLE_OFFSET_PLAYER[JAB]={xp:-50,yp:-70};PARTICLE_OFFSET_PLAYER[HOOK_R]={xp:-5,yp:-70};PARTICLE_OFFSET_PLAYER[HOOK_L]={xp:-35,yp:-70};PARTICLE_OFFSET_PLAYER[UPPERCUT]={xp:-15,yp:-70};
function CVersusPanel(){var e,c,a,b,g,f,d;this._init=function(){e=createBitmap(s_oSpriteLibrary.getSprite("bg_pselection"));s_oStage.addChild(e);0===s_iPlayerSelected?(b=new createjs.BitmapText(TEXT_BOXERW,s_oSpriteSheetBoxing),b.regX=b.getBounds().width/2,b.regY=b.getBounds().height/2,b.x=270,b.y=350,g=new createjs.BitmapText(TEXT_BOXERB,s_oSpriteSheetBoxing),g.regX=g.getBounds().width/2,g.regY=g.getBounds().height/2,g.x=460,g.y=750,c=createBitmap(s_oSpriteLibrary.getSprite("bw_versus")),a=createBitmap(s_oSpriteLibrary.getSprite("bb_versus"))):
(b=new createjs.BitmapText(TEXT_BOXERB,s_oSpriteSheetBoxing),b.regX=b.getBounds().width/2,b.regY=b.getBounds().height/2,b.x=270,b.y=350,g=new createjs.BitmapText(TEXT_BOXERW,s_oSpriteSheetBoxing),g.regX=g.getBounds().width/2,g.regY=g.getBounds().height/2,g.x=460,g.y=750,c=createBitmap(s_oSpriteLibrary.getSprite("bb_versus")),a=createBitmap(s_oSpriteLibrary.getSprite("bw_versus")));b.visible=!1;g.visible=!1;c.x=0;c.y=250;c.regX=c.getBounds().width/2;c.regY=c.getBounds().height/2;a.x=CANVAS_WIDTH;a.y=
650;a.regX=a.getBounds().width/2;a.regY=a.getBounds().height/2;d=new createjs.BitmapText("Loading...",s_oSpriteSheetBoxing);d.regX=d.getBounds().width/2;d.regY=d.getBounds().height/2;d.x=CANVAS_WIDTH/2;d.y=850;s_oStage.addChild(c);s_oStage.addChild(a);s_oStage.addChild(b);s_oStage.addChild(g);s_oStage.addChild(d);createjs.Tween.get(c).to({x:250},700);createjs.Tween.get(a).to({x:440},700);f=createBitmap(s_oSpriteLibrary.getSprite("vs"));f.regX=f.getBounds().width/2;f.regY=f.getBounds().height/2;f.x=
CANVAS_WIDTH/2;f.y=CANVAS_HEIGHT/2;s_oStage.addChild(f);f.scaleX=f.scaleY=2.5;f.alpha=.6;f.visible=!0;createjs.Tween.get(f).to({scaleX:1,scaleY:1,alpha:1},400,createjs.Ease.cubicIn).call(function(){b.scaleX=b.scaleY=2;b.alpha=.8;b.visible=!0;createjs.Tween.get(b).to({scaleX:1,scaleY:1,alpha:1},400,createjs.Ease.elasticOut).call(function(){g.scaleX=g.scaleY=2;g.alpha=.8;g.visible=!0;createjs.Tween.get(g).to({scaleX:1,scaleY:1,alpha:1},400,createjs.Ease.elasticOut).call(function(){})})})};this.setIndex=
function(k){s_oStage.setChildIndex(e,k);s_oStage.setChildIndex(c,k);s_oStage.setChildIndex(a,k);s_oStage.setChildIndex(b,k);s_oStage.setChildIndex(g,k);s_oStage.setChildIndex(f,k);s_oStage.setChildIndex(d,k)};this.unload=function(){s_oStage.removeChild(e);s_oStage.removeChild(c);s_oStage.removeChild(a);s_oStage.removeChild(b);s_oStage.removeChild(g);s_oStage.removeChild(f);s_oStage.removeChild(d)};this._init()}
function CToggle(e,c,a,b,g){var f,d,k,h,q;this._init=function(b,e,a,c){d=[];k=[];var g=new createjs.SpriteSheet({images:[a],frames:{width:a.width/2,height:a.height,regX:a.width/2/2,regY:a.height/2},animations:{state_true:[0],state_false:[1]}});f=c;h=createSprite(g,"state_"+f,a.width/2/2,a.height/2,a.width/2,a.height);h.x=b;h.y=e;h.stop();q.addChild(h);this._initListener()};this.unload=function(){h.off("mousedown",this.buttonDown);h.off("pressup",this.buttonRelease);q.removeChild(h)};this._initListener=
function(){h.on("mousedown",this.buttonDown);h.on("pressup",this.buttonRelease)};this.addEventListener=function(b,a,e){d[b]=a;k[b]=e};this.setActive=function(b){f=b;h.gotoAndStop("state_"+f)};this.buttonRelease=function(){h.scaleX=1;h.scaleY=1;f=!f;h.gotoAndStop("state_"+f);d[ON_MOUSE_UP]&&d[ON_MOUSE_UP].call(k[ON_MOUSE_UP],f)};this.buttonDown=function(){h.scaleX=.9;h.scaleY=.9;d[ON_MOUSE_DOWN]&&d[ON_MOUSE_DOWN].call(k[ON_MOUSE_DOWN])};this.setPosition=function(b,d){h.x=b;h.y=d};q=g;this._init(e,
c,a,b)}var s_iScaleFactor=1,s_oCanvasLeft,s_oCanvasTop,s_oMultiplier;
(function(e){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(e)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(e.substr(0,4))})(navigator.userAgent||
navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});$(window).blur(function(){s_oMain.stopUpdate()});$(window).focus(function(){s_oMain.startUpdate()});function trace(e){console.log(e)}
function getSize(e){var c=e.toLowerCase(),a=window.document,b=a.documentElement;if(void 0===window["inner"+e])e=b["client"+e];else if(window["inner"+e]!=b["client"+e]){var g=a.createElement("body");g.id="vpw-test-b";g.style.cssText="overflow:scroll";var f=a.createElement("div");f.id="vpw-test-d";f.style.cssText="position:absolute;top:-1000px";f.innerHTML="<style>@media("+c+":"+b["client"+e]+"px){body#vpw-test-b div#vpw-test-d{"+c+":7px!important}}</style>";g.appendChild(f);b.insertBefore(g,a.head);
e=7==f["offset"+e]?b["client"+e]:window["inner"+e];b.removeChild(g)}else e=window["inner"+e];return e}$(window).ready(function(){sizeHandler()});window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}
function getHeightOfIOSToolbars(){var e=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<e?e:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var e;e=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var c=getSize("Width"),a=Math.min(e/CANVAS_HEIGHT,c/CANVAS_WIDTH),b=CANVAS_WIDTH*a,g=CANVAS_HEIGHT*a,f=0;g<e?(f=e-g,g+=f,b+=CANVAS_WIDTH/CANVAS_HEIGHT*f):b<c&&(f=c-b,b+=f,g+=CANVAS_HEIGHT/CANVAS_WIDTH*f);var f=e/2-g/2,d=c/2-b/2,k=CANVAS_WIDTH/b;if(d*k<-EDGEBOARD_X||f*k<-EDGEBOARD_Y)a=Math.min(e/(CANVAS_HEIGHT-2*EDGEBOARD_Y),c/(CANVAS_WIDTH-2*
EDGEBOARD_X)),b=CANVAS_WIDTH*a,g=CANVAS_HEIGHT*a,f=(e-g)/2,d=(c-b)/2,k=CANVAS_WIDTH/b;s_iOffsetX=-1*d*k;s_iOffsetY=-1*f*k;0<=f&&(s_iOffsetY=0);0<=d&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oSelectCharacter&&s_oSelectCharacter.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);$("#canvas").css("width",b+"px");$("#canvas").css("height",g+"px");$("#canvasbg").css("width",b+"px");$("#canvasbg").css("height",
g+"px");$("#canvas_interface").css("width",b+"px");$("#canvas_interface").css("height",g+"px");0>f?($("#canvas").css("top",f+"px"),$("#canvasbg").css("top",f+"px"),$("#canvas_interface").css("top",f+"px")):($("#canvas").css("top","0px"),$("#canvasbg").css("top","0px"),$("#canvas_interface").css("top","0px"));$("#canvas").css("left",d+"px");$("#canvasbg").css("left",d+"px");$("#canvas_interface").css("left",d+"px");s_oMultiplier=a}}
function createBitmap(e,c,a){var b=new createjs.Bitmap(e),g=new createjs.Shape;c&&a?g.graphics.beginFill("#fff").drawRect(0,0,c,a):g.graphics.beginFill("#ff0").drawRect(0,0,e.width,e.height);b.hitArea=g;return b}function createSprite(e,c,a,b,g,f){e=null!==c?new createjs.Sprite(e,c):new createjs.Sprite(e);c=new createjs.Shape;c.graphics.beginFill("#000000").drawRect(-a,-b,g,f);e.hitArea=c;return e}
function randomFloatBetween(e,c,a){"undefined"===typeof a&&(a=2);return parseFloat(Math.min(e+Math.random()*(c-e),c).toFixed(a))}function rotateVector2D(e,c){var a=c.getX()*Math.cos(e)+c.getY()*Math.sin(e),b=c.getX()*-Math.sin(e)+c.getY()*Math.cos(e);c.set(a,b)}function tweenVectorsOnX(e,c,a){return e+a*(c-e)}function shuffle(e){for(var c=e.length,a,b;0!==c;)b=Math.floor(Math.random()*c),--c,a=e[c],e[c]=e[b],e[b]=a;return e}
function bubbleSort(e){var c;do{c=!1;for(var a=0;a<e.length-1;a++)e[a]>e[a+1]&&(c=e[a],e[a]=e[a+1],e[a+1]=c,c=!0)}while(c)}function compare(e,c){return e.index>c.index?-1:e.index<c.index?1:0}function easeLinear(e,c,a,b){return a*e/b+c}function easeInQuad(e,c,a,b){return a*(e/=b)*e+c}function easeInSine(e,c,a,b){return-a*Math.cos(e/b*(Math.PI/2))+a+c}function easeInCubic(e,c,a,b){return a*(e/=b)*e*e+c}
function getTrajectoryPoint(e,c){var a=new createjs.Point,b=(1-e)*(1-e),g=e*e;a.x=b*c.start.x+2*(1-e)*e*c.traj.x+g*c.end.x;a.y=b*c.start.y+2*(1-e)*e*c.traj.y+g*c.end.y;return a}function formatTime(e){e/=1E3;var c=Math.floor(e/60);e=Math.floor(e-60*c);var a="",a=10>c?a+("0"+c+":"):a+(c+":");return 10>e?a+("0"+e):a+e}function degreesToRadians(e){return e*Math.PI/180}function checkRectCollision(e,c){var a,b;a=getBounds(e,.9);b=getBounds(c,.98);return calculateIntersection(a,b)}
function calculateIntersection(e,c){var a,b,g,f,d,k,h,q;a=e.x+(g=e.width/2);b=e.y+(f=e.height/2);d=c.x+(k=c.width/2);h=c.y+(q=c.height/2);a=Math.abs(a-d)-(g+k);b=Math.abs(b-h)-(f+q);return 0>a&&0>b?(a=Math.min(Math.min(e.width,c.width),-a),b=Math.min(Math.min(e.height,c.height),-b),{x:Math.max(e.x,c.x),y:Math.max(e.y,c.y),width:a,height:b,rect1:e,rect2:c}):null}
function getBounds(e,c){var a={x:Infinity,y:Infinity,width:0,height:0};if(e instanceof createjs.Container){a.x2=-Infinity;a.y2=-Infinity;var b=e.children,g=b.length,f,d;for(d=0;d<g;d++)f=getBounds(b[d],1),f.x<a.x&&(a.x=f.x),f.y<a.y&&(a.y=f.y),f.x+f.width>a.x2&&(a.x2=f.x+f.width),f.y+f.height>a.y2&&(a.y2=f.y+f.height);Infinity==a.x&&(a.x=0);Infinity==a.y&&(a.y=0);Infinity==a.x2&&(a.x2=0);Infinity==a.y2&&(a.y2=0);a.width=a.x2-a.x;a.height=a.y2-a.y;delete a.x2;delete a.y2}else{var k,h;e instanceof createjs.Bitmap?
(g=e.sourceRect||e.image,d=g.width*c,k=g.height*c):e instanceof createjs.Sprite?e.spriteSheet._frames&&e.spriteSheet._frames[e.currentFrame]&&e.spriteSheet._frames[e.currentFrame].image?(g=e.spriteSheet.getFrame(e.currentFrame),d=g.rect.width,k=g.rect.height,b=g.regX,h=g.regY):(a.x=e.x||0,a.y=e.y||0):(a.x=e.x||0,a.y=e.y||0);b=b||0;d=d||0;h=h||0;k=k||0;a.regX=b;a.regY=h;g=e.localToGlobal(0-b,0-h);f=e.localToGlobal(d-b,k-h);d=e.localToGlobal(d-b,0-h);b=e.localToGlobal(0-b,k-h);a.x=Math.min(Math.min(Math.min(g.x,
f.x),d.x),b.x);a.y=Math.min(Math.min(Math.min(g.y,f.y),d.y),b.y);a.width=Math.max(Math.max(Math.max(g.x,f.x),d.x),b.x)-a.x;a.height=Math.max(Math.max(Math.max(g.y,f.y),d.y),b.y)-a.y}return a}function NoClickDelay(e){this.element=e;window.Touch&&this.element.addEventListener("touchstart",this,!1)}function shuffle(e){for(var c=e.length,a,b;0<c;)b=Math.floor(Math.random()*c),c--,a=e[c],e[c]=e[b],e[b]=a;return e}
NoClickDelay.prototype={handleEvent:function(e){switch(e.type){case "touchstart":this.onTouchStart(e);break;case "touchmove":this.onTouchMove(e);break;case "touchend":this.onTouchEnd(e)}},onTouchStart:function(e){e.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(e){this.moved=!0},onTouchEnd:function(e){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){e=document.elementFromPoint(e.changedTouches[0].clientX,e.changedTouches[0].clientY);3==e.nodeType&&(e=e.parentNode);var c=document.createEvent("MouseEvents");c.initEvent("click",!0,!0);e.dispatchEvent(c)}}};
(function(){function e(a){var b={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};a=a||window.event;a.type in b?document.body.className=b[a.type]:(document.body.className=this[c]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var c="hidden";c in document?document.addEventListener("visibilitychange",e):(c="mozHidden")in document?document.addEventListener("mozvisibilitychange",e):(c="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",e):(c="msHidden")in document?document.addEventListener("msvisibilitychange",e):"onfocusin"in document?document.onfocusin=document.onfocusout=e:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=e})();
function CSelectCharacter(){var e,c,a,b,g,f,d,k,h,q,l,p,m,n,r;this._init=function(){f=g=5;e=CANVAS_WIDTH/2;c=60;d=createBitmap(s_oSpriteLibrary.getSprite("bg_pselection"));s_oStage.addChild(d);q=createBitmap(s_oSpriteLibrary.getSprite("logo"));q.x=g;q.y=f;s_oStage.addChild(q);l=createBitmap(s_oSpriteLibrary.getSprite("logo_text"));l.regX=165;l.x=e;l.y=c;s_oStage.addChild(l);var t=s_oSpriteLibrary.getSprite("bw_selection");k=new CSelectButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-600,t,!0);k.addEventListener(ON_MOUSE_UP,
this._onButChooseWhite,this);t=s_oSpriteLibrary.getSprite("bb_selection");h=new CSelectButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-300,t,!0);h.addEventListener(ON_MOUSE_UP,this._onButChooseBlack,this);p=new createjs.BitmapText(TEXT_BOXERW,s_oSpriteSheetBoxing);p.regX=p.getBounds().width/2;p.regY=p.getBounds().height/2;p.x=CANVAS_WIDTH/2+50;p.y=463;s_oStage.addChild(p);m=new createjs.BitmapText(TEXT_BOXERB,s_oSpriteSheetBoxing);m.regX=m.getBounds().width/2;m.regY=m.getBounds().height/2;m.x=CANVAS_WIDTH/2+
65;m.y=CANVAS_HEIGHT-200;s_oStage.addChild(m);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)t=s_oSpriteLibrary.getSprite("audio_icon"),a=CANVAS_WIDTH-40,b=50,r=new CToggle(a,b,t,s_bAudioActive,s_oStage),r.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);this.refreshButtonPos(s_iOffsetX,s_iOffsetY);n=createBitmap(s_oSpriteLibrary.getSprite("fade"));s_oStage.addChild(n);createjs.Tween.get(n).to({alpha:0},500).call(function(){n.visible=!1})};this.unload=function(){s_oStage.removeAllChildren();s_oSelectCharacter=
null};this.refreshButtonPos=function(d,e){q.x=g+d;q.y=e+f;!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||r.setPosition(a-d,b+e);l.y=e+c};this._onButChooseWhite=function(){s_iPlayerSelected=0;this.unload();setTimeout(function(){s_oMain.gotoGame()},200)};this._onButChooseBlack=function(){s_iPlayerSelected=1;this.unload();setTimeout(function(){s_oMain.gotoGame()},200)};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};s_oSelectCharacter=this;this._init()}
var s_oSelectCharacter=null;
function CSelectButton(e,c,a,b){var g,f,d,k;this._init=function(b,a,e,c){f=[];d=[];var m=new createjs.SpriteSheet({images:[e],frames:{width:e.width/2,height:e.height,regX:e.width/2/2,regY:e.height/2},animations:{state_true:[0],state_false:[1]}});g=c;k=createSprite(m,"state_"+g,e.width/2/2,e.height/2,e.width/2,e.height);k.x=b;k.y=a;k.stop();s_oStage.addChild(k);this._initListener()};this.unload=function(){k.off("mousedown",this.buttonDown);k.off("pressup",this.buttonRelease);s_oStage.removeChild(k)};
this._initListener=function(){k.on("mousedown",this.buttonDown);k.on("pressup",this.buttonRelease)};this.addEventListener=function(b,e,a){f[b]=e;d[b]=a};this.setActive=function(b){g=b;k.gotoAndStop("state_"+g)};this.buttonRelease=function(){k.scaleX=1;k.scaleY=1;g=!g;k.gotoAndStop("state_"+g);f[ON_MOUSE_UP]&&f[ON_MOUSE_UP].call(d[ON_MOUSE_UP],g)};this.buttonDown=function(){k.gotoAndStop("state_false");f[ON_MOUSE_DOWN]&&f[ON_MOUSE_DOWN].call(d[ON_MOUSE_DOWN])};this.setPosition=function(b,d){k.x=b;
k.y=d};this._init(e,c,a,b)}
function CPreloader(){var e,c;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.loadSprites();c=new CContainer(0,0)};this.unload=function(){c.removeAllChildren();s_oStage.removeChild(e)};this.hide=function(){var e=this;setTimeout(function(){e.unload();s_oMain.gotoMenu()},1E3)};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};
this.attachSprites=function(){var a=s_oSpriteLibrary.getSprite("bg_menu"),a=createBitmap(a),a=new CChild(0,0,a,c);c.addChild(a);e=new createjs.BitmapText("0%",s_oSpriteSheetBoxing);e.regX=e.getBounds().width/2;e.regY=e.getBounds().height/2;e.x=CANVAS_WIDTH/2;e.y=CANVAS_HEIGHT-150;s_oStage.addChild(e)};this.refreshLoader=function(a){e.text=a+"%"};this._init()}
function CPlayer(e,c){var a=1,b=1,g,f="idle",d,k,h,q,l,p,m,n,r;this._init=function(b,e){d=new CContainer(b,e);if(0===s_iPlayerSelected){k=[];for(var a,c=0;c<s_aBw_Frame[IDLE];c++){a="bw_idle_"+c;a=s_oSpriteLibrary.getSprite(a);var f=createBitmap(a);k[c]=new CChild(0,0,f,d);k[c].setVisible(!1);k[c].setRegX(a.width/2);k[c].setRegY(a.height);d.addChild(k[c])}k[0].setVisible(!0);q=[];for(c=0;c<s_aBw_Frame[JAB];c++)a="bw_jab_"+c,a=s_oSpriteLibrary.getSprite(a),f=createBitmap(a),q[c]=new CChild(0,0,f,d),
q[c].setVisible(!1),q[c].setRegX(a.width/2),q[c].setRegY(a.height),d.addChild(q[c]);l=[];for(c=0;c<s_aBw_Frame[HOOK_R];c++)a="bw_hook_r_"+c,a=s_oSpriteLibrary.getSprite(a),f=createBitmap(a),l[c]=new CChild(0,0,f,d),l[c].setVisible(!1),l[c].setRegX(a.width/2),l[c].setRegY(a.height),d.addChild(l[c]);p=[];for(c=0;c<s_aBw_Frame[HOOK_L];c++)a="bw_hook_l_"+c,a=s_oSpriteLibrary.getSprite(a),f=createBitmap(a),p[c]=new CChild(0,0,f,d),p[c].setVisible(!1),p[c].setRegX(a.width/2),p[c].setRegY(a.height),d.addChild(p[c]);
m=[];for(c=0;c<s_aBw_Frame[UPPERCUT];c++)a="bw_uppercut_"+c,a=s_oSpriteLibrary.getSprite(a),f=createBitmap(a),m[c]=new CChild(0,0,f,d),m[c].setVisible(!1),m[c].setRegX(a.width/2),m[c].setRegY(a.height),d.addChild(m[c]);n=[];for(c=0;c<s_aBw_Frame[GETPUNCHED];c++)a="bw_get_punched_"+c,a=s_oSpriteLibrary.getSprite(a),f=createBitmap(a),n[c]=new CChild(0,0,f,d),n[c].setVisible(!1),n[c].setRegX(a.width/2),n[c].setRegY(a.height),d.addChild(n[c]);r=[];for(c=0;c<s_aBw_Frame[KO];c++)a="bw_ko_"+c,a=s_oSpriteLibrary.getSprite(a),
f=createBitmap(a),r[c]=new CChild(0,0,f,d),r[c].setVisible(!1),r[c].setRegX(a.width/2),r[c].setRegY(a.height),d.addChild(r[c]);h=[];for(c=0;c<s_aBw_Frame[GUARD];c++)a="bw_guard_"+c,a=s_oSpriteLibrary.getSprite(a),f=createBitmap(a),h[c]=new CChild(0,0,f,d),h[c].setVisible(!1),h[c].setRegX(a.width/2),h[c].setRegY(a.height),d.addChild(h[c])}else{k=[];for(c=0;c<s_aBb_Frame[IDLE];c++)a="bb_idle_"+c,a=s_oSpriteLibrary.getSprite(a),f=createBitmap(a),k[c]=new CChild(0,0,f,d),k[c].setVisible(!1),k[c].setRegX(a.width/
2),k[c].setRegY(a.height),d.addChild(k[c]);k[0].setVisible(!0);q=[];for(c=0;c<s_aBb_Frame[JAB];c++)a="bb_jab_"+c,a=s_oSpriteLibrary.getSprite(a),f=createBitmap(a),q[c]=new CChild(0,0,f,d),q[c].setVisible(!1),q[c].setRegX(a.width/2),q[c].setRegY(a.height),d.addChild(q[c]);l=[];for(c=0;c<s_aBb_Frame[HOOK_R];c++)a="bb_hook_r_"+c,a=s_oSpriteLibrary.getSprite(a),f=createBitmap(a),l[c]=new CChild(0,0,f,d),l[c].setVisible(!1),l[c].setRegX(a.width/2),l[c].setRegY(a.height),d.addChild(l[c]);p=[];for(c=0;c<
s_aBb_Frame[HOOK_L];c++)a="bb_hook_l_"+c,a=s_oSpriteLibrary.getSprite(a),f=createBitmap(a),p[c]=new CChild(0,0,f,d),p[c].setVisible(!1),p[c].setRegX(a.width/2),p[c].setRegY(a.height),d.addChild(p[c]);m=[];for(c=0;c<s_aBb_Frame[UPPERCUT];c++)a="bb_uppercut_"+c,a=s_oSpriteLibrary.getSprite(a),f=createBitmap(a),m[c]=new CChild(0,0,f,d),m[c].setVisible(!1),m[c].setRegX(a.width/2),m[c].setRegY(a.height),d.addChild(m[c]);n=[];for(c=0;c<s_aBb_Frame[GETPUNCHED];c++)a="bb_get_punched_"+c,a=s_oSpriteLibrary.getSprite(a),
f=createBitmap(a),n[c]=new CChild(0,0,f,d),n[c].setVisible(!1),n[c].setRegX(a.width/2),n[c].setRegY(a.height),d.addChild(n[c]);r=[];for(c=0;c<s_aBb_Frame[KO];c++)a="bb_ko_"+c,a=s_oSpriteLibrary.getSprite(a),f=createBitmap(a),r[c]=new CChild(0,0,f,d),r[c].setVisible(!1),r[c].setRegX(a.width/2),r[c].setRegY(a.height),d.addChild(r[c]);h=[];for(c=0;c<s_aBb_Frame[GUARD];c++)a="bb_guard_"+c,a=s_oSpriteLibrary.getSprite(a),f=createBitmap(a),h[c]=new CChild(0,0,f,d),h[c].setVisible(!1),h[c].setRegX(a.width/
2),h[c].setRegY(a.height),d.addChild(h[c])}g=s_oStage.getChildIndex(f)};this._onJabHit=function(){s_oGame.hitEnemy(s_aDamage[JAB])};this._onHookRHit=function(){s_oGame.hitEnemy(s_aDamage[HOOK_R])};this._onHookLHit=function(){s_oGame.hitEnemy(s_aDamage[HOOK_L])};this._onUppercutHit=function(){s_oGame.hitEnemy(s_aDamage[UPPERCUT])};this._animIdle=function(){0===b?(k[8].setVisible(!1),k[0].setVisible(!0)):(k[b-1].setVisible(!1),k[b].setVisible(!0));b++;b>s_aBw_Frame[IDLE]-1&&(b=0)};this._animGuard=function(){0===
b?(h[9].setVisible(!1),h[0].setVisible(!0)):(h[b-1].setVisible(!1),h[b].setVisible(!0));b++;b>s_aBw_Frame[GUARD]-1&&(b=0)};this._animJab=function(){0===b?q[0].setVisible(!0):(q[b-1].setVisible(!1),q[b].setVisible(!0));b===s_aFrameHit[JAB]&&(s_oGame.playParticle(PARTICLE_OFFSET_PLAYER[JAB].xp,PARTICLE_OFFSET_PLAYER[JAB].yp),this._onJabHit(),!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||!1!==s_oGame.getEGuard()||createjs.Sound.play("punch_left"));2===b&&s_oGame.reduceStamina(s_aSt_Decrese[JAB]);b++;b>
s_aBw_Frame[JAB]-1&&(k[0].setVisible(!0),this.changeState("idle"),s_oGame.setPBlocked(!1),s_oGame.setPIsPunching(!1),s_oInterface.setGuardButVisibilty(!0))};this._animHookR=function(){0===b?l[0].setVisible(!0):(l[b-1].setVisible(!1),l[b].setVisible(!0));b===s_aFrameHit[HOOK_R]&&(s_oGame.playParticle(PARTICLE_OFFSET_PLAYER[HOOK_R].xp,PARTICLE_OFFSET_PLAYER[HOOK_R].yp),this._onHookRHit(),!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||!1!==s_oGame.getEGuard()||createjs.Sound.play("punch_right"));2===b&&
s_oGame.reduceStamina(s_aSt_Decrese[HOOK_R]);b++;b>s_aBw_Frame[HOOK_R]-1&&(k[0].setVisible(!0),this.changeState("idle"),s_oGame.setPBlocked(!1),s_oGame.setPIsPunching(!1),s_oInterface.setGuardButVisibilty(!0))};this._animHookL=function(){0===b?p[0].setVisible(!0):(p[b-1].setVisible(!1),p[b].setVisible(!0));b===s_aFrameHit[HOOK_L]&&(s_oGame.playParticle(PARTICLE_OFFSET_PLAYER[HOOK_L].xp,PARTICLE_OFFSET_PLAYER[HOOK_L].yp),this._onHookLHit(),!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||!1!==s_oGame.getEGuard()||
createjs.Sound.play("punch_left"));2===b&&s_oGame.reduceStamina(s_aSt_Decrese[HOOK_L]);b++;b>s_aBw_Frame[HOOK_L]-1&&(k[0].setVisible(!0),this.changeState("idle"),s_oGame.setPBlocked(!1),s_oGame.setPIsPunching(!1),s_oInterface.setGuardButVisibilty(!0))};this._animUppercut=function(){0===b?m[0].setVisible(!0):(m[b-1].setVisible(!1),m[b].setVisible(!0));b===s_aFrameHit[UPPERCUT]&&(s_oGame.playParticle(PARTICLE_OFFSET_PLAYER[UPPERCUT].xp,PARTICLE_OFFSET_PLAYER[UPPERCUT].yp),this._onUppercutHit(),!1!==
DISABLE_SOUND_MOBILE&&!1!==s_bMobile||!1!==s_oGame.getEGuard()||createjs.Sound.play("uppercut"));2===b&&s_oGame.reduceStamina(s_aSt_Decrese[UPPERCUT]);b++;b>s_aBw_Frame[UPPERCUT]-1&&(k[0].setVisible(!0),this.changeState("idle"),s_oGame.setPBlocked(!1),s_oGame.setPIsPunching(!1),s_oInterface.setGuardButVisibilty(!0))};this._animGetPunched=function(){0===b?n[0].setVisible(!0):(n[b-1].setVisible(!1),n[b].setVisible(!0));b++;b>s_aBw_Frame[GETPUNCHED]-1&&(k[0].setVisible(!0),this.changeState("idle"),s_oGame.setPBlocked(!1),
s_oInterface.setGuardButVisibilty(!0))};this._animKo=function(){0===b?(s_oInterface.setGuardButVisibilty(!1),r[0].setVisible(!0)):(r[b-1].setVisible(!1),r[b].setVisible(!0));8===b&&(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("falling"));b++;b>s_aBw_Frame[KO]-1&&s_oGame.playerKo()};this.changeState=function(c){c===GUARD&&h[0].setVisible(!0);"get_punched"===c&&n[0].setVisible(!0);"ko"===c&&r[0].setVisible(!0);c===IDLE&&k[0].setVisible(!0);switch(f){case IDLE:for(var d=0;d<s_aBw_Frame[IDLE];d++)k[d].setVisible(!1);
a=1;break;case GUARD:for(d=0;d<s_aBw_Frame[GUARD];d++)h[d].setVisible(!1);a=1;break;case JAB:for(d=0;d<s_aBw_Frame[JAB];d++)q[d].setVisible(!1);a=1;break;case HOOK_R:for(d=0;d<s_aBw_Frame[HOOK_R];d++)l[d].setVisible(!1);a=1;break;case HOOK_L:for(d=0;d<s_aBw_Frame[HOOK_L];d++)p[d].setVisible(!1);a=1;break;case UPPERCUT:for(d=0;d<s_aBw_Frame[UPPERCUT];d++)m[d].setVisible(!1);a=1;break;case GETPUNCHED:for(d=0;d<s_aBw_Frame[GETPUNCHED];d++)n[d].setVisible(!1);a=1;break;case KO:for(d=0;d<s_aBw_Frame[KO];d++)r[d].setVisible(!1);
a=1}f=c;b=0};this.moveGuard=function(){d.setTween({y:d.getY()+30},100,function(){d.setTween({y:d.getY()-30},100)})};this.setVisible=function(a){d.setVisible(a)};this.getMaxIndex=function(){return g};this.playAllAnim=function(){switch(f){case IDLE:b<s_aBw_Frame[IDLE]-1?(0===b?k[0].setVisible(!0):(k[b-1].setVisible(!1),k[b].setVisible(!0)),b++):(b=0,this.changeState(GUARD));break;case GUARD:b<s_aBw_Frame[GUARD]-1?(0===b?h[0].setVisible(!0):(h[b-1].setVisible(!1),h[b].setVisible(!0)),b++):(b=0,this.changeState(JAB));
break;case JAB:b<s_aBw_Frame[JAB]-1?(0===b?q[0].setVisible(!0):(q[b-1].setVisible(!1),q[b].setVisible(!0)),b++):(b=0,this.changeState(HOOK_R));break;case HOOK_R:b<s_aBw_Frame[HOOK_R]-1?(0===b?l[0].setVisible(!0):(l[b-1].setVisible(!1),l[b].setVisible(!0)),b++):(b=0,this.changeState(HOOK_L));break;case HOOK_L:b<s_aBw_Frame[HOOK_L]-1?(0===b?p[0].setVisible(!0):(p[b-1].setVisible(!1),p[b].setVisible(!0)),b++):(b=0,this.changeState(UPPERCUT));break;case UPPERCUT:b<s_aBw_Frame[UPPERCUT]-1?(0===b?m[0].setVisible(!0):
(m[b-1].setVisible(!1),m[b].setVisible(!0)),b++):(b=0,this.changeState(GETPUNCHED));break;case GETPUNCHED:b<s_aBw_Frame[GETPUNCHED]-1?(0===b?n[0].setVisible(!0):(n[b-1].setVisible(!1),n[b].setVisible(!0)),b++):(b=0,this.changeState(KO));break;case KO:b<s_aBw_Frame[KO]-1?(0===b?r[0].setVisible(!0):(r[b-1].setVisible(!1),r[b].setVisible(!0)),b++):(s_oGame.onAllAnimPlayed(),this.changeState(IDLE))}};this.update=function(){switch(f){case IDLE:a!==IDLE_DELAY||s_oGame.getKoE()?a++:(a=0,this._animIdle());
break;case GUARD:a===IDLE_DELAY?(a=0,this._animGuard()):a++;break;case JAB:a!==IDLE_DELAY||s_oGame.getKoE()?a++:(a=0,this._animJab());break;case HOOK_R:a!==IDLE_DELAY||s_oGame.getKoE()?a++:(a=0,this._animHookR());break;case HOOK_L:a!==IDLE_DELAY||s_oGame.getKoE()?a++:(a=0,this._animHookL());break;case UPPERCUT:a!==IDLE_DELAY||s_oGame.getKoE()?a++:(a=0,this._animUppercut());break;case GETPUNCHED:a===IDLE_DELAY&&0<PLAYER_KO&&!s_oGame.getKoE()?(a=0,this._animGetPunched()):a++;break;case KO:a===IDLE_DELAY?
(a=0,this._animKo()):a++}};this._init(e,c)}
function CMenu(){var e,c,a,b,g,f,d,k;this._init=function(){a=CANVAS_WIDTH/2;b=CANVAS_HEIGHT-120;g=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(g);var h=s_oSpriteLibrary.getSprite("but_play");f=new CGfxButton(a,b,h,s_oStage);f.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)h=s_oSpriteLibrary.getSprite("audio_icon"),e=CANVAS_WIDTH-h.height/2-10,c=h.height/2+10,k=new CToggle(e,c,h,s_bAudioActive,s_oStage),k.addEventListener(ON_MOUSE_UP,
this._onAudioToggle,this);d=createBitmap(s_oSpriteLibrary.getSprite("fade"));s_oStage.addChild(d);createjs.Tween.get(d).to({alpha:0},500).call(function(){d.visible=!1});this.refreshButtonPos(s_iOffsetX,s_iOffsetY);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)null===s_oSoundtrack?s_oSoundtrack=createjs.Sound.play("soundtrack",{loop:-1}):s_oSoundtrack.play(),s_oSoundtrack.volume=1};this.unload=function(){s_oStage.removeAllChildren();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)k.unload(),k=null;s_oMenu=
null};this.refreshButtonPos=function(d,g){f.setPosition(a,b-g);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||k.setPosition(e-d,c+g)};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onButPlayRelease=function(){this.unload();s_oMain.gotoPSelection()};s_oMenu=this;this._init()}var s_oMenu=null;
function CMain(e,c){var a,b=0,g=0,f=STATE_LOADING,d,k,h;this.initContainer=function(){s_oCanvas=document.getElementById("canvas");location.search.match(/c/i)?(s_oStage=new createjs.Stage("canvas"),s_oStageBg=new createjs.Stage("canvasbg"),s_oStageInterface=new createjs.Stage("canvas_interface")):(s_oStage=new createjs.SpriteStage("canvas",!1,!1),s_oStageBg=new createjs.SpriteStage("canvasbg",!1,!1),s_oStageInterface=new createjs.SpriteStage("canvas_interface",!1,!1));createjs.Touch.enable(s_oStage);
s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&(s_oStage.enableMouseOver(20),$("body").on("contextmenu","#canvas",function(a){return!1}));s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.setFPS(FPS);navigator.userAgent.match(/Windows Phone/i)&&(DISABLE_SOUND_MOBILE=!0);s_oSpriteLibrary=new CSpriteLibrary;k=new CPreloader;new CBitmapFont};this.preloaderReady=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();this._loadImages();
a=!0};this.soundLoaded=function(a){b++;k.refreshLoader(Math.floor(b/g*100));b===g&&(k.unload(),this.gotoMenu())};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&(0<navigator.userAgent.indexOf("Opera")||0<navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=["mp3"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/start_match.ogg","start_match"),createjs.Sound.registerSound("./sounds/crowd_desperation.ogg",
"crowd_desperation"),createjs.Sound.registerSound("./sounds/crowd_exultance.ogg","crowd_exultance"),createjs.Sound.registerSound("./sounds/crowd_idle.ogg","crowd_idle"),createjs.Sound.registerSound("./sounds/ko.ogg","ko"),createjs.Sound.registerSound("./sounds/soundtrack.ogg","soundtrack"),createjs.Sound.registerSound("./sounds/falling.ogg","falling"),createjs.Sound.registerSound("./sounds/punch_left.ogg","punch_left"),createjs.Sound.registerSound("./sounds/punch_right.ogg","punch_right"),createjs.Sound.registerSound("./sounds/uppercut.ogg",
"uppercut"),createjs.Sound.registerSound("./sounds/1.ogg","1"),createjs.Sound.registerSound("./sounds/two.ogg","2"),createjs.Sound.registerSound("./sounds/three.ogg","3"),createjs.Sound.registerSound("./sounds/four.ogg","4"),createjs.Sound.registerSound("./sounds/five.ogg","5"),createjs.Sound.registerSound("./sounds/six.ogg","6"),createjs.Sound.registerSound("./sounds/seven.ogg","7"),createjs.Sound.registerSound("./sounds/eight.ogg","8"),createjs.Sound.registerSound("./sounds/nine.ogg","9")):(createjs.Sound.alternateExtensions=
["ogg"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/start_match.mp3","start_match"),createjs.Sound.registerSound("./sounds/crowd_desperation.mp3","crowd_desperation"),createjs.Sound.registerSound("./sounds/crowd_exultance.mp3","crowd_exultance"),createjs.Sound.registerSound("./sounds/crowd_idle.mp3","crowd_idle"),createjs.Sound.registerSound("./sounds/ko.mp3","ko"),createjs.Sound.registerSound("./sounds/soundtrack.mp3","soundtrack"),
createjs.Sound.registerSound("./sounds/falling.mp3","falling"),createjs.Sound.registerSound("./sounds/punch_left.mp3","punch_left"),createjs.Sound.registerSound("./sounds/punch_right.mp3","punch_right"),createjs.Sound.registerSound("./sounds/uppercut.mp3","uppercut"),createjs.Sound.registerSound("./sounds/one.mp3","1"),createjs.Sound.registerSound("./sounds/two.mp3","2"),createjs.Sound.registerSound("./sounds/three.mp3","3"),createjs.Sound.registerSound("./sounds/four.mp3","4"),createjs.Sound.registerSound("./sounds/five.mp3",
"5"),createjs.Sound.registerSound("./sounds/six.mp3","6"),createjs.Sound.registerSound("./sounds/seven.mp3","7"),createjs.Sound.registerSound("./sounds/eight.mp3","8"),createjs.Sound.registerSound("./sounds/nine.mp3","9")),g+=19)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("button","./sprites/button.png");s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("but_defence","./sprites/but_defence.png");
s_oSpriteLibrary.addSprite("energy_bar","./sprites/energy_bar.png");s_oSpriteLibrary.addSprite("fill_energy","./sprites/fill_energy.png");s_oSpriteLibrary.addSprite("mask_energy","./sprites/mask_energy.png");s_oSpriteLibrary.addSprite("fill_stamina","./sprites/fill_stamina.png");s_oSpriteLibrary.addSprite("energy_avatar_white","./sprites/energy_avatar_white.png");s_oSpriteLibrary.addSprite("energy_avatar_black","./sprites/energy_avatar_black.png");s_oSpriteLibrary.addSprite("icon_energy","./sprites/icon_energy.png");
s_oSpriteLibrary.addSprite("icon_stamina","./sprites/icon_stamina.png");s_oSpriteLibrary.addSprite("countdown_panel_white","./sprites/countdown_panel_white.png");s_oSpriteLibrary.addSprite("countdown_panel_black","./sprites/countdown_panel_black.png");s_oSpriteLibrary.addSprite("countdown_panel_continue_white","./sprites/countdown_panel_continue_white.png");s_oSpriteLibrary.addSprite("countdown_panel_continue_black","./sprites/countdown_panel_continue_black.png");s_oSpriteLibrary.addSprite("logo",
"./sprites/logo.png");s_oSpriteLibrary.addSprite("logo_text","./sprites/choose_player_text.png");s_oSpriteLibrary.addSprite("bw_selection","./sprites/bw_selection.png");s_oSpriteLibrary.addSprite("bb_selection","./sprites/bb_selection.png");s_oSpriteLibrary.addSprite("bw_versus","./sprites/bw_versus.png");s_oSpriteLibrary.addSprite("bb_versus","./sprites/bb_versus.png");s_oSpriteLibrary.addSprite("ko_white","./sprites/ko_player.png");s_oSpriteLibrary.addSprite("ko_black","./sprites/ko_enemy.png");
s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("bg_pselection","./sprites/bg_mod_menu.jpg");s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("fade","./sprites/fade.png");s_oSpriteLibrary.addSprite("vs","./sprites/vs.png");s_oSpriteLibrary.addSprite("but_exit_big","./sprites/but_exit_big.png");s_oSpriteLibrary.addSprite("but_restart","./sprites/but_restart.png");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");
s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("audio_icon2","./sprites/audio_icon2.png");s_oSpriteLibrary.addSprite("bg_help_1","./sprites/bg_help_1.png");s_oSpriteLibrary.addSprite("bg_help_2","./sprites/bg_help_2.png");s_oSpriteLibrary.addSprite("but_fight","./sprites/but_fight.png");s_oSpriteLibrary.addSprite("but_skip","./sprites/but_skip.png");for(var a=0;5>a;a++)s_oSpriteLibrary.addSprite("particle_"+a,"./sprites/particle/particle_"+a+".png");
g+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){b++;k.refreshLoader(Math.floor(b/g*100));b===g&&(k.unload(),this.gotoMenu())};this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this.gotoMenu=function(){new CMenu;f=STATE_MENU};this.gotoPSelection=function(){new CSelectCharacter};this.gotoGame=function(){h=new CGame(d);f=STATE_GAME;$(s_oMain).trigger("game_start")};this.gotoHelp=function(){new CHelp;
f=STATE_HELP};this.stopUpdate=function(){a=!1};this.startUpdate=function(){a=!0};this.playAllSounds=function(a){createjs.Sound.setMute(!a)};this._update=function(b){if(!1!==a){var c=(new Date).getTime();s_iTimeElaps=c-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=c;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);f===STATE_GAME&&h.update();s_oStage.update(b)}};s_oMain=this;d=e;this.initContainer()}
var s_bMobile,s_bLoadedPlayerWhite=!1,s_bLoadedPlayerBlack=!1,s_bAudioActive=!0,s_iPlayerSelected=0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oDrawLayer,s_oStage,s_oStageBg,s_oStageInterface,s_oMain=null,s_oSpriteLibrary,s_oCanvas,s_oSoundtrack=null;TEXT_BOXERW="IRONFIST";TEXT_BOXERB="DYNAMITE";
function CInterface(){var e,c,a,b,g,f,d=0,k,h,q,l,p,m,n,r,t,v,u,K,O,Q,z,x,w,C,B,L,R,y;this._init=function(){g=CANVAS_WIDTH/2;f=CANVAS_HEIGHT-70;var d=s_oSpriteLibrary.getSprite("but_defence");q=new CGfxButton(g,f,d,s_oStage);q.setVisible(!0);q.addEventListener(ON_MOUSE_UP,this._onGuardButReleased,this);q.addEventListener(ON_MOUSE_DOWN,this._onGuardButPressed,this);d=s_oSpriteLibrary.getSprite("fill_energy");t=createBitmap(d);t.regY=d.height;t.rotation=180;t.x=92;t.y=385;s_oStageInterface.addChild(t);
v=createBitmap(s_oSpriteLibrary.getSprite("mask_energy"));v.rotation=180;v.regY=d.height;v.x=92;v.y=385;v.scaleY=0;s_oStageInterface.addChild(v);d=s_oSpriteLibrary.getSprite("energy_bar");r=createBitmap(d);r.regY=d.height;r.rotation=180;r.x=102;r.y=375;s_oStageInterface.addChild(r);d=s_oSpriteLibrary.getSprite("fill_stamina");x=createBitmap(d);x.regY=d.height;x.rotation=180;x.x=112;x.y=385;s_oStageInterface.addChild(x);w=createBitmap(s_oSpriteLibrary.getSprite("mask_energy"));w.x=96;w.y=385;w.scaleY=
0;s_oStageInterface.addChild(w);d=s_oSpriteLibrary.getSprite("energy_bar");z=createBitmap(d);z.regY=d.height;z.rotation=180;z.x=122;z.y=375;s_oStageInterface.addChild(z);d=s_oSpriteLibrary.getSprite("fill_energy");B=createBitmap(d);B.x=576;B.y=190;s_oStageInterface.addChild(B);L=createBitmap(s_oSpriteLibrary.getSprite("mask_energy"));L.rotation=180;L.x=592;L.y=641;L.scaleY=0;s_oStageInterface.addChild(L);C=createBitmap(s_oSpriteLibrary.getSprite("energy_bar"));C.x=566;C.y=180;s_oStageInterface.addChild(C);
0===s_iPlayerSelected?(u=createBitmap(s_oSpriteLibrary.getSprite("energy_avatar_white")),R=createBitmap(s_oSpriteLibrary.getSprite("energy_avatar_black"))):(u=createBitmap(s_oSpriteLibrary.getSprite("energy_avatar_black")),R=createBitmap(s_oSpriteLibrary.getSprite("energy_avatar_white")));u.x=63;u.y=820;s_oStageInterface.addChild(u);R.x=551;R.y=160;s_oStageInterface.addChild(R);K=createBitmap(s_oSpriteLibrary.getSprite("icon_energy"));K.x=77;K.y=800;s_oStageInterface.addChild(K);O=createBitmap(s_oSpriteLibrary.getSprite("icon_stamina"));
O.x=98;O.y=800;s_oStageInterface.addChild(O);Q=createBitmap(s_oSpriteLibrary.getSprite("icon_energy"));Q.x=577;Q.y=200;s_oStageInterface.addChild(Q);d=s_oSpriteLibrary.getSprite("but_exit");a=CANVAS_WIDTH-120;b=50;n=new CGfxButton(a,b,d,s_oStage);n.addEventListener(ON_MOUSE_UP,this._onExitButReleased,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)e=CANVAS_WIDTH-40,c=50,m=new CToggle(e,c,s_oSpriteLibrary.getSprite("audio_icon2"),s_bAudioActive,s_oStage),m.addEventListener(ON_MOUSE_UP,this._onAudioToggle,
this);d=s_oSpriteLibrary.getSprite("but_exit_big");l=new CGfxButton(CANVAS_WIDTH/2-100,CANVAS_HEIGHT-200,d,s_oStage);l.setVisible(!1);l.addEventListener(ON_MOUSE_UP,this._onExitButReleased,this);d=s_oSpriteLibrary.getSprite("but_restart");p=new CGfxButton(CANVAS_WIDTH/2+100,CANVAS_HEIGHT-200,d,s_oStage);p.setVisible(!1);p.addEventListener(ON_MOUSE_UP,this._onRestartButReleased,this);y=[];for(var P=0;5>P;P++)d=s_oSpriteLibrary.getSprite("particle_"+P),y[P]=createBitmap(d),y[P].visible=!1,y[P].x=CANVAS_WIDTH/
2-100,y[P].y=300,s_oStage.addChild(y[P]);k=y[0].x;h=y[0].y;this.refreshButtonPos(s_iOffsetX,s_iOffsetY);s_oStageInterface.update()};this.unload=function(){};this.refreshButtonPos=function(d,x){q.setPosition(g,f-x);n.setPosition(a-d,b+x);s_oGame.setTapLimit(f-x);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||m.setPosition(e-d,c+x);s_oStageInterface.update()};this._onGuardButReleased=function(){s_oGame.getPIsPunching()||s_oGame.getKoP()||(s_oGame.changePlayerState(IDLE),s_oGame.setPBlocked(!1),s_oGame.setPGuard(!1))};
this._onGuardButPressed=function(){s_oGame.getPIsPunching()||s_oGame.getKoP()||(s_oGame.changePlayerState(GUARD),s_oGame.setPBlocked(!0),s_oGame.setPGuard(!0))};this._onExitButReleased=function(){s_oGame.onExit()};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onRestartButReleased=function(){s_oGame.onRestart()};this.setGuardButVisibilty=function(a){q.setVisible(a)};this.getGuardButVisibilty=function(){return q.getVisible()};this.setPlayerHp=
function(a){v.scaleY=1-a/100;s_oStageInterface.update()};this.setPlayerStamina=function(a){0>a&&(a=0);w.scaleY=1-a/100;s_oStageInterface.update()};this.setEnemyHp=function(a){L.scaleY=1-a/100;s_oStageInterface.update()};this.setKoButVisibility=function(a){l.setVisible(a);p.setVisible(a);s_oStageInterface.update()};this.setEnergyVisibility=function(a){r.visible=a;t.visible=a;v.visible=a;z.visible=a;x.visible=a;w.visible=a;C.visible=a;B.visible=a;L.visible=a;u.visible=a;R.visible=a;Q.visible=a;K.visible=
a;O.visible=a;s_oStageInterface.update()};this.playParticle=function(a,c){0===d?(y[0].visible=!0,y[0].x+=a,y[0].y+=c):(y[d-1].visible=!1,y[d-1].x=k,y[d-1].y=h,y[d].x+=a,y[d].y+=c,y[d].visible=!0);d++;5===d&&(s_oGame.stopParticle(),y[4].visible=!1,d=0)};s_oInterface=this;this._init();return this}var s_oInterface=null;
function CHelpPanel(){var e,c,a,b,g,f,d=0;this._init=function(){c=createBitmap(s_oSpriteLibrary.getSprite("bg_help_"+(d+1)));c.regX=c.getBounds().width/2;c.regY=c.getBounds().height/2;c.x=CANVAS_WIDTH/2;c.y=CANVAS_HEIGHT/2;s_oStage.addChild(c);a=new createjs.BitmapText("HOW TO PLAY",s_oSpriteSheetBoxing);a.regX=a.getBounds().width/2;a.regY=a.getBounds().height/2;a.x=CANVAS_WIDTH/2;a.y=180;s_oStage.addChild(a);var e=s_oSpriteLibrary.getSprite("but_skip");b=new CGfxButton(CANVAS_WIDTH-165,CANVAS_HEIGHT-
120,e,s_oStage);b.addEventListener(ON_MOUSE_UP,this._onSkipButtonPressedNext,this);e=s_oSpriteLibrary.getSprite("but_skip");g=new CGfxButton(165,CANVAS_HEIGHT-120,e,s_oStage);g.addEventListener(ON_MOUSE_UP,this._onSkipButtonPressedPrevious,this);g.setScaleX(-1);e=s_oSpriteLibrary.getSprite("but_fight");f=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-130,e,s_oStage);f.addEventListener(ON_MOUSE_UP,s_oGame.closeHelpPanel,this)};this._onSkipButtonPressedNext=function(){d+=1;2===d&&(d=0);c.image=s_oSpriteLibrary.getSprite("bg_help_"+
(d+1))};this._onSkipButtonPressedPrevious=function(){--d;-1===d&&(d=1);c.image=s_oSpriteLibrary.getSprite("bg_help_"+(d+1))};this.unload=function(){s_oStage.removeChild(e);s_oStage.removeChild(c);s_oStage.removeChild(a);b.unload();g.unload();f.unload()};e=this;this._init()}
function CGfxButton(e,c,a,b){var g,f,d,k;this._init=function(a,c,b){g=[];f=[];d=createBitmap(b);d.x=a;d.y=c;d.regX=b.width/2;d.regY=b.height/2;k.addChild(d);this._initListener()};this.unload=function(){d.off("mousedown",this.buttonDown);d.off("pressup",this.buttonRelease);k.removeChild(d)};this.setVisible=function(a){d.visible=a};this.getVisible=function(a){return d.visible};this._initListener=function(){d.on("mousedown",this.buttonDown);d.on("pressup",this.buttonRelease)};this.addEventListener=function(a,
d,c){g[a]=d;f[a]=c};this.buttonRelease=function(){d.scaleX=0<=d.scaleX?1:-1;d.scaleY=1;g[ON_MOUSE_UP]&&g[ON_MOUSE_UP].call(f[ON_MOUSE_UP]);k.update()};this.buttonDown=function(){d.scaleX=0<=d.scaleX?.9:-.9;d.scaleY=.9;g[ON_MOUSE_DOWN]&&g[ON_MOUSE_DOWN].call(f[ON_MOUSE_DOWN]);b.update()};this.setPosition=function(a,c){d.x=a;d.y=c};this.setX=function(a){d.x=a};this.setY=function(a){d.y=a};this.setScaleX=function(a){d.scaleX=a};this.setScaleY=function(a){d.scaleY=a};this.getButtonImage=function(){return d};
this.getX=function(){return d.x};this.getY=function(){return d.y};k=b;this._init(e,c,a);return this}
function CGame(e){var c=!1,a=!1,b=!1,g=!1,f=!1,d=!1,k=!1,h=!1,q=!1,l=!1,p=!1,m=!1,n=!1,r=!0,t=!1,v,u=0,K=0,O=0,Q=0,z,x,w,C,B,L=0,R,y,U,P,T,S,A,I,W,V,M,N,E,F,D,G,X,H,J,Y;this._init=function(a){W=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStageBg.addChild(W);z=PLAYER_HP;x=ENEMY_HP;w=PLAYER_STAMINA;C=PLAYER_KO;B=ENEMY_KO;0===s_iPlayerSelected?(M=createBitmap(s_oSpriteLibrary.getSprite("countdown_panel_white")),N=createBitmap(s_oSpriteLibrary.getSprite("countdown_panel_black")),E=createBitmap(s_oSpriteLibrary.getSprite("countdown_panel_continue_white")),
F=createBitmap(s_oSpriteLibrary.getSprite("countdown_panel_continue_black")),D=createBitmap(s_oSpriteLibrary.getSprite("ko_white")),G=createBitmap(s_oSpriteLibrary.getSprite("ko_black"))):(M=createBitmap(s_oSpriteLibrary.getSprite("countdown_panel_black")),N=createBitmap(s_oSpriteLibrary.getSprite("countdown_panel_white")),E=createBitmap(s_oSpriteLibrary.getSprite("countdown_panel_continue_black")),F=createBitmap(s_oSpriteLibrary.getSprite("countdown_panel_continue_white")),D=createBitmap(s_oSpriteLibrary.getSprite("ko_black")),
G=createBitmap(s_oSpriteLibrary.getSprite("ko_white")));M.regX=M.getBounds().width/2;M.regY=M.getBounds().height/2;M.x=CANVAS_WIDTH/2;M.y=CANVAS_HEIGHT/2;M.visible=!1;s_oStage.addChild(M);N.regX=N.getBounds().width/2;N.regY=N.getBounds().height/2;N.x=CANVAS_WIDTH/2;N.y=CANVAS_HEIGHT/2;N.visible=!1;s_oStage.addChild(N);E.alpha=.3;E.regX=E.getBounds().width/2;E.regY=E.getBounds().height/2;E.x=CANVAS_WIDTH/2-4;E.y=CANVAS_HEIGHT/2+4;E.visible=!1;s_oStage.addChild(E);F.alpha=.3;F.regX=F.getBounds().width/
2;F.regY=F.getBounds().height/2;F.x=CANVAS_WIDTH/2-4;F.y=CANVAS_HEIGHT/2+4;F.visible=!1;s_oStage.addChild(F);D.regX=D.getBounds().width/2;D.regY=D.getBounds().height/2;D.x=CANVAS_WIDTH/2;D.y=CANVAS_HEIGHT/2;D.visible=!1;s_oStage.addChild(D);G.regX=G.getBounds().width/2;G.regY=G.getBounds().height/2;G.x=CANVAS_WIDTH/2;G.y=CANVAS_HEIGHT/2;G.visible=!1;s_oStage.addChild(G);H=new createjs.BitmapText("1",s_oSpriteSheetBoxing);H.visible=!1;H.regX=H.getBounds().width/2;H.regY=H.getBounds().height/2;H.x=
CANVAS_WIDTH/2;H.y=200;s_oStage.addChild(H);J=new createjs.BitmapText("Prepare to fight!",s_oSpriteSheetBoxing);J.visible=!1;J.regX=J.getBounds().width/2;J.regY=J.getBounds().height/2;J.x=CANVAS_WIDTH/2;J.y=0;s_oStage.addChild(J);a&&(I=new CEnemy(CANVAS_WIDTH/2,1E3),A=new CPlayer(CANVAS_WIDTH/2,CANVAS_HEIGHT),h=!1);P=new CInterface;s_oInterface.setPlayerHp(z);s_oInterface.setPlayerStamina(w);s_oInterface.setEnemyHp(x);this.changePlayerState(IDLE);s_oStageBg.update();X=new CHelpPanel;if(!1===DISABLE_SOUND_MOBILE||
!1===s_bMobile)s_oSoundtrack.volume=.3;p=!0};this._preloadPW=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoadedPW,this);for(var a=0;a<s_aBw_Frame[IDLE];a++)s_oSpriteLibrary.addSprite("bw_idle_"+a,"./sprites/bw_idle/bw_idle_"+a+".png");for(a=0;a<s_aBw_Frame[GUARD];a++)s_oSpriteLibrary.addSprite("bw_guard_"+a,"./sprites/bw_guard/bw_guard_"+a+".png");for(a=0;a<s_aBw_Frame[JAB];a++)s_oSpriteLibrary.addSprite("bw_jab_"+a,"./sprites/bw_jab/bw_jab_"+a+".png");for(a=0;a<s_aBw_Frame[HOOK_R];a++)s_oSpriteLibrary.addSprite("bw_hook_r_"+
a,"./sprites/bw_hook_right/bw_hook_right_"+a+".png");for(a=0;a<s_aBw_Frame[HOOK_L];a++)s_oSpriteLibrary.addSprite("bw_hook_l_"+a,"./sprites/bw_hook_left/bw_hook_left_"+a+".png");for(a=0;a<s_aBw_Frame[UPPERCUT];a++)s_oSpriteLibrary.addSprite("bw_uppercut_"+a,"./sprites/bw_uppercut/bw_uppercut_"+a+".png");for(a=0;a<s_aBw_Frame[GETPUNCHED];a++)s_oSpriteLibrary.addSprite("bw_get_punched_"+a,"./sprites/bw_get_punched/bw_get_punched_"+a+".png");for(a=0;a<s_aBw_Frame[KO];a++)s_oSpriteLibrary.addSprite("bw_ko_"+
a,"./sprites/bw_ko/bw_ko_"+a+".png");for(a=0;a<s_aBb_En_Frame[IDLE];a++)s_oSpriteLibrary.addSprite("bb_en_idle_"+a,"./sprites/bb_en_idle/bb_en_idle_"+a+".png");for(a=0;a<s_aBb_En_Frame[GUARD];a++)s_oSpriteLibrary.addSprite("bb_en_guard_"+a,"./sprites/bb_en_guard/bb_en_guard_"+a+".png");for(a=0;a<s_aBb_En_Frame[JAB];a++)s_oSpriteLibrary.addSprite("bb_en_jab_"+a,"./sprites/bb_en_jab/bb_en_jab_"+a+".png");for(a=0;a<s_aBb_En_Frame[HOOK_R];a++)s_oSpriteLibrary.addSprite("bb_en_hook_r_"+a,"./sprites/bb_en_hook_right/bb_en_hook_right_"+
a+".png");for(a=0;a<s_aBb_En_Frame[HOOK_L];a++)s_oSpriteLibrary.addSprite("bb_en_hook_l_"+a,"./sprites/bb_en_hook_left/bb_en_hook_left_"+a+".png");for(a=0;a<s_aBb_En_Frame[UPPERCUT];a++)s_oSpriteLibrary.addSprite("bb_en_uppercut_"+a,"./sprites/bb_en_uppercut/bb_en_uppercut_"+a+".png");for(a=0;a<s_aBb_En_Frame[GETPUNCHED];a++)s_oSpriteLibrary.addSprite("bb_en_get_punched_"+a,"./sprites/bb_en_get_punched/bb_en_get_punched_"+a+".png");for(a=0;a<s_aBb_En_Frame[KO];a++)s_oSpriteLibrary.addSprite("bb_en_ko_"+
a,"./sprites/bb_en_ko/bb_en_ko_"+a+".png");s_oSpriteLibrary.loadSprites()};this._preloadPB=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoadedPB,this);for(var a=0;a<s_aBb_Frame[IDLE];a++)s_oSpriteLibrary.addSprite("bb_idle_"+a,"./sprites/bb_idle/bb_idle_"+a+".png");for(a=0;a<s_aBb_Frame[GUARD];a++)s_oSpriteLibrary.addSprite("bb_guard_"+a,"./sprites/bb_guard/bb_guard_"+a+".png");for(a=0;a<s_aBb_Frame[JAB];a++)s_oSpriteLibrary.addSprite("bb_jab_"+a,"./sprites/bb_jab/bb_jab_"+
a+".png");for(a=0;a<s_aBb_Frame[HOOK_R];a++)s_oSpriteLibrary.addSprite("bb_hook_r_"+a,"./sprites/bb_hook_right/bb_hook_right_"+a+".png");for(a=0;a<s_aBb_Frame[HOOK_L];a++)s_oSpriteLibrary.addSprite("bb_hook_l_"+a,"./sprites/bb_hook_left/bb_hook_left_"+a+".png");for(a=0;a<s_aBb_Frame[UPPERCUT];a++)s_oSpriteLibrary.addSprite("bb_uppercut_"+a,"./sprites/bb_uppercut/bb_uppercut_"+a+".png");for(a=0;a<s_aBb_Frame[GETPUNCHED];a++)s_oSpriteLibrary.addSprite("bb_get_punched_"+a,"./sprites/bb_get_punched/bb_get_punched_"+
a+".png");for(a=0;a<s_aBb_Frame[KO];a++)s_oSpriteLibrary.addSprite("bb_ko_"+a,"./sprites/bb_ko/bb_ko_"+a+".png");for(a=0;a<s_aBw_En_Frame[IDLE];a++)s_oSpriteLibrary.addSprite("bw_en_idle_"+a,"./sprites/bw_en_idle/bw_en_idle_"+a+".png");for(a=0;a<s_aBw_En_Frame[GUARD];a++)s_oSpriteLibrary.addSprite("bw_en_guard_"+a,"./sprites/bw_en_guard/bw_en_guard_"+a+".png");for(a=0;a<s_aBw_En_Frame[JAB];a++)s_oSpriteLibrary.addSprite("bw_en_jab_"+a,"./sprites/bw_en_jab/bw_en_jab_"+a+".png");for(a=0;a<s_aBw_En_Frame[HOOK_R];a++)s_oSpriteLibrary.addSprite("bw_en_hook_r_"+
a,"./sprites/bw_en_hook_right/bw_en_hook_right_"+a+".png");for(a=0;a<s_aBw_En_Frame[HOOK_L];a++)s_oSpriteLibrary.addSprite("bw_en_hook_l_"+a,"./sprites/bw_en_hook_left/bw_en_hook_left_"+a+".png");for(a=0;a<s_aBw_En_Frame[UPPERCUT];a++)s_oSpriteLibrary.addSprite("bw_en_uppercut_"+a,"./sprites/bw_en_uppercut/bw_en_uppercut_"+a+".png");for(a=0;a<s_aBw_En_Frame[GETPUNCHED];a++)s_oSpriteLibrary.addSprite("bw_en_get_punched_"+a,"./sprites/bw_en_get_punched/bw_en_get_punched_"+a+".png");for(a=0;a<s_aBw_En_Frame[KO];a++)s_oSpriteLibrary.addSprite("bw_en_ko_"+
a,"./sprites/bw_en_ko/bw_en_ko_"+a+".png");s_oSpriteLibrary.loadSprites()};this._onAllImagesLoadedPW=function(){s_bLoadedPlayerWhite=!0;I=new CEnemy(CANVAS_WIDTH/2,1E3);A=new CPlayer(CANVAS_WIDTH/2,CANVAS_HEIGHT);V.setIndex(A.getMaxIndex());m=!0};this._onAllImagesLoadedPB=function(){s_bLoadedPlayerBlack=!0;I=new CEnemy(CANVAS_WIDTH/2,1E3);A=new CPlayer(CANVAS_WIDTH/2,CANVAS_HEIGHT);V.setIndex(A.getMaxIndex());m=!0};this.onAllAnimPlayed=function(){1===L?(m=!1,V.unload(),this._init(!1),L=0):L++};this._onImagesLoaded=
function(){};this._initHammer=function(){S=new Hammer(document.getElementById("canvas"));S.get("swipe").set({direction:Hammer.DIRECTION_ALL});S.get("swipe").set({velocity:.005});S.get("swipe").set({threshold:.1});S.on("tap",function(a){w>=STAMINA_PUNCH_LIMIT&&!r&&(w<=s_aSt_Decrese[JAB]&&(d=!0),(1>s_oMultiplier?a.center.y/s_oMultiplier:a.center.y*s_oMultiplier)<U&&T._swipeControl("tap"))});S.on("swipeleft",function(a){w>=STAMINA_PUNCH_LIMIT&&!r&&(w<=s_aSt_Decrese[HOOK_R]&&(d=!0),(1>s_oMultiplier?a.center.y/
s_oMultiplier:a.center.y*s_oMultiplier)<U&&T._swipeControl("left"))});S.on("swiperight",function(a){w>=STAMINA_PUNCH_LIMIT&&!r&&(w<=s_aSt_Decrese[HOOK_L]&&(d=!0),(1>s_oMultiplier?a.center.y/s_oMultiplier:a.center.y*s_oMultiplier)<U&&T._swipeControl("right"))});S.on("swipeup",function(a){w>=STAMINA_PUNCH_LIMIT&&!r&&(w<=s_aSt_Decrese[UPPERCUT]&&(d=!0),(1>s_oMultiplier?a.center.y/s_oMultiplier:a.center.y*s_oMultiplier)<U&&T._swipeControl("up"))})};this._swipeControl=function(a){if(p)switch(a){case "left":k||
g||f||(h=k=!0,A.changeState("hook_r"),s_oInterface.setGuardButVisibilty(!1));break;case "right":k||g||f||(h=k=!0,A.changeState("hook_l"),s_oInterface.setGuardButVisibilty(!1));break;case "up":k||g||f||(h=k=!0,A.changeState("uppercut"),s_oInterface.setGuardButVisibilty(!1));break;case "tap":k||g||f||(h=k=!0,A.changeState("jab"),s_oInterface.setGuardButVisibilty(!1))}};this.unload=function(){s_oStage.removeAllChildren();s_oStageBg.removeAllChildren();s_oStageInterface.removeAllChildren();s_oStageBg.update();
s_oGame=null;$("#canvas_interface").css("display","none")};this.onExit=function(){this.unload();s_oMain.gotoMenu();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||Y.stop();$(s_oMain).trigger("restart")};this.onRestart=function(){this.unload();s_oMain.gotoGame()};this.changePlayerState=function(a){A.changeState(a)};this.setTapLimit=function(a){U=a};this.getPBlocked=function(){return k};this.setPBlocked=function(a){k=a};this.getPIsPunching=function(){return h};this.setPIsPunching=function(a){h=a};this.getPGuard=
function(){return q};this.setPGuard=function(a){q=a};this.setEGuard=function(a){l=a};this.getEGuard=function(){return l};this.hitEnemy=function(a){l?(--x,--B,I.moveGuard()):(I.changeState(GETPUNCHED),k=!0,d?(x-=a/2,B-=a/2):(x-=a,B-=a));s_oInterface.setEnemyHp(x);if(0>=x||1>=B)f=!0,I.changeState(KO),!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("crowd_exultance");d=!1};this.hitPlayer=function(a){q?(w-=3,--z,A.moveGuard()):(w-=5,z-=a,C=10>w?C-2*a:C-a,this.setPIsPunching(!1),A.changeState(GETPUNCHED),
k=!0);s_oInterface.setPlayerHp(z);if(0>=z||1>=C)s_oInterface.setGuardButVisibilty(!1),g=!0,A.changeState(KO),!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("crowd_exultance");s_oInterface.setPlayerStamina(w);d=!1};this.gamePause=function(){p=!1};this.gameResume=function(){p=!0};this.reduceStamina=function(a){w-=a;s_oInterface.setPlayerStamina(w)};this.regenStamina=function(){w+=1.5;s_oInterface.setPlayerStamina(w);c=!1};this.getKoP=function(){return g};this.getKoE=function(){return f};
this.regenKoP=function(){C+=1;a=!1};this.regenKoE=function(){B+=1;b=!1};this.playParticle=function(a,d){l||(n=!0,R=a,y=d)};this.stopParticle=function(){n=!1};this.playerKo=function(){this.gamePause();I.setVisible(!1);A.setVisible(!1);s_oInterface.setGuardButVisibilty(!1);s_oInterface.setEnergyVisibility(!1);t=M.visible=!0;z>=PLAYER_MIN_HP_KO?(v=Math.floor(8*Math.random()+3),C=z<=PLAYER_KO?z:PLAYER_KO):v=100};this.enemyKo=function(){this.gamePause();A.setVisible(!1);I.setVisible(!1);s_oInterface.setGuardButVisibilty(!1);
s_oInterface.setEnergyVisibility(!1);t=N.visible=!0;x>=ENEMY_MIN_HP_KO?(v=Math.floor(8*Math.random()+3),B=x<=ENEMY_KO?x:ENEMY_KO):v=100};this._wakeUp=function(){A.changeState(IDLE);I.changeState(IDLE);k=h=!1;M.visible=!1;N.visible=!1;E.visible=!1;F.visible=!1;s_oInterface.setGuardButVisibilty(!0);s_oInterface.setEnergyVisibility(!0);f=g=!1;I.setVisible(!0);I.setIsActing(!1);A.setVisible(!0);this.gameResume();H.visible=!1;u=0};this.closeHelpPanel=function(){X.unload();r=!1;if(!1===DISABLE_SOUND_MOBILE||
!1===s_bMobile)s_oSoundtrack.stop(),Y=createjs.Sound.play("crowd_idle",{loop:-1}),createjs.Sound.play("start_match");s_oGame._initHammer();$("#canvas_interface").css("display","block")};this.update=function(){m&&(A.playAllAnim(),I.playAllAnim());p&&!r&&(K+=s_iTimeElaps,K>STAMINA_REGEN_TIME&&!h&&100>w&&!c&&(K=0,c=!0,this.regenStamina()),O+=s_iTimeElaps,O>KO_REGEN_TIME&&(C<PLAYER_KO&&0<C&&!a&&(O=0,a=!0,this.regenKoP()),B<ENEMY_KO&0<C&&!b&&(O=0,b=!0,this.regenKoE())),A.update(),I.update(),n&&P.playParticle(R,
y));t&&(Q+=s_iTimeElaps,1E3<Q&&(Q=0,u+=1,10>=u?(H.visible=!0,H.text=""+u,u===v&&(t=!1,H.visible=!1,J.visible=!0,g?(E.visible=!0,createjs.Tween.get(E).to({alpha:1},500)):(F.visible=!0,createjs.Tween.get(F).to({alpha:1},500)),createjs.Tween.get(J).to({y:CANVAS_HEIGHT/2},300),setTimeout(function(){createjs.Tween.get(J).to({y:0},300).call(function(){T._wakeUp();J.visible=!0})},2E3)),(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)&&u!==v&&10>u&&createjs.Sound.play(""+u)):(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||
createjs.Sound.play("ko"),s_oInterface.setKoButVisibility(!0),t=!1,H.visible=!1,g?(D.scaleX=D.scaleY=3,D.alpha=.6,D.visible=!0,createjs.Tween.get(D).to({scaleX:1,scaleY:1,alpha:1},400,createjs.Ease.elasticOut).call(function(){})):(G.scaleX=D.scaleY=3,G.alpha=.6,G.visible=!0,createjs.Tween.get(G).to({scaleX:1,scaleY:1,alpha:1},400,createjs.Ease.elasticOut).call(function(){})))))};ENEMY_ATTACK_OCCURR=e.enemy_attack_occurr;ENEMY_MIN_ACTION_TIME=e.enemy_min_action_time;ENEMY_MAX_ACTION_TIME=e.enemy_max_action_time;
ENEMY_MIN_GUARD_TIME=e.enemy_min_guard_time;ENEMY_MAX_GUARD_TIME=e.enemy_max_guard_time;ENEMY_HP=e.enemy_hp;PLAYER_HP=e.player_hp;PLAYER_STAMINA=e.player_stamina;STAMINA_PUNCH_LIMIT=e.stamina_punch_limit;s_oGame=this;T=this;0===s_iPlayerSelected?s_bLoadedPlayerWhite?this._init(!0):(V=new CVersusPanel,this._preloadPW()):s_bLoadedPlayerBlack?this._init(!0):(V=new CVersusPanel,this._preloadPB())}var s_oEndPanel,s_oGame;
function CEnemy(e,c){var a=!1,b=1,g,f=0,d=1,k="idle",h,q,l,p,m,n,r,t,v,u,K=["jab","jab","hook_l","hook_r","uppercut"];this._init=function(a,d){h=new CContainer(a,d);if(0===s_iPlayerSelected){l=[];for(var c,b=0;b<s_aBb_En_Frame[IDLE];b++){c="bb_en_idle_"+b;c=s_oSpriteLibrary.getSprite(c);var e=createBitmap(c);l[b]=new CChild(0,0,e,h);l[b].setVisible(!1);l[b].setRegX(c.width/2);l[b].setRegY(c.height);h.addChild(l[b])}l[0].setVisible(!0);m=[];for(b=0;b<s_aBb_En_Frame[JAB];b++)c="bb_en_jab_"+b,c=s_oSpriteLibrary.getSprite(c),
e=createBitmap(c),m[b]=new CChild(0,0,e,h),m[b].setVisible(!1),m[b].setRegX(c.width/2+ANIMATION_OFFSET_ENEMY[JAB].xb),m[b].setRegY(c.height+ANIMATION_OFFSET_ENEMY[JAB].yb),h.addChild(m[b]);n=[];for(b=0;b<s_aBb_En_Frame[HOOK_R];b++)c="bb_en_hook_r_"+b,c=s_oSpriteLibrary.getSprite(c),e=createBitmap(c),n[b]=new CChild(0,0,e,h),n[b].setVisible(!1),n[b].setRegX(c.width/2+ANIMATION_OFFSET_ENEMY[HOOK_R].xb),n[b].setRegY(c.height),h.addChild(n[b]);r=[];for(b=0;b<s_aBb_En_Frame[HOOK_L];b++)c="bb_en_hook_l_"+
b,c=s_oSpriteLibrary.getSprite(c),e=createBitmap(c),r[b]=new CChild(0,0,e,h),r[b].setVisible(!1),r[b].setRegX(c.width/2+ANIMATION_OFFSET_ENEMY[HOOK_L].xb),r[b].setRegY(c.height),h.addChild(r[b]);t=[];for(b=0;b<s_aBb_En_Frame[UPPERCUT];b++)c="bb_en_uppercut_"+b,c=s_oSpriteLibrary.getSprite(c),e=createBitmap(c),t[b]=new CChild(0,0,e,h),t[b].setVisible(!1),t[b].setRegX(c.width/2+ANIMATION_OFFSET_ENEMY[UPPERCUT].xb),t[b].setRegY(c.height),h.addChild(t[b]);p=[];for(b=0;b<s_aBb_En_Frame[GUARD];b++)c="bb_en_guard_"+
b,c=s_oSpriteLibrary.getSprite(c),e=createBitmap(c),p[b]=new CChild(0,0,e,h),p[b].setVisible(!1),p[b].setRegX(c.width/2),p[b].setRegY(c.height),h.addChild(p[b]);v=[];for(b=0;b<s_aBb_En_Frame[GETPUNCHED];b++)c="bb_en_get_punched_"+b,c=s_oSpriteLibrary.getSprite(c),e=createBitmap(c),v[b]=new CChild(0,0,e,h),v[b].setVisible(!1),v[b].setRegX(c.width/2+ANIMATION_OFFSET_ENEMY[GETPUNCHED].xb),v[b].setRegY(c.height),h.addChild(v[b]);u=[];for(b=0;b<s_aBb_En_Frame[KO];b++)c="bb_en_ko_"+b,c=s_oSpriteLibrary.getSprite(c),
e=createBitmap(c),u[b]=new CChild(0,0,e,h),u[b].setVisible(!1),u[b].setRegX(c.width/2),u[b].setRegY(c.height),h.addChild(u[b])}else{l=[];for(b=0;b<s_aBw_En_Frame[IDLE];b++)c="bw_en_idle_"+b,c=s_oSpriteLibrary.getSprite(c),e=createBitmap(c),l[b]=new CChild(0,0,e,h),l[b].setVisible(!1),l[b].setRegX(c.width/2),l[b].setRegY(c.height),h.addChild(l[b]);l[0].setVisible(!0);m=[];for(b=0;b<s_aBw_En_Frame[JAB];b++)c="bw_en_jab_"+b,c=s_oSpriteLibrary.getSprite(c),e=createBitmap(c),m[b]=new CChild(0,0,e,h),m[b].setVisible(!1),
m[b].setRegX(c.width/2+ANIMATION_OFFSET_ENEMY[JAB].xb),m[b].setRegY(c.height+ANIMATION_OFFSET_ENEMY[JAB].yb),h.addChild(m[b]);n=[];for(b=0;b<s_aBw_En_Frame[HOOK_R];b++)c="bw_en_hook_r_"+b,c=s_oSpriteLibrary.getSprite(c),e=createBitmap(c),n[b]=new CChild(0,0,e,h),n[b].setVisible(!1),n[b].setRegX(c.width/2+ANIMATION_OFFSET_ENEMY[HOOK_R].xb),n[b].setRegY(c.height),h.addChild(n[b]);r=[];for(b=0;b<s_aBw_En_Frame[HOOK_L];b++)c="bw_en_hook_l_"+b,c=s_oSpriteLibrary.getSprite(c),e=createBitmap(c),r[b]=new CChild(0,
0,e,h),r[b].setVisible(!1),r[b].setRegX(c.width/2+ANIMATION_OFFSET_ENEMY[HOOK_L].xb),r[b].setRegY(c.height),h.addChild(r[b]);t=[];for(b=0;b<s_aBw_En_Frame[UPPERCUT];b++)c="bw_en_uppercut_"+b,c=s_oSpriteLibrary.getSprite(c),e=createBitmap(c),t[b]=new CChild(0,0,e,h),t[b].setVisible(!1),t[b].setRegX(c.width/2+ANIMATION_OFFSET_ENEMY[UPPERCUT].xb),t[b].setRegY(c.height),h.addChild(t[b]);p=[];for(b=0;b<s_aBw_En_Frame[GUARD];b++)c="bw_en_guard_"+b,c=s_oSpriteLibrary.getSprite(c),e=createBitmap(c),p[b]=
new CChild(0,0,e,h),p[b].setVisible(!1),p[b].setRegX(c.width/2),p[b].setRegY(c.height),h.addChild(p[b]);v=[];for(b=0;b<s_aBw_En_Frame[GETPUNCHED];b++)c="bw_en_get_punched_"+b,c=s_oSpriteLibrary.getSprite(c),e=createBitmap(c),v[b]=new CChild(0,0,e,h),v[b].setVisible(!1),v[b].setRegX(c.width/2+ANIMATION_OFFSET_ENEMY[GETPUNCHED].xb),v[b].setRegY(c.height),h.addChild(v[b]);u=[];for(b=0;b<s_aBw_En_Frame[KO];b++)c="bw_en_ko_"+b,c=s_oSpriteLibrary.getSprite(c),e=createBitmap(c),u[b]=new CChild(0,0,e,h),
u[b].setVisible(!1),u[b].setRegX(c.width/2),u[b].setRegY(c.height),h.addChild(u[b])}g=ENEMY_MAX_ACTION_TIME};this._animIdle=function(){0===d?(l[8].setVisible(!1),l[0].setVisible(!0)):(l[d-1].setVisible(!1),l[d].setVisible(!0));d++;d>s_aBb_En_Frame[IDLE]-1&&(d=0)};this._animGuard=function(){0===d?(p[9].setVisible(!1),p[0].setVisible(!0)):(p[d-1].setVisible(!1),p[d].setVisible(!0));d++;d>s_aBb_En_Frame[GUARD]-1&&(d=0)};this._animJab=function(){0===d?m[0].setVisible(!0):(m[d-1].setVisible(!1),m[d].setVisible(!0));
d===s_aFrameHit[JAB]&&(this._onJabHit(),!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||!1!==s_oGame.getPGuard()||createjs.Sound.play("punch_left"));d++;d>s_aBb_En_Frame[JAB]-1&&(l[0].setVisible(!0),a=!1,this.changeState("idle"))};this._animHookR=function(){0===d?n[0].setVisible(!0):(n[d-1].setVisible(!1),n[d].setVisible(!0));d===s_aFrameHit[HOOK_R]&&(this._onHookRHit(),!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||!1!==s_oGame.getPGuard()||createjs.Sound.play("punch_right"));d++;d>s_aBb_En_Frame[HOOK_R]-
1&&(l[0].setVisible(!0),a=!1,this.changeState("idle"))};this._animHookL=function(){0===d?r[0].setVisible(!0):(r[d-1].setVisible(!1),r[d].setVisible(!0));d===s_aFrameHit[HOOK_L]&&(this._onHookLHit(),!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||!1!==s_oGame.getPGuard()||createjs.Sound.play("punch_left"));d++;d>s_aBb_En_Frame[HOOK_L]-1&&(l[0].setVisible(!0),a=!1,this.changeState("idle"))};this._animUppercut=function(){0===d?t[0].setVisible(!0):(t[d-1].setVisible(!1),t[d].setVisible(!0));d===s_aFrameHit[UPPERCUT]&&
(this._onUppercutHit(),!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||!1!==s_oGame.getPGuard()||createjs.Sound.play("uppercut"));d++;d>s_aBb_En_Frame[UPPERCUT]-1&&(l[0].setVisible(!0),a=!1,this.changeState("idle"))};this._animGetPunched=function(){0===d?(a=!0,v[0].setVisible(!0)):(v[d-1].setVisible(!1),v[d].setVisible(!0));d++;d>s_aBb_En_Frame[GETPUNCHED]-1&&(a=!1,l[0].setVisible(!0),this.changeState("idle"))};this._animKo=function(){0===d?(a=!0,u[0].setVisible(!0)):(u[d-1].setVisible(!1),u[d].setVisible(!0));
11===d&&(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("falling"));d++;d>s_aBb_En_Frame[KO]-1&&s_oGame.enemyKo()};this._onJabHit=function(){s_oGame.hitPlayer(s_aDamage[JAB])};this._onHookRHit=function(){s_oGame.hitPlayer(s_aDamage[HOOK_R])};this._onHookLHit=function(){s_oGame.hitPlayer(s_aDamage[HOOK_L])};this._onUppercutHit=function(){s_oGame.hitPlayer(s_aDamage[UPPERCUT])};this.changeState=function(a){"get_punched"===a&&v[0].setVisible(!0);"ko"===a&&u[0].setVisible(!0);switch(k){case IDLE:for(var c=
0;c<s_aBb_En_Frame[IDLE];c++)l[c].setVisible(!1);b=1;break;case GUARD:for(c=0;c<s_aBb_En_Frame[GUARD];c++)p[c].setVisible(!1);b=1;break;case JAB:for(c=0;c<s_aBb_En_Frame[JAB];c++)m[c].setVisible(!1);b=1;break;case HOOK_R:for(c=0;c<s_aBb_En_Frame[HOOK_R];c++)n[c].setVisible(!1);b=1;break;case HOOK_L:for(c=0;c<s_aBb_En_Frame[HOOK_L];c++)r[c].setVisible(!1);b=1;break;case UPPERCUT:for(c=0;c<s_aBb_En_Frame[UPPERCUT];c++)t[c].setVisible(!1);b=1;break;case GETPUNCHED:for(c=0;c<s_aBb_En_Frame[GETPUNCHED];c++)v[c].setVisible(!1);
b=1;break;case KO:for(c=0;c<s_aBb_En_Frame[KO];c++)u[c].setVisible(!1);b=1}k=a;d=0};this._init(e,c);this.moveGuard=function(){h.setTween({y:h.getY()+30},100,function(){h.setTween({y:h.getY()-30},100)})};this._action=function(){if(Math.floor(100*Math.random()+1)>ENEMY_ATTACK_OCCURR)this.changeState("guard"),s_oGame.setEGuard(!0),this._guardRelease();else{var a=Math.floor(5*Math.random()+0);this.changeState(K[a])}};this._guardRelease=function(){var b=Math.floor(Math.random()*ENEMY_MAX_GUARD_TIME+ENEMY_MIN_GUARD_TIME);
setTimeout(function(){null===s_oGame||s_oGame.getKoE()||(q.changeState("idle"),a=!1,s_oGame.setEGuard(!1))},b)};this.setVisible=function(a){h.setVisible(a)};this.setIsActing=function(b){a=b};this.playAllAnim=function(){switch(k){case IDLE:d<s_aBb_En_Frame[IDLE]-1?(0===d?l[0].setVisible(!0):(l[d-1].setVisible(!1),l[d].setVisible(!0)),d++):(d=0,this.changeState(GUARD));break;case GUARD:d<s_aBb_En_Frame[GUARD]-1?(0===d?p[0].setVisible(!0):(p[d-1].setVisible(!1),p[d].setVisible(!0)),d++):(d=0,this.changeState(JAB));
break;case JAB:d<s_aBb_En_Frame[JAB]-1?(0===d?m[0].setVisible(!0):(m[d-1].setVisible(!1),m[d].setVisible(!0)),d++):(d=0,this.changeState(HOOK_R));break;case HOOK_R:d<s_aBb_En_Frame[HOOK_R]-1?(0===d?n[0].setVisible(!0):(n[d-1].setVisible(!1),n[d].setVisible(!0)),d++):(d=0,this.changeState(HOOK_L));break;case HOOK_L:d<s_aBb_En_Frame[HOOK_L]-1?(0===d?r[0].setVisible(!0):(r[d-1].setVisible(!1),r[d].setVisible(!0)),d++):(d=0,this.changeState(UPPERCUT));break;case UPPERCUT:d<s_aBb_En_Frame[UPPERCUT]-1?
(0===d?t[0].setVisible(!0):(t[d-1].setVisible(!1),t[d].setVisible(!0)),d++):(d=0,this.changeState(GETPUNCHED));break;case GETPUNCHED:d<s_aBb_En_Frame[GETPUNCHED]-1?(0===d?v[0].setVisible(!0):(v[d-1].setVisible(!1),v[d].setVisible(!0)),d++):(d=0,this.changeState(KO));break;case KO:d<s_aBb_En_Frame[KO]-1?(0===d?u[0].setVisible(!0):(u[d-1].setVisible(!1),u[d].setVisible(!0)),d++):(s_oGame.onAllAnimPlayed(),this.changeState(IDLE))}};this.update=function(){a||(f+=s_iTimeElaps);f>g&&!a&&!s_oGame.getKoP()&&
!s_oGame.getKoE()&&(f=0,a=!0,g=Math.random()*(ENEMY_MAX_ACTION_TIME-ENEMY_MIN_ACTION_TIME)+ENEMY_MIN_ACTION_TIME,this._action());switch(k){case IDLE:b!==IDLE_DELAY||s_oGame.getKoP()?b++:(b=0,this._animIdle());break;case GUARD:b!==IDLE_DELAY||s_oGame.getKoP()?b++:(b=0,this._animGuard());break;case JAB:b!==IDLE_DELAY||s_oGame.getKoP()?b++:(b=0,this._animJab());break;case HOOK_R:b!==IDLE_DELAY||s_oGame.getKoP()?b++:(b=0,this._animHookR());break;case HOOK_L:b!==IDLE_DELAY||s_oGame.getKoP()?b++:(b=0,this._animHookL());
break;case UPPERCUT:b!==IDLE_DELAY||s_oGame.getKoP()?b++:(b=0,this._animUppercut());break;case GETPUNCHED:b!==IDLE_DELAY||s_oGame.getKoP()?b++:(b=0,this._animGetPunched());break;case KO:b===IDLE_DELAY?(b=0,this._animKo()):b++}q=this}}
function CContainer(e,c){var a=!0,b=0,g=0,f=0,d=1,k=1,h=1,q,l;this._init=function(a,c){b=a;g=c;l=[]};this.addChild=function(){for(var a=0;a<arguments.length;a++)s_oStage.addChild(arguments[a].getChild()),l.push(arguments[a]),arguments[a].setAllParameter(this)};this.removeChild=function(){for(var a=0;a<arguments.length;a++)for(var b=0;b<l.length;b++)arguments[a]===l[b]&&(l.splice(1,b),s_oStage.removeChild(arguments[a].getChild()))};this.removeAllChildren=function(){for(var a=0;a<l.length;a++)s_oStage.removeChild(l[a].getChild())};
this.setX=function(a){b=a;for(a=0;a<l.length;a++)l[a].getChild().x=l[a].getX()+b};this.getX=function(){return b};this.setY=function(a){g=a;for(a=0;a<l.length;a++)l[a].getChild().y=l[a].getY()+g};this.getY=function(){return g};this.setScaleX=function(a){d=a;for(a=0;a<l.length;a++){var c=l[a].getChild().regX,e=l[a].getChild().x-b;l[a].setRegX(e);l[a].getChild().scaleX=l[a].getScaleX()*d;l[a].setRegX(c)}};this.getScaleX=function(){return d};this.setScaleY=function(a){k=a;for(a=0;a<l.length;a++)l[a].getChild().scaleY=
l[a].getScaleY()*k};this.getScaleY=function(){return k};this.setAlpha=function(a){h=a;for(a=0;a<l.length;a++)l[a].getChild().alpha=l[a].getAlpha()*h};this.getAlpha=function(){return h};this.setVisible=function(b){a=b;for(b=0;b<l.length;b++)l[b].getChild().visible=l[b].getVisible()&&a};this.getVisible=function(){return a};this.setTween=function(a,c,e){for(var f=0;f<l.length;f++){for(var t=a,v=Object.keys(t).length,u=0;u<v;u++)switch(Object.keys(t)[u]){case "x":b=a.x;t.x+=l[f].getX();break;case "y":g=
a.y;t.y+=l[f].getY();break;case "scaleX":d=a.scaleX;t.scaleX*=l[f].getScaleX();break;case "scaleY":k=a.scaleY;t.scaleY*=l[f].getScaleY();break;case "alpha":h=a.alpha,t.alpha*=l[f].getAlpha()}createjs.Tween.get(l[f].getChild()).to(t,c).call(function(){"function"===typeof e&&q._onTweenFinish(e)})}};this._onTweenFinish=function(a){f++;f===l.length&&(f=0,a())};this._testTween=function(){for(var a=0;a<l.length;a++){var c=b-l[a].getChild().x;l[a].setRegX(c);l[1].setX(75);createjs.Tween.get(l[a].getChild()).to({scaleX:.5},
3E3)}};q=this;this._init(e,c)}
function CChild(e,c,a,b){var g=!0,f,d,k,h,q,l,p,m,n;this._init=function(a,b,c,e){g=!0;f=a;d=b;h=k=0;p=l=q=1;m=c;n=e;"undefined"!==typeof n?(m.x=n.getX()+f,m.y=n.getY()+d,m.scaleX=n.getScaleX()*q,m.scaleY=n.getScaleY()*l,n.addChild(this)):(m.x=f,m.y=d)};this.setAllParameter=function(a){n=a;m.x=n.getX()+f;m.y=n.getY()+d;m.scaleX=n.getScaleX()*q;m.scaleY=n.getScaleY()*l;m.regX=k;m.regY=h;m.alpha=p;m.visible=g};this.setX=function(a){f=a;m.x="undefined"!==typeof n?n.getX()+f:f};this.getX=function(){return f};
this.setY=function(a){d=a;m.y="undefined"!==typeof n?n.getY()+d:d};this.getY=function(){return d};this.setRegX=function(a){k=a;m.regX=k};this.getRegX=function(){return k};this.setRegY=function(a){h=a;m.regY=h};this.getRegY=function(){return h};this.setScaleX=function(a){q=a;m.scaleX="undefined"!==typeof n?n.getScaleX()*q:q};this.getScaleX=function(){return q};this.setScaleY=function(a){l=a;m.scaleY="undefined"!==typeof n?n.getScaleY()*l:l};this.getScaleY=function(){return l};this.setAlpha=function(a){p=
a;m.alpha="undefined"!==typeof n?n.getAlpha()*p:p};this.getAlpha=function(){return p};this.setVisible=function(a){g=a;m.visible="undefined"!==typeof n?n.getVisible&&g:g};this.getVisible=function(){return g};this.getChild=function(){return m};this._init(e,c,a,b)}
function CBitmapFont(){this._init=function(){s_oSpriteSheetBoxing=new createjs.SpriteSheet({images:["./sprites/boxer_font.png"],frames:[[203,100,7,5,0,-3,79],[142,206,13,49,0,0,14],[376,196,23,22,0,0,9],[349,0,45,49,0,-1,14],[0,0,29,59,0,0,9],[211,0,44,50,0,0,13],[275,197,38,38,0,2,19],[413,196,12,22,0,0,9],[29,0,19,59,0,0,9],[48,0,19,59,0,-1,9],[313,196,29,28,0,0,13],[237,198,38,38,0,2,19],[399,196,14,22,0,0,49],[455,196,17,11,0,0,33],[425,196,14,14,0,-1,-20],[67,0,18,59,0,0,9],[90,157,30,49,0,0,
14],[489,98,20,49,0,0,14],[406,147,28,49,0,0,14],[330,49,31,49,0,0,14],[105,59,33,49,0,0,14],[178,155,29,49,0,0,14],[350,147,28,49,0,0,14],[279,98,30,49,0,0,14],[309,98,30,49,0,0,14],[236,149,29,49,0,0,14],[223,204,14,43,0,-1,20],[197,0,14,51,0,0,20],[189,204,34,47,0,0,18],[342,196,34,24,0,0,27],[155,206,34,47,0,0,18],[322,147,28,49,0,0,14],[394,0,44,49,0,-1,14],[339,98,30,49,0,0,14],[0,108,31,49,0,0,14],[93,108,31,49,0,0,14],[124,108,31,49,0,0,14],[434,147,27,49,0,-1,14],[79,206,25,49,0,0,14],[217,
100,31,49,0,-1,14],[369,98,30,49,0,0,14],[488,147,20,49,0,-1,14],[461,147,27,49,0,0,14],[267,49,32,49,0,0,14],[53,206,26,49,0,0,14],[438,0,38,49,0,0,14],[423,49,31,49,0,0,14],[429,98,30,49,0,0,14],[149,157,29,49,0,0,14],[135,0,31,57,0,0,14],[459,98,30,49,0,0,14],[120,157,29,49,0,0,14],[171,57,32,49,0,-1,14],[186,106,31,49,0,0,14],[155,106,31,49,0,0,14],[302,0,47,49,0,0,14],[38,59,34,49,0,0,14],[138,57,33,49,0,0,14],[378,147,28,49,0,0,14],[103,0,16,59,0,0,9],[85,0,18,59,0,0,9],[119,0,16,59,0,0,9],
[472,196,34,10,0,0,63],[439,196,16,13,0,1,2],[0,157,30,49,0,0,14],[248,99,31,49,0,0,14],[454,49,31,49,0,0,14],[361,49,31,49,0,0,14],[485,49,27,49,0,-1,14],[104,206,25,49,0,0,14],[392,49,31,49,0,-1,14],[30,157,30,49,0,0,14],[129,206,13,49,0,0,14],[0,206,27,49,0,0,14],[203,51,32,49,0,0,14],[27,206,26,49,0,0,14],[0,59,38,49,0,0,14],[31,108,31,49,0,0,14],[399,98,30,49,0,0,14],[207,155,29,49,0,0,14],[166,0,31,57,0,0,14],[60,157,30,49,0,0,14],[265,148,29,49,0,0,14],[235,50,32,49,0,-1,14],[62,108,31,49,
0,0,14],[299,49,31,49,0,0,14],[255,0,47,49,0,0,14],[476,0,34,49,0,0,14],[72,59,33,49,0,0,14],[294,147,28,49,0,0,14]],animations:{" ":0,"!":1,'"':2,"#":3,$:4,"%":5,"\u20ac":6,"'":7,"(":8,")":9,"*":10,"+":11,",":12,"-":13,".":14,"/":15,0:16,1:17,2:18,3:19,4:20,5:21,6:22,7:23,8:24,9:25,":":26,";":27,"<":28,"=":29,">":30,"?":31,"@":32,A:33,B:34,C:35,D:36,E:37,F:38,G:39,H:40,I:41,J:42,K:43,L:44,M:45,N:46,O:47,P:48,Q:49,R:50,S:51,T:52,U:53,V:54,W:55,X:56,Y:57,Z:58,"[":59,"/":60,"]":61,_:62,"\u00ec":63,
a:64,b:65,c:66,d:67,e:68,f:69,g:70,h:71,i:72,j:73,k:74,l:75,m:76,n:77,o:78,p:79,q:80,r:81,s:82,t:83,u:84,v:85,w:86,x:87,y:88,z:89}})};this._init()}var s_oSpriteSheetBoxing;