TEXT_GAMEOVER="YOU WIN";TEXT_PLAY="PLAY";TEXT_STATS="STATS";TEXT_RESTART="RESTART";TEXT_MORE="More Games";TEXT_HOW="HOW TO PLAY";TEXT_HELP1="You do all the work in the office while the boss is busy flirting with his personal assistant! Get your revenge by \u201cspicing up\u201d his coffee. Click anywhere on the screen to add things to his coffee cup.";TEXT_HELP2="Keep clicking to put some even nastier stuff in his cup! But watch out! If the boss notices, you will be fired!";TEXT_START="START";
TEXT_FIRED="YOU ARE FIRED!";TEXT_TIMEOUT="WHAT ARE YOU DOING?!";TEXT_WIN="YOU WIN!";TEXT_INSERTNAME="INSERT YOUR NAME";TEXT_SUBMIT="SUBMIT";TEXT_RESTART="RESTART";TEXT_HIGH="HIGH SCORES";TEXT_RANKING="RANKING";TEXT_NAME="NAME";TEXT_SCORE="SCORE";TEXT_MENU="MENU";
function CLady(a,e){var c,g,b,f,l,k,h,m,d,n,p,q,w,z,t,u;this._init=function(a,e){g=c=!1;f=0;l=[];l=[this.shine,this.shine,this.shine,this.shine,this.turn,this.checkCopy,this.stand,this.laugh,this.checkCopy,this.checkCopy];k=new createjs.Container;k.x=a;k.y=e;s_oStage.addChild(k);var b=s_oSpriteLibrary.getSprite("secretary_afraid"),b={images:[b],frames:{width:187,height:315},animations:{idle:[0,0,"idle1",.2],idle1:[1,1,"stop",1/77]}},b=new createjs.SpriteSheet(b);m=new createjs.Sprite(b,"idle");m.visible=
!1;m.gotoAndStop("idle");k.addChild(m);b=s_oSpriteLibrary.getSprite("secretary_check_copy");b={images:[b],frames:{width:187,height:315},animations:{idle:[0,0,"idle1",.0625],idle1:[1,1,"idle2",1/6],idle2:[2,2,"idle3",.2],idle3:[3,3,"idle4",1/33],idle4:[4,4,"idle5",.25],idle5:[5,5,"idle6",.25],idle6:[6,6,"idle7",.25],idle7:[7,7,"idle8",.25],idle8:[0,0,"stop",1/19]}};b=new createjs.SpriteSheet(b);d=new createjs.Sprite(b,"idle");d.on("animationend",this._onCheckCopy);d.visible=!1;d.gotoAndStop("idle");
k.addChild(d);b=s_oSpriteLibrary.getSprite("secretary_laugh");b={images:[b],frames:{width:187,height:315},animations:{idle:[0,0,"idle1",.25],idle1:[1,1,"idle2",1/3],idle2:[2,2,"idle3",.25],idle3:[1,1,"idle4",1/3],idle4:[2,2,"idle5",.25],idle5:[1,1,"idle6",1/3],idle6:[2,2,"idle",1/22]}};b=new createjs.SpriteSheet(b);n=new createjs.Sprite(b,"idle");n.visible=!1;n.gotoAndStop("idle");k.addChild(n);b=s_oSpriteLibrary.getSprite("secretary_look_boss");b={images:[b],frames:{width:187,height:315},animations:{idle:[0,
0,"stop"]}};b=new createjs.SpriteSheet(b);p=new createjs.Sprite(b,"idle");p.visible=!1;p.gotoAndStop("idle");k.addChild(p);b=s_oSpriteLibrary.getSprite("secretary_shine");b={images:[b],frames:{width:187,height:315},animations:{idle:[0,0,"idle1",1/14],idle1:[1,1,"idle2",.5],idle2:[2,2,"idle3",.2],idle3:[3,3,"idle",1/49]}};b=new createjs.SpriteSheet(b);q=new createjs.Sprite(b,"idle");q.visible=!1;q.gotoAndStop("idle");k.addChild(q);b=s_oSpriteLibrary.getSprite("secretary_stand");b={images:[b],frames:{width:187,
height:315},animations:{idle:[0,0,"stop",54]}};b=new createjs.SpriteSheet(b);w=new createjs.Sprite(b,"idle");w.visible=!1;w.gotoAndStop("idle");k.addChild(w);b=s_oSpriteLibrary.getSprite("secretary_talk");b={images:[b],frames:{width:187,height:315},animations:{idle:[0,0,"idle1",1/14],idle1:[1,1,"idle2",.5],idle2:[2,2,"idle3",.2],idle3:[3,3,"idle4",1/48],idle4:[4,4,"idle5",1/14],idle5:[5,5,"idle6",.5],idle6:[6,6,"idle7",.2],idle7:[7,7,"idle8",1/48],idle8:[8,8,"idle9",1/14],idle9:[9,9,"idle10",.5],
idle10:[10,10,"idle11",.2],idle11:[11,11,"idle12",1/48],idle12:[0,0,"idle",1/14]}};b=new createjs.SpriteSheet(b);z=new createjs.Sprite(b,"idle");z.visible=!1;z.gotoAndStop("idle");k.addChild(z);b=s_oSpriteLibrary.getSprite("secretary_turn_around");b={images:[b],frames:{width:187,height:315},animations:{idle:[0,0,"idle1",.03125],idle1:[1,1,"idle2",.1],idle2:[2,2,"stop",1/11]}};b=new createjs.SpriteSheet(b);t=new createjs.Sprite(b,"idle");t.visible=!1;t.on("animationend",this._onTurn);t.gotoAndStop("idle");
k.addChild(t);h=w;h.visible=!0};this.active=function(){this.getRandomActions()};this.unload=function(){t.off("animationend",this._onTurn);d.off("animationend",this._onCheckCopy);s_oStage.removeChild(k)};this.getRandomActions=function(){h.stop();l[Math.floor(Math.random()*l.length)]()};this.resetState=function(){f=-1};this.afraid=function(){h.visible=!1;f=9;h=m;h.visible=!0;h.gotoAndPlay("idle")};this.checkCopy=function(){s_oGame.checkCopy()?(h.visible=!1,h=d,h.visible=!0,h.gotoAndPlay("idle"),s_oGame.clearCopy(),
f=4):u.resetState()};this.laugh=function(){h.visible=!1;h=n;h.visible=!0;h.gotoAndPlay("idle");f=3;u.setDelay(u.resetState,5,2)};this.look=function(){h.visible=!1;f=8;h=p;h.visible=!0;h.gotoAndPlay("idle");u.setDelay(u.resetState,3,1)};this.shine=function(){h.visible=!1;h=q;h.visible=!0;h.gotoAndPlay("idle");f=0;u.setDelay(u.resetState,5,2)};this.stand=function(){h.visible=!1;h=w;h.visible=!0;h.gotoAndPlay("idle");f=7;u.setDelay(u.resetState,4,2)};this.talk=function(){h.visible=!1;h=z;h.visible=!0;
h.gotoAndPlay("idle");f=2;u.setDelay(u.resetState,5,3)};this.turn=function(){h.visible=!1;h=t;h.visible=!0;h.gotoAndPlay("idle");f=1};this.checkPP=function(){return 5===f&&g};this.update=function(){this.checkGetCopy()||(c&&9!==f?this.afraid():-1===f&&this.getRandomActions())};this.onDied=function(){c=!0;u.clearTimer();u.checkGetCopy()||u.afraid()};this.checkGetCopy=function(){return 4===f||5===f||6===f};this.checkState=function(){return 3===f||2===f||8===f};this._onCheckCopy=function(){"idle"===h.currentAnimation?
(f=5,g=.6<Math.random()?!0:!1):"idle3"===h.currentAnimation?!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("sd_get"):"idle7"===h.currentAnimation?f=6:"idle8"===h.currentAnimation&&u.resetState()};this._onTurn=function(){2===h.currentFrame&&u.resetState()};this.setDelay=function(a,d,c){d*=Math.random();d<=c&&(d=c);b=setTimeout(a,1E3*d)};this.clearTimer=function(){clearTimeout(b)};u=this;this._init(a,e)}
function CInterface(){var a,e,c,g,b,f,l,k,h,m,d,n,p,q,w,z,t,u,r,y,A,B,D,C,F,E;this._init=function(){e=a=0;c=9;l=new createjs.Container;l.x=55;l.y=41;s_oStage.addChild(l);var v=s_oSpriteLibrary.getSprite("timer");g=createBitmap(v);g.regX=v.width/2;g.regY=v.height/2;l.addChild(g);v=s_oSpriteLibrary.getSprite("hour");b=createBitmap(v);b.regX=v.width/2;b.regY=v.height;b.rotation=-90;l.addChild(b);v=s_oSpriteLibrary.getSprite("minute");f=createBitmap(v);f.regX=v.width/2;f.regY=v.height;l.addChild(f);k=
new createjs.Container;k.x=105;k.y=15;s_oStage.addChild(k);v=s_oSpriteLibrary.getSprite("life_bar");w=createBitmap(v);k.addChild(w);v=s_oSpriteLibrary.getSprite("life_bar_mask");n=createBitmap(v);n.x=7;n.y=5;n.alpha=.75;k.addChild(n);p=new createjs.Shape;p.graphics.beginFill("rgba(255,0,0,0.01)").drawRect(0,0,v.width,v.height);p.x=7;p.y=5;k.addChild(p);n.mask=p;v=s_oSpriteLibrary.getSprite("life_bar_mask");m=createBitmap(v);m.x=7;m.y=5;k.addChild(m);q=new createjs.Shape;q.graphics.beginFill("rgba(160,160,160,0.01)").drawRect(0,
0,v.width,v.height);q.x=7;q.y=5;k.addChild(q);m.mask=q;v=s_oSpriteLibrary.getSprite("life_glass");d=createBitmap(v);d.x=7;d.y=5;k.addChild(d);h=new createjs.Container;h.x=115;h.y=45;s_oStage.addChild(h);v=s_oSpriteLibrary.getSprite("coffee_bar");z=createBitmap(v);h.addChild(z);v=s_oSpriteLibrary.getSprite("highlight");t=createBitmap(v);t.x=35;t.y=0;t.alpha=a;h.addChild(t);v=s_oSpriteLibrary.getSprite("coffee_bar_energy");u=createBitmap(v);u.x=41;u.y=5;h.addChild(u);r=new createjs.Shape;r.graphics.beginFill("rgba(160,160,160,0.01)").drawRect(0,
0,v.width,v.height);r.x=41;r.y=5;r.scaleX=0;h.addChild(r);u.mask=r;v=s_oSpriteLibrary.getSprite("coffee_glass");y=createBitmap(v);y.x=41;y.y=5;h.addChild(y);B=new CFormatText(400,57,"0","#66CCFF",s_oStage,"#3C0064",18,"#660099");D=new createjs.Text("","bold 18px Arial Black","yellow");D.x=320;D.y=65;D.textAlign="left";D.textBaseline="alphabetic";D.shadow=new createjs.Shadow("#505050",4,4,5);D.lineWidth=200;s_oStage.addChild(D);C=new CFormatText(565,27,"0","#FFCC33",s_oStage,"#5E0000",22,"#663300");
F=new CFormatText(565,58,"0","#CCCCCC",s_oStage,"#000000",16);v=s_oSpriteLibrary.getSprite("explode");v=new createjs.SpriteSheet({images:[v],frames:{width:128,height:100},animations:{idle:[0,0,"idle1",.5],idle1:[1,1,"idle2",.5],idle2:[2,2,"idle3",.5],idle3:[3,3,"idle4",.5],idle4:[4,4,"stop",.5]}});E=new createjs.Sprite(v,"idle");E.visible=!1;E.on("animationend",this._onExplosionEnd);E.x=500;E.y=-10;E.gotoAndStop("idle");s_oStage.addChild(E)};this.unload=function(){E.off("animationend",this._onExplosionEnd)};
this._onExplosionEnd=function(){"idle4"===E.currentAnimation&&(E.visible=!1)};this.bestScoreVisible=function(){return F.isVisible()};this.refreshScore=function(a){B.setText(a);createjs.Tween.get(B.getText()).to({scaleX:1.2,scaleY:1.2},75,createjs.Ease.cubicOut).to({scaleX:1,scaleY:1},75,createjs.Ease.cubicIn)};this.refreshMultiplier=function(a){D.text=1<a?"x "+a:""};this.refreshCurScore=function(a,d){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("sd_Score");createjs.Tween.get(B.getText()).to({x:C.getPos().x},
300,createjs.Ease.linear).call(function(){B.setText("0");B.getText().x=400;C.setText(a);d&&(E.visible=!0,E.gotoAndPlay("idle"),F.setVisible(!1),C.setPos(42));createjs.Tween.get(B.getText()).to({scaleX:1.5,scaleY:1.5},300,createjs.Ease.linear).to({scaleX:1,scaleY:1},300,createjs.Ease.linear)})};this.refreshBestScore=function(a){F.setText(a)};this.refreshLifeOnTime=function(a){q.scaleX=a;p.scaleX=a};this.refreshLife=function(a){createjs.Tween.get(q).to({scaleX:a},1E3,createjs.Ease.cubicOut);createjs.Tween.get(n).to({alpha:0},
2E3,createjs.Ease.cubicOut).call(function(){p.scaleX=a;n.alpha=.75;s_oGame.resumeUpdateLife()})};this.refreshCoffeBar=function(a){1===a?(r.scaleX=1,createjs.Tween.removeTweens(r)):createjs.Tween.get(r,{override:!0}).to({scaleX:a},150,createjs.Ease.cubicOut).to({scaleX:a-.05},4E3,createjs.Ease.cubicOut)};this.flicker=function(){1===a?(a=0,createjs.Tween.get(t).to({alpha:a},0,createjs.Ease.cubicOut).call(function(){A.flicker()})):(a=1,createjs.Tween.get(t).to({alpha:a},400,createjs.Ease.cubicIn).call(function(){A.flicker()}))};
this.clearCoffeeBar=function(){createjs.Tween.get(r,{override:!0}).to({scaleX:0},150,createjs.Ease.cubicOut);createjs.Tween.removeTweens(t);t.alpha=0};this.rotateClock=function(){e+=.5;f.rotation=e;b.rotation=30*(c+Math.floor(e/360))+e%360/12;if(e>360*c)s_oGame.onTimeExpired()};this.getHour=function(){return b.rotation};this._onButRestartRelease=function(){s_oGame.restartGame()};s_oInterface=this;A=this;this._init();return this}var s_oInterface=null;
function CHelpPanel(){var a,e,c,g,b,f,l,k,h;this._init=function(){var h=s_bMobile?s_oSpriteLibrary.getSprite("bg_help_mob"):s_oSpriteLibrary.getSprite("bg_help");l=createBitmap(h);l.regX=h.width/2;l.regY=h.height/2;l.x=CANVAS_WIDTH/2;l.y=CANVAS_HEIGHT/2;var h=CANVAS_WIDTH/2-100,d=CANVAS_HEIGHT/2-95;c=new createjs.Text(TEXT_HELP1," 14px Arial Black","#A01F89");c.x=h;c.y=d;c.textAlign="left";c.textBaseline="alphabetic";c.lineWidth=350;h=CANVAS_WIDTH/2-223;d=CANVAS_HEIGHT/2+50;g=new createjs.Text(TEXT_HELP2,
" 14px Arial Black","#A01F89");g.x=h;g.y=d;g.textAlign="left";g.textBaseline="alphabetic";g.lineWidth=200;a=new createjs.Container;e=new CFormatText(CANVAS_WIDTH/2,80,TEXT_HOW,"#FFFF00",a,"#5E0000",22,"#660099");e.setOutline(4);e.setOutlineBorder(5);b=new createjs.Container;f=new CFormatText(CANVAS_WIDTH/2,400,TEXT_START,"#66CCFF",b,"#3C0064",24,"#660099");b.on("mouseover",this._onStartOver);b.on("mouseout",this._onStartOut);b.on("click",this._onExitHelp);k=new createjs.Container;k.addChild(l,a,c,
g,b);k.alpha=0;s_oStage.addChild(k);createjs.Tween.get(k).to({alpha:1},700)};this._onStartOver=function(){f.getText().scaleX=1.2;f.getText().scaleY=1.2};this._onStartOut=function(){f.getText().scaleX=1;f.getText().scaleY=1};this.unload=function(){s_oStage.removeChild(k);b.off("mouseover",this.onStartOver);b.off("mouseout",this._onStartOut);b.off("click",this.onStartClick)};this._onExitHelp=function(){h.unload();s_oGame._onExitHelp()};h=this;this._init()}
function CGfxButton(a,e,c){var g,b,f;this._init=function(a,c,e){g=[];b=[];f=createBitmap(e);f.x=a;f.y=c;f.regX=e.width/2;f.regY=e.height/2;s_oStage.addChild(f);this._initListener()};this.unload=function(){f.off("mousedown",this.buttonDown);f.off("pressup",this.buttonRelease);s_oStage.removeChild(f)};this.setVisible=function(a){f.visible=a};this._initListener=function(){f.on("mousedown",this.buttonDown);f.on("pressup",this.buttonRelease)};this.addEventListener=function(a,c,f){g[a]=c;b[a]=f};this.buttonRelease=
function(){f.scaleX=1;f.scaleY=1;g[ON_MOUSE_UP]&&g[ON_MOUSE_UP].call(b[ON_MOUSE_UP])};this.buttonDown=function(){f.scaleX=.9;f.scaleY=.9;g[ON_MOUSE_DOWN]&&g[ON_MOUSE_DOWN].call(b[ON_MOUSE_DOWN])};this.setPosition=function(a,c){f.x=a;f.y=c};this.setX=function(a){f.x=a};this.setY=function(a){f.y=a};this.getButtonImage=function(){return f};this.getX=function(){return f.x};this.getY=function(){return f.y};this._init(a,e,c);return this}
function CGame(a){var e,c,g,b,f,l,k,h,m,d,n,p,q,w,z,t,u,r,y,A,B,D,C,F,E,v,I,x,K,M,L,N,H,G,J,O;this._init=function(){m=h=k=!1;d=!0;z=w=q=p=n=!1;u=t=0;r=localStorage.bestscore;y=0;B=A=1;var a=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(a);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)E=createjs.Sound.play("sd_bg",{loop:-1});C=new CInterface;C.refreshBestScore(r);I=new CPrinter(526,276);x=new CLady(466,177);M=new CPloyer(-13,154);a=createBitmap(s_oSpriteLibrary.getSprite("plate"));
a.x=177;a.y=336;s_oStage.addChild(a);L=createBitmap(s_oSpriteLibrary.getSprite("cup"));L.x=182;L.y=321;s_oStage.addChild(L);a=s_oSpriteLibrary.getSprite("particle_coffee");a={images:[a],frames:{width:120,height:250},animations:{idle:[0,21,"idle"]}};a=new createjs.SpriteSheet(a);H=new createjs.Sprite(a,"idle");H.alpha=0;H.x=139;H.y=83;H.gotoAndPlay("idle");s_oStage.addChild(H);a=s_oSpriteLibrary.getSprite("empl_obj");a={images:[a],frames:[[0,0,31,48,0,-3,2],[32,0,31,48,0,-4,1],[64,0,31,48,0,-3,7],
[96,0,31,48,0,-3,1],[128,0,31,48,0,-8,6],[160,0,25,48,0,-7,-0],[192,0,31,48,0,0,5]],animations:{item0:[0],item1:[1],item2:[2],item3:[3],item4:[4],item5:[5],item6:[6]}};a=new createjs.SpriteSheet(a);G=new createjs.Sprite(a,"idle");G.visible=!1;G.gotoAndStop("item2");s_oStage.addChild(G);f=156;l=225;g=182;b=289;e=183;c=300;G.x=g;G.y=b;N=createBitmap(s_oSpriteLibrary.getSprite("cupcover"));N.x=182;N.y=321;s_oStage.addChild(N);K=new CBoss(172,140);this._attachSpilGamesLogo();new CHelpPanel};this.setObj=
function(a){G.gotoAndStop("item"+a);6!==a||z||(s_oApiInstance.Award.submit({award:"award5"}),z=!0)};this.moveObj=function(a){G.visible=!0;"getUp"===a?(G.x=f,G.y=l):"shakeUp"===a?(G.x=g,G.y=b):"shakeDown"===a?(G.x=e,G.y=c):"hide"===a&&(G.visible=!1)};this.showCup=function(){L.visible=!0;N.visible=!0};this.hideCup=function(){L.visible=!1;N.visible=!1};this.cupVisible=function(){return L.visible};this.removePoison=function(){m=!1};this.cupPoisoned=function(){return m};this.addSmoke=function(){H.alpha+=
.03;1<=H.alpha&&(H.alpha=1)};this._updateBossHealth=function(){A+=LIFE_BOSS_PER_TIME;1<A&&(A=1);B+=(A-B)/5;C.refreshLifeOnTime(A)};this.checkBossHealth=function(a){"remove"===a?(A-=(1-Math.pow(.95,Math.ceil(t/200)))*B,u+=t,u>r&&C.bestScoreVisible()&&C.refreshCurScore(u,!0),C.refreshCurScore(u,!1),1E3<=u&&!n&&(s_oApiInstance.Award.submit({award:"award1"}),n=!0),1500<=u&&!q&&360>C.getHour()&&(s_oApiInstance.Award.submit({award:"award3"}),q=!0),5E3<=u&&!w&&(s_oApiInstance.Award.submit({award:"award4"}),
w=!0),t=0,0>=A&&(A=0)):(A+=LIFE_BOSS_ON_DRINK,1<A&&(A=1));d=!1;C.refreshLife(A);.5>=A&&!p&&(s_oApiInstance.Award.submit({award:"award2"}),p=!0)};this.resumeUpdateLife=function(){d=!0};this.setScore=function(a){1===a%10&&(y++,1<y&&(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("sd_double")),C.refreshMultiplier(y));t+=a*y;C.refreshScore(t);m=!0};this.refreshCoffeeBar=function(a){var d=a%10/10;0===d&&(d=1);C.refreshCoffeBar(d);10===a&&C.flicker()};this.clearCoffeeBar=function(){C.clearCoffeeBar()};
this.removeSmoke=function(){0<H.alpha&&(H.alpha-=.05,0>=H.alpha&&(H.alpha=0))};this.onMouseStart=function(a){k=!0};this.onMouseEnd=function(){k=!1;y=0;C.refreshMultiplier(y)};this.checkCopy=function(){return I.checkCopy()};this.clearCopy=function(){I.clearCopy()};this.ladyCheckPP=function(){return x.checkPP()};this.bossCheckState=function(){return K.checkState()};this.bossCheckDir=function(){return K.checkDir()};this.onDied=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)E.stop(),createjs.Sound.play("sd_catch");
M.onDied();I.onDied();x.onDied();K.onDied();G.visible=!1;D=0;s_oGame.gameOver()};this.onTimeExpired=function(){D=1!==A?2:1;s_oGame.gameOver()};this.restartGame=function(){this.unload();this._init()};this.unload=function(){h=!1;C.unload();K.unload();x.unload();M.unload();I.unload();v.off("mousedown",this.onMouseStart);v.off("pressup",this.onMouseEnd);createjs.Tween.removeAllTweens();s_oStage.removeAllChildren()};this.onExit=function(){this.unload();s_oMain.gotoMenu();$(s_oMain).trigger("restart")};
this._onExitHelp=function(){v=new createjs.Shape;v.graphics.beginFill("rgba(0,0,0,0.01)").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);v.on("mousedown",this.onMouseStart);v.on("pressup",this.onMouseEnd);s_oStage.addChild(v);M.active();K.active();x.active();I.active();h=!0};this.gameOver=function(){F=new createjs.Shape;F.graphics.beginFill("rgba(0,0,0,1)").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);F.alpha=0;s_oStage.addChild(F);createjs.Tween.get(F).wait(1E3).to({alpha:1},2E3).call(function(){s_oGame.unload();
s_oEndPanel=CEndPanel(s_oSpriteLibrary.getSprite("end_panel_bg"),D,u)})};this.update=function(){h&&(x.update(),K.update(),k?M.doThings():M.cancelAction(),C.rotateClock(),d&&this._updateBossHealth())};this._attachSpilGamesLogo=function(){var a=s_oApiInstance.Branding.getLogo();if(a.image){J=new createjs.Bitmap(a.image);J.x=0;J.y=CANVAS_HEIGHT-97;J.scaleX=.9;J.scaleY=.9;s_oStage.addChild(J);var d=this;J.image.onload=function(){d._onAddLogoBut(a)}}};this._onAddLogoBut=function(a){var d=(new createjs.Graphics).beginFill("rgba(0,0,0,0.01)").drawRect(J.x,
J.y,J.getBounds().width,J.getBounds().height);O=new createjs.Shape(d);O.on("click",a.action);s_oStage.addChild(O)};s_oGame=this;POINTS_EARNED=a.points_earned;this._init()}var s_oEndPanel,s_oGame;
function CFormatText(a,e,c,g,b,f,l,k){var h,m,d,n,p;this._init=function(a,c,b,f,e,g,l,k){h=b;p=new createjs.Container;p.x=a;p.y=c;e.addChild(p);a=l+"px";m=new createjs.Text;m.text=h;m.font=" "+a+" Arial Black";m.color="#ffffff";m.textAlign="center";m.textBaseline="middle";m.lineWidth=400;m.outline=6;m.shadow=new createjs.Shadow(k,2,2,5);p.addChild(m);d=new createjs.Text;d.text=h;d.font=" "+a+" Arial Black";d.color=g;d.textAlign="center";d.textBaseline="middle";d.lineWidth=400;d.outline=3;p.addChild(d);
n=new createjs.Text;n.text=h;n.font="bold "+a+" Arial Black";n.color=f;n.textAlign="center";n.textBaseline="middle";n.lineWidth=400;p.addChild(n)};this.unload=function(){b.removeChild(p)};this.setVisible=function(a){p.visible=a};this.isVisible=function(){return p.visible};this.disableOutlineBorder=function(){m.visible=!1};this.setOutline=function(a){d.outline=a};this.setOutlineBorder=function(a){m.outline=a};this.setShadow=function(a){m.shadow=a?new createjs.Shadow(k,2,2,5):null};this.setText=function(a){n.text=
a;d.text=a;m.text=a};this.getText=function(){return p};this.setPos=function(a){p.y=a};this.getPos=function(){return{x:p.x,y:p.y}};this._init(a,e,c,g,b,f,l,k)}
function CEndPanel(a,e,c){var g,b,f,l,k,h,m,d,n,p,q,w,z,t,u,r;this._init=function(a,c,f){g=createBitmap(a);g.alpha=0;localStorage.bestscore<f&&localStorage.setItem("bestscore",f);l=new createjs.Container;l.alpha=0;l.x=-200;l.y=50;k=new CFormatText(0,0,"","#FFFF00",l,"#15590D",30,"#15590D");k.setOutline(6);k.setOutlineBorder(7);0===c?k.setText(TEXT_FIRED):1===c?k.setText(TEXT_TIMEOUT):k.setText(TEXT_WIN);h=new createjs.Container;h.x=700;h.y=160;h.alpha=0;new CFormatText(0,0,f,"#FFCC33",h,"#5E0000",
40,"#663300");a=s_oSpriteLibrary.getSprite("end_panel_"+c);m=createBitmap(a);2>c?(m.x=a.width/2,m.y=100+a.height/2):(m.x=-40+a.width/2,m.y=230+a.height/2);m.alpha=0;m.regX=a.width/2;m.regY=a.height/2;m.scaleX=3;m.scaleY=3;d=new createjs.Container;d.x=700;d.y=280;d.alpha=0;n=createBitmap(s_oSpriteLibrary.getSprite("end_panel_icon_1"));d.addChild(n);p=new CFormatText(90,30,TEXT_SUBMIT,"#FFFF00",d,"#15590D",18,"#15590D");p.disableOutlineBorder();p.setOutline(3);q=new createjs.Container;q.x=700;q.y=350;
q.alpha=0;w=createBitmap(s_oSpriteLibrary.getSprite("end_panel_icon_2"));q.addChild(w);z=new CFormatText(100,30,TEXT_RESTART,"#FFFF00",q,"#15590D",18,"#15590D");z.disableOutlineBorder();z.setOutline(3);b=new createjs.Container;b.addChild(g,h,l,m,d,q);s_oStage.addChild(b);this._attachSpilGamesLogo();this.show()};this.unload=function(){q.on("pressup",this._onRestartClick);s_oStage.removeChild(b);s_oEndPanel=null};this.initListeners=function(){d.on("pressup",this._onSubmitClick);q.on("pressup",this._onRestartClick);
u.on("click",r.action)};this.show=function(){createjs.Tween.get(m).to({alpha:1,scaleX:1,scaleY:1},750,createjs.Ease.cubicOut);createjs.Tween.get(l).to({alpha:1,x:CANVAS_WIDTH/2},500,createjs.Ease.cubicOut).call(function(){createjs.Tween.get(g).to({alpha:1},1E3).call(function(){createjs.Tween.get(h).to({alpha:1,x:510},300).call(function(){createjs.Tween.get(d).to({alpha:1,x:410},300).call(function(){createjs.Tween.get(q).to({alpha:1,x:410},300).call(function(){s_oApiInstance.GameBreak.request(pauseGame,
resumeGame)})})})})});$(s_oMain).trigger("save_score",c)};this._onRestartClick=function(){f.unload();s_oMain.gotoMenu()};this._onSubmitClick=function(){f.unload();(new CBestScore).insertNewField("Player",c)};this._attachSpilGamesLogo=function(){r=s_oApiInstance.Branding.getLogo();if(r.image){t=new createjs.Bitmap(r.image);t.x=440;t.y=430;t.scaleX=.8;t.scaleY=.8;b.addChild(t);var a=this;t.image.onload=function(){a._onAddLogoBut()}}};this._onAddLogoBut=function(){var a=(new createjs.Graphics).beginFill("rgba(0,0,0,0.01)").drawRect(t.x,
t.y,t.getBounds().width,t.getBounds().height);u=new createjs.Shape(a);b.addChild(u)};f=this;this._init(a,e,c);return this}
function CBoss(a,e){var c=-1,g=0,b,f,l,k,h,m,d,n,p,q,w,z,t,u,r,y,A,B,D,C,F,E,v,I,x;this._init=function(a,c){l=[];l=[this.talk,this.turnBack];k=[];k=[this.talkLady,this.talkLady,this.talkLady,this.talkLady,this.talkLady,this.talkLady,this.talkLady,this.talkLady,this.look,this.look,this.look,this.look,this.look,this.smoke,this.smoke,this.smoke,this.dance];n=new createjs.Container;n.x=a;n.y=c;s_oStage.addChild(n);var b=s_oSpriteLibrary.getSprite("boss_amaze"),b={images:[b],frames:{width:251,height:346},
animations:{idle:[0,0,"stop",1/24]}},b=new createjs.SpriteSheet(b);p=new createjs.Sprite(b,"idle");p.visible=!1;p.on("animationend",this._onAmazingDone);p.gotoAndStop("idle");n.addChild(p);b=s_oSpriteLibrary.getSprite("boss_crazy");b={images:[b],frames:{width:251,height:346},animations:{idle:[0,0,"idle1",.2],idle1:[2,2,"idle2",1/15],idle2:[1,1,"idle3",.2],idle3:[2,2,"idle4",.2],idle4:[1,1,"idle5",.2],idle5:[2,2,"idle6",.2],idle6:[1,1,"idle7",.2],idle7:[2,2,"idle8",.2],idle8:[1,1,"idle1",1/28]}};b=
new createjs.SpriteSheet(b);q=new createjs.Sprite(b,"idle");q.visible=!1;q.gotoAndStop("idle");n.addChild(q);b=s_oSpriteLibrary.getSprite("boss_dance");b={images:[b],frames:{width:251,height:346},animations:{idle:[1,1,"idle1",1/6],idle1:[0,0,"idle2",1/6],idle2:[1,1,"idle3",1/6],idle3:[0,0,"idle4",1/7],idle4:[1,1,"idle5",1/6],idle5:[0,0,"idle6",1/6],idle6:[1,1,"idle7",1/6],idle7:[0,0,"idle",1/6]}};b=new createjs.SpriteSheet(b);w=new createjs.Sprite(b,"idle");w.visible=!1;w.gotoAndStop("idle");n.addChild(w);
b=s_oSpriteLibrary.getSprite("boss_drink");b={images:[b],frames:{width:251,height:346},animations:{idle:[0,0,"idle1",.2],idle1:[1,1,"idle2",.2],idle2:[2,2,"idle3",1/7],idle3:[3,3,"idle4",.2],idle4:[4,4,"idle5",.2],idle5:[5,5,"idle6",.2],idle6:[6,6,"idle7",.2],idle7:[7,7,"idle8",1/6],idle8:[8,8,"idle9",.2],idle9:[9,9,"stop",1/13],idle10:[10,10,"idle11",.25],idle11:[11,11,"stop",.2]}};b=new createjs.SpriteSheet(b);t=new createjs.Sprite(b,"idle");t.visible=!1;t.on("animationend",this._onDrink);t.on("animationend",
this._onPull);t.gotoAndStop("idle");n.addChild(t);b=s_oSpriteLibrary.getSprite("boss_drink_D");b={images:[b],framerate:24,frames:{width:251,height:346},animations:{idle:[0,7,"idle1"],idle1:[8,8,"idle2",1/9],idle2:[9,12,"idle"]}};b=new createjs.SpriteSheet(b);y=new createjs.Sprite(b,"idle");y.visible=!1;y.on("animationend",this._onDrinkD);y.gotoAndStop("idle");n.addChild(y);b=s_oSpriteLibrary.getSprite("boss_look_lady");b={images:[b],frames:{width:251,height:346},animations:{idle:[0,0,"stop",1/65]}};
b=new createjs.SpriteSheet(b);u=new createjs.Sprite(b,"idle");u.visible=!1;u.gotoAndStop("idle");n.addChild(u);b=s_oSpriteLibrary.getSprite("boss_midd_state");b={images:[b],frames:{width:251,height:346},animations:{idle:[0,0,"idle1",.2],idle1:[1,1,"idle2",.2],idle2:[0,0,"idle3",.2],idle3:[1,1,"idle4",.2],idle4:[0,0,"idle",.125]}};b=new createjs.SpriteSheet(b);r=new createjs.Sprite(b,"idle");r.visible=!1;r.gotoAndStop("idle");n.addChild(r);b=s_oSpriteLibrary.getSprite("boss_pull_back");b={images:[b],
frames:{width:251,height:346},animations:{idle:[0,0,"idle1",.2],idle1:[1,1,"idle2",.2],idle2:[2,2,"idle3",.2],idle3:[3,3,"idle4",.25],idle4:[4,4,"idle5",.2],idle5:[5,5,"idle6",.2],idle6:[6,6,"idle7",.2],idle7:[7,7,"stop",1/12]}};b=new createjs.SpriteSheet(b);A=new createjs.Sprite(b,"idle");A.visible=!1;A.on("animationend",this._onDrinkDone);A.gotoAndStop("idle");n.addChild(A);b=s_oSpriteLibrary.getSprite("boss_shout");b={images:[b],frames:{width:251,height:346},animations:{idle:[0,0,"idle1",1/6],
idle1:[1,1,"idle2",.2],idle2:[0,0,"idle3",1/6],idle3:[1,1,"idle4",.2],idle4:[0,0,"idle5",1/6],idle5:[1,1,"idle6",.2],idle6:[0,0,"idle7",1/6],idle7:[1,1,"idle",1/9]}};b=new createjs.SpriteSheet(b);B=new createjs.Sprite(b,"idle");B.visible=!1;B.gotoAndStop("idle");n.addChild(B);b=s_oSpriteLibrary.getSprite("boss_smoke");b={images:[b],frames:{width:251,height:346},animations:{idle:[0,0,"idle1",1/9],idle1:[1,1,"idle2",.5],idle2:[2,2,"idle3",1/11],idle3:[3,3,"idle4",1/23],idle4:[4,4,"idle5",.25],idle5:[5,
5,"idle6",1/12],idle6:[6,6,"idle7",.25],idle7:[7,7,"idle8",.25],idle8:[8,8,"idle9",.25],idle9:[9,9,"idle10",.25],idle10:[10,10,"idle11",.25],idle11:[11,11,"idle12",.25],idle12:[12,12,"idle13",.25],idle13:[13,13,"stop",.125]}};b=new createjs.SpriteSheet(b);D=new createjs.Sprite(b,"idle");D.visible=!1;D.on("animationend",this._onSmokeDone);D.on("animationend",this._onSmoke);D.gotoAndStop("idle");n.addChild(D);b=s_oSpriteLibrary.getSprite("boss_talk");b={images:[b],frames:{width:251,height:346},animations:{idle:[0,
0,"idle1",.1],idle1:[1,1,"idle2",.5],idle2:[2,2,"idle3",1/3],idle3:[3,3,"idle4",1/3],idle4:[4,4,"idle5",.2],idle5:[5,5,"idle6",.5],idle6:[6,6,"idle7",.25],idle7:[7,7,"idle8",.25],idle8:[8,8,"idle9",1/3],idle9:[9,9,"idle10",1/6],idle10:[10,10,"idle11",.5],idle11:[11,11,"idle12",1/3],idle12:[12,12,"idle13",1/6],idle13:[13,13,"idle14",1],idle14:[14,14,"idle15",.2],idle15:[15,15,"idle2",.125]}};b=new createjs.SpriteSheet(b);C=new createjs.Sprite(b,"idle");C.visible=!1;C.gotoAndStop("idle");n.addChild(C);
b=s_oSpriteLibrary.getSprite("boss_talk_to_lady");b={images:[b],frames:{width:251,height:346},animations:{idle:[0,0,"idle1",.2],idle1:[1,1,"idle2",.2],idle2:[2,2,"idle3",.2],idle3:[3,3,"idle4",.2],idle4:[4,4,"idle5",.2],idle5:[5,5,"idle6",.2],idle6:[2,2,"idle7",.2],idle7:[4,4,"idle8",.2],idle8:[5,5,"idle9",.2],idle9:[2,2,"idle2",1/31]}};b=new createjs.SpriteSheet(b);F=new createjs.Sprite(b,"idle");F.visible=!1;F.gotoAndStop("idle");n.addChild(F);b=s_oSpriteLibrary.getSprite("boss_turn_back");b={images:[b],
frames:{width:251,height:346},animations:{idle:[0,0,"stop",.2]}};b=new createjs.SpriteSheet(b);E=new createjs.Sprite(b,"idle");E.visible=!1;E.gotoAndStop("idle");n.addChild(E);b=s_oSpriteLibrary.getSprite("boss_ugly");b={images:[b],frames:{width:251,height:346},animations:{idle:[0,0,"idle1",.25],idle1:[1,1,"idle2",.25],idle2:[0,0,"idle3",.25],idle3:[1,1,"idle4",.25],idle4:[0,0,"idle5",.25],idle5:[1,1,"idle6",.25],idle6:[0,0,"idle7",.25],idle7:[1,1,"idle",1/6]}};b=new createjs.SpriteSheet(b);v=new createjs.Sprite(b,
"idle");v.visible=!1;v.gotoAndStop("idle");n.addChild(v);b=s_oSpriteLibrary.getSprite("boss_wz");b={images:[b],frames:{width:251,height:346},animations:{idle:[0,0,"idle1",1/7],idle1:[1,1,"idle2",1/6],idle2:[0,0,"idle3",.04],idle3:[1,1,"idle4",.125],idle4:[0,0,"idle",.1]}};b=new createjs.SpriteSheet(b);I=new createjs.Sprite(b,"idle");I.visible=!1;I.gotoAndStop("idle");n.addChild(I);d=F;d.visible=!0};this.active=function(){c=1;k[Math.floor(Math.random()*k.length)]()};this.unload=function(){p.off("animationend",
this._onAmazingDone);t.off("animationend",this._onDrink);t.off("animationend",this._onPull);y.off("animationend",this._onDrinkD);A.off("animationend",this._onDrinkDone);D.off("animationend",this._onSmokeDone);D.off("animationend",this._onSmoke);s_oStage.removeChild(n)};this.getRandomAction=function(){switch(c){case 0:-1===g?(x.getSpecial(l),c=-1):(x.getSpecial(k),c=1);break;case -1:.38<Math.random()?(x.getSpecial(k),c=1):(c=-1,x.getSpecial(l));break;case 1:.4<Math.random()?(g=.38<Math.random()?-1:
1,h=m=x.mid,c=0):(x.getSpecial(k),c=1)}m()};this.getSpecial=function(a){for(;h===m;)h=x.getRandomSpecial(a);m=h};this.getRandomSpecial=function(a){return a[Math.floor(Math.random()*a.length)]};this.amaze=function(){d.stop();d.visible=!1;d=p;d.visible=!0;d.gotoAndPlay("idle");f=12};this.crazy=function(){d.stop();d.visible=!1;d=q;d.visible=!0;d.gotoAndPlay("idle");f=11};this.dance=function(){d.stop();d.visible=!1;d=w;d.visible=!0;d.gotoAndPlay("idle");if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)z=
createjs.Sound.play("sd_dance");f=4;x.setDelay(x.onDanceOver,4,2)};this.onDanceOver=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||z.stop();x.getRandomAction()};this.drink=function(){d.stop();d.visible=!1;d=t;d.visible=!0;d.gotoAndPlay("idle");s_oGame.hideCup();f=6};this.look=function(){d.stop();d.visible=!1;d=u;d.visible=!0;d.gotoAndPlay("idle");f=13;x.setDelay(x.getRandomAction,4,2)};this.mid=function(){d.stop();d.visible=!1;d=r;d.visible=!0;d.gotoAndPlay("idle");!1!==DISABLE_SOUND_MOBILE&&
!1!==s_bMobile||createjs.Sound.play("sd_sb");f=5;x.setDelay(x.getRandomAction,2,.5)};this.poison=function(){d.stop();d.visible=!1;d=y;d.visible=!0;d.gotoAndPlay("idle");f=8;!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("sd_turn")};this.pull=function(){d.stop();d.visible=!1;d=A;d.visible=!0;d.gotoAndPlay("idle");f=14};this.shout=function(){d.stop();d.visible=!1;d=B;d.visible=!0;d.gotoAndPlay("idle");f=7};this.smoke=function(){d.stop();d.visible=!1;d=D;d.visible=!0;d.gotoAndPlay("idle");
f=2};this.talk=function(){d.stop();d.visible=!1;d=C;d.visible=!0;d.gotoAndPlay("idle");f=1;x.setDelay(x.getRandomAction,4,2)};this.talkLady=function(){d.stop();d.visible=!1;d=F;d.visible=!0;d.gotoAndPlay("idle");f=3;x.setDelay(x.getRandomAction,4,2)};this.turnBack=function(){d.stop();d.visible=!1;d=E;d.visible=!0;d.gotoAndPlay("idle");f=15;x.setDelay(x.drink,2,1)};this.ugly=function(){d.stop();d.visible=!1;d=v;d.visible=!0;d.gotoAndPlay("idle");f=9;x.setDelay(x.pull,3,1)};this.wz=function(){d.stop();
d.visible=!1;d=I;d.visible=!0;d.gotoAndPlay("idle");!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("sd_ugly");f=10;x.setDelay(x.pull,3,1)};this.update=function(){3!==f&&13!==f||!s_oGame.ladyCheckPP()||11===f?11!==f||s_oGame.ladyCheckPP()||(x.clearTimer(),x.getRandomAction()):(x.clearTimer(),x.crazy())};this.onDied=function(){12!==f&&(x.clearTimer(),x.setDelay(x.amaze,.5,.4))};this._onDrinkD=function(){"idle2"===d.currentAnimation&&(.5<Math.random()?x.wz():x.ugly())};this._onAmazingDone=
function(){x.shout()};this._onSmoke=function(){"idle1"===d.currentAnimation?!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("sd_smokeIn"):"idle6"===d.currentAnimation&&(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("sd_smokeOut"))};this._onSmokeDone=function(){"idle13"===d.currentAnimation&&x.getRandomAction()};this._onDrinkDone=function(){"idle7"===d.currentAnimation&&(s_oGame.showCup(),x.getRandomAction())};this._onDrink=function(){"idle8"===d.currentAnimation?!1!==
DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("sd_drink"):"idle9"===d.currentAnimation&&(s_oGame.cupPoisoned()?(x.poison(),s_oGame.checkBossHealth("remove")):(d.gotoAndPlay("idle10"),s_oGame.checkBossHealth("add")),s_oGame.removePoison())};this._onPull=function(){"idle11"===d.currentAnimation&&(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("sd_ha"),x.pull())};this.checkDir=function(){return-1===c};this.checkState=function(){return 6===f||8===f||14===f||10===f||9===f};
this.checkLady=function(){return 3===f};this.setDelay=function(a,d,c){d*=Math.random();d<=c&&(d=c);b=setTimeout(a,1E3*d)};this.clearTimer=function(){clearTimeout(b)};x=this;this._init(a,e)}
function CBestScore(){var a,e,c,g,b,f,l,k,h,m,d,n,p,q,w,z;this._init=function(){g=createBitmap(s_oSpriteLibrary.getSprite("best_score_panel"));g.x=0;g.y=0;var f=CANVAS_WIDTH/2,h=CANVAS_WIDTH/2+125;b=new createjs.Container;d=new createjs.Container;d.x=f;a=[];for(var r=0;10>r;r++)f=JSON.parse(localStorage.getItem(r)).name,a[r]=new createjs.Text(f,"bold 14px Arial Black","#A01F89"),a[r].y=147+24*r,a[r].textAlign="center",a[r].textBaseline="middle",a[r].lineWidth=500,d.addChild(a[r]);n=new createjs.Container;
n.x=h;e=[];c=[];for(r=0;10>r;r++)e[r]=JSON.parse(localStorage.getItem(r)).score,c[r]=new createjs.Text(e[r],"bold 14px Arial Black","#000000"),c[r].y=147+24*r,c[r].textAlign="center",c[r].textBaseline="middle",c[r].lineWidth=500,n.addChild(c[r]);b.addChild(g,k,q,void 0,d,m,n);s_oStage.addChild(b);this._attachSpilGamesLogo();this._attachMoreGameButton();m=new CFormatText(CANVAS_WIDTH/2+200,CANVAS_HEIGHT-40,TEXT_MENU,"#FFFF00",b,"#006600",26,"#660099");m.disableOutlineBorder();m.setOutline(3);m.getText().addEventListener("click",
this._onRestartClick,this);l=new CFormatText(CANVAS_WIDTH/2+1,67,TEXT_HIGH,"#FFCC33",b,"#5E0000",26,"#663300");l.setOutline(4);p=new CFormatText(CANVAS_WIDTH/2-118,107,TEXT_RANKING,"#6601ff",b,"#FFFFFF",14,"#660099");p.disableOutlineBorder();p.setOutline(1);q=new CFormatText(CANVAS_WIDTH/2,107,TEXT_NAME,"#6601ff",b,"#FFFFFF",14,"#660099");q.disableOutlineBorder();q.setOutline(1);k=new CFormatText(CANVAS_WIDTH/2+125,107,TEXT_SCORE,"#6601ff",b,"#FFFFFF",14,"#660099");k.disableOutlineBorder();k.setOutline(1)};
this.unload=function(){h.unload();s_oStage.removeChild(b)};this.insertNewField=function(b,d){for(var f=null,g=0;g<e.length;g++)if(d>e[g]){f=g;break}if(null!==f){for(var h=e[f],l=a[f].text,g=f;g<e.length;g++)e[g]=d,c[g].text=d,d=h,g<e.length-1&&(h=e[g+1]),a[g].text=b,b=l,g<e.length-1&&(l=a[g+1].text);localStorage.clear();for(g=0;10>g;g++)localStorage.setItem(g,JSON.stringify({name:a[g].text,score:e[g]}))}};this._onRestartClick=function(){f.unload();s_oMain.gotoMenu()};this._attachSpilGamesLogo=function(){var a=
s_oApiInstance.Branding.getLogo();if(a.image){w=new createjs.Bitmap(a.image);w.x=CANVAS_WIDTH/2-100;w.y=CANVAS_HEIGHT-70;b.addChild(w);var d=this;w.image.onload=function(){d._onAddLogoBut(a)}}};this._onAddLogoBut=function(a){var d=(new createjs.Graphics).beginFill("rgba(0,0,0,0.01)").drawRect(w.x,w.y,w.getBounds().width,w.getBounds().height);z=new createjs.Shape(d);z.on("click",a.action);b.addChild(z)};this._attachMoreGameButton=function(){var a=s_oApiInstance.Branding.getLink("more_games");h=new CFormatText(CANVAS_WIDTH/
2-200,CANVAS_HEIGHT-40,TEXT_MORE,"#FFFF00",b,"#006600",26,"#660099");h.disableOutlineBorder();h.setOutline(3);h.getText().addEventListener("click",a.action,this)};f=this;this._init();return this}
function CAnimButton(a,e,c,g,b,f,l,k,h){var m,d,n,p,q,w,z;this._init=function(a,b,c,f,g,e,h){m=[];d=[];var l=Math.ceil(h/20),k=new createjs.SpriteSheet({images:[c],frames:{width:c.width,height:c.height/3,regX:c.width/2,regY:c.height/3/2},animations:{idle:[0],over:[1],press:[2]}});p=new createSprite(k,"idle",c.width/2,c.height/3/2,c.width,c.height/3);z=new createjs.Text(f,"bold "+h+"px "+g,"#000000");z.textAlign="center";z.textBaseline="center";z.getBounds();z.y=15+l;w=new createjs.Text(f,"bold "+
h+"px "+g,e);w.textAlign="center";w.textBaseline="center";w.getBounds();w.y=15;n=new createjs.Container;n.x=a;n.y=b;n.addChild(p,z,w);s_oStage.addChild(n);this._initListener()};this.unload=function(){!1===s_bMobile&&(q.off("mouseover",this._highlightOn),q.off("mouseout",this._highlightOff));q.off("mousedown",this.buttonDown);q.off("pressup",this.buttonRelease);s_oStage.removeChild(n)};this.setVisible=function(a){n.visible=a};this._initListener=function(){var a=(new createjs.Graphics).beginFill("rgba(158,158,158,0.01)").drawRect(-k/
2,-h/2,k,h);q=new createjs.Shape(a);!1===s_bMobile&&(q.on("mouseover",this._highlightOn),q.on("mouseout",this._highlightOff));q.on("mousedown",this.buttonDown);q.on("pressup",this.buttonRelease);n.addChild(q)};this._highlightOn=function(){p.gotoAndStop("over");!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("sd_on")};this._highlightOff=function(){p.gotoAndStop("idle")};this.addEventListener=function(a,b,c){m[a]=b;d[a]=c};this.buttonRelease=function(){p.gotoAndStop("idle");m[ON_MOUSE_UP]&&
m[ON_MOUSE_UP].call(d[ON_MOUSE_UP])};this.buttonDown=function(){p.gotoAndStop("press");!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("sd_down");m[ON_MOUSE_DOWN]&&m[ON_MOUSE_DOWN].call(d[ON_MOUSE_DOWN])};this.setTextPosition=function(a){w.y=a;z.y=a+2};this.setPosition=function(a,b){n.x=a;n.y=b};this.setX=function(a){n.x=a};this.setY=function(a){n.y=a};this.getButtonImage=function(){return n};this.getX=function(){return n.x};this.getY=function(){return n.y};this._init(a,e,c,g,b,f,l);
return this}
function CSpriteLibrary(){var a,e,c,g,b,f;this.init=function(l,k,h){c=e=0;g=l;b=k;f=h;a={}};this.addSprite=function(b,c){a.hasOwnProperty(b)||(a[b]={szPath:c,oSprite:new Image},e++)};this.getSprite=function(b){return a.hasOwnProperty(b)?a[b].oSprite:null};this._onSpritesLoaded=function(){b.call(f)};this._onSpriteLoaded=function(){g.call(f);++c==e&&this._onSpritesLoaded()};this.loadSprites=function(){for(var b in a)a[b].oSprite.oSpriteLibrary=this,a[b].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},a[b].oSprite.src=
a[b].szPath};this.getNumSprites=function(){return e}}var CANVAS_WIDTH=640,CANVAS_HEIGHT=480,EDGEBOARD_X=0,EDGEBOARD_Y=0,FPS=30,DISABLE_SOUND_MOBILE=!1,STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,LIFE_BOSS_PER_TIME=3.6E-5,LIFE_BOSS_ON_DRINK=.037;
function CToggle(a,e,c,g){var b,f,l,k;this._init=function(a,c,d,g){f=[];l=[];var e=new createjs.SpriteSheet({images:[d],frames:{width:d.width/2,height:d.height,regX:d.width/2/2,regY:d.height/2},animations:{state_true:[0],state_false:[1]}});b=g;k=createSprite(e,"state_"+b,d.width/2/2,d.height/2,d.width/2,d.height);k.x=a;k.y=c;k.stop();s_oStage.addChild(k);this._initListener()};this.unload=function(){k.off("mousedown",this.buttonDown);k.off("pressup",this.buttonRelease);s_oStage.removeChild(k)};this._initListener=
function(){k.on("mousedown",this.buttonDown);k.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,d){f[a]=b;l[a]=d};this.setActive=function(a){b=a;k.gotoAndStop("state_"+b)};this.buttonRelease=function(){k.scaleX=1;k.scaleY=1;!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");b=!b;k.gotoAndStop("state_"+b);f[ON_MOUSE_UP]&&f[ON_MOUSE_UP].call(l[ON_MOUSE_UP],b)};this.buttonDown=function(){k.scaleX=.9;k.scaleY=.9;f[ON_MOUSE_DOWN]&&f[ON_MOUSE_DOWN].call(l[ON_MOUSE_DOWN])};
this.setPosition=function(a,b){k.x=a;k.y=b};this._init(a,e,c,g)}var s_iScaleFactor=1,s_oCanvasLeft,s_oCanvasTop;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,4))})(navigator.userAgent||
navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});$(window).blur(function(){null!==s_oMain&&s_oMain.playAllSounds(!1)});$(window).focus(function(){s_bAudioActive&&null!==s_oMain&&s_oMain.playAllSounds(!0)});function trace(a){console.log(a)}
function getSize(a){var e=a.toLowerCase(),c=window.document,g=c.documentElement;if(void 0===window["inner"+a])a=g["client"+a];else if(window["inner"+a]!=g["client"+a]){var b=c.createElement("body");b.id="vpw-test-b";b.style.cssText="overflow:scroll";var f=c.createElement("div");f.id="vpw-test-d";f.style.cssText="position:absolute;top:-1000px";f.innerHTML="<style>@media("+e+":"+g["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+e+":7px!important}}</style>";b.appendChild(f);g.insertBefore(b,c.head);
a=7==f["offset"+a]?g["client"+a]:window["inner"+a];g.removeChild(b)}else a=window["inner"+a];return a}$(window).ready(function(){sizeHandler()});window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}
function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a;a=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var e=getSize("Width"),c=Math.min(a/CANVAS_HEIGHT,e/CANVAS_WIDTH),g=CANVAS_WIDTH*c,c=CANVAS_HEIGHT*c,b=0;c<a?(b=a-c,c+=b,g+=CANVAS_WIDTH/CANVAS_HEIGHT*b):g<e&&(b=e-g,g+=b,c+=CANVAS_HEIGHT/CANVAS_WIDTH*b);var b=a/2-c/2,f=e/2-g/2,l=CANVAS_WIDTH/g;if(f*l<-EDGEBOARD_X||b*l<-EDGEBOARD_Y)c=Math.min(a/(CANVAS_HEIGHT-2*EDGEBOARD_Y),e/(CANVAS_WIDTH-2*
EDGEBOARD_X)),g=CANVAS_WIDTH*c,c*=CANVAS_HEIGHT,b=(a-c)/2,f=(e-g)/2,l=CANVAS_WIDTH/g;s_iOffsetX=-1*f*l;s_iOffsetY=-1*b*l;0<=b&&(s_iOffsetY=0);0<=f&&(s_iOffsetX=0);$("#canvas").css("width",g+"px");$("#canvas").css("height",c+"px");0>b?$("#canvas").css("top",b+"px"):$("#canvas").css("top","0px");$("#canvas").css("left",f+"px")}}
function createBitmap(a,e,c){var g=new createjs.Bitmap(a),b=new createjs.Shape;e&&c?b.graphics.beginFill("#fff").drawRect(0,0,e,c):b.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);g.hitArea=b;return g}function createSprite(a,e,c,g,b,f){a=null!==e?new createjs.Sprite(a,e):new createjs.Sprite(a);e=new createjs.Shape;e.graphics.beginFill("#000000").drawRect(-c,-g,b,f);a.hitArea=e;return a}
function randomFloatBetween(a,e,c){"undefined"===typeof c&&(c=2);return parseFloat(Math.min(a+Math.random()*(e-a),e).toFixed(c))}function rotateVector2D(a,e){var c=e.getX()*Math.cos(a)+e.getY()*Math.sin(a),g=e.getX()*-Math.sin(a)+e.getY()*Math.cos(a);e.set(c,g)}function tweenVectorsOnX(a,e,c){return a+c*(e-a)}function shuffle(a){for(var e=a.length,c,g;0!==e;)g=Math.floor(Math.random()*e),--e,c=a[e],a[e]=a[g],a[g]=c;return a}
function bubbleSort(a){var e;do{e=!1;for(var c=0;c<a.length-1;c++)a[c]>a[c+1]&&(e=a[c],a[c]=a[c+1],a[c+1]=e,e=!0)}while(e)}function compare(a,e){return a.index>e.index?-1:a.index<e.index?1:0}function easeLinear(a,e,c,g){return c*a/g+e}function easeInQuad(a,e,c,g){return c*(a/=g)*a+e}function easeInSine(a,e,c,g){return-c*Math.cos(a/g*(Math.PI/2))+c+e}function easeInCubic(a,e,c,g){return c*(a/=g)*a*a+e}
function getTrajectoryPoint(a,e){var c=new createjs.Point,g=(1-a)*(1-a),b=a*a;c.x=g*e.start.x+2*(1-a)*a*e.traj.x+b*e.end.x;c.y=g*e.start.y+2*(1-a)*a*e.traj.y+b*e.end.y;return c}function formatTime(a){a/=1E3;var e=Math.floor(a/60);a=parseFloat(a-60*e).toFixed(1);var c="",c=10>e?c+("0"+e+":"):c+(e+":");return c=10>a?c+("0"+a):c+a}function degreesToRadians(a){return a*Math.PI/180}function checkRectCollision(a,e){var c,g;c=getBounds(a,.9);g=getBounds(e,.98);return calculateIntersection(c,g)}
function calculateIntersection(a,e){var c,g,b,f,l,k,h,m;c=a.x+(b=a.width/2);g=a.y+(f=a.height/2);l=e.x+(k=e.width/2);h=e.y+(m=e.height/2);c=Math.abs(c-l)-(b+k);g=Math.abs(g-h)-(f+m);return 0>c&&0>g?(c=Math.min(Math.min(a.width,e.width),-c),g=Math.min(Math.min(a.height,e.height),-g),{x:Math.max(a.x,e.x),y:Math.max(a.y,e.y),width:c,height:g,rect1:a,rect2:e}):null}
function getBounds(a,e){var c={x:Infinity,y:Infinity,width:0,height:0};if(a instanceof createjs.Container){c.x2=-Infinity;c.y2=-Infinity;var g=a.children,b=g.length,f,l;for(l=0;l<b;l++)f=getBounds(g[l],1),f.x<c.x&&(c.x=f.x),f.y<c.y&&(c.y=f.y),f.x+f.width>c.x2&&(c.x2=f.x+f.width),f.y+f.height>c.y2&&(c.y2=f.y+f.height);Infinity==c.x&&(c.x=0);Infinity==c.y&&(c.y=0);Infinity==c.x2&&(c.x2=0);Infinity==c.y2&&(c.y2=0);c.width=c.x2-c.x;c.height=c.y2-c.y;delete c.x2;delete c.y2}else{var k,h;a instanceof createjs.Bitmap?
(b=a.sourceRect||a.image,l=b.width*e,k=b.height*e):a instanceof createjs.Sprite?a.spriteSheet._frames&&a.spriteSheet._frames[a.currentFrame]&&a.spriteSheet._frames[a.currentFrame].image?(b=a.spriteSheet.getFrame(a.currentFrame),l=b.rect.width,k=b.rect.height,g=b.regX,h=b.regY):(c.x=a.x||0,c.y=a.y||0):(c.x=a.x||0,c.y=a.y||0);g=g||0;l=l||0;h=h||0;k=k||0;c.regX=g;c.regY=h;b=a.localToGlobal(0-g,0-h);f=a.localToGlobal(l-g,k-h);l=a.localToGlobal(l-g,0-h);g=a.localToGlobal(0-g,k-h);c.x=Math.min(Math.min(Math.min(b.x,
f.x),l.x),g.x);c.y=Math.min(Math.min(Math.min(b.y,f.y),l.y),g.y);c.width=Math.max(Math.max(Math.max(b.x,f.x),l.x),g.x)-c.x;c.height=Math.max(Math.max(Math.max(b.y,f.y),l.y),g.y)-c.y}return c}function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}function shuffle(a){for(var e=a.length,c,g;0<e;)g=Math.floor(Math.random()*e),e--,c=a[e],a[e]=a[g],a[g]=c;return a}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3==a.nodeType&&(a=a.parentNode);var e=document.createEvent("MouseEvents");e.initEvent("click",!0,!0);a.dispatchEvent(e)}}};function pauseGame(){}function resumeGame(){s_oEndPanel.initListeners()}
(function(){function a(a){var g={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};a=a||window.event;a.type in g?document.body.className=g[a.type]:(document.body.className=this[e]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var e="hidden";e in document?document.addEventListener("visibilitychange",a):(e="mozHidden")in document?document.addEventListener("mozvisibilitychange",a):(e="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",a):(e="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a})();
function CPrinter(a,e){var c,g;this._init=function(a,f){g=0;var e={images:[s_oSpriteLibrary.getSprite("printer")],frames:{width:130,height:210},animations:{idle:[0,0,"idle1"],idle1:[1,35,"idle2"],idle2:[36,36,"idle3",1/41],idle3:[37,55,"idle4"],idle4:[0,0,"idle",1/108]}},e=new createjs.SpriteSheet(e);c=new createjs.Sprite(e,"idle");c.gotoAndStop("idle");c.x=a;c.y=f;c.on("animationend",this._onCopyDone);s_oStage.addChild(c)};this.active=function(){c.play()};this.unload=function(){s_oStage.removeChild(c)};
this._onCopyDone=function(){"idle3"===c.currentAnimation?g++:"idle"===c.currentAnimation&&(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("sd_copyCat"))};this.onDied=function(){c.stop()};this.clearCopy=function(){g=0};this.checkCopy=function(){return 0!==g};this._init(a,e)}
function CPreloader(){var a,e,c,g,b,f,l;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.loadSprites();l=new createjs.Container;s_oStage.addChild(l)};this.unload=function(){l.removeAllChildren()};this.hide=function(){var a=this;setTimeout(function(){createjs.Tween.get(f).to({alpha:1},500).call(function(){a.unload();
s_oMain.gotoMenu()})},1E3)};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var k=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));l.addChild(k);k=s_oSpriteLibrary.getSprite("progress_bar");g=createBitmap(k);g.x=CANVAS_WIDTH/2-k.width/2;g.y=CANVAS_HEIGHT-70;l.addChild(g);a=k.width;e=k.height;b=new createjs.Shape;b.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(g.x,g.y,1,e);l.addChild(b);g.mask=
b;c=new createjs.Text("","30px Arial","#fff");c.x=CANVAS_WIDTH/2;c.y=CANVAS_HEIGHT-25;c.shadow=new createjs.Shadow("#000",2,2,2);c.textBaseline="alphabetic";c.textAlign="center";l.addChild(c);f=new createjs.Shape;f.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);f.alpha=0;l.addChild(f)};this.refreshLoader=function(f){c.text=f+"%";b.graphics.clear();f=Math.floor(f*a/100);b.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(g.x,g.y,f,e)};this._init()}
function CPloyer(a,e){var c,g,b,f,l,k,h,m,d,n,p,q,w,z,t,u,r,y,A,B;this._init=function(a,b){c=!1;f=g=0;k=2;h=[];h=[this.stupid,this.normal];if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)A=createjs.Sound.play("sd_fear"),A.stop(),B=createjs.Sound.play("sd_keyBoard",{loop:-1}),B.stop();m=new createjs.Container;m.x=a;m.y=b;s_oStage.addChild(m);var e=s_oSpriteLibrary.getSprite("employee_fail"),e={images:[e],frames:{width:254,height:364},animations:{idle:[0,0,"idle1",.1],idle1:[1,1,"stop",.05]}},e=new createjs.SpriteSheet(e);
n=new createjs.Sprite(e,"idle");n.visible=!1;n.on("animationend",this._onFallDone);n.gotoAndStop("idle");m.addChild(n);e=s_oSpriteLibrary.getSprite("employee_get_sock");e={images:[e],frames:{width:254,height:364},animations:{idle:[0,0,"idle1",.25],idle1:[1,1,"stop",1/9]}};e=new createjs.SpriteSheet(e);p=new createjs.Sprite(e,"idle");p.visible=!1;p.on("animationend",this._onFinding);p.gotoAndStop("idle");m.addChild(p);e=s_oSpriteLibrary.getSprite("employee_get_up");e={images:[e],frames:{width:254,
height:364},animations:{idle:[0,0,"idle1",1/7],idle1:[1,1,"idle2",.2],idle2:[0,0,"idle3",.25],idle3:[1,1,"idle4",.25],idle4:[0,0,"idle5",.25],idle5:[1,1,"idle6",.2],idle6:[0,0,"idle7",.25],idle7:[2,2,"idle8",1/3],idle8:[3,3,"stop",1]}};e=new createjs.SpriteSheet(e);q=new createjs.Sprite(e,"idle");q.visible=!1;q.on("animationend",this._onGetUp);q.gotoAndStop("idle");m.addChild(q);e=s_oSpriteLibrary.getSprite("employee_normal");e={images:[e],frames:{width:254,height:364},animations:{idle:[0,0,"idle1",
1/17],idle1:[1,1,"idle2",.0625],idle2:[2,2,"idle3",1/18],idle3:[1,1,"idle4",1/19],idle4:[0,0,"idle5",.05],idle5:[4,4,"idle6",1/3],idle6:[3,3,"idle7",.2],idle7:[4,4,"idle8",.5],idle8:[0,0,"idle",1/18]}};e=new createjs.SpriteSheet(e);w=new createjs.Sprite(e,"idle");w.visible=!1;w.gotoAndStop("idle");m.addChild(w);e=s_oSpriteLibrary.getSprite("employee_shake");e={images:[e],frames:{width:254,height:364},animations:{idle:[1,1,"idle1",.2],idle1:[0,0,"idle",.2]}};e=new createjs.SpriteSheet(e);z=new createjs.Sprite(e,
"idle");z.visible=!1;z.on("animationend",this._onShake);z.gotoAndStop("idle");m.addChild(z);e=s_oSpriteLibrary.getSprite("employee_stupid");e={images:[e],frames:{width:254,height:364},animations:{idle:[0,0,"idle1",.0625],idle1:[1,1,"idle2",1/3],idle2:[2,2,"idle3",1/3],idle3:[1,1,"idle4",.5],idle4:[0,0,"idle5",1/21],idle5:[1,1,"idle6",1/3],idle6:[2,2,"idle7",1/3],idle7:[1,1,"idle8",.5],idle8:[0,0,"idle",.0625]}};e=new createjs.SpriteSheet(e);t=new createjs.Sprite(e,"idle");t.visible=!1;t.gotoAndStop("idle");
m.addChild(t);e=s_oSpriteLibrary.getSprite("employee_ugly");e={images:[e],frames:{width:254,height:364},animations:{idle:[0,14,"stop",.4]}};e=new createjs.SpriteSheet(e);u=new createjs.Sprite(e,"idle");u.visible=!1;u.on("animationend",this._onUglyDone);u.gotoAndStop("idle");m.addChild(u);e=s_oSpriteLibrary.getSprite("employee_win");e={images:[e],frames:{width:254,height:364},animations:{idle:[0,0,"idle1",1/6],idle1:[1,1,"idle2",.2],idle2:[2,2,"idle3",1/7],idle3:[3,3,"idle4",.25],idle4:[4,4,"idle5",
1/6],idle5:[3,3,"idle6",.2],idle6:[4,4,"idle2",.125]}};e=new createjs.SpriteSheet(e);r=new createjs.Sprite(e,"idle");r.visible=!1;r.gotoAndStop("idle");m.addChild(r);d=w;d.visible=!0};this.active=function(){this.getRandomAction()};this.unload=function(){p.off("animationend",this._onFinding);z.off("animationend",this._onShake);q.off("animationend",this._onGetUp);n.off("animationend",this._onFallDone);u.off("animationend",this._onUglyDone);s_oStage.removeChild(m)};this.getRandomAction=function(){y.clearTimer();
h[Math.floor(Math.random()*h.length)]()};this.resetAnim=function(){d.visible=!1;d.stop();(void 0)[g]();g++;g===(void 0).length&&(g=0)};this.fail=function(){d.stop();d.visible=!1;d=n;d.visible=!0;d.gotoAndPlay("idle");l=4};this.getSock=function(){d.stop();d.visible=!1;d=p;d.visible=!0;d.gotoAndPlay("idle");l=2};this.getUp=function(){d.stop();d.visible=!1;d=q;d.visible=!0;d.gotoAndPlay("idle");l=3;s_oGame.moveObj("getUp")};this.normal=function(){d.stop();d.visible=!1;d=w;d.visible=!0;d.gotoAndPlay("idle");
if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)B=createjs.Sound.play("sd_keyBoard",{loop:-1});l=0;y.setDelay(y.onNormalDone,8,3)};this.onNormalDone=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||B.stop();y.getRandomAction()};this.shake=function(){d.stop();d.visible=!1;d=z;d.visible=!0;d.gotoAndPlay("idle");l=3};this.stupid=function(){d.stop();d.visible=!1;d=t;d.visible=!0;d.gotoAndPlay("idle");l=1;y.setDelay(y.getRandomAction,8,3)};this.ugly=function(){d.stop();d.visible=!1;d=u;d.visible=!0;
d.gotoAndPlay("idle");c=!0;l=6};this.win=function(){d.stop();d.visible=!1;d=r;d.visible=!0;d.gotoAndPlay("idle");y.clearTimer();l=5};this.doThings=function(){3===l&&s_oGame.addSmoke();4!==l&&(s_oGame.bossCheckState()&&6!==l&&!c?(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||B.stop(),y.clearTimer(),y.ugly()):3!==l&&3!==l&&4!==l&&2!==l&&3!==l&&s_oGame.cupVisible()?(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||B.stop(),c=!1,y.clearTimer(),s_oGame.moveObj("shakeUp"),y.shake()):s_oGame.bossCheckDir()&&s_oGame.cupVisible()&&
(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||B.stop(),s_oGame.onDied()))};this.cancelAction=function(){s_oGame.removeSmoke();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||A.stop();3===l||3===l||2===l||3===l?(s_oGame.moveObj("hide"),f=0,k=2,s_oGame.setObj(k),s_oGame.clearCoffeeBar(),y.clearTimer(),y.getRandomAction()):c&&(c=!1)};this._onFinding=function(){"idle1"===d.currentAnimation&&y.getUp()};this._onShake=function(){"idle"===d.currentAnimation?(s_oGame.moveObj("shakeDown"),f++,!1!==DISABLE_SOUND_MOBILE&&
!1!==s_bMobile||createjs.Sound.play("sd_put"),s_oGame.refreshCoffeeBar(f),1===f%10&&(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||A.play()),s_oGame.setScore(f),0===f%10&&(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||A.stop(),y.getSock(),s_oGame.moveObj("hide"),k++,6<k&&(k=6),s_oGame.setObj(k))):s_oGame.moveObj("shakeUp")};this._onGetUp=function(){"idle8"===d.currentAnimation&&(y.shake(),s_oGame.moveObj("shakeUp"))};this._onFallDone=function(){"idle1"===d.currentAnimation&&d.stop()};this._onUglyDone=function(){y.getRandomAction()};
this.onDied=function(){y.clearTimer();y.fail()};this.setDelay=function(a,d,c){d*=Math.random();d<=c&&(d=c);b=setTimeout(a,1E3*d)};this.clearTimer=function(){clearTimeout(b)};y=this;this._init(a,e)}
function CMenu(){var a,e,c,g,b,f,l,k,h,m;this._init=function(){0===localStorage.length&&(localStorage.setItem(0,JSON.stringify({name:"Receptionist1",score:9E3})),localStorage.setItem(1,JSON.stringify({name:"Receptionist2",score:7500})),localStorage.setItem(2,JSON.stringify({name:"Receptionist3",score:5E3})),localStorage.setItem(3,JSON.stringify({name:"Receptionist4",score:3500})),localStorage.setItem(4,JSON.stringify({name:"Receptionist5",score:2E3})),localStorage.setItem(5,JSON.stringify({name:"Receptionist6",
score:1E3})),localStorage.setItem(6,JSON.stringify({name:"Receptionist7",score:600})),localStorage.setItem(7,JSON.stringify({name:"Receptionist8",score:300})),localStorage.setItem(8,JSON.stringify({name:"Receptionist9",score:200})),localStorage.setItem(9,JSON.stringify({name:"Receptionist10",score:100})),localStorage.setItem("bestscore",0));c=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(c);var d=s_oSpriteLibrary.getSprite("but_play");g=new CAnimButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-
260,d,TEXT_PLAY,"Arial Black","#ffffff",24,200,50);g.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);g.setTextPosition(10);d=s_oSpriteLibrary.getSprite("but_play");b=new CAnimButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-200,d,TEXT_HIGH,"Arial Black","#ffffff",24,200,50);b.addEventListener(ON_MOUSE_UP,this._onButStatsRelease,this);b.setTextPosition(10);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)d=s_oSpriteLibrary.getSprite("audio_icon"),a=CANVAS_WIDTH-d.height/2-50,e=d.height/2+400,k=new CToggle(a,
e,d,s_bAudioActive),k.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);this._attachSpilGamesLogo();this._attachMoreGameButton();l=new createjs.Shape;l.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(l);createjs.Tween.get(l).to({alpha:0},1E3).call(function(){l.visible=!1});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){g.unload();g=null;b.unload();b=null;f.unload();f=null;l.visible=!1;s_oStage.removeChild(h);s_oStage.removeChild(m);
if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)k.unload(),k=null;s_oStage.removeChild(c);s_oMenu=c=null};this.refreshButtonPos=function(b,c){k.setPosition(a-b,c+e)};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onButPlayRelease=function(){this.unload();s_oMain.gotoGame()};this._onButStatsRelease=function(){this.unload();new CBestScore(0)};this._attachSpilGamesLogo=function(){var a=s_oApiInstance.Branding.getLogo();if(a.image){h=new createjs.Bitmap(a.image);
h.x=0;h.y=CANVAS_HEIGHT-70;s_oStage.addChild(h);var b=this;h.image.onload=function(){b._onAddLogoBut(a)}}};this._onAddLogoBut=function(a){var b=(new createjs.Graphics).beginFill("rgba(0,0,0,0.01)").drawRect(h.x,h.y,h.getBounds().width,h.getBounds().height);m=new createjs.Shape(b);m.on("click",a.action);s_oStage.addChild(m)};this._attachMoreGameButton=function(){var a=s_oApiInstance.Branding.getLink("more_games"),b=s_oSpriteLibrary.getSprite("but_redir");f=new CAnimButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-
100,b,TEXT_MORE,"Arial Black","#ffffff",24,200,90);f.addEventListener(ON_MOUSE_UP,a.action,this);f.setTextPosition(7)};s_oMenu=this;this._init()}var s_oMenu=null;
function CMain(a,e){var c,g=0,b=0,f=STATE_LOADING,l,k,h;this.initContainer=function(){s_oCanvas=document.getElementById("canvas");s_oStage=new createjs.Stage(s_oCanvas);createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&(s_oStage.enableMouseOver(20),$("body").on("contextmenu","#canvas",function(a){return!1}));s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.setFPS(FPS);navigator.userAgent.match(/Windows Phone/i)&&(DISABLE_SOUND_MOBILE=
!0);s_oSpriteLibrary=new CSpriteLibrary;k=new CPreloader};this.preloaderReady=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();this._loadImages();c=!0};this.soundLoaded=function(){g++;k.refreshLoader(Math.floor(g/b*100));g===b&&(k.unload(),this.gotoMenu())};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&(0<navigator.userAgent.indexOf("Opera")||0<navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=["m4a"],createjs.Sound.addEventListener("fileload",
createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/sd_bg.ogg","sd_bg"),createjs.Sound.registerSound("./sounds/sd_catch.ogg","sd_catch"),createjs.Sound.registerSound("./sounds/sd_copyCat.ogg","sd_copyCat"),createjs.Sound.registerSound("./sounds/sd_dance.ogg","sd_dance"),createjs.Sound.registerSound("./sounds/sd_double.ogg","sd_double"),createjs.Sound.registerSound("./sounds/sd_down.ogg","sd_down"),createjs.Sound.registerSound("./sounds/sd_drink.ogg","sd_drink"),createjs.Sound.registerSound("./sounds/sd_fear.ogg",
"sd_fear"),createjs.Sound.registerSound("./sounds/sd_get.ogg","sd_get"),createjs.Sound.registerSound("./sounds/sd_ha.ogg","sd_ha"),createjs.Sound.registerSound("./sounds/sd_keyBoard.ogg","sd_keyBoard"),createjs.Sound.registerSound("./sounds/sd_on.ogg","sd_on"),createjs.Sound.registerSound("./sounds/sd_put.ogg","sd_put"),createjs.Sound.registerSound("./sounds/sd_sb.ogg","sd_sb"),createjs.Sound.registerSound("./sounds/sd_Score.ogg","sd_Score"),createjs.Sound.registerSound("./sounds/sd_smokeIn.ogg",
"sd_smokeIn"),createjs.Sound.registerSound("./sounds/sd_smokeOut.ogg","sd_smokeOut"),createjs.Sound.registerSound("./sounds/sd_turn.ogg","sd_turn"),createjs.Sound.registerSound("./sounds/sd_ugly.ogg","sd_ugly")):(createjs.Sound.alternateExtensions=["ogg"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/sd_bg.mp3","sd_bg"),createjs.Sound.registerSound("./sounds/sd_catch.mp3","sd_catch"),createjs.Sound.registerSound("./sounds/sd_copyCat.mp3",
"sd_copyCat"),createjs.Sound.registerSound("./sounds/sd_dance.mp3","sd_dance"),createjs.Sound.registerSound("./sounds/sd_double.mp3","sd_double"),createjs.Sound.registerSound("./sounds/sd_down.mp3","sd_down"),createjs.Sound.registerSound("./sounds/sd_drink.mp3","sd_drink"),createjs.Sound.registerSound("./sounds/sd_fear.mp3","sd_fear"),createjs.Sound.registerSound("./sounds/sd_get.mp3","sd_get"),createjs.Sound.registerSound("./sounds/sd_ha.mp3","sd_ha"),createjs.Sound.registerSound("./sounds/sd_keyBoard.mp3",
"sd_keyBoard"),createjs.Sound.registerSound("./sounds/sd_on.mp3","sd_on",5),createjs.Sound.registerSound("./sounds/sd_put.mp3","sd_put"),createjs.Sound.registerSound("./sounds/sd_sb.mp3","sd_sb"),createjs.Sound.registerSound("./sounds/sd_Score.mp3","sd_Score"),createjs.Sound.registerSound("./sounds/sd_smokeIn.mp3","sd_smokeIn"),createjs.Sound.registerSound("./sounds/sd_smokeOut.mp3","sd_smokeOut"),createjs.Sound.registerSound("./sounds/sd_turn.mp3","sd_turn"),createjs.Sound.registerSound("./sounds/sd_ugly.mp3",
"sd_ugly")),b+=7)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("button","./sprites/button.png");s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("but_redir","./sprites/but_redir.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.png");s_oSpriteLibrary.addSprite("bg_help",
"./sprites/bg_help.png");s_oSpriteLibrary.addSprite("bg_help_mob","./sprites/bg_help_mob.png");s_oSpriteLibrary.addSprite("end_panel_bg","./sprites/end_panel_bg.png");s_oSpriteLibrary.addSprite("end_panel_0","./sprites/end_panel_0.png");s_oSpriteLibrary.addSprite("end_panel_1","./sprites/end_panel_1.png");s_oSpriteLibrary.addSprite("end_panel_2","./sprites/end_panel_2.png");s_oSpriteLibrary.addSprite("end_panel_icon_1","./sprites/end_panel_icon_1.png");s_oSpriteLibrary.addSprite("end_panel_icon_2",
"./sprites/end_panel_icon_2.png");s_oSpriteLibrary.addSprite("best_score_panel","./sprites/best_score_panel.png");s_oSpriteLibrary.addSprite("explode","./sprites/explode.png");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("timer","./sprites/timer.png");s_oSpriteLibrary.addSprite("hour","./sprites/timer_line_2.png");s_oSpriteLibrary.addSprite("minute","./sprites/timer_line.png");s_oSpriteLibrary.addSprite("life_glass",
"./sprites/life_glass.png");s_oSpriteLibrary.addSprite("life_bar","./sprites/life_bar.png");s_oSpriteLibrary.addSprite("life_bar_buffer","./sprites/life_bar_buffer.png");s_oSpriteLibrary.addSprite("life_bar_mask","./sprites/life_bar_mask.png");s_oSpriteLibrary.addSprite("coffee_glass","./sprites/coffee_glass.png");s_oSpriteLibrary.addSprite("coffee_bar","./sprites/coffee_bar.png");s_oSpriteLibrary.addSprite("coffee_bar_energy","./sprites/coffee_bar_energy.png");s_oSpriteLibrary.addSprite("highlight",
"./sprites/highlight.png");s_oSpriteLibrary.addSprite("particle_coffee","./sprites/particle_coffee.png");s_oSpriteLibrary.addSprite("plate","./sprites/plate.png");s_oSpriteLibrary.addSprite("cup","./sprites/cup.png");s_oSpriteLibrary.addSprite("cupcover","./sprites/cupcover.png");s_oSpriteLibrary.addSprite("empl_obj","./sprites/empl_obj.png");s_oSpriteLibrary.addSprite("printer","./sprites/printer.png");s_oSpriteLibrary.addSprite("boss_amaze","./sprites/boss/boss_amaze.png");s_oSpriteLibrary.addSprite("boss_crazy",
"./sprites/boss/boss_crazy.png");s_oSpriteLibrary.addSprite("boss_dance","./sprites/boss/boss_dance.png");s_oSpriteLibrary.addSprite("boss_drink","./sprites/boss/boss_drink.png");s_oSpriteLibrary.addSprite("boss_drink_D","./sprites/boss/boss_drink_D.png");s_oSpriteLibrary.addSprite("boss_look_lady","./sprites/boss/boss_look_lady.png");s_oSpriteLibrary.addSprite("boss_midd_state","./sprites/boss/boss_midd_state.png");s_oSpriteLibrary.addSprite("boss_pull_back","./sprites/boss/boss_pull_back.png");
s_oSpriteLibrary.addSprite("boss_shout","./sprites/boss/boss_shout.png");s_oSpriteLibrary.addSprite("boss_smoke","./sprites/boss/boss_smoke.png");s_oSpriteLibrary.addSprite("boss_talk","./sprites/boss/boss_talk.png");s_oSpriteLibrary.addSprite("boss_talk_to_lady","./sprites/boss/boss_talk_to_lady.png");s_oSpriteLibrary.addSprite("boss_turn_back","./sprites/boss/boss_turn_back.png");s_oSpriteLibrary.addSprite("boss_ugly","./sprites/boss/boss_ugly.png");s_oSpriteLibrary.addSprite("boss_wz","./sprites/boss/boss_wz.png");
s_oSpriteLibrary.addSprite("secretary_afraid","./sprites/secretary/secretary_afraid.png");s_oSpriteLibrary.addSprite("secretary_check_copy","./sprites/secretary/secretary_check_copy.png");s_oSpriteLibrary.addSprite("secretary_laugh","./sprites/secretary/secretary_laugh.png");s_oSpriteLibrary.addSprite("secretary_look_boss","./sprites/secretary/secretary_look_boss.png");s_oSpriteLibrary.addSprite("secretary_shine","./sprites/secretary/secretary_shine.png");s_oSpriteLibrary.addSprite("secretary_stand",
"./sprites/secretary/secretary_stand.png");s_oSpriteLibrary.addSprite("secretary_talk","./sprites/secretary/secretary_talk.png");s_oSpriteLibrary.addSprite("secretary_turn_around","./sprites/secretary/secretary_turn_around.png");s_oSpriteLibrary.addSprite("employee_fail","./sprites/employee/employee_fail.png");s_oSpriteLibrary.addSprite("employee_get_sock","./sprites/employee/employee_get_sock.png");s_oSpriteLibrary.addSprite("employee_get_up","./sprites/employee/employee_get_up.png");s_oSpriteLibrary.addSprite("employee_normal",
"./sprites/employee/employee_normal.png");s_oSpriteLibrary.addSprite("employee_shake","./sprites/employee/employee_shake.png");s_oSpriteLibrary.addSprite("employee_stupid","./sprites/employee/employee_stupid.png");s_oSpriteLibrary.addSprite("employee_ugly","./sprites/employee/employee_ugly.png");s_oSpriteLibrary.addSprite("employee_win","./sprites/employee/employee_win.png");b+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){g++;k.refreshLoader(Math.floor(g/
b*100));g===b&&(k.unload(),this.gotoMenu())};this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this.gotoMenu=function(){new CMenu;f=STATE_MENU};this.gotoGame=function(a){s_bEasyMode=a;h=new CGame(l);f=STATE_GAME;$(s_oMain).trigger("game_start")};this.gotoHelp=function(){new CHelp;f=STATE_HELP};this.stopUpdate=function(){c=!1};this.startUpdate=function(){c=!0};this.playAllSounds=function(a){createjs.Sound.setMute(!a)};this._update=function(a){if(!1!==
c){var b=(new Date).getTime();s_iTimeElaps=b-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=b;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);f===STATE_GAME&&h.update();s_oStage.update(a)}};s_oMain=this;l=a;s_oApiInstance=e;this.initContainer()}var s_bMobile,s_bEasyMode,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oApiInstance,s_oDrawLayer,s_oStage,s_oMain=null,s_oSpriteLibrary,s_oCanvas;