function CSpriteLibrary(){var c,a,b,d,f,e;this.init=function(l,p,t){b=a=0;d=l;f=p;e=t;c={}};this.addSprite=function(d,b){c.hasOwnProperty(d)||(c[d]={szPath:b,oSprite:new Image},a++)};this.getSprite=function(d){return c.hasOwnProperty(d)?c[d].oSprite:null};this._onSpritesLoaded=function(){f.call(e)};this._onSpriteLoaded=function(){d.call(e);++b===a&&this._onSpritesLoaded()};this.loadSprites=function(){for(var d in c)c[d].oSprite.oSpriteLibrary=this,c[d].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
c[d].oSprite.src=c[d].szPath};this.getNumSprites=function(){return a}}
var CANVAS_WIDTH=768,CANVAS_HEIGHT=1024,DISABLE_SOUND_MOBILE=!0,STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,BALL_SIZE=150,BALL_BOUNCE_YOFFSET=100,SHADOW_WIDTH=150,SHADOW_HEIGHT=64,INIT_GRAVITY_NORMAL,INIT_BALLMASS_NORMAL,FRICTION_NORMAL,EDGEFRICTION_NORMAL,ROTATIONSPEED_NORMAL,HORIZ_KICKFORCE_NORMAL,VERT_KICKFORCE_NORMAL,RESTITUTION_KICKFORCE_NORMAL,INIT_GRAVITY_CHALLENGE,INIT_BALLMASS_CHALLENGE,
FRICTION_CHALLENGE,EDGEFRICTION_CHALLENGE,ROTATIONSPEED_CHALLENGE,HORIZ_KICKFORCE_CHALLENGE,VERT_KICKFORCE_CHALLENGE,RESTITUTION_KICKFORCE_CHALLENGE,GRAVITY_INCREASE;
function CVector2(c,a){var b,d;this._init=function(a,c){b=a;d=c};this.add=function(a,c){b+=a;d+=c};this.addV=function(a){b+=a.getX();d+=a.getY()};this.scalarDivision=function(a){b/=a;d/=a};this.subV=function(a){b-=a.getX();d-=a.getY()};this.scalarProduct=function(a){b*=a;d*=a};this.invert=function(){b*=-1;d*=-1};this.dotProduct=function(a){return b*a.getX()+d*a.getY()};this.set=function(a,c){b=a;d=c};this.setV=function(a){b=a.getX();d=a.getY()};this.length=function(){return Math.sqrt(b*b+d*d)};this.length2=
function(){return b*b+d*d};this.normalize=function(){var a=this.length();0<a&&(b/=a,d/=a)};this.getNormalize=function(a){this.length();a.set(b,d);a.normalize()};this.rot90CCW=function(){var a=b;b=-d;d=a};this.rot90CW=function(){var a=b;b=d;d=-a};this.getRotCCW=function(a){a.set(b,d);a.rot90CCW()};this.getRotCW=function(a){a.set(b,d);a.rot90CW()};this.ceil=function(){b=Math.ceil(b);d=Math.ceil(d)};this.round=function(){b=Math.round(b);d=Math.round(d)};this.toString=function(){return"Vector2: "+b+", "+
d};this.print=function(){trace("Vector2: "+b+", "+d+"")};this.getX=function(){return b};this.getY=function(){return d};this._init(c,a)}
function CToggle(c,a,b){var d,f,e;this._init=function(a,b,c){d=[];f=[];c=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{on:[0,1],off:[1,2]}});e=s_bAudioActive?new createjs.Sprite(c,"on"):new createjs.Sprite(c,"off");e.x=a;e.y=b;e.stop();s_oStage.addChild(e);this._initListener()};this.unload=function(){e.off("mousedown",this.buttonDown);e.off("pressup",this.buttonRelease);s_oStage.removeChild(e)};this._initListener=function(){e.on("mousedown",
this.buttonDown);e.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){d[a]=b;f[a]=c};this.buttonRelease=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("press_but");e.scaleX=1;e.scaleY=1;(s_bAudioActive=!s_bAudioActive)?e.gotoAndStop("on"):e.gotoAndStop("off");d[ON_MOUSE_UP]&&d[ON_MOUSE_UP].call(f[ON_MOUSE_UP])};this.buttonDown=function(){e.scaleX=.9;e.scaleY=.9;d[ON_MOUSE_DOWN]&&d[ON_MOUSE_DOWN].call(f[ON_MOUSE_DOWN])};this._init(c,a,b)}
(function(c){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(c)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(c.substr(0,
4))})(navigator.userAgent||navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(c){console.log(c)}$(window).ready(function(){sizeHandler()});window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}

function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a=CANVAS_WIDTH,b=CANVAS_HEIGHT,c,d;!0===inIframe()&&"ios"==getMobileOperatingSystem()?top.location.href=document.location.href:(c=window.innerWidth,d=window.innerHeight,console.log("h: "+d),multiplier=Math.min(d/b,c/a),a*=multiplier,b*=multiplier,$("#canvas").css("width",a+"px"),$("#canvas").css("height",b+"px"),$("#canvas").css("left",c/2-a/2+"px"))}}
function getMobileOperatingSystem(){var a=navigator.userAgent||navigator.vendor||window.opera;return a.match(/iPad/i)||a.match(/iPhone/i)||a.match(/iPod/i)?"ios":a.match(/Android/i)?"android":"unknown"}function inIframe(){try{return window.self!==window.top}catch(a){return!0}};

function randomFloatBetween(c,a,b){"undefined"===typeof b&&(b=2);return parseFloat(Math.min(c+Math.random()*(a-c),a).toFixed(b))}
function shuffle(c){for(var a=c.length,b,d;0!==a;)d=Math.floor(Math.random()*a),a-=1,b=c[a],c[a]=c[d],c[d]=b;return c}function formatTime(c){c/=1E3;var a=Math.floor(c/60);c=Math.floor(c-60*a);var b="",b=10>a?b+("0"+a+":"):b+(a+":");return b=10>c?b+("0"+c):b+c}
Array.prototype.sortOn=function(){var c=this.slice();if(!arguments.length)return c.sort();var a=Array.prototype.slice.call(arguments);return c.sort(function(b,d){for(var c=a.slice(),e=c.shift();b[e]==d[e]&&c.length;)e=c.shift();return b[e]==d[e]?0:b[e]>d[e]?1:-1})};function roundDecimal(c,a){var b=Math.pow(10,a);return Math.round(b*c)/b}function tweenVectors(c,a,b,d){d.set(c.getX()+b*(a.getX()-c.getX()),c.getY()+b*(a.getY()-c.getY()));return d}
function NoClickDelay(c){this.element=c;window.Touch&&this.element.addEventListener("touchstart",this,!1)}
NoClickDelay.prototype={handleEvent:function(c){switch(c.type){case "touchstart":this.onTouchStart(c);break;case "touchmove":this.onTouchMove(c);break;case "touchend":this.onTouchEnd(c)}},onTouchStart:function(c){c.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(c){this.moved=!0},onTouchEnd:function(c){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){c=document.elementFromPoint(c.changedTouches[0].clientX,c.changedTouches[0].clientY);3===c.nodeType&&(c=c.parentNode);var a=document.createEvent("MouseEvents");a.initEvent("click",!0,!0);c.dispatchEvent(a)}}};
function CTextButton(c,a,b,d,f,e,l,p){var t,k,u,g,s,h,r,m,q,n;this._init=function(a,d,b,c,e,l,f,p){t=!1;g=[];s=[];n=p;r=new createjs.Bitmap(b);k=b.width;u=b.height;p=Math.ceil(f/20);m=new createjs.Text(c,"bold "+f+"px "+e,"#000000");var y=m.getBounds();m.textAlign="center";m.textBaseline="alphabetic";m.x=b.width/2+p;m.y=Math.floor(b.height/2)+y.height/3+p;q=new createjs.Text(c,"bold "+f+"px "+e,l);q.textAlign="center";q.textBaseline="alphabetic";q.x=b.width/2;q.y=Math.floor(b.height/2)+y.height/3;
h=new createjs.Container;h.x=a;h.y=d;h.regX=b.width/2;h.regY=b.height/2;h.addChild(r,m,q);n.addChild(h);this._initListener()};this.unload=function(){h.off("mousedown");h.off("pressup");n.removeChild(h)};this.setVisible=function(a){h.visible=a};this.enable=function(){t=!1;r.filters=[];r.cache(0,0,k,u)};this.disable=function(){t=!0;var a=(new createjs.ColorMatrix).adjustSaturation(-100);r.filters=[new createjs.ColorMatrixFilter(a)];r.cache(0,0,k,u)};this._initListener=function(){oParent=this;h.on("mousedown",
this.buttonDown);h.on("pressup",this.buttonRelease)};this.addEventListener=function(a,d,b){g[a]=d;s[a]=b};this.buttonRelease=function(){t||(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("press_but"),h.scaleX=1,h.scaleY=1,g[ON_MOUSE_UP]&&g[ON_MOUSE_UP].call(s[ON_MOUSE_UP]))};this.buttonDown=function(){t||(h.scaleX=.9,h.scaleY=.9,g[ON_MOUSE_DOWN]&&g[ON_MOUSE_DOWN].call(s[ON_MOUSE_DOWN]))};this.setPosition=function(a,d){h.x=a;h.y=d};this.changeText=function(a){q.text=a;m.text=a};this.setX=
function(a){h.x=a};this.setY=function(a){h.y=a};this.getButtonImage=function(){return h};this.getX=function(){return h.x};this.getY=function(){return h.y};this._init(c,a,b,d,f,e,l,p);return this}
function CPreloader(){var c;this._init=function(){this._onAllPreloaderImagesLoaded()};this._onPreloaderImagesLoaded=function(){};this._onAllPreloaderImagesLoaded=function(){c=new createjs.Text("","bold 22px Arial center","#ffffff");c.x=CANVAS_WIDTH/2-40;c.y=CANVAS_HEIGHT/2;s_oStage.addChild(c)};this.unload=function(){s_oStage.removeChild(c)};this.refreshLoader=function(a){c.text=a+"%"};this._init()}
CPlayer=function(){var c=!1,a;this.display=function(b,d){if(!c){c=!0;var f,e,l,p;d>=8*CANVAS_HEIGHT/10?(a=new createjs.Bitmap(s_oSpriteLibrary.getSprite("player_1")),a.regX=16,a.regY=720,a.alpha=0,e=d,p=d-BALL_SIZE/4,b>=CANVAS_WIDTH/2?(l=f=b,a.scaleX=-1):l=f=b):d>=7*CANVAS_HEIGHT/10?(a=new createjs.Bitmap(s_oSpriteLibrary.getSprite("player_2")),a.regX=28,a.regY=675,a.alpha=0,e=d,p=d-BALL_SIZE/4,b>=CANVAS_WIDTH/2?(l=f=b,a.scaleX=-1):l=f=b):d>=6*CANVAS_HEIGHT/10?(a=new createjs.Bitmap(s_oSpriteLibrary.getSprite("player_4")),
a.regX=440,a.regY=410,a.alpha=0,e=d,p=d-BALL_SIZE/2,b>=CANVAS_WIDTH/2?l=f=b:(l=f=b,a.scaleX=-1)):d>=4*CANVAS_HEIGHT/10?(a=new createjs.Bitmap(s_oSpriteLibrary.getSprite("player_3")),a.regX=51,a.regY=358,a.alpha=0,e=d,p=d-BALL_SIZE/2,b>=CANVAS_WIDTH/2?(l=f=b,a.scaleX=-1):l=f=b):d>=3*CANVAS_HEIGHT/10?(a=new createjs.Bitmap(s_oSpriteLibrary.getSprite("player_5")),a.regX=196,a.regY=132,a.alpha=0,e=d,p=d-BALL_SIZE/2,b>=CANVAS_WIDTH/2?l=f=b:(l=f=b,a.scaleX=-1)):d>=0*CANVAS_HEIGHT/10&&(a=new createjs.Bitmap(s_oSpriteLibrary.getSprite("player_7")),
a.regX=229,a.regY=3,a.alpha=0,e=d,p=d-BALL_SIZE/2,b>=CANVAS_WIDTH/2?l=f=b:(l=f=b,a.scaleX=-1));a.x=f;a.y=e;s_oStage.addChildAt(a,s_oStage.children.length-2);createjs.Tween.get(a).to({x:l,y:p,alpha:1},100,createjs.Ease.cubicIn).wait(25).call(function(){createjs.Tween.get(a).to({x:f,y:e,alpha:0},375,createjs.Ease.circIn).call(function(){c=!1;s_oStage.removeChild(a)})})}}};
function CMenu(){var c,a,b,d,f;this._init=function(){c=new createjs.Bitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(c);var e=s_oSpriteLibrary.getSprite("but_play");a=new CTextButton(CANVAS_WIDTH/2-170,CANVAS_HEIGHT-70,e,TEXT_PLAY,"Verdana","#ffffff",30,s_oStage);a.addEventListener(ON_MOUSE_UP,this._onButPlay,this,!1);b=new CTextButton(CANVAS_WIDTH/2+170,CANVAS_HEIGHT-70,e,TEXT_PLAYCHALLENGE,"Verdana","#ffffff",30,s_oStage);b.addEventListener(ON_MOUSE_UP,this._onButPlayChallenge,this);
if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)e=s_oSpriteLibrary.getSprite("audio_icon"),d=new CToggle(CANVAS_WIDTH-e.width/2+5,e.height/2+20,e),d.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this),null===s_oSoundTrack&&(s_oSoundTrack=createjs.Sound.play("soundtrack",{loop:-1,volume:.7}));f=new createjs.Shape;f.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(f);createjs.Tween.get(f).to({alpha:0},1E3).call(function(){f.visible=!1})};this.unload=function(){a.unload();
a=null;b.unload();b=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)d.unload(),d=null;s_oStage.removeAllChildren()};this._onButPlay=function(){this.unload();s_oMain.gotoGame(!1)};this._onButPlayChallenge=function(){this.unload();s_oMain.gotoGame(!0)};this._onAudioToggle=function(){createjs.Sound.setMute(!s_bAudioActive)};this._init()}
function CMain(c){var a=0,b=0,d=STATE_LOADING,f,e;this.initContainer=function(a){INIT_GRAVITY_NORMAL=a.gravity;INIT_BALLMASS_NORMAL=a.ballMass;FRICTION_NORMAL=a.friction;EDGEFRICTION_NORMAL=a.edgeFriction;ROTATIONSPEED_NORMAL=a.rotationSpeed;HORIZ_KICKFORCE_NORMAL=a.horizKickForce;VERT_KICKFORCE_NORMAL=a.vertKickForce;RESTITUTION_KICKFORCE_NORMAL=a.restitutionKickForce;INIT_GRAVITY_CHALLENGE=a.chGravity;INIT_BALLMASS_CHALLENGE=a.chBallMass;FRICTION_CHALLENGE=a.chFriction;EDGEFRICTION_CHALLENGE=a.chEdgeFriction;
ROTATIONSPEED_CHALLENGE=a.chRotationSpeed;HORIZ_KICKFORCE_CHALLENGE=a.chHorizKickForce;VERT_KICKFORCE_CHALLENGE=a.chVertKickForce;RESTITUTION_KICKFORCE_CHALLENGE=a.chRestitutionKickForce;GRAVITY_INCREASE=a.chGravityIncrease;s_oStage=new createjs.Stage("canvas");createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&s_oStage.enableMouseOver(20);s_iPrevTime=(new Date).getTime();createjs.Ticker.setFPS(30);createjs.Ticker.addEventListener("tick",this._update);!1!==DISABLE_SOUND_MOBILE&&
!1!==s_bMobile||this._initSounds();s_oSpriteLibrary=new CSpriteLibrary;f=new CPreloader;this._loadImages()};this.soundLoaded=function(){a++;a===b&&(f.unload(),this.gotoMenu())};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&(0<navigator.userAgent.indexOf("Opera")||0<navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=["mp3"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/reset_kickup.ogg",
"reset_kickup"),createjs.Sound.registerSound("./sounds/soundtrack.ogg","soundtrack"),createjs.Sound.registerSound("./sounds/tap.ogg","tap")):(createjs.Sound.alternateExtensions=["ogg"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/reset_kickup.mp3","reset_kickup"),createjs.Sound.registerSound("./sounds/soundtrack.mp3","soundtrack"),createjs.Sound.registerSound("./sounds/tap.mp3","tap")),b+=3)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,
this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("ball_1","./sprites/ball_1.png");s_oSpriteLibrary.addSprite("ball_2","./sprites/ball_2.png");s_oSpriteLibrary.addSprite("ball_3","./sprites/ball_3.png");s_oSpriteLibrary.addSprite("ball_hit","./sprites/ball_hit.png");s_oSpriteLibrary.addSprite("shadow","./sprites/shadow.png");s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("bg_help",
"./sprites/bg_help.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("panel","./sprites/msg_box.png");for(var a=1;7>=a;a++)s_oSpriteLibrary.addSprite("player_"+a,"./sprites/player_sprite_"+a+".png");b+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){a++;f.refreshLoader(Math.floor(a/
b*100));a===b&&(f.unload(),this.gotoMenu())};this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this.gotoMenu=function(){new CMenu;d=STATE_MENU};this.gotoGame=function(a){e=new CGame(a);d=STATE_GAME;$(s_oMain).trigger("game_start")};this.gotoHelp=function(){_oHelp=new CHelp;d=STATE_HELP};this._update=function(a){var b=(new Date).getTime();s_iTimeElaps=b-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=b;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,
s_iCntTime-=1E3,s_iCntFps=0);d===STATE_GAME&&e.update();s_oStage.update(a)};s_oMain=this;this.initContainer(c)}var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oSoundTrack=null,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oGameSettings;TEXT_GAMEOVER="GAME OVER";TEXT_PLAY="NORMAL";TEXT_PLAYCHALLENGE="CHALLENGE";TEXT_SCORE="SCORE: ";TEXT_HISCORE="TOP SCORE: ";TEXT_NEWHISCORE="NEW RECORD!!";TEXT_GRAVITY="GRAVITY: ";TEXT_HIGRAVITY="TOP GRAVITY: ";
TEXT_NEWHIGRAVITY="NEW HIGHEST GRAVITY!!";TEXT_SUPPORT_STRINGS=4;TEXT_SUPPORT=["GREAT!","CHAMPION!","LIKE A BOSS!!","KEEP CALM AND KICK UP!"];
function CInterface(c,a){var b,d=!1,f,e,l,p,t,k,u,g;this._init=function(a,d){b=a;f=d;e=new createjs.Bitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(e);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile){var c=s_oSpriteLibrary.getSprite("audio_icon");l=new CToggle(CANVAS_WIDTH-c.width/2-35,c.height/2+15,c);l.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this)}c=s_oSpriteLibrary.getSprite("but_exit");t=new CGfxButton(CANVAS_WIDTH-c.width/2+5,c.height/2+8,c);t.addEventListener(ON_MOUSE_UP,
this._onExit,this);if(f)c=TEXT_NEWHIGRAVITY,m=TEXT_GRAVITY+INIT_GRAVITY_CHALLENGE,q=TEXT_HIGRAVITY+0;else var c=TEXT_NEWHISCORE,m=TEXT_SCORE+0,q=TEXT_HISCORE+0;g=new createjs.Text(c,"bold 24px Verdana","Orange");g.x=CANVAS_WIDTH/2;g.y=200;g.textBaseline="alphabetic";g.textAlign="center";g.shadow=new createjs.Shadow("#000000",2,2,2);g.visible=!1;k=new createjs.Text(m,"bold 60px Verdana","#5b8e2d");k.x=20;k.y=65;k.textBaseline="alphabetic";k.textAlign="left";k.shadow=new createjs.Shadow("#000000",3,
3,2);u=new createjs.Text(q,"bold 24px Verdana","#fff");u.x=CANVAS_WIDTH/2;u.y=CANVAS_HEIGHT-40;u.textBaseline="alphabetic";u.textAlign="center";u.shadow=new createjs.Shadow("#000000",2,2,2);s_oStage.addChild(g,k,u);p=new createjs.Shape;p.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(p);createjs.Tween.get(p).to({alpha:0},1E3).call(function(){p.visible=!1})};this.unload=function(){s_oStage.removeChild(e,g,k,u);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||l.unload();
t.unload()};this.updateScore=function(a,d){if(f)b=TEXT_GRAVITY+(0===a?INIT_GRAVITY_CHALLENGE:a),k.text=b,b=TEXT_HIGRAVITY+d;else{var b=TEXT_SCORE+a;k.text=b;b=TEXT_HISCORE+d}u.text=b};this.newTopScore=function(){!1===d&&(d=!0,g.text=TEXT_NEWHISCORE,g.x=-200,g.alpha=.5,g.visible=!0,g.color="Orange",createjs.Tween.get(g).to({x:CANVAS_WIDTH/2,scaleX:1.5,scaleY:1.5,alpha:1},750,createjs.Ease.backInOut).wait(500).call(function(){createjs.Tween.get(g).to({x:CANVAS_WIDTH+200,scaleX:1,scaleY:1,alpha:.5},
750,createjs.Ease.backInOut).call(function(){d=g.visible=!1})}))};this.encouragement=function(){if(!1===d){var a=Math.floor(Math.random()*(TEXT_SUPPORT_STRINGS+1));d=!0;g.text=TEXT_SUPPORT[a];g.x=-200;g.alpha=.5;g.visible=!0;g.color="#fcd000";createjs.Tween.get(g).to({x:CANVAS_WIDTH/2,scaleX:1.5,scaleY:1.5,alpha:1},750,createjs.Ease.backInOut).wait(500).call(function(){createjs.Tween.get(g).to({x:CANVAS_WIDTH+200,scaleX:1,scaleY:1,alpha:.5},750,createjs.Ease.backInOut).call(function(){d=g.visible=
!1})})}};this._onExit=function(){this.unload();b.unload();$(s_oMain).trigger("restart")};this._onAudioToggle=function(){createjs.Sound.setMute(!s_bAudioActive)};this._init(c,a)}
function CGfxButton(c,a,b){var d,f,e,l,p,t=[],k;this._init=function(a,b,c){d=!1;l=[];p=[];f=c.width;e=c.height;k=new createjs.Bitmap(c);k.x=a;k.y=b;k.regX=c.width/2;k.regY=c.height/2;s_oStage.addChild(k);this._initListener()};this.unload=function(){k.off("mousedown",this.buttonDown);k.off("pressup",this.buttonRelease);s_oStage.removeChild(k)};this.setVisible=function(a){k.visible=a};this._initListener=function(){k.on("mousedown",this.buttonDown);k.on("pressup",this.buttonRelease)};this.addEventListener=
function(a,b,d){l[a]=b;p[a]=d};this.addEventListenerWithParams=function(a,b,d,c){l[a]=b;p[a]=d;t=c};this.buttonRelease=function(){d||(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("press_but"),k.scaleX=1,k.scaleY=1,l[ON_MOUSE_UP]&&l[ON_MOUSE_UP].call(p[ON_MOUSE_UP],t))};this.buttonDown=function(){d||(k.scaleX=.9,k.scaleY=.9,l[ON_MOUSE_DOWN]&&l[ON_MOUSE_DOWN].call(p[ON_MOUSE_DOWN],t))};this.setPosition=function(a,b){k.x=a;k.y=b};this.setX=function(a){k.x=a};this.setY=function(a){k.y=
a};this.enable=function(){d=!1;k.filters=[];k.cache(0,0,f,e)};this.disable=function(){d=!0;var a=(new createjs.ColorMatrix).adjustSaturation(-100).adjustBrightness(40);k.filters=[new createjs.ColorMatrixFilter(a)];k.cache(0,0,f,e)};this.getButtonImage=function(){return k};this.getX=function(){return k.x};this.getY=function(){return k.y};this._init(c,a,b);return this}
function CGame(c){var a,b,d=0,f=0,e,l,p;this._init=function(c){a=c;p=new CPlayer;a?(l=new CInterface(this,a),e=new CBallChallenge(this),c=e.getInitialScoringdata(),d=c.initGravity,b=c.tick):(l=new CInterface(this,a),e=new CBall(this))};this.unload=function(){e.unload();s_oMain.gotoMenu()};this.update=function(){e.checkEdges()&&(0!==d&&l.updateScore(0,Math.floor(100*f)/100),a?(d=e.getInitialScoringdata().initGravity,!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("reset_kickup")):0<
d&&(d=0,!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("reset_kickup")));e.update();s_oStage.update()};this.increaseScore=function(){a?d+=b:d++;var c=Math.random();.25>=c&&d>f?l.newTopScore():.7>=c&&l.encouragement();d>f&&(f=d,$(s_oMain).trigger("new_highscore",f));l.updateScore(Math.floor(100*d)/100,Math.floor(100*f)/100)};this.playerAnim=function(a,b){p.display(a,b)};this._init(c)}
function CBallChallenge(c){var a=!1,b=GRAVITY_INCREASE,d=new CVector2(0,INIT_GRAVITY_CHALLENGE),f=INIT_BALLMASS_CHALLENGE,e=0,l=0,p=FRICTION_CHALLENGE,t=EDGEFRICTION_CHALLENGE,k=ROTATIONSPEED_CHALLENGE,u=HORIZ_KICKFORCE_CHALLENGE,g=VERT_KICKFORCE_CHALLENGE,s=RESTITUTION_KICKFORCE_CHALLENGE,h,r,m,q,n,v,w,x;this._init=function(a){this._initForces();var b="ball_"+Math.floor(3*Math.random()+1);n=new createjs.Bitmap(s_oSpriteLibrary.getSprite(b));n.regX=BALL_SIZE/2;n.regY=BALL_SIZE/2;n.x=CANVAS_WIDTH/
2;n.y=CANVAS_HEIGHT/2;v=new createjs.Bitmap(s_oSpriteLibrary.getSprite("shadow"));v.regX=SHADOW_WIDTH/2;v.regY=SHADOW_HEIGHT/2;v.x=n.x;v.y=CANVAS_HEIGHT-BALL_BOUNCE_YOFFSET;v.alpha=.65;w=new createjs.Bitmap(s_oSpriteLibrary.getSprite("ball_hit"));w.regX=BALL_SIZE/2;w.regY=BALL_SIZE/2;w.x=CANVAS_WIDTH/2;w.y=CANVAS_HEIGHT/2;w.alpha=0;s_oStage.addChild(v);s_oStage.addChild(n);s_oStage.addChild(w);n.on("mousedown",this.clicked,this);h=new CVector2(n.x,n.y);r=new CVector2(0,0);m=new CVector2(0,0);x=a};
this._initForces=function(){q=new CVector2(d.getX(),d.getY());g=u=50};this._updateForces=function(){q.set(0,q.getY()+b);g+=4*b;u+=4*b/2};this.getInitialScoringdata=function(){return{tick:b,initGravity:d.getY()}};this.unload=function(){s_oStage.removeChild(n,v,w);n=void 0};this.update=function(){m.addV(q);this._friction();r.addV(m);h.addV(r);m._init(0,0);n.x=h.getX();n.y=h.getY();l=r.getX();e+=l;n.rotation=e*k;v.x=n.x;v.scaleX=v.scaleY=n.y/(CANVAS_HEIGHT-BALL_SIZE/2-BALL_BOUNCE_YOFFSET);w.x=n.x;w.y=
n.y;w.rotation=e*k};this.checkEdges=function(){h.getX()<BALL_SIZE/2?(h.set(BALL_SIZE/2,h.getY()),r.set(-(1-t)*r.getX(),r.getY())):h.getX()>CANVAS_WIDTH-BALL_SIZE/2&&(h.set(CANVAS_WIDTH-BALL_SIZE/2,h.getY()),r.set(-(1-t)*r.getX(),r.getY()));if(h.getY()>CANVAS_HEIGHT-BALL_SIZE/2-BALL_BOUNCE_YOFFSET)return h.set(h.getX(),CANVAS_HEIGHT-BALL_SIZE/2-BALL_BOUNCE_YOFFSET),r.set(r.getX(),-(1-t)*r.getY()),this._initForces(),!0};this.applyForce=function(a){a=new CVector2(a.getX(),a.getY());a.scalarDivision(f);
m.addV(a)};this.clicked=function(b){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("tap");this._updateForces();x.increaseScore();x.playerAnim(h.getX(),h.getY());r.set(-s*r.getX(),-s*r.getY());b=new CVector2(-b.rawX+h.getX(),-1*(b.rawY-(h.getY()-BALL_SIZE/2)));b.normalize();b=new CVector2(b.getX()*u,b.getY()*g-0);this.applyForce(b);!1===a&&(a=!0,createjs.Tween.get(n).to({scaleX:1.15,scaleY:.85},100,createjs.Ease.cubicIn).call(function(){createjs.Tween.get(n).to({scaleX:1,scaleY:1},
100,createjs.Ease.cubicOut).call(function(){})}),createjs.Tween.get(w).to({scaleX:1.15,scaleY:.85,alpha:.4},100,createjs.Ease.cubicIn).call(function(){createjs.Tween.get(w).to({scaleX:1,scaleY:1,alpha:0},100,createjs.Ease.cubicOut).call(function(){a=!1})}))};this._friction=function(){var a=new CVector2(r.getX(),r.getY());a.scalarProduct(-1);a.normalize();a.scalarProduct(p);this.applyForce(a)};this._v2Limit=function(a,b){a.length()>=b&&(a.normalize(),a.scalarProduct(b))};this._init(c)}
function CBall(c){var a=!1,b=INIT_BALLMASS_NORMAL,d=0,f=0,e=FRICTION_NORMAL,l=EDGEFRICTION_NORMAL,p=ROTATIONSPEED_NORMAL,t=HORIZ_KICKFORCE_NORMAL,k=VERT_KICKFORCE_NORMAL,u=RESTITUTION_KICKFORCE_NORMAL,g,s,h,r=new CVector2(0,INIT_GRAVITY_NORMAL),m,q,n,v;this._init=function(a){var b="ball_"+Math.floor(3*Math.random()+1);m=new createjs.Bitmap(s_oSpriteLibrary.getSprite(b));m.regX=BALL_SIZE/2;m.regY=BALL_SIZE/2;m.x=CANVAS_WIDTH/2;m.y=CANVAS_HEIGHT/2;q=new createjs.Bitmap(s_oSpriteLibrary.getSprite("shadow"));
q.regX=SHADOW_WIDTH/2;q.regY=SHADOW_HEIGHT/2;q.x=m.x;q.y=CANVAS_HEIGHT-BALL_BOUNCE_YOFFSET;q.alpha=.65;n=new createjs.Bitmap(s_oSpriteLibrary.getSprite("ball_hit"));n.regX=BALL_SIZE/2;n.regY=BALL_SIZE/2;n.x=CANVAS_WIDTH/2;n.y=CANVAS_HEIGHT/2;n.alpha=0;s_oStage.addChild(q);s_oStage.addChild(m);s_oStage.addChild(n);m.on("mousedown",this.clicked,this);g=new CVector2(m.x,m.y);s=new CVector2(0,0);h=new CVector2(0,0);v=a};this.unload=function(){s_oStage.removeChild(m,q,n);m=void 0};this.update=function(){h.addV(r);
this._friction();s.addV(h);g.addV(s);h._init(0,0);m.x=g.getX();m.y=g.getY();f=s.getX();d+=f;m.rotation=d*p;q.x=m.x;q.scaleX=q.scaleY=m.y/(CANVAS_HEIGHT-BALL_SIZE/2-BALL_BOUNCE_YOFFSET);q.alpha=m.y/(CANVAS_HEIGHT-BALL_SIZE/2-BALL_BOUNCE_YOFFSET);n.x=m.x;n.y=m.y;n.rotation=d*p};this.checkEdges=function(){g.getX()<BALL_SIZE/2?(g.set(BALL_SIZE/2,g.getY()),s.set(-(1-l)*s.getX(),s.getY())):g.getX()>CANVAS_WIDTH-BALL_SIZE/2&&(g.set(CANVAS_WIDTH-BALL_SIZE/2,g.getY()),s.set(-(1-l)*s.getX(),s.getY()));if(g.getY()>
CANVAS_HEIGHT-BALL_SIZE/2-BALL_BOUNCE_YOFFSET)return g.set(g.getX(),CANVAS_HEIGHT-BALL_SIZE/2-BALL_BOUNCE_YOFFSET),s.set(s.getX(),-(1-l)*s.getY()),!0};this.applyForce=function(a){a=new CVector2(a.getX(),a.getY());a.scalarDivision(b);h.addV(a)};this.clicked=function(b){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("tap");v.increaseScore();v.playerAnim(g.getX(),g.getY());s.set(-u*s.getX(),-u*s.getY());b=new CVector2(-b.rawX+g.getX(),-1*(b.rawY-(g.getY()-BALL_SIZE/2)));b.normalize();
b=new CVector2(b.getX()*t,b.getY()*k-0);this.applyForce(b);!1===a&&(a=!0,createjs.Tween.get(m).to({scaleX:1.15,scaleY:.85},100,createjs.Ease.cubicIn).call(function(){createjs.Tween.get(m).to({scaleX:1,scaleY:1},100,createjs.Ease.cubicOut).call(function(){})}),createjs.Tween.get(n).to({scaleX:1.15,scaleY:.85,alpha:.4},100,createjs.Ease.cubicIn).call(function(){createjs.Tween.get(n).to({scaleX:1,scaleY:1,alpha:0},100,createjs.Ease.cubicOut).call(function(){a=!1})}))};this._friction=function(){var a=
new CVector2(s.getX(),s.getY());a.scalarProduct(-1);a.normalize();a.scalarProduct(e);this.applyForce(a)};this._v2Limit=function(a,b){a.length()>=b&&(a.normalize(),a.scalarProduct(b))};this._init(c)};