function CInterface(){var a,e,b,d,c,g,f,h,k,l,m,q,t,n,p,x,v,w,y;this._init=function(){k=[];for(var r=0;9>r;r++)k[r+1]=5<r?new CNumButton(97+177.5*(r-6),1650,r+1):new CNumButton(97+177.5*r,1500,r+1);r=s_oSpriteLibrary.getSprite("but_del_toggle");l=new CDeleteButton(629.5,1650,r,!1);l.changeMode();r=s_oSpriteLibrary.getSprite("note_toggle");m=new CToggle(807,1650,r,!0);m.addEventListener(ON_MOUSE_UP,this._onNoteToggle,this);r=s_oSpriteLibrary.getSprite("mode_toggle");q=new CToggle(984.5,1650,r,!0);
q.addEventListener(ON_MOUSE_UP,this._onModeToggle,this);var z,r=s_oSpriteLibrary.getSprite("but_exit");f=CANVAS_WIDTH-r.height/2-20;h=r.height/2+10;y=new CGfxButton(f,h,r,s_oStage);y.addEventListener(ON_MOUSE_UP,this._onExit,this);c=z=CANVAS_WIDTH-r.width/2-175;g=r.height/2+10;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)r=s_oSpriteLibrary.getSprite("audio_icon"),v=new CToggle(c,g,r,s_bAudioActive),v.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);z=CANVAS_WIDTH-r.width/2-257;r=s_oSpriteLibrary.getSprite("config_icon");
b=z;d=r.height/2+10;w=new CGfxButton(b,d,r,s_oStage);w.addEventListener(ON_MOUSE_UP,this._onConf,this);z=CANVAS_WIDTH-r.width/2-490;r=s_oSpriteLibrary.getSprite("but_help_icon");a=z;e=r.height/2+10;t=new CGfxButton(a,e,r,s_oStage);t.addEventListener(ON_MOUSE_UP,this._onHelpPress,this);r=s_oSpriteLibrary.getSprite("time_display");x=createBitmap(r);x.x=220;x.y=260;s_oStage.addChild(x);n=new createjs.Text(TEXT_TIME,"bold 60px Arial","#008df0");n.x=40;n.y=325;n.textAlign="left";n.textBaseline="alphabetic";
n.lineWidth=200;s_oStage.addChild(n);p=new createjs.Text("00:00","bold 60px Arial","#ffffff");p.x=245;p.y=325;p.textAlign="left";p.textBaseline="alphabetic";p.lineWidth=200;s_oStage.addChild(p);this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)v.unload(),v=null;y.unload();for(var a=0;9>a;a++)k[a+1].unload();l.unload();m.unload();q.unload();t.unload()};this.refreshButtonPos=function(k,l){y.setPosition(f-k,l+h);w.setPosition(b-k,l+d);t.setPosition(a-
k,l+e);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||v.setPosition(c-k,l+g)};this.refreshTime=function(a){p.text=a};this._onConf=function(){new CConfigPanel};this.setNoTime=function(){s_oStage.removeChild(n,p,x)};this._onHelpPress=function(){new CHelpPanel;s_oGame.pauseTimer(!0)};this._onNoteToggle=function(){s_oGame.setNoteState()};this._onModeToggle=function(){for(var a=0;9>a;a++)k[a+1].changeMode();l.changeMode();this.setAllBlackColor();s_oGame.setDigitState()};this.updateCounterOnButton=function(a,
d){k[a].clearCounter();k[a].setCounter(d)};this.pressNumButton=function(a){k[a].buttonDown()};this.releaseNumButton=function(a){k[a].buttonRelease()};this.pressDelButton=function(){l.buttonDown()};this.releaseDelButton=function(a){l.buttonRelease()};this.setAllBlackColor=function(){for(var a=0;9>a;a++)k[a+1].changeNumColor(!1);l.reset()};this._onButHelpRelease=function(){_oHelpPanel=new CHelpPanel};this._onButRestartRelease=function(){s_oGame.restartGame()};this.onExitFromHelp=function(){_oHelpPanel.unload()};
this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onExit=function(){s_oGame.onExit()};s_oInterface=this;this._init();return this}var s_oInterface=null;
function CHelpPanel(){var a,e,b,d,c,g,f,h,k,l,m,q,t,n,p;this._init=function(){var x=this;k=createBitmap(s_oSpriteLibrary.getSprite("bg_help"));var t=CANVAS_WIDTH/2,w=CANVAS_HEIGHT/2-400;a=new createjs.Text(TEXT_HELP0," 140px blackplotan","#008df0");a.x=t;a.y=w-100;a.textAlign="center";a.textBaseline="alphabetic";a.lineWidth=700;e=new createjs.Text(TEXT_HELP1,"bold 50px Arial","#008df0");e.x=t;e.y=w;e.textAlign="center";e.textBaseline="alphabetic";e.lineWidth=950;m=new createjs.Container;m.addChild(k,
a,e);s_oStage.addChild(m);m.on("pressup",function(){x._onExitHelp()});l=createBitmap(s_oSpriteLibrary.getSprite("bg_help2"));b=!1===s_bMobile?TEXT_HELP1_PAGE2:TEXT_HELP1_MOB_PAGE2;d=new createjs.Text(TEXT_HELP0_PAGE2," 140px blackplotan","#008df0");d.x=.5*CANVAS_WIDTH;d.y=w-100;d.textAlign="center";d.textBaseline="alphabetic";d.lineWidth=800;c=new createjs.Text(b,"bold 35px Arial","#008df0");c.x=CANVAS_WIDTH/2;c.y=CANVAS_HEIGHT/2-432;c.textAlign="center";c.lineWidth=900;c.textBaseline="alphabetic";
g=new createjs.Text(TEXT_HELP2_PAGE2,"bold 35px Arial","#008df0");g.x=CANVAS_WIDTH/2-180;g.y=CANVAS_HEIGHT/2-272;g.textAlign="left";g.lineWidth=600;g.textBaseline="alphabetic";f=new createjs.Text(TEXT_HELP3_PAGE2,"bold 35px Arial","#008df0");f.x=CANVAS_WIDTH/2-380;f.y=CANVAS_HEIGHT/2+45;f.textAlign="left";f.lineWidth=600;f.textBaseline="alphabetic";h=new createjs.Text(TEXT_HELP4_PAGE2,"bold 35px Arial","#008df0");h.x=CANVAS_WIDTH/2-180;h.y=CANVAS_HEIGHT/2+340;h.textAlign="left";h.lineWidth=600;h.textBaseline=
"alphabetic";q=new createjs.Container;q.addChild(l,d,c,g,f,h);q.visible=0;s_oStage.addChild(q);q.on("pressup",function(){x._onExitHelp()});createjs.Tween.get(q).to({alpha:1},700);n=createBitmap(s_oSpriteLibrary.getSprite("arrow"));n.x=740;n.y=1450;n.alpha=0;n.on("click",x._changePageTo2);s_oStage.addChild(n);p=createBitmap(s_oSpriteLibrary.getSprite("arrow"));p.scaleX=-1;p.x=340;p.y=1450;p.visible=!1;p.on("click",x._changePageTo1);s_oStage.addChild(p);createjs.Tween.get(n).to({alpha:1},700)};this.unload=
function(){s_oStage.removeChild(m,q,n,p);var a=this;m.off("pressup",function(){a._onExitHelp()});q.off("pressup",function(){a._onExitHelp()})};this._changePageTo1=function(){q.visible=!1;p.visible=!1;m.visible=!0;n.visible=!0};this._changePageTo2=function(){m.visible=!1;n.visible=!1;q.visible=!0;p.visible=!0};this._onExitHelp=function(){t.unload();s_oGame._onExitHelp()};t=this;this._init()}
function CGrid(){var a,e,b,d,c,g,f,h;this._init=function(){e=a=0;g=new createjs.Container;g.x=CANVAS_WIDTH/2;g.y=880;s_oStage.addChild(g);var k=CELL_SIZE,l=9*CELL_SIZE+44,m=.5*l,q=k,t=[];t.push(.5*k);f=[];for(var n=0;8>n;n++){if(2===n%3)var p=(new createjs.Graphics).beginFill("rgba(0,0,0,1)").drawRect(-m,-m+q,l,10),q=q+(k+10);else p=(new createjs.Graphics).beginFill("rgba(0,0,0,1)").drawRect(-m,-m+q,l,4),q+=k+4;t.push(q-.5*k);f[n]=new createjs.Shape(p);g.addChild(f[n])}q=k;h=[];for(n=0;8>n;n++)2===
n%3?(p=(new createjs.Graphics).beginFill("rgba(0,0,0,1)").drawRect(-m+q,-m,10,l),q+=k+10):(p=(new createjs.Graphics).beginFill("rgba(0,0,0,1)").drawRect(-m+q,-m,4,l),q+=k+4),h[n]=new createjs.Shape(p),g.addChild(h[n]);p=(new createjs.Graphics).beginFill("rgba(0,0,0,1)").drawRect(-m-10,-m-10,10,l+20);n=new createjs.Shape(p);g.addChild(n);p=(new createjs.Graphics).beginFill("rgba(0,0,0,1)").drawRect(m,-m-10,10,l+20);n=new createjs.Shape(p);g.addChild(n);p=(new createjs.Graphics).beginFill("rgba(0,0,0,1)").drawRect(-m-
10,-m-10,l+20,10);n=new createjs.Shape(p);g.addChild(n);p=(new createjs.Graphics).beginFill("rgba(0,0,0,1)").drawRect(-m-10,+m,l+20,10);l=new createjs.Shape(p);g.addChild(l);b=[];for(n=0;9>n;n++)for(b[n]=[],l=0;9>l;l++)b[n][l]={x:t[n],y:t[l]};d=[];for(n=0;9>n;n++)for(d[n]=[],l=0;9>l;l++)d[n][l]=new CCell(b[n][l].x-m,b[n][l].y-m,{row:n,col:l},g);c=[];for(n=0;10>n;n++)c[n]=[]};this.setCurNum=function(a){};this.setActiveCell=function(c){this.turnOffAllCells();a=c.row;e=c.col;this.highlightCells();0!==
d[a][e].getNumber()&&this.showSameNumbers(d[a][e].getNumber())};this.showCorner=function(){d[a][e].setCorner(!0)};this.turnOffAllCells=function(){for(var c=0;9>c;c++)for(var b=0;9>b;b++)d[c][b].highlight("off");d[a][e].setCorner(!1)};this.showSameNumbers=function(a){if(0!==a){for(var b=0;b<c[a].length;b++)d[c[a][b].row][c[a][b].col].highlight("green");for(b=0;9>b;b++)for(var e=0;9>e;e++)0!==d[b][e].getNote(a)&&d[b][e].highlight("green")}};this.highlightCells=function(){this.showCorner();for(var c=
0;9>c;c++)d[a][c].highlight("yellow");for(c=0;9>c;c++)d[c][e].highlight("yellow");for(var c=3*Math.floor(a/3),b=3*Math.floor(e/3),f=0;3>f;f++)for(var g=0;3>g;g++)d[c+f][b+g].highlight("yellow")};this.deleteCell=function(){d[a][e].getGiven()||(0!==d[a][e].getNumber()&&s_oGame.checkEndGame("remove"),this.deleteSmartFromList(d[a][e].getNumber()),d[a][e].clearCell(),this.turnOffAllCells(),this.highlightCells())};this.writeNum=function(c){d[a][e].getGiven()||0===c||c===d[a][e].getNumber()||(this.turnOffAllCells(),
this.highlightCells(),this.checkCollision(c,a,e,!0)||(0!==d[a][e].getNumber()&&this.deleteCell(),d[a][e].setNumber(c),this.insertSmartInList(c),this.updateNote(c),this.showSameNumbers(c),s_oGame.checkEndGame("add")))};this.deleteAllNote=function(){for(var b=0;b<c[0].length;b++)d[c[0][b].row][c[0][b].col].clearAllNote();this.turnOffAllCells();this.highlightCells();this.showSameNumbers(d[a][e].getNumber())};this.writeNote=function(c){d[a][e].getGiven()||(this.turnOffAllCells(),this.highlightCells(),
d[a][e].setNote(c),this.showSameNumbers(d[a][e].getNumber()))};this.writeHelpNote=function(a,c,b){d[c][b].setHelpNote(a)};this.setGiven=function(a,b,e){d[a][b].setGiven(e);c[e].push({row:a,col:b})};this.isGiven=function(a,c){return d[a][c].getGiven()};this.setSolvedNumber=function(a,b,e){d[a][b].setHintNumber(e);c[e].push({row:a,col:b});for(e=0;e<c[0].length;e++)c[0][e].row===a&&c[0][e].col===b&&c[0].splice(e,1)};this.setHintNumber=function(a,b,e){d[a][b].setHintNumber(e);c[e].push({row:a,col:b});
for(e=0;e<c[0].length;e++)c[0][e].row===a&&c[0][e].col===b&&c[0].splice(e,1)};this.deleteResetNumber=function(a,b){var e=d[a][b].getNumber();if(0!==e){for(var f=0;f<c[e].length;f++)c[e][f].row===a&&c[e][f].col===b&&c[e].splice(f,1);d[a][b].clearCell()}c[0].push({row:a,col:b})};this.updateNote=function(c){for(var b=0;9>b;b++)0!==d[a][b].getNote(c)&&d[a][b].clearNote(c),0!==d[b][e].getNote(c)&&d[b][e].clearNote(c);for(var f=3*Math.floor(a/3),g=3*Math.floor(e/3),b=0;3>b;b++)for(var h=0;3>h;h++)0!==d[f+
b][g+h].getNote(c)&&d[f+b][g+h].clearNote(c)};this.checkCollision=function(a,b,e,f){for(var g=3*Math.floor(b/3),h=3*Math.floor(e/3),p=0;p<c[a].length;p++)if(c[a][p].row===b||c[a][p].col===e||g<=c[a][p].row&&c[a][p].row<g+3&&h<=c[a][p].col&&c[a][p].col<h+3)return f&&d[c[a][p].row][c[a][p].col].highlight("red"),!0};this.deleteSmartFromList=function(b){if(0!==b){for(var d=0;d<c[b].length;d++)c[b][d].row===a&&c[b][d].col===e&&c[b].splice(d,1);c[0].push({row:a,col:e})}};this.insertSmartInList=function(b){if(0!==
b)for(c[b].push({row:a,col:e}),b=0;b<c[0].length;b++)c[0][b].row===a&&c[0][b].col===e&&c[0].splice(b,1)};this.getList=function(a){return c[a]};this.viewList=function(a){trace(c[a]);trace(c[a].length)};this.getCurActiveCell=function(){return{row:a,col:e,num:d[a][e].getNumber()}};this.getCurGrid=function(){for(var a=[],b=0;9>b;b++){a[b]=[];for(var c=0;9>c;c++)a[b][c]=d[b][c].getNumber()}return a};this._init()}
function CGfxButton(a,e,b,d){var c,g,f,h;this._init=function(a,b,d,e){c=[];g=[];f=createBitmap(d);f.x=a;f.y=b;f.regX=d.width/2;f.regY=d.height/2;h=e;h.addChild(f);this._initListener()};this.unload=function(){f.off("mousedown",this.buttonDown);f.off("pressup",this.buttonRelease);h.removeChild(f)};this.setVisible=function(a){f.visible=a};this._initListener=function(){f.on("mousedown",this.buttonDown);f.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,d){c[a]=b;g[a]=d};this.buttonRelease=
function(){f.scaleX=1;f.scaleY=1;!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");c[ON_MOUSE_UP]&&c[ON_MOUSE_UP].call(g[ON_MOUSE_UP])};this.buttonDown=function(){f.scaleX=.9;f.scaleY=.9;c[ON_MOUSE_DOWN]&&c[ON_MOUSE_DOWN].call(g[ON_MOUSE_DOWN])};this.setPosition=function(a,b){f.x=a;f.y=b};this.setX=function(a){f.x=a};this.setY=function(a){f.y=a};this.getButtonImage=function(){return f};this.getX=function(){return f.x};this.getY=function(){return f.y};this._init(a,e,b,d);return this}
function CGame(a){function e(a){a||(a=window.event);a=a.keyCode-48;10>a&&0<a?r.pressNumButton(a):-2===a&&r.pressDelButton()}function b(a){a=a.keyCode-48;10>a&&0<a?r.releaseNumButton(a):-2===a&&r.releaseDelButton()}var d,c,g,f,h,k,l,m,q,t,n,p,x,v,w,y,r,z=null,u,A;this._init=function(){m=l=k=h=f=g=!1;x=q=t=n=0;var a=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(a);r=new CInterface;u=new CGrid;v=Array(81);this._generateValidGrid(v);v=this._convertToMatrix(v);w=[];for(a=0;9>a;a++){w[a]=
[];for(var d=0;9>d;d++)w[a][d]=v[a][d]}A=new CSudokuLoader;c=!0;!1===s_bMobile&&(document.onkeydown=e,document.onkeyup=b)};this.getHint=function(){x++;for(var a=[],b=0;9>b;b++)for(var c=0;9>c;c++)0===v[b][c]&&a.push({row:b,col:c});if(1===a.length)this.gameOver();else if(0!==a.length){shuffle(a);var b=a[0].row,c=a[0].col,d=w[b][c];v[b][c]=d;u.setHintNumber(b,c,d);u.setActiveCell(a[0]);u.updateNote(d);u.setActiveCell(a[0]);this._getEndCounterAndSetButCounter()}};this.setNoTime=function(){d=!1;r.setNoTime();
m=!0};this.solveAndWrite=function(){for(var a=0;9>a;a++)for(var b=0;9>b;b++)0===v[a][b]&&(u.setSolvedNumber(a,b,w[a][b]),v[a][b]=w[a][b]);this._getEndCounterAndSetButCounter();l=!0};this.resetGame=function(){for(var a=0;9>a;a++)for(var b=0;9>b;b++)u.isGiven(a,b)||(u.deleteResetNumber(a,b),v[a][b]=0);this._getEndCounterAndSetButCounter();u.turnOffAllCells();u.highlightCells()};this.fillWithNote=function(){this.clearNoteFill();for(var a=u.getList(0),b=0;b<a.length;b++)for(var c=a[b],d=1;10>d;d++)!0!==
u.checkCollision(d,c.row,c.col,!1)&&u.writeHelpNote(d,c.row,c.col);k=!0};this.deleteAllNote=function(){this.clearNoteFill()};this.clearNoteFill=function(){u.deleteAllNote()};this.setNoteState=function(){g=!g};this.setDigitState=function(){h=!h;f=!1;q=0};this.setDeleteState=function(){f=!0;q=0};this.setCurNum=function(a){f=!1;q=a};this.activeCell=function(a){h&&!f?(u.setActiveCell(a),this.writeNum(q)):h&&f?(u.setActiveCell(a),u.deleteCell()):u.setActiveCell(a)};this.writeNum=function(a){if(g)u.writeNote(a);
else{u.writeNum(a);r.updateCounterOnButton(a,u.getList(a).length);var b=u.getCurActiveCell().row,c=u.getCurActiveCell().col;v[b][c]=a}};this.deleteCell=function(){var a=u.getCurActiveCell().num,b=u.getCurActiveCell().row,c=u.getCurActiveCell().col;u.deleteCell();0!==a&&(r.updateCounterOnButton(a,u.getList(a).length),v[b][c]=0)};this.restartGame=function(){this.unload();this._init()};this.unload=function(){_bInitGame=!1;r.unload();null!==z&&z.unload();createjs.Tween.removeAllTweens();s_oStage.removeAllChildren()};
this.onExit=function(){this.unload();s_oMain.gotoMenu();$(s_oMain).trigger("restart")};this._onExitHelp=function(){d=!0};this.checkEndGame=function(a){"add"===a?t++:t--;81===t&&this.gameOver()};this.gameOver=function(){z=CEndPanel(s_oSpriteLibrary.getSprite("msg_box"),k,l,m,x);z.show(n)};this.pauseTimer=function(a){d=!a};this.update=function(){if(c){A.update();for(var a=0;12>a;a++){for(var b=0;9>b;b++)for(var e=0;9>e;e++)v[b][e]=w[b][e];this._generateMask(s_iDifficultyMode);this._coverGrid(v);p=solve(v);
if(1!==p){c=!1;A.unload();this._coverGrid(v);this.setGrid(v);d=!0;s_oMain.startUpdate();break}}}d&&(n+=s_iTimeElaps,5999E3<n&&(n=5999E3),r.refreshTime(formatTime(n)))};this.setGrid=function(a){for(var b=0;9>b;b++)for(var c=0;9>c;c++)u.setGiven(b,c,a[b][c]);this._getEndCounterAndSetButCounter()};this._getEndCounterAndSetButCounter=function(){t=0;for(var a=1;10>a;a++){var b=u.getList(a).length;t+=b;r.updateCounterOnButton(a,b)}};this._convertToMatrix=function(a){for(var b=0,c=[],d=0;81>d;d+=9)c[b]=
[a[d],a[d+1],a[d+2],a[d+3],a[d+4],a[d+5],a[d+6],a[d+7],a[d+8]],b++;return c};this._generateMask=function(a){y=[];for(var b=0;9>b;b++){y[b]=[];for(var c=0;9>c;c++)y[b][c]=0}var b=MAX_GIVENS_EASY-RANGE_GIVENS,d,e;switch(a){case EASY_MODE:b=MAX_GIVENS_EASY-RANGE_GIVENS;d=b+Math.ceil(Math.random()*RANGE_GIVENS);e=LOWER_BOUND_EASY;break;case MEDIUM_MODE:b=MAX_GIVENS_MEDIUM-RANGE_GIVENS;d=b+Math.ceil(Math.random()*RANGE_GIVENS);e=LOWER_BOUND_MEDIUM;break;case HARD_MODE:b=MAX_GIVENS_HARD-RANGE_GIVENS,d=
b+Math.ceil(Math.random()*RANGE_GIVENS),e=LOWER_BOUND_HARD}for(var f=[],b=0;9>b;b++)b<e?f.push(1):f.push(0);a=[];for(b=0;9>b;b++)for(a[b]=0,shuffle(f),c=0;9>c;c++)1===f[c]&&(y[b][c]=1);for(var g=[],b=0;9>b;b++)for(g[b]=0,shuffle(f),c=0;9>c;c++)1===f[c]&&(y[c][b]=1);for(b=f=0;9>b;b++)for(c=0;9>c;c++)1===y[b][c]&&(a[b]++,g[c]++,f++);d=f-d;if(0>d)this._generateMask(s_iDifficultyMode);else if(0===d)return;f=[];for(b=0;9>b;b++)for(c=0;9>c;c++)1===y[b][c]&&f.push({row:b,col:c,weightRow:a[b],weightCol:g[c],
weightTotal:a[b]+g[c]});f.sort(function(a,b){return a.weightTotal<b.weightTotal?-1:a.weightTotal>b.weightTotal?1:0});for(c=0;c<d;){b=f.length-1;if(0>b)break;if(f[b].weightRow>e&&f[b].weightCol>e){y[f[b].row][f[b].col]=0;var h=f[b].row,k=f[b].col;a[h]--;g[k]--;for(b=0;b<f.length;b++)f[b].row===h&&(f[b].weightRow=a[h],f[b].weightTotal--),f[b].col===k&&(f[b].weightCol=g[k],f[b].weightTotal--);c++}f.pop()}};this._coverGrid=function(a){for(var b=0;9>b;b++)for(var c=0;9>c;c++)0===y[b][c]&&(a[b][c]=0)};
this.findUnassignedLocation=function(a,b,c){for(var d=!1,e=[-1,-1];!d;)9===b?d=!0:0===a[b][c]?(e[0]=b,e[1]=c,d=!0):8>c?c++:(b++,c=0);return e};this.noConflicts=function(a,b,c,d){return this.isRowOk(a,b,d)&&this.isColOk(a,c,d)&&this.isBoxOk(a,b,c,d)};this.isRowOk=function(a,b,c){for(var d=0;9>d;d++)if(a[b][d]===c)return!1;return!0};this.isColOk=function(a,b,c){for(var d=0;9>d;d++)if(a[d][b]===c)return!1;return!0};this.isBoxOk=function(a,b,c,d){b=3*Math.floor(b/3);c=3*Math.floor(c/3);for(var e=0;3>
e;e++)for(var f=0;3>f;f++)if(a[b+e][c+f]===d)return!1;return!0};this._generateValidGrid=function(a){for(var b=0;9>b;b++)for(var c=0;9>c;c++)a[9*b+c]=(3*b+Math.floor(b/3)+c)%9+1;for(b=0;42>b;b++){var d=Math.ceil(9*Math.random()),e;do e=Math.ceil(9*Math.random());while(d===e);for(c=0;9>c;c++)for(var f=0;9>f;f++)a[9*c+f]===d?a[9*c+f]=e:a[9*c+f]===e&&(a[9*c+f]=d)}for(f=0;42>f;f++)for(d=Math.floor(3*Math.random()),e=Math.floor(3*Math.random()),c=0;9>c;c++)b=a[9*c+(3*d+f%3)],a[9*c+(3*d+f%3)]=a[9*c+(3*e+
f%3)],a[9*c+(3*e+f%3)]=b;for(d=0;42>d;d++)for(f=Math.floor(3*Math.random()),e=Math.floor(3*Math.random()),c=0;9>c;c++)b=a[9*c+(d%3*3+f)],a[9*c+(d%3*3+f)]=a[9*c+(d%3*3+e)],a[9*c+(d%3*3+e)]=b;for(d=0;42>d;d++)for(c=Math.floor(3*Math.random()),e=Math.floor(3*Math.random()),f=0;9>f;f++)b=a[9*(d%3*3+c)+f],a[9*(d%3*3+c)+f]=a[9*(d%3*3+e)+f],a[9*(d%3*3+e)+f]=b};s_oGame=this;MAX_GIVENS_EASY=a.max_givens_beginner;MAX_GIVENS_MEDIUM=a.max_givens_intermediate;MAX_GIVENS_HARD=a.max_givens_advanced;this._init()}
var s_oGame;
function CEndPanel(a,e,b,d,c){var g,f,h,k,l,m;this._init=function(a,b,c,d,e){g=[];b&&g.push(TEXT_HELP_NOTE);c&&g.push(TEXT_HELP_SOLVE);d&&g.push(TEXT_HELP_TIME);0<e&&(1<e?g.push(e+TEXT_HELP_HINTS):g.push(e+TEXT_HELP_HINT));h=createBitmap(a);h.x=0;h.y=0;l=new createjs.Text(""," 80px blackplotan","#008df0");l.x=CANVAS_WIDTH/2;l.y=CANVAS_HEIGHT/2-462;l.textAlign="center";l.textBaseline="alphabetic";l.lineWidth=700;m=new createjs.Text("","bold 40px Arial","#008df0");m.x=CANVAS_WIDTH/2;m.y=CANVAS_HEIGHT/
2-132;m.textAlign="center";m.textBaseline="alphabetic";m.lineWidth=700;f=[];f[0]=new createjs.Text("","bold 40px Arial","#008df0");f[0].x=300;f[0].y=CANVAS_HEIGHT/2-52;f[0].textAlign="left";f[0].textBaseline="alphabetic";f[0].lineWidth=700;f[1]=new createjs.Text("","bold 40px Arial","#008df0");f[1].x=300;f[1].y=CANVAS_HEIGHT/2+28;f[1].textAlign="left";f[1].textBaseline="alphabetic";f[1].lineWidth=700;f[2]=new createjs.Text("","bold 40px Arial","#008df0");f[2].x=300;f[2].y=CANVAS_HEIGHT/2+108;f[2].textAlign=
"left";f[2].textBaseline="alphabetic";f[2].lineWidth=700;f[3]=new createjs.Text("","bold 40px Arial","#008df0");f[3].x=300;f[3].y=CANVAS_HEIGHT/2+188;f[3].textAlign="left";f[3].textBaseline="alphabetic";f[3].lineWidth=700;k=new createjs.Container;k.alpha=0;k.visible=!1;k.addChild(h,m,l,f[0],f[1],f[2],f[3]);s_oStage.addChild(k)};this.unload=function(){k.off("mousedown",this._onExit)};this._initListener=function(){k.on("mousedown",this._onExit)};this.show=function(a){!1!==DISABLE_SOUND_MOBILE&&!1!==
s_bMobile||createjs.Sound.play("game_over");a=formatTime(a);var h=[];h[0]=TEXT_EASY;h[1]=TEXT_MEDIUM;h[2]=TEXT_EASY;l.text=d?TEXT_GAMEOVER+h[s_iDifficultyMode]+TEXT_SUDOKU:TEXT_GAMEOVER+h[s_iDifficultyMode]+TEXT_SUDOKU+TEXT_IN+a;1===g.length?m.text=TEXT_HELP_USED:1<g.length&&(m.text=TEXT_HELPS_USED);if(0<g.length)for(h=0;h<g.length;h++)f[h].text="-"+g[h];k.visible=!0;var n=this;createjs.Tween.get(k).to({alpha:1},500).call(function(){n._initListener()});$(s_oMain).trigger("save_score",[s_iDifficultyMode,
a,e,b,d,c])};this._onExit=function(){k.off("mousedown",this._onExit);s_oStage.removeChild(k);s_oGame.onExit()};this._init(a,e,b,d,c);return this}
function CDeleteButton(a,e,b,d){var c,g,f,h,k;this._init=function(a,b,d,e){g=!0;f=[];h=[];var n=new createjs.SpriteSheet({images:[d],frames:{width:d.width/2,height:d.height,regX:d.width/2/2,regY:d.height/2},animations:{state_true:[0],state_false:[1]}});c=e;k=createSprite(n,"state_"+c,d.width/2/2,d.height/2,d.width/2,d.height);k.x=a;k.y=b;k.stop();s_oStage.addChild(k);this._initListener()};this.unload=function(){k.off("mousedown",this.buttonDown);k.off("pressup",this.buttonRelease);s_oStage.removeChild(k)};
this.changeMode=function(){g=!g;c=!1;k.gotoAndStop("state_"+c)};this.reset=function(){c=!1;k.gotoAndStop("state_"+c)};this._initListener=function(){k.on("mousedown",this.buttonDown);k.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){f[a]=b;h[a]=c};this.setActive=function(a){c=a;k.gotoAndStop("state_"+c)};this.buttonRelease=function(){k.scaleX=1;k.scaleY=1;g?(s_oInterface.setAllBlackColor(),c=!0,k.gotoAndStop("state_"+c),s_oGame.setDeleteState()):s_oGame.deleteCell();f[ON_MOUSE_UP]&&
f[ON_MOUSE_UP].call(h[ON_MOUSE_UP],c)};this.buttonDown=function(){k.scaleX=.9;k.scaleY=.9;f[ON_MOUSE_DOWN]&&f[ON_MOUSE_DOWN].call(h[ON_MOUSE_DOWN])};this.setPosition=function(a,b){k.x=a;k.y=b};this._init(a,e,b,d)}
function CConfigPanel(){var a,e,b,d,c,g,f,h,k,l,m,q,t,n,p,x,v,w,y,r,z;this._init=function(){s_oGame.pauseTimer(!0);var k=this;f=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));x=new createjs.Container;x.x=130;x.y=430;s_oStage.addChild(x);a=new createjs.Text(TEXT_GETHINT," 50px blackplotan","#008df0");a.textAlign="left";a.textBaseline="alphabetic";a.lineWidth=700;x.addChild(a);var A=s_oSpriteLibrary.getSprite("but_help_hint");p=new CGfxButton(750,0,A,x);p.addEventListener(ON_MOUSE_UP,this._onHintPress,
this);v=new createjs.Container;v.x=130;v.y=630;s_oStage.addChild(v);e=new createjs.Text(TEXT_FILL_WITH_NOTE," 50px blackplotan","#008df0");e.textAlign="left";e.textBaseline="alphabetic";e.lineWidth=700;v.addChild(e);A=s_oSpriteLibrary.getSprite("but_help_note");l=new CGfxButton(750,0,A,v);l.addEventListener(ON_MOUSE_UP,this._onHelpPress,this);w=new createjs.Container;w.x=130;w.y=830;s_oStage.addChild(w);b=new createjs.Text(TEXT_SOLVE," 50px blackplotan","#008df0");b.textAlign="left";b.textBaseline=
"alphabetic";b.lineWidth=700;w.addChild(b);A=s_oSpriteLibrary.getSprite("but_solve");q=new CGfxButton(750,0,A,w);q.addEventListener(ON_MOUSE_UP,this._onSolvePress,this);y=new createjs.Container;y.x=130;y.y=1130;s_oStage.addChild(y);d=new createjs.Text(TEXT_RESET," 50px blackplotan","#008df0");d.textAlign="left";d.textBaseline="alphabetic";d.lineWidth=700;y.addChild(d);A=s_oSpriteLibrary.getSprite("but_reset");t=new CGfxButton(750,0,A,y);t.addEventListener(ON_MOUSE_UP,this._onResetPress,this);r=new createjs.Container;
r.x=130;r.y=1330;s_oStage.addChild(r);c=new createjs.Text(TEXT_DELETE_ALL_NOTE," 50px blackplotan","#008df0");c.textAlign="left";c.textBaseline="alphabetic";c.lineWidth=700;r.addChild(c);A=s_oSpriteLibrary.getSprite("but_del_note");m=new CGfxButton(750,0,A,r);m.addEventListener(ON_MOUSE_UP,this._onDelPress,this);z=new createjs.Container;z.x=130;z.y=1530;s_oStage.addChild(z);g=new createjs.Text(TEXT_SETNOTIME," 50px blackplotan","#008df0");g.textAlign="left";g.textBaseline="alphabetic";g.lineWidth=
700;z.addChild(g);A=s_oSpriteLibrary.getSprite("but_time");n=new CGfxButton(750,0,A,z);n.addEventListener(ON_MOUSE_UP,this._onTimePress,this);h=new createjs.Container;h.addChild(f,x,v,w,y,r,z);s_oStage.addChild(h);h.on("pressup",function(){k._onExitHelp()})};this.unload=function(){s_oStage.removeChild(h);var a=this;h.off("pressup",function(){a._onExitHelp()})};this._onHelpPress=function(){s_oGame.fillWithNote()};this._onDelPress=function(){s_oGame.deleteAllNote()};this._onSolvePress=function(){s_oGame.solveAndWrite()};
this._onResetPress=function(){s_oGame.resetGame()};this._onTimePress=function(){s_oGame.setNoTime()};this._onHintPress=function(){s_oGame.getHint()};this._onExitHelp=function(){k.unload();s_oGame.pauseTimer(!1)};k=this;this._init()}
function CCell(a,e,b,d){var c,g,f,h,k,l,m,q,t,n,p;this._init=function(a,b,d,e){c=!1;var k=CELL_SIZE;g=0;h=[];p=new createjs.Container;p.x=a;p.y=b;e.addChild(p);l={row:d.row,col:d.col};a=s_oSpriteLibrary.getSprite("background");b={images:[a],frames:{width:a.width/2,height:a.height,regX:a.width/2/2,regY:a.height/2},animations:{white:[0],grey:[1]}};b=new createjs.SpriteSheet(b);q=createSprite(b,"white",a.width/2/2,a.height/2,a.width/2,a.height);p.addChild(q);a=s_oSpriteLibrary.getSprite("highlight");
b={images:[a],frames:{width:a.width/3,height:a.height,regX:a.width/3/2,regY:a.height/2},animations:{yellow:[0],green:[1],red:[2]}};b=new createjs.SpriteSheet(b);m=createSprite(b,"yellow",a.width/3/2,a.height/2,a.width/2,a.height);m.alpha=.9;m.visible=!1;p.addChild(m);f=[];a=k/3;f[1]={x:-a,y:-a};f[2]={x:0,y:-a};f[3]={x:a,y:-a};f[4]={x:-a,y:0};f[5]={x:0,y:0};f[6]={x:a,y:0};f[7]={x:-a,y:a};f[8]={x:0,y:a};f[9]={x:+a,y:a};this.clearAllNote();a=s_oSpriteLibrary.getSprite("cell_selected");t=createBitmap(a);
t.regX=a.width/2;t.regY=a.height/2;t.visible=!1;p.addChild(t);(new createjs.Graphics).beginFill("rgba(158,158,158,0.01)").drawRect(-k/2,-k/2,k,k);p.on("click",this._setActive)};this.unload=function(){d.removeChild(p)};this.setGiven=function(a){0!==a&&(q.gotoAndStop("grey"),c=!0);this.setNumber(a)};this.getGiven=function(){return c};this.setHintNumber=function(a){0!==a&&(this.clearNumber(),this.clearAllNote(),n=new createjs.Text(a,"bold 80px Arial","#add8fd"),n.textAlign="center",n.textBaseline="middle",
p.addChild(n),g=a)};this.setNumber=function(a){0!==a&&(this.clearNumber(),this.clearAllNote(),n=new createjs.Text(a,"bold 80px Arial","#000000"),n.textAlign="center",n.textBaseline="middle",p.addChild(n),g=a)};this.getNumber=function(){return g};this.clearNumber=function(){g=0;p.removeChild(n)};this.setNote=function(a){0===g&&(0!==h[a]?this.clearNote(a):(h[a]=new createjs.Text(a," 30px Arial","#000000"),h[a].textAlign="center",h[a].textBaseline="middle",h[a].x=f[a].x,h[a].y=f[a].y,p.addChild(h[a])))};
this.setHelpNote=function(a){this.clearNote(a);h[a]=new createjs.Text(a," 30px Arial","#000000");h[a].textAlign="center";h[a].textBaseline="middle";h[a].x=f[a].x;h[a].y=f[a].y;p.addChild(h[a])};this.getNote=function(a){return h[a]};this.clearNote=function(a){p.removeChild(h[a]);h[a]=0};this.clearAllNote=function(){for(var a=1;10>a;a++)p.removeChild(h[a]),h[a]=0};this.clearCell=function(){this.clearNumber();this.clearAllNote()};this.highlight=function(a){m.visible=!0;"off"!==a?m.gotoAndStop(a):m.visible=
!1};this.setCorner=function(a){t.visible=a?!0:!1};this._setActive=function(){k.highlight("yellow");s_oGame.activeCell(l)};k=this;this._init(a,e,b,d)}
function CSpriteLibrary(){var a,e,b,d,c,g;this.init=function(f,h,k){b=e=0;d=f;c=h;g=k;a={}};this.addSprite=function(b,c){a.hasOwnProperty(b)||(a[b]={szPath:c,oSprite:new Image},e++)};this.getSprite=function(b){return a.hasOwnProperty(b)?a[b].oSprite:null};this._onSpritesLoaded=function(){c.call(g)};this._onSpriteLoaded=function(){d.call(g);++b==e&&this._onSpritesLoaded()};this.loadSprites=function(){for(var b in a)a[b].oSprite.oSpriteLibrary=this,a[b].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
a[b].oSprite.src=a[b].szPath};this.getNumSprites=function(){return e}}
var CANVAS_WIDTH=1080,CANVAS_HEIGHT=1920,EDGEBOARD_X=25,EDGEBOARD_Y=200,CELL_SIZE=106,FPS_TIME=1E3/24,DISABLE_SOUND_MOBILE=!1,TIME_LOOP_WAIT=2E3,STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,EASY_MODE=0,MEDIUM_MODE=1,HARD_MODE=2,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,MAX_GIVENS_EASY,MAX_GIVENS_MEDIUM,MAX_GIVENS_HARD,RANGE_GIVENS=0,LOWER_BOUND_EASY=4,LOWER_BOUND_MEDIUM=3,LOWER_BOUND_HARD=2;
function CToggle(a,e,b,d){var c,g,f,h;this._init=function(a,b,d,e){g=[];f=[];var t=new createjs.SpriteSheet({images:[d],frames:{width:d.width/2,height:d.height,regX:d.width/2/2,regY:d.height/2},animations:{state_true:[0],state_false:[1]}});c=e;h=createSprite(t,"state_"+c,d.width/2/2,d.height/2,d.width/2,d.height);h.x=a;h.y=b;h.stop();s_oStage.addChild(h);this._initListener()};this.unload=function(){h.off("mousedown",this.buttonDown);h.off("pressup",this.buttonRelease);s_oStage.removeChild(h)};this._initListener=
function(){h.on("mousedown",this.buttonDown);h.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){g[a]=b;f[a]=c};this.setActive=function(a){c=a;h.gotoAndStop("state_"+c)};this.buttonRelease=function(){h.scaleX=1;h.scaleY=1;!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");c=!c;h.gotoAndStop("state_"+c);g[ON_MOUSE_UP]&&g[ON_MOUSE_UP].call(f[ON_MOUSE_UP],c)};this.buttonDown=function(){h.scaleX=.9;h.scaleY=.9;g[ON_MOUSE_DOWN]&&g[ON_MOUSE_DOWN].call(f[ON_MOUSE_DOWN])};
this.setPosition=function(a,b){h.x=a;h.y=b};this._init(a,e,b,d)}var s_iScaleFactor=1,s_oCanvasLeft,s_oCanvasTop;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,4))})(navigator.userAgent||
navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});$(window).blur(function(){s_oMain.stopUpdate()});$(window).focus(function(){s_oMain.startUpdate()});function trace(a){console.log(a)}
function getSize(a){var e=a.toLowerCase(),b=window.document,d=b.documentElement;if(void 0===window["inner"+a])a=d["client"+a];else if(window["inner"+a]!=d["client"+a]){var c=b.createElement("body");c.id="vpw-test-b";c.style.cssText="overflow:scroll";var g=b.createElement("div");g.id="vpw-test-d";g.style.cssText="position:absolute;top:-1000px";g.innerHTML="<style>@media("+e+":"+d["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+e+":7px!important}}</style>";c.appendChild(g);d.insertBefore(c,b.head);
a=7==g["offset"+a]?d["client"+a]:window["inner"+a];d.removeChild(c)}else a=window["inner"+a];return a}$(window).ready(function(){sizeHandler()});window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}
function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a;a=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var e=getSize("Width"),b=Math.min(a/CANVAS_HEIGHT,e/CANVAS_WIDTH),d=CANVAS_WIDTH*b,b=CANVAS_HEIGHT*b,c=0;b<a?(c=a-b,b+=c,d+=CANVAS_WIDTH/CANVAS_HEIGHT*c):d<e&&(c=e-d,d+=c,b+=CANVAS_HEIGHT/CANVAS_WIDTH*c);var c=a/2-b/2,g=e/2-d/2,f=CANVAS_WIDTH/d;if(g*f<-EDGEBOARD_X||c*f<-EDGEBOARD_Y)b=Math.min(a/(CANVAS_HEIGHT-2*EDGEBOARD_Y),e/(CANVAS_WIDTH-2*
EDGEBOARD_X)),d=CANVAS_WIDTH*b,b*=CANVAS_HEIGHT,c=(a-b)/2,g=(e-d)/2,f=CANVAS_WIDTH/d;s_iOffsetX=-1*g*f;s_iOffsetY=-1*c*f;0<=c&&(s_iOffsetY=0);0<=g&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);$("#canvas").css("width",d+"px");$("#canvas").css("height",b+"px");0>c?$("#canvas").css("top",c+"px"):$("#canvas").css("top","0px");$("#canvas").css("left",g+"px")}}
function createBitmap(a,e,b){var d=new createjs.Bitmap(a),c=new createjs.Shape;e&&b?c.graphics.beginFill("#fff").drawRect(0,0,e,b):c.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);d.hitArea=c;return d}function createSprite(a,e,b,d,c,g){a=null!==e?new createjs.Sprite(a,e):new createjs.Sprite(a);e=new createjs.Shape;e.graphics.beginFill("#000000").drawRect(-b,-d,c,g);a.hitArea=e;return a}
function randomFloatBetween(a,e,b){"undefined"===typeof b&&(b=2);return parseFloat(Math.min(a+Math.random()*(e-a),e).toFixed(b))}function rotateVector2D(a,e){var b=e.getX()*Math.cos(a)+e.getY()*Math.sin(a),d=e.getX()*-Math.sin(a)+e.getY()*Math.cos(a);e.set(b,d)}function tweenVectorsOnX(a,e,b){return a+b*(e-a)}function shuffle(a){for(var e=a.length,b,d;0!==e;)d=Math.floor(Math.random()*e),--e,b=a[e],a[e]=a[d],a[d]=b;return a}
function bubbleSort(a){var e;do{e=!1;for(var b=0;b<a.length-1;b++)a[b]>a[b+1]&&(e=a[b],a[b]=a[b+1],a[b+1]=e,e=!0)}while(e)}function compare(a,e){return a.index>e.index?-1:a.index<e.index?1:0}function easeLinear(a,e,b,d){return b*a/d+e}function easeInQuad(a,e,b,d){return b*(a/=d)*a+e}function easeInSine(a,e,b,d){return-b*Math.cos(a/d*(Math.PI/2))+b+e}function easeInCubic(a,e,b,d){return b*(a/=d)*a*a+e}
function getTrajectoryPoint(a,e){var b=new createjs.Point,d=(1-a)*(1-a),c=a*a;b.x=d*e.start.x+2*(1-a)*a*e.traj.x+c*e.end.x;b.y=d*e.start.y+2*(1-a)*a*e.traj.y+c*e.end.y;return b}function formatTime(a){a/=1E3;var e=Math.floor(a/60);a=Math.floor(a-60*e);var b="",b=10>e?b+("0"+e+":"):b+(e+":");return 10>a?b+("0"+a):b+a}function degreesToRadians(a){return a*Math.PI/180}function checkRectCollision(a,e){var b,d;b=getBounds(a,.9);d=getBounds(e,.98);return calculateIntersection(b,d)}
function calculateIntersection(a,e){var b,d,c,g,f,h,k,l;b=a.x+(c=a.width/2);d=a.y+(g=a.height/2);f=e.x+(h=e.width/2);k=e.y+(l=e.height/2);b=Math.abs(b-f)-(c+h);d=Math.abs(d-k)-(g+l);return 0>b&&0>d?(b=Math.min(Math.min(a.width,e.width),-b),d=Math.min(Math.min(a.height,e.height),-d),{x:Math.max(a.x,e.x),y:Math.max(a.y,e.y),width:b,height:d,rect1:a,rect2:e}):null}
function dlx_cover(a){a.right.left=a.left;a.left.right=a.right;for(var e=a.down;e!==a;e=e.down)for(var b=e.right;b!==e;b=b.right)b.down.up=b.up,b.up.down=b.down,b.column.size--}function dlx_uncover(a){for(var e=a.up;e!==a;e=e.up)for(var b=e.left;b!==e;b=b.left)b.column.size++,b.down.up=b,b.up.down=b;a.right.left=a;a.left.right=a}
function dlx_search(a,e,b,d,c){if(a.right===a)return d.push(e.slice(0)),d.length>=c?d:null;for(var g=null,f=99999,h=a.right;h!==a;h=h.right){if(0===h.size)return null;h.size<f&&(f=h.size,g=h)}dlx_cover(g);for(var k=g.down;k!==g;k=k.down){e[b]=k.row;for(h=k.right;h!==k;h=h.right)dlx_cover(h.column);f=dlx_search(a,e,b+1,d,c);if(null!==f)return f;for(h=k.left;h!==k;h=h.left)dlx_uncover(h.column)}dlx_uncover(g);return null}
function dlx_solve(a,e,b){for(var d=Array(a[0].length),c=0;c<d.length;c++)d[c]={};for(c=0;c<d.length;c++)d[c].index=c,d[c].up=d[c],d[c].down=d[c],c>=e?(c-1>=e&&(d[c].left=d[c-1]),c+1<d.length&&(d[c].right=d[c+1])):(d[c].left=d[c],d[c].right=d[c]),d[c].size=0;for(c=0;c<a.length;c++)for(var g=null,f=0;f<a[c].length;f++)if(a[c][f]){var h={};h.row=c;h.column=d[f];h.up=d[f].up;h.down=d[f];g?(h.left=g,h.right=g.right,g.right.left=h,g.right=h):(h.left=h,h.right=h);d[f].up.down=h;d[f].up=h;d[f].size++;g=
h}a={};a.right=d[e];a.left=d[d.length-1];d[e].left=a;d[d.length-1].right=a;solutions=[];dlx_search(a,[],0,solutions,b);return solutions}
function solve_sudoku(a){for(var e=[],b=[],d=0;9>d;d++)for(var c=0;9>c;c++){var g=a[d][c]-1;if(0<=g){var f=Array(324);f[9*d+c]=1;f[81+9*d+g]=1;f[162+9*c+g]=1;f[243+9*(3*Math.floor(d/3)+Math.floor(c/3))+g]=1;e.push(f);b.push({row:d,col:c,n:g+1})}else for(g=0;9>g;g++)f=Array(324),f[9*d+c]=1,f[81+9*d+g]=1,f[162+9*c+g]=1,f[243+9*(3*Math.floor(d/3)+Math.floor(c/3))+g]=1,e.push(f),b.push({row:d,col:c,n:g+1})}e=dlx_solve(e,0,2);if(0<e.length){c=e[0];for(d=0;d<c.length;d++)a[b[c[d]].row][b[c[d]].col]=b[c[d]].n;
return e.length}return 0}function solve(a){a=solve_sudoku(a);if(0<a){if(1<a)return 1}else return trace("no solution"),0}
function getBounds(a,e){var b={x:Infinity,y:Infinity,width:0,height:0};if(a instanceof createjs.Container){b.x2=-Infinity;b.y2=-Infinity;var d=a.children,c=d.length,g,f;for(f=0;f<c;f++)g=getBounds(d[f],1),g.x<b.x&&(b.x=g.x),g.y<b.y&&(b.y=g.y),g.x+g.width>b.x2&&(b.x2=g.x+g.width),g.y+g.height>b.y2&&(b.y2=g.y+g.height);Infinity==b.x&&(b.x=0);Infinity==b.y&&(b.y=0);Infinity==b.x2&&(b.x2=0);Infinity==b.y2&&(b.y2=0);b.width=b.x2-b.x;b.height=b.y2-b.y;delete b.x2;delete b.y2}else{var h,k;a instanceof createjs.Bitmap?
(c=a.sourceRect||a.image,f=c.width*e,h=c.height*e):a instanceof createjs.Sprite?a.spriteSheet._frames&&a.spriteSheet._frames[a.currentFrame]&&a.spriteSheet._frames[a.currentFrame].image?(c=a.spriteSheet.getFrame(a.currentFrame),f=c.rect.width,h=c.rect.height,d=c.regX,k=c.regY):(b.x=a.x||0,b.y=a.y||0):(b.x=a.x||0,b.y=a.y||0);d=d||0;f=f||0;k=k||0;h=h||0;b.regX=d;b.regY=k;c=a.localToGlobal(0-d,0-k);g=a.localToGlobal(f-d,h-k);f=a.localToGlobal(f-d,0-k);d=a.localToGlobal(0-d,h-k);b.x=Math.min(Math.min(Math.min(c.x,
g.x),f.x),d.x);b.y=Math.min(Math.min(Math.min(c.y,g.y),f.y),d.y);b.width=Math.max(Math.max(Math.max(c.x,g.x),f.x),d.x)-b.x;b.height=Math.max(Math.max(Math.max(c.y,g.y),f.y),d.y)-b.y}return b}function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}function shuffle(a){for(var e=a.length,b,d;0<e;)d=Math.floor(Math.random()*e),e--,b=a[e],a[e]=a[d],a[d]=b;return a}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3==a.nodeType&&(a=a.parentNode);var e=document.createEvent("MouseEvents");e.initEvent("click",!0,!0);a.dispatchEvent(e)}}};
(function(){function a(a){var d={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};a=a||window.event;a.type in d?document.body.className=d[a.type]:(document.body.className=this[e]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var e="hidden";e in document?document.addEventListener("visibilitychange",a):(e="mozHidden")in document?document.addEventListener("mozvisibilitychange",a):(e="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",a):(e="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a})();
function CTextButton(a,e,b,d,c,g,f){var h,k,l,m,q;this._init=function(a,b,c,d,e,f,g){h=[];k=[];var r=createBitmap(c),z=Math.ceil(g/20);q=new createjs.Text(d," "+g+"px "+e,"#000000");q.textAlign="center";q.textBaseline="alphabetic";var u=q.getBounds();q.x=c.width/2+z;q.y=Math.floor(c.height/2)+u.height/3+z;m=new createjs.Text(d," "+g+"px "+e,f);m.textAlign="center";m.textBaseline="alphabetic";u=m.getBounds();m.x=c.width/2;m.y=Math.floor(c.height/2)+u.height/3-9;l=new createjs.Container;l.x=a;l.y=b;
l.regX=c.width/2;l.regY=c.height/2;l.addChild(r,q,m);s_oStage.addChild(l);this._initListener()};this.unload=function(){l.off("mousedown");l.off("pressup");s_oStage.removeChild(l)};this.setVisible=function(a){l.visible=a};this._initListener=function(){oParent=this;l.on("mousedown",this.buttonDown);l.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){h[a]=b;k[a]=c};this.buttonRelease=function(){l.scaleX=1;l.scaleY=1;!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");
h[ON_MOUSE_UP]&&h[ON_MOUSE_UP].call(k[ON_MOUSE_UP])};this.buttonDown=function(){l.scaleX=.9;l.scaleY=.9;h[ON_MOUSE_DOWN]&&h[ON_MOUSE_DOWN].call(k[ON_MOUSE_DOWN])};this.setNoShadow=function(){l.removeChild(q)};this.setTextPosition=function(a){m.y=a;q.y=a+2};this.setPosition=function(a,b){l.x=a;l.y=b};this.setX=function(a){l.x=a};this.setY=function(a){l.y=a};this.getButtonImage=function(){return l};this.getX=function(){return l.x};this.getY=function(){return l.y};this._init(a,e,b,d,c,g,f);return this}
function CSudokuLoader(){var a,e,b,d,c,g;this._init=function(){a=!0;e=0;b=new createjs.Container;var f=(new createjs.Graphics).beginFill("rgba(0,0,0,0.8)").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);g=new createjs.Shape(f);g.on("click",function(){});d=new createjs.Text(TEXT_GENERATE_SUDOKU,"bold 60px Arial","#ffffff");d.x=.5*CANVAS_WIDTH;d.y=.5*CANVAS_HEIGHT-100;d.textAlign="center";d.textBaseline="alphabetic";d.lineWidth=800;c=new createjs.Text("","bold 180px Arial","#ffffff");c.x=.5*CANVAS_WIDTH-
76;c.y=.5*CANVAS_HEIGHT+50;c.textAlign="left";c.textBaseline="alphabetic";c.lineWidth=800;b.addChild(g,d,c);s_oStage.addChild(b)};this.unload=function(){a=!1;s_oStage.removeChild(b)};this.update=function(){a&&(e+=s_iTimeElaps,0<=e&&e<TIME_LOOP_WAIT/4?c.text="":e>=TIME_LOOP_WAIT/4&&e<2*TIME_LOOP_WAIT/4?c.text=".":e>=2*TIME_LOOP_WAIT/4&&e<3*TIME_LOOP_WAIT/4?c.text="..":e>=3*TIME_LOOP_WAIT/4&&e<TIME_LOOP_WAIT?c.text="...":e=0)};s_oSudokuLoader=this;this._init()}var s_oSudokuLoader;
function CPreloader(){var a,e,b,d,c,g,f;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.loadSprites();f=new createjs.Container;s_oStage.addChild(f)};this.unload=function(){f.removeAllChildren()};this.hide=function(){var a=this;setTimeout(function(){createjs.Tween.get(g).to({alpha:1},500).call(function(){a.unload();
s_oMain.gotoMenu()})},1E3)};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var h=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));f.addChild(h);h=s_oSpriteLibrary.getSprite("progress_bar");d=createBitmap(h);d.x=CANVAS_WIDTH/2-h.width/2;d.y=CANVAS_HEIGHT-250;f.addChild(d);a=h.width;e=h.height;c=new createjs.Shape;c.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(d.x,d.y,1,e);f.addChild(c);d.mask=
c;b=new createjs.Text("","40px Arial","#008df0");b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT-205;b.textBaseline="alphabetic";b.textAlign="center";f.addChild(b);g=new createjs.Shape;g.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);g.alpha=0;f.addChild(g)};this.refreshLoader=function(f){b.text=f+"%";c.graphics.clear();f=Math.floor(f*a/100);c.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(d.x,d.y,f,e)};this._init()}
function CNumButton(a,e,b){var d,c,g,f,h,k,l,m,q;this._init=function(a,b,e){g=!1;f=e;m=new createjs.Container;m.x=a;m.y=b;s_oStage.addChild(m);b=s_oSpriteLibrary.getSprite("but_num");k=createBitmap(b);a=b.width;b=b.height;k.regX=a/2;k.regY=b/2;l=new createjs.Text(e,"Bold 90px Arial","#000000");l.textAlign="center";l.textBaseline="middle";m.addChild(k,l);d=a/3-2;c=-b/3+5;this.setCounter(0);this._initListener()};this.unload=function(){m.off("mousedown");m.off("pressup");s_oStage.removeChild(m)};this._initListener=
function(){m.on("mousedown",this.buttonDown);m.on("pressup",this.buttonRelease)};this.buttonRelease=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");m.scaleX=1;m.scaleY=1;g?(s_oGame.setCurNum(f),s_oInterface.setAllBlackColor(),h.changeNumColor(!0)):s_oGame.writeNum(f)};this.buttonDown=function(){m.scaleX=.9;m.scaleY=.9};this.changeNumColor=function(a){l.color=a?"#ff8814":"#000000"};this.changeMode=function(){g=!g};this.setCounter=function(a){q=new createjs.Text(a,
" 30px Arial","#000000");q.textAlign="center";q.textBaseline="middle";q.x=d;q.y=c;m.addChild(q)};this.clearCounter=function(){m.removeChild(q)};h=this;this._init(a,e,b)}
function CModeMenu(){var a,e,b,d,c,g,f,h,k,l,m,q,t;this._init=function(){a=createBitmap(s_oSpriteLibrary.getSprite("bg_mode_menu"));s_oStage.addChild(a);m=new createjs.Text(TEXT_TOP_MODE," 100px blackplotan","#008df0");m.x=CANVAS_WIDTH/2;m.y=200;m.textAlign="center";m.lineWidth=800;s_oStage.addChild(m);var n=CANVAS_WIDTH/2;e=new createjs.Container;e.x=n;e.y=350;b=new createjs.Container;b.x=n;b.y=800;d=new createjs.Container;d.x=n;d.y=1250;c=new createjs.Text(TEXT_EASY," 50px blackplotan","#008df0");
c.textBaseline="alphabetic";c.textAlign="center";c.lineWidth=400;e.addChild(c);var p=s_oSpriteLibrary.getSprite("mod_easy_icon");g=new CGfxButton(n,530,p,s_oStage);g.addEventListener(ON_MOUSE_UP,this._selectEasy,this);f=new createjs.Text(TEXT_MEDIUM," 50px blackplotan","#008df0");f.textBaseline="alphabetic";f.textAlign="center";f.lineWidth=400;b.addChild(f);p=s_oSpriteLibrary.getSprite("mod_medium_icon");h=new CGfxButton(n,980,p,s_oStage);h.addEventListener(ON_MOUSE_UP,this._selectMedium,this);k=
new createjs.Text(TEXT_HARD," 50px blackplotan","#008df0");k.textBaseline="alphabetic";k.textAlign="center";k.lineWidth=400;d.addChild(k);p=s_oSpriteLibrary.getSprite("mod_hard_icon");l=new CGfxButton(n,1430,p,s_oStage);l.addEventListener(ON_MOUSE_UP,this._selectHard,this);s_oStage.addChild(e,b,d);t=new createjs.Shape;t.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(t);createjs.Tween.get(t).to({alpha:0},400).call(function(){t.visible=!1})};this._selectEasy=
function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");q.unload();s_oMain.gotoGame(0)};this._selectMedium=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");q.unload();s_oMain.gotoGame(1)};this._selectHard=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");q.unload();s_oMain.gotoGame(2)};this.unload=function(){s_oStage.removeAllChildren();a=null};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);
s_bAudioActive=!s_bAudioActive};this._onButPlayRelease=function(){this.unload();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");s_oMain.gotoGame()};q=this;this._init()}
function CMenu(){var a,e,b,d,c,g;this._init=function(){b=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(b);var f=s_oSpriteLibrary.getSprite("but_play");d=new CTextButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-600,f,TEXT_PLAY,"blackplotan","#ffffff",130);d.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);d.setNoShadow();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)f=s_oSpriteLibrary.getSprite("audio_icon"),a=CANVAS_WIDTH-f.height/2-10,e=f.height/2+10,g=new CToggle(a,e,f,s_bAudioActive),
g.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);c=new createjs.Shape;c.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(c);createjs.Tween.get(c).to({alpha:0},1E3).call(function(){c.visible=!1});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){d.unload();d=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)g.unload(),g=null;s_oStage.removeChild(b);s_oMenu=b=null};this.refreshButtonPos=function(b,c){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||
g.setPosition(a-b,c+e)};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onButPlayRelease=function(){this.unload();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");s_oMain.goToModeMenu()};s_oMenu=this;this._init()}var s_oMenu=null;
function CMain(a){var e,b=0,d=0,c=STATE_LOADING,g,f,h;this.initContainer=function(){s_oCanvas=document.getElementById("canvas");s_oStage=new createjs.Stage(s_oCanvas);createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&(s_oStage.enableMouseOver(20),$("body").on("contextmenu","#canvas",function(a){return!1}));s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.setFPS(20);navigator.userAgent.match(/Windows Phone/i)&&(DISABLE_SOUND_MOBILE=
!0);s_oSpriteLibrary=new CSpriteLibrary;f=new CPreloader};this.preloaderReady=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();this._loadImages()};this.soundLoaded=function(){b++;f.refreshLoader(Math.floor(b/d*100));b===d&&(f.unload(),this.gotoMenu())};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&(0<navigator.userAgent.indexOf("Opera")||0<navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=["m4a"],createjs.Sound.addEventListener("fileload",
createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/press_button.ogg","click"),createjs.Sound.registerSound("./sounds/game_over.ogg","game_over")):(createjs.Sound.alternateExtensions=["ogg"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/press_button.m4a","click"),createjs.Sound.registerSound("./sounds/game_over.mp3","game_over")),d+=2)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,
this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("bg_mode_menu","./sprites/bg_mode_menu.jpg");s_oSpriteLibrary.addSprite("mod_easy_icon","./sprites/mod_easy_icon.png");s_oSpriteLibrary.addSprite("mod_medium_icon","./sprites/mod_medium_icon.png");s_oSpriteLibrary.addSprite("mod_hard_icon","./sprites/mod_hard_icon.png");
s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("bg_help","./sprites/bg_help.png");s_oSpriteLibrary.addSprite("bg_help2","./sprites/bg_help2.png");s_oSpriteLibrary.addSprite("arrow","./sprites/arrow.png");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("config_icon","./sprites/config_icon.png");s_oSpriteLibrary.addSprite("but_help_icon","./sprites/but_help_icon.png");
s_oSpriteLibrary.addSprite("but_help_note","./sprites/but_help_note.png");s_oSpriteLibrary.addSprite("but_del_note","./sprites/but_del_note.png");s_oSpriteLibrary.addSprite("but_solve","./sprites/but_solve.png");s_oSpriteLibrary.addSprite("but_reset","./sprites/but_reset.png");s_oSpriteLibrary.addSprite("but_time","./sprites/but_time.png");s_oSpriteLibrary.addSprite("but_help_hint","./sprites/but_help_hint.png");s_oSpriteLibrary.addSprite("time_display","./sprites/time_display.png");s_oSpriteLibrary.addSprite("given_bg",
"./sprites/given_bg.png");s_oSpriteLibrary.addSprite("blank","./sprites/blank.png");s_oSpriteLibrary.addSprite("background","./sprites/background.png");s_oSpriteLibrary.addSprite("highlight","./sprites/highlight.png");s_oSpriteLibrary.addSprite("cell_selected","./sprites/cell_selected.png");s_oSpriteLibrary.addSprite("but_num","./sprites/but_num.png");s_oSpriteLibrary.addSprite("but_del_toggle","./sprites/but_del_toggle.png");s_oSpriteLibrary.addSprite("note_toggle","./sprites/note_toggle.png");s_oSpriteLibrary.addSprite("mode_toggle",
"./sprites/mode_toggle.png");d+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){b++;f.refreshLoader(Math.floor(b/d*100));b===d&&(f.unload(),this.gotoMenu())};this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this.gotoMenu=function(){new CMenu;c=STATE_MENU};this.goToModeMenu=function(){new CModeMenu;c=STATE_MENU};this.gotoGame=function(a){s_iDifficultyMode=a;h=new CGame(g);c=STATE_GAME;$(s_oMain).trigger("game_start")};
this.gotoHelp=function(){new CHelp;c=STATE_HELP};this.stopUpdate=function(){e=!1};this.startUpdate=function(){s_iPrevTime=(new Date).getTime();e=!0};this._update=function(a){if(!1!==e){var b=(new Date).getTime();s_iTimeElaps=b-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=b;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);c===STATE_GAME&&h.update();s_oStage.update(a)}};s_oMain=this;g=a;this.initContainer()}
var s_bMobile,s_iDifficultyMode,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oCanvas;TEXT_GAMEOVER="YOU COMPLETED ";TEXT_SUDOKU=" SUDOKU";TEXT_IN=" IN ";TEXT_HELP_USED="YOU USED FOLLOWING HELP:";TEXT_HELPS_USED="YOU USED FOLLOWING HELPS:";TEXT_HELP_NOTE="NOTES AUTOFILL";TEXT_HELP_SOLVE="SOLVER";TEXT_HELP_TIME="SET NO TIME";TEXT_HELP_HINT=" HINT";TEXT_HELP_HINTS=" HINTS";TEXT_SCORE="SCORE";TEXT_PLAY="PLAY";
TEXT_RESTART="RESTART";TEXT_TIME="TIME";TEXT_GENERATE_SUDOKU="GENERATING SUDOKU. PLEASE WAIT";TEXT_TOP_MODE="SELECT YOUR LEVEL";TEXT_EASY="BEGINNER";TEXT_MEDIUM="INTERMEDIATE";TEXT_HARD="ADVANCED";TEXT_HELP0="RULES";TEXT_HELP1="FILL IN THE BLANKS WITH NUMBERS FROM 1 TO 9. EACH ROW, COLUMN OR 3X3 BLOCK, MUST CONTAIN THE NUMBER 1 THROUGH 9 EXACTLY ONCE";TEXT_HELP0_PAGE2="HOW-TO";TEXT_HELP1_PAGE2="USE KEYBOARD OR NUMBER BUTTONS TO FILL IN THE BLANKS. THERE ARE 3 DIFFERENT GAME MODES:";
TEXT_HELP1_MOB_PAGE2="USE NUMBER BUTTONS TO FILL BLANKS IN GAME. THERE ARE 3 DIFFERENT GAME MODES:";TEXT_HELP2_PAGE2='"CELL FIRST" MODE: CLICK FIRST THE CELL YOU WANT TO FILL IN, THEN SELECT THE NUMBER YOU WANT TO ENTER';TEXT_HELP3_PAGE2='"NUMBER FIRST" MODE: SELECT THE NUMBER YOU WANT TO ENTER FIRST, THEN CLICK THE CELL YOU WANT TO FILL IN';TEXT_HELP4_PAGE2="MEMO MODE: THIS BUTTON ALLOWS YOU TO WRITE DOWN A MEMO IN A BLANK";TEXT_FILL_WITH_NOTE="FILL THE BOARD WITH NOTES";TEXT_DELETE_ALL_NOTE="DELETE ALL NOTES";
TEXT_SOLVE="SOLVE THE SUDOKU";TEXT_RESET="RESET THE SUDOKU";TEXT_SETNOTIME="PLAY WITHOUT TIME";TEXT_GETHINT="GET A HINT";