TEXT_GAMEOVER="YOU WIN";TEXT_SCORE="SCORE";TEXT_PLAY="PLAY";TEXT_RESTART="RESTART";TEXT_MOVES="MOVES";TEXT_SCORE="SCORE";TEXT_HELP1="THE CARD PILES IN BOARD, CAN BE BUILD DOWN BY DECRESCENT CARD RANK WITH ALTERNATE COLORS";TEXT_HELP2="YOU CAN USE A FREE CELL, TO TEMPORARILY DISCARD A CARD. ANYWAY THIS WILL REDUCE THE NUMBER OF CARDS YOU CAN DRAG SIMULTANEOUSLY";TEXT_HELP3="THE GOAL IS TO BUILD UP FOUR FOUNDATIONS BY SUIT, FROM ACE TO KING ";TEXT_HINT="NOT ENOUGH EMPTY FREE CELLS. NOW YOU CAN MOVE JUST ";
TEXT_HINT2=" AT ONCE";TEXT_HINT_MOVE="NO MORE MOVES AVAILABLES. RESTART THE GAME.";TEXT_HELP1_PAGE2="SCORE SYSTEM";TEXT_HELP2_PAGE2="You start with ";TEXT_HELP3_PAGE2=" points";TEXT_LOSE1_PAGE2="Every time you move a card from its position you lose ";TEXT_LOSE2_PAGE2=" point!! Try to complete the game with as few moves as possible!";
function CInterface(){var a,d,b,e,c=null,g,h,f,n,k,t,r,x,z;this._init=function(){var c,p=s_oSpriteLibrary.getSprite("but_exit");d=new CGfxButton(CANVAS_WIDTH-p.height/2-10,p.height/2+10,p,!0);d.addEventListener(ON_MOUSE_UP,this._onExit,this);c=CANVAS_WIDTH-p.width/2-80;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)p=s_oSpriteLibrary.getSprite("audio_icon"),a=new CToggle(c,10+p.height/2,p,s_bAudioActive),a.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);c-=68;p=s_oSpriteLibrary.getSprite("but_help");
b=new CGfxButton(c,10+p.height/2,p,!0);b.addEventListener(ON_MOUSE_UP,this._onButHelpRelease,this);b.setVisible(!1);c-=120;p=s_oSpriteLibrary.getSprite("but_restart");e=new CTextButton(c,10+p.height/2,p,TEXT_RESTART,"Arial","#ffffff",26);e.addEventListener(ON_MOUSE_UP,this._onButRestartRelease,this);e.setTextPosition(35);g=new createjs.Text(TEXT_SCORE,"bold 24px Arial","#ffffff");g.x=30;g.y=45;g.textAlign="left";g.textBaseline="alphabetic";g.lineWidth=200;s_oStage.addChild(g);p=s_oSpriteLibrary.getSprite("score_display");
h=createBitmap(p);h.scaleX=1;h.x=116;h.y=15;s_oStage.addChild(h);f=new createjs.Text("0","bold 24px Arial","#ffffff");f.x=189;f.y=45;f.textAlign="right";f.textBaseline="alphabetic";f.lineWidth=200;s_oStage.addChild(f);k=new createjs.Text(TEXT_MOVES,"bold 24px Arial","#ffffff");k.x=222;k.y=45;k.textAlign="left";k.textBaseline="alphabetic";k.lineWidth=200;s_oStage.addChild(k);p=s_oSpriteLibrary.getSprite("moves_display");n=createBitmap(p);n.x=310;n.y=15;s_oStage.addChild(n);t=new createjs.Text("0",
"bold 24px Arial","#ffffff");t.x=383;t.y=45;t.textAlign="right";t.textBaseline="alphabetic";t.lineWidth=200;s_oStage.addChild(t);c=s_oSpriteLibrary.getSprite("hintpanel");r=createBitmap(c);x=new createjs.Text(TEXT_HINT,"bold 14px Arial","#ffffff");x.x=15;x.y=25;x.textAlign="left";x.textBaseline="alphabetic";x.lineWidth=200;z=new createjs.Container;z.addChild(r,x);z.x=CANVAS_WIDTH/2-c.width/2;z.y=540;z.alpha=0;s_oStage.addChild(z)};this.unload=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)a.unload(),
a=null;z.off("mousedown",this._onButRestartRelease);d.unload();b.unload();e.unload();null!==c&&c.unload()};this.refreshScore=function(b){f.alpha=1;f.text=b};this.fadeScore=function(b,a){var d=this;createjs.Tween.get(f).to({alpha:0},a,createjs.Ease.linear).call(function(){d.refreshScore(b)})};this._refreshMove=function(b){t.alpha=1;t.text=b};this.fadeMove=function(b,a){var d=this;createjs.Tween.get(t).to({alpha:0},a,createjs.Ease.linear).call(function(){d._refreshMove(b)})};this.showHint=function(b,
a){if("move"===b){x.text=TEXT_HINT_MOVE;r.scaleX=.9;r.scaleY=1.5;x.lineWidth=180;var d=this;createjs.Tween.get(z,{override:!0}).to({alpha:1},3E3,createjs.Ease.linear).call(function(){d.callRestart()})}else{var e=" CARDS";1===a&&(e=" CARD");x.text=TEXT_HINT+a+e+TEXT_HINT2;r.scaleX=.99;r.scaleY=1.5;x.lineWidth=220;createjs.Tween.get(z,{override:!0}).to({alpha:1},3E3,createjs.Ease.linear).call(function(){createjs.Tween.get(z).to({alpha:0},3E3,createjs.Ease.linear)})}};this.callRestart=function(){z.on("mousedown",
this._onButRestartRelease)};this.setVisibleButHelp=function(){b.setVisible(!0)};this._onButHelpRelease=function(){c=new CHelpPanel};this._onButRestartRelease=function(){s_oGame.restartGame()};this.onExitFromHelp=function(){c.unload()};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onExit=function(){s_oGame.onExit()};this._init();return this}
function CHelpPanel(){var a,d,b,e,c,g,h,f,n,k,t,r,x,z,D,p,A,q,C;this._init=function(){var w=this;x=createBitmap(s_oSpriteLibrary.getSprite("bg_help"));var E=CANVAS_WIDTH/2+50,y=CANVAS_HEIGHT/2-240;d=new createjs.Text(TEXT_HELP1," 24px Arial","#000000");d.x=E+2;d.y=y+2;d.textAlign="center";d.lineWidth=400;a=new createjs.Text(TEXT_HELP1," 24px Arial","#ffffff");a.x=E;a.y=y;a.textAlign="center";a.lineWidth=400;E=CANVAS_WIDTH/2-130;y=CANVAS_HEIGHT/2-40;e=new createjs.Text(TEXT_HELP2," 24px Arial","#000000");
e.x=E+2;e.y=y+2;e.textAlign="center";e.lineWidth=280;b=new createjs.Text(TEXT_HELP2," 24px Arial","#ffffff");b.x=E;b.y=y;b.textAlign="center";b.lineWidth=280;E=CANVAS_WIDTH/2+190;y=CANVAS_HEIGHT/2+100;g=new createjs.Text(TEXT_HELP3," 24px Arial","#000000");g.x=E+2;g.y=y+2;g.textAlign="center";g.lineWidth=230;c=new createjs.Text(TEXT_HELP3," 24px Arial","#ffffff");c.x=E;c.y=y;c.textAlign="center";c.lineWidth=230;A=new createjs.Container;A.addChild(x,d,a,e,b,g,c);A.alpha=0;s_oStage.addChild(A);createjs.Tween.get(A).to({alpha:1},
700);A.on("pressup",function(){w._onExitHelp()});z=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));h=new createjs.Text(TEXT_HELP1_PAGE2," 30px Arial","#000000");h.x=CANVAS_WIDTH/2+2;h.y=CANVAS_HEIGHT/2-200;h.textAlign="center";h.lineWidth=400;f=new createjs.Text(TEXT_HELP1_PAGE2," 30px Arial","#ffffff");f.x=CANVAS_WIDTH/2;f.y=CANVAS_HEIGHT/2-202;f.textAlign="center";f.lineWidth=400;n=new createjs.Text(TEXT_HELP2_PAGE2+START_SCORE+TEXT_HELP3_PAGE2," 30px Arial","#000000");n.x=CANVAS_WIDTH/2+2;
n.y=CANVAS_HEIGHT/2-100;n.textAlign="center";n.lineWidth=400;k=new createjs.Text(TEXT_HELP2_PAGE2+START_SCORE+TEXT_HELP3_PAGE2," 30px Arial","#ffffff");k.x=CANVAS_WIDTH/2;k.y=CANVAS_HEIGHT/2-102;k.textAlign="center";k.lineWidth=400;r=new createjs.Text(TEXT_LOSE1_PAGE2+POINTS_TO_LOSE+TEXT_LOSE2_PAGE2," 28px Arial","#000000");r.x=CANVAS_WIDTH/2-328;r.y=CANVAS_HEIGHT/2+32;r.textAlign="left";r.lineWidth=670;t=new createjs.Text(TEXT_LOSE1_PAGE2+POINTS_TO_LOSE+TEXT_LOSE2_PAGE2," 28px Arial","#ffffff");
t.x=CANVAS_WIDTH/2-330;t.y=CANVAS_HEIGHT/2+30;t.textAlign="left";t.lineWidth=670;q=new createjs.Container;q.addChild(z,h,f,n,k,r,t);q.visible=0;s_oStage.addChild(q);q.on("pressup",function(){w._onExitHelp()});createjs.Tween.get(q).to({alpha:1},700);D=createBitmap(s_oSpriteLibrary.getSprite("arrow"));D.x=1E3;D.y=500;D.alpha=0;D.on("click",w._changePageTo2);s_oStage.addChild(D);p=createBitmap(s_oSpriteLibrary.getSprite("arrow"));p.scaleX=-1;p.x=140;p.y=500;p.visible=!1;p.on("click",w._changePageTo1);
s_oStage.addChild(p);createjs.Tween.get(D).to({alpha:1},700)};this.unload=function(){s_oStage.removeChild(A,q,D,p);var b=this;A.off("pressup",function(){b._onExitHelp()});q.off("pressup",function(){b._onExitHelp()})};this._changePageTo1=function(){q.visible=!1;p.visible=!1;A.visible=!0;D.visible=!0};this._changePageTo2=function(){A.visible=!1;D.visible=!1;q.visible=!0;p.visible=!0};this._onExitHelp=function(){C.unload();s_oGame._onExitHelp()};C=this;this._init()}
function CGfxButton(a,d,b){var e,c,g;this._init=function(b,a,d){e=[];c=[];g=createBitmap(d);g.x=b;g.y=a;g.regX=d.width/2;g.regY=d.height/2;s_oStage.addChild(g);this._initListener()};this.unload=function(){g.off("mousedown",this.buttonDown);g.off("pressup",this.buttonRelease);s_oStage.removeChild(g)};this.setVisible=function(b){g.visible=b};this._initListener=function(){g.on("mousedown",this.buttonDown);g.on("pressup",this.buttonRelease)};this.addEventListener=function(b,a,d){e[b]=a;c[b]=d};this.buttonRelease=
function(){g.scaleX=1;g.scaleY=1;e[ON_MOUSE_UP]&&e[ON_MOUSE_UP].call(c[ON_MOUSE_UP])};this.buttonDown=function(){g.scaleX=.9;g.scaleY=.9;e[ON_MOUSE_DOWN]&&e[ON_MOUSE_DOWN].call(c[ON_MOUSE_DOWN])};this.setPosition=function(b,a){g.x=b;g.y=a};this.setX=function(b){g.x=b};this.setY=function(b){g.y=b};this.getButtonImage=function(){return g};this.getX=function(){return g.x};this.getY=function(){return g.y};this._init(a,d,b);return this}
function CGame(a){var d,b,e,c,g,h,f,n,k,t,r,x,z,D,p,A,q,C,w,E,y,u,F,H,m,B,I,M=null,J,v,K;this._init=function(){n=f=!0;t=k=!1;p=25;A=0;q=5;r=START_SCORE;x=0;H=[];B=[];u=[];for(var a=0;4>a;a++)u[a]=null;a=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(a);J=new createjs.Container;s_oStage.addChild(J);I=new CInterface;I.refreshScore(r);w=[];for(a=0;4>a;a++)w[a]=1;C=[];C[SUIT_HEARTS]={x:1062,y:147};C[SUIT_SPADES]={x:1062,y:285};C[SUIT_DIAMONDS]={x:1062,y:419};C[SUIT_CLUBS]={x:1062,
y:554};E=[];for(a=0;4>a;a++)E[a]=new createjs.Rectangle(C[a].x-CARD_WIDTH/2,C[a].y-CARD_HEIGHT/2,CARD_WIDTH,CARD_HEIGHT);y=[{x:72,y:147},{x:72,y:284},{x:72,y:419},{x:72,y:555}];d=CANVAS_WIDTH/2;b=CANVAS_HEIGHT-100;var e=0;F=[];for(a=0;7>a;a++)for(var g=0;8>g;g++)F[e]={x:217+100*g,y:148+a*p},e++;m=[];for(a=0;25>a;a++)for(m[a]=[],g=0;8>g;g++)m[a][g]={status:LABEL_EMPTY,oCard:null};this._shuffleCard(!0);this._setBoard();s_bMobile?window.navigator.msPointerEnabled?(s_oCanvas.addEventListener("MSPointerMove",
this.onTouchMoveMS,!1),s_oCanvas.addEventListener("MSPointerUp",this.releaseCard,!1)):(s_oCanvas.addEventListener("touchmove",this.onTouchMove,!1),s_oCanvas.addEventListener("touchend",this.releaseCard,!1)):(s_oStage.addEventListener("stagemousemove",this.dragCard,!1),s_oStage.addEventListener("stagemouseup",this.releaseCard,!1))};this._shuffleCard=function(a){for(var e=-1,g=[],l=0;52>l;l++){var c=(l+1)%13;1===c?e++:0===c&&(c=13);g.push({fotogram:l,rank:c,suit:e})}e=[];for(l=0;l<g.length;l++)e[l]=
g[l];for(c=[];0<e.length;)c.push(e.splice(Math.round(Math.random()*(e.length-1)),1)[0]);if(a)for(l=0;l<c.length;l++)H[l]=new CCard(d,b,J,c[l].fotogram,c[l].rank,c[l].suit);else for(l=0;l<c.length;l++)H[l]=new CCard(d,b,J,g[l].fotogram,g[l].rank,g[l].suit)};this._setBoard=function(){for(var a=0,b=H.length-1,d=0;52>d;d++)H[51-d].moveCard(F[d].x,F[d].y,100,a),H[51-d].setType("board"),a+=100;for(d=0;7>d;d++)for(a=0;8>a&&!(m[d][a].oCard=H[b],m[d][a].status=LABEL_SHOWN,b--,0>b);a++);};this.scaleDepth=function(a){J.setChildIndex(a.getSprite(),
A);A++;a.showCard();52===A&&(n=f=!1,I.setVisibleButHelp())};this.pickCard=function(a,b){var d;if(0===B.length&&!f){f=!0;g=a.getPos().x;h=a.getPos().y;e=b.stageX-g;c=b.stageY-h;for(d=0;8>d;d++)for(var l=m.length-1;0<=l;l--)m[l][d].oCard===a&&(v={row:l,column:d});if("freecell"===a.checkType())l=a.saveInfo(),B[0]=new CCard(g,h,J,l.szFotogram,l.iRank,l.iSuit),B[0].setType("freecell"),B[0].instantShow(),a.unload();else if("board"===a.checkType()){d=1;var G=a.getRank(),L=a.getColor(),k=v.row+q,n=!1;if(m[k][v.column].status===
LABEL_SHOWN){for(l=v.row;l<m.length-1&&m[l+1][v.column].status!==LABEL_EMPTY;l++)if(m[l+1][v.column].oCard.getColor()!==L&&m[l+1][v.column].oCard.getRank()===G-1)n=!0,G--,L=m[l+1][v.column].oCard.getColor();else{n=!1;break}n&&I.showHint("drag",q)}else{G=a.getRank();L=a.getColor();for(l=v.row;l<k;l++)if(m[l+1][v.column].status===LABEL_SHOWN&&m[l+1][v.column].oCard.getColor()!==L&&m[l+1][v.column].oCard.getRank()===G-1)d++,G--,L=m[l+1][v.column].oCard.getColor();else if(m[l+1][v.column].status===LABEL_EMPTY)break;
else return;G=[];for(l=0;l<d;l++)G[l]=m[v.row+l][v.column].oCard.saveInfo(),B[l]=new CCard(g,h+l*p,J,G[l].szFotogram,G[l].iRank,G[l].iSuit),B[l].setType("board"),m[v.row+l][v.column].oCard.unload(),B[l].instantShow()}}else l=a.saveInfo(),B[0]=new CCard(g,h,J,l.szFotogram,l.iRank,l.iSuit),B[0].setType("suit"),B[0].instantShow(),a.unload()}};this.dragCard=function(a){if(!n&&f)for(var b=0;b<B.length;b++)B[b].setPos(a.stageX-e,a.stageY-c+b*p)};this.releaseCard=function(a){!1===n&&0<B.length?(f=!1,K._checkFreeCellCollision(B),
k||K._checkSuitCollision(B),k||t||K._checkCardCollision(B),K._controlBoard(),v=null,B=[],t=k=!1):f=!1};this._checkCardCollision=function(a){for(var b=0,d=[],e=[],c=0;8>c;c++)for(var f=m.length-1;0<=f;f--)if(m[f][c].status===LABEL_SHOWN){d[b]=m[f][c].oCard.getLogicRect();e[b]={oCard:m[f][c].oCard,x:m[f][c].oCard.getPos().x,y:m[f][c].oCard.getPos().y,row:f,column:c};b++;break}else 0===f&&(d[b]=new createjs.Rectangle(F[c].x-CARD_WIDTH/2,F[c].y-CARD_HEIGHT/2,CARD_WIDTH,CARD_HEIGHT),b++);for(var b=0,c=
-1,k=a[0].getLogicRect(),f=0;f<d.length;f++){var n=k.intersection(d[f]);null!==n&&b<n.width*n.height&&(b=n.width*n.height,c=f)}if(0>c)if("freecell"===a[0].checkType())a[0].stackInPlace(g,h,200);else if("board"===a[0].checkType())for(f=0;f<a.length;f++)a[f].stackInPlace(g,h+f*p,200),m[v.row+f][v.column].oCard=a[f];else a[0].stackInPlace(g,h,200);else if(m[0][c].status===LABEL_EMPTY){if("freecell"===a[0].checkType())for(a[0].stackInPlace(F[c].x,F[c].y,200),a[0].setType("board"),m[0][c].status=LABEL_SHOWN,
m[0][c].oCard=a[0],f=0;f<u.length;f++)null!==u[f]&&a[0].getRank()===u[f].getRank()&&a[0].getSuit()===u[f].getSuit()&&(u[f]=null);else if("board"===a[0].checkType())for(f=0;f<a.length;f++)a[f].stackInPlace(F[c].x,F[c].y+f*p,200),a[f].setType("board"),m[f][c].status=LABEL_SHOWN,m[v.row+f][v.column].status=LABEL_EMPTY,m[f][c].oCard=a[f];else a[0].stackInPlace(F[c].x,F[c].y,200),a[0].setType("board"),m[0][c].status=LABEL_SHOWN,m[0][c].oCard=a[0],w[a[0].getSuit()]--;this._updateMoves();this._removeScore()}else if(1===
e[c].oCard.getRank()-a[0].getRank()&&e[c].oCard.getColor()!==a[0].getColor()){if("freecell"===a[0].checkType())for(a[0].stackInPlace(e[c].x,e[c].y+p,200),a[0].setType("board"),m[e[c].row+1][c].status=LABEL_SHOWN,m[e[c].row+1][c].oCard=a[0],f=0;f<u.length;f++)null!==u[f]&&a[0].getRank()===u[f].getRank()&&a[0].getSuit()===u[f].getSuit()&&(u[f]=null);else if("board"===a[0].checkType())for(f=0;f<a.length;f++)a[f].stackInPlace(e[c].x,e[c].y+p+f*p,200),m[e[c].row+1+f][e[c].column].status=LABEL_SHOWN,m[v.row+
f][v.column].status=LABEL_EMPTY,m[e[c].row+1+f][e[c].column].oCard=a[f];else a[0].stackInPlace(e[c].x,e[c].y+p,200),a[0].setType("board"),m[e[c].row+1][c].status=LABEL_SHOWN,m[e[c].row+1][c].oCard=a[0],w[a[0].getSuit()]--;this._updateMoves();this._removeScore()}else if("freecell"===a[0].checkType())a[0].stackInPlace(g,h,200);else if("board"===a[0].checkType())for(f=0;f<a.length;f++)a[f].stackInPlace(g,h+f*p,200),m[v.row+f][v.column].oCard=a[f];else a[0].stackInPlace(g,h,200)};this._checkFreeCellCollision=
function(a){if(!(1<a.length)){for(var b=[],d=0;4>d;d++)b[d]=null===u[d]?new createjs.Rectangle(y[d].x-CARD_WIDTH/2,y[d].y-CARD_HEIGHT/2,CARD_WIDTH,CARD_HEIGHT):new createjs.Rectangle(y[d].x-CARD_WIDTH/2,y[d].y-CARD_HEIGHT/2,0,0);for(var c=0,e=-1,f=a[0].getLogicRect(),d=0;d<b.length;d++){var g=f.intersection(b[d]);null!==g&&c<g.width*g.height&&(c=g.width*g.height,e=d)}if(!(0>e)){if("freecell"===a[0].checkType()){for(d=0;d<u.length;d++)null!==u[d]&&a[0].getRank()===u[d].getRank()&&a[0].getSuit()===
u[d].getSuit()&&(u[d]=null);a[0].stackInPlace(y[e].x,y[e].y,200)}else"board"===a[0].checkType()?(a[0].setType("freecell"),a[0].stackInPlace(y[e].x,y[e].y,200),m[v.row][v.column].status=LABEL_EMPTY):(a[0].setType("freecell"),a[0].stackInPlace(y[e].x,y[e].y,200));u[e]=a[0];k=!0;this._updateMoves();this._removeScore()}}};this._checkSuitCollision=function(a){if(!(1<a.length||"suit"===a[0].checkType())){for(var b=0,d=-1,e=a[0].getLogicRect(),c=0;c<E.length;c++){var f=e.intersection(E[c]);null!==f&&b<f.width*
f.height&&(b=f.width*f.height,d=c)}if(!(0>d)&&a[0].getRank()===w[a[0].getSuit()]&&d===a[0].getSuit()){if("freecell"===a[0].checkType()){for(c=0;c<u.length;c++)null!==u[c]&&a[0].getRank()===u[c].getRank()&&a[0].getSuit()===u[c].getSuit()&&(u[c]=null);a[0].stackInPlace(C[d].x,C[d].y,200)}else a[0].stackInPlace(C[d].x,C[d].y,200),m[v.row][v.column].status=LABEL_EMPTY;w[a[0].getSuit()]++;a[0].setType("suit");t=!0;this._updateMoves();this._removeScore()}}};this._controlBoard=function(){for(var a=0,b=0;b<
u.length;b++)null===u[b]&&a++;q=a+1;if(14===w[0]&&14===w[1]&&14===w[2]&&14===w[3])this.gameOver();else{for(var a=[],d=[],c=0;8>c;c++)for(b=m.length-1;0<=b;b--)if(m[b][c].status===LABEL_SHOWN){a.push(m[b][c].oCard);d.push({row:b,column:c});break}if(!(8>a.length)){for(var e=[],f=[],c=0;8>c;c++){var g=a[c].getRank(),h;h="red"===a[c].getColor()?"black":"red";for(b=d[c].row;b>=d[c].row-q+1;b--)if(0>b){f.push(m[0][c].oCard);break}else if(m[b][c].oCard.getRank()===g&&m[b][c].oCard.getColor()!==h)e.push({oCard:m[b][c].oCard,
row:b,column:c}),h=m[b][c].oCard.getColor(),g++;else{f.push(m[b+1][c].oCard);break}}for(b=0;b<u.length;b++){if(null===u[b])return;for(c=0;c<a.length;c++)if(u[b].getRank()===a[c].getRank()-1&&u[b].getColor()!==a[c].getColor())return;if(u[b].getRank()===w[u[b].getSuit()])return}for(b=0;b<a.length;b++){if(a[b].getRank()===w[a[b].getSuit()])return;for(c=0;c<e.length;c++)if(a[b].getRank()===e[c].oCard.getRank()+1&&a[b].getColor()!==e[c].oCard.getColor()){if(0===e[c].row)return;d=[];h=m[e[c].row-1][e[c].column].oCard;
var n=e[c].row-1,g=h.getRank();h="red"===h.getColor()?"black":"red";for(var k=n;k>=n-q+1&&!(0>k);k--)if(m[k][c].oCard.getRank()===g&&m[k][c].oCard.getColor()!==h)d.push({oCard:m[k][c].oCard,row:k,column:c}),h=m[k][c].oCard.getColor(),g++;else break;for(k=0;k<d.length;k++){if(0===k)for(g=0;g<f.length;g++)if(d[k].oCard.getRank()===f[g].getRank()+1&&d[k].oCard.getColor()===f[g].getColor())return;if(d[k].oCard.getRank()===w[d[k].oCard.getSuit()])return;for(g=0;g<a.length;g++)if(d[k].oCard.getRank()===
a[g].getRank()-1&&d[k].oCard.getColor()!==a[g].getColor()&&b!==g)return}}}for(b=0;b<w.length;b++)for(e=0===b%2?"red":"black",c=0;c<a.length;c++)if(w[b]===a[c].getRank()&&e!==a[c].getColor())return;I.showHint("move",q)}}};this.onTouchMove=function(a){a.preventDefault();if(!n&&f)for(z=parseInt((a.touches[0].pageX-s_oCanvasLeft)/s_iScaleFactor),D=parseInt((a.touches[0].pageY-s_oCanvasTop)/s_iScaleFactor),a=0;a<B.length;a++)B[a].setPos(z-e,D-c+a*p)};this.onTouchMoveMS=function(a){if(!window.navigator.msPointerEnabled||
a.isPrimary)if(a.preventDefault(),!n&&f)for(z=parseInt(((a.pageX||a.targetTouches[0].pageX)-s_oCanvasLeft)/s_iScaleFactor),D=parseInt(((a.pageY||a.targetTouches[0].pageY)-s_oCanvasTop)/s_iScaleFactor),a=0;a<B.length;a++)B[a].setPos(z-e,D-c+a*p)};this._calculateScore=function(a,b){(new CScore).showScore(a.getPos(),b)};this._removeScore=function(){r-=POINTS_TO_LOSE;0>r&&(r=0);(new CScore).removeScore(r,750);I.fadeScore(r,750)};this.updateScore=function(a){r+=a;I.refreshScore(r)};this._updateMoves=function(){x++;
(new CScore).displayMoves(x,750);I.fadeMove(x,750)};this.restartGame=function(){this.unload();this._init()};this.unload=function(){n=!1;for(var a=0;a<H.length;a++)H[a].unload();I.unload();null!==M&&M.unload();createjs.Tween.removeAllTweens();s_oStage.removeAllChildren()};this.onExit=function(){this.unload();s_oMain.gotoMenu();$(s_oMain).trigger("restart")};this._onExitHelp=function(){_bStartGame=!0};this.gameOver=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("game_over");
M=CEndPanel(s_oSpriteLibrary.getSprite("msg_box"));M.show(r)};this.update=function(){};s_oGame=this;POINTS_TO_LOSE=a.points_to_lose;START_SCORE=a.starting_points;K=this;this._init()}var s_oGame;
function CEndPanel(a){var d,b,e,c,g,h;this._init=function(a){d=createBitmap(a);d.x=0;d.y=0;e=new createjs.Text("","bold 60px Arial","#000");e.x=CANVAS_WIDTH/2+1;e.y=CANVAS_HEIGHT/2-160;e.textAlign="center";c=new createjs.Text("","bold 60px Arial","#ffffff");c.x=CANVAS_WIDTH/2;c.y=CANVAS_HEIGHT/2-162;c.textAlign="center";g=new createjs.Text("","bold 40px Arial","#000");g.x=CANVAS_WIDTH/2+1;g.y=CANVAS_HEIGHT/2+50;g.textAlign="center";h=new createjs.Text("","bold 40px Arial","#ffffff");h.x=CANVAS_WIDTH/
2;h.y=CANVAS_HEIGHT/2+52;h.textAlign="center";b=new createjs.Container;b.alpha=0;b.visible=!1;b.addChild(d,g,h,e,c);s_oStage.addChild(b)};this.unload=function(){b.off("mousedown",this._onExit)};this._initListener=function(){b.on("mousedown",this._onExit)};this.show=function(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("game_over");e.text=TEXT_GAMEOVER;c.text=TEXT_GAMEOVER;g.text=TEXT_SCORE+": "+a;h.text=TEXT_SCORE+": "+a;b.visible=!0;var d=this;createjs.Tween.get(b).to({alpha:1},
500).call(function(){d._initListener()});$(s_oMain).trigger("save_score",a)};this._onExit=function(){b.off("mousedown",this._onExit);s_oStage.removeChild(b);s_oGame.onExit()};this._init(a);return this}
function CCard(a,d,b,e,c,g){var h=!1,f,n,k,t,r,x,z,D,p,A,q,C,w;this._init=function(a,b,c,d,e,g){C=c;t=d;r=e;x=g;f=!1;n="deck";k=0===x||2===x?"red":"black";q=new createjs.Container;q.x=a;q.y=b;C.addChild(q);a={images:[s_oSpriteLibrary.getSprite("card_spritesheet")],frames:{width:CARD_WIDTH,height:CARD_HEIGHT,regX:CARD_WIDTH/2,regY:CARD_HEIGHT/2},animations:{card_1_1:[0],card_1_2:[1],card_1_3:[2],card_1_4:[3],card_1_5:[4],card_1_6:[5],card_1_7:[6],card_1_8:[7],card_1_9:[8],card_1_10:[9],card_1_J:[10],
card_1_Q:[11],card_1_K:[12],card_2_1:[13],card_2_2:[14],card_2_3:[15],card_2_4:[16],card_2_5:[17],card_2_6:[18],card_2_7:[19],card_2_8:[20],card_2_9:[21],card_2_10:[22],card_2_J:[23],card_2_Q:[24],card_2_K:[25],card_3_1:[26],card_3_2:[27],card_3_3:[28],card_3_4:[29],card_3_5:[30],card_3_6:[31],card_3_7:[32],card_3_8:[33],card_3_9:[34],card_3_10:[35],card_3_J:[36],card_3_Q:[37],card_3_K:[38],card_4_1:[39],card_4_2:[40],card_4_3:[41],card_4_4:[42],card_4_5:[43],card_4_6:[44],card_4_7:[45],card_4_8:[46],
card_4_9:[47],card_4_10:[48],card_4_J:[49],card_4_Q:[50],card_4_K:[51],back:[52]}};a=new createjs.SpriteSheet(a);p=createSprite(a,"back",0,0,CARD_WIDTH,CARD_HEIGHT);p.stop();q.addChild(p);A=new createjs.Shape;A.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(-CARD_WIDTH/2,-CARD_HEIGHT/2,CARD_WIDTH,CARD_HEIGHT);A.on("mousedown",this._mouseDown);q.addChild(A);z=[];D=[]};this.unload=function(){A.off("mousedown",this._mouseDown);C.removeChild(q)};this.saveInfo=function(){return{szFotogram:t,iRank:r,
iSuit:x,bValue:!0}};this.changeInfo=function(a,b,c){t=a;r=b;x=c};this.instantShow=function(){p.gotoAndStop(t)};this.setType=function(a){n=a};this.checkType=function(){return n};this.setValue=function(a){p.gotoAndStop(t);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("card");createjs.Tween.get(q).to({scaleX:1},200)};this.setActive=function(a){a?q.addChild(A):q.removeChild(A)};this.setVisible=function(a){q.visible=!0===a?!0:!1};this.moveCard=function(a,b,c,d){createjs.Tween.get(q).wait(d).to({x:a,
y:b},c,createjs.Ease.linear).call(function(){w.setPlaced()})};this.moveDeckCard=function(a,b,c,d){createjs.Tween.get(q).wait(d).to({x:a,y:b},c,createjs.Ease.linear).call(function(){s_oGame.activeDeck();w.showCard()})};this.moveToSuit=function(a,b,c){createjs.Tween.get(q).wait(c).to({x:a,y:b},200,createjs.Ease.cubicOut).call(function(){s_oGame.stackInSuit(w)})};this.setPlaced=function(){h=!0;s_oGame.scaleDepth(w)};this.stackInPlace=function(a,b,c){createjs.Tween.get(q).to({x:a,y:b},c,createjs.Ease.cubicOut).call(function(){f=
!0})};this.stackAndDeactive=function(a,b,c){createjs.Tween.get(q).to({x:a,y:b},c,createjs.Ease.cubicOut)};this._mouseDown=function(a){!1!==f&&(C.getChildIndex(q),s_oGame.pickCard(w,a))};this.getPlaced=function(){return h};this.showCard=function(){var a=this;createjs.Tween.get(q).to({scaleX:.1},200).call(function(){a.setValue()}).call(function(){f=!0})};this.hideCard=function(){var a=this;createjs.Tween.get(q).to({scaleX:.1},200).call(function(){a.setBack()})};this.setPos=function(a,b){q.x=a;q.y=b};
this.setBack=function(){f=!1;p.gotoAndStop("back");var a=this;createjs.Tween.get(q).to({scaleX:1},200).call(function(){a.cardHidden()})};this.cardHidden=function(){z[ON_CARD_HIDE]&&z[ON_CARD_HIDE].call(D[ON_CARD_HIDE],this)};this.getRank=function(){return r};this.getSuit=function(){return x};this.getColor=function(){return k};this.getFotogram=function(){return t};this.getPos=function(){return{x:q.x,y:q.y}};this.getSprite=function(){return q};this.getLogicRect=function(){return new createjs.Rectangle(q.x-
CARD_WIDTH/2,q.y-CARD_HEIGHT/2,CARD_WIDTH,CARD_HEIGHT)};w=this;this._init(a,d,b,e,c,g)}
function CSpriteLibrary(){var a,d,b,e,c,g;this.init=function(h,f,n){b=d=0;e=h;c=f;g=n;a={}};this.addSprite=function(b,c){a.hasOwnProperty(b)||(a[b]={szPath:c,oSprite:new Image},d++)};this.getSprite=function(b){return a.hasOwnProperty(b)?a[b].oSprite:null};this._onSpritesLoaded=function(){c.call(g)};this._onSpriteLoaded=function(){e.call(g);++b==d&&this._onSpritesLoaded()};this.loadSprites=function(){for(var b in a)a[b].oSprite.oSpriteLibrary=this,a[b].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
a[b].oSprite.src=a[b].szPath};this.getNumSprites=function(){return d}}
var CANVAS_WIDTH=1136,CANVAS_HEIGHT=640,FPS_TIME=1E3/24,DISABLE_SOUND_MOBILE=!1,STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,STATE_GAME_WAITING_FOR_BET=0,STATE_GAME_DEAL=1,STATE_GAME_CHOOSE_HOLD=2,STATE_GAME_DRAW=3,STATE_GAME_EVALUATE=4,ON_CARD_SHOWN="ON_CARD_SHOWN",ON_CARD_HIDE="ON_CARD_HIDE",ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,SUIT_HEARTS=0,SUIT_SPADES=1,SUIT_DIAMONDS=2,SUIT_CLUBS=3,LABEL_EMPTY=0,LABEL_HIDDEN=1,LABEL_SHOWN=2,CARD_WIDTH=
79,CARD_HEIGHT=121,POINTS_TO_LOSE,START_SCORE;
function CToggle(a,d,b,e){var c,g,h,f;this._init=function(a,b,d,e){g=[];h=[];var x=new createjs.SpriteSheet({images:[d],frames:{width:d.width/2,height:d.height,regX:d.width/2/2,regY:d.height/2},animations:{state_true:[0],state_false:[1]}});c=e;f=createSprite(x,"state_"+c,d.width/2/2,d.height/2,d.width/2,d.height);f.x=a;f.y=b;f.stop();s_oStage.addChild(f);this._initListener()};this.unload=function(){f.off("mousedown",this.buttonDown);f.off("pressup",this.buttonRelease);s_oStage.removeChild(f)};this._initListener=
function(){f.on("mousedown",this.buttonDown);f.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){g[a]=b;h[a]=c};this.setActive=function(a){c=a;f.gotoAndStop("state_"+c)};this.buttonRelease=function(){f.scaleX=1;f.scaleY=1;!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");c=!c;f.gotoAndStop("state_"+c);g[ON_MOUSE_UP]&&g[ON_MOUSE_UP].call(h[ON_MOUSE_UP],c)};this.buttonDown=function(){f.scaleX=.9;f.scaleY=.9;g[ON_MOUSE_DOWN]&&g[ON_MOUSE_DOWN].call(h[ON_MOUSE_DOWN])};
this._init(a,d,b,e)}var s_iScaleFactor=1,s_oCanvasLeft,s_oCanvasTop;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,4))})(navigator.userAgent||
navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}$(window).ready(function(){sizeHandler()});window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a=CANVAS_WIDTH,d=CANVAS_HEIGHT,b=window.innerWidth;multiplier=s_iScaleFactor=Math.min(window.innerHeight/d,b/a);a*=multiplier;d*=multiplier;$("#canvas").css("width",a+"px");$("#canvas").css("height",d+"px");$("#canvas").css("left",b/2-a/2+"px");s_oCanvasLeft=$("#canvas").offset().left;s_oCanvasTop=$("#canvas").offset().top}}
function createBitmap(a,d,b){var e=new createjs.Bitmap(a),c=new createjs.Shape;d&&b?c.graphics.beginFill("#fff").drawRect(0,0,d,b):c.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);e.hitArea=c;return e}function createSprite(a,d,b,e,c,g){a=null!==d?new createjs.Sprite(a,d):new createjs.Sprite(a);d=new createjs.Shape;d.graphics.beginFill("#000000").drawRect(-b,-e,c,g);a.hitArea=d;return a}
function randomFloatBetween(a,d,b){"undefined"===typeof b&&(b=2);return parseFloat(Math.min(a+Math.random()*(d-a),d).toFixed(b))}function shuffle(a){for(var d=a.length,b,e;0!==d;)e=Math.floor(Math.random()*d),--d,b=a[d],a[d]=a[e],a[e]=b;return a}function bubbleSort(a){var d;do{d=!1;for(var b=0;b<a.length-1;b++)a[b]>a[b+1]&&(d=a[b],a[b]=a[b+1],a[b+1]=d,d=!0)}while(d)}function easeLinear(a,d,b,e){return b*a/e+d}function easeInQuad(a,d,b,e){return b*(a/=e)*a+d}
function easeInSine(a,d,b,e){return-b*Math.cos(a/e*(Math.PI/2))+b+d}function easeInCubic(a,d,b,e){return b*(a/=e)*a*a+d}function getTrajectoryPoint(a,d){var b=new createjs.Point,e=(1-a)*(1-a),c=a*a;b.x=e*d.start.x+2*(1-a)*a*d.traj.x+c*d.end.x;b.y=e*d.start.y+2*(1-a)*a*d.traj.y+c*d.end.y;return b}function formatTime(a){a/=1E3;var d=Math.floor(a/60);a=parseFloat(a-60*d).toFixed(1);var b="",b=10>d?b+("0"+d+":"):b+(d+":");return b=10>a?b+("0"+a):b+a}function degreesToRadians(a){return a*Math.PI/180}
function checkRectCollision(a,d){var b,e;b=getBounds(a,.9);e=getBounds(d,.98);return calculateIntersection(b,e)}function calculateIntersection(a,d){var b,e,c,g,h,f,n,k;b=a.x+(c=a.width/2);e=a.y+(g=a.height/2);h=d.x+(f=d.width/2);n=d.y+(k=d.height/2);b=Math.abs(b-h)-(c+f);e=Math.abs(e-n)-(g+k);return 0>b&&0>e?(b=Math.min(Math.min(a.width,d.width),-b),e=Math.min(Math.min(a.height,d.height),-e),{x:Math.max(a.x,d.x),y:Math.max(a.y,d.y),width:b,height:e,rect1:a,rect2:d}):null}
function getBounds(a,d){var b={x:Infinity,y:Infinity,width:0,height:0};if(a instanceof createjs.Container){b.x2=-Infinity;b.y2=-Infinity;var e=a.children,c=e.length,g,h;for(h=0;h<c;h++)g=getBounds(e[h],1),g.x<b.x&&(b.x=g.x),g.y<b.y&&(b.y=g.y),g.x+g.width>b.x2&&(b.x2=g.x+g.width),g.y+g.height>b.y2&&(b.y2=g.y+g.height);Infinity==b.x&&(b.x=0);Infinity==b.y&&(b.y=0);Infinity==b.x2&&(b.x2=0);Infinity==b.y2&&(b.y2=0);b.width=b.x2-b.x;b.height=b.y2-b.y;delete b.x2;delete b.y2}else{var f,n;a instanceof createjs.Bitmap?
(c=a.sourceRect||a.image,h=c.width*d,f=c.height*d):a instanceof createjs.Sprite?a.spriteSheet._frames&&a.spriteSheet._frames[a.currentFrame]&&a.spriteSheet._frames[a.currentFrame].image?(c=a.spriteSheet.getFrame(a.currentFrame),h=c.rect.width,f=c.rect.height,e=c.regX,n=c.regY):(b.x=a.x||0,b.y=a.y||0):(b.x=a.x||0,b.y=a.y||0);e=e||0;h=h||0;n=n||0;f=f||0;b.regX=e;b.regY=n;c=a.localToGlobal(0-e,0-n);g=a.localToGlobal(h-e,f-n);h=a.localToGlobal(h-e,0-n);e=a.localToGlobal(0-e,f-n);b.x=Math.min(Math.min(Math.min(c.x,
g.x),h.x),e.x);b.y=Math.min(Math.min(Math.min(c.y,g.y),h.y),e.y);b.width=Math.max(Math.max(Math.max(c.x,g.x),h.x),e.x)-b.x;b.height=Math.max(Math.max(Math.max(c.y,g.y),h.y),e.y)-b.y}return b}function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}function shuffle(a){for(var d=a.length,b,e;0<d;)e=Math.floor(Math.random()*d),d--,b=a[d],a[d]=a[e],a[e]=b;return a}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3==a.nodeType&&(a=a.parentNode);var d=document.createEvent("MouseEvents");d.initEvent("click",!0,!0);a.dispatchEvent(d)}}};
(function(){function a(a){var e={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};a=a||window.event;a.type in e?document.body.className=e[a.type]:(document.body.className=this[d]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var d="hidden";d in document?document.addEventListener("visibilitychange",a):(d="mozHidden")in document?document.addEventListener("mozvisibilitychange",a):(d="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",a):(d="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a})();
function CTextButton(a,d,b,e,c,g,h){var f,n,k,t,r;this._init=function(a,b,c,d,e,g,h){f=[];n=[];var w=createBitmap(c),E=Math.ceil(h/20);r=new createjs.Text(d,"bold "+h+"px "+e,"#000000");r.textAlign="center";r.textBaseline="alphabetic";var y=r.getBounds();r.x=c.width/2+E;r.y=Math.floor(c.height/2)+y.height/3+E;t=new createjs.Text(d,"bold "+h+"px "+e,g);t.textAlign="center";t.textBaseline="alphabetic";y=t.getBounds();t.x=c.width/2;t.y=Math.floor(c.height/2)+y.height/3;k=new createjs.Container;k.x=a;
k.y=b;k.regX=c.width/2;k.regY=c.height/2;k.addChild(w,r,t);s_oStage.addChild(k);this._initListener()};this.unload=function(){k.off("mousedown");k.off("pressup");s_oStage.removeChild(k)};this.setVisible=function(a){k.visible=a};this._initListener=function(){oParent=this;k.on("mousedown",this.buttonDown);k.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){f[a]=b;n[a]=c};this.buttonRelease=function(){k.scaleX=1;k.scaleY=1;f[ON_MOUSE_UP]&&f[ON_MOUSE_UP].call(n[ON_MOUSE_UP])};this.buttonDown=
function(){k.scaleX=.9;k.scaleY=.9;f[ON_MOUSE_DOWN]&&f[ON_MOUSE_DOWN].call(n[ON_MOUSE_DOWN])};this.setTextPosition=function(a){t.y=a;r.y=a+2};this.setPosition=function(a,b){k.x=a;k.y=b};this.setX=function(a){k.x=a};this.setY=function(a){k.y=a};this.getButtonImage=function(){return k};this.getX=function(){return k.x};this.getY=function(){return k.y};this._init(a,d,b,e,c,g,h);return this}
function CScore(){this.showScore=function(a,d){var b=new createjs.Text("+"+d,"bold 24px Arial","#000000");b.x=a.x;b.y=a.y;b.scaleX=2;b.scaleY=2;b.textAlign="right";b.textBaseline="alphabetic";b.outline=4;s_oStage.addChild(b);var e=new createjs.Text("+"+d,"bold 24px Arial","#fff");e.x=a.x;e.y=a.y;e.scaleX=2;e.scaleY=2;e.textAlign="right";e.textBaseline="alphabetic";s_oStage.addChild(e);createjs.Tween.get(e).to({x:193,y:45},1E3,createjs.Ease.cubicIn).call(function(){s_oGame.updateScore(d);s_oStage.removeChild(e)});
createjs.Tween.get(e).to({scaleX:1,scaleY:1},1E3,createjs.Ease.linear);createjs.Tween.get(b).to({x:193,y:45},1E3,createjs.Ease.cubicIn).call(function(){s_oStage.removeChild(b)});createjs.Tween.get(b).to({scaleX:1,scaleY:1},1E3,createjs.Ease.linear)};this.removeScore=function(a,d){var b=new createjs.Text(a,"bold 24px Arial","#ffffff");b.x=189;b.y=45;b.alpha=0;b.textAlign="right";b.textBaseline="alphabetic";b.lineWidth=200;s_oStage.addChild(b);createjs.Tween.get(b).to({alpha:1},d,createjs.Ease.linear).call(function(){s_oStage.removeChild(b)})};
this.displayMoves=function(a,d){var b=new createjs.Text(a,"bold 24px Arial","#ffffff");b.x=383;b.y=45;b.alpha=0;b.textAlign="right";b.textBaseline="alphabetic";b.lineWidth=200;s_oStage.addChild(b);createjs.Tween.get(b).to({alpha:1},d,createjs.Ease.linear).call(function(){s_oStage.removeChild(b)})}}
function CPreloader(){var a,d,b,e,c,g,h;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.loadSprites();h=new createjs.Container;s_oStage.addChild(h)};this.unload=function(){h.removeAllChildren()};this.hide=function(){var a=this;setTimeout(function(){createjs.Tween.get(g).to({alpha:1},500).call(function(){a.unload();
s_oMain.gotoMenu()})},1E3)};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var f=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));h.addChild(f);f=s_oSpriteLibrary.getSprite("progress_bar");e=createBitmap(f);e.x=CANVAS_WIDTH/2-f.width/2;e.y=CANVAS_HEIGHT-170;h.addChild(e);a=f.width;d=f.height;c=new createjs.Shape;c.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(e.x,e.y,1,d);h.addChild(c);e.mask=
c;b=new createjs.Text("","30px ZombieA","#fff");b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT-125;b.shadow=new createjs.Shadow("#000",2,2,2);b.textBaseline="alphabetic";b.textAlign="center";h.addChild(b);g=new createjs.Shape;g.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);g.alpha=0;h.addChild(g)};this.refreshLoader=function(f){b.text=f+"%";c.graphics.clear();f=Math.floor(f*a/100);c.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(e.x,e.y,f,d)};this._init()}
function CMenu(){var a,d,b,e;this._init=function(){a=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(a);var c=s_oSpriteLibrary.getSprite("but_play");d=new CTextButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-80,c,TEXT_PLAY,"Arial","#ffffff",40);d.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)c=s_oSpriteLibrary.getSprite("audio_icon"),e=new CToggle(CANVAS_WIDTH-c.height/2-10,c.height/2+10,c,s_bAudioActive),e.addEventListener(ON_MOUSE_UP,
this._onAudioToggle,this);b=new createjs.Shape;b.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(b);createjs.Tween.get(b).to({alpha:0},1E3).call(function(){b.visible=!1})};this.unload=function(){d.unload();d=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)e.unload(),e=null;s_oStage.removeChild(a);a=null};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onButPlayRelease=function(){this.unload();!1!==
DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");s_oMain.gotoGame()};this._init()}
function CMain(a){var d,b=0,e=0,c=STATE_LOADING,g,h,f;this.initContainer=function(){s_oCanvas=document.getElementById("canvas");s_oStage=new createjs.Stage(s_oCanvas);createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&(s_oStage.enableMouseOver(20),$("body").on("contextmenu","#canvas",function(a){return!1}));s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.setFPS(30);navigator.userAgent.match(/Windows Phone/i)&&(DISABLE_SOUND_MOBILE=
!0);s_oSpriteLibrary=new CSpriteLibrary;h=new CPreloader};this.preloaderReady=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();this._loadImages();d=!0};this.soundLoaded=function(){b++;if(b===e){h.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundtrack=createjs.Sound.play("soundtrack",{loop:100});this.gotoMenu()}};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&(0<navigator.userAgent.indexOf("Opera")||0<navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=
["m4a"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/soundtrack.ogg","soundtrack"),createjs.Sound.registerSound("./sounds/card_dealing.ogg","card_dealing"),createjs.Sound.registerSound("./sounds/snap.ogg","snap"),createjs.Sound.registerSound("./sounds/press_button.ogg","click"),createjs.Sound.registerSound("./sounds/game_over.ogg","game_over"),createjs.Sound.registerSound("./sounds/card.ogg","card")):(createjs.Sound.alternateExtensions=
["ogg"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/soundtrack.mp3","soundtrack"),createjs.Sound.registerSound("./sounds/card_dealing.mp3","card_dealing"),createjs.Sound.registerSound("./sounds/snap.mp3","snap"),createjs.Sound.registerSound("./sounds/press_button.m4a","click"),createjs.Sound.registerSound("./sounds/game_over.mp3","game_over"),createjs.Sound.registerSound("./sounds/card.mp3","card")),e+=6)};this._loadImages=
function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("bg_help","./sprites/bg_help.png");s_oSpriteLibrary.addSprite("arrow","./sprites/arrow.png");s_oSpriteLibrary.addSprite("hintpanel","./sprites/hint_panel.png");
s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("but_help","./sprites/but_help.png");s_oSpriteLibrary.addSprite("but_restart","./sprites/but_restart.png");s_oSpriteLibrary.addSprite("moves_display","./sprites/moves_display.png");s_oSpriteLibrary.addSprite("score_display","./sprites/score_display.png");s_oSpriteLibrary.addSprite("card_spritesheet","./sprites/cards.png");e+=s_oSpriteLibrary.getNumSprites();
s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){b++;h.refreshLoader(Math.floor(b/e*100));if(b===e){h.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundtrack=createjs.Sound.play("soundtrack",{loop:100});this.gotoMenu()}};this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this.gotoMenu=function(){new CMenu;c=STATE_MENU};this.goToModeMenu=function(){new CModeMenu;c=STATE_MENU};this.gotoGame=function(a){s_bEasyMode=a;f=new CGame(g);
c=STATE_GAME;$(s_oMain).trigger("game_start")};this.gotoHelp=function(){new CHelp;c=STATE_HELP};this.stopUpdate=function(){d=!1};this.startUpdate=function(){d=!0};this._update=function(a){if(!1!==d){var b=(new Date).getTime();s_iTimeElaps=b-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=b;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);c===STATE_GAME&&f.update();s_oStage.update(a)}};s_oMain=this;g=a;this.initContainer()}
var s_bMobile,s_bEasyMode,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oSoundTrack,s_oCanvas;