TEXT_GAMEOVER="YOU LOSE!";TEXT_SCORE="SCORE";TEXT_PLAY="PLAY";TEXT_BET="BET";TEXT_ALLIN="ALL IN!";TEXT_CLEARBET="CLEAR BET";TEXT_GIVEUP="GIVE UP";TEXT_MAKE="MAKE YOUR BET!";TEXT_ENDGIVEUP="ARE YOU SURE TO EXIT AND SAVE ";TEXT_YES="YES";TEXT_NO="NO";TEXT_CURRENCY="$";TEXT_TURN="TURN ";TEXT_HIGHS="HIGHs: ";TEXT_LOWS="LOWs: ";TEXT_GUESS="TOTAL GUESS: ";TEXT_BEST="BEST SCORE: ";TEXT_WIN="YOU WIN";TEXT_LOSE="YOU LOSE";TEXT_HELP1="THE AIM OF THE GAME IS TO GUESS WHETHER THE FACE DOWN CARD IS HIGH OR LOW";
TEXT_HELP2="CARDS FROM 2 TO 7 ARE LOW THOSE BETWEEN 8 AND KING ARE HIGH. THE ACE IS BOTH HIGH AND LOW, SO IT'S ALWAYS WINNING";TEXT_HELP3='CLICK ON CHIPS TO CHOOSE HOW MUCH YOU WANT BET, THEN CLICK ON "BET" BUTTON TO PLAY. IF YOU WIN, YOU DOUBLE YOUR WAGER';TEXT_HELP4='TO SAVE YOUR CURRENT PRIZE MONEY, CLICK ON "GIVE UP" BUTTON, THIS WILL END YOUR GAME';
function CInterface(){var a,d,b,c,e,f,g,k,h,m,p,t,l,q,r,u,v,w,x;this._init=function(){var z,n=s_oSpriteLibrary.getSprite("but_exit");d=new CGfxButton(CANVAS_WIDTH-n.height/2-10,n.height/2+10,n,!0);d.addEventListener(ON_MOUSE_UP,this._onExit,this);z=CANVAS_WIDTH-n.width/2-80;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)n=s_oSpriteLibrary.getSprite("audio_icon"),a=new CToggle(z,10+n.height/2,n,s_bAudioActive),a.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);n=s_oSpriteLibrary.getSprite("but_bet");
e=new CTextButton(1005,CANVAS_HEIGHT-46,n,TEXT_BET,"Arial","#ffffff",40,!1,s_oStage);e.addEventListener(ON_MOUSE_UP,this._onButBetRelease,this);e.disable();n=s_oSpriteLibrary.getSprite("but_bet");f=new CTextButton(750,CANVAS_HEIGHT-46,n,TEXT_ALLIN,"Arial","#ffffff",40,!1,s_oStage);f.addEventListener(ON_MOUSE_UP,this._onButAllinRelease,this);f.enable();n=s_oSpriteLibrary.getSprite("but_clear_bet");b=new CTextButton(105,CANVAS_HEIGHT-63,n,TEXT_CLEARBET,"Arial","#ffffff",20,!1,s_oStage);b.setTextPosition(0,
0);b.addEventListener(ON_MOUSE_UP,this._onButClearBetRelease,this);b.enable();n=s_oSpriteLibrary.getSprite("but_clear_bet");c=new CTextButton(105,CANVAS_HEIGHT-19,n,TEXT_GIVEUP,"Arial","#ffffff",20,!1,s_oStage);c.setTextPosition(0,0);c.addEventListener(ON_MOUSE_UP,this._onButGiveupRelease,this);c.enable();n=s_oSpriteLibrary.getSprite("arrow_high");p=new CGfxButton(CANVAS_WIDTH/2-n.height/2-100,CANVAS_HEIGHT/2-n.height/2-5,n,!1);p.addEventListener(ON_MOUSE_UP,this._onArrowHigh,this);n=s_oSpriteLibrary.getSprite("arrow_low");
t=new CGfxButton(CANVAS_WIDTH/2-n.height/2+235,CANVAS_HEIGHT/2-n.height/2+85,n,!1);t.addEventListener(ON_MOUSE_UP,this._onArrowLow,this);l=new createjs.Shape;l.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(0,0,135,135);l.visible=!1;l.on("mousedown",function(){});s_oStage.addChild(l);this.enableArrow(!1);z=[];for(var y=0;5>y;y++)n=s_oSpriteLibrary.getSprite("fiche_"+y),z[y]=new CGfxButton(258+50*y,575,n,!0),z[y].addEventListenerWithParams(ON_MOUSE_UP,this._onFicheClicked,this,y);q=new createjs.Shape;
q.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(0,0,250,50);q.x=230;q.y=550;q.visible=!1;q.on("mousedown",function(){});s_oStage.addChild(q);h=new createjs.Text(TEXT_MAKE,"bold 28px Arial","#000000");h.x=362;h.y=537;h.textAlign="center";h.textBaseline="alphabetic";h.lineWidth=300;s_oStage.addChild(h);m=new createjs.Text(TEXT_MAKE,"bold 28px Arial","#ffffff");m.x=360;m.y=535;m.textAlign="center";m.textBaseline="alphabetic";m.lineWidth=300;s_oStage.addChild(m);n=s_oSpriteLibrary.getSprite("money_panel");
n=createBitmap(n);n.x=50;n.y=595;s_oStage.addChild(n);g=new createjs.Text(TEXT_CURRENCY+" "+PLAYER_MONEY,"bold 32px Arial","#000000");g.x=353;g.y=630;g.textAlign="center";g.textBaseline="alphabetic";g.lineWidth=200;s_oStage.addChild(g);k=new createjs.Text(TEXT_CURRENCY+" "+PLAYER_MONEY,"bold 32px Arial","#ffffff");k.x=350;k.y=627;k.textAlign="center";k.textBaseline="alphabetic";k.lineWidth=200;s_oStage.addChild(k);r=new createjs.Container;r.x=10;r.y=10;s_oStage.addChild(r);n=s_oSpriteLibrary.getSprite("panel_high_sx");
n=createBitmap(n);r.addChild(n);u=new createjs.Text(TEXT_TURN+"1","bold 24px Arial","#ffffff");u.x=140;u.y=25;u.textAlign="center";u.textBaseline="alphabetic";u.lineWidth=400;r.addChild(u);v=new createjs.Text(TEXT_HIGHS+"0/0","bold 18px Arial","#ffffff");v.x=10;v.y=50;v.textAlign="left";v.textBaseline="alphabetic";v.lineWidth=400;r.addChild(v);w=new createjs.Text(TEXT_LOWS+"0/0","bold 18px Arial","#ffffff");w.x=10;w.y=75;w.textAlign="left";w.textBaseline="alphabetic";w.lineWidth=400;r.addChild(w);
x=new createjs.Text(TEXT_GUESS+"0","bold 18px Arial","#ffffff");x.x=10;x.y=100;x.textAlign="left";x.textBaseline="alphabetic";x.lineWidth=400;r.addChild(x)};this.unload=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)a.unload(),a=null;d.unload();e.unload();f.unload();b.unload();c.unload();p.unload();t.unload();for(var g=0;g<FICHE_VALUE.length;g++)(void 0)[g].unload();q.off("mousedown",function(){});l.off("mousedown",function(){});s_oStage.removeChild(r)};this.refreshMoney=function(a){g.text=
TEXT_CURRENCY+" "+a;k.text=TEXT_CURRENCY+" "+a};this.refreshTurn=function(a){u.text=TEXT_TURN+a};this.refreshHighs=function(a,b,e){v.text=TEXT_HIGHS+a+"/"+b+" ("+e+"%)"};this.refreshLows=function(a,b,e){w.text=TEXT_LOWS+a+"/"+b+" ("+e+"%)"};this.refreshGuess=function(a,b){x.text=TEXT_GUESS+a+" ("+b+"%)"};this.disableAllIn=function(){f.disable()};this.initState=function(){e.disable();f.enable();b.enable();c.enable();l.visible=!1;h.visible=!0;m.visible=!0;this.enableArrow(!1);this._enableFiche(!0)};
this._onButBetRelease=function(){e.disable();f.disable();this.enableArrow(!0);this._enableFiche(!1)};this._onButAllinRelease=function(){e.disable();f.disable();h.visible=!1;m.visible=!1;this.enableArrow(!0);this._enableFiche(!1);s_oGame.updateCurBet(-1)};this._onButGiveupRelease=function(){s_oGame.onGiveUp()};this._onButClearBetRelease=function(){s_oGame.resetBet();e.disable();f.enable();c.enable();h.visible=!0;m.visible=!0;this.enableArrow(!1);this._enableFiche(!0)};this._onArrowHigh=function(){t.disable();
b.disable();c.disable();l.x=CANVAS_WIDTH/2-230;l.y=CANVAS_HEIGHT/2-140;l.visible=!0;s_oGame.onPlayerSelection("high")};this._onArrowLow=function(){p.disable();b.disable();c.disable();l.x=CANVAS_WIDTH/2+100;l.y=CANVAS_HEIGHT/2-50;l.visible=!0;s_oGame.onPlayerSelection("low")};this._enableFiche=function(a){q.visible=a?!1:!0};this.enableArrow=function(a){a?(p.enable(),t.enable()):(p.disable(),t.disable())};this._onFicheClicked=function(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("chip");
h.visible=!1;m.visible=!1;this.enableArrow(!1);e.enable();f.enable();c.disable();a=s_oGameSettings.getFichesValueAt(a);s_oGame.updateCurBet(a)};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onExit=function(){s_oGame.onExit()};this._init();return this}
function CHelpPanel(){var a,d,b,c,e,f,g,k,h,m,p;this._init=function(){var t=this;h=createBitmap(s_oSpriteLibrary.getSprite("bg_help"));var l=CANVAS_WIDTH/2,p=CANVAS_HEIGHT/2-185;d=new createjs.Text(TEXT_HELP1,"Bold 22px Arial","#000000");d.x=l+2;d.y=p+2;d.textAlign="center";d.textBaseline="alphabetic";d.lineWidth=600;a=new createjs.Text(TEXT_HELP1,"Bold 22px Arial","#ffffff");a.x=l;a.y=p;a.textAlign="center";a.textBaseline="alphabetic";a.lineWidth=600;l=CANVAS_WIDTH/2-340;p=CANVAS_HEIGHT/2-110;c=
new createjs.Text(TEXT_HELP2," 18px Arial","#000000");c.x=l+2;c.y=p+2;c.textAlign="left";c.textBaseline="alphabetic";c.lineWidth=320;b=new createjs.Text(TEXT_HELP2," 18px Arial","#ffffff");b.x=l;b.y=p;b.textAlign="left";b.textBaseline="alphabetic";b.lineWidth=320;l=CANVAS_WIDTH/2-50;p=CANVAS_HEIGHT/2+50;f=new createjs.Text(TEXT_HELP3," 18px Arial","#000000");f.x=l+2;f.y=p+2;f.textAlign="left";f.textBaseline="alphabetic";f.lineWidth=380;e=new createjs.Text(TEXT_HELP3," 18px Arial","#ffffff");e.x=l;
e.y=p;e.textAlign="left";e.textBaseline="alphabetic";e.lineWidth=380;l=CANVAS_WIDTH/2-340;p=CANVAS_HEIGHT/2+170;k=new createjs.Text(TEXT_HELP4," 18px Arial","#000000");k.x=l+2;k.y=p+2;k.textAlign="left";k.textBaseline="alphabetic";k.lineWidth=400;g=new createjs.Text(TEXT_HELP4," 18px Arial","#ffffff");g.x=l;g.y=p;g.textAlign="left";g.textBaseline="alphabetic";g.lineWidth=400;m=new createjs.Container;m.addChild(h,d,a,c,b,f,e,k,g);m.alpha=0;s_oStage.addChild(m);createjs.Tween.get(m).to({alpha:1},700);
m.on("pressup",function(){t._onExitHelp()})};this.unload=function(){s_oStage.removeChild(m);var a=this;m.off("pressup",function(){a._onExitHelp()})};this._onExitHelp=function(){p.unload();s_oGame._onExitHelp()};p=this;this._init()}
function CGiveupPanel(a,d){var b,c,e,f,g,k,h;this._init=function(a,d){b=createBitmap(a);b.x=0;b.y=0;e=new createjs.Text("","bold 60px Arial","#000");e.x=CANVAS_WIDTH/2+2;e.y=CANVAS_HEIGHT/2-140;e.textAlign="center";e.textBaseline="alphabetic";e.lineWidth=500;f=new createjs.Text("","bold 60px Arial","#ffffff");f.x=CANVAS_WIDTH/2;f.y=CANVAS_HEIGHT/2-142;f.textAlign="center";f.textBaseline="alphabetic";f.lineWidth=500;g=new createjs.Shape;g.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(0,0,CANVAS_WIDTH,
CANVAS_HEIGHT);g.on("mousedown",function(){});c=new createjs.Container;c.alpha=0;c.addChild(b,e,f,g);var t=s_oSpriteLibrary.getSprite("but_bet");k=new CTextButton(CANVAS_WIDTH/2-200,CANVAS_HEIGHT/2+150,t,TEXT_YES,"Arial","#ffffff",40,!1,c);k.addEventListener(ON_MOUSE_UP,this._onYesRelease,this);k.enable();h=new CTextButton(CANVAS_WIDTH/2+200,CANVAS_HEIGHT/2+150,t,TEXT_NO,"Arial","#ffffff",40,!1,c);h.addEventListener(ON_MOUSE_UP,this._onNoRelease,this);h.enable();s_oStage.addChild(c);!1!==DISABLE_SOUND_MOBILE&&
!1!==s_bMobile||createjs.Sound.play("game_over");e.text=TEXT_ENDGIVEUP+TEXT_CURRENCY+d+" ?";f.text=TEXT_ENDGIVEUP+TEXT_CURRENCY+d+" ?";createjs.Tween.get(c).to({alpha:1},500)};this.unload=function(){s_oStage.removeChild(c)};this._onYesRelease=function(){$(s_oMain).trigger("save_score",d);s_oStage.removeChild(c);s_oGame.onExit()};this._onNoRelease=function(){this.unload()};this._init(a,d);return this}
function CGfxButton(a,d,b,c){var e,f,g,k=[],h;this._init=function(a,b,c,d){e=!1;f=[];g=[];d?(h=createBitmap(c),h.regX=c.width/2,h.regY=c.height/2):(d=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_true:[0],state_false:[1]}}),h=createSprite(d,"state_false",c.width/2/2,c.height/2,c.width/2,c.height));h.x=a;h.y=b;s_oStage.addChild(h);this._initListener()};this.unload=function(){h.off("mousedown",this.buttonDown);h.off("pressup",
this.buttonRelease);s_oStage.removeChild(h)};this.setVisible=function(a){h.visible=a};this._initListener=function(){h.on("mousedown",this.buttonDown);h.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,e){f[a]=b;g[a]=e};this.addEventListenerWithParams=function(a,b,e,c){f[a]=b;g[a]=e;k=c};this.buttonRelease=function(){e||(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("press_but"),h.scaleX=1,h.scaleY=1,f[ON_MOUSE_UP]&&f[ON_MOUSE_UP].call(g[ON_MOUSE_UP],k))};this.buttonDown=
function(){e||(h.scaleX=.9,h.scaleY=.9,f[ON_MOUSE_DOWN]&&f[ON_MOUSE_DOWN].call(g[ON_MOUSE_DOWN],k))};this.setPosition=function(a,b){h.x=a;h.y=b};this.setX=function(a){h.x=a};this.setY=function(a){h.y=a};this.enable=function(){e=!1;c||h.gotoAndStop("state_true")};this.disable=function(){e=!0;c||h.gotoAndStop("state_false")};this.getButtonImage=function(){return h};this.getDisable=function(){return e};this.getX=function(){return h.x};this.getY=function(){return h.y};this._init(a,d,b,c);return this}
function CGameSettings(){var a,d,b,c;this._init=function(){b=[];a=[];for(var e=0;52>e;e++){a.push(e);var d=(e+1)%13;0===d&&(d=13);b.push(d)}c=[];for(e=0;e<FICHES_VALUE.length;e++)c[e]=FICHES_VALUE[e]};this.getFichesValues=function(){return c};this.getFichesValueAt=function(a){return c[a]};this.getIndexForFiches=function(a){for(var b=0,d=0;d<c.length;d++)c[d]===a&&(b=d);return b};this.generateFichesPile=function(a){var b=[],d,k=c.length-1,h=c[k];do{d=a%h;d=CMath.roundDecimal(d,1);a=Math.floor(a/h);
for(var m=0;m<a;m++)b.push(h);k--;h=c[k];a=d}while(0<d&&-1<k);return b};this.timeToString=function(a){a=Math.round(a/1E3);var b=Math.floor(a/60);a-=60*b;var c="",c=10>b?c+("0"+b+":"):c+(b+":");return 10>a?c+("0"+a):c+a};this.getShuffledCardDeck=function(){for(var b=[],c=0;c<a.length;c++)b[c]=a[c];for(d=[];0<b.length;)d.push(b.splice(Math.round(Math.random()*(b.length-1)),1)[0]);return d};this.getCardValue=function(a){return b[a]};this._init()}
function CGame(a){var d,b,c,e,f,g,k,h,m,p,t,l,q,r,u,v,w,x,z,n,y=null,A,C;this._init=function(){c=!1;g=f=0;k=1;l=t=p=m=h=0;r=[];u=[];v=[];w=[];s_oGameSettings=new CGameSettings;var a=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(a);n=new CInterface;C=new createjs.Container;s_oStage.addChild(C);d=CANVAS_WIDTH/2;b=CANVAS_HEIGHT/2-30;this._setCards();this._setHideCardOnTable();A=new CFichesController(221,455,C);new CHelpPanel};this._setCards=function(){r=[];r=s_oGameSettings.getShuffledCardDeck();
u=[];v=[];w=[];for(var a=0;a<r.length;a++){var b=s_oGameSettings.getCardValue(r[a]);1<b&&8>b?u.push(r[a]):7<b&&14>b?v.push(r[a]):w.push(r[a])}};this.unload=function(){n.unload();null!==y&&y.unload();createjs.Tween.removeAllTweens();s_oStage.removeAllChildren()};this.resetBet=function(){A.reset();e+=f;f=0;n.refreshMoney(e)};this.updateCurBet=function(a){0>a&&(a=e);e-=a;f+=a;0>e?(f+=e,e=0,n.disableAllIn(),r=[],r=s_oGameSettings.getShuffledCardDeck()):0===e&&n.disableAllIn();n.refreshMoney(e);A.createFichesPile(f)};
this._setHideCardOnTable=function(){z=new CCard(d,b,s_oStage,0,s_oGameSettings.getCardValue(0))};this._pickCard=function(a){a="high"===a?v.pop():"low"===a?u.pop():w.pop();x=new CCard(d,b,s_oStage,a,s_oGameSettings.getCardValue(a))};this.onPlayerSelection=function(a){z.unload();if((q<2*f?WIN_OCCURRENCE+1:100*Math.random())<=WIN_OCCURRENCE){var b=Math.random(),d=4/(52-g);"high"===a?(c=!0,b<d&&0!==w.length||0===v.length?this._pickCard("ace"):this._pickCard("high")):(c=!1,b<d&&0!==w.length||0===u.length?
this._pickCard("ace"):this._pickCard("low"))}else"high"===a?(c=!0,this._pickCard("low")):(c=!1,this._pickCard("high"));x.showCard()};this.checkWin=function(a){if(!c&&8>a.getRank()){var b=2*f,b=new CWinText(TEXT_WIN+" "+TEXT_CURRENCY+b+"!",d,b);b.show();h++;t++;l++;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)a=createjs.Sound.play("win"),a.volume=.3}else if(c&&(8<=a.getRank()||1===a.getRank())){if(b=2*f,b=new CWinText(TEXT_WIN+" "+TEXT_CURRENCY+b+"!",d,b),b.show(),h++,m++,p++,!1===DISABLE_SOUND_MOBILE||
!1===s_bMobile)a=createjs.Sound.play("win"),a.volume=.3}else{if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)createjs.Sound.play("game_over").volume=.3;b=f;b=new CWinText(TEXT_LOSE+" "+TEXT_CURRENCY+b+"!",d,0);b.show();8>a.getRank()?l++:p++}};this._calculateStats=function(){var a=(h/k*100).toFixed(2);n.refreshGuess(h,a);0!==p&&(a=(m/p*100).toFixed(2),n.refreshHighs(m,p,a));0!==l&&(a=(t/l*100).toFixed(2),n.refreshLows(t,l,a))};this.refreshGame=function(a){e+=a;0===a?(trace("INCREAS OF "+f),q+=f):(trace("DECREASE OF "+
a),q-=a);trace("CUR CASH: "+q);this._calculateStats();n.refreshMoney(e);if(0===e)this.gameOver();else{f=0;A.reset();x.unload();g++;k++;n.refreshTurn(k);if(0===u.length||0===v.length)g=0,this._setCards();this._setHideCardOnTable();n.initState()}};this.onGiveUp=function(){new CGiveupPanel(s_oSpriteLibrary.getSprite("msg_box"),e)};this.onExit=function(){this.unload();s_oMain.gotoMenu();$(s_oMain).trigger("restart")};this._onExitHelp=function(){_bStartGame=!0};this.gameOver=function(){y=CEndPanel(s_oSpriteLibrary.getSprite("msg_box"));
y.show()};this.update=function(){};s_oGame=this;WIN_OCCURRENCE=a.win_occurrence;q=a.casino_cash;e=PLAYER_MONEY=a.player_money;FICHES_VALUE=a.fiches_value;TURN_CARD_SPEED=a.turn_card_speed;SHOWTEXT_SPEED=a.showtext_timespeed;this._init()}var s_oGame;
function CFichesController(a,d,b){var c,e,f,g,k,h,m,p,t,l,q;this._init=function(a,b,d){m=new createjs.Container;m.x=a;m.y=b;d.addChild(m);g=f=0;c=!1;l=[];q=[]};this.addEventListener=function(a,b,c){l[a]=b;q[a]=c};this.reset=function(){e=!1;g=0;m.removeAllChildren()};this.refreshFiches=function(a,b,c){a=a.sortOn("value","index");for(var d=c,e=g=0,f=0;f<a.length;f++){var h=createBitmap(s_oSpriteLibrary.getSprite("fiche_"+a[f].index));h.scaleX=.7;h.scaleY=.7;m.addChild(h);h.x=b;h.y=d;d-=5;e++;9<e&&(e=
0,b+=FICHE_WIDTH,d=c);g+=a[f].value}!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("chip")};this._createFichesAmountText=function(a,b,c){p=new createjs.Text(TEXT_CURRENCY+" "+c,"bold 24px Arial","#000000");p.x=a+3;p.y=b+3;p.textAlign="center";p.textBaseline="alphabetic";p.lineWidth=200;m.addChild(p);t=new createjs.Text(TEXT_CURRENCY+" "+c,"bold 24px Arial","#ffffff");t.x=a;t.y=b;t.textAlign="center";t.textBaseline="alphabetic";t.lineWidth=200;m.addChild(t)};this.createFichesPile=function(a){m.removeAllChildren();
this._createFichesAmountText(10,60,a);var b=s_oGameSettings.getFichesValues(),c=[];do{for(var d=b[b.length-1],e=b.length-1;d>a;)e--,d=b[e];for(var e=Math.floor(a/d),f=0;f<e;f++)c.push({value:d,index:s_oGameSettings.getIndexForFiches(d)});a=d=a%d}while(0<d);this.refreshFiches(c,0,0)};this.initMovement=function(a,b,d){c=d;k=new CVector2(m.x,m.y);h=new CVector2(a,b)};this.getValue=function(){return g};this.update=function(a){if(!e)if(f+=a,f>TIME_FICHES_MOV)f=0,e=!0,l[FICHES_END_MOV]&&l[FICHES_END_MOV].call(q[FICHES_END_MOV],
c,g);else{a=easeInOutCubic(f,0,1,TIME_FICHES_MOV);var b=new CVector2,b=tweenVectors(k,h,a,b);m.x=b.getX();m.y=b.getY()}};this._init(a,d,b)}
function CEndPanel(a){var d,b,c,e;this._init=function(a){d=createBitmap(a);d.x=0;d.y=0;c=new createjs.Text("","bold 60px Arial","#000");c.x=CANVAS_WIDTH/2+3;c.y=CANVAS_HEIGHT/2+43;c.textAlign="center";c.textBaseline="alphabetic";c.lineWidth=500;e=new createjs.Text("","bold 60px Arial","#ffffff");e.x=CANVAS_WIDTH/2;e.y=CANVAS_HEIGHT/2+40;e.textAlign="center";e.textBaseline="alphabetic";e.lineWidth=500;b=new createjs.Container;b.alpha=0;b.visible=!1;b.addChild(d,c,e);s_oStage.addChild(b)};this.unload=
function(){b.off("mousedown",this._onExit)};this._initListener=function(){b.on("mousedown",this._onExit)};this.show=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("game_over");c.text=TEXT_GAMEOVER;e.text=TEXT_GAMEOVER;b.visible=!0;var a=this;createjs.Tween.get(b).to({alpha:1},500).call(function(){a._initListener()})};this._onExit=function(){b.off("mousedown",this._onExit);s_oStage.removeChild(b);s_oGame.onExit()};this._init(a);return this}
function CCard(a,d,b,c,e){var f,g,k,h,m,p;this._init=function(a,b,c,d,e){m=c;f=d;g=e;h=new createjs.Container;h.x=a;h.y=b;m.addChild(h);a={images:[s_oSpriteLibrary.getSprite("card_spritesheet")],frames:{width:CARD_WIDTH,height:CARD_HEIGHT,regX:CARD_WIDTH/2,regY:CARD_HEIGHT/2},animations:{card_1_1:[0],card_1_2:[1],card_1_3:[2],card_1_4:[3],card_1_5:[4],card_1_6:[5],card_1_7:[6],card_1_8:[7],card_1_9:[8],card_1_10:[9],card_1_J:[10],card_1_Q:[11],card_1_K:[12],card_2_1:[13],card_2_2:[14],card_2_3:[15],
card_2_4:[16],card_2_5:[17],card_2_6:[18],card_2_7:[19],card_2_8:[20],card_2_9:[21],card_2_10:[22],card_2_J:[23],card_2_Q:[24],card_2_K:[25],card_3_1:[26],card_3_2:[27],card_3_3:[28],card_3_4:[29],card_3_5:[30],card_3_6:[31],card_3_7:[32],card_3_8:[33],card_3_9:[34],card_3_10:[35],card_3_J:[36],card_3_Q:[37],card_3_K:[38],card_4_1:[39],card_4_2:[40],card_4_3:[41],card_4_4:[42],card_4_5:[43],card_4_6:[44],card_4_7:[45],card_4_8:[46],card_4_9:[47],card_4_10:[48],card_4_J:[49],card_4_Q:[50],card_4_K:[51],
back:[52]}};a=new createjs.SpriteSheet(a);k=createSprite(a,"back",0,0,CARD_WIDTH,CARD_HEIGHT);k.stop();h.addChild(k)};this.unload=function(){m.removeChild(h)};this.showCard=function(){var a=this;createjs.Tween.get(h).to({scaleX:.1},TURN_CARD_SPEED/2,createjs.Ease.cubicIn).call(function(){a.setValue()}).call(function(){})};this.setValue=function(){k.gotoAndStop(f);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("card");createjs.Tween.get(h).to({scaleX:1},TURN_CARD_SPEED/2,createjs.Ease.cubicOut).call(function(){s_oGame.checkWin(p)})};
this.hideCard=function(){var a=this;createjs.Tween.get(h).to({scaleX:.1},TURN_CARD_SPEED/2,createjs.Ease.linear).call(function(){a.setBack()})};this.setBack=function(){k.gotoAndStop("back");var a=this;createjs.Tween.get(h).to({scaleX:1},TURN_CARD_SPEED/2,createjs.Ease.linear).call(function(){a.cardHidden()})};this.getRank=function(){return g};p=this;this._init(a,d,b,c,e)}
function CSpriteLibrary(){var a,d,b,c,e,f;this.init=function(g,k,h){b=d=0;c=g;e=k;f=h;a={}};this.addSprite=function(b,c){a.hasOwnProperty(b)||(a[b]={szPath:c,oSprite:new Image},d++)};this.getSprite=function(b){return a.hasOwnProperty(b)?a[b].oSprite:null};this._onSpritesLoaded=function(){e.call(f)};this._onSpriteLoaded=function(){c.call(f);++b==d&&this._onSpritesLoaded()};this.loadSprites=function(){for(var b in a)a[b].oSprite.oSpriteLibrary=this,a[b].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
a[b].oSprite.src=a[b].szPath};this.getNumSprites=function(){return d}}var CANVAS_WIDTH=1136,CANVAS_HEIGHT=640,FPS_TIME=1E3/24,DISABLE_SOUND_MOBILE=!1,STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,FICHE_WIDTH=40,FICHE_VALUE=[],WIN_OCCURRENCE,TURN_CARD_SPEED,CARD_WIDTH=122,CARD_HEIGHT=190,SHOWTEXT_SPEED,PLAYER_MONEY;
function CWinText(a,d,b){var c,e,f,g,k;this._init=function(a,b,d){g=new createjs.Container;g.x=0;g.y=CANVAS_HEIGHT/2-135;g.alpha=1;s_oStage.addChild(g);e=new createjs.Text(a,"bold 60px Arial","#ffffff");e.textAlign="center";e.textBaseline="alphabetic";g.addChild(e);f=new createjs.Text(a,"bold 60px Arial","#000000");f.textAlign="center";f.outline=3;f.textBaseline="alphabetic";g.addChild(f);c=f.getMeasuredWidth()};this.show=function(){createjs.Tween.get(g).to({x:d},SHOWTEXT_SPEED/4,createjs.Ease.elasticOut).wait(SHOWTEXT_SPEED/
2).to({x:CANVAS_WIDTH+c/2},SHOWTEXT_SPEED/4,createjs.Ease.quartOut).call(function(){k.unload();s_oGame.refreshGame(b)})};this.unload=function(){s_oStage.removeChild(g)};k=this;this._init(a,d,b)}
function CToggle(a,d,b,c){var e,f,g,k;this._init=function(a,b,c,d){f=[];g=[];var l=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_true:[0],state_false:[1]}});e=d;k=createSprite(l,"state_"+e,c.width/2/2,c.height/2,c.width/2,c.height);k.x=a;k.y=b;k.stop();s_oStage.addChild(k);this._initListener()};this.unload=function(){k.off("mousedown",this.buttonDown);k.off("pressup",this.buttonRelease);s_oStage.removeChild(k)};this._initListener=
function(){k.on("mousedown",this.buttonDown);k.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){f[a]=b;g[a]=c};this.setActive=function(a){e=a;k.gotoAndStop("state_"+e)};this.buttonRelease=function(){k.scaleX=1;k.scaleY=1;!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");e=!e;k.gotoAndStop("state_"+e);f[ON_MOUSE_UP]&&f[ON_MOUSE_UP].call(g[ON_MOUSE_UP],e)};this.buttonDown=function(){k.scaleX=.9;k.scaleY=.9;f[ON_MOUSE_DOWN]&&f[ON_MOUSE_DOWN].call(g[ON_MOUSE_DOWN])};
this._init(a,d,b,c)}var s_iScaleFactor=1,s_oCanvasLeft,s_oCanvasTop;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,4))})(navigator.userAgent||
navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}$(window).ready(function(){sizeHandler()});window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a=CANVAS_WIDTH,d=CANVAS_HEIGHT,b=window.innerWidth;multiplier=s_iScaleFactor=Math.min(window.innerHeight/d,b/a);a*=multiplier;d*=multiplier;$("#canvas").css("width",a+"px");$("#canvas").css("height",d+"px");$("#canvas").css("left",b/2-a/2+"px");s_oCanvasLeft=$("#canvas").offset().left;s_oCanvasTop=$("#canvas").offset().top}}
function createBitmap(a,d,b){var c=new createjs.Bitmap(a),e=new createjs.Shape;d&&b?e.graphics.beginFill("#fff").drawRect(0,0,d,b):e.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);c.hitArea=e;return c}function createSprite(a,d,b,c,e,f){a=null!==d?new createjs.Sprite(a,d):new createjs.Sprite(a);d=new createjs.Shape;d.graphics.beginFill("#000000").drawRect(-b,-c,e,f);a.hitArea=d;return a}
function randomFloatBetween(a,d,b){"undefined"===typeof b&&(b=2);return parseFloat(Math.min(a+Math.random()*(d-a),d).toFixed(b))}function shuffle(a){for(var d=a.length,b,c;0!==d;)c=Math.floor(Math.random()*d),--d,b=a[d],a[d]=a[c],a[c]=b;return a}function bubbleSort(a){var d;do{d=!1;for(var b=0;b<a.length-1;b++)a[b]>a[b+1]&&(d=a[b],a[b]=a[b+1],a[b+1]=d,d=!0)}while(d)}
Array.prototype.sortOn=function(){var a=this.slice();if(!arguments.length)return a.sort();var d=Array.prototype.slice.call(arguments);return a.sort(function(a,c){for(var e=d.slice(),f=e.shift();a[f]==c[f]&&e.length;)f=e.shift();return a[f]==c[f]?0:a[f]>c[f]?1:-1})};function easeLinear(a,d,b,c){return b*a/c+d}function easeInQuad(a,d,b,c){return b*(a/=c)*a+d}function easeInSine(a,d,b,c){return-b*Math.cos(a/c*(Math.PI/2))+b+d}function easeInCubic(a,d,b,c){return b*(a/=c)*a*a+d}
function getTrajectoryPoint(a,d){var b=new createjs.Point,c=(1-a)*(1-a),e=a*a;b.x=c*d.start.x+2*(1-a)*a*d.traj.x+e*d.end.x;b.y=c*d.start.y+2*(1-a)*a*d.traj.y+e*d.end.y;return b}function formatTime(a){a/=1E3;var d=Math.floor(a/60);a=parseFloat(a-60*d).toFixed(1);var b="",b=10>d?b+("0"+d+":"):b+(d+":");return b=10>a?b+("0"+a):b+a}function degreesToRadians(a){return a*Math.PI/180}function checkRectCollision(a,d){var b,c;b=getBounds(a,.9);c=getBounds(d,.98);return calculateIntersection(b,c)}
function calculateIntersection(a,d){var b,c,e,f,g,k,h,m;b=a.x+(e=a.width/2);c=a.y+(f=a.height/2);g=d.x+(k=d.width/2);h=d.y+(m=d.height/2);b=Math.abs(b-g)-(e+k);c=Math.abs(c-h)-(f+m);return 0>b&&0>c?(b=Math.min(Math.min(a.width,d.width),-b),c=Math.min(Math.min(a.height,d.height),-c),{x:Math.max(a.x,d.x),y:Math.max(a.y,d.y),width:b,height:c,rect1:a,rect2:d}):null}
function getBounds(a,d){var b={x:Infinity,y:Infinity,width:0,height:0};if(a instanceof createjs.Container){b.x2=-Infinity;b.y2=-Infinity;var c=a.children,e=c.length,f,g;for(g=0;g<e;g++)f=getBounds(c[g],1),f.x<b.x&&(b.x=f.x),f.y<b.y&&(b.y=f.y),f.x+f.width>b.x2&&(b.x2=f.x+f.width),f.y+f.height>b.y2&&(b.y2=f.y+f.height);Infinity==b.x&&(b.x=0);Infinity==b.y&&(b.y=0);Infinity==b.x2&&(b.x2=0);Infinity==b.y2&&(b.y2=0);b.width=b.x2-b.x;b.height=b.y2-b.y;delete b.x2;delete b.y2}else{var k,h;a instanceof createjs.Bitmap?
(e=a.sourceRect||a.image,g=e.width*d,k=e.height*d):a instanceof createjs.Sprite?a.spriteSheet._frames&&a.spriteSheet._frames[a.currentFrame]&&a.spriteSheet._frames[a.currentFrame].image?(e=a.spriteSheet.getFrame(a.currentFrame),g=e.rect.width,k=e.rect.height,c=e.regX,h=e.regY):(b.x=a.x||0,b.y=a.y||0):(b.x=a.x||0,b.y=a.y||0);c=c||0;g=g||0;h=h||0;k=k||0;b.regX=c;b.regY=h;e=a.localToGlobal(0-c,0-h);f=a.localToGlobal(g-c,k-h);g=a.localToGlobal(g-c,0-h);c=a.localToGlobal(0-c,k-h);b.x=Math.min(Math.min(Math.min(e.x,
f.x),g.x),c.x);b.y=Math.min(Math.min(Math.min(e.y,f.y),g.y),c.y);b.width=Math.max(Math.max(Math.max(e.x,f.x),g.x),c.x)-b.x;b.height=Math.max(Math.max(Math.max(e.y,f.y),g.y),c.y)-b.y}return b}function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}function shuffle(a){for(var d=a.length,b,c;0<d;)c=Math.floor(Math.random()*d),d--,b=a[d],a[d]=a[c],a[c]=b;return a}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3==a.nodeType&&(a=a.parentNode);var d=document.createEvent("MouseEvents");d.initEvent("click",!0,!0);a.dispatchEvent(d)}}};
(function(){function a(a){var c={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};a=a||window.event;a.type in c?document.body.className=c[a.type]:(document.body.className=this[d]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var d="hidden";d in document?document.addEventListener("visibilitychange",a):(d="mozHidden")in document?document.addEventListener("mozvisibilitychange",a):(d="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",a):(d="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a})();
function CTextButton(a,d,b,c,e,f,g,k,h){var m,p,t,l,q,r,u;this._init=function(a,b,c,d,e,f,h,g,k){m=!1;p=[];t=[];u=createBitmap(c);var B=Math.ceil(h/20);r=new createjs.Text(d,"bold "+h+"px "+e,"#000000");r.textAlign="center";r.textBaseline="alphabetic";var D=r.getBounds();r.x=c.width/2+B;r.y=Math.floor(c.height/2)+D.height/3+B-7;q=new createjs.Text(d,"bold "+h+"px "+e,f);q.textAlign="center";q.textBaseline="alphabetic";D=q.getBounds();q.x=c.width/2;q.y=Math.floor(c.height/2)+D.height/3-7;l=new createjs.Container;
l.x=a;l.y=b;l.regX=c.width/2;l.regY=c.height/2;g||(a=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_true:[0],state_false:[1]}}),u=createSprite(a,"state_false",c.width/2/2,c.height/2,c.width/2,c.height),r.x=B-7,r.y=B+7,q.x=-7,q.y=7,l.regX=0,l.regY=0);l.addChild(u,r,q);k.addChild(l);this._initListener()};this.unload=function(){l.off("mousedown");l.off("pressup");h.removeChild(l)};this.setVisible=function(a){l.visible=
a};this._initListener=function(){oParent=this;l.on("mousedown",this.buttonDown);l.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){p[a]=b;t[a]=c};this.buttonRelease=function(){m||(l.scaleX=1,l.scaleY=1,p[ON_MOUSE_UP]&&p[ON_MOUSE_UP].call(t[ON_MOUSE_UP]))};this.buttonDown=function(){m||(l.scaleX=.9,l.scaleY=.9,p[ON_MOUSE_DOWN]&&p[ON_MOUSE_DOWN].call(t[ON_MOUSE_DOWN]))};this.enable=function(){m=!1;k||u.gotoAndStop("state_true")};this.disable=function(){m=!0;k||u.gotoAndStop("state_false")};
this.setTextPosition=function(a,b){var c=Math.ceil(g/20);r.x=a+c;r.y=b+c;q.x=a;q.y=b};this.setPosition=function(a,b){l.x=a;l.y=b};this.setX=function(a){l.x=a};this.setY=function(a){l.y=a};this.getButtonImage=function(){return l};this.getX=function(){return l.x};this.getY=function(){return l.y};this._init(a,d,b,c,e,f,g,k,h);return this}
function CPreloader(){var a,d,b,c,e,f,g;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.loadSprites();g=new createjs.Container;s_oStage.addChild(g)};this.unload=function(){g.removeAllChildren()};this.hide=function(){var a=this;setTimeout(function(){createjs.Tween.get(f).to({alpha:1},500).call(function(){a.unload();
s_oMain.gotoMenu()})},1E3)};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var k=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));g.addChild(k);k=s_oSpriteLibrary.getSprite("progress_bar");c=createBitmap(k);c.x=CANVAS_WIDTH/2-k.width/2;c.y=CANVAS_HEIGHT-170;g.addChild(c);a=k.width;d=k.height;e=new createjs.Shape;e.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(c.x,c.y,1,d);g.addChild(e);c.mask=
e;b=new createjs.Text("","30px ZombieA","#fff");b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT-125;b.shadow=new createjs.Shadow("#000",2,2,2);b.textBaseline="alphabetic";b.textAlign="center";g.addChild(b);f=new createjs.Shape;f.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);f.alpha=0;g.addChild(f)};this.refreshLoader=function(f){b.text=f+"%";e.graphics.clear();f=Math.floor(f*a/100);e.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(c.x,c.y,f,d)};this._init()}
function CMenu(){var a,d,b,c;this._init=function(){a=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(a);var e=s_oSpriteLibrary.getSprite("but_play");d=new CTextButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-80,e,TEXT_PLAY,"Arial","#ffffff",40,!0,s_oStage);d.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)e=s_oSpriteLibrary.getSprite("audio_icon"),c=new CToggle(CANVAS_WIDTH-e.height/2-10,e.height/2+10,e,s_bAudioActive),c.addEventListener(ON_MOUSE_UP,
this._onAudioToggle,this);b=new createjs.Shape;b.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(b);createjs.Tween.get(b).to({alpha:0},1E3).call(function(){b.visible=!1})};this.unload=function(){d.unload();d=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)c.unload(),c=null;s_oStage.removeChild(a);a=null};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onButPlayRelease=function(){this.unload();!1!==
DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");s_oMain.gotoGame()};this._init()}
function CMain(a){var d,b=0,c=0,e=STATE_LOADING,f,g,k;this.initContainer=function(){s_oCanvas=document.getElementById("canvas");s_oStage=new createjs.Stage(s_oCanvas);createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&(s_oStage.enableMouseOver(20),$("body").on("contextmenu","#canvas",function(a){return!1}));s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.setFPS(30);navigator.userAgent.match(/Windows Phone/i)&&(DISABLE_SOUND_MOBILE=
!0);s_oSpriteLibrary=new CSpriteLibrary;g=new CPreloader};this.preloaderReady=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();this._loadImages();d=!0};this.soundLoaded=function(){b++;g.refreshLoader(Math.floor(b/c*100));if(b===c){g.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundtrack=createjs.Sound.play("soundtrack",{loop:-1});this.gotoMenu()}};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&(0<navigator.userAgent.indexOf("Opera")||0<
navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=["m4a"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/soundtrack.ogg","soundtrack"),createjs.Sound.registerSound("./sounds/snap.ogg","win"),createjs.Sound.registerSound("./sounds/press_button.ogg","click"),createjs.Sound.registerSound("./sounds/game_over.ogg","game_over"),createjs.Sound.registerSound("./sounds/card.ogg","card"),createjs.Sound.registerSound("./sounds/chip.ogg",
"chip",5)):(createjs.Sound.alternateExtensions=["ogg"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/soundtrack.mp3","soundtrack"),createjs.Sound.registerSound("./sounds/snap.mp3","win"),createjs.Sound.registerSound("./sounds/press_button.m4a","click"),createjs.Sound.registerSound("./sounds/game_over.mp3","game_over"),createjs.Sound.registerSound("./sounds/card.mp3","card"),createjs.Sound.registerSound("./sounds/chip.mp3",
"chip",5)),c+=6)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("bg_help","./sprites/bg_help.png");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("audio_icon",
"./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("but_bet","./sprites/but_bet.png");s_oSpriteLibrary.addSprite("but_clear_bet","./sprites/but_clear_bet.png");s_oSpriteLibrary.addSprite("money_panel","./sprites/money_panel.png");s_oSpriteLibrary.addSprite("panel_high_sx","./sprites/panel_high_sx.png");s_oSpriteLibrary.addSprite("arrow_high","./sprites/arrow_high.png");s_oSpriteLibrary.addSprite("arrow_low","./sprites/arrow_low.png");s_oSpriteLibrary.addSprite("card_spritesheet","./sprites/card_spritesheet.png");
for(var a,b=0;5>b;b++)a=b,s_oSpriteLibrary.addSprite("fiche_"+a,"./sprites/fiche_"+a+".png");c+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){b++;g.refreshLoader(Math.floor(b/c*100));if(b===c){g.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundtrack=createjs.Sound.play("soundtrack",{loop:-1});this.gotoMenu()}};this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this.gotoMenu=function(){new CMenu;
e=STATE_MENU};this.gotoGame=function(a){s_bEasyMode=a;k=new CGame(f);e=STATE_GAME;$(s_oMain).trigger("game_start")};this.gotoHelp=function(){new CHelp;e=STATE_HELP};this.stopUpdate=function(){d=!1};this.startUpdate=function(){d=!0};this._update=function(a){if(!1!==d){var b=(new Date).getTime();s_iTimeElaps=b-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=b;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);e===STATE_GAME&&k.update();s_oStage.update(a)}};s_oMain=this;
f=a;this.initContainer()}var s_bMobile,s_bEasyMode,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oSoundTrack,s_oCanvas,s_oGameSettings;