function CSpriteLibrary(){var g,k,n,e,l,m;this.init=function(q,h,b){n=k=0;e=q;l=h;m=b;g={}};this.addSprite=function(e,h){g.hasOwnProperty(e)||(g[e]={szPath:h,oSprite:new Image},k++)};this.getSprite=function(e){return g.hasOwnProperty(e)?g[e].oSprite:null};this._onSpritesLoaded=function(){l.call(m)};this._onSpriteLoaded=function(){e.call(m);++n===k&&this._onSpritesLoaded()};this.loadSprites=function(){for(var e in g)g[e].oSprite.oSpriteLibrary=this,g[e].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
g[e].oSprite.src=g[e].szPath};this.getNumSprites=function(){return k}}var CANVAS_WIDTH=768,CANVAS_HEIGHT=1024,DISABLE_SOUND_MOBILE=!0,STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,CELL_SIZE=195,CELL_PADDING=15,CELL_SCALING_3x3=1,CELL_SCALING_5x5=.7,CELL_SCALING_7x7=.5,MATRIX_YOFFSET=200;
function CToggle(g,k,n){var e,l,m;this._init=function(g,h,b){e=[];l=[];b=new createjs.SpriteSheet({images:[b],frames:{width:b.width/2,height:b.height,regX:b.width/2/2,regY:b.height/2},animations:{on:[0,1],off:[1,2]}});m=s_bAudioActive?new createjs.Sprite(b,"on"):new createjs.Sprite(b,"off");m.x=g;m.y=h;m.stop();s_oStage.addChild(m);this._initListener()};this.unload=function(){m.off("mousedown",this.buttonDown);m.off("pressup",this.buttonRelease);s_oStage.removeChild(m)};this._initListener=function(){m.on("mousedown",
this.buttonDown);m.on("pressup",this.buttonRelease)};this.addEventListener=function(g,h,b){e[g]=h;l[g]=b};this.buttonRelease=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("press_but");m.scaleX=1;m.scaleY=1;(s_bAudioActive=!s_bAudioActive)?m.gotoAndStop("on"):m.gotoAndStop("off");e[ON_MOUSE_UP]&&e[ON_MOUSE_UP].call(l[ON_MOUSE_UP])};this.buttonDown=function(){m.scaleX=.9;m.scaleY=.9;e[ON_MOUSE_DOWN]&&e[ON_MOUSE_DOWN].call(l[ON_MOUSE_DOWN])};this._init(g,k,n)}
(function(g){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(g)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(g.substr(0,
4))})(navigator.userAgent||navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(g){console.log(g)}$(window).ready(function(){sizeHandler()});window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}

function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a=CANVAS_WIDTH,b=CANVAS_HEIGHT,c,d;!0===inIframe()&&"ios"==getMobileOperatingSystem()?top.location.href=document.location.href:(c=window.innerWidth,d=window.innerHeight,console.log("h: "+d),multiplier=Math.min(d/b,c/a),a*=multiplier,b*=multiplier,$("#canvas").css("width",a+"px"),$("#canvas").css("height",b+"px"),$("#canvas").css("left",c/2-a/2+"px"))}}
function getMobileOperatingSystem(){var a=navigator.userAgent||navigator.vendor||window.opera;return a.match(/iPad/i)||a.match(/iPhone/i)||a.match(/iPod/i)?"ios":a.match(/Android/i)?"android":"unknown"}function inIframe(){try{return window.self!==window.top}catch(a){return!0}};

function randomFloatBetween(g,k,n){"undefined"===typeof n&&(n=2);return parseFloat(Math.min(g+Math.random()*(k-g),k).toFixed(n))}
function shuffle(g){for(var k=g.length,n,e;0!==k;)e=Math.floor(Math.random()*k),k-=1,n=g[k],g[k]=g[e],g[e]=n;return g}function formatTime(g){g/=1E3;var k=Math.floor(g/60);g=Math.floor(g-60*k);var n="",n=10>k?n+("0"+k+":"):n+(k+":");return n=10>g?n+("0"+g):n+g}
Array.prototype.sortOn=function(){var g=this.slice();if(!arguments.length)return g.sort();var k=Array.prototype.slice.call(arguments);return g.sort(function(g,e){for(var l=k.slice(),m=l.shift();g[m]==e[m]&&l.length;)m=l.shift();return g[m]==e[m]?0:g[m]>e[m]?1:-1})};function roundDecimal(g,k){var n=Math.pow(10,k);return Math.round(n*g)/n}function tweenVectors(g,k,n,e){e.set(g.getX()+n*(k.getX()-g.getX()),g.getY()+n*(k.getY()-g.getY()));return e}
function NoClickDelay(g){this.element=g;window.Touch&&this.element.addEventListener("touchstart",this,!1)}
NoClickDelay.prototype={handleEvent:function(g){switch(g.type){case "touchstart":this.onTouchStart(g);break;case "touchmove":this.onTouchMove(g);break;case "touchend":this.onTouchEnd(g)}},onTouchStart:function(g){g.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(g){this.moved=!0},onTouchEnd:function(g){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){g=document.elementFromPoint(g.changedTouches[0].clientX,g.changedTouches[0].clientY);3===g.nodeType&&(g=g.parentNode);var k=document.createEvent("MouseEvents");k.initEvent("click",!0,!0);g.dispatchEvent(k)}}};
function CTextButton(g,k,n,e,l,m,q,h){var b,p,r,d,a,c,f,s,t,u;this._init=function(e,g,h,m,k,n,l,q){b=!1;d=[];a=[];u=q;f=new createjs.Bitmap(h);p=h.width;r=h.height;q=Math.ceil(l/20);s=new createjs.Text(m,"bold "+l+"px "+k,"#000000");var v=s.getBounds();s.textAlign="center";s.textBaseline="alphabetic";s.x=h.width/2+q;s.y=Math.floor(h.height/2)+v.height/3+q;t=new createjs.Text(m,"bold "+l+"px "+k,n);t.textAlign="center";t.textBaseline="alphabetic";t.x=h.width/2;t.y=Math.floor(h.height/2)+v.height/3;
c=new createjs.Container;c.x=e;c.y=g;c.regX=h.width/2;c.regY=h.height/2;c.addChild(f,s,t);u.addChild(c);this._initListener()};this.unload=function(){c.off("mousedown");c.off("pressup");u.removeChild(c)};this.setVisible=function(a){c.visible=a};this.enable=function(){b=!1;f.filters=[];f.cache(0,0,p,r)};this.disable=function(){b=!0;var a=(new createjs.ColorMatrix).adjustSaturation(-100);f.filters=[new createjs.ColorMatrixFilter(a)];f.cache(0,0,p,r)};this._initListener=function(){oParent=this;c.on("mousedown",
this.buttonDown);c.on("pressup",this.buttonRelease)};this.addEventListener=function(c,b,e){d[c]=b;a[c]=e};this.buttonRelease=function(){b||(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("press_but"),c.scaleX=1,c.scaleY=1,d[ON_MOUSE_UP]&&d[ON_MOUSE_UP].call(a[ON_MOUSE_UP]))};this.buttonDown=function(){b||(c.scaleX=.9,c.scaleY=.9,d[ON_MOUSE_DOWN]&&d[ON_MOUSE_DOWN].call(a[ON_MOUSE_DOWN]))};this.setPosition=function(a,d){c.x=a;c.y=d};this.changeText=function(a){t.text=a;s.text=a};this.setX=
function(a){c.x=a};this.setY=function(a){c.y=a};this.getButtonImage=function(){return c};this.getX=function(){return c.x};this.getY=function(){return c.y};this._init(g,k,n,e,l,m,q,h);return this}
function CPreloader(){var g;this._init=function(){this._onAllPreloaderImagesLoaded()};this._onPreloaderImagesLoaded=function(){};this._onAllPreloaderImagesLoaded=function(){g=new createjs.Text("","bold 22px Arial center","#ffffff");g.x=CANVAS_WIDTH/2-40;g.y=CANVAS_HEIGHT/2;s_oStage.addChild(g)};this.unload=function(){s_oStage.removeChild(g)};this.refreshLoader=function(k){g.text=k+"%"};this._init()}
function CMenu(){var g,k,n,e,l;this._init=function(){g=new createjs.Bitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(g);var m=s_oSpriteLibrary.getSprite("but_box_2");k=new CTextButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-170,m,TEXT_BUT1PLAYER,"aachen_btroman","#ffffff",30,s_oStage);k.addEventListener(ON_MOUSE_UP,this._onBut1Player,this);m=s_oSpriteLibrary.getSprite("but_box_2");n=new CTextButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-75,m,TEXT_BUT2PLAYERS,"aachen_btroman","#ffffff",30,s_oStage);n.addEventListener(ON_MOUSE_UP,
this._onBut2Players,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)m=s_oSpriteLibrary.getSprite("audio_icon"),e=new CToggle(CANVAS_WIDTH-m.width/2+5,m.height/2+20,m),e.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);l=new createjs.Shape;l.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(l);createjs.Tween.get(l).to({alpha:0},500).call(function(){l.visible=!1})};this.unload=function(){k.unload();k=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)e.unload(),
e=null;s_oStage.removeAllChildren()};this._onBut1Player=function(){this.unload();s_oMain.gotoGameModeMenu(!1)};this._onBut2Players=function(){this.unload();s_oMain.gotoGameModeMenu(!0)};this._onAudioToggle=function(){createjs.Sound.setMute(!s_bAudioActive)};this._init()}
function CMain(g){var k=0,n=0,e={},l,m=!1;this.initContainer=function(){s_oStage=new createjs.Stage("canvas");createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&s_oStage.enableMouseOver(20);s_iPrevTime=(new Date).getTime();createjs.Ticker.setFPS(30);createjs.Ticker.addEventListener("tick",this._update);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();s_oSpriteLibrary=new CSpriteLibrary;l=new CPreloader;this._loadImages()};this.soundLoaded=function(){k++;k===
n&&(l.unload(),this.gotoMenu())};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&(0<navigator.userAgent.indexOf("Opera")||0<navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=["mp3"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/gameover.ogg","gameover"),createjs.Sound.registerSound("./sounds/place_mark.ogg","place_mark"),createjs.Sound.registerSound("./sounds/press_but.ogg","press_but"),
createjs.Sound.registerSound("./sounds/win.ogg","win"),createjs.Sound.registerSound("./sounds/draw.ogg","draw")):(createjs.Sound.alternateExtensions=["ogg"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/gameover.mp3","gameover"),createjs.Sound.registerSound("./sounds/place_mark.mp3","place_mark"),createjs.Sound.registerSound("./sounds/press_but.mp3","press_but"),createjs.Sound.registerSound("./sounds/win.mp3","win"),createjs.Sound.registerSound("./sounds/draw.mp3",
"draw")),n+=5)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("but_box_1","./sprites/but_box_1.png");s_oSpriteLibrary.addSprite("but_box_2","./sprites/but_box_2.png");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("cell","./sprites/cell.png");s_oSpriteLibrary.addSprite("choose_text",
"./sprites/choose_text.png");s_oSpriteLibrary.addSprite("but_3x3","./sprites/layout_3x3.png");s_oSpriteLibrary.addSprite("but_5x5","./sprites/layout_5x5.png");s_oSpriteLibrary.addSprite("but_7x7","./sprites/layout_7x7.png");s_oSpriteLibrary.addSprite("panel","./sprites/panel.png");s_oSpriteLibrary.addSprite("tokenX","./sprites/player_1.png");s_oSpriteLibrary.addSprite("tokenO","./sprites/player_2.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("tris_line",
"./sprites/tris_line.png");n+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){k++;l.refreshLoader(Math.floor(k/n*100));k===n&&(l.unload(),this.gotoMenu())};this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this.gotoMenu=function(){new CMenu};this.gotoGameModeMenu=function(e){m=e?!0:!1;new CGameModeMenu};this.gotoGame=function(g){e.iMatrixSize=g;e.b2Players=m;new CGame(e);$(s_oMain).trigger("game_start")};
this.gotoHelp=function(){new CHelp};this._update=function(e){var h=(new Date).getTime();s_iTimeElaps=h-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=h;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);s_oStage.update(e)};s_oMain=this;e=g;this.initContainer()}var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oGameSettings;TEXT_GAMEOVER="GAME OVER";TEXT_PLAY="PLAY";
TEXT_PLAYAGAIN="PLAY AGAIN";TEXT_PL1_VICTORY="PLAYER 1\n WINS!!!";TEXT_PL2_VICTORY="PLAYER 2\n WINS!!!";TEXT_DRAW="DRAW!!!";TEXT_BUT1PLAYER="1 Player";TEXT_BUT2PLAYERS="2 Players";TEXT_ACTIVEPLAYER={pt1:"Player ",pt2:" to move"};TEXT_AIACTIVEPLAYER={pt1:"AI ",pt2:" to move"};TEXT_THREE_IN_ROW="PLACE 3 IN A ROW!";TEXT_FOUR_IN_ROW="PLACE 4 IN A ROW!";
function CInterface(g){var k,n,e,l,m;this._init=function(g){n=new createjs.Bitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(n);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile){var h=s_oSpriteLibrary.getSprite("audio_icon");k=new CToggle(CANVAS_WIDTH-h.width/2-30,h.height/2+20,h);k.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this)}h=s_oSpriteLibrary.getSprite("but_exit");e=new CGfxButton(CANVAS_WIDTH-h.width/2+5,h.height/2+14,h);e.addEventListener(ON_MOUSE_UP,this._onExit,this);h=
TEXT_ACTIVEPLAYER.pt1+s_oGame.getActivePlayer()+TEXT_ACTIVEPLAYER.pt2;l=new createjs.Text(h,"bold 52px aachen_btroman","White");l.x=CANVAS_WIDTH/2;l.y=100;l.textBaseline="alphabetic";l.textAlign="center";l.shadow=new createjs.Shadow("#000000",6,6,2);s_oStage.addChild(l);m=new createjs.Text(3<g?TEXT_FOUR_IN_ROW:TEXT_THREE_IN_ROW,"bold 30px aachen_btroman","White");m.x=CANVAS_WIDTH/2;m.y=CANVAS_HEIGHT-30;m.textBaseline="alphabetic";m.textAlign="center";m.shadow=new createjs.Shadow("#000000",3,3,2);
s_oStage.addChild(m)};this.unload=function(){s_oStage.removeChild(n);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||k.unload();e.unload();s_oStage.removeChild(l)};this.update=function(){var e=TEXT_ACTIVEPLAYER.pt1+s_oGame.getActivePlayer()+TEXT_ACTIVEPLAYER.pt2;createjs.Tween.get(l).to({scaleX:.1,scaleY:1.2,alpha:.5},250,createjs.Ease.cubicOut).call(function(){l.text=e;createjs.Tween.get(l).to({scaleX:1,scaleY:1,alpha:1},250,createjs.Ease.cubicIn)})};this._onExit=function(){this.unload();s_oGame.unload()};
this._init(g);return this}
function CGfxButton(g,k,n){var e,l,m,q,h,b=[],p;this._init=function(b,d,a){e=!1;q=[];h=[];l=a.width;m=a.height;p=new createjs.Bitmap(a);p.x=b;p.y=d;p.regX=a.width/2;p.regY=a.height/2;s_oStage.addChild(p);this._initListener()};this.unload=function(){p.off("mousedown",this.buttonDown);p.off("pressup",this.buttonRelease);s_oStage.removeChild(p)};this.setVisible=function(b){p.visible=b};this._initListener=function(){p.on("mousedown",this.buttonDown);p.on("pressup",this.buttonRelease)};this.addEventListener=
function(b,d,a){q[b]=d;h[b]=a};this.addEventListenerWithParams=function(e,d,a,c){q[e]=d;h[e]=a;b=c};this.buttonRelease=function(){e||(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("press_but"),p.scaleX=1,p.scaleY=1,q[ON_MOUSE_UP]&&q[ON_MOUSE_UP].call(h[ON_MOUSE_UP],b))};this.buttonDown=function(){e||(p.scaleX=.9,p.scaleY=.9,q[ON_MOUSE_DOWN]&&q[ON_MOUSE_DOWN].call(h[ON_MOUSE_DOWN],b))};this.setPosition=function(b,d){p.x=b;p.y=d};this.setX=function(b){p.x=b};this.setY=function(b){p.y=
b};this.enable=function(){e=!1;p.filters=[];p.cache(0,0,l,m)};this.disable=function(){e=!0;var b=(new createjs.ColorMatrix).adjustSaturation(-100).adjustBrightness(40);p.filters=[new createjs.ColorMatrixFilter(b)];p.cache(0,0,l,m)};this.getButtonImage=function(){return p};this.getX=function(){return p.x};this.getY=function(){return p.y};this._init(g,k,n);return this}
function CGameModeMenu(){var g,k,n,e,l,m;this._init=function(){g=new createjs.Bitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(g);var q=new createjs.Bitmap(s_oSpriteLibrary.getSprite("choose_text"));q.x=40;q.y=310;s_oStage.addChild(q);k=new createjs.Bitmap(s_oSpriteLibrary.getSprite("but_3x3"));k.x=70;k.y=450;s_oStage.addChild(k);k.on("click",function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("press_but");this._onBut3x3()},this);n=new createjs.Bitmap(s_oSpriteLibrary.getSprite("but_5x5"));
n.x=275;n.y=450;s_oStage.addChild(n);n.on("click",function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("press_but");this._onBut5x5()},this);e=new createjs.Bitmap(s_oSpriteLibrary.getSprite("but_7x7"));e.x=480;e.y=450;s_oStage.addChild(e);e.on("click",function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("press_but");this._onBut7x7()},this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)q=s_oSpriteLibrary.getSprite("audio_icon"),l=new CToggle(CANVAS_WIDTH-q.width/
2+5,q.height/2+20,q),l.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);m=new createjs.Shape;m.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(m);createjs.Tween.get(m).to({alpha:0},500).call(function(){m.visible=!1})};this.unload=function(){k.removeAllEventListeners();n.removeAllEventListeners();e.removeAllEventListeners();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)l.unload(),l=null;s_oStage.removeAllChildren()};this._onBut3x3=function(){this.unload();
s_oMain.gotoGame(3)};this._onBut5x5=function(){this.unload();s_oMain.gotoGame(5)};this._onBut7x7=function(){this.unload();s_oMain.gotoGame(7)};this._onAudioToggle=function(){createjs.Sound.setMute(!s_bAudioActive)};this._init()}
function CGame(g){var k=!1,n,e,l=1,m=0,q=0,h=[],b=[],p=[],r;this._init=function(b){n=b.b2Players;e=b.iMatrixSize;r=new CInterface(e);this.initMatrix();this._initWinCellsArray()};this.unload=function(){for(var b=0;b<e;b++)for(var a=0;a<e;a++)p[b][a].unload();r.unload();s_oMain.gotoMenu()};this.initMatrix=function(){for(var d=0;d<e;d++){p[d]=[];b[d]=[];for(var a=0;a<e;a++){var c,f,g,h=MATRIX_YOFFSET;3===e?g=CELL_SCALING_3x3:5===e?g=CELL_SCALING_5x5:7===e&&(g=CELL_SCALING_7x7);c=a*(CELL_SIZE+CELL_PADDING)*
g;f=d*(CELL_SIZE+CELL_PADDING)*g;c+=(CANVAS_WIDTH-CELL_SIZE*g*e)/2-30*g;f+=h;p[d][a]=new CCell(c,f,g,a,d);b[d][a]=0}}};this._initWinCellsArray=function(){if(3===e)for(var b=0;3>b;b++)h[b]={x:0,y:0};else for(b=0;4>b;b++)h[b]={x:0,y:0}};this.getActivePlayer=function(){return l};this.updateGameStatus=function(d,a){if(!k){b[a][d]=l;m++;3===e&&(5<=m?this.checkTris():this._switchPlayer());if(5===e||7===e)7<=m?this.checkQuad():this._switchPlayer();r.update()}};this._switchPlayer=function(){1===l?!0===n?
l=2:(l=2,this._AINext()):l=1};this._checkWinningCouples=function(d){for(var a={x:void 0,y:void 0},c=0;c<e;c++)for(var f=0;f<e;f++){if(b[c][f]===d){if(c<=e-3&&b[c][f]===b[c+1][f]&&0===b[c+2][f])return a.x=f,a.y=c+2,a;if(f<=e-3&&b[c][f]===b[c][f+1]&&0===b[c][f+2])return a.x=f+2,a.y=c,a;if(f<=e-3&&c<=e-3&&b[c][f]===b[c+1][f+1]&&0===b[c+2][f+2])return a.x=f+2,a.y=c+2,a}if(f<=e-3&&c<=e-3&&b[c+2][f]===d&&b[c+2][f]===b[c+1][f+1]&&0===b[c][f+2])return a.x=f+2,a.y=c,a;if(0===b[c][f]&&(c<=e-3&&d===b[c+1][f]&&
d===b[c+2][f]||f<=e-3&&d===b[c][f+1]&&d===b[c][f+2]||f<=e-3&&c<=e-3&&d===b[c+1][f+1]&&d===b[c+2][f+2]))return a.x=f,a.y=c,a;if(f<=e-3&&c<=e-3&&0===b[c+2][f]&&d===b[c+1][f+1]&&d===b[c][f+2])return a.x=f,a.y=c+2,a;if(b[c][f]===d){if(c<=e-3&&0===b[c+1][f]&&d===b[c+2][f])return a.x=f,a.y=c+1,a;if(f<=e-3&&0===b[c][f+1]&&d===b[c][f+2])return a.x=f+1,a.y=c,a;if(f<=e-3&&c<=e-3&&0===b[c+1][f+1]&&d===b[c+2][f+2])return a.x=f+1,a.y=c+1,a}if(f<=e-3&&c<=e-3&&b[c+2][f]===d&&0===b[c+1][f+1]&&d===b[c][f+2])return a.x=
f+1,a.y=c+1,a}return a};this._checkWinningTriples=function(d){for(var a={x:void 0,y:void 0},c=0;c<e;c++)for(var f=0;f<e;f++){if(b[c][f]===d){if(c<=e-4&&b[c][f]===b[c+1][f]&&b[c][f]===b[c+2][f]&&0===b[c+3][f])return a.x=f,a.y=c+3,a;if(f<=e-4&&b[c][f]===b[c][f+1]&&b[c][f]===b[c][f+2]&&0===b[c][f+3])return a.x=f+3,a.y=c,a;if(f<=e-4&&c<=e-4&&b[c][f]===b[c+1][f+1]&&b[c][f]===b[c+2][f+2]&&0===b[c+3][f+3])return a.x=f+3,a.y=c+3,a}if(f<=e-4&&c<=e-4&&b[c+3][f]===d&&b[c+3][f]===b[c+2][f+1]&&b[c+3][f]===b[c+
1][f+2]&&0===b[c][f+3])return a.x=f+3,a.y=c,a;if(0===b[c][f]&&(c<=e-4&&d===b[c+1][f]&&d===b[c+2][f]&&d===b[c+3][f]||f<=e-4&&d===b[c][f+1]&&d===b[c][f+2]&&d===b[c][f+3]||f<=e-4&&c<=e-4&&d===b[c+1][f+1]&&d===b[c+2][f+2]&&d===b[c+3][f+3]))return a.x=f,a.y=c,a;if(f<=e-4&&c<=e-4&&0===b[c+3][f]&&d===b[c+2][f+1]&&d===b[c+1][f+2]&&d===b[c][f+3])return a.x=f,a.y=c+3,a;if(b[c][f]===d){if(c<=e-4&&0===b[c+1][f]&&d===b[c+2][f]&&d===b[c+3][f])return a.x=f,a.y=c+1,a;if(f<=e-4&&0===b[c][f+1]&&d===b[c][f+2]&&d===
b[c][f+3])return a.x=f+1,a.y=c,a;if(f<=e-4&&c<=e-4&&0===b[c+1][f+1]&&d===b[c+2][f+2]&&d===b[c+3][f+3])return a.x=f+1,a.y=c+1,a}if(f<=e-4&&c<=e-4&&b[c+3][f]===d&&0===b[c+2][f+1]&&d===b[c+1][f+2]&&d===b[c][f+3])return a.x=f+1,a.y=c+2,a}return a};this._checkForks=function(){for(var d={x:void 0,y:void 0},a=0;a<e;a++)for(var c=0;c<e;c++)if(a<=e-3&&c<=e-3&&2===b[a+2][c]&&2===b[a][c+2]&&0===b[a+1][c]&&0===b[a][c+1]||2<=a&&c<=e-3&&2===b[a-2][c]&&2===b[a][c+2]&&0===b[a-1][c]&&0===b[a][c+1]||2<=a&&2<=c&&2===
b[a-2][c]&&2===b[a][c-2]&&0===b[a-1][c]&&0===b[a][c-1]||a<=e-3&&2<=c&&2===b[a+2][c]&&2===b[a][c-2]&&0===b[a+1][c]&&0===b[a][c-1])return d.x=c,d.y=a,d;return d};this._checkWinningSingletons=function(d){for(var a={x:void 0,y:void 0},c=0;c<e;c++)for(var f=0;f<e;f++){if(b[c][f]===d){if(c<=e-3&&0===b[c+1][f])return a.x=f,a.y=c+1,a;if(f<=e-3&&0===b[c][f+1])return a.x=f+1,a.y=c,a;if(f<=e-3&&c<=e-3&&0===b[c+1][f+1])return a.x=f+1,a.y=c+1,a}if(f<=e-3&&c<=e-3&&b[c+1][f]===d&&0===b[c][f+1])return a.x=f+1,a.y=
c,a}return a};this.checkTris=function(){for(var d=0;d<e;d++)for(var a=0;a<e;a++){if(0!==b[d][a]){if(d<=e-3&&b[d][a]===b[d+1][a]&&b[d][a]===b[d+2][a]){h[0].x=a;h[0].y=d;h[1].x=a;h[1].y=d+1;h[2].x=a;h[2].y=d+2;this.endGame();return}if(a<=e-3&&b[d][a]===b[d][a+1]&&b[d][a]===b[d][a+2]){h[0].x=a;h[0].y=d;h[1].x=a+1;h[1].y=d;h[2].x=a+2;h[2].y=d;this.endGame();return}if(a<=e-3&&d<=e-3&&b[d][a]===b[d+1][a+1]&&b[d][a]===b[d+2][a+2]){h[0].x=a;h[0].y=d;h[1].x=a+1;h[1].y=d+1;h[2].x=a+2;h[2].y=d+2;this.endGame();
return}}if(a<=e-3&&d<=e-3&&0!==b[d+2][a]&&b[d+2][a]===b[d+1][a+1]&&b[d+2][a]===b[d][a+2]){h[0].x=a;h[0].y=d+2;h[1].x=a+1;h[1].y=d+1;h[2].x=a+2;h[2].y=d;this.endGame();return}}m===e*e&&(l=0,this.showEndPanel());this._switchPlayer()};this.checkQuad=function(){for(var d=0;d<e;d++)for(var a=0;a<e;a++){if(0!==b[d][a]){if(d<=e-4&&b[d][a]===b[d+1][a]&&b[d][a]===b[d+2][a]&&b[d][a]===b[d+3][a]){h[0].x=a;h[0].y=d;h[1].x=a;h[1].y=d+1;h[2].x=a;h[2].y=d+2;h[3].x=a;h[3].y=d+3;this.endGame();return}if(a<=e-4&&b[d][a]===
b[d][a+1]&&b[d][a]===b[d][a+2]&&b[d][a]===b[d][a+3]){h[0].x=a;h[0].y=d;h[1].x=a+1;h[1].y=d;h[2].x=a+2;h[2].y=d;h[3].x=a+3;h[3].y=d;this.endGame();return}if(a<=e-4&&d<=e-4&&b[d][a]===b[d+1][a+1]&&b[d][a]===b[d+2][a+2]&&b[d][a]===b[d+3][a+3]){h[0].x=a;h[0].y=d;h[1].x=a+1;h[1].y=d+1;h[2].x=a+2;h[2].y=d+2;h[3].x=a+3;h[3].y=d+3;this.endGame();return}}if(a<=e-4&&d<=e-4&&0!==b[d+3][a]&&b[d+3][a]===b[d+2][a+1]&&b[d+3][a]===b[d+1][a+2]&&b[d+3][a]===b[d][a+3]){h[0].x=a;h[0].y=d+3;h[1].x=a+1;h[1].y=d+2;h[2].x=
a+2;h[2].y=d+1;h[3].x=a+3;h[3].y=d;this.endGame();return}}m===e*e&&(l=0,this.showEndPanel());this._switchPlayer()};this._AINext=function(){var d={};3===e&&(d=this._checkWinningCouples(2),void 0===d.x&&(d=this._checkWinningCouples(1),void 0===d.x&&(d=this._checkForks())));if(5===e||7===e)d=this._checkWinningTriples(2),void 0===d.x&&(d=this._checkWinningTriples(1),void 0===d.x&&(d=this._checkWinningCouples(2),void 0===d.x&&(d=this._checkWinningCouples(1),void 0===d.x&&(d=this._checkWinningSingletons(2)))));
if(void 0===d.x)for(;;){var a=Math.floor(Math.random()*e),c=Math.floor(Math.random()*e);if(0===b[c][a]){d.x=a;d.y=c;break}}p[d.y][d.x].AIMove()};this.endGame=function(){for(var b=0;b<h.length;b++)p[h[b].y][h[b].x].EndAnim(),q++};this.showEndPanel=function(){if(1<q)q--;else if(1===q||0===l)new CEndPanel(l),n?!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("win"):0===l?!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("draw"):1===l?!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||
createjs.Sound.play("win"):!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("gameover")};this.onExit=function(){this.unload();s_oMain.gotoMenu();$(s_oMain).trigger("restart")};this.isFrozen=function(){return k};this.freeze=function(){k=!0};this.unFreeze=function(){k=!1};s_oGame=this;this._init(g)}var s_oGame;
function CEndPanel(g){var k,n,e,l,m;this._init=function(g){k=new createjs.Bitmap(s_oSpriteLibrary.getSprite("panel"));s_oStage.addChild(k);1===g?(n=new createjs.Bitmap(s_oSpriteLibrary.getSprite("tokenX")),e=new createjs.Text(TEXT_PL1_VICTORY,"bold 52px aachen_btroman","White"),n.x=150,n.y=380,e.x=CANVAS_WIDTH/2+70):2===g?(n=new createjs.Bitmap(s_oSpriteLibrary.getSprite("tokenO")),e=new createjs.Text(TEXT_PL2_VICTORY,"bold 52px aachen_btroman","White"),n.x=150,n.y=380,e.x=CANVAS_WIDTH/2+70):(e=new createjs.Text(TEXT_DRAW,
"bold 52px aachen_btroman","White"),e.x=CANVAS_WIDTH/2);e.y=CANVAS_HEIGHT/2-60;e.textBaseline="alphabetic";e.textAlign="center";e.shadow=new createjs.Shadow("#000000",6,6,2);s_oStage.addChild(n);s_oStage.addChild(e);var h=s_oSpriteLibrary.getSprite("but_box_2");l=new CTextButton(CANVAS_WIDTH/2,CANVAS_HEIGHT/2+85,h,TEXT_PLAYAGAIN,"aachen_btroman","#ffffff",30,s_oStage);l.addEventListener(ON_MOUSE_UP,this._onButPlayAgain,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)h=s_oSpriteLibrary.getSprite("audio_icon"),
m=new CToggle(CANVAS_WIDTH-h.width/2+5,h.height/2+20,h),m.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);_oFade=new createjs.Shape;_oFade.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(_oFade);$(s_oMain).trigger("end_game",[g]);createjs.Tween.get(_oFade).to({alpha:0},1E3).call(function(){_oFade.visible=!1})};this.unload=function(){l.unload();l=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)m.unload(),m=null;s_oStage.removeChild(k,n,e,_oFade)};this._onButPlayAgain=
function(){this.unload();s_oGame.unload()};this._onAudioToggle=function(){createjs.Sound.setMute(!s_bAudioActive)};this._init(g)}
function CCell(g,k,n,e,l){var m,q,h,b,p,r,d,a,c;this._init=function(e,g,k,n,l){m=0;q=n;h=l;b=k;n=s_oSpriteLibrary.getSprite("cell");d=new createjs.Bitmap(n);d.scaleX=d.scaleY=k;l=s_oSpriteLibrary.getSprite("tokenX");p=new createjs.Bitmap(l);p.x=n.width/2*k;p.y=n.height/2*k;p.regX=l.width/2;p.regY=l.height/2;p.scaleX=p.scaleY=k;p.alpha=0;l=s_oSpriteLibrary.getSprite("tokenO");r=new createjs.Bitmap(l);r.x=n.width/2*k;r.y=n.height/2*k;r.regX=l.width/2;r.regY=l.height/2;r.scaleX=r.scaleY=k;r.alpha=0;
a=new createjs.Shape;a.graphics.beginFill("black").drawRect(0,0,CELL_SIZE*k,CELL_SIZE*k);a.alpha=.05;c=new createjs.Container;c.x=e;c.y=g;c.addChild(d,p,r,a);c.on("click",function(){this.clicked()},this);s_oStage.addChild(c)};this.unload=function(){c.removeAllEventListeners();s_oStage.removeChild(c)};this.clicked=function(){s_oGame.isFrozen()||(c.removeAllEventListeners(),s_oGame.freeze(),this.showToken())};this.showToken=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("place_mark");
1===s_oGame.getActivePlayer()?(m=1,p.scaleX=p.scaleY=.5,p.alpha=.1,p.visible=!0,createjs.Tween.get(p).to({scaleX:1.2*b,scaleY:1.2*b,alpha:1},200,createjs.Ease.cubicOut).call(function(){createjs.Tween.get(p).to({scaleX:1*b,scaleY:1*b},200,createjs.Ease.cubicIn).call(function(){s_oGame.unFreeze();s_oGame.updateGameStatus(q,h)})})):(m=2,r.scaleX=p.scaleY=.5,r.alpha=.1,r.visible=!0,createjs.Tween.get(r).to({scaleX:1.2*b,scaleY:1.2*b,alpha:1},200,createjs.Ease.cubicOut).call(function(){createjs.Tween.get(r).to({scaleX:1*
b,scaleY:1*b},200,createjs.Ease.cubicIn).call(function(){s_oGame.unFreeze();s_oGame.updateGameStatus(q,h)})}))};this.AIMove=function(){c.removeAllEventListeners();s_oGame.freeze();m=2;r.alpha=0;createjs.Tween.get(r).wait(1E3).to({scaleX:1.2*b,scaleY:1.2*b,alpha:1},250,createjs.Ease.cubicOut).call(function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("place_mark");createjs.Tween.get(r).to({scaleX:1*b,scaleY:1*b},250,createjs.Ease.cubicIn).call(function(){s_oGame.unFreeze();s_oGame.updateGameStatus(q,
h)})})};this.EndAnim=function(){s_oGame.freeze();1===m?createjs.Tween.get(p).to({scaleX:1.5*b,scaleY:1.5*b,alpha:.8},1E3,createjs.Ease.cubicInOut).call(function(){createjs.Tween.get(p).to({scaleX:1*b,scaleY:1*b,alpha:1},1500,createjs.Ease.bounceOut).call(function(){s_oGame.showEndPanel()})}):createjs.Tween.get(r).to({scaleX:1.5*b,scaleY:1.5*b,alpha:.8},1E3,createjs.Ease.cubicInOut).call(function(){createjs.Tween.get(r).to({scaleX:1*b,scaleY:1*b,alpha:1},1500,createjs.Ease.bounceOut).call(function(){s_oGame.showEndPanel()})})};
this._init(g,k,n,e,l)};