function CGame(a){var e=!1,k,h,l,g,c,d,f,b,m,t,n,p,u,r=0,y,w,x,z,F,A,C,q,E,D,K,G,H,I,v,B=null,J;this._init=function(){l=GAME_STATE_IDLE;k=!0;u=d=g=0;F=[0,1,2,3,4];c=F[0];f=NUM_PAYLINES;p=TOTAL_MONEY;t=MIN_BET;n=t*f;A=[];for(var a=0;a<NUM_ROWS;a++){A[a]=[];for(var b=0;b<NUM_REELS;b++)A[a][b]=0}s_oTweenController=new CTweenController;H=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(H);this._initReels();I=createBitmap(s_oSpriteLibrary.getSprite("mask_slot"));s_oStage.addChild(I);
this._initStaticSymbols();this._initHitAreaColumn();v=new CInterface(t,n,p);J=new CBonusPanel;B=new CPayTablePanel;p<n&&v.disableSpin();MIN_WIN=s_aSymbolWin[0][s_aSymbolWin[0].length-1];for(a=0;a<s_aSymbolWin.length;a++)for(var m=s_aSymbolWin[a],b=0;b<m.length;b++)0!==m[b]&&m[b]<MIN_WIN&&(MIN_WIN=m[b]);e=!0};this.unload=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)createjs.Sound.stop(),s_oSoundTrack=null;s_oStage.removeChild(H);s_oStage.removeChild(I);v.unload();B.unload();for(var a=0;a<
w.length;a++)w[a].unload();for(a=0;a<NUM_ROWS;a++)for(var b=0;b<NUM_REELS;b++)x[a][b].unload();J.unload()};this._initReels=function(){var a=REEL_OFFSET_X,b=REEL_OFFSET_Y,c=0;w=[];for(var d=0;d<NUM_REELS;d++)w[d]=new CReelColumn(d,a,b,c),w[d+NUM_REELS]=new CReelColumn(d+NUM_REELS,a,b+SYMBOL_SIZE*NUM_ROWS,c),a+=SYMBOL_SIZE+SPACE_BETWEEN_SYMBOLS,c+=REEL_DELAY};this._initStaticSymbols=function(){var a=REEL_OFFSET_X,b=REEL_OFFSET_Y;x=[];for(var c=0;c<NUM_ROWS;c++){x[c]=[];for(var d=0;d<NUM_REELS;d++){var f=
new CStaticSymbolCell(c,d,a,b);x[c][d]=f;a+=SYMBOL_SIZE+SPACE_BETWEEN_SYMBOLS}a=REEL_OFFSET_X;b+=SYMBOL_SIZE}};this._initHitAreaColumn=function(){D=[];E=[];for(var a=376,b=120,c=0;c<NUM_REELS;c++){var d=createBitmap(s_oSpriteLibrary.getSprite("hold_col"));d.x=a;d.y=b;d.visible=!1;s_oStage.addChild(d);a+=150;E.push(d);D[c]=!1}C=[];q=[];for(var a=381,b=108,c=s_oSpriteLibrary.getSprite("hit_area_col"),d=0;d<NUM_REELS;d++){var f=new createjs.Text(TEXT_HOLD,"22px "+FONT_GAME,"#ffffff");f.visible=!1;f.x=
a+c.width/2;f.y=b+c.height-20;f.shadow=new createjs.Shadow("#000",1,1,2);f.textAlign="center";s_oStage.addChild(f);C[d]=f;f=new CGfxButton(a+c.width/2,b+c.height/2,c);f.setVisible(!1);f.addEventListenerWithParams(ON_MOUSE_UP,this._onHitAreaCol,this,{index:d});a+=150;q.push(f)}};this.generateFinalSymbols=function(){for(var a=0;a<NUM_ROWS;a++)for(var b=0;b<NUM_REELS;b++)!1===w[b].isHold()&&(A[a][b]=s_aRandSymbols[Math.floor(Math.random()*s_aRandSymbols.length)]);z=[];for(a=y=0;a<f;a++){var b=s_aPaylineCombo[a],
c=[],d=A[b[0].row][b[0].col];if(d!==BONUS_SYMBOL){var g=1,e=1;for(c.push({row:b[0].row,col:b[0].col,value:A[b[0].row][b[0].col]});d===WILD_SYMBOL&&e<NUM_REELS;)g++,d=A[b[e].row][b[e].col],c.push({row:b[e].row,col:b[e].col,value:A[b[e].row][b[e].col]}),e++;for(;e<b.length;e++)if(A[b[e].row][b[e].col]===d||A[b[e].row][b[e].col]===WILD_SYMBOL){if(A[b[e].row][b[e].col]===BONUS_SYMBOL)break;g++;c.push({row:b[e].row,col:b[e].col,value:A[b[e].row][b[e].col]})}else break;0<s_aSymbolWin[d-1][g-1]&&(y+=s_aSymbolWin[d-
1][g-1],z.push({line:a+1,amount:s_aSymbolWin[d-1][g-1],num_win:g,value:d,list:c}))}}h=!1;r=0;c=[];for(a=0;a<NUM_ROWS;a++)for(b=0;b<NUM_REELS;b++)A[a][b]===BONUS_SYMBOL&&(c.push({row:a,col:b,value:A[a][b]}),r++);r>=NUM_SYMBOLS_FOR_BONUS&&(z.push({line:-1,amount:0,num_win:r,value:BONUS_SYMBOL,list:c}),5<r&&(r=5),h=!0);return 0<z.length?!0:!1};this._generateRandSymbols=function(){for(var a=[],b=0;b<NUM_ROWS;b++)a[b]=s_aRandSymbols[Math.floor(Math.random()*s_aRandSymbols.length)];return a};this.reelArrived=
function(a,b){if(g>MIN_REEL_LOOPS)if(c===b){if(!1===w[a].isReadyToStop()){var d=a;a<NUM_REELS?(d+=NUM_REELS,w[d].setReadyToStop(),w[a].restart([A[0][a],A[1][a],A[2][a]],!0)):(d-=NUM_REELS,w[d].setReadyToStop(),w[a].restart([A[0][d],A[1][d],A[2][d]],!0))}}else w[a].restart(this._generateRandSymbols(),!1);else w[a].restart(this._generateRandSymbols(),!1),0===a&&g++};this.increaseReelLoops=function(){g+=2};this.stopNextReel=function(){d++;0===d%2&&(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("reel_stop",
{volume:.3}),c=F[d/2],d===2*NUM_REELS&&this._endReelAnimation())};this._endReelAnimation=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||K.stop();d=g=0;c=F[0];for(var a=0;a<NUM_REELS;a++)D[a]=!1,E[a].visible=!1,w[a].setHold(!1),w[a+NUM_REELS].setHold(!1);u=0;if(0<z.length){for(var f=0;f<z.length;f++){B.highlightCombo(z[f].value,z[f].num_win);-1!==z[f].line&&v.showLine(z[f].line);for(var e=z[f].list,a=0;a<e.length;a++)x[e[a].row][e[a].col].show(e[a].value)}y*=t;p+=y;SLOT_CASH-=y;0<y&&(v.refreshMoney(p),
v.refreshWinText(y));b=0;l=GAME_STATE_SHOW_ALL_WIN;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)G=createjs.Sound.play("win")}else k&&this.enableColumnHitArea(),l=GAME_STATE_IDLE;!1===k&&(k=!0);!1===h&&(v.disableBetBut(!1),v.enableGuiButtons());p<n&&v.disableSpin();$(s_oMain).trigger("end_bet",[p,0])};this.hidePayTable=function(){B.hide()};this._showWin=function(){var a;if(0<m){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||G.stop();-1!==z[m-1].line&&(a=z[m-1].line,v.hideLine(a));a=z[m-1].list;for(var b=
0;b<a.length;b++)x[a[b].row][a[b].col].stopAnim()}m===z.length&&(m=0);-1!==z[m].line&&(a=z[m].line,v.showLine(a));a=z[m].list;for(b=0;b<a.length;b++)x[a[b].row][a[b].col].show(a[b].value);m++};this._hideAllWins=function(){for(var a=0;a<z.length;a++)for(var c=z[a].list,d=0;d<c.length;d++)x[c[d].row][c[d].col].stopAnim();v.hideAllLines();m=b=0;b=TIME_SHOW_WIN;l=GAME_STATE_SHOW_WIN;h&&J.show(r)};this.enableColumnHitArea=function(){for(var a=0;a<NUM_REELS;a++)C[a].visible=!0,q[a].setVisible(!0)};this.disableColumnHitArea=
function(){for(var a=0;a<NUM_REELS;a++)C[a].visible=!1,q[a].setVisible(!1)};this.activateLines=function(a){f=a;this.removeWinShowing();n=a=t*f;v.refreshTotalBet(n);v.refreshNumLines(f);a>p?v.disableSpin():v.enableSpin()};this.addLine=function(){f===NUM_PAYLINES?f=1:f++;var a=t*f;n=a;v.refreshTotalBet(n);v.refreshNumLines(f);a>p?v.disableSpin():v.enableSpin()};this.changeCoinBet=function(){var a=Math.floor(100*(t+.05))/100;a>MAX_BET?(t=MIN_BET,n=t*f,v.refreshBet(t),v.refreshTotalBet(n),a=n):(a*=f,
t+=.05,t=Math.floor(100*t)/100,n=a,v.refreshBet(t),v.refreshTotalBet(n));a>p?v.disableSpin():v.enableSpin()};this.onMaxBet=function(){var a=MAX_BET;f=NUM_PAYLINES;a*=f;t=MAX_BET;n=a;v.refreshBet(t);v.refreshTotalBet(n);v.refreshNumLines(f);a>p?v.disableSpin():(v.enableSpin(),this.onSpin())};this._onHitAreaCol=function(a){a=a.index;!0===D[a]?(D[a]=!1,E[a].visible=!1,C[a].visible=!0,u--,w[a].setHold(!1),w[a+NUM_REELS].setHold(!1)):u<MAX_NUM_HOLD&&(D[a]=!0,u++,E[a].visible=!0,C[a].visible=!1,w[a].setHold(!0),
w[a+NUM_REELS].setHold(!0),!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("press_hold"));k=!1};this.removeWinShowing=function(){B.resetHighlightCombo();v.resetWin();for(var a=0;a<NUM_ROWS;a++)for(var b=0;b<NUM_REELS;b++)x[a][b].hide();for(a=0;a<w.length;a++)w[a].activate();l=GAME_STATE_IDLE};this.endBonus=function(a){p+=a;v.refreshMoney(p);v.disableBetBut(!1);v.enableGuiButtons()};this.onSpin=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)G&&G.stop(),K=createjs.Sound.play("reels",
{volume:.3});this.disableColumnHitArea();v.disableBetBut(!0);this.removeWinShowing();if(SLOT_CASH<MIN_WIN){do var a=this.generateFinalSymbols();while(!0===a)}else if(Math.floor(100*Math.random())>WIN_OCCURRENCE){do a=this.generateFinalSymbols();while(!0===a)}else if(Math.floor(100*Math.random())>BONUS_OCCURRENCE){do a=this.generateFinalSymbols();while(!1===a||y*t>SLOT_CASH)}else{do a=this.generateFinalSymbols();while(!1===a||y*t>SLOT_CASH||!1===h)}v.hideAllLines();v.disableGuiButtons();p-=n;v.refreshMoney(p);
SLOT_CASH+=n;l=GAME_STATE_SPINNING};this.onInfoClicked=function(){l!==GAME_STATE_SPINNING&&(B.isVisible()?B.hide():B.show())};this.onExit=function(){this.unload();s_oMain.gotoMenu();$(s_oMain).trigger("restart")};this.getState=function(){return l};this.update=function(){if(!1!==e)switch(l){case GAME_STATE_SPINNING:for(var a=0;a<w.length;a++)w[a].update(c);break;case GAME_STATE_SHOW_ALL_WIN:b+=s_iTimeElaps;b>TIME_SHOW_ALL_WINS&&this._hideAllWins();break;case GAME_STATE_SHOW_WIN:b+=s_iTimeElaps,b>TIME_SHOW_WIN&&
(b=0,this._showWin())}};s_oGame=this;WIN_OCCURRENCE=a.win_occurrence;SLOT_CASH=a.slot_cash;BONUS_OCCURRENCE=a.bonus_occurrence;MIN_REEL_LOOPS=a.min_reel_loop;REEL_DELAY=a.reel_delay;TIME_SHOW_WIN=a.time_show_win;TIME_SHOW_ALL_WINS=a.time_show_all_wins;TOTAL_MONEY=a.money;MIN_BET=a.min_bet;MAX_BET=a.max_bet;MAX_NUM_HOLD=a.max_hold;PERC_WIN_BONUS_PRIZE_1=a.perc_win_bonus_prize_1;PERC_WIN_BONUS_PRIZE_2=a.perc_win_bonus_prize_2;PERC_WIN_BONUS_PRIZE_3=a.perc_win_bonus_prize_3;NUM_SYMBOLS_FOR_BONUS=a.num_symbol_bonus;
new CSlotSettings;this._init()}var s_oGame,s_oTweenController;
function CBonusPanel(){var a,e,k,h,l,g,c,d,f,b,m,t,n,p,u,r,y;this._init=function(){r=new createjs.Container;s_oStage.addChild(r);var a=createBitmap(s_oSpriteLibrary.getSprite("bonus_bg"));r.alpha=0;r.visible=!1;r.addChild(a);d=[];for(var a=s_oSpriteLibrary.getSprite("bonus_item"),b=[{x:530,y:496},{x:684,y:496},{x:838,y:496},{x:376,y:496},{x:992,y:496}],c=0;5>c;c++){var e=createBitmap(a);e.on("click",this._onItemReleased,this,!1,c);e.x=b[c].x;e.y=b[c].y;e.regY=a.height;e.visible=!1;r.addChild(e);d[c]=
e}u=new createjs.Container;u.visible=!1;r.addChild(u);f=[];for(b=0;25>b;b++)a=s_oSpriteLibrary.getSprite("bonus_item_"+b),c=createBitmap(a),u.addChild(c),0<b&&(c.visible=!1),f.push(c);u.regY=a.height;a=s_oSpriteLibrary.getSprite("star_bonus");b=new createjs.SpriteSheet({framerate:10,images:[a],frames:{width:Math.floor(a.width/NUM_PRIZES),height:a.height,regX:Math.floor(a.width/NUM_PRIZES)/2,regY:a.height/2},animations:{star_0:[0],star_1:[1],star_2:[2]}});n=createSprite(b,"star_0",Math.floor(a.width/
NUM_PRIZES)/2,a.height/2,Math.floor(a.width/NUM_PRIZES),a.height);r.addChild(n);m=[];t=[];m[0]=createSprite(b,"star_0",Math.floor(a.width/NUM_PRIZES)/2,a.height/2,Math.floor(a.width/NUM_PRIZES),a.height);m[0].x=340;m[0].y=CANVAS_HEIGHT-70;r.addChild(m[0]);c=new createjs.Text("100","34px "+FONT_GAME,"#ffff00");c.textAlign="left";c.x=m[0].x+a.width/NUM_PRIZES/2+6;c.y=m[0].y+12;c.textBaseline="alphabetic";r.addChild(c);t.push(c);m[1]=createSprite(b,"star_1",Math.floor(a.width/NUM_PRIZES)/2,a.height/
2,Math.floor(a.width/NUM_PRIZES),a.height);m[1].x=640;m[1].y=CANVAS_HEIGHT-70;r.addChild(m[1]);c=new createjs.Text("200","34px "+FONT_GAME,"#ffff00");c.textAlign="left";c.x=m[1].x+ +(a.width/NUM_PRIZES)/2+6;c.y=m[1].y+12;c.textBaseline="alphabetic";r.addChild(c);t.push(c);m[2]=createSprite(b,"star_2",Math.floor(a.width/NUM_PRIZES)/2,a.height/2,Math.floor(a.width/NUM_PRIZES),a.height);m[2].x=940;m[2].y=CANVAS_HEIGHT-70;r.addChild(m[2]);c=new createjs.Text("300","34px "+FONT_GAME,"#ffff00");c.textAlign=
"left";c.x=m[2].x+ +(a.width/NUM_PRIZES)/2+6;c.y=m[2].y+12;c.textBaseline="alphabetic";r.addChild(c);t.push(c);p=new createjs.Text("+ 300$","bold 80px Arial","#ffff00");p.alpha=0;p.textAlign="center";p.shadow=new createjs.Shadow("#000",2,2,2);p.x=CANVAS_WIDTH/2;p.y=150;p.textBaseline="alphabetic";r.addChild(p)};this.unload=function(){for(var a=0;5>a;a++)d[a].off("click",this._onItemReleased)};this.show=function(c){a=!1;l=h=p.alpha=0;g=4;switch(c){case 3:b=[50,500,2E3];break;case 4:b=[500,2E3,5E3];
break;case 5:b=[1E3,5E3,1E4];break;default:b=[50,500,2E3]}t[0].text=b[0]+"$";t[1].text=b[1]+"$";t[2].text=b[2]+"$";n.x=118;n.y=308;n.rotation=0;n.gotoAndStop("star_0");for(var f=0;f<c;f++)d[f].visible=!0;r.visible=!0;createjs.Tween.get(r).to({alpha:1},1E3);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundTrack.setVolume(0),y=createjs.Sound.play("soundtrack_bonus",{loop:-1})};this._onItemReleased=function(b,f){if(!a){a=!0;c=f;var e=Math.floor(Math.random()*s_aBonusItemOccurence.length);d[c].visible=
!1;this.playItemAnim(c,s_aBonusItemOccurence[e]);trace("_aItems["+c+"]: "+d[c].visible);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("bonus_item_choosen")}};this.playItemAnim=function(a,c){e=b[c];n.gotoAndStop("star_"+c);u.x=d[a].x;u.y=d[a].y;u.visible=!0;var f=this;k=setInterval(function(){f.update()},FPS_TIME)};this.endBonus=function(){p.text="+ "+e+"$";createjs.Tween.get(p).to({alpha:1},500);setTimeout(function(){r.alpha=0;r.visible=!1;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundTrack.setVolume(SOUNDTRACK_VOLUME),
y.stop();s_oGame.endBonus(e)},4E3)};this.setFrame=function(a,b){f[a].visible=!1;h=b;f[h].visible=!0};this.nextFrame=function(){f[h].visible=!1;h++;f[h].visible=!0};this.update=function(){19===h&&l<g?(this.setFrame(19,7),l++):(this.nextFrame(),l===g&&24===h&&(clearInterval(k),f[f.length-1].visible=!1,this.endBonus(),!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("reveal_prize")))};this._init()}
function CBetBut(a,e,k){var h,l,g,c=[],d;this._init=function(a,b,c){h=!1;l=[];g=[];c=s_oSpriteLibrary.getSprite("bet_but");var e=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:0,regY:0},animations:{on:[0,1],off:[1,2]}});d=createSprite(e,"on",0,0,c.width/2,c.height);d.stop();d.x=a;d.y=b;d.regX=c.width/2;d.regY=c.height/2;s_oStage.addChild(d);this._initListener()};this.unload=function(){d.off("mousedown",this.buttonDown);d.off("pressup",this.buttonRelease);s_oStage.removeChild(d)};
this.disable=function(a){h=a};this.setVisible=function(a){d.visible=a};this.setOn=function(){d.gotoAndStop("on")};this.setOff=function(){d.gotoAndStop("off")};this._initListener=function(){d.on("mousedown",this.buttonDown);d.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){l[a]=b;g[a]=c};this.addEventListenerWithParams=function(a,b,d,e){l[a]=b;g[a]=d;c=e};this.buttonRelease=function(){l[ON_MOUSE_UP]&&!1===h&&(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("press_but"),
l[ON_MOUSE_UP].call(g[ON_MOUSE_UP],c))};this.buttonDown=function(){l[ON_MOUSE_DOWN]&&!1===h&&l[ON_MOUSE_DOWN].call(g[ON_MOUSE_DOWN],c)};this.setPosition=function(a,b){d.x=a;d.y=b};this.setX=function(a){d.x=a};this.setY=function(a){d.y=a};this.getButtonImage=function(){return d};this.getX=function(){return d.x};this.getY=function(){return d.y};this._init(a,e,k)}
function CSpriteLibrary(){var a,e,k,h,l,g;this.init=function(c,d,f){k=e=0;h=c;l=d;g=f;a={}};this.addSprite=function(c,d){a.hasOwnProperty(c)||(a[c]={szPath:d,oSprite:new Image},e++)};this.getSprite=function(c){return a.hasOwnProperty(c)?a[c].oSprite:null};this._onSpritesLoaded=function(){l.call(g)};this._onSpriteLoaded=function(){h.call(g);++k===e&&this._onSpritesLoaded()};this.loadSprites=function(){for(var c in a)a[c].oSprite.oSpriteLibrary=this,a[c].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
a[c].oSprite.src=a[c].szPath};this.getNumSprites=function(){return e}}
var CANVAS_WIDTH=1500,CANVAS_HEIGHT=640,EDGEBOARD_X=300,EDGEBOARD_Y=0,FONT_GAME="walibi0615bold",FPS_TIME=1E3/24,DISABLE_SOUND_MOBILE=!0,STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,GAME_STATE_IDLE=0,GAME_STATE_SPINNING=1,GAME_STATE_SHOW_ALL_WIN=2,GAME_STATE_SHOW_WIN=3,REEL_STATE_START=0,REEL_STATE_MOVING=1,REEL_STATE_STOP=2,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,REEL_OFFSET_X=380,REEL_OFFSET_Y=123,NUM_REELS=5,NUM_ROWS=3,NUM_SYMBOLS=10,
WILD_SYMBOL=10,BONUS_SYMBOL=9,NUM_PAYLINES=5,SYMBOL_SIZE=140,SPACE_BETWEEN_SYMBOLS=10,MAX_FRAMES_REEL_EASE=16,MIN_REEL_LOOPS,REEL_DELAY,REEL_START_Y=REEL_OFFSET_Y-3*SYMBOL_SIZE,REEL_ARRIVAL_Y=REEL_OFFSET_Y+3*SYMBOL_SIZE,TIME_SHOW_WIN,TIME_SHOW_ALL_WINS,MIN_BET,MAX_BET,TOTAL_MONEY,MAX_NUM_HOLD,NUM_PRIZES=3,NUM_SYMBOLS_FOR_BONUS,PERC_WIN_BONUS_PRIZE_1,PERC_WIN_BONUS_PRIZE_2,PERC_WIN_BONUS_PRIZE_3,SOUNDTRACK_VOLUME=.5,WIN_OCCURRENCE,SLOT_CASH,MIN_WIN,BONUS_OCCURRENCE;
function CTweenController(){this.tweenValue=function(a,e,k){return a+k*(e-a)};this.easeLinear=function(a,e,k,h){return k*a/h+e};this.easeInCubic=function(a,e,k,h){h=(a/=h)*a*a;return e+k*h};this.easeBackInQuart=function(a,e,k,h){h=(a/=h)*a;return e+k*(2*h*h+2*h*a+-3*h)};this.easeInBack=function(a,e,k,h){return k*(a/=h)*a*(2.70158*a-1.70158)+e};this.easeOutCubic=function(a,e,k,h){return k*((a=a/h-1)*a*a+1)+e}}
function CToggle(a,e,k){var h,l,g;this._init=function(a,d,f){h=[];l=[];var b=new createjs.SpriteSheet({images:[f],frames:{width:f.width/2,height:f.height,regX:f.width/2/2,regY:f.height/2},animations:{on:[0,1],off:[1,2]}});g=s_bAudioActive?createSprite(b,"on",f.width/2/2,f.height/2,f.width/2,f.height):createSprite(b,"off",f.width/2/2,f.height/2,f.width/2,f.height);g.x=a;g.y=d;g.stop();s_oStage.addChild(g);this._initListener()};this.unload=function(){g.off("mousedown",this.buttonDown);g.off("pressup",
this.buttonRelease);s_oStage.removeChild(g)};this._initListener=function(){g.on("mousedown",this.buttonDown);g.on("pressup",this.buttonRelease)};this.setPosition=function(a,d){g.x=a;g.y=d};this.addEventListener=function(a,d,f){h[a]=d;l[a]=f};this.buttonRelease=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("press_but");g.scaleX=1;g.scaleY=1;(s_bAudioActive=!s_bAudioActive)?g.gotoAndStop("on"):g.gotoAndStop("off");h[ON_MOUSE_UP]&&h[ON_MOUSE_UP].call(l[ON_MOUSE_UP])};this.buttonDown=
function(){g.scaleX=.9;g.scaleY=.9;h[ON_MOUSE_DOWN]&&h[ON_MOUSE_DOWN].call(l[ON_MOUSE_DOWN])};this._init(a,e,k)}
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,4))})(navigator.userAgent||
navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}
function getSize(a){var e=a.toLowerCase(),k=window.document,h=k.documentElement;if(void 0===window["inner"+a])a=h["client"+a];else if(window["inner"+a]!=h["client"+a]){var l=k.createElement("body");l.id="vpw-test-b";l.style.cssText="overflow:scroll";var g=k.createElement("div");g.id="vpw-test-d";g.style.cssText="position:absolute;top:-1000px";g.innerHTML="<style>@media("+e+":"+h["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+e+":7px!important}}</style>";l.appendChild(g);h.insertBefore(l,k.head);
a=7==g["offset"+a]?h["client"+a]:window["inner"+a];h.removeChild(l)}else a=window["inner"+a];return a}window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}
function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a;a=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var e=getSize("Width"),k=Math.min(a/CANVAS_HEIGHT,e/CANVAS_WIDTH),h=CANVAS_WIDTH*k,k=CANVAS_HEIGHT*k,l=0;k<a?(l=a-k,k+=l,h+=CANVAS_WIDTH/CANVAS_HEIGHT*l):h<e&&(l=e-h,h+=l,k+=CANVAS_HEIGHT/CANVAS_WIDTH*l);var l=a/2-k/2,g=e/2-h/2,c=CANVAS_WIDTH/h;if(g*c<-EDGEBOARD_X||l*c<-EDGEBOARD_Y)k=Math.min(a/(CANVAS_HEIGHT-2*EDGEBOARD_Y),e/(CANVAS_WIDTH-2*
EDGEBOARD_X)),h=CANVAS_WIDTH*k,k*=CANVAS_HEIGHT,l=(a-k)/2,g=(e-h)/2,c=CANVAS_WIDTH/h;s_iOffsetX=-1*g*c;s_iOffsetY=-1*l*c;0<=l&&(s_iOffsetY=0);0<=g&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);$("#canvas").css("width",h+"px");$("#canvas").css("height",k+"px");0>l?$("#canvas").css("top",l+"px"):$("#canvas").css("top","0px");$("#canvas").css("left",g+"px")}}
function createBitmap(a,e,k){var h=new createjs.Bitmap(a),l=new createjs.Shape;e&&k?l.graphics.beginFill("#fff").drawRect(0,0,e,k):l.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);h.hitArea=l;return h}function createSprite(a,e,k,h,l,g){a=null!==e?new createjs.Sprite(a,e):new createjs.Sprite(a);e=new createjs.Shape;e.graphics.beginFill("#000000").drawRect(-k,-h,l,g);a.hitArea=e;return a}
function randomFloatBetween(a,e,k){"undefined"===typeof k&&(k=2);return parseFloat(Math.min(a+Math.random()*(e-a),e).toFixed(k))}function shuffle(a){for(var e=a.length,k,h;0!==e;)h=Math.floor(Math.random()*e),--e,k=a[e],a[e]=a[h],a[h]=k;return a}function formatTime(a){a/=1E3;var e=Math.floor(a/60);a=parseFloat(a-60*e).toFixed(1);var k="",k=10>e?k+("0"+e+":"):k+(e+":");return k=10>a?k+("0"+a):k+a}
function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3===a.nodeType&&(a=a.parentNode);var e=document.createEvent("MouseEvents");e.initEvent("click",!0,!0);a.dispatchEvent(e)}}};
function CTextButton(a,e,k,h,l,g,c){var d,f,b,m,t,n,p,u;this._init=function(a,c,e,g,h,k,l){d=!1;m=[];t=[];u=createBitmap(e);f=e.width;b=e.height;p=new createjs.Text(g,"bold "+l+"px "+h,k);p.textAlign="center";p.shadow=new createjs.Shadow("#000",2,2,2);p.textBaseline="middle";p.lineHeight=24;p.x=e.width/2;p.y=e.height/2;n=new createjs.Container;n.x=a;n.y=c;n.regX=e.width/2;n.regY=e.height/2;n.addChild(u,p);s_oStage.addChild(n);this._initListener()};this.unload=function(){n.off("mousedown");n.off("pressup");
s_oStage.removeChild(n)};this.setVisible=function(a){n.visible=a};this.enable=function(){d=!1;u.filters=[];u.cache(0,0,f,b)};this.disable=function(){d=!0;var a=(new createjs.ColorMatrix).adjustSaturation(-100).adjustBrightness(40);u.filters=[new createjs.ColorMatrixFilter(a)];u.cache(0,0,f,b)};this._initListener=function(){oParent=this;n.on("mousedown",this.buttonDown);n.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){m[a]=b;t[a]=c};this.buttonRelease=function(){d||(!1!==DISABLE_SOUND_MOBILE&&
!1!==s_bMobile||createjs.Sound.play("press_but"),n.scaleX=1,n.scaleY=1,m[ON_MOUSE_UP]&&m[ON_MOUSE_UP].call(t[ON_MOUSE_UP]))};this.buttonDown=function(){d||(n.scaleX=.9,n.scaleY=.9,m[ON_MOUSE_DOWN]&&m[ON_MOUSE_DOWN].call(t[ON_MOUSE_DOWN]))};this.setPosition=function(a,b){n.x=a;n.y=b};this.changeText=function(a){p.text=a};this.setX=function(a){n.x=a};this.setY=function(a){n.y=a};this.getButtonImage=function(){return n};this.getX=function(){return n.x};this.getY=function(){return n.y};this._init(a,e,
k,h,l,g,c);return this}
function CStaticSymbolCell(a,e,k,h){var l=-1,g,c,d,f;this._init=function(a,e,g,h){f=new createjs.Container;f.visible=!1;c=[];for(a=0;a<NUM_SYMBOLS;a++)e=createSprite(s_aSymbolAnims[a],"static",0,0,SYMBOL_SIZE,SYMBOL_SIZE),e.stop(),e.x=g,e.y=h,e.on("animationend",this._onAnimEnded,null,!1,{index:a}),f.addChild(e),c[a]=e,c[a].visible=!1;a={framerate:60,images:[s_oSpriteLibrary.getSprite("win_frame_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,
19]}};a=new createjs.SpriteSheet(a);d=new createSprite(a,"static",0,0,SYMBOL_SIZE,SYMBOL_SIZE);d.stop();d.x=g;d.y=h;f.addChild(d);s_oStage.addChild(f)};this.unload=function(){s_oStage.removeChild(f)};this.hide=function(){-1<l&&(d.gotoAndStop("static"),d.visible=!1,c[l].gotoAndPlay("static"),f.visible=!1)};this.show=function(a){d.gotoAndPlay("anim");d.visible=!0;for(var e=0;e<NUM_SYMBOLS;e++)c[e].visible=e+1===a?!0:!1;c[a-1].gotoAndPlay("anim");l=a-1;g=c[a-1].spriteSheet.getNumFrames();f.visible=!0};
this._onAnimEnded=function(a,d){c[d.index].currentFrame!==g&&(c[d.index].stop(),setTimeout(function(){c[d.index].gotoAndPlay(1)},100))};this.stopAnim=function(){c[l].gotoAndStop("static");c[l].visible=!1;d.gotoAndStop("static");d.visible=!1};this._init(a,e,k,h)}
function CSlotSettings(){this._init=function(){this._initSymbolSpriteSheets();this._initPaylines();this._initSymbolWin();this._initSymbolAnims();this._initSymbolsOccurence();this._initBonus()};this._initSymbolSpriteSheets=function(){s_aSymbolData=[];for(var a=1;a<NUM_SYMBOLS+1;a++){var e={images:[s_oSpriteLibrary.getSprite("symbol_"+a)],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],moving:[1,2]}};s_aSymbolData[a]=new createjs.SpriteSheet(e)}};this._initPaylines=
function(){s_aPaylineCombo=[[{row:1,col:0},{row:1,col:1},{row:1,col:2},{row:1,col:3},{row:1,col:4}],[{row:0,col:0},{row:0,col:1},{row:0,col:2},{row:0,col:3},{row:0,col:4}],[{row:2,col:0},{row:2,col:1},{row:2,col:2},{row:2,col:3},{row:2,col:4}],[{row:0,col:0},{row:1,col:1},{row:2,col:2},{row:1,col:3},{row:0,col:4}],[{row:2,col:0},{row:1,col:1},{row:0,col:2},{row:1,col:3},{row:2,col:4}]]};this._initSymbolAnims=function(){s_aSymbolAnims=[];var a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_1_anim")],
frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[0]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_2_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[1]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_3_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,
1],anim:[1,14]}};s_aSymbolAnims[2]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_4_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[3]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_5_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[4]=new createjs.SpriteSheet(a);a={framerate:20,
images:[s_oSpriteLibrary.getSprite("symbol_6_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[5]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_7_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[6]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_8_anim")],frames:{width:SYMBOL_SIZE,
height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[7]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_9_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[8]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_10_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,
14]}};s_aSymbolAnims[9]=new createjs.SpriteSheet(a)};this._initSymbolWin=function(){s_aSymbolWin=[[0,0,1500,2500,5E3],[0,0,1E3,1500,2E3],[0,0,500,1E3,1500],[0,100,250,500,1E3],[0,100,250,500,1E3],[0,50,150,250,500],[0,20,100,200,350],[0,10,50,100,150],[0,10,50,100,150]]};this._initSymbolsOccurence=function(){s_aRandSymbols=[];var a;for(a=0;1>a;a++)s_aRandSymbols.push(1);for(a=0;2>a;a++)s_aRandSymbols.push(2);for(a=0;3>a;a++)s_aRandSymbols.push(3);for(a=0;4>a;a++)s_aRandSymbols.push(4);for(a=0;4>a;a++)s_aRandSymbols.push(5);
for(a=0;6>a;a++)s_aRandSymbols.push(6);for(a=0;7>a;a++)s_aRandSymbols.push(7);for(a=0;8>a;a++)s_aRandSymbols.push(8);for(a=0;2>a;a++)s_aRandSymbols.push(9);for(a=0;1>a;a++)s_aRandSymbols.push(10)};this._initBonus=function(){s_aBonusItemOccurence=[];var a;for(a=0;a<PERC_WIN_BONUS_PRIZE_1;a++)s_aBonusItemOccurence.push(0);for(a=0;a<PERC_WIN_BONUS_PRIZE_2;a++)s_aBonusItemOccurence.push(1);for(a=0;a<PERC_WIN_BONUS_PRIZE_3;a++)s_aBonusItemOccurence.push(2)};this._init()}
var s_aSymbolData,s_aPaylineCombo,s_aSymbolWin,s_aSymbolAnims,s_aRandSymbols,s_aBonusItemOccurence;
function CReelColumn(a,e,k,h){var l,g,c,d,f,b,m,t,n,p,u,r,y,w,x;this._init=function(a,e,h,k){d=c=g=l=!1;t=0;f=a;m=k;b=f<NUM_REELS?f:f-NUM_REELS;p=0;u=MAX_FRAMES_REEL_EASE;n=REEL_STATE_START;r=h;y=r+SYMBOL_SIZE*NUM_ROWS;this.initContainer(e,h)};this.initContainer=function(a,b){x=new createjs.Container;x.x=a;x.y=b;var c=0;w=[];for(var d=0;d<NUM_ROWS;d++){var e=createSprite(s_aSymbolData[s_aRandSymbols[Math.floor(Math.random()*s_aRandSymbols.length)]],"static",0,0,SYMBOL_SIZE,SYMBOL_SIZE);e.stop();e.x=
0;e.y=c;x.addChild(e);w[d]=e;c+=SYMBOL_SIZE}s_oStage.addChild(x)};this.unload=function(){s_oStage.removeChild(x)};this.activate=function(){r=x.y;y=r+SYMBOL_SIZE*NUM_ROWS;l=!0};this._setSymbol=function(a){x.removeAllChildren();for(var b=0,c=0;c<a.length;c++){var d=new createSprite(s_aSymbolData[a[c]],"static",0,0,SYMBOL_SIZE,SYMBOL_SIZE);d.stop();d.x=0;d.y=b;x.addChild(d);w[c]=d;b+=SYMBOL_SIZE}};this.setHold=function(a){d=a};this.restart=function(a,b){x.y=r=REEL_START_Y;y=r+SYMBOL_SIZE*NUM_ROWS;this._setSymbol(a);
if(g=b){p=0;u=MAX_FRAMES_REEL_EASE;n=REEL_STATE_STOP;for(var d=0;d<NUM_ROWS;d++)w[d].gotoAndStop("static");c=!0}else for(d=0;d<NUM_ROWS;d++)w[d].gotoAndStop("moving")};this.setReadyToStop=function(){p=0;u=MAX_FRAMES_REEL_EASE;n=REEL_STATE_STOP};this.isReadyToStop=function(){return g};this.isHold=function(){return d};this._updateStart=function(){0===p&&f<NUM_REELS&&(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("start_reel",{volume:.3}));p++;p>u&&(p=0,u/=2,n++,r=x.y,y=r+SYMBOL_SIZE*
NUM_ROWS);var a=s_oTweenController.easeInBack(p,0,1,u),a=s_oTweenController.tweenValue(r,y,a);x.y=a};this._updateMoving=function(){p++;p>u&&(p=0,r=x.y,y=r+SYMBOL_SIZE*NUM_ROWS);var a=s_oTweenController.easeLinear(p,0,1,u),a=s_oTweenController.tweenValue(r,y,a);x.y=a};this._updateStopping=function(){p++;if(p>=u)l=!1,p=0,u=MAX_FRAMES_REEL_EASE,n=REEL_STATE_START,t=0,g=!1,c&&(c=!1,x.y=REEL_OFFSET_Y),s_oGame.stopNextReel();else{var a=s_oTweenController.easeOutCubic(p,0,1,u),a=s_oTweenController.tweenValue(r,
y,a);x.y=a}};this.update=function(a){if(!1!==l&&(t++,t>m))if(d)a===f&&(l=!1,s_oGame.stopNextReel(),s_oGame.stopNextReel(),0===f&&s_oGame.increaseReelLoops());else switch(!1===g&&x.y>REEL_ARRIVAL_Y&&s_oGame.reelArrived(f,b),n){case REEL_STATE_START:this._updateStart();break;case REEL_STATE_MOVING:this._updateMoving();break;case REEL_STATE_STOP:this._updateStopping()}};this._init(a,e,k,h)}
function CPreloader(){var a,e,k,h,l,g,c;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_preloader","./sprites/bg_preloader.jpg");s_oSpriteLibrary.addSprite("preloader_bar","./sprites/preloader_bar.png");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.loadSprites();c=new createjs.Container;s_oStage.addChild(c)};this.unload=function(){c.removeAllChildren()};this.hide=function(){var a=
this;setTimeout(function(){createjs.Tween.get(g).to({alpha:1},500).call(function(){a.unload();s_oMain.gotoMenu()})},1E3)};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var d=createBitmap(s_oSpriteLibrary.getSprite("bg_preloader"));c.addChild(d);d=s_oSpriteLibrary.getSprite("preloader_bar");k=createBitmap(d);k.x=510;k.y=CANVAS_HEIGHT-171;c.addChild(k);h=createBitmap(s_oSpriteLibrary.getSprite("progress_bar"));
h.x=511;h.y=CANVAS_HEIGHT-170;c.addChild(h);a=d.width;l=new createjs.Shape;l.graphics.beginFill("rgba(255,0,0,0.01)").drawRect(511,CANVAS_HEIGHT-170,1,30);c.addChild(l);h.mask=l;e=new createjs.Text("","24px "+FONT_GAME,"#fff");e.x=CANVAS_WIDTH/2;e.y=CANVAS_HEIGHT-148;e.shadow=new createjs.Shadow("#000",2,2,2);e.textBaseline="alphabetic";e.textAlign="center";c.addChild(e);g=new createjs.Shape;g.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);g.alpha=0;c.addChild(g)};this.refreshLoader=
function(c){e.text=c+"%";l.graphics.clear();c=Math.floor(c*a/100);l.graphics.beginFill("rgba(255,0,0,0.01)").drawRect(511,CANVAS_HEIGHT-170,c,30)};this._init()}
function CPayTablePanel(){var a,e,k,h,l,g;this._init=function(){g=new createjs.Container;l=createBitmap(s_oSpriteLibrary.getSprite("paytable"));g.addChild(l);a=[];var c,d=404,f=90;a[0]=[];for(c=0;3>c;c++){var b=new createjs.Text("X"+(5-c),"bold 22px "+FONT_GAME,"#ffffff");b.textAlign="center";b.shadow=new createjs.Shadow("#000",1,1,2);b.x=d;b.y=f;b.textBaseline="alphabetic";g.addChild(b);a[0][c]=b;f+=30}d=634;f=90;a[1]=[];for(c=0;3>c;c++)b=new createjs.Text("X"+(5-c),"bold 22px "+FONT_GAME,"#ffffff"),
b.textAlign="center",b.shadow=new createjs.Shadow("#000",1,1,2),b.x=d,b.y=f,b.textBaseline="alphabetic",g.addChild(b),a[1][c]=b,f+=30;d=864;f=90;a[2]=[];for(c=0;3>c;c++)b=new createjs.Text("X"+(5-c),"bold 22px "+FONT_GAME,"#ffffff"),b.textAlign="center",b.shadow=new createjs.Shadow("#000",1,1,2),b.x=d,b.y=f,b.textBaseline="alphabetic",g.addChild(b),a[2][c]=b,f+=30;d=1098;f=84;a[3]=[];for(c=0;4>c;c++)b=new createjs.Text("X"+(5-c),"bold 21px "+FONT_GAME,"#ffffff"),b.textAlign="center",b.shadow=new createjs.Shadow("#000",
1,1,2),b.x=d,b.y=f,b.textBaseline="alphabetic",g.addChild(b),a[3][c]=b,f+=22;d=404;f=190;a[4]=[];for(c=0;4>c;c++)b=new createjs.Text("X"+(5-c),"bold 21px "+FONT_GAME,"#ffffff"),b.textAlign="center",b.shadow=new createjs.Shadow("#000",1,1,2),b.x=d,b.y=f,b.textBaseline="alphabetic",g.addChild(b),a[4][c]=b,f+=22;d=634;f=190;a[5]=[];for(c=0;4>c;c++)b=new createjs.Text("X"+(5-c),"bold 21px "+FONT_GAME,"#ffffff"),b.textAlign="center",b.shadow=new createjs.Shadow("#000",1,1,2),b.x=d,b.y=f,b.textBaseline=
"alphabetic",g.addChild(b),a[5][c]=b,f+=22;d=864;f=190;a[6]=[];for(c=0;4>c;c++)b=new createjs.Text("X"+(5-c),"bold 21px "+FONT_GAME,"#ffffff"),b.textAlign="center",b.shadow=new createjs.Shadow("#000",1,1,2),b.x=d,b.y=f,b.textBaseline="alphabetic",g.addChild(b),a[6][c]=b,f+=22;d=1096;f=190;a[7]=[];for(c=0;4>c;c++)b=new createjs.Text("X"+(5-c),"bold 21px "+FONT_GAME,"#ffffff"),b.textAlign="center",b.shadow=new createjs.Shadow("#000",1,1,2),b.x=d,b.y=f,b.textBaseline="alphabetic",g.addChild(b),a[7][c]=
b,f+=22;e=[];d=440;f=90;e[0]=[];for(c=0;3>c;c++)b=new createjs.Text(s_aSymbolWin[0][4-c],"22px "+FONT_GAME,"#ffff00"),b.textAlign="left",b.shadow=new createjs.Shadow("#000",1,1,2),b.x=d,b.y=f,b.textBaseline="alphabetic",g.addChild(b),e[0][c]=b,f+=30;d=670;f=90;e[1]=[];for(c=0;3>c;c++)b=new createjs.Text(s_aSymbolWin[1][4-c],"22px "+FONT_GAME,"#ffff00"),b.textAlign="left",b.shadow=new createjs.Shadow("#000",1,1,2),b.x=d,b.y=f,b.textBaseline="alphabetic",g.addChild(b),e[1][c]=b,f+=30;d=900;f=90;e[2]=
[];for(c=0;3>c;c++)b=new createjs.Text(s_aSymbolWin[2][4-c],"22px "+FONT_GAME,"#ffff00"),b.textAlign="left",b.shadow=new createjs.Shadow("#000",1,1,2),b.x=d,b.y=f,b.textBaseline="alphabetic",g.addChild(b),e[2][c]=b,f+=30;d=1130;f=84;e[3]=[];for(c=0;4>c;c++)b=new createjs.Text(s_aSymbolWin[3][4-c],"21px "+FONT_GAME,"#ffff00"),b.textAlign="left",b.shadow=new createjs.Shadow("#000",1,1,2),b.x=d,b.y=f,b.textBaseline="alphabetic",g.addChild(b),e[3][c]=b,f+=22;d=440;f=190;e[4]=[];for(c=0;4>c;c++)b=new createjs.Text(s_aSymbolWin[4][4-
c],"21px "+FONT_GAME,"#ffff00"),b.textAlign="left",b.shadow=new createjs.Shadow("#000",1,1,2),b.x=d,b.y=f,b.textBaseline="alphabetic",g.addChild(b),e[4][c]=b,f+=22;d=670;f=190;e[5]=[];for(c=0;4>c;c++)b=new createjs.Text(s_aSymbolWin[5][4-c],"21px "+FONT_GAME,"#ffff00"),b.textAlign="left",b.shadow=new createjs.Shadow("#000",1,1,2),b.x=d,b.y=f,b.textBaseline="alphabetic",g.addChild(b),e[5][c]=b,f+=22;d=900;f=190;e[6]=[];for(c=0;4>c;c++)b=new createjs.Text(s_aSymbolWin[6][4-c],"21px "+FONT_GAME,"#ffff00"),
b.textAlign="left",b.shadow=new createjs.Shadow("#000",1,1,2),b.x=d,b.y=f,b.textBaseline="alphabetic",g.addChild(b),e[6][c]=b,f+=22;d=1130;f=190;e[7]=[];for(c=0;4>c;c++)b=new createjs.Text(s_aSymbolWin[7][4-c],"21px "+FONT_GAME,"#ffff00"),b.textAlign="left",b.shadow=new createjs.Shadow("#000",1,1,2),b.x=d,b.y=f,b.textBaseline="alphabetic",g.addChild(b),e[7][c]=b,f+=22;k=new createjs.Text(TEXT_HELP_WILD,"21px "+FONT_GAME,"#ffff00");k.shadow=new createjs.Shadow("#000",2,2,2);k.textAlign="center";k.lineHeight=
22;k.lineWidth=200;k.x=636;k.y=286;g.addChild(k);h=new createjs.Text(TEXT_HELP_BONUS,"21px "+FONT_GAME,"#ffff00");h.shadow=new createjs.Shadow("#000",2,2,2);h.textAlign="center";h.lineHeight=22;h.lineWidth=200;h.x=1012;h.y=294;g.addChild(h);g.visible=!1;s_oStage.addChild(g);var m=this;g.on("pressup",function(){m._onExit()})};this.unload=function(){var c=this;g.off("pressup",function(){c._onExit()});s_oStage.removeChild(g);for(var d=0;d<a.length;d++)g.removeChild(a[d]);for(d=0;d<e.length;d++)g.removeChild(e[d])};
this.show=function(){g.visible=!0};this.hide=function(){g.visible=!1};this.resetHighlightCombo=function(){for(var c=0;c<a.length;c++)for(var d=0;d<a[c].length;d++)a[c][d].color="#ffffff",e[c][d].color="#ffff00",createjs.Tween.removeTweens(e[c][d]),e[c][d].alpha=1};this.highlightCombo=function(a,d){8<a||(e[a-1][NUM_REELS-d].color="#ff0000",this.tweenAlpha(e[a-1][NUM_REELS-d],0))};this.tweenAlpha=function(a,d){var e=this;createjs.Tween.get(a).to({alpha:d},200).call(function(){1===d?e.tweenAlpha(a,0):
e.tweenAlpha(a,1)})};this._onExit=function(){s_oGame.hidePayTable()};this.isVisible=function(){return g.visible};this._init()}
function CMenu(){var a,e,k,h,l,g;this._init=function(){k=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(k);var c=s_oSpriteLibrary.getSprite("but_play_bg");h=new CTextButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-60,c,TEXT_PLAY,FONT_GAME,"#ffffff",32);h.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)a=CANVAS_WIDTH-c.width/2+20,e=c.height/2+20,c=s_oSpriteLibrary.getSprite("audio_icon"),l=new CToggle(CANVAS_WIDTH-c.width/2+20,c.height/
2+20,c),l.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this),null===s_oSoundTrack&&(s_oSoundTrack=createjs.Sound.play("soundtrack",{volume:SOUNDTRACK_VOLUME,loop:-1}));g=new createjs.Shape;g.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(g);createjs.Tween.get(g).to({alpha:0},600).call(function(){g.visible=!1});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.refreshButtonPos=function(c,d){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||l.setPosition(a-c,d+
e)};this.unload=function(){h.unload();h=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)l.unload(),l=null;s_oStage.removeAllChildren();s_oMenu=null};this._onButPlayRelease=function(){this.unload();s_oMain.gotoGame()};this._onAudioToggle=function(){createjs.Sound.setMute(!s_bAudioActive)};s_oMenu=this;this._init()}var s_oMenu=null;
function CMain(a){var e=0,k=0,h=STATE_LOADING,l,g,c;this.initContainer=function(){var a=document.getElementById("canvas");s_oStage=new createjs.Stage(a);createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&s_oStage.enableMouseOver(20);s_iPrevTime=(new Date).getTime();createjs.Ticker.setFPS(30);createjs.Ticker.addEventListener("tick",this._update);navigator.userAgent.match(/Windows Phone/i)&&(DISABLE_SOUND_MOBILE=!0);s_oSpriteLibrary=new CSpriteLibrary;g=new CPreloader};
this.preloaderReady=function(){this._loadImages();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds()};this.soundLoaded=function(){e++;e===k&&(g.unload(),this.gotoMenu())};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&(0<navigator.userAgent.indexOf("Opera")||0<navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=["mp3"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/press_but.ogg",
"press_but"),createjs.Sound.registerSound("./sounds/win.ogg","win"),createjs.Sound.registerSound("./sounds/reels.ogg","reels"),createjs.Sound.registerSound("./sounds/reel_stop.ogg","reel_stop",6),createjs.Sound.registerSound("./sounds/start_reel.ogg","start_reel",6),createjs.Sound.registerSound("./sounds/bonus_item_choosen.ogg","bonus_item_choosen"),createjs.Sound.registerSound("./sounds/press_hold.ogg","press_hold"),createjs.Sound.registerSound("./sounds/soundtrack.ogg","soundtrack"),createjs.Sound.registerSound("./sounds/soundtrack_bonus.ogg",
"soundtrack_bonus"),createjs.Sound.registerSound("./sounds/reveal_prize.ogg","reveal_prize")):(createjs.Sound.alternateExtensions=["ogg"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/press_but.mp3","press_but"),createjs.Sound.registerSound("./sounds/win.mp3","win"),createjs.Sound.registerSound("./sounds/reels.mp3","reels"),createjs.Sound.registerSound("./sounds/reel_stop.mp3","reel_stop",6),createjs.Sound.registerSound("./sounds/start_reel.mp3",
"start_reel",6),createjs.Sound.registerSound("./sounds/bonus_item_choosen.mp3","bonus_item_choosen"),createjs.Sound.registerSound("./sounds/press_hold.mp3","press_hold"),createjs.Sound.registerSound("./sounds/soundtrack.mp3","soundtrack"),createjs.Sound.registerSound("./sounds/soundtrack_bonus.mp3","soundtrack_bonus"),createjs.Sound.registerSound("./sounds/reveal_prize.mp3","reveal_prize")),k+=10)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);
s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("paytable","./sprites/paytable.jpg");s_oSpriteLibrary.addSprite("but_play_bg","./sprites/but_play_bg.png");s_oSpriteLibrary.addSprite("mask_slot","./sprites/mask_slot.png");s_oSpriteLibrary.addSprite("spin_but","./sprites/but_spin_bg.png");s_oSpriteLibrary.addSprite("coin_but","./sprites/but_coin_bg.png");
s_oSpriteLibrary.addSprite("info_but","./sprites/but_info_bg.png");s_oSpriteLibrary.addSprite("bet_but","./sprites/bet_but.png");s_oSpriteLibrary.addSprite("win_frame_anim","./sprites/win_frame_anim.png");s_oSpriteLibrary.addSprite("but_lines_bg","./sprites/but_lines_bg.png");s_oSpriteLibrary.addSprite("but_maxbet_bg","./sprites/but_maxbet_bg.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("hit_area_col","./sprites/hit_area_col.png");s_oSpriteLibrary.addSprite("hold_col",
"./sprites/hold_col.png");s_oSpriteLibrary.addSprite("bonus_bg","./sprites/bonus_bg.jpg");s_oSpriteLibrary.addSprite("star_bonus","./sprites/star_bonus.png");s_oSpriteLibrary.addSprite("bonus_item","./sprites/bonus_item.png");for(var a=1;a<NUM_SYMBOLS+1;a++)s_oSpriteLibrary.addSprite("symbol_"+a,"./sprites/symbol_"+a+".png"),s_oSpriteLibrary.addSprite("symbol_"+a+"_anim","./sprites/symbol_"+a+"_anim.png");for(a=1;a<NUM_PAYLINES+1;a++)s_oSpriteLibrary.addSprite("payline_"+a,"./sprites/payline_"+a+
".png");for(a=0;25>a;a++)s_oSpriteLibrary.addSprite("bonus_item_"+a,"./sprites/bonus_item/bonus_item_"+a+".png");k+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){e++;g.refreshLoader(Math.floor(e/k*100));e===k&&(g.unload(),this.gotoMenu())};this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this.gotoMenu=function(){new CMenu;h=STATE_MENU};this.gotoGame=function(){c=new CGame(l);h=STATE_GAME;$(s_oMain).trigger("game_start")};
this.gotoHelp=function(){new CHelp;h=STATE_HELP};this._update=function(a){var e=(new Date).getTime();s_iTimeElaps=e-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=e;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);h===STATE_GAME&&c.update();s_oStage.update(a)};s_oMain=this;l=a;this.initContainer()}var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oSoundTrack=null;
TEXT_GAMEOVER="GAME OVER";TEXT_CONGRATS="CONGRATULATIONS";TEXT_MONEY="SCORE";TEXT_PLAY="PLAY";TEXT_BET="BET";TEXT_COIN="COIN";TEXT_MAX_BET="MAX BET";TEXT_INFO="INFO";TEXT_LINES="LINES";TEXT_SPIN="SPIN";TEXT_WIN="WIN";TEXT_HOLD="HOLD";TEXT_HELP_WILD="JOLLY SYMBOL CAN REPLACE ANY OTHER SYMBOL TO MAKE UP A COMBO";TEXT_HELP_BONUS="3 OR MORE RIBBON BOW LET YOU PLAY THE BONUS GAME!";
function CInterface(a,e,k){var h,l,g,c,d,f,b,m,t,n,p,u,r,y,w,x,z;this._init=function(a,e,k){var q=s_oSpriteLibrary.getSprite("but_exit");h=CANVAS_WIDTH-q.width/2-20;l=q.height/2+20;b=new CGfxButton(h,l,q,!0);b.addEventListener(ON_MOUSE_UP,this._onExit,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)g=b.getX()-q.width,c=q.height/2+20,p=new CToggle(g,c,s_oSpriteLibrary.getSprite("audio_icon")),p.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);q=s_oSpriteLibrary.getSprite("spin_but");m=new CTextButton(1090+
q.width/2,CANVAS_HEIGHT-q.height/2,q,"",FONT_GAME,"#ffde00",22);m.addEventListener(ON_MOUSE_UP,this._onSpin,this);q=s_oSpriteLibrary.getSprite("info_but");t=new CTextButton(328+q.width/2,CANVAS_HEIGHT-q.height/2,q,TEXT_INFO,FONT_GAME,"#ffffff",30);t.addEventListener(ON_MOUSE_UP,this._onInfo,this);q=s_oSpriteLibrary.getSprite("but_lines_bg");n=new CTextButton(494+q.width/2,CANVAS_HEIGHT-q.height/2,q,TEXT_LINES,FONT_GAME,"#ffffff",30);n.addEventListener(ON_MOUSE_UP,this._onAddLine,this);q=s_oSpriteLibrary.getSprite("coin_but");
u=new CTextButton(680+q.width/2,CANVAS_HEIGHT-q.height/2,q,TEXT_COIN,FONT_GAME,"#ffffff",30);u.addEventListener(ON_MOUSE_UP,this._onBet,this);q=s_oSpriteLibrary.getSprite("but_maxbet_bg");r=new CTextButton(866+q.width/2,CANVAS_HEIGHT-q.height/2,q,TEXT_MAX_BET,FONT_GAME,"#ffffff",30);r.addEventListener(ON_MOUSE_UP,this._onMaxBet,this);w=new createjs.Text(TEXT_MONEY+"\n"+k.toFixed(2),"30px "+FONT_GAME,"#ffde00");w.x=450;w.y=46;w.textBaseline="alphabetic";w.lineHeight=28;w.textAlign="center";s_oStage.addChild(w);
z=new createjs.Text(NUM_PAYLINES,"26px "+FONT_GAME,"#ffffff");z.x=584;z.y=CANVAS_HEIGHT-65;z.shadow=new createjs.Shadow("#000",2,2,2);z.textAlign="center";z.textBaseline="alphabetic";s_oStage.addChild(z);y=new createjs.Text(a.toFixed(2),"26px "+FONT_GAME,"#ffffff");y.x=776;y.y=CANVAS_HEIGHT-65;y.shadow=new createjs.Shadow("#000",2,2,2);y.textAlign="center";y.textBaseline="alphabetic";s_oStage.addChild(y);x=new createjs.Text(TEXT_BET+": "+e.toFixed(2),"26px "+FONT_GAME,"#ffffff");x.x=980;x.y=CANVAS_HEIGHT-
65;x.shadow=new createjs.Shadow("#000",2,2,2);x.textAlign="center";x.textBaseline="alphabetic";s_oStage.addChild(x);q=s_oSpriteLibrary.getSprite("bet_but");d=[];a=new CBetBut(328+q.width/2,276+q.height/2,q,!0);a.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,1);d[0]=a;a=new CBetBut(326+q.width/2,176+q.height/2,q,!0);a.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,2);d[1]=a;a=new CBetBut(326+q.width/2,426+q.height/2,q,!0);a.addEventListenerWithParams(ON_MOUSE_UP,
this._onBetLineClicked,this,3);d[2]=a;a=new CBetBut(326+q.width/2,106+q.height/2,q,!0);a.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,4);d[3]=a;a=new CBetBut(326+q.width/2,495+q.height/2,q,!0);a.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,5);d[4]=a;f=[];for(q=0;q<NUM_PAYLINES;q++)a=new createjs.Bitmap(s_oSpriteLibrary.getSprite("payline_"+(q+1))),a.x=0,a.y=0,a.visible=!1,s_oStage.addChild(a),f[q]=a;this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=
function(){b.unload();b=null;m.unload();m=null;t.unload();t=null;n.unload();n=null;u.unload();u=null;r.unload();r=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)p.unload(),p=null;for(var a=0;a<NUM_PAYLINES;a++)d[a].unload();s_oStage.removeAllChildren();s_oInterface=null};this.refreshButtonPos=function(a,d){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||p.setPosition(g-a,d+c);b.setPosition(h-a,d+l)};this.refreshMoney=function(a){w.text=TEXT_MONEY+"\n"+a.toFixed(2)};this.refreshBet=function(a){y.text=
a.toFixed(2)};this.refreshTotalBet=function(a){x.text=TEXT_BET+": "+a.toFixed(2)};this.refreshNumLines=function(a){z.text=a;for(var b=0;b<NUM_PAYLINES;b++)b<a?(d[b].setOn(),f[b].visible=!0):d[b].setOff();setTimeout(function(){for(var a=0;a<NUM_PAYLINES;a++)f[a].visible=!1},1E3)};this.resetWin=function(){m.changeText("")};this.refreshWinText=function(a){m.changeText(TEXT_WIN+"\n"+a.toFixed(2))};this.showLine=function(a){f[a-1].visible=!0};this.hideLine=function(a){f[a-1].visible=!1};this.hideAllLines=
function(){for(var a=0;a<NUM_PAYLINES;a++)f[a].visible=!1};this.disableBetBut=function(a){for(var b=0;b<NUM_PAYLINES;b++)d[b].disable(a)};this.enableGuiButtons=function(){m.enable();r.enable();u.enable();n.enable();t.enable()};this.enableSpin=function(){m.enable();r.enable()};this.disableSpin=function(){m.disable();r.disable()};this.disableGuiButtons=function(){m.disable();r.disable();u.disable();n.disable();t.disable()};this._onBetLineClicked=function(a){this.refreshNumLines(a);s_oGame.activateLines(a)};
this._onExit=function(){s_oGame.onExit()};this._onSpin=function(){s_oGame.onSpin()};this._onAddLine=function(){s_oGame.addLine()};this._onInfo=function(){s_oGame.onInfoClicked()};this._onBet=function(){s_oGame.changeCoinBet()};this._onMaxBet=function(){s_oGame.onMaxBet()};this._onAudioToggle=function(){createjs.Sound.setMute(!s_bAudioActive)};s_oInterface=this;this._init(a,e,k);return this}var s_oInterface=null;
function CGfxButton(a,e,k,h){var l,g,c,d,f,b,m;this._init=function(a,b,e,h){l=!1;d=[];f=[];m=createBitmap(e);m.x=a;m.y=b;g=e.width;c=e.height;m.regX=e.width/2;m.regY=e.height/2;!1!==h&&s_oStage.addChild(m);this._initListener()};this.unload=function(){m.off("mousedown",this.buttonDown);m.off("pressup",this.buttonRelease);s_oStage.removeChild(m)};this.setVisible=function(a){m.visible=a};this.enable=function(){l=!1;m.filters=[];m.cache(0,0,g,c)};this.disable=function(){l=!0;var a=(new createjs.ColorMatrix).adjustSaturation(-100).adjustBrightness(40);
m.filters=[new createjs.ColorMatrixFilter(a)];m.cache(0,0,g,c)};this._initListener=function(){m.on("mousedown",this.buttonDown);m.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){d[a]=b;f[a]=c};this.addEventListenerWithParams=function(a,c,e,g){d[a]=c;f[a]=e;b=g};this.buttonRelease=function(){l||(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("press_but"),m.scaleX=1,m.scaleY=1,d[ON_MOUSE_UP]&&d[ON_MOUSE_UP].call(f[ON_MOUSE_UP],b))};this.buttonDown=function(){l||
(m.scaleX=.9,m.scaleY=.9,d[ON_MOUSE_DOWN]&&d[ON_MOUSE_DOWN].call(f[ON_MOUSE_DOWN],b))};this.setPosition=function(a,b){m.x=a;m.y=b};this.setX=function(a){m.x=a};this.setY=function(a){m.y=a};this.getButtonImage=function(){return m};this.getX=function(){return m.x};this.getY=function(){return m.y};this.getSprite=function(){return m};this._init(a,e,k,h);return this};