function CBezier(){var a,c,e,d,f,b,g,l,q,n,m,t;this.init=function(p,y,w,x){a=p;c=y;e=w;f=a.x-2*c.x+e.x;b=a.y-2*c.y+e.y;g=2*c.x-2*a.x;l=2*c.y-2*a.y;q=4*(f*f+b*b);n=4*(f*g+b*l);m=g*g+l*l;t=this._length(1);d=Math.floor(t/x);t%x>x/2&&d++;return d};this._speed=function(a){return Math.sqrt(q*a*a+n*a+m)};this._length=function(a){var d=Math.sqrt(m+a*(n+q*a)),g=2*q*a*d+n*(d-Math.sqrt(m)),b=Math.log(n+2*Math.sqrt(q)*Math.sqrt(m));a=Math.log(n+2*q*a+2*Math.sqrt(q)*d);return(2*Math.sqrt(q)*g+(n*n-4*q*m)*(b-a))/
(8*Math.pow(q,1.5))};this.invertL=function(a,d){var g=a,b;do{b=g-(this._length(g)-d)/this._speed(g);if(1E-6>Math.abs(g-b))break;g=b}while(1);return b};this.getAnchorPoint=function(g){if(0<=g&&g<=d){var b=g/d,b=this.invertL(b,b*t);g=(1-b)*(1-b)*a.x+2*(1-b)*b*c.x+b*b*e.x;var f=(1-b)*(1-b)*a.y+2*(1-b)*b*c.y+b*b*e.y,l=new createjs.Point((1-b)*a.x+b*c.x,(1-b)*a.y+b*c.y),b=new createjs.Point((1-b)*c.x+b*e.x,(1-b)*c.y+b*e.y),l=180*Math.atan2(b.y-l.y,b.x-l.x)/Math.PI;return[g,f,l]}return[]}}
function CBall(a,c){var e,d,f,b,g;this._init=function(a,b){e=a;d=0;g=b;var c=s_oSpriteLibrary.getSprite("ball_"+e);BALL_DIAMETER=c.width;BALL_DIAMETER_SQUARE=BALL_DIAMETER*BALL_DIAMETER;BALL_RADIUS=BALL_DIAMETER/2;c=new createjs.SpriteSheet({images:[c],frames:{width:BALL_DIAMETER,height:BALL_DIAMETER,regX:BALL_RADIUS,regY:BALL_RADIUS},animations:{move:[0,49]}});f=createSprite(c,null,BALL_RADIUS,BALL_RADIUS,BALL_DIAMETER,BALL_DIAMETER);f.stop();g.addChild(f)};this.unload=function(){g.removeChild(b);
g.removeChild(f)};this.nextFrame=function(){f.gotoAndStop(50===f.currentFrame+1?0:f.currentFrame+1)};this.prevFrame=function(){f.gotoAndStop(0>f.currentFrame-1?49:f.currentFrame-1)};this.setPos=function(a,b){a>d?this.nextFrame():a<d&&this.prevFrame();d=a;f.x=b[d][0];f.y=b[d][1];f.rotation=b[d][2]-90};this.changePos=function(a,b){f.x=a;f.y=b};this.increasePosWithNumbers=function(a,b){f.x+=a;f.y+=b};this.decreasePos=function(a,b){f.x-=a;f.y-=b};this.increasePos=function(a,b){this.setPos(d+a,b)};this.setContainer=
function(a){f.mask=null;g=a};this.explode=function(){var a={images:[s_oSpriteLibrary.getSprite("explosion")],frames:{width:62,height:62,regX:31,regY:31},animations:{show:[0,19],hide:[20]}},d=this,a=new createjs.SpriteSheet(a,"show");b=new createjs.Sprite(a);b.addEventListener("animationend",function(){d.onExplosionEnd()});g.addChild(b);b.x=f.x;b.y=f.y;b.gotoAndPlay("show");f.visible=!1};this.onExplosionEnd=function(){g.removeChild(b);g.removeChild(f)};this.rollInStage=function(){};this.getFotogram=
function(){return d};this.getSprite=function(){return f};this.getIndex=function(){return e};this.getX=function(){return f.x};this.getY=function(){return f.y};this._init(a,c)}
function CSpriteLibrary(){var a,c,e,d,f,b;this.init=function(g,l,q){e=c=0;d=g;f=l;b=q;a={}};this.addSprite=function(b,d){a.hasOwnProperty(b)||(a[b]={szPath:d,oSprite:new Image},c++)};this.getSprite=function(b){return a.hasOwnProperty(b)?a[b].oSprite:null};this._onSpritesLoaded=function(){f.call(b)};this._onSpriteLoaded=function(){d.call(b);++e===c&&this._onSpritesLoaded()};this.loadSprites=function(){for(var b in a)a[b].oSprite.oSpriteLibrary=this,a[b].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
a[b].oSprite.src=a[b].szPath};this.getNumSprites=function(){return c}}
var CANVAS_WIDTH=1024,CANVAS_HEIGHT=768,FPS_TIME=1E3/24,DISABLE_SOUND_MOBILE=!0,STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,STATE_GAME_ROLL_IN=0,STATE_GAME_BALL_MOVE=1,STATE_GAME_ROLL_OUT=2,STATE_GAME_SHOOTING=3,STATE_GAME_ATTRACT_BALLS=4,STEP_LENGTH=2,BALL_COLORS=5,BALL_ROLLING_IN,BALL_SHOOTED_SPEED=36,COMBO_VALUE,EXTRA_SCORE,BALL_DIAMETER,BALL_RADIUS,BALL_DIAMETER_SQUARE;
function CTweenController(){this.tweenValue=function(a,c,e){return a+e*(c-a)};this.easeLinear=function(a,c,e,d){return e*a/d+c};this.easeInCubic=function(a,c,e,d){d=(a/=d)*a*a;return c+e*d};this.easeBackInQuart=function(a,c,e,d){d=(a/=d)*a;return c+e*(2*d*d+2*d*a+-3*d)};this.easeInBack=function(a,c,e,d){return e*(a/=d)*a*(2.70158*a-1.70158)+c};this.easeOutCubic=function(a,c,e,d){return e*((a=a/d-1)*a*a+1)+c}}
function CToggle(a,c,e){var d,f,b;this._init=function(a,c,e){d=[];f=[];var n=new createjs.SpriteSheet({images:[e],frames:{width:e.width/2,height:e.height,regX:e.width/2/2,regY:e.height/2},animations:{on:[0,1],off:[1,2]}});b=s_bAudioActive?createSprite(n,"on",e.width/2/2,e.height/2,e.width/2,e.height):createSprite(n,"off",e.width/2/2,e.height/2,e.width/2,e.height);b.x=a;b.y=c;b.stop();s_oStage.addChild(b);this._initListener()};this.unload=function(){b.off("mousedown",this.buttonDown);b.off("pressup",
this.buttonRelease);s_oStage.removeChild(b)};this._initListener=function(){b.on("mousedown",this.buttonDown);b.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,e){d[a]=b;f[a]=e};this.buttonRelease=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("press_but");b.scaleX=1;b.scaleY=1;(s_bAudioActive=!s_bAudioActive)?b.gotoAndStop("on"):b.gotoAndStop("off");d[ON_MOUSE_UP]&&d[ON_MOUSE_UP].call(f[ON_MOUSE_UP])};this.buttonDown=function(){b.scaleX=.9;b.scaleY=
.9;d[ON_MOUSE_DOWN]&&d[ON_MOUSE_DOWN].call(f[ON_MOUSE_DOWN])};this._init(a,c,e)}
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,4))})(navigator.userAgent||
navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}$(window).ready(function(){sizeHandler()});window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a=CANVAS_WIDTH,c=CANVAS_HEIGHT,e,d;!0===inIframe()&&"ios"==getMobileOperatingSystem()?top.location.href=document.location.href:(e=window.innerWidth,d=window.innerHeight,multiplier=s_iScaleFactor=Math.min(d/c,e/a),a*=multiplier,c*=multiplier,$("#canvas").css("width",a+"px"),$("#canvas").css("height",c+"px"),$("#canvas").css("left",e/2-a/2+"px"))}}
function getMobileOperatingSystem(){var a=navigator.userAgent||navigator.vendor||window.opera;return a.match(/iPad/i)||a.match(/iPhone/i)||a.match(/iPod/i)?"ios":a.match(/Android/i)?"android":"unknown"}function inIframe(){try{return window.self!==window.top}catch(a){return!0}}function randomFloatBetween(a,c,e){"undefined"===typeof e&&(e=2);return parseFloat(Math.min(a+Math.random()*(c-a),c).toFixed(e))}
function shuffle(a){for(var c=a.length,e,d;0!==c;)d=Math.floor(Math.random()*c),--c,e=a[c],a[c]=a[d],a[d]=e;return a}function createBitmap(a,c,e){var d=new createjs.Bitmap(a),f=new createjs.Shape;c&&e?f.graphics.beginFill("#fff").drawRect(0,0,c,e):f.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);d.hitArea=f;return d}
function createSprite(a,c,e,d,f,b){a=null!==c?new createjs.Sprite(a,c):new createjs.Sprite(a);c=new createjs.Shape;c.graphics.beginFill("#000000").drawRect(-e,-d,f,b);a.hitArea=c;return a}function formatTime(a){a/=1E3;var c=Math.floor(a/60);a=parseFloat(a-60*c).toFixed(1);var e="",e=10>c?e+("0"+c+":"):e+(c+":");return e=10>a?e+("0"+a):e+a}function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3===a.nodeType&&(a=a.parentNode);var c=document.createEvent("MouseEvents");c.initEvent("click",!0,!0);a.dispatchEvent(c)}}};
function CTextButton(a,c,e,d,f,b,g){var l,q,n,m,t,p,y,w,x;this._init=function(a,b,d,e,c,g,f){l=!1;m=[];t=[];x=createBitmap(d);q=d.width;n=d.height;var A=Math.ceil(f/20);y=new createjs.Text(e,"bold "+f+"px "+c,"#000000");y.textAlign="center";var v=y.getBounds();y.x=d.width/2+A;y.y=(d.height-v.height)/2+A;w=new createjs.Text(e,"bold "+f+"px "+c,g);w.textAlign="center";v=w.getBounds();w.x=d.width/2;w.y=(d.height-v.height)/2;p=new createjs.Container;p.x=a;p.y=b;p.regX=d.width/2;p.regY=d.height/2;p.addChild(x,
y,w);s_oStage.addChild(p);this._initListener()};this.unload=function(){p.off("mousedown");p.off("pressup");s_oStage.removeChild(p)};this.setVisible=function(a){p.visible=a};this.enable=function(){l=!1;x.filters=[];x.cache(0,0,q,n)};this.disable=function(){l=!0;var a=(new createjs.ColorMatrix).adjustSaturation(-100).adjustBrightness(40);x.filters=[new createjs.ColorMatrixFilter(a)];x.cache(0,0,q,n)};this._initListener=function(){oParent=this;p.on("mousedown",this.buttonDown);p.on("pressup",this.buttonRelease)};
this.addEventListener=function(a,b,d){m[a]=b;t[a]=d};this.buttonRelease=function(){l||(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("press_but"),p.scaleX=1,p.scaleY=1,m[ON_MOUSE_UP]&&m[ON_MOUSE_UP].call(t[ON_MOUSE_UP]))};this.buttonDown=function(){l||(p.scaleX=.9,p.scaleY=.9,m[ON_MOUSE_DOWN]&&m[ON_MOUSE_DOWN].call(t[ON_MOUSE_DOWN]))};this.setPosition=function(a,b){p.x=a;p.y=b};this.changeText=function(a){w.text=a;y.text=a};this.setX=function(a){p.x=a};this.setY=function(a){p.y=a};
this.getButtonImage=function(){return p};this.getX=function(){return p.x};this.getY=function(){return p.y};this._init(a,c,e,d,f,b,g);return this}
function CPreloader(){var a;this._init=function(){this._onAllPreloaderImagesLoaded()};this._onPreloaderImagesLoaded=function(){};this._onAllPreloaderImagesLoaded=function(){a=new createjs.Text("","bold 22px Arial center","#ffffff");a.x=CANVAS_WIDTH/2-40;a.y=CANVAS_HEIGHT/2;s_oStage.addChild(a)};this.unload=function(){s_oStage.removeChild(a)};this.refreshLoader=function(c){a.text=c+"%"};this._init()}
function CNextLevel(){var a,c,e,d,f,b;this._init=function(){a=createBitmap(s_oSpriteLibrary.getSprite("msg_box"));a.x=0;a.y=0;e=new createjs.Text("","bold 58px Chewy","#000");e.x=CANVAS_WIDTH/2+32;e.y=CANVAS_HEIGHT/2-138;e.textAlign="center";c=new createjs.Text("","bold 58px Chewy","#ffffff");c.x=CANVAS_WIDTH/2+30;c.y=CANVAS_HEIGHT/2-140;c.textAlign="center";f=new createjs.Text("","bold 44px Chewy","#000");f.x=CANVAS_WIDTH/2+32;f.y=CANVAS_HEIGHT/2+40;f.textAlign="center";d=new createjs.Text("","bold 44px Chewy",
"#ffffff");d.x=CANVAS_WIDTH/2+30;d.y=CANVAS_HEIGHT/2+38;d.textAlign="center";b=new createjs.Container;b.alpha=0;b.visible=!1;b.addChild(a,e,c,f,d);s_oStage.addChild(b)};this.show=function(a,l){e.text=TEXT_LEVEL+" "+a;c.text=TEXT_LEVEL+" "+a;f.text=TEXT_SCORE+" "+l;d.text=TEXT_SCORE+" "+l;b.visible=!0;var q=this;createjs.Tween.get(b).to({alpha:1},500).call(function(){q._initListener()})};this._initListener=function(){b.on("mousedown",this._onExit)};this._onExit=function(){b.off("mousedown");b.alpha=
0;b.visible=!1;s_oGame.nextLevel()};this._init()}
function CMenu(){var a,c,e,d;this._init=function(){a=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(a);var f=s_oSpriteLibrary.getSprite("but_bg");c=new CTextButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-100,f,TEXT_PLAY,"Chewy","#ffffff",40);c.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)f=s_oSpriteLibrary.getSprite("audio_icon"),e=new CToggle(CANVAS_WIDTH-f.width/2+20,f.height/2+20,f),e.addEventListener(ON_MOUSE_UP,this._onAudioToggle,
this),s_oSoundtrack=createjs.Sound.play("soundtrack",{loop:100});d=new createjs.Shape;d.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(d);createjs.Tween.get(d).to({alpha:0},1E3).call(function(){d.visible=!1})};this.unload=function(){c.unload();c=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)e.unload(),e=null;s_oStage.removeChild(a);a=null;s_oStage.removeChild(d);d=null};this._onButPlayRelease=function(){this.unload();s_oMain.gotoGame()};this._onAudioToggle=
function(){createjs.Sound.setMute(!s_bAudioActive)};this._init()}
function CMain(a){var c=0,e=0,d=STATE_LOADING,f,b,g;this.initContainer=function(){var a=document.getElementById("canvas");s_oStage=new createjs.Stage(a);createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&s_oStage.enableMouseOver(20);s_oLevelSettings=new CLevelSettings;s_iPrevTime=(new Date).getTime();createjs.Ticker.setFPS(35);createjs.Ticker.on("tick",this._update);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();s_oSpriteLibrary=new CSpriteLibrary;b=new CPreloader;
this._loadImages()};this.soundLoaded=function(){c++;c===e&&(b.unload(),this.gotoMenu())};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&(0<navigator.userAgent.indexOf("Opera")||0<navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=["mp3"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/press_but.ogg","press_but"),createjs.Sound.registerSound("./sounds/win.ogg","win"),createjs.Sound.registerSound("./sounds/game_over.ogg",
"game_over"),createjs.Sound.registerSound("./sounds/combo.ogg","combo"),createjs.Sound.registerSound("./sounds/shot.ogg","shot"),createjs.Sound.registerSound("./sounds/soundtrack.ogg","soundtrack")):(createjs.Sound.alternateExtensions=["ogg"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/press_but.mp3","press_but"),createjs.Sound.registerSound("./sounds/win.mp3","win"),createjs.Sound.registerSound("./sounds/game_over.mp3",
"game_over"),createjs.Sound.registerSound("./sounds/combo.mp3","combo"),createjs.Sound.registerSound("./sounds/shot.mp3","shot"),createjs.Sound.registerSound("./sounds/soundtrack.mp3","soundtrack")),e+=6)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_bg","./sprites/but_play_bg.png");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("audio_icon",
"./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("hero","./sprites/hero.png");s_oSpriteLibrary.addSprite("hit_area","./sprites/hit_area.png");s_oSpriteLibrary.addSprite("explosion","./sprites/explosion.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("extra_score","./sprites/extra_score.png");s_oSpriteLibrary.addSprite("end_path","./sprites/end_path.png");for(var a=0;a<BALL_COLORS;a++)s_oSpriteLibrary.addSprite("ball_"+a,"./sprites/ball_"+a+".png");
for(a=0;a<s_oLevelSettings.getNumLevels();a++)s_oSpriteLibrary.addSprite("bg_game_"+(a+1),"./sprites/bg_game_"+(a+1)+".jpg");e+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){c++;b.refreshLoader(Math.floor(c/e*100));c===e&&(b.unload(),this.gotoMenu())};this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this.gotoMenu=function(){new CMenu;d=STATE_MENU};this.gotoGame=function(){g=new CGame(f);d=STATE_GAME;
$(s_oMain).trigger("game_start")};this.gotoHelp=function(){new CHelp;d=STATE_HELP};this._update=function(a){var b=(new Date).getTime();s_iTimeElaps=b-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=b;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);d===STATE_GAME&&g.update();void 0!==s_oStage&&s_oStage.update(a)};s_oMain=this;f=a;this.initContainer()}
var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oSoundtrack,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oLevelSettings;
function CLevelSettings(){var a,c,e,d,f;this._init=function(){this._initBallSpeed();this._initBallNumber();this._initBallColors();this._initHeroPos();this._initCurveLevel()};this._initBallSpeed=function(){a=[50,40,30]};this._initBallNumber=function(){c=[60,80,100]};this._initBallColors=function(){e=[];e[0]=BALL_COLORS-1;e[1]=BALL_COLORS;e[2]=BALL_COLORS};this._initHeroPos=function(){d=[];d[0]=new createjs.Point(500,400);d[1]=new createjs.Point(500,400);d[2]=new createjs.Point(500,400)};this._initCurveLevel=
function(){f=[[[-102,262],[-42,226],[120,154],[168,136],[215,120],[264,104],[313,92],[363,83],[414,76],[464,71],[516,68],[566,66],[617,66],[668,71],[718,84],[765,100],[810,125],[851,154],[891,188],[923,226],[950,269],[967,317],[969,368],[948,413],[902,433],[855,417],[825,375],[805,329],[781,284],[755,240],[719,204],[676,178],[628,158],[578,151],[528,151],[477,159],[428,169],[378,179],[328,192],[280,208],[233,227],[187,250],[145,278],[105,309],[75,350],[57,397],[51,447],[56,498],[68,548],[91,593],
[122,634],[163,663],[210,681],[260,690],[311,694],[359,697],[419,698],[479,698],[529,696],[579,692],[632,685],[687,674],[737,661],[787,643],[827,625],[872,598],[897,565],[897,523],[867,495],[829,477],[789,477],[749,492],[717,514],[679,541],[634,571],[592,592],[552,605],[512,613],[469,615],[422,612],[379,604],[339,593],[296,576],[254,551],[224,519],[205,476]],[[378,-39],[498,3],[618,51],[670,74],[720,97],[768,122],[810,147],[853,175],[890,204],[935,245],[971,290],[992,328],[999,369],[990,410],[967,
448],[936,483],[898,515],[856,545],[806,575],[763,597],[718,618],[663,640],[615,656],[558,673],[505,686],[440,697],[373,704],[298,701],[240,691],[189,671],[142,636],[105,591],[83,544],[68,497],[60,444],[59,382],[65,329],[76,282],[93,234],[119,187],[149,148],[184,120],[224,100],[272,92],[319,95],[366,101],[409,110],[482,128],[552,149],[609,169],[707,212],[776,250],[840,297],[872,347],[865,386],[842,423],[802,458],[754,491],[709,515],[606,555],[529,577],[456,591],[379,593],[339,585],[299,557],[276,
517],[264,475],[259,422],[264,365],[273,320],[291,272],[318,235],[348,217],[383,216],[428,223],[487,240],[555,265],[632,298]],[[-49,228],[22,181],[81,150],[181,113],[253,95],[343,78],[421,71],[476,71],[542,72],[593,76],[651,85],[703,97],[758,114],[811,136],[863,166],[903,200],[933,237],[954,277],[970,325],[978,375],[962,472],[900,550],[845,586],[803,611],[758,631],[710,646],[664,657],[619,665],[567,670],[519,672],[467,671],[410,667],[363,660],[315,651],[265,637],[218,620],[175,598],[122,561],[82,
513],[58,468],[47,418],[46,370],[59,330],[96,304],[137,310],[164,346],[160,389],[169,431],[193,476],[226,509],[263,535],[323,560],[401,577],[473,584],[546,584],[616,579],[689,564],[744,540],[796,503],[829,461],[849,413],[854,371],[839,331],[802,311],[759,318],[741,358],[736,401],[714,439],[677,468],[634,486],[587,497],[540,501],[475,501],[420,493],[372,480],[327,456],[293,423],[274,378],[272,338]]]};this.getBallSpeedForLevel=function(b){return a[b-1]};this.getBallNumberForLevel=function(a){return c[a-
1]};this.getBallColorsForLevel=function(a){return e[a-1]};this.getHeroPosForLevel=function(a){return d[a-1]};this.getCurveForLevel=function(a){return f[a-1]};this.getNumLevels=function(){return f.length};this._init()}TEXT_GAMEOVER="GAME OVER";TEXT_CONGRATS="CONGRATULATIONS";TEXT_PLAY="PLAY";TEXT_SCORE="SCORE";TEXT_LEVEL="LEVEL";TEXT_FINAL_SCORE="FINAL SCORE";
function CInterface(){var a,c,e,d,f,b;this._init=function(){a=new createjs.Text(TEXT_SCORE+" 0","bold 38px Chewy","#fff");a.x=10;a.y=10;a.textAlign="left";s_oStage.addChild(a);var g=this;e=createBitmap(s_oSpriteLibrary.getSprite("hit_area"));s_oStage.addChild(e);e.on("pressup",function(a){g._onTapScreen(a.stageX,a.stageY)});var l=s_oSpriteLibrary.getSprite("but_exit");c=new CGfxButton(CANVAS_WIDTH-l.width/2-10,l.height/2+10,l,!0);c.addEventListener(ON_MOUSE_UP,this._onExit,this);if(!1===DISABLE_SOUND_MOBILE||
!1===s_bMobile)d=new CToggle(c.getX()-l.width,l.height/2+10,s_oSpriteLibrary.getSprite("audio_icon")),d.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);b=new CNextLevel;f=new CEndPanel(s_oSpriteLibrary.getSprite("msg_box"))};this.unload=function(){c.unload();c=null;!1===DISABLE_SOUND_MOBILE&&(d.unload(),d=null);s_oStage.removeAllChildren()};this._onTapScreen=function(a,b){s_oGame.onShot(a,b)};this.gameOver=function(a){f.show(a,!1)};this.win=function(a){f.show(a,!0)};this.nextLevel=function(a,
d){b.show(a,d)};this.refreshScore=function(b){a.text=TEXT_SCORE+" "+b};this._onExit=function(){s_oGame.onExit()};this._onAudioToggle=function(){createjs.Sound.setMute(!s_bAudioActive)};s_oInterface=this;this._init();return this}var s_oInterface;
function CHero(){var a=!1,c,e,d,f,b,g,l,q,n,m;this._init=function(){var a=s_oSpriteLibrary.getSprite("hero");m=new createjs.Container;m.regX=a.width/2;m.regY=a.height/2;s_oStage.addChild(m);l=createBitmap(a);l.x=0;l.y=0;m.addChild(l);q=new createjs.Shape;q.graphics.beginFill("rgba(255,0,0,0.01)").drawCircle(40,110,16);m.addChild(q);n=new createjs.Shape;n.graphics.beginFill("rgba(255,0,0,0.01)").drawCircle(120,60,6);m.addChild(n);c=a.width;e=a.height};this.reset=function(a,e){d=e;void 0!==b&&null!==
b&&b.unload();void 0!==g&&null!==g&&g.unload();m.x=a.x;m.y=a.y;f=[];for(var c=0;c<d;c++)f[c]=!0};this.unload=function(){};this.rotate=function(a){m.rotation=a};this.start=function(){b=this._getRandomBall();b.changePos(c/2-25,e/2+20);b.getSprite().mask=q;g=this._getRandomBall();g.changePos(120,e/2-12);g.getSprite().mask=n;var a=this;createjs.Tween.get(b.getSprite()).to({y:b.getY()+25},300).call(function(){a._onBallReady()});createjs.Tween.get(g.getSprite()).to({y:g.getY()+16},300)};this._getRandomBall=
function(){var a;if(!0===this._checkIfAllColorsNotAvailable())return null;do{var b=Math.floor(Math.random()*d),e=!1;if(!0===f[b]){a=new CBall(b,m);break}}while(!1===e);return a};this._checkIfAllColorsNotAvailable=function(){for(var a=!0,b=0;b<f.length;b++)!0===f[b]&&(a=!1);return a};this._nextShoot=function(){null!==b&&b.unload();b=g;b.changePos(c/2-25,e/2+20);b.getSprite().mask=q;g=this._getRandomBall();g.changePos(120,e/2-12);g.getSprite().mask=n;var a=this;createjs.Tween.get(b.getSprite()).to({y:b.getY()+
25},300).call(function(){a._onBallReady()});createjs.Tween.get(g.getSprite()).to({y:g.getY()+16},300)};this.colorCleared=function(a){f[a]=!1;b.getIndex()===a&&(b.unload(),b=this._getRandomBall(),null!==b&&(b.changePos(c/2-25,e/2+45),b.getSprite().mask=q));g.getIndex()===a&&(g.unload(),g=this._getRandomBall(),null!==g&&(g.changePos(120,e/2+4),g.getSprite().mask=n))};this._onBallReady=function(){a=!0};this.getCurrentBall=function(){a=!1;var d=b;this._nextShoot();return d};this.getX=function(){return m.x};
this.getY=function(){return m.y};this.getRotation=function(){return m.rotation};this.canShoot=function(){return a};this._init()}
function CGfxButton(a,c,e){var d,f,b=[],g;this._init=function(a,b,e){d=[];f=[];g=createBitmap(e);g.x=a;g.y=b;g.regX=e.width/2;g.regY=e.height/2;s_oStage.addChild(g);this._initListener()};this.unload=function(){g.off("mousedown",this.buttonDown);g.off("pressup",this.buttonRelease);s_oStage.removeChild(g)};this.setVisible=function(a){g.visible=a};this._initListener=function(){g.on("mousedown",this.buttonDown);g.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,e){d[a]=b;f[a]=e};this.addEventListenerWithParams=
function(a,e,c,g){d[a]=e;f[a]=c;b=g};this.buttonRelease=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("press_but");g.scaleX=1;g.scaleY=1;d[ON_MOUSE_UP]&&d[ON_MOUSE_UP].call(f[ON_MOUSE_UP],b)};this.buttonDown=function(){g.scaleX=.9;g.scaleY=.9;d[ON_MOUSE_DOWN]&&d[ON_MOUSE_DOWN].call(f[ON_MOUSE_DOWN],b)};this.setPosition=function(a,b){g.x=a;g.y=b};this.setX=function(a){g.x=a};this.setY=function(a){g.y=a};this.getButtonImage=function(){return g};this.getX=function(){return g.x};
this.getY=function(){return g.y};this._init(a,c,e);return this}
function CGame(a){var c=!1,e,d,f,b=1,g,l,q,n,m=-1,t,p,y,w,x,D,h,k,u,r,z=null,H=null,A=null,v,E,B,F,C,I,G;this._init=function(){s_oBezier=new CBezier;G=new createjs.Container;E=createBitmap(s_oSpriteLibrary.getSprite("bg_game_"+b));G.addChild(E);s_oStage.addChild(G);v=new CHero;n=0;C=new createjs.Container;F=new createjs.Container;I=new createjs.Container;this.reset();s_oStage.addChild(C);s_oStage.addChild(F);s_oStage.addChild(I);B=new CInterface;if(!1===s_bMobile){var a=this;s_oStage.addEventListener("stagemousemove",
function(b){a._onMouseMove(b.stageX,b.stageY)})}c=!0};this.unload=function(){c=!1;clearInterval(y);createjs.Sound.stop();B.unload();v.unload();s_oStage.removeAllChildren()};this.reset=function(){e=!0;f=d=!1;q=s_oLevelSettings.getBallSpeedForLevel(b);l=s_oLevelSettings.getBallNumberForLevel(b);x=s_oLevelSettings.getBallColorsForLevel(b);BALL_ROLLING_IN=Math.floor(.33*l);t=0;g=p=1;D=0;v.reset(s_oLevelSettings.getHeroPosForLevel(b),x);null!==H&&(C.removeChild(H),C.removeChild(A));this._initCurve();this._initBall()};
this._normalize=function(a){var b=this._length(a);return 0<b?{x:a.x/b,y:a.y/b}:a};this._length=function(a){return Math.sqrt(a.x*a.x+a.y*a.y)};this._dotProductV2=function(a,b){return a.x*b.x+a.y*b.y};this._angleBetweenVectors=function(a,b){var d=Math.acos(this._dotProductV2(a,b)/(this._length(a)*this._length(b)));return!0===isNaN(d)?0:d};this._rot90CW=function(a){return{x:a.y,y:-a.x}};this._rot90CCW=function(a){return{x:-a.y,y:a.x}};this._rotateVector2D=function(a,b){var d=b.x*Math.cos(a)+b.y*Math.sin(a),
e=b.x*-Math.sin(a)+b.y*Math.cos(a);return{x:d,y:e}};this._initCurve=function(){var a,d;a=s_oLevelSettings.getCurveForLevel(b);var e=new createjs.Graphics;k=[];for(d=0;d<a.length-2;++d)for(var c=0===d?new createjs.Point(a[0][0],a[0][1]):new createjs.Point((a[d][0]+a[d+1][0])/2,(a[d][1]+a[d+1][1])/2),f=new createjs.Point(a[d+1][0],a[d+1][1]),g=d<=a.length-4?new createjs.Point((a[d+1][0]+a[d+2][0])/2,(a[d+1][1]+a[d+2][1])/2):new createjs.Point(a[d+2][0],a[d+2][1]),c=s_oBezier.init(c,f,g,STEP_LENGTH),
f=1;f<=c;++f)g=s_oBezier.getAnchorPoint(f),k.push(g);e.setStrokeStyle(4);e.beginStroke("#00a29b");e.beginFill("#221910");c={x:k[1][0]-k[0][0],y:k[1][1]-k[0][1]};c=this._normalize(c);c=this._rot90CW(c);c.x*=16;c.y*=16;c.x+=k[0][0];c.y+=k[0][1];a=c.x;d=c.y;e.moveTo(c.x,c.y);for(f=1;f<k.length-1;f++)c={x:k[f+1][0]-k[f][0],y:k[f+1][1]-k[f][1]},c=this._normalize(c),c=this._rot90CW(c),c.x*=16,c.y*=16,c.x+=k[f][0],c.y+=k[f][1],e.lineTo(c.x,c.y);e.lineTo(c.x,c.y);c={x:k[k.length-1][0]-k[k.length-2][0],y:k[k.length-
1][1]-k[k.length-2][1]};c=this._normalize(c);c=this._rot90CCW(c);c.x*=16;c.y*=16;c.x+=k[k.length-1][0];c.y+=k[k.length-1][1];e.lineTo(c.x,c.y);for(f=k.length-2;1<f;f--)c={x:k[f][0]-k[f-1][0],y:k[f][1]-k[f-1][1]},c=this._normalize(c),c=this._rot90CCW(c),c.x*=16,c.y*=16,c.x+=k[f][0],c.y+=k[f][1],e.lineTo(c.x,c.y);e.lineTo(a,d);e.endFill();H=new createjs.Shape(e);C.addChild(H);e=k.length;a=s_oSpriteLibrary.getSprite("end_path");A=createBitmap(a);A.x=k[e-9][0];A.y=k[e-9][1];A.regX=a.width/2;A.regY=a.height/
2;C.addChild(A);C.cache(0,0,CANVAS_WIDTH,CANVAS_HEIGHT)};this._initBall=function(){h=[];var a=this.getRandomBall();h.unshift(a);a.setPos(16,k);m=STATE_GAME_ROLL_IN};this.getRandomBall=function(){l--;var a=Math.floor(Math.random()*x);return new CBall(a,F)};this._pushNextBall=function(a,b){var c=[];c.push(h[a]);for(var l=a;l<h.length-1;++l)if(16>=h[l+1].getFotogram()-h[l].getFotogram())16>h[l+1].getFotogram()-h[l].getFotogram()&&h[l+1].setPos(h[l].getFotogram()+16,k),c.push(h[l+1]);else break;for(l=
0;l<c.length;++l)c[l].increasePos(b,k);if(h[h.length-1].getFotogram()>=k.length-17){e=!1;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundtrack.pause(),createjs.Sound.play("game_over").addEventListener("complete",this._onSoundGameOverComplete);s_oStage.removeEventListener("stagemousemove");f=d=!1;g=1;h[h.length-1].unload();h.splice(h.length-1,1);m=STATE_GAME_ROLL_OUT}};this.onIntroduceBall=function(){if(0!==h.length&&(s_oGame._pushNextBall(0,1),32===h[0].getFotogram()&&0!==l)){var a=s_oGame.getRandomBall();
h.unshift(a);a.setPos(16,k)}};this.shoot=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("shot");var a=(v.getRotation()+90)*Math.PI/180,b=v.getCurrentBall();b.changePos(v.getX()+60*Math.cos(a),v.getY()+60*Math.sin(a));F.addChild(b.getSprite());b.setContainer(F);u.push([b,a]);m=STATE_GAME_SHOOTING};this._checkCollision=function(a){a=a[0];for(var b=0;b<h.length;++b)if((h[b].getX()-a.getX())*(h[b].getX()-a.getX())+(h[b].getY()-a.getY())*(h[b].getY()-a.getY())<=BALL_DIAMETER_SQUARE)return b;
return-1};this._insertBall=function(a,b,c){var e;"next"===c?(e=h[b].getFotogram()+16,h[b+1]&&32>h[b+1].getFotogram()-h[b].getFotogram()&&(r.push([a,h[b+1]]),d=!0)):h[b-1]&&32>h[b].getFotogram()-h[b-1].getFotogram()?(e=h[b-1].getFotogram()+16,r.push([a,h[b]]),d=!0):e=h[b].getFotogram()-16;b=k[e][0];c=k[e][1];var f=this;createjs.Tween.get(a.getSprite()).to({x:b,y:c},200).call(function(){f.motionFinished(a,e)})};this.motionFinished=function(a,b){for(var c,d=0;d<h.length;++d){if(h[d].getFotogram()>b){c=
d;break}d===h.length-1&&(c=d+1)}r.splice(r.indexOf(a),1);a.setPos(b,k);h.splice(c,0,a);h[c-1]&&h[c-1].getIndex()===h[c].getIndex()&&17<h[c].getFotogram()-h[c-1].getFotogram()&&this._addToBallAttracted(h[c]);h[c+1]&&h[c+1].getIndex()===h[c].getIndex()&&17<h[c+1].getFotogram()-h[c].getFotogram()&&this._addToBallAttracted(h[c+1]);this._clearCheck(c,!0)};this._addToBallAttracted=function(a){null===z&&(z=[]);z.push(a);setTimeout(function(){f=!0},400)};this._clearCheck=function(a,b){var c=[];c.push(h[a]);
for(var d=h[a].getIndex(),e=a+1;h[e];)if(h[e].getIndex()===d)if(17>=h[e].getFotogram()-h[e-1].getFotogram())c.push(h[e]),++e;else if(b)break;else c.push(h[e]),++e;else break;for(e=a-1;h[e];)if(h[e].getIndex()===d)if(17>=h[e+1].getFotogram()-h[e].getFotogram())c.push(h[e]),--e;else if(b)break;else c.push(h[e]),--e;else break;++e;2<c.length&&b&&this._clearBall(e,c);return c.length};this._attract=function(){if(0!==z.length)for(var a=0;a<z.length;++a){var b=h.indexOf(z[a]);if(-1!==b&&h[b-1])if(z[a].getIndex()===
h[b-1].getIndex()){var c=19<z[a].getFotogram()-h[b-1].getFotogram()?3:z[a].getFotogram()-h[b-1].getFotogram()-16;this._pushNextBall(b,-c);16>=z[a].getFotogram()-h[b-1].getFotogram()&&(g++,z.splice(a,1),this._clearCheck(b-1,!0),0===z.length&&(f=!1,g=1))}else z.splice(a,1),t>p&&(p=t),t=0}else f=!1,g=1};this._checkPushCollision=function(){if(0!==r.length)for(var a=0;a<r.length;++a){for(var b=(r[a][0].getX()-r[a][1].getX())*(r[a][0].getX()-r[a][1].getX())+(r[a][0].getY()-r[a][1].getY())*(r[a][0].getY()-
r[a][1].getY()),b=b<BALL_DIAMETER_SQUARE?!0:!1,c=0;b;)++c,b=(r[a][0].getX()-k[r[a][1].getFotogram()+c][0])*(r[a][0].getX()-k[r[a][1].getFotogram()+c][0])+(r[a][0].getY()-k[r[a][1].getFotogram()+c][1])*(r[a][0].getY()-k[r[a][1].getFotogram()+c][1]),b=b<BALL_DIAMETER_SQUARE?!0:!1;b=h.indexOf(r[a][1]);-1!==b&&this._pushNextBall(b,c)}else d=!1};this._clearBall=function(a,b){++t;!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("combo");for(var c=0,d=0;d<b.length;++d)b[d].explode(),c+=COMBO_VALUE;
c*=g;n+=c;B.refreshScore(n);h.length===b.length&&(e=!1,w=h[h.length-1].getFotogram(),setTimeout(this._gamePass,600),!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)&&(s_oSoundtrack.pause(),createjs.Sound.play("win").addEventListener("complete",this._onSoundGameOverComplete));h.splice(a,b.length);0===l&&this._checkColor(b[0].getIndex());h[a-1]&&h[a]&&h[a-1].getIndex()===h[a].getIndex()?(3>this._clearCheck(a,!1)&&(t>p&&(p=t),t=0),this._addToBallAttracted(h[a])):(t>p&&(p=t),t=0)};this._gamePass=function(){y=
setInterval(s_oGame._extraScore,q)};this._extraScore=function(){w+16<k.length-17?(w+=16,new CExtraScore(k[w][0],k[w][1],I),n+=EXTRA_SCORE,B.refreshScore(n)):(clearInterval(y),s_oStage.removeEventListener("stagemousemove"),e=!1,b++,b>s_oLevelSettings.getNumLevels()?B.win(n):B.nextLevel(b,n))};this._checkColor=function(a){for(var b=0;b<h.length;++b)if(h[b].getIndex()===a)return;for(b=0;b<u.length;++b)if(u[b].getIndex()===a)return;v.colorCleared(a)};this.nextLevel=function(){G.removeChild(E);E=createBitmap(s_oSpriteLibrary.getSprite("bg_game_"+
b));G.addChild(E);this.reset();c=!0};this.onShot=function(a,b){if(e&&v.canShoot()){if(s_bMobile){var c=a-v.getX(),d=b-v.getY(),c=Math.atan2(d,c);v.rotate(180*c/Math.PI-90)}this.shoot()}};this._onMouseMove=function(a,b){var c=a-v.getX(),d=b-v.getY(),c=Math.atan2(d,c);v.rotate(180*c/Math.PI-90)};this.onExit=function(){createjs.Sound.stop();this.unload();s_oMain.gotoMenu();$(s_oMain).trigger("restart")};this._onSoundGameOverComplete=function(){s_oSoundtrack.resume()};this._updateMove=function(){D+=s_iTimeElaps;
D>q&&(D=0,this.onIntroduceBall())};this._updateRollOut=function(){for(var a=h.length-1;0<=a;--a)h[a].getFotogram()>k.length-17?(h[a].unload(),h.splice(a,1),0===h.length&&(m=-1,B.gameOver(n))):h[a].increasePos(8,k)};this._updateRollIn=function(){if(h.length<BALL_ROLLING_IN){for(var a=0;a<h.length;++a)h[a].increasePos(4,k);32===h[0].getFotogram()&&(a=this.getRandomBall(),h.unshift(a),a.setPos(16,k))}else m=-1,u=[],r=[],v.start(),m=STATE_GAME_BALL_MOVE};this._updateShooting=function(){if(0!==u.length)for(var a=
0;a<u.length;++a)if(0<u[a][0].getX()&&u[a][0].getX()<CANVAS_WIDTH&&0<u[a][0].getY()&&u[a][0].getY()<CANVAS_HEIGHT){var b=this._checkCollision(u[a]);if(-1===b)u[a][0].increasePosWithNumbers(Math.cos(u[a][1])*BALL_SHOOTED_SPEED,Math.sin(u[a][1])*BALL_SHOOTED_SPEED);else{var c=u[a][0],d=u[a][1],e=Math.sqrt((h[b].getX()-c.getX())*(h[b].getX()-c.getX())+(h[b].getY()-c.getY())*(h[b].getY()-c.getY()));u[a][0].decreasePos((BALL_DIAMETER-e)*Math.cos(d),(BALL_DIAMETER-e)*Math.sin(d));var d=k[h[b].getFotogram()-
BALL_RADIUS][0],e=k[h[b].getFotogram()-BALL_RADIUS][1],d=Math.sqrt((c.getX()-d)*(c.getX()-d)+(c.getY()-e)*(c.getY()-e)),e=k[h[b].getFotogram()+BALL_RADIUS][0],f=k[h[b].getFotogram()+BALL_RADIUS][1],c=Math.sqrt((c.getX()-e)*(c.getX()-e)+(c.getY()-f)*(c.getY()-f));this._insertBall(u[a][0],b,d>c?"next":"previous");u.splice(a,1)}}else u[a][0].unload(),u.splice(a,1);else m=-1};this.update=function(){if(!1!==c)switch(!0===f&&this._attract(),!0===d&&this._checkPushCollision(),m){case STATE_GAME_ROLL_IN:this._updateRollIn();
break;case STATE_GAME_ROLL_OUT:this._updateRollOut();break;case STATE_GAME_SHOOTING:this._updateShooting();this._updateMove();break;default:this._updateMove()}};s_oGame=this;COMBO_VALUE=a.combo_value;EXTRA_SCORE=a.extra_score;this._init()}var s_oGame,s_oBezier;
function CExtraScore(a,c,e){var d;this._init=function(a,b,c){var e=s_oSpriteLibrary.getSprite("extra_score");d=createBitmap(e);d.x=a;d.y=b;d.regX=e.width/2;d.regY=e.height/2;d.alpha=0;c.addChild(d);createjs.Tween.get(d).to({alpha:1},1E3).call(function(){c.removeChild(d)})};this._init(a,c,e)}
function CEndPanel(a){var c,e,d,f,b,g;this._init=function(a){c=createBitmap(a);c.x=0;c.y=0;b=new createjs.Text("","bold 48px Chewy","#000");b.x=CANVAS_WIDTH/2+2;b.y=CANVAS_HEIGHT/2-138;b.textAlign="center";f=new createjs.Text("","bold 48px Chewy","#ffffff");f.x=CANVAS_WIDTH/2;f.y=CANVAS_HEIGHT/2-140;f.textAlign="center";e=new createjs.Text("","bold 32px Chewy","#000");e.x=CANVAS_WIDTH/2+1;e.y=CANVAS_HEIGHT/2+11;e.textAlign="center";d=new createjs.Text("","bold 32px Chewy","#ffffff");d.x=CANVAS_WIDTH/
2;d.y=CANVAS_HEIGHT/2+10;d.textAlign="center";g=new createjs.Container;g.alpha=0;g.visible=!1;g.addChild(c,e,d,b,f);s_oStage.addChild(g)};this.unload=function(){g.off("mousedown",this._onExit);s_oStage.removeChild(g)};this._initListener=function(){g.on("mousedown",this._onExit)};this.show=function(a,c){c?(b.text=TEXT_CONGRATS,f.text=TEXT_CONGRATS):(b.text=TEXT_GAMEOVER,f.text=TEXT_GAMEOVER);e.text=TEXT_FINAL_SCORE+": "+a;d.text=TEXT_FINAL_SCORE+": "+a;g.visible=!0;var n=this;createjs.Tween.get(g).to({alpha:1},
500).call(function(){n._initListener()});$(s_oMain).trigger("save_score",a)};this._onExit=function(){g.off("mousedown");s_oGame.onExit()};this._init(a);return this};