function CGfxButton(a,e,b){var c,h,d;this._init=function(b,a,e){c=[];h=[];d=createBitmap(e);d.x=b;d.y=a;d.regX=e.width/2;d.regY=e.height/2;s_oStage.addChild(d);this._initListener()};this.unload=function(){d.off("mousedown",this.buttonDown);d.off("pressup",this.buttonRelease);s_oStage.removeChild(d)};this.setVisible=function(b){d.visible=b};this._initListener=function(){d.on("mousedown",this.buttonDown);d.on("pressup",this.buttonRelease)};this.addEventListener=function(b,a,d){c[b]=a;h[b]=d};this.buttonRelease=
function(){d.scaleX=1;d.scaleY=1;c[ON_MOUSE_UP]&&c[ON_MOUSE_UP].call(h[ON_MOUSE_UP])};this.buttonDown=function(){d.scaleX=.9;d.scaleY=.9;c[ON_MOUSE_DOWN]&&c[ON_MOUSE_DOWN].call(h[ON_MOUSE_DOWN])};this.setPosition=function(b,a){d.x=b;d.y=a};this.setX=function(b){d.x=b};this.setY=function(b){d.y=b};this.getButtonImage=function(){return d};this.getX=function(){return d.x};this.getY=function(){return d.y};this._init(a,e,b);return this}
function CGame(a){var e,b,c,h,d,k,g,l,f,r,n,m=null,p,q;this._init=function(){k=1;c=b=0;g=START_BET;l=START_CREDIT;f=-1;d=STATE_IDLE;r=[];for(var a=0,v=0;v<WHEEL_SETTINGS.length;v++)a+=WHEEL_SETTINGS[v].win_occurence;100!==a?(a=createBitmap(s_oSpriteLibrary.getSprite("msg_box")),s_oStage.addChild(a),a=new createjs.Text(TEXT_ALERT,"bold 50px Arial Black","#ffffff"),a.x=CANVAS_WIDTH/2,a.y=CANVAS_HEIGHT/2-200,a.textAlign="center",a.textBaseline="middle",a.lineWidth=900,s_oStage.addChild(a)):(e=!0,p=new CWheel(1198,
540),a=createBitmap(s_oSpriteLibrary.getSprite("bg_game")),s_oStage.addChild(a),q=new CLeds(1198,540),h=q.getState(),n=new CInterface,new CHelpPanel,this._initProbability())};this._initProbability=function(){for(var a=[],b=0;b<WHEEL_SETTINGS.length;b++)a[b]=WHEEL_SETTINGS[b].win_occurence;for(b=0;b<a.length;b++)for(var c=0;c<a[b];c++)r.push(b)};this.modifyBonus=function(b){g="plus"===b?g+BET_OFFSET:g-BET_OFFSET;if(g>MAX_BET)g-=BET_OFFSET,k=1;else if(g<START_BET)g+=BET_OFFSET,k=1;else if(g>l){g-=BET_OFFSET;
return}k=Math.floor(g/START_BET);n.refreshBet(g);p.clearText(k);p.setText(k)};this.spinWheel=function(){n.disableSpin(!0);d=STATE_SPIN;c=0;this.setNewRound();n.refreshMoney("0");l-=g;n.refreshCredit(l);var b=Math.floor(Math.random()*r.length);f=r[b];var a=MIN_FAKE_SPIN+Math.floor(3*Math.random()),h=SEGMENT_ROT-3,h=-h/2+Math.random()*h,b=(360-p.getDegree()+r[b]*SEGMENT_ROT+h)%360;p.spin(360*a+b,a)};this.setNewRound=function(){0>f||(n.refreshCredit(l),n.clearMoneyPanel(),f=-1)};this.releaseWheel=function(){n.disableSpin(!1);
n.refreshMoney(WHEEL_SETTINGS[f].prize*k);l+=WHEEL_SETTINGS[f].prize*k;n.refreshCredit(l);n.animWin();l<START_BET&&this.gameOver();k>l/START_BET&&(k=Math.floor(l/START_BET),g=k*START_BET,n.refreshBet(g));0>=WHEEL_SETTINGS[f].prize?(d=STATE_LOSE,!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("game_over")):(d=STATE_WIN,!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("win"));$(s_oMain).trigger("save_score",[l,WHEEL_SETTINGS[f].prize])};this.getCurColor=function(){return p.getColor()};
this.unload=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.stop();e=!1;n.unload();null!==m&&m.unload();createjs.Tween.removeAllTweens();s_oStage.removeAllChildren()};this.onExit=function(){this.unload();s_oMain.gotoMenu();$(s_oMain).trigger("restart")};this._onExitHelp=function(){_bStartGame=!0};this.gameOver=function(){m=CEndPanel(s_oSpriteLibrary.getSprite("msg_box"));m.show()};this._animLedIdle=function(){b+=s_iTimeElaps;if(b>TIME_ANIM_IDLE){b=0;for(var a=Math.floor(Math.random()*
q.getNumAnim());a===h;)a=Math.floor(Math.random()*q.getNumAnim());q.changeAnim(a);h=a}};this._animLedSpin=function(){q.changeAnim(LED_SPIN);d=-1};this._animLedWin=function(){if(0===c){var a=4+Math.round(Math.random());q.changeAnim(a);q.setWinColor(this.getCurColor())}else c>TIME_ANIM_WIN&&(b=TIME_ANIM_IDLE,d=STATE_IDLE,this.setNewRound(),c=0);c+=s_iTimeElaps};this._animLedLose=function(){0===c?(q.changeAnim(6),q.setWinColor(this.getCurColor())):c>TIME_ANIM_LOSE&&(b=TIME_ANIM_IDLE,d=STATE_IDLE,this.setNewRound(),
c=0);c+=s_iTimeElaps};this.update=function(){if(e)switch(q.update(),d){case STATE_IDLE:this._animLedIdle();break;case STATE_SPIN:this._animLedSpin();break;case STATE_WIN:this._animLedWin();break;case STATE_LOSE:this._animLedLose()}};s_oGame=this;WHEEL_SETTINGS=a.wheel_settings;START_CREDIT=a.start_credit;START_BET=a.start_bet;BET_OFFSET=a.bet_offset;MAX_BET=a.max_bet;TIME_ANIM_IDLE=a.anim_idle_change_frequency;ANIM_IDLE1_TIMESPEED=a.led_anim_idle1_timespeed;ANIM_IDLE2_TIMESPEED=a.led_anim_idle2_timespeed;
ANIM_IDLE3_TIMESPEED=a.led_anim_idle3_timespeed;ANIM_SPIN_TIMESPEED=a.led_anim_spin_timespeed;TIME_ANIM_WIN=a.led_anim_win_duration;ANIM_WIN1_TIMESPEED=a.led_anim_win1_timespeed;ANIM_WIN2_TIMESPEED=a.led_anim_win2_timespeed;TIME_ANIM_LOSE=a.led_anim_lose_duration;this._init()}var s_oGame;
function CFormatText(a,e,b,c){var h,d,k,g;this._init=function(b,a,c,e){h=0;g=new createjs.Container;g.x=b;g.y=a;e.addChild(g);b=85;a=b/20;for(e=0;e<c.length;e++){var m=b+"px";d=new createjs.Text;d.text=c[e];d.font="bold "+m+" Arial";d.color="#000000";d.textAlign="left";d.textBaseline="middle";d.x=h+2;d.y=2;g.addChild(d);k=new createjs.Text;k.text=c[e];k.font="bold "+m+" Arial";k.color="#ffffff";k.textAlign="left";k.textBaseline="middle";k.x=h;g.addChild(k);h+=d.getMeasuredWidth()+a;b-=9}};this.unload=
function(){c.removeChild(g)};this.rotateText=function(b){g.rotation=b};this._init(a,e,b,c)}
function CEndPanel(a){var e,b,c,h;this._init=function(a){e=createBitmap(a);e.x=0;e.y=0;c=new createjs.Text("","bold 70px Arial","#000");c.x=CANVAS_WIDTH/2+3;c.y=CANVAS_HEIGHT/2-50;c.textAlign="center";c.textBaseline="alphabetic";c.lineWidth=800;h=new createjs.Text("","bold 70px Arial","#ffffff");h.x=CANVAS_WIDTH/2;h.y=CANVAS_HEIGHT/2-53;h.textAlign="center";h.textBaseline="alphabetic";h.lineWidth=800;b=new createjs.Container;b.alpha=0;b.visible=!1;b.addChild(e,c,h);s_oStage.addChild(b)};this.unload=
function(){b.off("mousedown",this._onExit)};this._initListener=function(){b.on("mousedown",this._onExit)};this.show=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("game_over");c.text=TEXT_GAMEOVER;h.text=TEXT_GAMEOVER;b.visible=!0;var a=this;createjs.Tween.get(b).to({alpha:1},500).call(function(){a._initListener()})};this._onExit=function(){b.off("mousedown",this._onExit);s_oStage.removeChild(b);s_oGame.onExit()};this._init(a);return this}
function CSpriteLibrary(){var a,e,b,c,h,d;this.init=function(k,g,l){b=e=0;c=k;h=g;d=l;a={}};this.addSprite=function(b,c){a.hasOwnProperty(b)||(a[b]={szPath:c,oSprite:new Image},e++)};this.getSprite=function(b){return a.hasOwnProperty(b)?a[b].oSprite:null};this._onSpritesLoaded=function(){h.call(d)};this._onSpriteLoaded=function(){c.call(d);++b==e&&this._onSpritesLoaded()};this.loadSprites=function(){for(var b in a)a[b].oSprite.oSpriteLibrary=this,a[b].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
a[b].oSprite.src=a[b].szPath};this.getNumSprites=function(){return e}}
var CANVAS_WIDTH=1920,CANVAS_HEIGHT=1080,EDGEBOARD_X=256,EDGEBOARD_Y=84,FPS_TIME=1E3/24,DISABLE_SOUND_MOBILE=!1,STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,TIME_ANIM_IDLE,ANIM_IDLE1_TIMESPEED,ANIM_IDLE2_TIMESPEED,ANIM_IDLE3_TIMESPEED,ANIM_SPIN_TIMESPEED,TIME_ANIM_WIN,ANIM_WIN1_TIMESPEED,ANIM_WIN2_TIMESPEED,TIME_ANIM_LOSE,STATE_IDLE=0,STATE_SPIN=1,STATE_WIN=2,STATE_LOSE=3,LED_SPIN=3,MIN_FAKE_SPIN=
3,WHEEL_SPIN_TIMESPEED=2600,START_CREDIT,START_BET,BET_OFFSET,MAX_BET,WHEEL_SETTINGS,SEGMENT_ROT=18;
function CWheel(a,e){var b,c,h,d,k,g;this._init=function(a,f){b=[];c=[];h=[];for(var e=0;e<WHEEL_SETTINGS.length;e++)h[e]=WHEEL_SETTINGS[e].prize;this._initColors();e=s_oSpriteLibrary.getSprite("wheel");k=new createjs.Container;k.x=a;k.y=f;s_oStage.addChild(k);d=createBitmap(e);d.regX=e.width/2;d.regY=e.height/2;k.addChild(d);this.setText(1)};this.unload=function(){s_oStage.removeChild(k)};this._initColors=function(){for(var b=0;9>b;b++)c[0]="violet";for(b=351;360>=b;b++)c[b]="violet";for(var a=0;4>
a;a++)for(b=9+a*SEGMENT_ROT*5;b<27+a*SEGMENT_ROT*5;b++)c[b]="blue";for(a=0;4>a;a++)for(b=27+a*SEGMENT_ROT*5;b<45+a*SEGMENT_ROT*5;b++)c[b]="green";for(a=0;4>a;a++)for(b=45+a*SEGMENT_ROT*5;b<63+a*SEGMENT_ROT*5;b++)c[b]="yellow";for(a=0;4>a;a++)for(b=63+a*SEGMENT_ROT*5;b<81+a*SEGMENT_ROT*5;b++)c[b]="red";for(a=0;3>a;a++)for(b=81+a*SEGMENT_ROT*5;b<=99+a*SEGMENT_ROT*5;b++)c[b]="violet";for(b=315;333>=b;b++)c[b]="white"};this.setText=function(a){for(var c=new CVector2(-355,3),d=SEGMENT_ROT,e=Math.PI*SEGMENT_ROT/
180,g=0;g<h.length;g++)b[g]=new CFormatText(c.getX(),c.getY(),TEXT_CURRENCY+h[g]*a,k),b[g].rotateText(-d*g),rotateVector2D(e,c)};this.clearText=function(){for(var a=0;a<h.length;a++)b[a].unload()};this.spin=function(b,a){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)createjs.Sound.play("start_reel"),g=createjs.Sound.play("reel",{loop:-1}),g.volume=.1;createjs.Tween.get(k).to({rotation:k.rotation+b},WHEEL_SPIN_TIMESPEED*a,createjs.Ease.quartOut).call(function(){k.rotation%=360;s_oGame.releaseWheel();
!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||g.stop()})};this.getDegree=function(){return k.rotation};this.getColor=function(){var b=Math.round(k.rotation);return c[b]};this._init(a,e)}
function CVector2(a,e){var b,c;this._init=function(a,d){b=a;c=d};this.add=function(a,d){b+=a;c+=d};this.addV=function(a){b+=a.getX();c+=a.getY()};this.scalarDivision=function(a){b/=a;c/=a};this.subV=function(a){b-=a.getX();c-=a.getY()};this.scalarProduct=function(a){b*=a;c*=a};this.invert=function(){b*=-1;c*=-1};this.dotProduct=function(a){return b*a.getX()+c*a.getY()};this.set=function(a,d){b=a;c=d};this.setV=function(a){b=a.getX();c=a.getY()};this.length=function(){return Math.sqrt(b*b+c*c)};this.length2=
function(){return b*b+c*c};this.normalize=function(){var a=this.length();0<a&&(b/=a,c/=a)};this.getNormalize=function(a){this.length();a.set(b,c);a.normalize()};this.rot90CCW=function(){var a=b;b=-c;c=a};this.rot90CW=function(){var a=b;b=c;c=-a};this.getRotCCW=function(a){a.set(b,c);a.rot90CCW()};this.getRotCW=function(a){a.set(b,c);a.rot90CW()};this.ceil=function(){b=Math.ceil(b);c=Math.ceil(c)};this.round=function(){b=Math.round(b);c=Math.round(c)};this.toString=function(){return"Vector2: "+b+", "+
c};this.print=function(){trace("Vector2: "+b+", "+c+"")};this.getX=function(){return b};this.getY=function(){return c};this._init(a,e)}
function CToggle(a,e,b,c){var h,d,k,g;this._init=function(a,b,c,e){d=[];k=[];var m=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_true:[0],state_false:[1]}});h=e;g=createSprite(m,"state_"+h,c.width/2/2,c.height/2,c.width/2,c.height);g.x=a;g.y=b;g.stop();s_oStage.addChild(g);this._initListener()};this.unload=function(){g.off("mousedown",this.buttonDown);g.off("pressup",this.buttonRelease);s_oStage.removeChild(g)};this._initListener=
function(){g.on("mousedown",this.buttonDown);g.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){d[a]=b;k[a]=c};this.setActive=function(a){h=a;g.gotoAndStop("state_"+h)};this.buttonRelease=function(){g.scaleX=1;g.scaleY=1;!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");h=!h;g.gotoAndStop("state_"+h);d[ON_MOUSE_UP]&&d[ON_MOUSE_UP].call(k[ON_MOUSE_UP],h)};this.buttonDown=function(){g.scaleX=.9;g.scaleY=.9;d[ON_MOUSE_DOWN]&&d[ON_MOUSE_DOWN].call(k[ON_MOUSE_DOWN])};
this.setPosition=function(a,b){g.x=a;g.y=b};this._init(a,e,b,c)}var s_iScaleFactor=1,s_oCanvasLeft,s_oCanvasTop;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,4))})(navigator.userAgent||
navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}
function getSize(a){var e=a.toLowerCase(),b=window.document,c=b.documentElement;if(void 0===window["inner"+a])a=c["client"+a];else if(window["inner"+a]!=c["client"+a]){var h=b.createElement("body");h.id="vpw-test-b";h.style.cssText="overflow:scroll";var d=b.createElement("div");d.id="vpw-test-d";d.style.cssText="position:absolute;top:-1000px";d.innerHTML="<style>@media("+e+":"+c["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+e+":7px!important}}</style>";h.appendChild(d);c.insertBefore(h,b.head);
a=7==d["offset"+a]?c["client"+a]:window["inner"+a];c.removeChild(h)}else a=window["inner"+a];return a}$(window).ready(function(){sizeHandler()});window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}
function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a;a=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var e=getSize("Width"),b=Math.min(a/CANVAS_HEIGHT,e/CANVAS_WIDTH),c=CANVAS_WIDTH*b,b=CANVAS_HEIGHT*b,h=0;b<a?(h=a-b,b+=h,c+=CANVAS_WIDTH/CANVAS_HEIGHT*h):c<e&&(h=e-c,c+=h,b+=CANVAS_HEIGHT/CANVAS_WIDTH*h);var h=a/2-b/2,d=e/2-c/2,k=CANVAS_WIDTH/c;if(d*k<-EDGEBOARD_X||h*k<-EDGEBOARD_Y)b=Math.min(a/(CANVAS_HEIGHT-2*EDGEBOARD_Y),e/(CANVAS_WIDTH-2*
EDGEBOARD_X)),c=CANVAS_WIDTH*b,b*=CANVAS_HEIGHT,h=(a-b)/2,d=(e-c)/2,k=CANVAS_WIDTH/c;s_iOffsetX=-1*d*k;s_iOffsetY=-1*h*k;0<=h&&(s_iOffsetY=0);0<=d&&(s_iOffsetX=0);null!==s_oInterface&&s_oInterface.refreshButtonPos(s_iOffsetX,s_iOffsetY);null!==s_oMenu&&s_oMenu.refreshButtonPos(s_iOffsetX,s_iOffsetY);$("#canvas").css("width",c+"px");$("#canvas").css("height",b+"px");0>h?$("#canvas").css("top",h+"px"):$("#canvas").css("top","0px");$("#canvas").css("left",d+"px")}}
function createBitmap(a,e,b){var c=new createjs.Bitmap(a),h=new createjs.Shape;e&&b?h.graphics.beginFill("#fff").drawRect(0,0,e,b):h.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);c.hitArea=h;return c}function createSprite(a,e,b,c,h,d){a=null!==e?new createjs.Sprite(a,e):new createjs.Sprite(a);e=new createjs.Shape;e.graphics.beginFill("#000000").drawRect(-b,-c,h,d);a.hitArea=e;return a}
function randomFloatBetween(a,e,b){"undefined"===typeof b&&(b=2);return parseFloat(Math.min(a+Math.random()*(e-a),e).toFixed(b))}function rotateVector2D(a,e){var b=e.getX()*Math.cos(a)+e.getY()*Math.sin(a),c=e.getX()*-Math.sin(a)+e.getY()*Math.cos(a);e.set(b,c)}function tweenVectorsOnX(a,e,b){return a+b*(e-a)}function shuffle(a){for(var e=a.length,b,c;0!==e;)c=Math.floor(Math.random()*e),--e,b=a[e],a[e]=a[c],a[c]=b;return a}
function bubbleSort(a){var e;do{e=!1;for(var b=0;b<a.length-1;b++)a[b]>a[b+1]&&(e=a[b],a[b]=a[b+1],a[b+1]=e,e=!0)}while(e)}function compare(a,e){return a.index>e.index?-1:a.index<e.index?1:0}function easeLinear(a,e,b,c){return b*a/c+e}function easeInQuad(a,e,b,c){return b*(a/=c)*a+e}function easeInSine(a,e,b,c){return-b*Math.cos(a/c*(Math.PI/2))+b+e}function easeInCubic(a,e,b,c){return b*(a/=c)*a*a+e}
function getTrajectoryPoint(a,e){var b=new createjs.Point,c=(1-a)*(1-a),h=a*a;b.x=c*e.start.x+2*(1-a)*a*e.traj.x+h*e.end.x;b.y=c*e.start.y+2*(1-a)*a*e.traj.y+h*e.end.y;return b}function formatTime(a){a/=1E3;var e=Math.floor(a/60);a=parseFloat(a-60*e).toFixed(1);var b="",b=10>e?b+("0"+e+":"):b+(e+":");return b=10>a?b+("0"+a):b+a}function degreesToRadians(a){return a*Math.PI/180}function checkRectCollision(a,e){var b,c;b=getBounds(a,.9);c=getBounds(e,.98);return calculateIntersection(b,c)}
function calculateIntersection(a,e){var b,c,h,d,k,g,l,f;b=a.x+(h=a.width/2);c=a.y+(d=a.height/2);k=e.x+(g=e.width/2);l=e.y+(f=e.height/2);b=Math.abs(b-k)-(h+g);c=Math.abs(c-l)-(d+f);return 0>b&&0>c?(b=Math.min(Math.min(a.width,e.width),-b),c=Math.min(Math.min(a.height,e.height),-c),{x:Math.max(a.x,e.x),y:Math.max(a.y,e.y),width:b,height:c,rect1:a,rect2:e}):null}
function getBounds(a,e){var b={x:Infinity,y:Infinity,width:0,height:0};if(a instanceof createjs.Container){b.x2=-Infinity;b.y2=-Infinity;var c=a.children,h=c.length,d,k;for(k=0;k<h;k++)d=getBounds(c[k],1),d.x<b.x&&(b.x=d.x),d.y<b.y&&(b.y=d.y),d.x+d.width>b.x2&&(b.x2=d.x+d.width),d.y+d.height>b.y2&&(b.y2=d.y+d.height);Infinity==b.x&&(b.x=0);Infinity==b.y&&(b.y=0);Infinity==b.x2&&(b.x2=0);Infinity==b.y2&&(b.y2=0);b.width=b.x2-b.x;b.height=b.y2-b.y;delete b.x2;delete b.y2}else{var g,l;a instanceof createjs.Bitmap?
(h=a.sourceRect||a.image,k=h.width*e,g=h.height*e):a instanceof createjs.Sprite?a.spriteSheet._frames&&a.spriteSheet._frames[a.currentFrame]&&a.spriteSheet._frames[a.currentFrame].image?(h=a.spriteSheet.getFrame(a.currentFrame),k=h.rect.width,g=h.rect.height,c=h.regX,l=h.regY):(b.x=a.x||0,b.y=a.y||0):(b.x=a.x||0,b.y=a.y||0);c=c||0;k=k||0;l=l||0;g=g||0;b.regX=c;b.regY=l;h=a.localToGlobal(0-c,0-l);d=a.localToGlobal(k-c,g-l);k=a.localToGlobal(k-c,0-l);c=a.localToGlobal(0-c,g-l);b.x=Math.min(Math.min(Math.min(h.x,
d.x),k.x),c.x);b.y=Math.min(Math.min(Math.min(h.y,d.y),k.y),c.y);b.width=Math.max(Math.max(Math.max(h.x,d.x),k.x),c.x)-b.x;b.height=Math.max(Math.max(Math.max(h.y,d.y),k.y),c.y)-b.y}return b}function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}function shuffle(a){for(var e=a.length,b,c;0<e;)c=Math.floor(Math.random()*e),e--,b=a[e],a[e]=a[c],a[c]=b;return a}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3==a.nodeType&&(a=a.parentNode);var e=document.createEvent("MouseEvents");e.initEvent("click",!0,!0);a.dispatchEvent(e)}}};
(function(){function a(a){var c={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};a=a||window.event;a.type in c?document.body.className=c[a.type]:(document.body.className=this[e]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var e="hidden";e in document?document.addEventListener("visibilitychange",a):(e="mozHidden")in document?document.addEventListener("mozvisibilitychange",a):(e="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",a):(e="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a})();
function CTextButton(a,e,b,c,h,d,k,g,l){var f,r,n,m,p,q,t;this._init=function(a,b,c,d,e,g,h,k,l){f=!1;r=[];n=[];t=createBitmap(c);var u=Math.ceil(h/20);q=new createjs.Text(d,"bold "+h+"px "+e,"#000000");q.textAlign="center";q.textBaseline="alphabetic";var w=q.getBounds();q.x=c.width/2+u;q.y=Math.floor(c.height/2)+w.height/3+u-7;p=new createjs.Text(d,"bold "+h+"px "+e,g);p.textAlign="center";p.textBaseline="alphabetic";w=p.getBounds();p.x=c.width/2;p.y=Math.floor(c.height/2)+w.height/3-7;m=new createjs.Container;
m.x=a;m.y=b;m.regX=c.width/2;m.regY=c.height/2;k||(a=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_true:[0],state_false:[1]}}),t=createSprite(a,"state_false",c.width/2/2,c.height/2,c.width/2,c.height),q.x=u,q.y=u+17,p.x=0,p.y=17,m.regX=0,m.regY=0);m.addChild(t,q,p);l.addChild(m);this._initListener()};this.unload=function(){m.off("mousedown");m.off("pressup");l.removeChild(m)};this.setVisible=function(a){m.visible=a};
this._initListener=function(){oParent=this;m.on("mousedown",this.buttonDown);m.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){r[a]=b;n[a]=c};this.buttonRelease=function(){f||(m.scaleX=1,m.scaleY=1,r[ON_MOUSE_UP]&&r[ON_MOUSE_UP].call(n[ON_MOUSE_UP]))};this.buttonDown=function(){f||(m.scaleX=.9,m.scaleY=.9,r[ON_MOUSE_DOWN]&&r[ON_MOUSE_DOWN].call(n[ON_MOUSE_DOWN]))};this.enable=function(){f=!1;g||t.gotoAndStop("state_true")};this.disable=function(){f=!0;g||t.gotoAndStop("state_false")};
this.setTextPosition=function(a,b){var c=Math.ceil(k/20);q.x=a+c;q.y=b+c;p.x=a;p.y=b};this.setPosition=function(a,b){m.x=a;m.y=b};this.setX=function(a){m.x=a};this.setY=function(a){m.y=a};this.getButtonImage=function(){return m};this.getX=function(){return m.x};this.getY=function(){return m.y};this._init(a,e,b,c,h,d,k,g,l);return this}
function CPreloader(){var a,e,b,c,h,d,k;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.loadSprites();k=new createjs.Container;s_oStage.addChild(k)};this.unload=function(){k.removeAllChildren()};this.hide=function(){var a=this;setTimeout(function(){createjs.Tween.get(d).to({alpha:1},500).call(function(){a.unload();
s_oMain.gotoMenu()})},1E3)};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var g=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));k.addChild(g);g=s_oSpriteLibrary.getSprite("progress_bar");c=createBitmap(g);c.x=CANVAS_WIDTH/2-g.width/2;c.y=CANVAS_HEIGHT-170;k.addChild(c);a=g.width;e=g.height;h=new createjs.Shape;h.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(c.x,c.y,1,e);k.addChild(h);c.mask=
h;b=new createjs.Text("","30px Arial","#fff");b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT-125;b.shadow=new createjs.Shadow("#000",2,2,2);b.textBaseline="alphabetic";b.textAlign="center";k.addChild(b);d=new createjs.Shape;d.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);d.alpha=0;k.addChild(d)};this.refreshLoader=function(d){b.text=d+"%";h.graphics.clear();d=Math.floor(d*a/100);h.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(c.x,c.y,d,e)};this._init()}
function CMenu(){var a,e,b,c,h,d;this._init=function(){b=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(b);var k=s_oSpriteLibrary.getSprite("but_play");c=new CTextButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-190,k,TEXT_PLAY,"Arial","#ffffff",70,!1,s_oStage);c.enable();c.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)k=s_oSpriteLibrary.getSprite("audio_icon"),a=CANVAS_WIDTH-k.height/2-10,e=k.height/2+10,d=new CToggle(a,e,k,s_bAudioActive),
d.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);h=new createjs.Shape;h.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(h);createjs.Tween.get(h).to({alpha:0},1E3).call(function(){h.visible=!1});this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){c.unload();c=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)d.unload(),d=null;s_oStage.removeChild(b);s_oMenu=b=null};this.refreshButtonPos=function(b,c){d.setPosition(a-b,c+e)};this._onAudioToggle=
function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onButPlayRelease=function(){this.unload();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");s_oMain.gotoGame()};s_oMenu=this;this._init()}var s_oMenu=null;
function CMain(a){var e,b=0,c=0,h=STATE_LOADING,d,k,g;this.initContainer=function(){s_oCanvas=document.getElementById("canvas");s_oStage=new createjs.Stage(s_oCanvas);createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&(s_oStage.enableMouseOver(20),$("body").on("contextmenu","#canvas",function(a){return!1}));s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.setFPS(30);navigator.userAgent.match(/Windows Phone/i)&&(DISABLE_SOUND_MOBILE=
!0);s_oSpriteLibrary=new CSpriteLibrary;k=new CPreloader};this.preloaderReady=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();this._loadImages();e=!0};this.soundLoaded=function(){b++;k.refreshLoader(Math.floor(b/c*100));b===c&&(k.unload(),this.gotoMenu())};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&(0<navigator.userAgent.indexOf("Opera")||0<navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=["mp3"],createjs.Sound.addEventListener("fileload",
createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/press_button.ogg","click"),createjs.Sound.registerSound("./sounds/game_over.ogg","game_over"),createjs.Sound.registerSound("./sounds/reel.ogg","reel"),createjs.Sound.registerSound("./sounds/start_reel.ogg","start_reel"),createjs.Sound.registerSound("./sounds/win.ogg","win")):(createjs.Sound.alternateExtensions=["ogg"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/press_button.mp3",
"click"),createjs.Sound.registerSound("./sounds/game_over.mp3","game_over"),createjs.Sound.registerSound("./sounds/reel.mp3","reel"),createjs.Sound.registerSound("./sounds/start_reel.mp3","start_reel"),createjs.Sound.registerSound("./sounds/win.mp3","win")),c+=5)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("bg_menu",
"./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.png");s_oSpriteLibrary.addSprite("bg_help","./sprites/bg_help.png");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("but_spin","./sprites/but_spin.png");s_oSpriteLibrary.addSprite("but_plus","./sprites/but_plus.png");s_oSpriteLibrary.addSprite("wheel","./sprites/wheel.png");s_oSpriteLibrary.addSprite("leds",
"./sprites/leds.png");c+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){b++;k.refreshLoader(Math.floor(b/c*100));b===c&&(k.unload(),this.gotoMenu())};this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this.gotoMenu=function(){new CMenu;h=STATE_MENU};this.gotoGame=function(a){s_bEasyMode=a;g=new CGame(d);h=STATE_GAME;$(s_oMain).trigger("game_start")};this.gotoHelp=function(){new CHelp;h=STATE_HELP};this.stopUpdate=
function(){e=!1};this.startUpdate=function(){e=!0};this._update=function(a){if(!1!==e){var b=(new Date).getTime();s_iTimeElaps=b-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=b;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);h===STATE_GAME&&g.update();s_oStage.update(a)}};s_oMain=this;d=a;this.initContainer()}
var s_bMobile,s_bEasyMode,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oCanvas;
function CLeds(a,e){var b,c,h,d,k,g,l,f,r;this._init=function(a,b){k=3;h=Math.floor(Math.random()*k);d=0;f=[];r=new createjs.Container;r.x=a;r.y=b;s_oStage.addChild(r);for(var c={images:[s_oSpriteLibrary.getSprite("leds")],frames:{width:90,height:90,regX:45,regY:45},animations:{off:[0],white:[1],green:[2],blue:[3],violet:[4],red:[5],yellow:[6]}},c=new createjs.SpriteSheet(c),e=new CVector2(-427,0),g=360/WHEEL_SETTINGS.length*Math.PI/180,l=0;l<WHEEL_SETTINGS.length;l++)f[l]=createSprite(c,"off",0,
0,90,90),f[l].x=e.getX(),f[l].y=e.getY(),rotateVector2D(g,e),r.addChild(f[l]);f[0].visible=!1};this.unload=function(){s_oStage.removeChild(r)};this.setWinColor=function(a){b=a};this.getState=function(){return h};this.getNumAnim=function(){return k};this.changeAnim=function(a){d=0;h=a;for(a=0;a<f.length;a++)f[a].gotoAndStop("off")};this.animIdle0=function(){d+=s_iTimeElaps;if(0<=d&&d<ANIM_IDLE1_TIMESPEED/2)for(var a=0;a<f.length;a++)0===a%2?f[a].gotoAndStop("white"):f[a].gotoAndStop("off");else if(d>=
ANIM_IDLE1_TIMESPEED/2&&d<ANIM_IDLE1_TIMESPEED)for(a=0;a<f.length;a++)0===a%2?f[a].gotoAndStop("off"):f[a].gotoAndStop("white");else d=0};this.animIdle1=function(){0===d&&(g=0,f[g].gotoAndStop("white"),f[f.length/4].gotoAndStop("white"),f[f.length/2].gotoAndStop("white"),f[3*f.length/4].gotoAndStop("white"));d+=s_iTimeElaps;d>ANIM_IDLE2_TIMESPEED&&(g===f.length/4&&(g=0,d=1),0===g?(f[f.length-1].gotoAndStop("off"),f[0].gotoAndStop("white"),f[f.length/4-1].gotoAndStop("off"),f[f.length/4].gotoAndStop("white"),
f[f.length/2-1].gotoAndStop("off"),f[f.length/2].gotoAndStop("white"),f[3*f.length/4-1].gotoAndStop("off"),f[3*f.length/4].gotoAndStop("white")):(f[g-1].gotoAndStop("off"),f[g].gotoAndStop("white"),f[f.length/4+g-1].gotoAndStop("off"),f[f.length/4+g].gotoAndStop("white"),f[f.length/2+g-1].gotoAndStop("off"),f[f.length/2+g].gotoAndStop("white"),f[3*f.length/4+g-1].gotoAndStop("off"),f[3*f.length/4+g].gotoAndStop("white")),g++,d=1)};this.animIdle2=function(){0===d&&(g=0,l=f.length/2,f[g].gotoAndStop("white"),
f[l].gotoAndStop("white"));d+=s_iTimeElaps;d>ANIM_IDLE3_TIMESPEED&&(g===f.length/2&&(g=0,l=f.length/2,d=1),0===g?(f[f.length-1].gotoAndStop("off"),f[1].gotoAndStop("off"),f[0].gotoAndStop("white"),f[f.length/2+1].gotoAndStop("off"),f[f.length/2-1].gotoAndStop("off"),f[f.length/2].gotoAndStop("white")):(f[g-1].gotoAndStop("off"),f[g].gotoAndStop("white"),1!==g&&f[f.length-g+1].gotoAndStop("off"),f[f.length-g].gotoAndStop("white"),f[l+1].gotoAndStop("off"),f[l].gotoAndStop("white"),f[f.length-l-1].gotoAndStop("off"),
0!==l&&f[f.length-l].gotoAndStop("white")),g++,l--,d=1)};this.animSpin0=function(){0===d&&(g=Math.floor(Math.random()*f.length),f[g].gotoAndStop("white"));d+=s_iTimeElaps;d>ANIM_SPIN_TIMESPEED&&(0>g&&(g=f.length-1,d=1),g===f.length-1?(f[0].gotoAndStop("off"),f[f.length-1].gotoAndStop("white")):(f[g+1].gotoAndStop("off"),f[g].gotoAndStop("white")),g--,d=1)};this.animWin0=function(){d+=s_iTimeElaps;if(0<=d&&d<ANIM_WIN1_TIMESPEED/2)for(var a=0;a<f.length;a++)0===a%2?f[a].gotoAndStop(b):f[a].gotoAndStop("off");
else if(d>=ANIM_WIN1_TIMESPEED/2&&d<ANIM_WIN1_TIMESPEED)for(a=0;a<f.length;a++)0===a%2?f[a].gotoAndStop("off"):f[a].gotoAndStop(b);else d=0};this.animWin1=function(){0===d&&(g=0,l=f.length/2,c=b,f[g].gotoAndStop(c),f[l].gotoAndStop(c));d+=s_iTimeElaps;d>ANIM_WIN2_TIMESPEED&&(g>f.length/4&&(g=0,l=f.length/2,d=1,c=c===b?"off":b),0===g?(f[0].gotoAndStop(c),f[f.length/2].gotoAndStop(c)):g<=f.length/4&&(f[g].gotoAndStop(c),f[f.length-g].gotoAndStop(c),f[l].gotoAndStop(c),0!==l&&f[f.length-l].gotoAndStop(c)),
g++,l--,d=1)};this.animLose=function(){for(var a=0;a<f.length;a++)f[a].gotoAndStop(b);h=-1};this.update=function(){switch(h){case 0:this.animIdle0();break;case 1:this.animIdle1();break;case 2:this.animIdle2();break;case 3:this.animSpin0();break;case 4:this.animWin0();break;case 5:this.animWin1();break;case 6:this.animLose()}};this._init(a,e)}TEXT_GAMEOVER="I'M SORRY, NO MORE CREDITS TO PLAY";TEXT_PLAY="PLAY";TEXT_CREDITS="CREDITS";TEXT_SPIN="SPIN";TEXT_PLUS="+";TEXT_MIN="-";TEXT_CURRENCY="$";
TEXT_HELP1='CLICK ON "+" or "-" BUTTONS TO SELECT YOUR BET. PRIZE WILL VARY ACCORDING TO THE WAGER. THE MORE YOU BET, THE MORE YOU CAN WIN. WHEN YOU ARE READY, SPIN THE WHEEL TO PLAY!';TEXT_HELP2="WHEN THE WHEEL STOPS SPINNING, YOU'LL BE SHOWN YOUR PRIZE!";TEXT_ALERT="wheel_settings PROBABILITY CHECK FAILED: win_occurence number sum must be 100! Please read paragraph in the documentation for more help.";
function CInterface(){var a,e,b,c,h,d,k,g,l,f=null,r,n,m,p,q,t;this._init=function(){q=this;r=0;var f=s_oSpriteLibrary.getSprite("but_exit");b=CANVAS_WIDTH-f.height/2-20;c=f.height/2+10;d=new CGfxButton(b,c,f,!0);d.addEventListener(ON_MOUSE_UP,this._onExit,this);a=CANVAS_WIDTH-f.width/2-100;e=f.height/2+10;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)f=s_oSpriteLibrary.getSprite("audio_icon"),h=new CToggle(a,e,f,s_bAudioActive),h.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);f=s_oSpriteLibrary.getSprite("but_spin");
k=new CTextButton(500,CANVAS_HEIGHT-190,f,TEXT_SPIN,"Arial","#ffffff",70,!1,s_oStage);k.enable();k.addEventListener(ON_MOUSE_UP,this._onButSpinRelease,this);f=s_oSpriteLibrary.getSprite("but_plus");g=new CTextButton(650,CANVAS_HEIGHT-320,f,TEXT_PLUS,"Arial","#ffffff",70,!1,s_oStage);g.enable();g.addEventListener(ON_MOUSE_UP,this._onButPlusRelease,this);f=s_oSpriteLibrary.getSprite("but_plus");l=new CTextButton(350,CANVAS_HEIGHT-320,f,TEXT_MIN,"Arial","#ffffff",70,!1,s_oStage);l.enable();l.addEventListener(ON_MOUSE_UP,
this._onButMinRelease,this);f=new createjs.Text(TEXT_CREDITS,"bold 90px Arial","#000000");f.x=304;f.y=204;f.textAlign="left";f.textBaseline="alphabetic";f.lineWidth=400;s_oStage.addChild(f);f=new createjs.Text(TEXT_CREDITS,"bold 90px Arial","#ffffff");f.x=300;f.y=200;f.textAlign="left";f.textBaseline="alphabetic";f.lineWidth=400;s_oStage.addChild(f);n=new createjs.Text(TEXT_CURRENCY+START_CREDIT,"bold 70px Arial","#ffffff");n.x=320;n.y=350;n.textAlign="left";n.textBaseline="alphabetic";n.lineWidth=
400;s_oStage.addChild(n);m=new createjs.Text(TEXT_CURRENCY+"0","bold 70px Arial","#ffffff");m.x=320;m.y=560;m.textAlign="left";m.textBaseline="alphabetic";m.lineWidth=400;s_oStage.addChild(m);t=new createjs.Text(TEXT_CURRENCY+"0","bold 70px Arial","yellow");t.x=320;t.y=560;t.textAlign="left";t.textBaseline="alphabetic";t.lineWidth=400;t.alpha=r;s_oStage.addChild(t);p=new createjs.Text(TEXT_CURRENCY+START_BET,"bold 40px Arial","#ffffff");p.x=500;p.y=775;p.textAlign="center";p.textBaseline="alphabetic";
p.lineWidth=400;s_oStage.addChild(p);this.refreshButtonPos(s_iOffsetX,s_iOffsetY)};this.unload=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)h.unload(),h=null;d.unload();k.unload();s_oInterface=null};this.refreshCredit=function(a){n.text=TEXT_CURRENCY+a};this.clearMoneyPanel=function(){t.alpha=0;createjs.Tween.removeTweens(t)};this.refreshMoney=function(a){m.text=TEXT_CURRENCY+a;t.text=TEXT_CURRENCY+a};this.refreshBet=function(a){p.text=TEXT_CURRENCY+a};this.animWin=function(){r=1===r?0:
1;createjs.Tween.get(t).to({alpha:r},150,createjs.Ease.cubicOut).call(function(){q.animWin()})};this._onButSpinRelease=function(){s_oGame.spinWheel()};this._onButPlusRelease=function(){s_oGame.modifyBonus("plus")};this._onButMinRelease=function(){s_oGame.modifyBonus("min")};this.disableSpin=function(a){!0===a?(k.disable(),g.disable(),l.disable()):(k.enable(),g.enable(),l.enable())};this._onButHelpRelease=function(){f=new CHelpPanel};this._onButRestartRelease=function(){s_oGame.restartGame()};this.onExitFromHelp=
function(){f.unload()};this.refreshButtonPos=function(f,g){d.setPosition(b-f,g+c);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||h.setPosition(a-f,g+e)};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onExit=function(){s_oGame.onExit()};s_oInterface=this;this._init();return this}var s_oInterface=null;
function CHelpPanel(){var a,e,b,c,h,d,k;this._init=function(){var g=this;h=createBitmap(s_oSpriteLibrary.getSprite("bg_help"));var k=CANVAS_WIDTH/2+200,f=CANVAS_HEIGHT/2-270;e=new createjs.Text(TEXT_HELP1,"bold 40px Arial","#000000");e.x=k+3;e.y=f+3;e.textAlign="center";e.textBaseline="alphabetic";e.lineWidth=600;a=new createjs.Text(TEXT_HELP1,"bold 40px Arial","#ffffff");a.x=k;a.y=f;a.textAlign="center";a.textBaseline="alphabetic";a.lineWidth=600;k=CANVAS_WIDTH/2-200;f=CANVAS_HEIGHT/2+150;c=new createjs.Text(TEXT_HELP2,
"bold 40px Arial","#000000");c.x=k+3;c.y=f+3;c.textAlign="center";c.textBaseline="alphabetic";c.lineWidth=600;b=new createjs.Text(TEXT_HELP2,"bold 40px Arial","#ffffff");b.x=k;b.y=f;b.textAlign="center";b.textBaseline="alphabetic";b.lineWidth=600;d=new createjs.Container;d.addChild(h,e,a,c,b);d.alpha=0;s_oStage.addChild(d);createjs.Tween.get(d).to({alpha:1},700);d.on("pressup",function(){g._onExitHelp()})};this.unload=function(){s_oStage.removeChild(d);var a=this;d.off("pressup",function(){a._onExitHelp()})};
this._onExitHelp=function(){k.unload();s_oGame._onExitHelp()};k=this;this._init()};