function CBomb(a,d,c,b,e,f,h){var q,l,r,n=0,G,A,w,E,D,p,F,v,x,B,t,z,C,k,m,u,g,y,H;this._init=function(a,b,c,e,f,d,h){H=h;r=!1;m=e;y=new createjs.Container;H.addChild(y);g=createSprite(c,"idle",e.regX,e.regY,e.width,e.height);g.x=a;g.y=b;g.regX=m.width/2;g.regY=m.height/2;H.addChild(g);F=m.width<m.height?Math.floor(m.width/2):Math.floor(m.height/2);p=Math.floor(1*F);p=Math.pow(p,2);A=f;G=A/9;w=a>CANVAS_WIDTH/2?randomFloatBetween(-.5,0,2):randomFloatBetween(0,.5,2);E=randomFloatBetween(-MAX_FRUIT_ROT_SPEED,
MAX_FRUIT_ROT_SPEED,2);C=new CVector2(0,-1);D=d;k=[{x:10,y:0},{x:-20,y:0},{x:10,y:-10},{x:0,y:20},{x:10,y:-10},{x:-10,y:0}];if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)u=createjs.Sound.play("bomb_fuse",{loop:-1})};this.unload=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||u.stop();H.removeChild(g)};this.explode=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)u.stop(),createjs.Sound.play(s_aFruitSpliceSound[D]);x=z=v=0;r=!0;q=g.x;l=g.y;var a=this;B=setInterval(function(){a.changeBrightness();
a.tremble()},20);t=setInterval(function(){a.showRay()},150)};this.tremble=function(){var a=k[z];g.x+=a.x;g.y+=a.y;z++;z===k.length&&(z=0)};this.showRay=function(){var a=s_oSpriteLibrary.getSprite("bomb_ray"),b=createBitmap(a);b.alpha=0;b.regY=a.height/2;b.x=q;b.y=l;b.scaleX=randomFloatBetween(.5,1,2);b.rotation=x;y.addChild(b);createjs.Tween.get(b).to({alpha:1},200);x+=randomFloatBetween(40,55,1);320<x&&(clearInterval(B),clearInterval(t),s_oGame.showExplosion())};this.changeBrightness=function(){if(201>
v){var a=(new createjs.ColorMatrix).adjustBrightness(v);g.filters=[new createjs.ColorMatrixFilter(a)];g.cache(0,0,m.width,m.height);v+=4}};this.getCenter=function(){return new CVector2(g.x,g.y)};this.getRadius=function(){return F};this.getSliceOffset=function(){return p};this.getY=function(){return g.y};this.getSprite=function(){return g};this.getRotation=function(){return g.rotation};this.getVectorDir=function(){return rotateVector2D(toRadian(-g.rotation),C)};this.isSliced=function(){return r};this.getType=
function(){return D};this.update=function(){n+=G;!1===r&&(g.y=g.y-A+n*n/1E3,g.x+=.1*n*w,g.rotation+=E)};this._init(a,d,c,b,e,f,h)}
function CSpriteLibrary(){var a,d,c,b,e,f;this.init=function(h,q,l){c=d=0;b=h;e=q;f=l;a={}};this.addSprite=function(b,c){a.hasOwnProperty(b)||(a[b]={szPath:c,oSprite:new Image},d++)};this.getSprite=function(b){return a.hasOwnProperty(b)?a[b].oSprite:null};this._onSpritesLoaded=function(){e.call(f)};this._onSpriteLoaded=function(){b.call(f);++c==d&&this._onSpritesLoaded()};this.loadSprites=function(){for(var b in a)a[b].oSprite.oSpriteLibrary=this,a[b].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
a[b].oSprite.src=a[b].szPath};this.getNumSprites=function(){return d}}
var CANVAS_WIDTH=768,CANVAS_HEIGHT=1024,DISABLE_SOUND_MOBILE=!0,FPS_TIME=1E3/24,STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,ON_PRESS_MOVE=6,NUM_FRUITS=6,Y_START_FRUIT,OCCURENCE_FRUIT,MAX_FRUIT_ROT_SPEED,NUM_LIVES,STARTING_SIMULTANEOUS_FRUITS,MAX_SIMULTANEOUS_FRUITS,FRUIT_TO_CUT_FOR_LEVEL_UP,TIME_FOR_COMBO,COMBO_TWO_FRUIT,LINE_DRAW_INTERVAL=100,BOMB_SYMBOL=6,SOUNDTRACK_VOLUME=.5;
function CWinText(a,d,c,b){var e;this._init=function(b,a,c,d){e=new createjs.Container;e.x=b;e.y=a;s_oStage.addChild(e);var r=new createjs.Text("+"+c,"70px katanaregular",d);r.textAlign="center";r.textBaseline="middle";r.shadow=new createjs.Shadow("#000000",2,2,3);e.addChild(r);b=Math.floor(1500*Math.random())+500;var n=this;createjs.Tween.get(r).to({y:r.y-100},b,createjs.Ease.sineOut).call(function(){createjs.Tween.get(r).to({alpha:0},500).call(function(){n.unload()})})};this.unload=function(){s_oStage.removeChild(e)};
this._init(a,d,c,b)}
function CVector2(a,d){var c,b;this._init=function(a,f){c=a;b=f};this.add=function(a,f){c+=a;b+=f};this.addV=function(a){c+=a.getX();b+=a.getY()};this.scalarDivision=function(a){c/=a;b/=a};this.subV=function(a){c-=a.getX();b-=a.getY()};this.scalarProduct=function(a){c*=a;b*=a};this.invert=function(){c*=-1;b*=-1};this.dotProduct=function(a){return c*a.getX()+b*a.getY()};this.set=function(a,f){c=a;b=f};this.setV=function(a){c=a.getX();b=a.getY()};this.length=function(){return Math.sqrt(c*c+b*b)};this.length2=
function(){return c*c+b*b};this.normalize=function(){var a=this.length();0<a&&(c/=a,b/=a)};this.getNormalize=function(a){this.length();a.set(c,b);a.normalize()};this.rot90CCW=function(){var a=c;c=-b;b=a};this.rot90CW=function(){var a=c;c=b;b=-a};this.getRotCCW=function(a){a.set(c,b);a.rot90CCW()};this.getRotCW=function(a){a.set(c,b);a.rot90CW()};this.ceil=function(){c=Math.ceil(c);b=Math.ceil(b)};this.round=function(){c=Math.round(c);b=Math.round(b)};this.toString=function(){return"Vector2: "+c+", "+
b};this.print=function(){trace("Vector2: "+c+", "+b+"")};this.getX=function(){return c};this.getY=function(){return b};this._init(a,d)}
function CToggle(a,d,c,b,e){var f,h,q,l,r=null;this._init=function(a,b,c,e,d){h=[];q=[];var r=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_true:[0],state_false:[1]}});f=e;l=createSprite(r,"state_"+f,c.width/2/2,c.height/2,c.width/2,c.height);l.x=a;l.y=b;l.stop();!1!==d&&s_oStage.addChild(l);this._initListener()};this.unload=function(){l.off("mousedown",this.buttonDown);l.off("pressup",this.buttonRelease);s_oStage.removeChild(l)};
this._initListener=function(){l.on("mousedown",this.buttonDown);l.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){h[a]=b;q[a]=c};this.addEventListenerWithParams=function(a,b,c,e){h[a]=b;q[a]=c;r=e};this.setActive=function(a){f=a;l.gotoAndStop("state_"+f)};this.buttonRelease=function(){l.scaleX=1;l.scaleY=1;!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");f=!f;l.gotoAndStop("state_"+f);h[ON_MOUSE_UP]&&h[ON_MOUSE_UP].call(q[ON_MOUSE_UP],{active:f,params:r})};
this.buttonDown=function(){l.scaleX=.9;l.scaleY=.9;h[ON_MOUSE_DOWN]&&h[ON_MOUSE_DOWN].call(q[ON_MOUSE_DOWN])};this.getSprite=function(){return l};this._init(a,d,c,b,e)}var s_iScaleFactor=1,s_bLandscape=!1,s_oCanvasLeft,s_oCanvasTop;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,
4))})(navigator.userAgent||navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}$(window).ready(function(){sizeHandler();s_bLandscape=window.innerWidth<window.innerHeight?!1:!0});window.addEventListener("resize",onOrientationChange,!1);window.addEventListener("orientationchange",onOrientationChange);
function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&(sizeHandler(),s_bLandscape=!1);window.matchMedia("(orientation: landscape)").matches&&(sizeHandler(),s_bLandscape=!0)}

function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a=CANVAS_WIDTH,b=CANVAS_HEIGHT,c,d;!0===inIframe()&&"ios"==getMobileOperatingSystem()?top.location.href=document.location.href:(c=window.innerWidth,d=window.innerHeight,multiplier=s_iScaleFactor=Math.min(d/b,c/a),a*=multiplier,b*=multiplier,$("#canvas").css("width",a+"px"),$("#canvas").css("height",b+"px"),$("#canvas").css("left",c/2-a/2+"px"),s_oCanvasLeft=$("#canvas").offset().left,s_oCanvasTop=$("#canvas").offset().top)}}
function getMobileOperatingSystem(){var a=navigator.userAgent||navigator.vendor||window.opera;return a.match(/iPad/i)||a.match(/iPhone/i)||a.match(/iPod/i)?"ios":a.match(/Android/i)?"android":"unknown"}function inIframe(){try{return window.self!==window.top}catch(a){return!0}};

function createBitmap(a,d,c){var b=new createjs.Bitmap(a),e=new createjs.Shape;d&&c?e.graphics.beginFill("#fff").drawRect(0,0,d,c):e.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);b.hitArea=e;return b}function createSprite(a,d,c,b,e,f){a=null!==d?new createjs.Sprite(a,d):new createjs.Sprite(a);d=new createjs.Shape;d.graphics.beginFill("#000000").drawRect(-c,-b,e,f);a.hitArea=d;return a}
function randomFloatBetween(a,d,c){"undefined"===typeof c&&(c=2);return parseFloat(Math.min(a+Math.random()*(d-a),d).toFixed(c))}function shuffle(a){for(var d=a.length,c,b;0!==d;)b=Math.floor(Math.random()*d),--d,c=a[d],a[d]=a[b],a[b]=c;return a}function dotProductV2(a,d){return a.x*d.x+a.y*d.y}function distanceV2(a,d){return Math.sqrt((d.x-a.x)*(d.x-a.x)+(d.y-a.y)*(d.y-a.y))}
function closestPointOnLine(a,d,c){var b={x:c.x,y:c.y};b.x-=a.x;b.y-=a.y;c={x:d.x,y:d.y};c.x-=a.x;c.y-=a.y;var e=Math.sqrt(c.x*c.x+c.y*c.y);0<e&&(c.x/=e,c.y/=e);b=dotProductV2(c,b);if(0>=b)return a;if(b>=distanceV2(a,d))return d;c.x*=b;c.y*=b;c.x+=a.x;c.y+=a.y;return c}function toRadian(a){return Math.PI/180*a}function toDegree(a){return 180/Math.PI*a}function collideEdgeWithCircle(a,d,c,b){a=closestPointOnLine(a,d,c);c=distanceV2(c,a);return b<c?!1:!0}
function rotateVector2D(a,d){var c=d.getX()*Math.cos(a)+d.getY()*Math.sin(a),b=d.getX()*-Math.sin(a)+d.getY()*Math.cos(a);return new CVector2(c,b)}
function getBounds(a,d){var c={x:Infinity,y:Infinity,width:0,height:0};if(a instanceof createjs.Container){c.x2=-Infinity;c.y2=-Infinity;var b=a.children,e=b.length,f,h;for(h=0;h<e;h++)f=getBounds(b[h],1),f.x<c.x&&(c.x=f.x),f.y<c.y&&(c.y=f.y),f.x+f.width>c.x2&&(c.x2=f.x+f.width),f.y+f.height>c.y2&&(c.y2=f.y+f.height);Infinity==c.x&&(c.x=0);Infinity==c.y&&(c.y=0);Infinity==c.x2&&(c.x2=0);Infinity==c.y2&&(c.y2=0);c.width=c.x2-c.x;c.height=c.y2-c.y;delete c.x2;delete c.y2}else{var q,l;a instanceof createjs.Bitmap?
(e=a.sourceRect||a.image,h=e.width*d,q=e.height*d):a instanceof createjs.Sprite?a.spriteSheet._frames&&a.spriteSheet._frames[a.currentFrame]&&a.spriteSheet._frames[a.currentFrame].image?(e=a.spriteSheet.getFrame(a.currentFrame),h=e.rect.width,q=e.rect.height,b=e.regX,l=e.regY):(c.x=a.x||0,c.y=a.y||0):(c.x=a.x||0,c.y=a.y||0);b=b||0;h=h||0;l=l||0;q=q||0;c.regX=b;c.regY=l;e=a.localToGlobal(0-b,0-l);f=a.localToGlobal(h-b,q-l);h=a.localToGlobal(h-b,0-l);b=a.localToGlobal(0-b,q-l);c.x=Math.min(Math.min(Math.min(e.x,
f.x),h.x),b.x);c.y=Math.min(Math.min(Math.min(e.y,f.y),h.y),b.y);c.width=Math.max(Math.max(Math.max(e.x,f.x),h.x),b.x)-c.x;c.height=Math.max(Math.max(Math.max(e.y,f.y),h.y),b.y)-c.y}return c}function binarySearch(a,d,c,b){if(c>b)return-1;var e=Math.floor((c+b)/2);return a[e].toLowerCase()===d.toLowerCase()?e:a[e].toLowerCase()>d.toLowerCase()?binarySearch(a,d,c,e-1):binarySearch(a,d,e+1,b)}function between(a,d,c){var b=!1;a<c&&d>a&&d<c&&(b=!0);a>c&&d>c&&d<a&&(b=!0);if(d===a||d===c)b=!0;return b}
function pointInRectangle(a,d,c){var b=!1,e=c.y,f=c.height;between(c.x,a,c.width)&&between(e,d,f)&&(b=!0);return b}function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3==a.nodeType&&(a=a.parentNode);var d=document.createEvent("MouseEvents");d.initEvent("click",!0,!0);a.dispatchEvent(d)}}};
(function(){function a(a){var b={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};a=a||window.event;a.type in b?document.body.className=b[a.type]:(document.body.className=this[d]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var d="hidden";d in document?document.addEventListener("visibilitychange",a):(d="mozHidden")in document?document.addEventListener("mozvisibilitychange",a):(d="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",a):(d="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a})();
function CTextButton(a,d,c,b,e,f,h,q){var l,r,n;this._init=function(a,b,c,e,f,d,h,q){l=[];r=[];var x=createBitmap(c),B=Math.ceil(h/30),t=new createjs.Text(e,h+"px "+f,"#000000");t.textAlign="center";t.textBaseline="middle";t.lineHeight=1;var z=t.getBounds();t.x=c.width/2+B;t.y=Math.floor(c.height/2)+z.height/3+B;e=new createjs.Text(e,h+"px "+f,d);e.textAlign="center";e.textBaseline="middle";e.lineHeight=1;z=e.getBounds();e.x=c.width/2;e.y=Math.floor(c.height/2)+z.height/3;n=new createjs.Container;
n.x=a;n.y=b;n.regX=c.width/2;n.regY=c.height/2;n.addChild(x,t,e);!1!==q&&s_oStage.addChild(n);this._initListener()};this.unload=function(){n.off("mousedown");n.off("pressup");s_oStage.removeChild(n)};this.setVisible=function(a){n.visible=a};this._initListener=function(){oParent=this;n.on("mousedown",this.buttonDown);n.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){l[a]=b;r[a]=c};this.buttonRelease=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");
n.scaleX=1;n.scaleY=1;l[ON_MOUSE_UP]&&l[ON_MOUSE_UP].call(r[ON_MOUSE_UP])};this.buttonDown=function(){n.scaleX=.9;n.scaleY=.9;l[ON_MOUSE_DOWN]&&l[ON_MOUSE_DOWN].call(r[ON_MOUSE_DOWN])};this.setPosition=function(a,b){n.x=a;n.y=b};this.setX=function(a){n.x=a};this.setY=function(a){n.y=a};this.getButtonImage=function(){return n};this.getX=function(){return n.x};this.getY=function(){return n.y};this.getSprite=function(){return n};this._init(a,d,c,b,e,f,h,q);return this}
function CStain(a,d,c,b){var e,f;this._init=function(a,b,c,d){f=d;c=s_oSpriteLibrary.getSprite("stain_"+c);e=createBitmap(c);e.x=a;e.y=b;e.regX=c.width/2;e.regY=c.height/2;f.addChild(e);var n=this;createjs.Tween.get(e).wait(1E3).to({alpha:0},1E3).call(function(){n.unload()})};this.unload=function(){f.removeChild(e)};this._init(a,d,c,b)}
function CPreloader(){var a,d,c,b,e,f;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_preloader","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("preloader_bar","./sprites/preloader_bar.png");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.loadSprites();f=new createjs.Container;s_oStage.addChild(f)};this.unload=function(){f.removeAllChildren()};this._onImagesLoaded=function(){};
this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var h=new createBitmap(s_oSpriteLibrary.getSprite("bg_preloader"));f.addChild(h);c=createBitmap(s_oSpriteLibrary.getSprite("preloader_bar"));c.x=140;c.y=950;f.addChild(c);b=createBitmap(s_oSpriteLibrary.getSprite("progress_bar"));b.x=141;b.y=951;f.addChild(b);a=476;e=new createjs.Shape;e.graphics.beginFill("rgba(255,0,0,0.01)").drawRect(141,951,1,30);f.addChild(e);b.mask=e;d=new createjs.Text("",
"40px katanaregular","#fff");d.x=CANVAS_WIDTH/2;d.y=970;d.textAlign="center";d.textBaseline="middle";f.addChild(d)};this.refreshLoader=function(b){d.text=b+"%";b=Math.floor(b*a/100);e.graphics.clear();e.graphics.beginFill("rgba(255,0,0,0.01)").drawRect(141,951,b,30)};this._init()}
function CMenu(){var a,d,c,b;this._init=function(){a=new createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(a);var e=s_oSpriteLibrary.getSprite("but_play");d=new CTextButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-80,e,TEXT_PLAY,"katanaregular","#ffc600",60);d.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)e=s_oSpriteLibrary.getSprite("audio_icon"),b=new CToggle(CANVAS_WIDTH-e.height/2-10,e.height/2+10,e,s_bAudioActive,!0),b.addEventListener(ON_MOUSE_UP,
this._onAudioToggle,this),null===s_oSoundTrack&&(s_oSoundTrack=createjs.Sound.play("soundtrack",{loop:-1,volume:SOUNDTRACK_VOLUME}));c=new createjs.Shape;c.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(c);createjs.Tween.get(c).to({alpha:0},1E3).call(function(){c.visible=!1})};this.unload=function(){d.unload();d=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)b.unload(),b=null;s_oStage.removeAllChildren()};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);
s_bAudioActive=!s_bAudioActive};this._onButPlayRelease=function(){s_oMenu.unload();s_oMain.gotoGame()};s_oMenu=this;this._init()}var s_oMenu;
function CMain(a){var d,c=0,b=0,e=STATE_LOADING,f,h,q;this.initContainer=function(){var a=document.getElementById("canvas");s_oStage=new createjs.Stage(a);s_oCanvas=a;s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&(s_oStage.enableMouseOver(20),$("body").on("contextmenu","#canvas",function(a){return!1}));createjs.Touch.enable(s_oStage);s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.setFPS(35);navigator.userAgent.match(/Windows Phone/i)&&(DISABLE_SOUND_MOBILE=
!0);s_oSpriteLibrary=new CSpriteLibrary;h=new CPreloader};this.preloaderReady=function(){this._loadImages();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds();d=!0};this.soundLoaded=function(){c++;c===b&&(h.unload(),this.gotoMenu())};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&(0<navigator.userAgent.indexOf("Opera")||0<navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=["mp3"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,
this)),createjs.Sound.registerSound("./sounds/click.ogg","click"),createjs.Sound.registerSound("./sounds/gameover.ogg","gameover"),createjs.Sound.registerSound("./sounds/soundtrack.ogg","soundtrack"),createjs.Sound.registerSound("./sounds/explosion.ogg","explosion"),createjs.Sound.registerSound("./sounds/fruit_slice_1.ogg","fruit_slice_1",3),createjs.Sound.registerSound("./sounds/fruit_slice_2.ogg","fruit_slice_2",3),createjs.Sound.registerSound("./sounds/fruit_slice_3.ogg","fruit_slice_3",3),createjs.Sound.registerSound("./sounds/bomb_fuse.ogg",
"bomb_fuse"),createjs.Sound.registerSound("./sounds/boing_fruit.ogg","boing_fruit"),createjs.Sound.registerSound("./sounds/combo.ogg","combo")):(createjs.Sound.alternateExtensions=["ogg"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/click.mp3","click"),createjs.Sound.registerSound("./sounds/gameover.mp3","gameover"),createjs.Sound.registerSound("./sounds/soundtrack.mp3","soundtrack"),createjs.Sound.registerSound("./sounds/explosion.mp3",
"explosion"),createjs.Sound.registerSound("./sounds/fruit_slice_1.mp3","fruit_slice_1",3),createjs.Sound.registerSound("./sounds/fruit_slice_2.mp3","fruit_slice_2",3),createjs.Sound.registerSound("./sounds/fruit_slice_3.mp3","fruit_slice_3",3),createjs.Sound.registerSound("./sounds/bomb_fuse.mp3","bomb_fuse"),createjs.Sound.registerSound("./sounds/boing_fruit.mp3","boing_fruit"),createjs.Sound.registerSound("./sounds/combo.mp3","combo")),b+=10)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,
this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("gameover_bg","./sprites/gameover_bg.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("help_bg","./sprites/help_bg.png");s_oSpriteLibrary.addSprite("hit_area",
"./sprites/hit_area.png");s_oSpriteLibrary.addSprite("bomb","./sprites/bomb.png");s_oSpriteLibrary.addSprite("bomb_ray","./sprites/bomb_ray.png");s_oSpriteLibrary.addSprite("life","./sprites/life.png");s_oSpriteLibrary.addSprite("miss","./sprites/miss.png");for(var a=0;a<NUM_FRUITS;a++)s_oSpriteLibrary.addSprite("fruit_"+a,"./sprites/fruit_"+a+".png"),s_oSpriteLibrary.addSprite("stain_"+a,"./sprites/stain_"+a+".png");b+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=
function(){c++;h.refreshLoader(Math.floor(c/b*100));c===b&&(h.unload(),this.gotoMenu())};this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this.gotoMenu=function(){new CMenu;e=STATE_MENU};this.gotoGame=function(){q=new CGame(f);e=STATE_GAME;$(s_oMain).trigger("game_start")};this.gotoHelp=function(){new CHelpPanel;e=STATE_HELP};this.stopUpdate=function(){d=!1};this.startUpdate=function(){d=!0};this._update=function(a){if(!1!==d){var b=(new Date).getTime();
s_iTimeElaps=b-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=b;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);e===STATE_GAME&&q.update();s_oStage.update(a)}};s_oMain=this;f=a;this.initContainer()}var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oDrawLayer,s_oStage,s_oMain,s_oCanvas,s_oSpriteLibrary,s_oSoundTrack=null;
function CLineDrawing(a,d,c){var b,e;this._init=function(a,c,d){b=new createjs.Graphics;b.setStrokeStyle(5);b.beginStroke("rgba(0,0,0,1)");b.moveTo(a,c);e=new createjs.Shape(b);d.addChild(e)};this.hide=function(){createjs.Tween.get(e).to({alpha:0},1E3).call(function(){b.clear()})};this.updateDraw=function(a,c){b.lineTo(a,c)};this._init(a,d,c)}TEXT_LOSE="GAME OVER";TEXT_WIN="CONGRATULATIONS!!!";TEXT_SCORE="SCORE";TEXT_PLAY="PLAY";TEXT_RESTART="RESTART";TEXT_EXIT="EXIT";TEXT_GAMEOVER="GAME OVER";
TEXT_COMBO="COMBO";TEXT_HELP="CUT THE FRUITS WITH THE MOUSE CURSOR AND AVOID THE BOMBS!";TEXT_HELP_MOBILE="CUT THE FRUITS WITH THE FINGER AND AVOID THE BOMBS!";
function CInterface(){var a,d,c,b;this._init=function(){var e=new createBitmap(s_oSpriteLibrary.getSprite("life"));e.x=20;e.y=20;s_oStage.addChild(e);a=new createjs.Text("X"+NUM_LIVES,"40px katanaregular","#FFCC00");a.x=120;a.y=40;a.textAlign="center";a.textBaseline="middle";s_oStage.addChild(a);c=new createjs.Text(TEXT_SCORE+" 0","40px katanaregular","#FFCC00");c.x=CANVAS_WIDTH/2;c.y=45;c.textAlign="center";c.textBaseline="middle";s_oStage.addChild(c);e=s_oSpriteLibrary.getSprite("but_exit");d=new CGfxButton(CANVAS_WIDTH-
e.height/2-6,6+e.height/2,e,!0);d.addEventListener(ON_MOUSE_UP,this._onExit,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)e=s_oSpriteLibrary.getSprite("audio_icon"),b=new CToggle(CANVAS_WIDTH-e.height/2-80,e.height/2+6,e,s_bAudioActive),b.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this)};this.unload=function(){d.unload();d=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)b.unload(),b=null};this.loseLife=function(b){a.text="X"+b};this.refreshScore=function(a){c.text=TEXT_SCORE+" "+a};this._onAudioToggle=
function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onExit=function(){s_oGame.onExit()};this._init();return this}
function CHitArea(a,d,c){var b,e,f;this._init=function(a,c,d){b=[];e=[];f=new createBitmap(d);f.x=a;f.y=c;f.regX=d.width/2;f.regY=d.height/2;s_oStage.addChild(f);this._initListener()};this.unload=function(){f.off("mousedown",this.buttonDown);f.off("pressup",this.buttonRelease);f.off("pressmove",this.onPressMove);!1===s_bMobile&&(f.off("mouseover",this.buttonOver),f.off("mouseout",this.buttonOut));s_oStage.removeChild(f)};this.setVisible=function(a){f.visible=a};this._initListener=function(){f.on("mousedown",
this.buttonDown);f.on("pressup",this.buttonRelease);f.on("pressmove",this.onPressMove);!1===s_bMobile&&(f.on("mouseover",this.buttonOver),f.on("mouseout",this.buttonOut))};this.addEventListener=function(a,c,d){b[a]=c;e[a]=d};this.buttonRelease=function(a){f.scaleX=1;f.scaleY=1;b[ON_MOUSE_UP]&&b[ON_MOUSE_UP].call(e[ON_MOUSE_UP],{event:a})};this.buttonDown=function(a){f.scaleX=.9;f.scaleY=.9;b[ON_MOUSE_DOWN]&&b[ON_MOUSE_DOWN].call(e[ON_MOUSE_DOWN],{event:a})};this.onPressMove=function(a){b[ON_PRESS_MOVE]&&
b[ON_PRESS_MOVE].call(e[ON_PRESS_MOVE],{event:a})};this.buttonOver=function(){b[ON_MOUSE_OVER]&&b[ON_MOUSE_OVER].call(e[ON_MOUSE_OVER])};this.buttonOut=function(){b[ON_MOUSE_OUT]&&b[ON_MOUSE_OUT].call(e[ON_MOUSE_OUT])};this.setPosition=function(a,b){f.x=a;f.y=b};this.setX=function(a){f.x=a};this.setY=function(a){f.y=a};this.getSprite=function(){return f};this.getX=function(){return f.x};this.getY=function(){return f.y};this._init(a,d,c);return this}
function CHelpPanel(){var a,d,c,b;this._init=function(){d=new createBitmap(s_oSpriteLibrary.getSprite("help_bg"));a=new createjs.Text(s_bMobile?TEXT_HELP_MOBILE:TEXT_HELP,"70px katanaregular","#FFCC00");a.x=CANVAS_WIDTH/2;a.y=420;a.textAlign="center";a.textBaseline="alphabetic";a.lineHeight=70;a.lineWidth=560;a.shadow=new createjs.Shadow("#000",2,2,2);var e=s_oSpriteLibrary.getSprite("but_play");c=new CTextButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-280,e,TEXT_PLAY,"katanaregular","#ffc600",60,!1);c.addEventListener(ON_MOUSE_UP,
this._onExit,this);b=new createjs.Container;b.addChild(d,a,c.getSprite());s_oStage.addChild(b)};this.unload=function(){c.unload();b.removeAllChildren()};this._onExit=function(){this.unload();s_oGame.exitFromHelp()};this._init()}
function CGfxButton(a,d,c){var b,e,f;this._init=function(a,c,d){b=[];e=[];f=new createBitmap(d);f.x=a;f.y=c;f.regX=d.width/2;f.regY=d.height/2;s_oStage.addChild(f);this._initListener()};this.unload=function(){f.off("mousedown",this.buttonDown);f.off("pressup",this.buttonRelease);f.off("pressmove",this.onPressMove);!1===s_bMobile&&(f.off("mouseover",this.buttonOver),f.off("mouseout",this.buttonOut));s_oStage.removeChild(f)};this.setVisible=function(a){f.visible=a};this._initListener=function(){f.on("mousedown",
this.buttonDown);f.on("pressup",this.buttonRelease);f.on("pressmove",this.onPressMove);!1===s_bMobile&&(f.on("mouseover",this.buttonOver),f.on("mouseout",this.buttonOut))};this.addEventListener=function(a,c,d){b[a]=c;e[a]=d};this.buttonRelease=function(a){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");f.scaleX=1;f.scaleY=1;b[ON_MOUSE_UP]&&b[ON_MOUSE_UP].call(e[ON_MOUSE_UP],{event:a})};this.buttonDown=function(a){f.scaleX=.9;f.scaleY=.9;b[ON_MOUSE_DOWN]&&b[ON_MOUSE_DOWN].call(e[ON_MOUSE_DOWN],
{event:a})};this.onPressMove=function(a){b[ON_PRESS_MOVE]&&b[ON_PRESS_MOVE].call(e[ON_PRESS_MOVE],{event:a})};this.buttonOver=function(){b[ON_MOUSE_OVER]&&b[ON_MOUSE_OVER].call(e[ON_MOUSE_OVER])};this.buttonOut=function(){b[ON_MOUSE_OUT]&&b[ON_MOUSE_OUT].call(e[ON_MOUSE_OUT])};this.setPosition=function(a,b){f.x=a;f.y=b};this.setX=function(a){f.x=a};this.setY=function(a){f.y=a};this.getSprite=function(){return f};this.getX=function(){return f.x};this.getY=function(){return f.y};this._init(a,d,c);return this}
function CGame(a){var d=!1,c=!1,b,e,f,h,q,l,r,n,G,A,w,E,D,p=[],F=[],v,x,B,t,z,C,k,m,u,g=null,y,H,I,J=null;this._init=function(){D=E=f=0;l=NUM_LIVES;G=n=OCCURENCE_FRUIT;r=STARTING_SIMULTANEOUS_FRUITS;w=0;y=new createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(y);k=new createjs.Container;s_oStage.addChild(k);m=new createjs.Container;s_oStage.addChild(m);C=new createjs.Container;s_oStage.addChild(C);g=new createjs.Shape;C.addChild(g);s_bMobile?window.navigator.msPointerEnabled?(s_oCanvas.addEventListener("MSPointerDown",
this.onTouchStartMS,!1),s_oCanvas.addEventListener("MSPointerMove",this.onTouchMoveMS,!1),s_oCanvas.addEventListener("MSPointerUp",this.onTouchEndMS,!1)):(s_oCanvas.addEventListener("touchstart",this.onTouchStart,!1),s_oCanvas.addEventListener("touchmove",this.onTouchMove,!1),s_oCanvas.addEventListener("touchend",this.onTouchEnd,!1)):(H=new CHitArea(CANVAS_WIDTH/2,CANVAS_HEIGHT/2,s_oSpriteLibrary.getSprite("hit_area")),H.addEventListener(ON_MOUSE_DOWN,this._onMouseDown,this),H.addEventListener(ON_MOUSE_UP,
this._onMouseUp,this),H.addEventListener(ON_MOUSE_OUT,this._onMouseOut,this),H.addEventListener(ON_PRESS_MOVE,this._onMouseMoving,this));I=new CInterface;J=CEndPanel();new CHelpPanel;x=[];for(var a=Math.floor(CANVAS_WIDTH/30),c=20;c<CANVAS_WIDTH-20;)x.push(c),c+=a;v=[];e=b=!1};this.unload=function(){c=!0;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)createjs.Sound.stop(),s_oSoundTrack=null;s_bMobile?window.navigator.msPointerEnabled?(s_oCanvas.removeEventListener("MSPointerDown",this.onTouchStartMS,
!1),s_oCanvas.removeEventListener("MSPointerMove",this.onTouchMoveMS,!1),s_oCanvas.removeEventListener("MSPointerUp",this.onTouchEndMS,!1)):(s_oCanvas.removeEventListener("touchstart",this.onTouchStart,!1),s_oCanvas.removeEventListener("touchmove",this.onTouchMove,!1),s_oCanvas.removeEventListener("touchend",this.onTouchEnd,!1)):H.unload();J&&J.unload();I.unload();s_oStage.removeAllChildren()};this.exitFromHelp=function(){d=!0};this.loseLife=function(a){var b=s_oSpriteLibrary.getSprite("miss"),c=
createBitmap(b);c.alpha=0;c.x=a.getX();c.y=CANVAS_HEIGHT-b.height;c.regX=b.width/2;C.addChild(c);0>c.x?c.x=b.width/2:c.x>CANVAS_WIDTH&&(c.x=CANVAS_WIDTH-b.width/2);createjs.Tween.get(c).to({alpha:1},500).call(function(){createjs.Tween.get(c).wait(1500).to({alpha:0},500)});l--;I.loseLife(l);0===l&&this.gameOver()};this.gameOver=function(){if(!c){d=!1;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)u=createjs.Sound.play("gameover"),u.addEventListener("complete",this.gameOVerSfxComplete),s_oSoundTrack.setVolume(0);
this.removeAllLines();J.show(f)}};this.gameOVerSfxComplete=function(){s_oSoundTrack.setVolume(SOUNDTRACK_VOLUME)};this.showCombo=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("combo");var a=COMBO_TWO_FRUIT*D;f+=a;I.refreshScore(f);var b=new createjs.Shape;b.alpha=0;b.graphics.beginFill("#fffC00").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);C.addChild(b);createjs.Tween.get(b).to({alpha:.8},200).call(function(){createjs.Tween.get(b).to({alpha:0},200).call(function(){C.removeChild(b)})});
var c=Math.floor(Math.random()*s_aFruitColors.length),d=new createjs.Text(TEXT_COMBO+"\n+"+a,"60px katanaregular",s_aFruitColors[c]);d.alpha=0;d.x=z.x;d.y=z.y;d.shadow=new createjs.Shadow("#000",2,2,2);d.textAlign="center";d.textBaseline="middle";m.addChild(d);createjs.Tween.get(d).to({alpha:1},500).call(function(){createjs.Tween.get(d).wait(1500).to({alpha:0},500)})};this.launchFruit=function(){for(var a=Math.random()*(r-1)+1,b=0;b<a;b++){var c=Math.floor(Math.random()*x.length),d=Math.floor(Math.random()*
s_aFruitSpriteSheet.length),c=d===BOMB_SYMBOL?new CBomb(x[c],Y_START_FRUIT,s_aFruitSpriteSheet[d],s_aFruitSize[d],s_aFruitSpeed[d],d,m):new CFruit(x[c],Y_START_FRUIT,s_aFruitSpriteSheet[d],s_aFruitSize[d],s_aFruitSpeed[d],d,m);p.push(c)}if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)_oIdleSfx=createjs.Sound.play("boing_fruit")};this.onExit=function(){this.unload();s_oMain.gotoMenu();$(s_oMain).trigger("restart")};this._onMouseDown=function(a){!0!==b&&(b=!0,A=0,a=a.event,a||(a=window.event),h=a.stageX,
q=a.stageY,t=B={x:a.stageX,y:a.stageY},g.uncache(),g.graphics.setStrokeStyle(10,"round",0,0).beginStroke("#fff"),g.graphics.moveTo(t.x,t.y))};this._onMouseUp=function(){e=b=!1;g.graphics.clear();g.cache(0,0,CANVAS_WIDTH,CANVAS_HEIGHT)};this._onMouseMoving=function(a){a=a.event;a||(a=window.event);h=a.stageX;q=a.stageY};this._onMouseOut=function(){b&&this._onMouseUp()};this.onTouchStart=function(a){b=!0;A=0;h=parseInt((a.touches[0].pageX-s_oCanvasLeft)/s_iScaleFactor);q=parseInt((a.touches[0].pageY-
s_oCanvasTop)/s_iScaleFactor);t=B={x:h,y:q};g.uncache();g.graphics.setStrokeStyle(10,"round",0,0).beginStroke("#fff");g.graphics.moveTo(t.x,t.y)};this.onTouchMove=function(a){a.preventDefault();h=parseInt((a.touches[0].pageX-s_oCanvasLeft)/s_iScaleFactor);q=parseInt((a.touches[0].pageY-s_oCanvasTop)/s_iScaleFactor)};this.onTouchEnd=function(a){e=b=!1;g.graphics.clear();g.cache(0,0,CANVAS_WIDTH,CANVAS_HEIGHT)};this.onTouchStartMS=function(a){if(!window.navigator.msPointerEnabled||a.isPrimary)b=!0,
A=0,h=parseInt(((a.pageX||a.targetTouches[0].pageX)-s_oCanvasLeft)/s_iScaleFactor),q=parseInt(((a.pageY||a.targetTouches[0].pageY)-s_oCanvasTop)/s_iScaleFactor),t=B={x:h,y:q},g.uncache(),g.graphics.setStrokeStyle(10,"round",0,0).beginStroke("#fff"),g.graphics.moveTo(t.x,t.y)};this.onTouchMoveMS=function(a){if(!window.navigator.msPointerEnabled||a.isPrimary)a.preventDefault(),h=parseInt(((a.pageX||a.targetTouches[0].pageX)-s_oCanvasLeft)/s_iScaleFactor),q=parseInt(((a.pageY||a.targetTouches[0].pageY)-
s_oCanvasTop)/s_iScaleFactor)};this.onTouchEndMS=function(a){e=b=!1;g.graphics.clear();g.cache(0,0,CANVAS_WIDTH,CANVAS_HEIGHT)};this.showExplosion=function(){var a=new createjs.Shape;a.alpha=0;a.graphics.beginFill("#fff").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);C.addChild(a);createjs.Tween.get(a).to({alpha:1},1E3).call(function(){s_oGame.gameOver();m.removeAllChildren();createjs.Tween.get(a).to({alpha:0},1500).call(function(){C.removeChild(a)})})};this.bombExplosion=function(a){p[a].explode()};this.assignScore=
function(a,b){new CStain(a.getX(),a.getY(),b,k);new CWinText(a.getX(),a.getY(),s_aFruitScore[b],s_aFruitColors[b]);f+=s_aFruitScore[b];I.refreshScore(f);E++;0===E%FRUIT_TO_CUT_FOR_LEVEL_UP&&(r++,r>MAX_SIMULTANEOUS_FRUITS&&(r=MAX_SIMULTANEOUS_FRUITS));D++;z={x:a.getX(),y:a.getY()}};this.removeSlices=function(a){for(var b=0;b<p.length;b++)p[b]===a&&F.push(a)};this.removeAllLines=function(){for(var a=0;a<v.length;a++)C.removeChild(v[a].line);v=[]};this.dotProductV2=function(a,b){return a.getX()*b.getX()+
a.getY()*b.getY()};this.distanceV2=function(a,b){return Math.sqrt((b.getX()-a.getX())*(b.getX()-a.getX())+(b.getY()-a.getY())*(b.getY()-a.getY()))};this.distance=function(a,b){return(b.getX()-a.getX())*(b.getX()-a.getX())+(b.getY()-a.getY())*(b.getY()-a.getY())};this.closestPointOnLine=function(a,b,c){var d=new CVector2;d.setV(c);d.subV(a);c=new CVector2;c.setV(b);c.subV(a);c.normalize();d=this.dotProductV2(c,d);if(0>=d)return a;if(d>=this.distanceV2(a,b))return b;c.scalarProduct(d);c.addV(a);return c};
this.collideEdgeWithCircle=function(a,b,c,d){a=this.closestPointOnLine(a,b,c);c=this.distanceV2(c,a);return d<c?!1:!0};this.getCircleLineIntersectionPoint=function(a,b,c,d){var e=b.getX()-a.getX();b=b.getY()-a.getY();var f=c.getX()-a.getX(),g=c.getY()-a.getY(),h=e*e+b*b;c=(e*f+b*g)/h;d=c*c-(f*f+g*g-d*d)/h;if(0>d)return null;g=Math.sqrt(d);f=-c+g;c=-c-g;f=new CVector2(a.getX()-e*f,a.getY()-b*f);if(0===d)return Array(f);a=new CVector2(a.getX()-e*c,a.getY()-b*c);return[f,a]};this.angleBetweenVectors=
function(a,b){var c=Math.acos(this.dotProductV2(a,b)/(a.length()*b.length()));return!0===isNaN(c)?0:c};this.checkCollisionWithFruit=function(){if(0!==v.length)for(var a=0;a<p.length;a++)if(!1===p[a].isSliced())for(var b=0;b<v.length;b++)if(this.collideEdgeWithCircle(v[b].start_point,v[b].end_point,p[a].getCenter(),p[a].getRadius())){var c=this.getCircleLineIntersectionPoint(v[b].start_point,v[b].end_point,p[a].getCenter(),p[a].getRadius()),e=!0;if(null!==c&&1<c.length)for(var f=c[0],g=1;g<c.length;g++)if(this.distance(f,
c[g])>p[a].getSliceOffset()){if(p[a].getType()===BOMB_SYMBOL){d=!1;this.bombExplosion(a);return}e=new CVector2(c[g].getX(),c[g].getY());e.subV(f);f=p[a].getVectorDir();f=this.angleBetweenVectors(e,f);f=toDegree(f);e=p[a].getCenter();30>f?p[a].sliceVertical():60>f?e.getX()>c[g].getX()?p[a].sliceDiagonalLeft():p[a].sliceDiagonalRight():120>f?p[a].sliceHorizontal():150>f?e.getX()>c[g].getX()?p[a].sliceDiagonalRight():p[a].sliceDiagonalLeft():p[a].sliceVertical();this.assignScore(p[a].getCenter(),p[a].getType());
e=!1;break}if(!1===e)break}};this.update=function(){if(!1!==d){G+=s_iTimeElaps;G>n&&(G=0,this.launchFruit());F=[];for(var a=0;a<p.length;a++)p[a].update(),!1===p[a].isSliced()&&p[a].getY()>Y_START_FRUIT&&(F.push(p[a]),p[a].getType()!==BOMB_SYMBOL&&this.loseLife(p[a]));for(a=0;a<F.length;a++)for(var c=0;c<p.length;c++)if(F[a]===p[c]){F[a].unload();p.splice(c,1);break}if(b){if(t.x!==h||t.y!==q)A+=s_iTimeElaps,A>LINE_DRAW_INTERVAL&&(A=0,v.push({line:g,start_point:new CVector2(B.x,B.y),end_point:new CVector2(t.x,
t.y)}),g=new createjs.Shape,C.addChild(g),g.graphics.setStrokeStyle(10,"round",0,0).beginStroke("#fff"),g.graphics.moveTo(t.x,t.y),B={x:t.x,y:t.y});0<v.length&&!1===e&&(e=!0,createjs.Tween.get(v[0].line).to({alpha:0},LINE_DRAW_INTERVAL).call(function(){0<v.length&&(C.removeChild(v[0].line),v.splice(0,1));e=!1}));t={x:h,y:q};g.graphics.lineTo(t.x,t.y)}else if(0<v.length&&!1===e){e=!0;for(var f=this,a=0;a<v.length;a++)createjs.Tween.get(v[a].line).wait(120).to({alpha:0},200).call(function(){f.removeAllLines()})}this.checkCollisionWithFruit();
w+=s_iTimeElaps;w>TIME_FOR_COMBO&&(1<D&&this.showCombo(),w=D=0)}};s_oGame=this;Y_START_FRUIT=a.fruit_start;OCCURENCE_FRUIT=a.occurence_fruit;MAX_FRUIT_ROT_SPEED=a.max_fruit_rot_speed;NUM_LIVES=a.num_lives;STARTING_SIMULTANEOUS_FRUITS=a.start_sim_fruit;MAX_SIMULTANEOUS_FRUITS=a.max_sim_fruits;FRUIT_TO_CUT_FOR_LEVEL_UP=a.fruits_for_level_up;TIME_FOR_COMBO=a.time_for_combo;COMBO_TWO_FRUIT=a.combo_points;new CFruitSettings;this._init()}var s_oGame;
function CFruitSettings(){this._init=function(){s_aFruitSpriteSheet=[];s_aFruitSize=[];s_aFruitSpeed=[];s_aFruitColors=[];s_aFruitScore=[];s_aFruitSpliceSound=[];var a=s_oSpriteLibrary.getSprite("fruit_0"),a={framerate:8,images:[a],frames:{width:90,height:103,regX:45,regY:51},animations:{idle:[0],slice_1:[1],slice_2:[2],slice_3:[3],slice_4:[4],slice_5:[5],slice_6:[6],slice_7:[7],slice_8:[8]}};s_aFruitSpriteSheet[0]=new createjs.SpriteSheet(a);s_aFruitSize[0]={width:90,height:103,regX:45,regY:51};
s_aFruitSpeed[0]=20;s_aFruitColors[0]="#fdc06f";s_aFruitScore[0]=20;s_aFruitSpliceSound[0]="fruit_slice_2";a=s_oSpriteLibrary.getSprite("fruit_1");a={framerate:8,images:[a],frames:{width:90,height:103,regX:45,regY:51},animations:{idle:[0],slice_1:[1],slice_2:[2],slice_3:[3],slice_4:[4],slice_5:[5],slice_6:[6],slice_7:[7],slice_8:[8]}};s_aFruitSpriteSheet[1]=new createjs.SpriteSheet(a);s_aFruitSize[1]={width:90,height:103,regX:45,regY:51};s_aFruitSpeed[1]=24;s_aFruitColors[1]="#cc0001";s_aFruitScore[1]=
30;s_aFruitSpliceSound[1]="fruit_slice_1";a=s_oSpriteLibrary.getSprite("fruit_2");a={framerate:8,images:[a],frames:{width:100,height:122,regX:50,regY:61},animations:{idle:[0],slice_1:[1],slice_2:[2],slice_3:[3],slice_4:[4],slice_5:[5],slice_6:[6],slice_7:[7],slice_8:[8]}};s_aFruitSpriteSheet[2]=new createjs.SpriteSheet(a);s_aFruitSize[2]={width:100,height:122,regX:50,regY:61};s_aFruitSpeed[2]=24;s_aFruitColors[2]="#74542d";s_aFruitScore[2]=40;s_aFruitSpliceSound[2]="fruit_slice_1";a=s_oSpriteLibrary.getSprite("fruit_3");
a={framerate:8,images:[a],frames:{width:87,height:90,regX:43,regY:45},animations:{idle:[0],slice_1:[1],slice_2:[2],slice_3:[3],slice_4:[4],slice_5:[5],slice_6:[6],slice_7:[7],slice_8:[8]}};s_aFruitSpriteSheet[3]=new createjs.SpriteSheet(a);s_aFruitSize[3]={width:87,height:90,regX:43,regY:45};s_aFruitSpeed[3]=18;s_aFruitColors[3]="#fd6909";s_aFruitScore[3]=30;s_aFruitSpliceSound[3]="fruit_slice_3";a=s_oSpriteLibrary.getSprite("fruit_4");a={framerate:8,images:[a],frames:{width:83,height:105,regX:41,
regY:52},animations:{idle:[0],slice_1:[1],slice_2:[2],slice_3:[3],slice_4:[4],slice_5:[5],slice_6:[6],slice_7:[7],slice_8:[8]}};s_aFruitSpriteSheet[4]=new createjs.SpriteSheet(a);s_aFruitSize[4]={width:83,height:105,regX:41,regY:52};s_aFruitSpeed[4]=18;s_aFruitColors[4]="#e8e570";s_aFruitScore[4]=30;s_aFruitSpliceSound[4]="fruit_slice_1";a=s_oSpriteLibrary.getSprite("fruit_5");a={framerate:8,images:[a],frames:{width:200,height:200,regX:100,regY:100},animations:{idle:[0],slice_1:[1],slice_2:[2],slice_3:[3],
slice_4:[4],slice_5:[5],slice_6:[6],slice_7:[7],slice_8:[8]}};s_aFruitSpriteSheet[5]=new createjs.SpriteSheet(a);s_aFruitSize[5]={width:200,height:200,regX:100,regY:100};s_aFruitSpeed[5]=18;s_aFruitColors[5]="#6da818";s_aFruitScore[5]=10;s_aFruitSpliceSound[5]="fruit_slice_3";a=s_oSpriteLibrary.getSprite("bomb");a={framerate:10,images:[a],frames:{width:150,height:150},animations:{idle:[0,1,"idle"]}};s_aFruitSpriteSheet[6]=new createjs.SpriteSheet(a);s_aFruitSize[6]={width:150,height:150,regX:0,regY:0};
s_aFruitSpeed[6]=20;s_aFruitColors[6]="#fff";s_aFruitScore[6]=0;s_aFruitSpliceSound[6]="explosion"};this._init()}var s_aFruitSpriteSheet,s_aFruitSize,s_aFruitSpeed,s_aFruitColors,s_aFruitScore,s_aFruitSpliceSound;
function CFruit(a,d,c,b,e,f,h){var q,l,r,n,G,A,w=0,E,D,p,F,v=0,x=0,B,t,z,C,k,m,u,g,y;this._init=function(a,b,c,d,e,f,g){y=g;k=createSprite(c,"idle",d.regX,d.regY,d.width,d.height);k.x=a;k.y=b;y.addChild(k);q=!1;z=d;l=z.width<z.height?Math.floor(z.width/2):Math.floor(z.height/2);B=Math.floor(1*l);B=Math.pow(B,2);A=e;E=A/9;r=a>CANVAS_WIDTH/2?randomFloatBetween(-.5,0,2):randomFloatBetween(0,.5,2);D=randomFloatBetween(-MAX_FRUIT_ROT_SPEED,MAX_FRUIT_ROT_SPEED,2);C=new CVector2(0,-1);t=f};this.unload=function(){y.removeChild(k)};
this.setInfoAfterSlice=function(){q=!0;90<k.rotation?(v=w+2*E,x=w-2*E,n=r+.1,G=r-.1,p=1.2*D,F=1.2*-D):(v=w-2*E,x=w+2*E,n=r-.1,G=r+.1,p=1.2*-D,F=1.2*D);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play(s_aFruitSpliceSound[t])};this.sliceDiagonalRight=function(){this.setInfoAfterSlice();m=createSprite(c,"slice_1",b.regX,b.regY,b.width,b.height);m.x=k.x;m.y=k.y;m.rotation=k.rotation;y.addChild(m);u=createSprite(c,"slice_2",b.regX,b.regY,b.width,b.height);u.x=k.x;u.y=k.y;u.rotation=k.rotation;
y.addChild(u);g.unload()};this.sliceDiagonalLeft=function(){this.setInfoAfterSlice();m=createSprite(c,"slice_3",b.regX,b.regY,b.width,b.height);m.x=k.x;m.y=k.y;m.rotation=k.rotation;y.addChild(m);u=createSprite(c,"slice_4",b.regX,b.regY,b.width,b.height);u.x=k.x;u.y=k.y;u.rotation=k.rotation;y.addChild(u);g.unload()};this.sliceVertical=function(){this.setInfoAfterSlice();m=createSprite(c,"slice_5",b.regX,b.regY,b.width,b.height);m.x=k.x;m.y=k.y;m.rotation=k.rotation;y.addChild(m);u=createSprite(c,
"slice_6",b.regX,b.regY,b.width,b.height);u.x=k.x;u.y=k.y;u.rotation=k.rotation;y.addChild(u);g.unload()};this.sliceHorizontal=function(){this.setInfoAfterSlice();m=createSprite(c,"slice_7",b.regX,b.regY,b.width,b.height);m.x=k.x;m.y=k.y;m.rotation=k.rotation;y.addChild(m);u=createSprite(c,"slice_8",b.regX,b.regY,b.width,b.height);u.x=k.x;u.y=k.y;u.rotation=k.rotation;y.addChild(u);g.unload()};this.getCenter=function(){return new CVector2(k.x,k.y)};this.getRadius=function(){return l};this.getSliceOffset=
function(){return B};this.getX=function(){return k.x};this.getY=function(){return k.y};this.getSprite=function(){return k};this.getRotation=function(){return k.rotation};this.getVectorDir=function(){return rotateVector2D(toRadian(-k.rotation),C)};this.isSliced=function(){return q};this.getType=function(){return t};this.update=function(){w+=E;if(!1===q)k.y=k.y-A+w*w/1E3,k.x+=.1*w*r,k.rotation+=D;else{v+=E;m.y=m.y-A+v*v/1E3;m.x+=.1*w*n;m.rotation+=p;x+=E;u.y=u.y-A+x*x/1E3;u.x+=.1*w*G;u.rotation+=F;
var a=0;m.y>Y_START_FRUIT&&(y.removeChild(m),a++);u.y>Y_START_FRUIT&&(y.removeChild(m),a++);2===a&&s_oGame.removeSlices(this)}};g=this;this._init(a,d,c,b,e,f,h)}
function CEndPanel(){var a,d,c,b,e;this._init=function(){a=createBitmap(s_oSpriteLibrary.getSprite("gameover_bg"));a.x=0;a.y=0;c=new createjs.Text("","80px katanaregular","#FFCC00");c.x=CANVAS_WIDTH/2;c.y=CANVAS_HEIGHT/2-132;c.textAlign="center";c.shadow=new createjs.Shadow("#000",2,2,2);d=new createjs.Text("","50px katanaregular","#FFCC00");d.x=CANVAS_WIDTH/2;d.y=CANVAS_HEIGHT/2+52;d.shadow=new createjs.Shadow("#000",2,2,2);d.textAlign="center";var f=s_oSpriteLibrary.getSprite("but_play");b=new CTextButton(CANVAS_WIDTH/
2,CANVAS_HEIGHT-280,f,TEXT_RESTART,"katanaregular","#ffc600",60,!1);b.addEventListener(ON_MOUSE_UP,this._onButRestartRelease,this);e=new createjs.Container;e.visible=!1;e.addChild(a,d,c,b.getSprite());s_oStage.addChild(e)};this.unload=function(){e.off("mousedown",this._onExit)};this._initListener=function(){e.on("mousedown",this._onExit)};this.show=function(a){c.text=TEXT_GAMEOVER;d.text=TEXT_SCORE+": "+a;e.visible=!0;$(s_oMain).trigger("save_score",a)};this._onExit=function(){e.off("mousedown",this._onExit);
s_oStage.removeChild(e);s_oGame.onExit()};this._onButRestartRelease=function(){s_oStage.removeAllChildren();s_oMain.gotoGame()};this._init();return this};