function CSpriteLibrary(){var a,e,l,h,k,g;this.init=function(b,f,d){l=e=0;h=b;k=f;g=d;a={}};this.addSprite=function(b,f){a.hasOwnProperty(b)||(a[b]={szPath:f,oSprite:new Image},e++)};this.getSprite=function(b){return a.hasOwnProperty(b)?a[b].oSprite:null};this._onSpritesLoaded=function(){k.call(g)};this._onSpriteLoaded=function(){h.call(g);++l===e&&this._onSpritesLoaded()};this.loadSprites=function(){for(var b in a)a[b].oSprite.oSpriteLibrary=this,a[b].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
a[b].oSprite.src=a[b].szPath};this.getNumSprites=function(){return e}}
var CANVAS_WIDTH=1024,CANVAS_HEIGHT=768,FPS_TIME=1E3/24,DISABLE_SOUND_MOBILE=!0,STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,GAME_STATE_IDLE=0,GAME_STATE_SPINNING=1,GAME_STATE_SHOW_ALL_WIN=2,GAME_STATE_SHOW_WIN=3,REEL_STATE_START=0,REEL_STATE_MOVING=1,REEL_STATE_STOP=2,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,REEL_OFFSET_X=142,REEL_OFFSET_Y=148,NUM_REELS=5,NUM_ROWS=3,NUM_SYMBOLS=10,WILD_SYMBOL=10,BONUS_SYMBOL=9,NUM_PAYLINES=5,SYMBOL_SIZE=
140,SPACE_BETWEEN_SYMBOLS=10,MAX_FRAMES_REEL_EASE=16,MIN_REEL_LOOPS,REEL_DELAY,REEL_START_Y=REEL_OFFSET_Y-3*SYMBOL_SIZE,REEL_ARRIVAL_Y=REEL_OFFSET_Y+3*SYMBOL_SIZE,TIME_SHOW_WIN,TIME_SHOW_ALL_WINS,MIN_BET,MAX_BET,TOTAL_MONEY,MAX_NUM_HOLD,CHICKEN_WIDTH=166,CHICKEN_HEIGHT=187,NUM_EGGS=3,NUM_SYMBOLS_FOR_BONUS,PERC_WIN_EGG_1,PERC_WIN_EGG_2,PERC_WIN_EGG_3,SOUNDTRACK_VOLUME=.5;
function CTweenController(){this.tweenValue=function(a,e,l){return a+l*(e-a)};this.easeLinear=function(a,e,l,h){return l*a/h+e};this.easeInCubic=function(a,e,l,h){h=(a/=h)*a*a;return e+l*h};this.easeBackInQuart=function(a,e,l,h){h=(a/=h)*a;return e+l*(2*h*h+2*h*a+-3*h)};this.easeInBack=function(a,e,l,h){return l*(a/=h)*a*(2.70158*a-1.70158)+e};this.easeOutCubic=function(a,e,l,h){return l*((a=a/h-1)*a*a+1)+e}}
function CToggle(a,e,l){var h,k,g;this._init=function(a,f,d){h=[];k=[];var c=new createjs.SpriteSheet({images:[d],frames:{width:d.width/2,height:d.height,regX:d.width/2/2,regY:d.height/2},animations:{on:[0,1],off:[1,2]}});g=s_bAudioActive?createSprite(c,"on",d.width/2/2,d.height/2,d.width/2,d.height):createSprite(c,"off",d.width/2/2,d.height/2,d.width/2,d.height);g.x=a;g.y=f;g.stop();s_oStage.addChild(g);this._initListener()};this.unload=function(){g.off("mousedown",this.buttonDown);g.off("pressup",
this.buttonRelease);s_oStage.removeChild(g)};this._initListener=function(){g.on("mousedown",this.buttonDown);g.on("pressup",this.buttonRelease)};this.addEventListener=function(a,f,d){h[a]=f;k[a]=d};this.buttonRelease=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("press_but");g.scaleX=1;g.scaleY=1;(s_bAudioActive=!s_bAudioActive)?g.gotoAndStop("on"):g.gotoAndStop("off");h[ON_MOUSE_UP]&&h[ON_MOUSE_UP].call(k[ON_MOUSE_UP])};this.buttonDown=function(){g.scaleX=.9;g.scaleY=
.9;h[ON_MOUSE_DOWN]&&h[ON_MOUSE_DOWN].call(k[ON_MOUSE_DOWN])};this._init(a,e,l)}
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,4))})(navigator.userAgent||
navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}$(window).ready(function(){sizeHandler()});window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}

function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a=CANVAS_WIDTH,b=CANVAS_HEIGHT,c,d;!0===inIframe()&&"ios"==getMobileOperatingSystem()?top.location.href=document.location.href:(c=window.innerWidth,d=window.innerHeight,console.log("h: "+d),multiplier=Math.min(d/b,c/a),a*=multiplier,b*=multiplier,$("#canvas").css("width",a+"px"),$("#canvas").css("height",b+"px"),$("#canvas").css("left",c/2-a/2+"px"))}}
function getMobileOperatingSystem(){var a=navigator.userAgent||navigator.vendor||window.opera;return a.match(/iPad/i)||a.match(/iPhone/i)||a.match(/iPod/i)?"ios":a.match(/Android/i)?"android":"unknown"}function inIframe(){try{return window.self!==window.top}catch(a){return!0}};

function createBitmap(a,e,l){var h=new createjs.Bitmap(a),k=new createjs.Shape;e&&l?k.graphics.beginFill("#fff").drawRect(0,0,e,l):k.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);h.hitArea=k;return h}function createSprite(a,e,l,h,k,g){a=null!==e?new createjs.Sprite(a,e):new createjs.Sprite(a);e=new createjs.Shape;e.graphics.beginFill("#000000").drawRect(-l,-h,k,g);a.hitArea=e;return a}
function randomFloatBetween(a,e,l){"undefined"===typeof l&&(l=2);return parseFloat(Math.min(a+Math.random()*(e-a),e).toFixed(l))}function shuffle(a){for(var e=a.length,l,h;0!==e;)h=Math.floor(Math.random()*e),--e,l=a[e],a[e]=a[h],a[h]=l;return a}function formatTime(a){a/=1E3;var e=Math.floor(a/60);a=parseFloat(a-60*e).toFixed(1);var l="",l=10>e?l+("0"+e+":"):l+(e+":");return l=10>a?l+("0"+a):l+a}
function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3===a.nodeType&&(a=a.parentNode);var e=document.createEvent("MouseEvents");e.initEvent("click",!0,!0);a.dispatchEvent(e)}}};
function CTextButton(a,e,l,h,k,g,b){var f,d,c,m,t,n,p,u;this._init=function(a,b,e,g,h,k,l){f=!1;m=[];t=[];u=createBitmap(e);d=e.width;c=e.height;p=new createjs.Text(g,"bold "+l+"px "+h,k);p.textAlign="center";p.shadow=new createjs.Shadow("#000",2,2,2);p.textBaseline="middle";p.lineHeight=24;p.x=e.width/2;p.y=e.height/2;n=new createjs.Container;n.x=a;n.y=b;n.regX=e.width/2;n.regY=e.height/2;n.addChild(u,p);s_oStage.addChild(n);this._initListener()};this.unload=function(){n.off("mousedown");n.off("pressup");
s_oStage.removeChild(n)};this.setVisible=function(a){n.visible=a};this.enable=function(){f=!1;u.filters=[];u.cache(0,0,d,c)};this.disable=function(){f=!0;var a=(new createjs.ColorMatrix).adjustSaturation(-100).adjustBrightness(40);u.filters=[new createjs.ColorMatrixFilter(a)];u.cache(0,0,d,c)};this._initListener=function(){oParent=this;n.on("mousedown",this.buttonDown);n.on("pressup",this.buttonRelease)};this.addEventListener=function(a,c,b){m[a]=c;t[a]=b};this.buttonRelease=function(){f||(!1!==DISABLE_SOUND_MOBILE&&
!1!==s_bMobile||createjs.Sound.play("press_but"),n.scaleX=1,n.scaleY=1,m[ON_MOUSE_UP]&&m[ON_MOUSE_UP].call(t[ON_MOUSE_UP]))};this.buttonDown=function(){f||(n.scaleX=.9,n.scaleY=.9,m[ON_MOUSE_DOWN]&&m[ON_MOUSE_DOWN].call(t[ON_MOUSE_DOWN]))};this.setPosition=function(a,c){n.x=a;n.y=c};this.changeText=function(a){p.text=a};this.setX=function(a){n.x=a};this.setY=function(a){n.y=a};this.getButtonImage=function(){return n};this.getX=function(){return n.x};this.getY=function(){return n.y};this._init(a,e,
l,h,k,g,b);return this}
function CStaticSymbolCell(a,e,l,h){var k=-1,g,b,f,d;this._init=function(a,e,g,n){d=new createjs.Container;d.visible=!1;b=[];for(a=0;a<NUM_SYMBOLS;a++)e=createSprite(s_aSymbolAnims[a],"static",0,0,SYMBOL_SIZE,SYMBOL_SIZE),e.stop(),e.x=g,e.y=n,e.on("animationend",this._onAnimEnded,null,!1,{index:a}),d.addChild(e),b[a]=e,b[a].visible=!1;a={framerate:60,images:[s_oSpriteLibrary.getSprite("win_frame_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,
19]}};a=new createjs.SpriteSheet(a);f=new createSprite(a,"static",0,0,SYMBOL_SIZE,SYMBOL_SIZE);f.stop();f.x=g;f.y=n;d.addChild(f);s_oStage.addChild(d)};this.unload=function(){s_oStage.removeChild(d)};this.hide=function(){-1<k&&(f.gotoAndStop("static"),f.visible=!1,b[k].gotoAndPlay("static"),d.visible=!1)};this.show=function(a){f.gotoAndPlay("anim");f.visible=!0;for(var e=0;e<NUM_SYMBOLS;e++)b[e].visible=e+1===a?!0:!1;b[a-1].gotoAndPlay("anim");k=a-1;g=b[a-1].spriteSheet.getNumFrames();d.visible=!0};
this._onAnimEnded=function(a,d){b[d.index].currentFrame!==g&&(b[d.index].stop(),setTimeout(function(){b[d.index].gotoAndPlay(1)},100))};this.stopAnim=function(){b[k].gotoAndStop("static");b[k].visible=!1;f.gotoAndStop("static");f.visible=!1};this._init(a,e,l,h)}
function CSlotSettings(){this._init=function(){this._initSymbolSpriteSheets();this._initPaylines();this._initSymbolWin();this._initSymbolAnims();this._initSymbolsOccurence();this._initBonus()};this._initSymbolSpriteSheets=function(){s_aSymbolData=[];for(var a=1;a<NUM_SYMBOLS+1;a++){var e={images:[s_oSpriteLibrary.getSprite("symbol_"+a)],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],moving:[1,2]}};s_aSymbolData[a]=new createjs.SpriteSheet(e)}};this._initPaylines=
function(){s_aPaylineCombo=[[{row:1,col:0},{row:1,col:1},{row:1,col:2},{row:1,col:3},{row:1,col:4}],[{row:0,col:0},{row:0,col:1},{row:0,col:2},{row:0,col:3},{row:0,col:4}],[{row:2,col:0},{row:2,col:1},{row:2,col:2},{row:2,col:3},{row:2,col:4}],[{row:0,col:0},{row:1,col:1},{row:2,col:2},{row:1,col:3},{row:0,col:4}],[{row:2,col:0},{row:1,col:1},{row:0,col:2},{row:1,col:3},{row:2,col:4}]]};this._initSymbolAnims=function(){s_aSymbolAnims=[];var a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_1_anim")],
frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[0]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_2_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[1]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_3_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,
1],anim:[1,14]}};s_aSymbolAnims[2]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_4_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[3]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_5_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[4]=new createjs.SpriteSheet(a);a={framerate:20,
images:[s_oSpriteLibrary.getSprite("symbol_6_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[5]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_7_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[6]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_8_anim")],frames:{width:SYMBOL_SIZE,
height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[7]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_9_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,14]}};s_aSymbolAnims[8]=new createjs.SpriteSheet(a);a={framerate:20,images:[s_oSpriteLibrary.getSprite("symbol_10_anim")],frames:{width:SYMBOL_SIZE,height:SYMBOL_SIZE,regX:0,regY:0},animations:{"static":[0,1],anim:[1,
14]}};s_aSymbolAnims[9]=new createjs.SpriteSheet(a)};this._initSymbolWin=function(){s_aSymbolWin=[[0,0,1500,2500,5E3],[0,0,1E3,1500,2E3],[0,0,500,1E3,1500],[0,100,250,500,1E3],[0,100,250,500,1E3],[0,50,150,250,500],[0,20,100,200,350],[0,10,50,100,150],[0,10,50,100,150]]};this._initSymbolsOccurence=function(){s_aRandSymbols=[];var a;for(a=0;1>a;a++)s_aRandSymbols.push(1);for(a=0;2>a;a++)s_aRandSymbols.push(2);for(a=0;3>a;a++)s_aRandSymbols.push(3);for(a=0;4>a;a++)s_aRandSymbols.push(4);for(a=0;4>a;a++)s_aRandSymbols.push(5);
for(a=0;6>a;a++)s_aRandSymbols.push(6);for(a=0;7>a;a++)s_aRandSymbols.push(7);for(a=0;8>a;a++)s_aRandSymbols.push(8);for(a=0;2>a;a++)s_aRandSymbols.push(9);for(a=0;1>a;a++)s_aRandSymbols.push(10)};this._initBonus=function(){s_aEggOccurence=[];var a;for(a=0;a<PERC_WIN_EGG_1;a++)s_aEggOccurence.push(0);for(a=0;a<PERC_WIN_EGG_2;a++)s_aEggOccurence.push(1);for(a=0;a<PERC_WIN_EGG_3;a++)s_aEggOccurence.push(2)};this._init()}var s_aSymbolData,s_aPaylineCombo,s_aSymbolWin,s_aSymbolAnims,s_aRandSymbols,s_aEggOccurence;
function CReelColumn(a,e,l,h){var k,g,b,f,d,c,m,t,n,p,u,w,v,y,r;this._init=function(a,e,h,l){f=b=g=k=!1;t=0;d=a;m=l;c=d<NUM_REELS?d:d-NUM_REELS;p=0;u=MAX_FRAMES_REEL_EASE;n=REEL_STATE_START;w=h;v=w+SYMBOL_SIZE*NUM_ROWS;this.initContainer(e,h)};this.initContainer=function(a,b){r=new createjs.Container;r.x=a;r.y=b;var d=0;y=[];for(var c=0;c<NUM_ROWS;c++){var f=Math.floor(Math.random()*s_aRandSymbols.length),f=createSprite(s_aSymbolData[s_aRandSymbols[f]],"static",0,0,SYMBOL_SIZE,SYMBOL_SIZE);f.stop();
f.x=0;f.y=d;r.addChild(f);y[c]=f;d+=SYMBOL_SIZE}s_oStage.addChild(r)};this.unload=function(){s_oStage.removeChild(r)};this.activate=function(){w=r.y;v=w+SYMBOL_SIZE*NUM_ROWS;k=!0};this._setSymbol=function(a){r.removeAllChildren();for(var b=0,d=0;d<a.length;d++){var f=new createSprite(s_aSymbolData[a[d]],"static",0,0,SYMBOL_SIZE,SYMBOL_SIZE);f.stop();f.x=0;f.y=b;r.addChild(f);y[d]=f;b+=SYMBOL_SIZE}};this.setHold=function(a){f=a};this.restart=function(a,d){r.y=w=REEL_START_Y;v=w+SYMBOL_SIZE*NUM_ROWS;
this._setSymbol(a);if(g=d){p=0;u=MAX_FRAMES_REEL_EASE;n=REEL_STATE_STOP;for(var f=0;f<NUM_ROWS;f++)y[f].gotoAndStop("static");b=!0}else for(f=0;f<NUM_ROWS;f++)y[f].gotoAndStop("moving")};this.setReadyToStop=function(){p=0;u=MAX_FRAMES_REEL_EASE;n=REEL_STATE_STOP};this.isReadyToStop=function(){return g};this.isHold=function(){return f};this._updateStart=function(){0===p&&d<NUM_REELS&&(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("start_reel",{volume:.3}));p++;p>u&&(p=0,u/=2,n++,w=
r.y,v=w+SYMBOL_SIZE*NUM_ROWS);var a=s_oTweenController.easeInBack(p,0,1,u),a=s_oTweenController.tweenValue(w,v,a);r.y=a};this._updateMoving=function(){p++;p>u&&(p=0,w=r.y,v=w+SYMBOL_SIZE*NUM_ROWS);var a=s_oTweenController.easeLinear(p,0,1,u),a=s_oTweenController.tweenValue(w,v,a);r.y=a};this._updateStopping=function(){p++;if(p>=u)k=!1,p=0,u=MAX_FRAMES_REEL_EASE,n=REEL_STATE_START,t=0,g=!1,b&&(b=!1,r.y=REEL_OFFSET_Y),s_oGame.stopNextReel();else{var a=s_oTweenController.easeOutCubic(p,0,1,u),a=s_oTweenController.tweenValue(w,
v,a);r.y=a}};this.update=function(a){if(!1!==k&&(t++,t>m))if(f)a===d&&(k=!1,s_oGame.stopNextReel(),s_oGame.stopNextReel(),0===d&&s_oGame.increaseReelLoops());else switch(!1===g&&r.y>REEL_ARRIVAL_Y&&s_oGame.reelArrived(d,c),n){case REEL_STATE_START:this._updateStart();break;case REEL_STATE_MOVING:this._updateMoving();break;case REEL_STATE_STOP:this._updateStopping()}};this._init(a,e,l,h)}
function CPreloader(){var a,e,l,h,k,g,b;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_preloader","./sprites/bg_preloader.jpg");s_oSpriteLibrary.addSprite("preloader_bar","./sprites/preloader_bar.png");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.loadSprites();b=new createjs.Container;s_oStage.addChild(b)};this.unload=function(){b.removeAllChildren()};this.hide=function(){var a=
this;setTimeout(function(){createjs.Tween.get(g).to({alpha:1},500).call(function(){a.unload();s_oMain.gotoMenu()})},1E3)};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var f=createBitmap(s_oSpriteLibrary.getSprite("bg_preloader"));b.addChild(f);f=s_oSpriteLibrary.getSprite("preloader_bar");l=createBitmap(f);l.x=270;l.y=CANVAS_HEIGHT-171;b.addChild(l);h=createBitmap(s_oSpriteLibrary.getSprite("progress_bar"));
h.x=271;h.y=CANVAS_HEIGHT-170;b.addChild(h);a=f.width;k=new createjs.Shape;k.graphics.beginFill("rgba(255,0,0,0.01)").drawRect(271,CANVAS_HEIGHT-170,1,30);b.addChild(k);h.mask=k;e=new createjs.Text("","24px walibi0615bold","#fff");e.x=CANVAS_WIDTH/2;e.y=CANVAS_HEIGHT-148;e.shadow=new createjs.Shadow("#000",2,2,2);e.textBaseline="alphabetic";e.textAlign="center";b.addChild(e);g=new createjs.Shape;g.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);g.alpha=0;b.addChild(g)};this.refreshLoader=
function(b){e.text=b+"%";k.graphics.clear();b=Math.floor(b*a/100);k.graphics.beginFill("rgba(255,0,0,0.01)").drawRect(271,CANVAS_HEIGHT-170,b,30)};this._init()}
function CPayTablePanel(){var a,e,l,h,k,g;this._init=function(){g=new createjs.Container;k=createBitmap(s_oSpriteLibrary.getSprite("paytable"));g.addChild(k);a=[];var b,f=184,d=90;a[0]=[];for(b=0;3>b;b++){var c=new createjs.Text("X"+(5-b),"bold 22px walibi0615bold","#ffffff");c.textAlign="center";c.shadow=new createjs.Shadow("#000",1,1,2);c.x=f;c.y=d;c.textBaseline="alphabetic";g.addChild(c);a[0][b]=c;d+=30}f=394;d=90;a[1]=[];for(b=0;3>b;b++)c=new createjs.Text("X"+(5-b),"bold 22px walibi0615bold",
"#ffffff"),c.textAlign="center",c.shadow=new createjs.Shadow("#000",1,1,2),c.x=f,c.y=d,c.textBaseline="alphabetic",g.addChild(c),a[1][b]=c,d+=30;f=624;d=90;a[2]=[];for(b=0;3>b;b++)c=new createjs.Text("X"+(5-b),"bold 22px walibi0615bold","#ffffff"),c.textAlign="center",c.shadow=new createjs.Shadow("#000",1,1,2),c.x=f,c.y=d,c.textBaseline="alphabetic",g.addChild(c),a[2][b]=c,d+=30;f=858;d=84;a[3]=[];for(b=0;4>b;b++)c=new createjs.Text("X"+(5-b),"bold 21px walibi0615bold","#ffffff"),c.textAlign="center",
c.shadow=new createjs.Shadow("#000",1,1,2),c.x=f,c.y=d,c.textBaseline="alphabetic",g.addChild(c),a[3][b]=c,d+=22;d=f=190;a[4]=[];for(b=0;4>b;b++)c=new createjs.Text("X"+(5-b),"bold 21px walibi0615bold","#ffffff"),c.textAlign="center",c.shadow=new createjs.Shadow("#000",1,1,2),c.x=f,c.y=d,c.textBaseline="alphabetic",g.addChild(c),a[4][b]=c,d+=22;f=414;d=190;a[5]=[];for(b=0;4>b;b++)c=new createjs.Text("X"+(5-b),"bold 21px walibi0615bold","#ffffff"),c.textAlign="center",c.shadow=new createjs.Shadow("#000",
1,1,2),c.x=f,c.y=d,c.textBaseline="alphabetic",g.addChild(c),a[5][b]=c,d+=22;f=634;d=190;a[6]=[];for(b=0;4>b;b++)c=new createjs.Text("X"+(5-b),"bold 21px walibi0615bold","#ffffff"),c.textAlign="center",c.shadow=new createjs.Shadow("#000",1,1,2),c.x=f,c.y=d,c.textBaseline="alphabetic",g.addChild(c),a[6][b]=c,d+=22;f=856;d=190;a[7]=[];for(b=0;4>b;b++)c=new createjs.Text("X"+(5-b),"bold 21px walibi0615bold","#ffffff"),c.textAlign="center",c.shadow=new createjs.Shadow("#000",1,1,2),c.x=f,c.y=d,c.textBaseline=
"alphabetic",g.addChild(c),a[7][b]=c,d+=22;e=[];f=220;d=90;e[0]=[];for(b=0;3>b;b++)c=new createjs.Text(s_aSymbolWin[0][4-b],"22px walibi0615bold","#ffff00"),c.textAlign="left",c.shadow=new createjs.Shadow("#000",1,1,2),c.x=f,c.y=d,c.textBaseline="alphabetic",g.addChild(c),e[0][b]=c,d+=30;f=430;d=90;e[1]=[];for(b=0;3>b;b++)c=new createjs.Text(s_aSymbolWin[1][4-b],"22px walibi0615bold","#ffff00"),c.textAlign="left",c.shadow=new createjs.Shadow("#000",1,1,2),c.x=f,c.y=d,c.textBaseline="alphabetic",g.addChild(c),
e[1][b]=c,d+=30;f=660;d=90;e[2]=[];for(b=0;3>b;b++)c=new createjs.Text(s_aSymbolWin[2][4-b],"22px walibi0615bold","#ffff00"),c.textAlign="left",c.shadow=new createjs.Shadow("#000",1,1,2),c.x=f,c.y=d,c.textBaseline="alphabetic",g.addChild(c),e[2][b]=c,d+=30;f=890;d=84;e[3]=[];for(b=0;4>b;b++)c=new createjs.Text(s_aSymbolWin[3][4-b],"21px walibi0615bold","#ffff00"),c.textAlign="left",c.shadow=new createjs.Shadow("#000",1,1,2),c.x=f,c.y=d,c.textBaseline="alphabetic",g.addChild(c),e[3][b]=c,d+=22;f=220;
d=190;e[4]=[];for(b=0;4>b;b++)c=new createjs.Text(s_aSymbolWin[4][4-b],"21px walibi0615bold","#ffff00"),c.textAlign="left",c.shadow=new createjs.Shadow("#000",1,1,2),c.x=f,c.y=d,c.textBaseline="alphabetic",g.addChild(c),e[4][b]=c,d+=22;f=445;d=190;e[5]=[];for(b=0;4>b;b++)c=new createjs.Text(s_aSymbolWin[5][4-b],"21px walibi0615bold","#ffff00"),c.textAlign="left",c.shadow=new createjs.Shadow("#000",1,1,2),c.x=f,c.y=d,c.textBaseline="alphabetic",g.addChild(c),e[5][b]=c,d+=22;f=665;d=190;e[6]=[];for(b=
0;4>b;b++)c=new createjs.Text(s_aSymbolWin[6][4-b],"21px walibi0615bold","#ffff00"),c.textAlign="left",c.shadow=new createjs.Shadow("#000",1,1,2),c.x=f,c.y=d,c.textBaseline="alphabetic",g.addChild(c),e[6][b]=c,d+=22;f=890;d=190;e[7]=[];for(b=0;4>b;b++)c=new createjs.Text(s_aSymbolWin[7][4-b],"21px walibi0615bold","#ffff00"),c.textAlign="left",c.shadow=new createjs.Shadow("#000",1,1,2),c.x=f,c.y=d,c.textBaseline="alphabetic",g.addChild(c),e[7][b]=c,d+=22;l=new createjs.Text(TEXT_HELP_WILD,"21px walibi0615bold",
"#ffff00");l.shadow=new createjs.Shadow("#000",2,2,2);l.textAlign="center";l.lineHeight=22;l.x=396;l.y=286;g.addChild(l);h=new createjs.Text(TEXT_HELP_BONUS,"21px walibi0615bold","#ffff00");h.shadow=new createjs.Shadow("#000",2,2,2);h.textAlign="center";h.lineHeight=22;h.x=776;h.y=300;g.addChild(h);g.visible=!1;s_oStage.addChild(g);var m=this;g.on("pressup",function(){m._onExit()})};this.unload=function(){var b=this;g.off("pressup",function(){b._onExit()});s_oStage.removeChild(g);for(var f=0;f<a.length;f++)g.removeChild(a[f]);
for(f=0;f<e.length;f++)g.removeChild(e[f])};this.show=function(){g.visible=!0};this.hide=function(){g.visible=!1};this.resetHighlightCombo=function(){for(var b=0;b<a.length;b++)for(var f=0;f<a[b].length;f++)a[b][f].color="#ffffff",e[b][f].color="#ffff00",createjs.Tween.removeTweens(e[b][f]),e[b][f].alpha=1};this.highlightCombo=function(a,f){8<a||(e[a-1][NUM_REELS-f].color="#ff0000",this.tweenAlpha(e[a-1][NUM_REELS-f],0))};this.tweenAlpha=function(a,f){var d=this;createjs.Tween.get(a).to({alpha:f},
200).call(function(){1===f?d.tweenAlpha(a,0):d.tweenAlpha(a,1)})};this._onExit=function(){s_oGame.hidePayTable()};this.isVisible=function(){return g.visible};this._init()}
function CMenu(){var a,e,l,h;this._init=function(){a=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(a);var k=s_oSpriteLibrary.getSprite("but_play_bg");e=new CTextButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-100,k,TEXT_PLAY,"walibi0615bold","#ffffff",40);e.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)k=s_oSpriteLibrary.getSprite("audio_icon"),l=new CToggle(CANVAS_WIDTH-k.width/2+20,k.height/2+20,k),l.addEventListener(ON_MOUSE_UP,
this._onAudioToggle,this),null===s_oSoundTrack&&(s_oSoundTrack=createjs.Sound.play("soundtrack",{volume:SOUNDTRACK_VOLUME,loop:-1}));h=new createjs.Shape;h.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(h);createjs.Tween.get(h).to({alpha:0},600).call(function(){h.visible=!1})};this.unload=function(){e.unload();e=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)l.unload(),l=null;s_oStage.removeChild(a);a=null;s_oStage.removeChild(h);h=null};this._onButPlayRelease=
function(){this.unload();s_oMain.gotoGame()};this._onAudioToggle=function(){createjs.Sound.setMute(!s_bAudioActive)};this._init()}
function CMain(a){var e=0,l=0,h=STATE_LOADING,k,g,b;this.initContainer=function(){var a=document.getElementById("canvas");s_oStage=new createjs.Stage(a);createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&s_oStage.enableMouseOver(20);s_iPrevTime=(new Date).getTime();createjs.Ticker.setFPS(30);createjs.Ticker.addEventListener("tick",this._update);if(navigator.userAgent.match(/Windows Phone/i)){
			DISABLE_SOUND_MOBILE = true;
		}s_oSpriteLibrary=new CSpriteLibrary;g=new CPreloader};this.preloaderReady=function(){this._loadImages();!1!==DISABLE_SOUND_MOBILE&&
!1!==s_bMobile||this._initSounds()};this.soundLoaded=function(){e++;e===l&&(g.unload(),this.gotoMenu())};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&(0<navigator.userAgent.indexOf("Opera")||0<navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=["mp3"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/press_but.ogg","press_but"),createjs.Sound.registerSound("./sounds/win.ogg","win"),
createjs.Sound.registerSound("./sounds/reels.ogg","reels"),createjs.Sound.registerSound("./sounds/reel_stop.ogg","reel_stop",6),createjs.Sound.registerSound("./sounds/start_reel.ogg","start_reel",6),createjs.Sound.registerSound("./sounds/choose_chicken.ogg","choose_chicken"),createjs.Sound.registerSound("./sounds/press_hold.ogg","press_hold"),createjs.Sound.registerSound("./sounds/soundtrack.ogg","soundtrack"),createjs.Sound.registerSound("./sounds/soundtrack_bonus.ogg","soundtrack_bonus"),createjs.Sound.registerSound("./sounds/reveal_egg.ogg",
"reveal_egg")):(createjs.Sound.alternateExtensions=["ogg"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/press_but.mp3","press_but"),createjs.Sound.registerSound("./sounds/win.mp3","win"),createjs.Sound.registerSound("./sounds/reels.mp3","reels"),createjs.Sound.registerSound("./sounds/reel_stop.mp3","reel_stop",6),createjs.Sound.registerSound("./sounds/start_reel.mp3","start_reel",6),createjs.Sound.registerSound("./sounds/choose_chicken.mp3",
"choose_chicken"),createjs.Sound.registerSound("./sounds/press_hold.mp3","press_hold"),createjs.Sound.registerSound("./sounds/soundtrack.mp3","soundtrack"),createjs.Sound.registerSound("./sounds/soundtrack_bonus.mp3","soundtrack_bonus"),createjs.Sound.registerSound("./sounds/reveal_egg.mp3","reveal_egg")),l+=10)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("bg_menu",
"./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("paytable","./sprites/paytable.jpg");s_oSpriteLibrary.addSprite("but_play_bg","./sprites/but_play_bg.png");s_oSpriteLibrary.addSprite("mask_slot","./sprites/mask_slot.png");s_oSpriteLibrary.addSprite("spin_but","./sprites/but_spin_bg.png");s_oSpriteLibrary.addSprite("coin_but","./sprites/but_coin_bg.png");s_oSpriteLibrary.addSprite("info_but","./sprites/but_info_bg.png");s_oSpriteLibrary.addSprite("bet_but",
"./sprites/bet_but.png");s_oSpriteLibrary.addSprite("win_frame_anim","./sprites/win_frame_anim.png");s_oSpriteLibrary.addSprite("but_lines_bg","./sprites/but_lines_bg.png");s_oSpriteLibrary.addSprite("but_maxbet_bg","./sprites/but_maxbet_bg.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("hit_area_col","./sprites/hit_area_col.png");s_oSpriteLibrary.addSprite("hold_col","./sprites/hold_col.png");s_oSpriteLibrary.addSprite("bonus_bg","./sprites/bonus_bg.jpg");
s_oSpriteLibrary.addSprite("chicken","./sprites/chicken.png");s_oSpriteLibrary.addSprite("hit_area_chicken","./sprites/hit_area_chicken.png");s_oSpriteLibrary.addSprite("egg","./sprites/egg.png");for(var a=1;a<NUM_SYMBOLS+1;a++)s_oSpriteLibrary.addSprite("symbol_"+a,"./sprites/symbol_"+a+".png"),s_oSpriteLibrary.addSprite("symbol_"+a+"_anim","./sprites/symbol_"+a+"_anim.png");for(a=1;a<NUM_PAYLINES+1;a++)s_oSpriteLibrary.addSprite("payline_"+a,"./sprites/payline_"+a+".png");l+=s_oSpriteLibrary.getNumSprites();
s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){e++;g.refreshLoader(Math.floor(e/l*100));e===l&&(g.unload(),this.gotoMenu())};this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this.gotoMenu=function(){new CMenu;h=STATE_MENU};this.gotoGame=function(){b=new CGame(k);h=STATE_GAME;$(s_oMain).trigger("game_start")};this.gotoHelp=function(){new CHelp;h=STATE_HELP};this._update=function(a){var d=(new Date).getTime();s_iTimeElaps=d-s_iPrevTime;
s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=d;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);h===STATE_GAME&&b.update();s_oStage.update(a)};s_oMain=this;k=a;this.initContainer()}var s_bMobile,s_bAudioActive=!0,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oSoundTrack=null;TEXT_GAMEOVER="GAME OVER";TEXT_CONGRATS="CONGRATULATIONS";TEXT_MONEY="SCORE";TEXT_PLAY="PLAY";TEXT_BET="BET";TEXT_COIN="COIN";
TEXT_MAX_BET="MAX BET";TEXT_INFO="INFO";TEXT_LINES="LINES";TEXT_SPIN="SPIN";TEXT_WIN="WIN";TEXT_HOLD="HOLD";TEXT_HELP_WILD="JOLLY SYMBOL\nCAN REPLACE\nANY OTHER\nSYMBOL TO\nMAKE UP A\nCOMBO";TEXT_HELP_BONUS="3 OR MORE\nMR CHICKEN\nLET YOU PLAY\nTHE BONUS\nGAME!";
function CInterface(a,e,l){var h,k,g,b,f,d,c,m,t,n,p,u,w;this._init=function(a,e,l){var q=s_oSpriteLibrary.getSprite("but_exit");g=new CGfxButton(CANVAS_WIDTH-q.width/2-20,q.height/2+20,q,!0);g.addEventListener(ON_MOUSE_UP,this._onExit,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)c=new CToggle(g.getX()-q.width,q.height/2+20,s_oSpriteLibrary.getSprite("audio_icon")),c.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);q=s_oSpriteLibrary.getSprite("spin_but");b=new CTextButton(830+q.width/
2,610+q.height/2,q,"","walibi0615bold","#ffde00",22);b.addEventListener(ON_MOUSE_UP,this._onSpin,this);q=s_oSpriteLibrary.getSprite("info_but");f=new CTextButton(28+q.width/2,642+q.height/2,q,TEXT_INFO,"walibi0615bold","#ffffff",30);f.addEventListener(ON_MOUSE_UP,this._onInfo,this);q=s_oSpriteLibrary.getSprite("but_lines_bg");d=new CTextButton(194+q.width/2,642+q.height/2,q,TEXT_LINES,"walibi0615bold","#ffffff",30);d.addEventListener(ON_MOUSE_UP,this._onAddLine,this);q=s_oSpriteLibrary.getSprite("coin_but");
m=new CTextButton(380+q.width/2,642+q.height/2,q,TEXT_COIN,"walibi0615bold","#ffffff",30);m.addEventListener(ON_MOUSE_UP,this._onBet,this);q=s_oSpriteLibrary.getSprite("but_maxbet_bg");t=new CTextButton(566+q.width/2,642+q.height/2,q,TEXT_MAX_BET,"walibi0615bold","#ffffff",30);t.addEventListener(ON_MOUSE_UP,this._onMaxBet,this);p=new createjs.Text(TEXT_MONEY+"\n"+l.toFixed(2),"30px walibi0615bold","#ffde00");p.x=140;p.y=78;p.textBaseline="alphabetic";p.lineHeight=28;p.textAlign="center";s_oStage.addChild(p);
w=new createjs.Text(NUM_PAYLINES,"30px walibi0615bold","#ffffff");w.x=284;w.y=CANVAS_HEIGHT-135;w.shadow=new createjs.Shadow("#000",2,2,2);w.textAlign="center";w.textBaseline="alphabetic";s_oStage.addChild(w);n=new createjs.Text(a.toFixed(2),"30px walibi0615bold","#ffffff");n.x=476;n.y=CANVAS_HEIGHT-135;n.shadow=new createjs.Shadow("#000",2,2,2);n.textAlign="center";n.textBaseline="alphabetic";s_oStage.addChild(n);u=new createjs.Text(TEXT_BET+": "+e.toFixed(2),"30px walibi0615bold","#ffffff");u.x=
680;u.y=CANVAS_HEIGHT-135;u.shadow=new createjs.Shadow("#000",2,2,2);u.textAlign="center";u.textBaseline="alphabetic";s_oStage.addChild(u);q=s_oSpriteLibrary.getSprite("bet_but");h=[];a=new CBetBut(95+q.width/2,313+q.height/2,q,!0);a.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,1);h[0]=a;a=new CBetBut(95+q.width/2,211+q.height/2,q,!0);a.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,2);h[1]=a;a=new CBetBut(95+q.width/2,462+q.height/2,q,!0);a.addEventListenerWithParams(ON_MOUSE_UP,
this._onBetLineClicked,this,3);h[2]=a;a=new CBetBut(95+q.width/2,144+q.height/2,q,!0);a.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,4);h[3]=a;a=new CBetBut(95+q.width/2,531+q.height/2,q,!0);a.addEventListenerWithParams(ON_MOUSE_UP,this._onBetLineClicked,this,5);h[4]=a;k=[];for(q=0;q<NUM_PAYLINES;q++)a=new createjs.Bitmap(s_oSpriteLibrary.getSprite("payline_"+(q+1))),a.x=0,a.y=0,a.visible=!1,s_oStage.addChild(a),k[q]=a};this.unload=function(){g.unload();g=null;b.unload();b=null;
f.unload();f=null;d.unload();d=null;m.unload();m=null;t.unload();t=null;!1===DISABLE_SOUND_MOBILE&&(c.unload(),c=null);s_oStage.removeChild(u);s_oStage.removeChild(w);s_oStage.removeChild(p);s_oStage.removeChild(n);for(var a=0;a<NUM_PAYLINES;a++)h[a].unload(),s_oStage.removeChild(k[a])};this.refreshMoney=function(a){p.text=TEXT_MONEY+"\n"+a.toFixed(2)};this.refreshBet=function(a){n.text=a.toFixed(2)};this.refreshTotalBet=function(a){u.text=TEXT_BET+": "+a.toFixed(2)};this.refreshNumLines=function(a){w.text=
a;for(var d=0;d<NUM_PAYLINES;d++)d<a?(h[d].setOn(),k[d].visible=!0):h[d].setOff();setTimeout(function(){for(var a=0;a<NUM_PAYLINES;a++)k[a].visible=!1},1E3)};this.resetWin=function(){b.changeText("")};this.refreshWinText=function(a){b.changeText(TEXT_WIN+"\n"+a.toFixed(2))};this.showLine=function(a){k[a-1].visible=!0};this.hideLine=function(a){k[a-1].visible=!1};this.hideAllLines=function(){for(var a=0;a<NUM_PAYLINES;a++)k[a].visible=!1};this.disableBetBut=function(a){for(var d=0;d<NUM_PAYLINES;d++)h[d].disable(a)};
this.enableGuiButtons=function(){b.enable();t.enable();m.enable();d.enable();f.enable()};this.enableSpin=function(){b.enable();t.enable()};this.disableSpin=function(){b.disable();t.disable()};this.disableGuiButtons=function(){b.disable();t.disable();m.disable();d.disable();f.disable()};this._onBetLineClicked=function(a){this.refreshNumLines(a);s_oGame.activateLines(a)};this._onExit=function(){s_oGame.onExit()};this._onSpin=function(){s_oGame.onSpin()};this._onAddLine=function(){s_oGame.addLine()};
this._onInfo=function(){s_oGame.onInfoClicked()};this._onBet=function(){s_oGame.changeCoinBet()};this._onMaxBet=function(){s_oGame.onMaxBet()};this._onAudioToggle=function(){createjs.Sound.setMute(!s_bAudioActive)};s_oInterface=this;this._init(a,e,l);return this}var s_oInterface;
function CGfxButton(a,e,l,h){var k,g,b,f,d,c,m;this._init=function(a,c,e,h){k=!1;f=[];d=[];m=createBitmap(e);m.x=a;m.y=c;g=e.width;b=e.height;m.regX=e.width/2;m.regY=e.height/2;!1!==h&&s_oStage.addChild(m);this._initListener()};this.unload=function(){m.off("mousedown",this.buttonDown);m.off("pressup",this.buttonRelease);s_oStage.removeChild(m)};this.setVisible=function(a){m.visible=a};this.enable=function(){k=!1;m.filters=[];m.cache(0,0,g,b)};this.disable=function(){k=!0;var a=(new createjs.ColorMatrix).adjustSaturation(-100).adjustBrightness(40);
m.filters=[new createjs.ColorMatrixFilter(a)];m.cache(0,0,g,b)};this._initListener=function(){m.on("mousedown",this.buttonDown);m.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){f[a]=b;d[a]=c};this.addEventListenerWithParams=function(a,b,e,g){f[a]=b;d[a]=e;c=g};this.buttonRelease=function(){k||(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("press_but"),m.scaleX=1,m.scaleY=1,f[ON_MOUSE_UP]&&f[ON_MOUSE_UP].call(d[ON_MOUSE_UP],c))};this.buttonDown=function(){k||
(m.scaleX=.9,m.scaleY=.9,f[ON_MOUSE_DOWN]&&f[ON_MOUSE_DOWN].call(d[ON_MOUSE_DOWN],c))};this.setPosition=function(a,d){m.x=a;m.y=d};this.setX=function(a){m.x=a};this.setY=function(a){m.y=a};this.getButtonImage=function(){return m};this.getX=function(){return m.x};this.getY=function(){return m.y};this.getSprite=function(){return m};this._init(a,e,l,h);return this}
function CGame(a){var e=!1,l,h,k,g,b,f,d,c,m,t,n,p,u,w=0,v,y,r,q,x,A,D,C,B,I,E,F,G,s,z=null,H;this._init=function(){k=GAME_STATE_IDLE;l=!0;u=f=g=0;q=[0,1,2,3,4];b=q[0];d=NUM_PAYLINES;p=TOTAL_MONEY;t=MIN_BET;n=t*d;x=[];for(var a=0;a<NUM_ROWS;a++){x[a]=[];for(var c=0;c<NUM_REELS;c++)x[a][c]=0}s_oTweenController=new CTweenController;F=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(F);this._initReels();G=createBitmap(s_oSpriteLibrary.getSprite("mask_slot"));s_oStage.addChild(G);
s=new CInterface(t,n,p);this._initStaticSymbols();this._initHitAreaColumn();H=new CBonusPanel;z=new CPayTablePanel;e=!0};this.unload=function(){createjs.Sound.stop();s_oSoundTrack=null;s_oStage.removeChild(F);s_oStage.removeChild(G);s.unload();z.unload();for(var a=0;a<v.length;a++)v[a].unload();for(a=0;a<NUM_ROWS;a++)for(var d=0;d<NUM_REELS;d++)y[a][d].unload();H.unload()};this._initReels=function(){var a=REEL_OFFSET_X,d=REEL_OFFSET_Y,b=0;v=[];for(var c=0;c<NUM_REELS;c++)v[c]=new CReelColumn(c,a,
d,b),v[c+NUM_REELS]=new CReelColumn(c+NUM_REELS,a,d+SYMBOL_SIZE*NUM_ROWS,b),a+=SYMBOL_SIZE+SPACE_BETWEEN_SYMBOLS,b+=REEL_DELAY};this._initStaticSymbols=function(){var a=REEL_OFFSET_X,d=REEL_OFFSET_Y;y=[];for(var b=0;b<NUM_ROWS;b++){y[b]=[];for(var c=0;c<NUM_REELS;c++){var f=new CStaticSymbolCell(b,c,a,d);y[b][c]=f;a+=SYMBOL_SIZE+SPACE_BETWEEN_SYMBOLS}a=REEL_OFFSET_X;d+=SYMBOL_SIZE}};this._initHitAreaColumn=function(){B=[];C=[];for(var a=136,d=144,b=0;b<NUM_REELS;b++){var c=createBitmap(s_oSpriteLibrary.getSprite("hold_col"));
c.x=a;c.y=d;c.visible=!1;s_oStage.addChild(c);a+=150;C.push(c);B[b]=!1}A=[];D=[];for(var a=141,d=148,b=s_oSpriteLibrary.getSprite("hit_area_col"),c=0;c<NUM_REELS;c++){var f=new createjs.Text(TEXT_HOLD,"22px walibi0615bold","#ffffff");f.visible=!1;f.x=a+b.width/2;f.y=d+b.height-20;f.shadow=new createjs.Shadow("#000",1,1,2);f.textAlign="center";s_oStage.addChild(f);A[c]=f;f=new CGfxButton(a+b.width/2,d+b.height/2,b);f.setVisible(!1);f.addEventListenerWithParams(ON_MOUSE_UP,this._onHitAreaCol,this,{index:c});
a+=150;D.push(f)}};this.generateFinalSymbols=function(){for(var a=0;a<NUM_ROWS;a++)for(var b=0;b<NUM_REELS;b++)if(!1===v[b].isHold()){var c=Math.floor(Math.random()*s_aRandSymbols.length);x[a][b]=s_aRandSymbols[c]}r=[];for(a=0;a<d;a++){var b=s_aPaylineCombo[a],c=[],f=x[b[0].row][b[0].col];if(f!==BONUS_SYMBOL){var e=1,g=1;for(c.push({row:b[0].row,col:b[0].col,value:x[b[0].row][b[0].col]});f===WILD_SYMBOL&&g<NUM_REELS;)e++,f=x[b[g].row][b[g].col],c.push({row:b[g].row,col:b[g].col,value:x[b[g].row][b[g].col]}),
g++;for(;g<b.length;g++)if(x[b[g].row][b[g].col]===f||x[b[g].row][b[g].col]===WILD_SYMBOL){if(x[b[g].row][b[g].col]===BONUS_SYMBOL)break;e++;c.push({row:b[g].row,col:b[g].col,value:x[b[g].row][b[g].col]})}else break;0<s_aSymbolWin[f-1][e-1]&&r.push({line:a+1,amount:s_aSymbolWin[f-1][e-1],num_win:e,value:f,list:c})}}h=!1;w=0;c=[];for(a=0;a<NUM_ROWS;a++)for(b=0;b<NUM_REELS;b++)x[a][b]===BONUS_SYMBOL&&(c.push({row:a,col:b,value:x[a][b]}),w++);w>=NUM_SYMBOLS_FOR_BONUS&&(r.push({line:-1,amount:0,num_win:w,
value:BONUS_SYMBOL,list:c}),5<w&&(w=5),h=!0)};this._generateRandSymbols=function(){for(var a=[],b=0;b<NUM_ROWS;b++){var d=Math.floor(Math.random()*s_aRandSymbols.length);a[b]=s_aRandSymbols[d]}return a};this.reelArrived=function(a,d){if(g>MIN_REEL_LOOPS)if(b===d){if(!1===v[a].isReadyToStop()){var c=a;a<NUM_REELS?(c+=NUM_REELS,v[c].setReadyToStop(),v[a].restart([x[0][a],x[1][a],x[2][a]],!0)):(c-=NUM_REELS,v[c].setReadyToStop(),v[a].restart([x[0][c],x[1][c],x[2][c]],!0))}}else v[a].restart(this._generateRandSymbols(),
!1);else v[a].restart(this._generateRandSymbols(),!1),0===a&&g++};this.increaseReelLoops=function(){g+=2};this.stopNextReel=function(){f++;0===f%2&&(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("reel_stop",{volume:.3}),b=q[f/2],f===2*NUM_REELS&&this._endReelAnimation())};this._endReelAnimation=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||I.stop();f=g=0;b=q[0];for(var a=0;a<NUM_REELS;a++)B[a]=!1,C[a].visible=!1,v[a].setHold(!1),v[a+NUM_REELS].setHold(!1);var d=u=0;if(0<r.length){for(var e=
0;e<r.length;e++){z.highlightCombo(r[e].value,r[e].num_win);-1!==r[e].line&&s.showLine(r[e].line);for(var m=r[e].list,a=0;a<m.length;a++)y[m[a].row][m[a].col].show(m[a].value);d+=r[e].amount}d*=t;p+=d;0<d&&(s.refreshMoney(p),s.refreshWinText(d));c=0;k=GAME_STATE_SHOW_ALL_WIN;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)E=createjs.Sound.play("win")}else l&&this.enableColumnHitArea(),k=GAME_STATE_IDLE;!1===l&&(l=!0);!1===h&&(s.disableBetBut(!1),s.enableGuiButtons());p<n&&s.disableSpin();$(s_oMain).trigger("end_bet",
[p,d])};this.hidePayTable=function(){z.hide()};this._showWin=function(){var a;if(0<m){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||E.stop();-1!==r[m-1].line&&(a=r[m-1].line,s.hideLine(a));a=r[m-1].list;for(var b=0;b<a.length;b++)y[a[b].row][a[b].col].stopAnim()}m===r.length&&(m=0);-1!==r[m].line&&(a=r[m].line,s.showLine(a));a=r[m].list;for(b=0;b<a.length;b++)y[a[b].row][a[b].col].show(a[b].value);m++};this._hideAllWins=function(){for(var a=0;a<r.length;a++)for(var b=r[a].list,d=0;d<b.length;d++)y[b[d].row][b[d].col].stopAnim();
s.hideAllLines();m=c=0;c=TIME_SHOW_WIN;k=GAME_STATE_SHOW_WIN;h&&H.show(w)};this.enableColumnHitArea=function(){for(var a=0;a<NUM_REELS;a++)A[a].visible=!0,D[a].setVisible(!0)};this.disableColumnHitArea=function(){for(var a=0;a<NUM_REELS;a++)A[a].visible=!1,D[a].setVisible(!1)};this.activateLines=function(a){d=a;this.removeWinShowing();n=a=t*d;s.refreshTotalBet(n);s.refreshNumLines(d);a>p?s.disableSpin():s.enableSpin()};this.addLine=function(){d===NUM_PAYLINES?d=1:d++;var a=t*d;n=a;s.refreshTotalBet(n);
s.refreshNumLines(d);a>p?s.disableSpin():s.enableSpin()};this.changeCoinBet=function(){var a=Math.floor(100*(t+.05))/100;a>MAX_BET?(t=MIN_BET,n=t*d,s.refreshBet(t),s.refreshTotalBet(n),a=n):(a*=d,t+=.05,t=Math.floor(100*t)/100,n=a,s.refreshBet(t),s.refreshTotalBet(n));a>p?s.disableSpin():s.enableSpin()};this.onMaxBet=function(){var a=MAX_BET;d=NUM_PAYLINES;a*=d;t=MAX_BET;n=a;s.refreshBet(t);s.refreshTotalBet(n);s.refreshNumLines(d);a>p?s.disableSpin():(s.enableSpin(),this.onSpin())};this._onHitAreaCol=
function(a){a=a.index;!0===B[a]?(B[a]=!1,C[a].visible=!1,A[a].visible=!0,u--,v[a].setHold(!1),v[a+NUM_REELS].setHold(!1)):u<MAX_NUM_HOLD&&(B[a]=!0,u++,C[a].visible=!0,A[a].visible=!1,v[a].setHold(!0),v[a+NUM_REELS].setHold(!0),!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("press_hold"));l=!1};this.removeWinShowing=function(){z.resetHighlightCombo();s.resetWin();for(var a=0;a<NUM_ROWS;a++)for(var b=0;b<NUM_REELS;b++)y[a][b].hide();for(a=0;a<v.length;a++)v[a].activate();k=GAME_STATE_IDLE};
this.endBonus=function(a){p+=a;s.refreshMoney(p);s.disableBetBut(!1);s.enableGuiButtons()};this.onSpin=function(){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)E&&E.stop(),I=createjs.Sound.play("reels",{volume:.3});this.disableColumnHitArea();s.disableBetBut(!0);this.removeWinShowing();this.generateFinalSymbols();s.hideAllLines();s.disableGuiButtons();p-=n;s.refreshMoney(p);k=GAME_STATE_SPINNING};this.onInfoClicked=function(){k!==GAME_STATE_SPINNING&&(z.isVisible()?z.hide():z.show())};this.onExit=
function(){this.unload();s_oMain.gotoMenu();$(s_oMain).trigger("restart")};this.getState=function(){return k};this.update=function(){if(!1!==e)switch(k){case GAME_STATE_SPINNING:for(var a=0;a<v.length;a++)v[a].update(b);break;case GAME_STATE_SHOW_ALL_WIN:c+=s_iTimeElaps;c>TIME_SHOW_ALL_WINS&&this._hideAllWins();break;case GAME_STATE_SHOW_WIN:c+=s_iTimeElaps,c>TIME_SHOW_WIN&&(c=0,this._showWin())}};s_oGame=this;MIN_REEL_LOOPS=a.min_reel_loop;REEL_DELAY=a.reel_delay;TIME_SHOW_WIN=a.time_show_win;TIME_SHOW_ALL_WINS=
a.time_show_all_wins;TOTAL_MONEY=a.money;MIN_BET=a.min_bet;MAX_BET=a.max_bet;MAX_NUM_HOLD=a.max_hold;PERC_WIN_EGG_1=a.perc_win_egg_1;PERC_WIN_EGG_2=a.perc_win_egg_2;PERC_WIN_EGG_3=a.perc_win_egg_3;NUM_SYMBOLS_FOR_BONUS=a.num_symbol_bonus;new CSlotSettings;this._init()}var s_oGame,s_oTweenController;
function CBonusPanel(){var a,e,l,h,k,g,b,f,d,c;this._init=function(){d=new createjs.Container;s_oStage.addChild(d);var a=createBitmap(s_oSpriteLibrary.getSprite("bonus_bg"));d.alpha=0;d.visible=!1;d.addChild(a);a={framerate:3,images:[s_oSpriteLibrary.getSprite("chicken")],frames:{width:CHICKEN_WIDTH,height:CHICKEN_HEIGHT,regX:CHICKEN_WIDTH/2,regY:CHICKEN_HEIGHT/2},animations:{idle:[0,5,"idle"],lay_egg:[6,9,"lay_egg"],idle_rand_0:[1,5,"idle"],idle_rand_1:[2,5,"idle"],idle_rand_2:[3,5,"idle"],idle_rand_3:[4,
5,"idle"],right:[3],left:[4]}};a=new createjs.SpriteSheet(a);l=[];for(var c=180,e=0;5>e;e++){var h=createSprite(a,"idle",CHICKEN_WIDTH/2,CHICKEN_HEIGHT/2,CHICKEN_WIDTH,CHICKEN_HEIGHT);h.on("click",this._onChickenReleased,this,!1,e);h.x=c;h.y=286;h.stop();h.visible=!1;d.addChild(h);c+=164;l[e]=h}c=s_oSpriteLibrary.getSprite("egg");a={framerate:10,images:[c],frames:{width:Math.floor(c.width/NUM_EGGS),height:c.height,regX:Math.floor(c.width/NUM_EGGS)/2,regY:c.height/2},animations:{egg_0:[0],egg_1:[1],
egg_2:[2]}};a=new createjs.SpriteSheet(a);b=createSprite(a,"egg_0",Math.floor(c.width/NUM_EGGS)/2,c.height/2,Math.floor(c.width/NUM_EGGS),c.height);d.addChild(b);e=new createjs.Shape;e.graphics.beginFill("rgba(255,0,0,0.01)").drawRect(110,390,800,160);d.addChild(e);b.mask=e;k=[];g=[];k[0]=createSprite(a,"egg_0",Math.floor(c.width/NUM_EGGS)/2,c.height/2,Math.floor(c.width/NUM_EGGS),c.height);k[0].x=170;k[0].y=CANVAS_HEIGHT-85;d.addChild(k[0]);e=new createjs.Text("100","34px walibi0615bold","#ffff00");
e.textAlign="left";e.x=k[0].x+c.width/NUM_EGGS/2+6;e.y=k[0].y+12;e.textBaseline="alphabetic";d.addChild(e);g.push(e);k[1]=createSprite(a,"egg_1",Math.floor(c.width/NUM_EGGS)/2,c.height/2,Math.floor(c.width/NUM_EGGS),c.height);k[1].x=460;k[1].y=CANVAS_HEIGHT-85;d.addChild(k[1]);e=new createjs.Text("200","34px walibi0615bold","#ffff00");e.textAlign="left";e.x=k[1].x+ +(c.width/NUM_EGGS)/2+6;e.y=k[1].y+12;e.textBaseline="alphabetic";d.addChild(e);g.push(e);k[2]=createSprite(a,"egg_2",Math.floor(c.width/
NUM_EGGS)/2,c.height/2,Math.floor(c.width/NUM_EGGS),c.height);k[2].x=760;k[2].y=CANVAS_HEIGHT-85;d.addChild(k[2]);e=new createjs.Text("300","34px walibi0615bold","#ffff00");e.textAlign="left";e.x=k[2].x+ +(c.width/NUM_EGGS)/2+6;e.y=k[2].y+12;e.textBaseline="alphabetic";d.addChild(e);g.push(e);f=new createjs.Text("+ 300$","bold 80px Arial","#ffff00");f.alpha=0;f.textAlign="center";f.shadow=new createjs.Shadow("#000",2,2,2);f.x=CANVAS_WIDTH/2;f.y=150;f.textBaseline="alphabetic";d.addChild(f)};this.unload=
function(){for(var a=0;5>a;a++)l[a].off("click",this._onChickenReleased)};this.show=function(e){a=!1;f.alpha=0;switch(e){case 3:h=[50,500,2E3];break;case 4:h=[500,2E3,5E3];break;case 5:h=[1E3,5E3,1E4];break;default:h=[50,500,2E3]}g[0].text=h[0]+"$";g[1].text=h[1]+"$";g[2].text=h[2]+"$";b.x=118;b.y=308;b.rotation=0;b.gotoAndStop("egg_0");for(var k=0;k<e;k++){var n=Math.floor(4*Math.random());l[k].framerate=3;l[k].visible=!0;l[k].gotoAndPlay("idle_rand_"+n)}d.visible=!0;createjs.Tween.get(d).to({alpha:1},
1E3);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundTrack.setVolume(0),c=createjs.Sound.play("soundtrack_bonus",{loop:-1})};this._onChickenReleased=function(b,c){if(!a){a=!0;var d=Math.floor(Math.random()*s_aEggOccurence.length);this.playChickenLayAnim(c,s_aEggOccurence[d]);!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("choose_chicken")}};this.playChickenLayAnim=function(a,c){e=h[c];b.gotoAndStop("egg_"+c);for(var d=0;5>d;d++)d<a?l[d].gotoAndStop("right"):d===a?(l[a].framerate=
10,l[a].gotoAndPlay("lay_egg")):l[d].gotoAndStop("left");var f=this;setTimeout(function(){f.layEgg(a)},2500)};this.layEgg=function(a){l[a].gotoAndStop(5);b.x=l[a].x;var c=this;createjs.Tween.get(b).to({y:500},300).call(function(){c.endBonus()});!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("reveal_egg")};this.endBonus=function(){f.text="+ "+e+"$";createjs.Tween.get(f).to({alpha:1},500);createjs.Tween.get(b).to({rotation:110},500);setTimeout(function(){d.alpha=0;d.visible=!1;s_oSoundTrack.setVolume(SOUNDTRACK_VOLUME);
c.stop();s_oGame.endBonus(e)},4E3)};this._init()}
function CBetBut(a,e,l){var h,k,g,b=[],f;this._init=function(a,b,e){h=!1;k=[];g=[];e=s_oSpriteLibrary.getSprite("bet_but");var l=new createjs.SpriteSheet({images:[e],frames:{width:e.width/2,height:e.height,regX:0,regY:0},animations:{on:[0,1],off:[1,2]}});f=createSprite(l,"on",0,0,e.width/2,e.height);f.stop();f.x=a;f.y=b;f.regX=e.width/2;f.regY=e.height/2;s_oStage.addChild(f);this._initListener()};this.unload=function(){f.off("mousedown",this.buttonDown);f.off("pressup",this.buttonRelease);s_oStage.removeChild(f)};
this.disable=function(a){h=a};this.setVisible=function(a){f.visible=a};this.setOn=function(){f.gotoAndStop("on")};this.setOff=function(){f.gotoAndStop("off")};this._initListener=function(){f.on("mousedown",this.buttonDown);f.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,e){k[a]=b;g[a]=e};this.addEventListenerWithParams=function(a,c,e,f){k[a]=c;g[a]=e;b=f};this.buttonRelease=function(){k[ON_MOUSE_UP]&&!1===h&&(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("press_but"),
k[ON_MOUSE_UP].call(g[ON_MOUSE_UP],b))};this.buttonDown=function(){k[ON_MOUSE_DOWN]&&!1===h&&k[ON_MOUSE_DOWN].call(g[ON_MOUSE_DOWN],b)};this.setPosition=function(a,b){f.x=a;f.y=b};this.setX=function(a){f.x=a};this.setY=function(a){f.y=a};this.getButtonImage=function(){return f};this.getX=function(){return f.x};this.getY=function(){return f.y};this._init(a,e,l)};