function CGame(a){var d,b,c,f,e,g,k,l,h,u,v,F=!1,A,D=null,y,E,w,B,q,p,n,C,r,G,z,m,t,x;this._init=function(){v=!1;d=2*SIZE;b=342;c=b/36;f=c/2;e=Math.floor(1.44*SCRATCH_RATIO);g=k=0;C=[];r=[];G=[];x=[];m=[];t=[];z=[];for(var a=0;3>a;a++)z.push(!1);a=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(a);A=new CInterface;n=[];for(a=0;9>a;a++)n[a]=!1;p=[];for(a=0;36>a;a++){p[a]=[];for(var l=0;36>l;l++)p[a][l]={centerX:(a+1)*c-f,centerY:(l+1)*c-f,deleted:!1}}this._initProbability();this._initFruits();
a=s_oSpriteLibrary.getSprite("silver");y=createBitmap(a);y.x=SCRATCH_X;y.y=SCRATCH_Y;s_oStage.addChild(y);s_bMobile&&window.navigator.msPointerEnabled?(u=0,s_oCanvasScratch.addEventListener("MSPointerDown",this.onTouchStartMS,!1),s_oCanvasScratch.addEventListener("MSPointerMove",this.onTouchMoveMS,!1),s_oCanvasScratch.addEventListener("MSPointerUp",this.onTouchEndMS,!1)):(s_oStageScratch.addEventListener("stagemousedown",this.onMouseStart,!1),s_oStageScratch.addEventListener("stagemousemove",this.onMouseMove,
!1),s_oStageScratch.addEventListener("stagemouseup",this.onMouseEnd,!1));CHelpPanel();E=document.getElementById("clear-image").getContext("2d");E.drawImage(s_oSpriteLibrary.getSprite("silver"),0,0)};this._initProbability=function(){for(var a=Math.floor(PROBABILITY_SCALE*PRIZE_PROB[0]),b=Math.floor(PROBABILITY_SCALE*PRIZE_PROB[1]),c=Math.floor(PROBABILITY_SCALE*PRIZE_PROB[2]),f=Math.floor(PROBABILITY_SCALE*PRIZE_PROB[3]),d=Math.floor(PROBABILITY_SCALE*PRIZE_PROB[4]),e=Math.floor(PROBABILITY_SCALE*
PRIZE_PROB[5]),g=Math.floor(PROBABILITY_SCALE*PRIZE_PROB[6]),l=Math.floor(PROBABILITY_SCALE*PRIZE_PROB[7]),k=Math.floor(PROBABILITY_SCALE*PRIZE_PROB[8]),h=0;h<a;h++)r.push(0);for(h=0;h<b;h++)r.push(1);for(h=0;h<c;h++)r.push(2);for(h=0;h<f;h++)r.push(3);for(h=0;h<d;h++)r.push(4);for(h=0;h<e;h++)r.push(5);for(h=0;h<g;h++)r.push(6);for(h=0;h<l;h++)r.push(7);for(h=0;h<k;h++)r.push(8);for(h=a=0;h<WIN_PERCENTAGE.length;h++)for(b=0;b<WIN_PERCENTAGE[h];b++)G[a]=h,a++};this._initFruits=function(){var a=Math.floor(Math.random()*
G.length),a=G[a];m.push(0);m.push(1);m.push(2);shuffle(m);var b;switch(a){case 0:for(var c=0;3>c;c++)new CRow(SCRATCH_X,SCRATCH_Y+110*c,9);break;case 1:x[m[0]]=!0;b=Math.floor(Math.random()*r.length);t[m[0]]=r[b];g=PRIZE[t[m[0]]];new CRow(SCRATCH_X,SCRATCH_Y+114*m[0],t[m[0]]);new CRow(SCRATCH_X,SCRATCH_Y+114*m[1],9);new CRow(SCRATCH_X,SCRATCH_Y+114*m[2],9);break;case 2:x[m[0]]=!0;x[m[1]]=!0;for(c=0;c<a;c++)b=Math.floor(Math.random()*r.length),t[m[c]]=r[b],g+=PRIZE[t[m[c]]],new CRow(SCRATCH_X,SCRATCH_Y+
114*m[c],t[m[c]]);new CRow(SCRATCH_X,SCRATCH_Y+114*m[2],9);break;case 3:for(x[m[0]]=!0,x[m[1]]=!0,x[m[2]]=!0,c=0;c<a;c++)b=Math.floor(Math.random()*r.length),t[m[c]]=r[b],g+=PRIZE[t[m[c]]],new CRow(SCRATCH_X,SCRATCH_Y+114*m[c],t[m[c]])}};this._scratch=function(){var a,f,e,h,g,l;e=q.getX();h=q.getY();q.subV(B);g=q.length();q.normalize();q.scalarProduct(PRECISION);l=g/PRECISION;a=B.getX()-SIZE;f=B.getY()-SIZE;for(g=0;g<l;g++){var k=parseInt(a+g*q.getX()),v=parseInt(f+g*q.getY());E.clearRect(k,v,d,d);
C[g]=new createjs.Rectangle(k,v,d,d)}a=[];f=[];l=[];k=[];for(g=0;g<C.length;g++)for(a[g]=Math.floor((C[g].x-SIZE)/c),f[g]=Math.floor((C[g].x+SIZE)/c),l[g]=Math.floor((C[g].y-SIZE)/c),k[g]=Math.floor((C[g].y+SIZE)/c),0>a[g]&&(a[g]=0),0>l[g]&&(l[g]=0),f[g]>b&&(f[g]=b),k[g]>b&&(k[g]=b),v=a[g];v<=f[g];v++)for(var u=l[g];u<=k[g];u++)C[g].contains(p[v][u].centerX,p[v][u].centerY)&&(p[u][v].deleted=!0);C=[];B.set(e,h);s_bDefaultAndroid&&$("#clear-image").hide().show(0)};this._checkGrid=function(){for(var a=
0,b=0;12>b;b++)for(var c=0;12>c;c++)!0===p[b][c].deleted&&a++;a>e&&(n[0]=!0);for(b=a=0;12>b;b++)for(c=12;24>c;c++)!0===p[b][c].deleted&&a++;a>e&&(n[1]=!0);for(b=a=0;12>b;b++)for(c=24;36>c;c++)!0===p[b][c].deleted&&a++;a>e&&(n[2]=!0);a=0;for(b=12;24>b;b++)for(c=0;12>c;c++)!0===p[b][c].deleted&&a++;a>e&&(n[3]=!0);a=0;for(b=12;24>b;b++)for(c=12;24>c;c++)!0===p[b][c].deleted&&a++;a>e&&(n[4]=!0);a=0;for(b=12;24>b;b++)for(c=24;36>c;c++)!0===p[b][c].deleted&&a++;a>e&&(n[5]=!0);a=0;for(b=24;36>b;b++)for(c=
0;12>c;c++)!0===p[b][c].deleted&&a++;a>e&&(n[6]=!0);a=0;for(b=24;36>b;b++)for(c=12;24>c;c++)!0===p[b][c].deleted&&a++;a>e&&(n[7]=!0);a=0;for(b=24;36>b;b++)for(c=24;36>c;c++)!0===p[b][c].deleted&&a++;a>e&&(n[8]=!0)};this._checkWin=function(){n[0]&&n[1]&&n[2]&&!z[0]&&(x[0]?(z[0]=!0,new CShowResult("win",t[0],0)):(z[0]=!0,new CShowResult("nowin",t[0],0)));n[3]&&n[4]&&n[5]&&!z[1]&&(x[1]?(z[1]=!0,new CShowResult("win",t[1],1)):(z[1]=!0,new CShowResult("nowin",t[1],1)));n[6]&&n[7]&&n[8]&&!z[2]&&(x[2]?(z[2]=
!0,new CShowResult("win",t[2],2)):(z[2]=!0,new CShowResult("nowin",t[2],2)))};this._playScratch=function(){if(F)F=!1,!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||s_oScratchSfx.stop();else if(F=!0,!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oScratchSfx=createjs.Sound.play("scratch",{loop:100})};this.onMouseStart=function(a){a=a||window.event;B=new CVector2(a.stageX,a.stageY);w._playScratch();v=!0};this.onMouseMove=function(a){!1!==v&&(q=new CVector2(a.stageX,a.stageY),w._scratch(),w._checkGrid(),w._checkWin())};
this.onMouseEnd=function(){v=!1;w._playScratch()};this.onTouchStartMS=function(a){u++;1<u||(l=parseInt(((a.pageX||a.targetTouches[0].pageX)-s_oCanvasLeft)/s_iScaleFactor)-SCRATCH_X,h=parseInt(((a.pageY||a.targetTouches[0].pageY)-s_oCanvasTop)/s_iScaleFactor)-SCRATCH_Y,B=new CVector2(l,h),v=!0,w._playScratch())};this.onTouchMoveMS=function(a){if(!window.navigator.msPointerEnabled||a.isPrimary)a.preventDefault(),l=parseInt(((a.pageX||a.targetTouches[0].pageX)-s_oCanvasLeft)/s_iScaleFactor)-SCRATCH_X,
h=parseInt(((a.pageY||a.targetTouches[0].pageY)-s_oCanvasTop)/s_iScaleFactor)-SCRATCH_Y,q=new CVector2(l,h),w._scratch(),w._checkGrid(),w._checkWin()};this.onTouchEndMS=function(a){u--;0===u&&(v=!1);w._playScratch()};this.unload=function(){this.removeListeners();createjs.Tween.removeAllTweens();s_oStage.removeAllChildren();s_oStageScratch.removeAllChildren();s_oStageScratch.clear();$("#clear-image").css("display","none");A.unload();null!==D&&D.unload()};this.removeListeners=function(){s_bMobile&&
window.navigator.msPointerEnabled?(u=0,s_oCanvasScratch.removeEventListener("MSPointerDown",this.onTouchStartMS,!1),s_oCanvasScratch.removeEventListener("MSPointerMove",this.onTouchMoveMS,!1),s_oCanvasScratch.removeEventListener("MSPointerUp",this.onTouchEndMS,!1)):(s_oStageScratch.removeEventListener("stagemousedown",this.onMouseStart,!1),s_oStageScratch.removeEventListener("stagemousemove",this.onMouseMove,!1),s_oStageScratch.removeEventListener("stagemouseup",this.onMouseEnd,!1))};this.onExit=
function(){this.unload();s_oMain.gotoMenu();$(s_oMain).trigger("restart")};this._onExitHelp=function(){$("#clear-image").css("display","block");s_oStage.removeChild(y)};this.checkGameOver=function(){k++;3===k&&this.gameOver()};this.gameOver=function(){this.removeListeners();s_oStageScratch.removeAllChildren();s_oStageScratch.clear();$("#clear-image").css("display","none");var a;if(x[0]||x[1]||x[2])a=!0;D=CEndPanel(s_oSpriteLibrary.getSprite("msg_box"));D.show(g,a)};this.update=function(){};s_oGame=
this;PRIZE[0]=a.prize0;PRIZE[1]=a.prize1;PRIZE[2]=a.prize2;PRIZE[3]=a.prize3;PRIZE[4]=a.prize4;PRIZE[5]=a.prize5;PRIZE[6]=a.prize6;PRIZE[7]=a.prize7;PRIZE[8]=a.prize8;PRIZE_PROB[0]=a.prizeprob0;PRIZE_PROB[1]=a.prizeprob1;PRIZE_PROB[2]=a.prizeprob2;PRIZE_PROB[3]=a.prizeprob3;PRIZE_PROB[4]=a.prizeprob4;PRIZE_PROB[5]=a.prizeprob5;PRIZE_PROB[6]=a.prizeprob6;PRIZE_PROB[7]=a.prizeprob7;PRIZE_PROB[8]=a.prizeprob8;WIN_PERCENTAGE=a.winpercentage;SCRATCH_RATIO=a.scratch_tolerance_per_cell;w=this;this._init()}
var s_oGame,s_oScratchSfx;
function CEndPanel(a){var d,b,c,f,e,g;this._init=function(a){d=createBitmap(a);a=CANVAS_WIDTH/2+1;var l=CANVAS_HEIGHT/2-160,h=CANVAS_WIDTH/2+1,u=CANVAS_HEIGHT/2+50;c=new createjs.Text("","bold 60px Arial","#000");c.x=h+2;c.y=u+2;c.textAlign="center";c.lineWidth=400;e=new createjs.Text("","bold 60px Arial","#ffffff");e.x=h;e.y=u;e.textAlign="center";e.lineWidth=400;f=new createjs.Text("","bold 50px Arial","#000");f.x=a+2;f.y=l+2;f.textAlign="center";g=new createjs.Text("","bold 50px Arial","#ffffff");
g.x=a;g.y=l;g.textAlign="center";b=new createjs.Container;b.alpha=0;b.visible=!1;b.addChild(d,f,g,c,e);s_oStage.addChild(b)};this.unload=function(){b.off("mousedown",this._onExit)};this._initListener=function(){b.on("mousedown",this._onExit)};this.show=function(a,d){d?(c.text=TEXT_WIN+" "+a+" "+TEXT_CURRENCY,e.text=TEXT_WIN+" "+a+" "+TEXT_CURRENCY,f.text=TEXT_CONGRATS,g.text=TEXT_CONGRATS):(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("loose"),c.text=TEXT_NO_WIN,c.y=202,e.text=TEXT_NO_WIN,
e.y=200);b.visible=!0;var h=this;createjs.Tween.get(b).to({alpha:1},500).call(function(){h._initListener()});$(s_oMain).trigger("save_score",a)};this._onExit=function(){b.off("mousedown",this._onExit);s_oStage.removeChild(b);s_oGame.onExit()};this._init(a);return this}
function CSpriteLibrary(){var a,d,b,c,f,e;this.init=function(g,k,l){b=d=0;c=g;f=k;e=l;a={}};this.addSprite=function(b,c){a.hasOwnProperty(b)||(a[b]={szPath:c,oSprite:new Image},d++)};this.getSprite=function(b){return a.hasOwnProperty(b)?a[b].oSprite:null};this._onSpritesLoaded=function(){f.call(e)};this._onSpriteLoaded=function(){c.call(e);++b==d&&this._onSpritesLoaded()};this.loadSprites=function(){for(var b in a)a[b].oSprite.oSpriteLibrary=this,a[b].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
a[b].oSprite.src=a[b].szPath};this.getNumSprites=function(){return d}}var CANVAS_WIDTH=1136,CANVAS_HEIGHT=640,DISABLE_SOUND_MOBILE=!1,FPS_TIME=1E3/24,STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,ON_PRESS_MOVE=6,SCRATCHCANVAS_DIM=342,SCRATCH_X=395,SCRATCH_Y=283,SIZE=10,PRECISION=10,PRIZE=[],PRIZE_PROB=[],PROBABILITY_SCALE=1,WIN_PERCENTAGE,SCRATCH_RATIO;
function CVector2(a,d){var b,c;this._init=function(a,d){b=a;c=d};this.add=function(a,d){b+=a;c+=d};this.addV=function(a){b+=a.getX();c+=a.getY()};this.scalarDivision=function(a){b/=a;c/=a};this.subV=function(a){b-=a.getX();c-=a.getY()};this.scalarProduct=function(a){b*=a;c*=a};this.invert=function(){b*=-1;c*=-1};this.dotProduct=function(a){return b*a.getX()+c*a.getY()};this.set=function(a,d){b=a;c=d};this.setV=function(a){b=a.getX();c=a.getY()};this.length=function(){return Math.sqrt(b*b+c*c)};this.length2=
function(){return b*b+c*c};this.normalize=function(){var a=this.length();0<a&&(b/=a,c/=a)};this.getNormalize=function(a){this.length();a.set(b,c);a.normalize()};this.rot90CCW=function(){var a=b;b=-c;c=a};this.rot90CW=function(){var a=b;b=c;c=-a};this.getRotCCW=function(a){a.set(b,c);a.rot90CCW()};this.getRotCW=function(a){a.set(b,c);a.rot90CW()};this.ceil=function(){b=Math.ceil(b);c=Math.ceil(c)};this.round=function(){b=Math.round(b);c=Math.round(c)};this.toString=function(){return"Vector2: "+b+", "+
c};this.print=function(){trace("Vector2: "+b+", "+c+"")};this.getX=function(){return b};this.getY=function(){return c};this._init(a,d)}
function CToggle(a,d,b,c){var f,e,g,k;this._init=function(a,b,c,d){e=[];g=[];var F=new createjs.SpriteSheet({images:[c],frames:{width:c.width/2,height:c.height,regX:c.width/2/2,regY:c.height/2},animations:{state_true:[0],state_false:[1]}});f=d;k=createSprite(F,"state_"+f,c.width/2/2,c.height/2,c.width/2,c.height);k.x=a;k.y=b;k.stop();s_oStage.addChild(k);this._initListener()};this.unload=function(){k.off("mousedown",this.buttonDown);k.off("pressup",this.buttonRelease);s_oStage.removeChild(k)};this._initListener=
function(){k.on("mousedown",this.buttonDown);k.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){e[a]=b;g[a]=c};this.setActive=function(a){f=a;k.gotoAndStop("state_"+f)};this.buttonRelease=function(){k.scaleX=1;k.scaleY=1;!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");f=!f;k.gotoAndStop("state_"+f);e[ON_MOUSE_UP]&&e[ON_MOUSE_UP].call(g[ON_MOUSE_UP],f)};this.buttonDown=function(){k.scaleX=.9;k.scaleY=.9;e[ON_MOUSE_DOWN]&&e[ON_MOUSE_DOWN].call(g[ON_MOUSE_DOWN])};
this._init(a,d,b,c)}var s_iScaleFactor=1,s_oCanvasLeft,s_oCanvasTop;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,4))})(navigator.userAgent||
navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}$(window).ready(function(){sizeHandler()});window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a=CANVAS_WIDTH,d=CANVAS_HEIGHT,b=window.innerWidth;multiplier=s_iScaleFactor=Math.min(window.innerHeight/d,b/a);a*=multiplier;d*=multiplier;$("#canvas").css("width",a+"px");$("#canvas").css("height",d+"px");$("#canvas").css("left",b/2-a/2+"px");s_oCanvasLeft=$("#canvas").offset().left;s_oCanvasTop=$("#canvas").offset().top;a=SCRATCHCANVAS_DIM*multiplier;d=SCRATCHCANVAS_DIM*multiplier;$("#clear-image").css("width",a+"px");$("#clear-image").css("height",
d+"px");$("#clear-image").css("left",$("#canvas").position().left+SCRATCH_X*multiplier+"px");$("#clear-image").css("top",$("#canvas").position().top+SCRATCH_Y*multiplier+"px");s_oCanvasScratchLeft=$("#clear-image").offset().left;s_oCanvasScratchTop=$("#clear-image").offset().top}}
Number.prototype.formatDecimal=function(a,d,b){var c=this;a=isNaN(a=Math.abs(a))?2:a;d=void 0==d?".":d;b=void 0==b?",":b;var f=0>c?"-":"",e=parseInt(c=Math.abs(+c||0).toFixed(a))+"",g=3<(g=e.length)?g%3:0;return f+(g?e.substr(0,g)+b:"")+e.substr(g).replace(/(\d{3})(?=\d)/g,"$1"+b)+(a?d+Math.abs(c-e).toFixed(a).slice(2):"")};
function createBitmap(a,d,b){var c=new createjs.Bitmap(a),f=new createjs.Shape;d&&b?f.graphics.beginFill("#fff").drawRect(0,0,d,b):f.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);c.hitArea=f;return c}function createSprite(a,d,b,c,f,e){a=null!==d?new createjs.Sprite(a,d):new createjs.Sprite(a);d=new createjs.Shape;d.graphics.beginFill("#000000").drawRect(-b,-c,f,e);a.hitArea=d;return a}
function randomFloatBetween(a,d,b){"undefined"===typeof b&&(b=2);return parseFloat(Math.min(a+Math.random()*(d-a),d).toFixed(b))}function shuffle(a){for(var d=a.length,b,c;0!==d;)c=Math.floor(Math.random()*d),--d,b=a[d],a[d]=a[c],a[c]=b;return a}function easeLinear(a,d,b,c){return b*a/c+d}function easeInQuad(a,d,b,c){return b*(a/=c)*a+d}function easeInSine(a,d,b,c){return-b*Math.cos(a/c*(Math.PI/2))+b+d}function easeInCubic(a,d,b,c){return b*(a/=c)*a*a+d}
function getTrajectoryPoint(a,d){var b=new createjs.Point,c=(1-a)*(1-a),f=a*a;b.x=c*d.start.x+2*(1-a)*a*d.traj.x+f*d.end.x;b.y=c*d.start.y+2*(1-a)*a*d.traj.y+f*d.end.y;return b}function formatTime(a){a/=1E3;var d=Math.floor(a/60);a=parseFloat(a-60*d).toFixed(1);var b="",b=10>d?b+("0"+d+":"):b+(d+":");return b=10>a?b+("0"+a):b+a}function degreesToRadians(a){return a*Math.PI/180}function checkRectCollision(a,d){var b,c;b=getBounds(a,.9);c=getBounds(d,.98);return calculateIntersection(b,c)}
function calculateIntersection(a,d){var b,c,f,e,g,k,l,h;b=a.x+(f=a.width/2);c=a.y+(e=a.height/2);g=d.x+(k=d.width/2);l=d.y+(h=d.height/2);b=Math.abs(b-g)-(f+k);c=Math.abs(c-l)-(e+h);return 0>b&&0>c?(b=Math.min(Math.min(a.width,d.width),-b),c=Math.min(Math.min(a.height,d.height),-c),{x:Math.max(a.x,d.x),y:Math.max(a.y,d.y),width:b,height:c,rect1:a,rect2:d}):null}
function getBounds(a,d){var b={x:Infinity,y:Infinity,width:0,height:0};if(a instanceof createjs.Container){b.x2=-Infinity;b.y2=-Infinity;var c=a.children,f=c.length,e,g;for(g=0;g<f;g++)e=getBounds(c[g],1),e.x<b.x&&(b.x=e.x),e.y<b.y&&(b.y=e.y),e.x+e.width>b.x2&&(b.x2=e.x+e.width),e.y+e.height>b.y2&&(b.y2=e.y+e.height);Infinity==b.x&&(b.x=0);Infinity==b.y&&(b.y=0);Infinity==b.x2&&(b.x2=0);Infinity==b.y2&&(b.y2=0);b.width=b.x2-b.x;b.height=b.y2-b.y;delete b.x2;delete b.y2}else{var k,l;a instanceof createjs.Bitmap?
(f=a.sourceRect||a.image,g=f.width*d,k=f.height*d):a instanceof createjs.Sprite?a.spriteSheet._frames&&a.spriteSheet._frames[a.currentFrame]&&a.spriteSheet._frames[a.currentFrame].image?(f=a.spriteSheet.getFrame(a.currentFrame),g=f.rect.width,k=f.rect.height,c=f.regX,l=f.regY):(b.x=a.x||0,b.y=a.y||0):(b.x=a.x||0,b.y=a.y||0);c=c||0;g=g||0;l=l||0;k=k||0;b.regX=c;b.regY=l;f=a.localToGlobal(0-c,0-l);e=a.localToGlobal(g-c,k-l);g=a.localToGlobal(g-c,0-l);c=a.localToGlobal(0-c,k-l);b.x=Math.min(Math.min(Math.min(f.x,
e.x),g.x),c.x);b.y=Math.min(Math.min(Math.min(f.y,e.y),g.y),c.y);b.width=Math.max(Math.max(Math.max(f.x,e.x),g.x),c.x)-b.x;b.height=Math.max(Math.max(Math.max(f.y,e.y),g.y),c.y)-b.y}return b}function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}function shuffle(a){for(var d=a.length,b,c;0<d;)c=Math.floor(Math.random()*d),d--,b=a[d],a[d]=a[c],a[c]=b;return a}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3==a.nodeType&&(a=a.parentNode);var d=document.createEvent("MouseEvents");d.initEvent("click",!0,!0);a.dispatchEvent(d)}}};
(function(){function a(a){var c={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};a=a||window.event;a.type in c?document.body.className=c[a.type]:(document.body.className=this[d]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var d="hidden";d in document?document.addEventListener("visibilitychange",a):(d="mozHidden")in document?document.addEventListener("mozvisibilitychange",a):(d="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",a):(d="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a})();
function CTextButton(a,d,b,c,f,e,g){var k,l,h;this._init=function(a,b,c,d,e,g,f){k=[];l=[];var w=createBitmap(c),B=Math.ceil(f/20),q=new createjs.Text(d,"bold "+f+"px "+e,"#000000");q.textAlign="center";q.textBaseline="alphabetic";var p=q.getBounds();q.x=c.width/2+B;q.y=Math.floor(c.height/2)+p.height/3+B;d=new createjs.Text(d,"bold "+f+"px "+e,g);d.textAlign="center";d.textBaseline="alphabetic";p=d.getBounds();d.x=c.width/2;d.y=Math.floor(c.height/2)+p.height/3;h=new createjs.Container;h.x=a;h.y=
b;h.regX=c.width/2;h.regY=c.height/2;h.addChild(w,q,d);s_oStage.addChild(h);this._initListener()};this.unload=function(){h.off("mousedown");h.off("pressup");s_oStage.removeChild(h)};this.setVisible=function(a){h.visible=a};this._initListener=function(){oParent=this;h.on("mousedown",this.buttonDown);h.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){k[a]=b;l[a]=c};this.buttonRelease=function(){h.scaleX=1;h.scaleY=1;k[ON_MOUSE_UP]&&k[ON_MOUSE_UP].call(l[ON_MOUSE_UP])};this.buttonDown=
function(){h.scaleX=.9;h.scaleY=.9;k[ON_MOUSE_DOWN]&&k[ON_MOUSE_DOWN].call(l[ON_MOUSE_DOWN])};this.setPosition=function(a,b){h.x=a;h.y=b};this.setX=function(a){h.x=a};this.setY=function(a){h.y=a};this.getButtonImage=function(){return h};this.getX=function(){return h.x};this.getY=function(){return h.y};this._init(a,d,b,c,f,e,g);return this}
function CShowResult(a,d,b){var c,f,e,g,k,l,h;this._init=function(a,b,d){h=0;k=[];l=[];for(var e=0;3>e;e++)k.push(170+260*e);for(e=0;3>e;e++)l.push(150+35*e);"win"===a&&(c=new createjs.Text(PRIZE[b].formatDecimal(2,".",",")+" "+TEXT_CURRENCY,"bold 28px Arial","#FFBF00"),c.alpha=0,s_oStage.addChild(c),this._highlight(b));this._advice(a,d)};this.unload=function(){s_oStage.removeChild(c)};this._highlight=function(a){var b,d;switch(a){case 0:d=b=0;break;case 1:b=0;d=1;break;case 2:b=0;d=2;break;case 3:b=
1;d=0;break;case 4:d=b=1;break;case 5:b=1;d=2;break;case 6:b=2;d=0;break;case 7:b=2;d=1;break;case 8:d=b=2}c.x=k[b]+110;c.y=l[d]+10;this._flicker()};this._flicker=function(){h=1===h?0:1;createjs.Tween.get(c).to({alpha:h},250,createjs.Ease.cubicOut).call(function(){g._flicker()})};this._advice=function(a,b){s_oScratchSfx.stop();var d=CANVAS_WIDTH+400,g=330+110*b;f=new createjs.Text("","bold 40px Arial","#000000");f.x=d+2;f.y=g+2;f.textAlign="center";e=new createjs.Text("","bold 40px Arial","#ffffff");
e.x=d;e.y=g;e.textAlign="center";s_oStage.addChild(f);s_oStage.addChild(e);if("win"===a){if(f.text=TEXT_ADVICE_WIN+" "+c.text,e.text=TEXT_ADVICE_WIN+" "+c.text,!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)createjs.Sound.play("win"),trace("PLAY WIN")}else if(f.text=TEXT_ADVICE_LOSE,e.text=TEXT_ADVICE_LOSE,!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)createjs.Sound.play("loose"),trace("PLAY LOOSE");createjs.Tween.get(f).to({x:CANVAS_WIDTH/2+2,y:332+110*b},2E3,createjs.Ease.elasticOut);createjs.Tween.get(e).to({x:CANVAS_WIDTH/
2,y:330+110*b},2E3,createjs.Ease.elasticOut).call(function(){s_oGame.checkGameOver()})};g=this;this._init(a,d,b);return this}
function CRow(a,d,b){var c;this._init=function(a,b,d){var k={images:[s_oSpriteLibrary.getSprite("fruits")],frames:{width:114,height:114},animations:{symbol0:[0],symbol1:[1],symbol2:[2],symbol3:[3],symbol4:[4],symbol5:[5],symbol6:[6],symbol7:[7],symbol8:[8]}};c=new createjs.SpriteSheet(k);this._select(a,b,d)};this._select=function(a,b,d){if(9>d)for(var k="symbol"+d,l=0;3>l;l++){var h=createSprite(c,k,0,0,114,114);h.x+=a+114*l;h.y=b;h.visible=!0;s_oStage.addChild(h)}else{d=[];if(.7>Math.random()){k=
Math.floor(9*Math.random());for(l=Math.floor(9*Math.random());k===l;)l=Math.floor(9*Math.random());d.push(k);d.push(k);d.push(l)}else for(l=0;9>l;l++)d.push(l);shuffle(d);for(l=0;3>l;l++)k="symbol"+d[l],h=createSprite(c,k,0,0,114,114),h.x+=a+114*l,h.y=b,h.visible=!0,s_oStage.addChild(h)}};this._init(a,d,b)}
function CPreloader(){var a,d,b,c,f;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.loadSprites();f=new createjs.Container;s_oStage.addChild(f)};this.unload=function(){f.removeAllChildren()};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};
this.attachSprites=function(){var e=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));f.addChild(e);b=createBitmap(s_oSpriteLibrary.getSprite("progress_bar"));b.x=330;b.y=CANVAS_HEIGHT-50;f.addChild(b);a=476;c=new createjs.Shape;c.graphics.beginFill("rgba(255,0,0,0.01)").drawRect(330,CANVAS_HEIGHT-50,1,30);f.addChild(c);b.mask=c;d=new createjs.Text("0%","30px OpenSans-BoldItalic","#fff");d.x=330;d.y=CANVAS_HEIGHT-65;d.textAlign="center";d.textBaseline="middle";f.addChild(d)};this.refreshLoader=
function(b){d.text=b+"%";b=Math.floor(b*a/100);c.graphics.clear();c.graphics.beginFill("rgba(255,0,0,0.01)").drawRect(330,CANVAS_HEIGHT-50,b,30)};this._init()}
function CMenu(){var a,d,b,c;this._init=function(){a=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(a);var f=s_oSpriteLibrary.getSprite("but_play");d=new CTextButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-80,f,TEXT_PLAY,"Arial","#ffffff",40);d.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)f=s_oSpriteLibrary.getSprite("audio_icon"),c=new CToggle(CANVAS_WIDTH-f.height/2-10,f.height/2+10,f,s_bAudioActive),c.addEventListener(ON_MOUSE_UP,
this._onAudioToggle,this);b=new createjs.Shape;b.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(b);createjs.Tween.get(b).to({alpha:0},1E3).call(function(){b.visible=!1})};this.unload=function(){d.unload();d=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)c.unload(),c=null;s_oStage.removeChild(a);a=null};this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onButPlayRelease=function(){this.unload();!1!==
DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("press_but");s_oMain.gotoGame()};this._init()}
function CMain(a){var d,b=0,c=0,f=STATE_LOADING,e,g,k;this.initContainer=function(){s_oCanvas=document.getElementById("canvas");s_oStage=new createjs.Stage(s_oCanvas);createjs.Touch.enable(s_oStage);s_oCanvasScratch=document.getElementById("clear-image");s_oStageScratch=new createjs.Stage(s_oCanvasScratch);createjs.Touch.enable(s_oStageScratch);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&(s_oStageScratch.enableMouseOver(0),$("body").on("contextmenu","#clear-image",function(a){return!1}));s_iPrevTime=
(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.setFPS(20);var a=navigator.userAgent;s_bDefaultAndroid=-1<a.indexOf("Mozilla/5.0")&&-1<a.indexOf("Android ")&&-1<a.indexOf("AppleWebKit")&&!(-1<a.indexOf("Chrome"));navigator.userAgent.match(/Windows Phone/i)&&(DISABLE_SOUND_MOBILE=!0);s_oSpriteLibrary=new CSpriteLibrary;g=new CPreloader;d=!0};this.soundLoaded=function(){b++;b===c&&(g.unload(),this.gotoMenu())};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&
(0<navigator.userAgent.indexOf("Opera")||0<navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=["m4a"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/sf_loose.ogg","loose"),createjs.Sound.registerSound("./sounds/sf_win.ogg","win"),createjs.Sound.registerSound("./sounds/sf_press_but.ogg","press_but"),createjs.Sound.registerSound("./sounds/sf_scratch.ogg","scratch")):(createjs.Sound.alternateExtensions=["ogg"],
createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/sf_loose.m4a","loose"),createjs.Sound.registerSound("./sounds/sf_win.m4a","win"),createjs.Sound.registerSound("./sounds/sf_press_but.m4a","press_but"),createjs.Sound.registerSound("./sounds/sf_scratch.m4a","scratch")),c+=4)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");
s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("bg_help","./sprites/bg_help.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");s_oSpriteLibrary.addSprite("fruits_icon","./sprites/fruits_icon.png");s_oSpriteLibrary.addSprite("fruits","./sprites/fruits.png");
s_oSpriteLibrary.addSprite("silver","./sprites/silver.png");c+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){b++;g.refreshLoader(Math.floor(b/c*100));b===c&&(g.unload(),this.gotoMenu())};this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this.preloaderReady=function(){this._loadImages();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||this._initSounds()};this.gotoMenu=function(){new CMenu;f=STATE_MENU};this.gotoGame=
function(){k=new CGame(e);f=STATE_GAME;$(s_oMain).trigger("game_start")};this.gotoHelp=function(){new CHelp;f=STATE_HELP};this.stopUpdate=function(){d=!1};this.startUpdate=function(){d=!0};this._update=function(a){if(!1!==d){var b=(new Date).getTime();s_iTimeElaps=b-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=b;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);f===STATE_GAME&&k.update();s_oStage.update(a)}};s_oMain=this;e=a;this.initContainer()}
var s_bMobile,s_bAudioActive=!0,s_bDefaultAndroid=!1,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oCanvas,s_oCanvasScratch,s_oStageScratch;TEXT_WIN="YOU WIN";TEXT_CONGRATS="CONGRATULATIONS!";TEXT_NO_WIN="I'M SORRY...YOU WIN NOTHING";TEXT_PLAY="PLAY";TEXT_HELP1="SCRATCH A LINE COMPLETELY. IF YOU UNCOVER THREE IDENTICAL SYMBOLS, YOU'LL WIN THE PRIZE!!";TEXT_HEAD="WIN TOP PRIZES!";TEXT_CURRENCY="$";TEXT_SCORE="SCORE";
TEXT_ADVICE_WIN="WIN";TEXT_ADVICE_LOSE="NO WIN";
function CInterface(){var a,d,b,c,f,e,g,k,l,h;this._init=function(){k=0;a=new createjs.Text(TEXT_HEAD,"bold 60px Arial","#ffe603");a.x=950;a.y=80;a.textAlign="right";a.shadow=new createjs.Shadow("#000000",2,2,2);s_oStage.addChild(a);var b=s_oSpriteLibrary.getSprite("fruits_icon"),b=new createjs.SpriteSheet({images:[b],frames:{width:40,height:40},animations:{symbol0:[0],symbol1:[1],symbol2:[2],symbol3:[3],symbol4:[4],symbol5:[5],symbol6:[6],symbol7:[7],symbol8:[8]}});l=[];h=[];for(var c=0;3>c;c++)l.push(170+
260*c);for(c=0;3>c;c++)h.push(150+35*c);for(var f=0,c=0;3>c;c++)for(var A=0;3>A;A++)d=new createjs.Text(PRIZE[f].formatDecimal(2,".",",")+" "+TEXT_CURRENCY,"bold 28px Arial","#ffffff"),d.x=l[c]+110,d.y=h[A]+10,s_oStage.addChild(d),f++;for(var D=0,y,c=0;3>c;c++)for(A=0;3>A;A++){f="symbol"+D;D++;for(var E=0;3>E;E++)y=createSprite(b,f,0,0,40,40),y.x+=l[c]+30*E,y.y=h[A],y.visible=!0,s_oStage.addChild(y)}b=s_oSpriteLibrary.getSprite("but_exit");g=new CGfxButton(CANVAS_WIDTH-b.height/2-10,b.height/2+10,
b,!0);g.addEventListener(ON_MOUSE_UP,this._onExit,this);c=CANVAS_WIDTH-b.width/2-80;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)b=s_oSpriteLibrary.getSprite("audio_icon"),e=new CToggle(c,10+b.height/2,b,s_bAudioActive),e.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this)};this.advice=function(a,d){var e=CANVAS_WIDTH+400,f=330+110*d;c=new createjs.Text("","bold 40px Arial","#000000");c.x=e+2;c.y=f+2;c.textAlign="center";b=new createjs.Text("","bold 40px Arial","#ffffff");b.x=e;b.y=f;b.textAlign=
"center";s_oStage.addChild(c);s_oStage.addChild(b);"win"===a?(c.text=TEXT_ADVICE_WIN,b.text=TEXT_ADVICE_WIN):(c.text=TEXT_ADVICE_LOSE,b.text=TEXT_ADVICE_LOSE);createjs.Tween.get(c).to({x:CANVAS_WIDTH/2+2,y:332+110*d},2E3,createjs.Ease.elasticOut);createjs.Tween.get(b).to({x:CANVAS_WIDTH/2,y:330+110*d},2E3,createjs.Ease.elasticOut).call(function(){s_oGame.checkGameOver()})};this.highlight=function(a){var b,c;switch(a){case 0:c=b=0;break;case 1:b=0;c=1;break;case 2:b=0;c=2;break;case 3:b=1;c=0;break;
case 4:c=b=1;break;case 5:b=1;c=2;break;case 6:b=2;c=0;break;case 7:b=2;c=1;break;case 8:c=b=2}d=new createjs.Text(PRIZE[a].formatDecimal(2,".",",")+" "+TEXT_CURRENCY,"bold 28px Arial","#FFBF00");d.x=l[b]+110;d.y=h[c]+10;d.alpha=0;s_oStage.addChild(d);this._flicker()};this._flicker=function(){k=1===k?0:1;createjs.Tween.get(d).to({alpha:k},250,createjs.Ease.cubicOut).call(function(){f._flicker()})};this.unload=function(){g.unload();g=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)e.unload(),e=null};
this._onAudioToggle=function(){createjs.Sound.setMute(s_bAudioActive);s_bAudioActive=!s_bAudioActive};this._onExit=function(){s_oGame.onExit()};f=this;this._init();return this}
function CHelpPanel(){var a,d,b,c,f;this._init=function(){c=createBitmap(s_oSpriteLibrary.getSprite("bg_help"));s_oStage.addChild(c);b=TEXT_HELP1;d=new createjs.Text(b,"bold 25px Arial","#000000");d.textAlign="center";d.x=500;d.y=252;d.lineWidth=350;a=new createjs.Text(b,"bold 25px Arial","#ffffff");a.textAlign="center";a.x=502;a.y=250;a.lineWidth=350;f=new createjs.Container;f.addChild(c,d,a);s_oStage.addChild(f);var e=this;f.on("pressup",function(){e._onExitHelp()})};this.unload=function(){s_oStage.removeChild(f);
var a=this;f.off("pressup",function(){a._onExitHelp()})};this._onExitHelp=function(){this.unload();s_oGame._onExitHelp()};this._init()}
function CGfxButton(a,d,b){var c,f,e;this._init=function(a,b,d){c=[];f=[];e=createBitmap(d);e.x=a;e.y=b;e.regX=d.width/2;e.regY=d.height/2;s_oStage.addChild(e);this._initListener()};this.unload=function(){e.off("mousedown",this.buttonDown);e.off("pressup",this.buttonRelease);s_oStage.removeChild(e)};this.setVisible=function(a){e.visible=a};this._initListener=function(){e.on("mousedown",this.buttonDown);e.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,d){c[a]=b;f[a]=d};this.buttonRelease=
function(){e.scaleX=1;e.scaleY=1;c[ON_MOUSE_UP]&&c[ON_MOUSE_UP].call(f[ON_MOUSE_UP])};this.buttonDown=function(){e.scaleX=.9;e.scaleY=.9;c[ON_MOUSE_DOWN]&&c[ON_MOUSE_DOWN].call(f[ON_MOUSE_DOWN])};this.setPosition=function(a,b){e.x=a;e.y=b};this.setX=function(a){e.x=a};this.setY=function(a){e.y=a};this.getButtonImage=function(){return e};this.getX=function(){return e.x};this.getY=function(){return e.y};this._init(a,d,b);return this};