TEXT_GAMEOVER="GAME OVER";TEXT_SCORE="SCORE";TEXT_LEVEL="LEVEL";TEXT_PLAY="PLAY";TEXT_HELP="MATCH ALL THE EASTER SYMBOLS TO CLEAR THE LEVEL!!!";
function CInterface(a,b){var e,d,f,h,c,n,l,m,k,g;this._init=function(a,b){var r=s_oSpriteLibrary.getSprite("but_exit");e=new CGfxButton(CANVAS_WIDTH-r.width/2-100,40,r,!0);e.addEventListener(ON_MOUSE_UP,this._onExit,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)d=new CToggle(CANVAS_WIDTH-60,40,s_oSpriteLibrary.getSprite("audio_icon")),d.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);f=new createjs.Text(TEXT_SCORE+": 0","40px walibi0615bold","#000000");f.x=CANVAS_WIDTH/2+2;f.y=CANVAS_HEIGHT-
200;f.textAlign="center";s_oStage.addChild(f);h=new createjs.Text(TEXT_SCORE+": 0","40px walibi0615bold","#f1e10b");h.x=CANVAS_WIDTH/2;h.y=CANVAS_HEIGHT-198;h.textAlign="center";s_oStage.addChild(h);r=s_oSpriteLibrary.getSprite("life");n=createBitmap(r);n.x=14;n.y=10;s_oStage.addChild(n);l=new createjs.Text("X"+b,"40px walibi0615bold","#000000");l.x=n.x+r.width+7;l.y=40;s_oStage.addChild(l);m=new createjs.Text("X"+b,"40px walibi0615bold","#f1e10b");m.x=n.x+r.width+5;m.y=38;s_oStage.addChild(m);k=
new createjs.Text(TEXT_LEVEL+" "+a,"40px walibi0615bold","#000000");k.x=106;k.y=202;k.textAlign="center";s_oStage.addChild(k);g=new createjs.Text(TEXT_LEVEL+" "+a,"40px walibi0615bold","#f1e10b");g.x=104;g.y=200;g.textAlign="center";s_oStage.addChild(g);c=new CEndPanel(s_oSpriteLibrary.getSprite("msg_box"))};this.unload=function(){e.unload();e=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)d.unload(),d=null;s_oStage.removeChild(g);s_oStage.removeChild(l);s_oStage.removeChild(m);s_oStage.removeChild(n);
s_oStage.removeChild(h);s_oStage.removeChild(f)};this.refreshScore=function(a){h.text=TEXT_SCORE+": "+a;f.text=TEXT_SCORE+": "+a};this.refreshLives=function(a){m.text="X"+a;l.text="X"+a};this.refreshLevel=function(a){g.text=TEXT_LEVEL+" "+a;k.text=TEXT_LEVEL+" "+a};this.gameOver=function(a){c.show(a)};this._onExit=function(){s_oGame.onExit()};this._onAudioToggle=function(){createjs.Sound.setMute(!s_bAudioActive)};this._init(a,b);return this}
function CHelpPanel(a){var b,e,d,f;this._init=function(a){d=createBitmap(a);e=new createjs.Text(TEXT_HELP,"44px walibi0615bold","#000");e.textAlign="center";e.lineWidth=560;e.x=CANVAS_WIDTH/2+2;e.y=352;b=new createjs.Text(TEXT_HELP,"44px walibi0615bold","#f1e10b");b.textAlign="center";b.lineWidth=560;b.x=CANVAS_WIDTH/2;b.y=350;f=new createjs.Container;f.addChild(d,e,b);s_oStage.addChild(f);var c=this;f.on("pressup",function(){c._onExitHelp()})};this.unload=function(){s_oStage.removeChild(f);var a=
this;f.off("pressup",function(){a._onExitHelp()})};this._onExitHelp=function(){this.unload()};this._init(a)}
function CGfxButton(a,b,e,d){var f,h,c;this._init=function(a,b,e,d){f=[];h=[];c=createBitmap(e);c.x=a;c.y=b;c.regX=e.width/2;c.regY=e.height/2;d&&s_oStage.addChild(c);this._initListener()};this.unload=function(){c.off("mousedown",this.buttonDown);c.off("pressup",this.buttonRelease);s_oStage.removeChild(c)};this.setVisible=function(a){c.visible=a};this._initListener=function(){c.on("mousedown",this.buttonDown);c.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){f[a]=b;h[a]=c};
this.buttonRelease=function(){c.scaleX=1;c.scaleY=1;f[ON_MOUSE_UP]&&f[ON_MOUSE_UP].call(h[ON_MOUSE_UP])};this.buttonDown=function(){c.scaleX=.9;c.scaleY=.9;f[ON_MOUSE_DOWN]&&f[ON_MOUSE_DOWN].call(h[ON_MOUSE_DOWN])};this.setPosition=function(a,b){c.x=a;c.y=b};this.setX=function(a){c.x=a};this.setY=function(a){c.y=a};this.getButtonImage=function(){return c};this.getX=function(){return c.x};this.getY=function(){return c.y};this._init(a,b,e,d);return this}
function CGame(a){var b,e,d=0,f,h,c,n,l,m,k,g,q=[],v,r,w,t,y,u;this._init=function(){this.createBoard()};this.unload=function(){s_oStage.removeChild(w);for(var a=0;a<BOARD_ROWS;a++)for(var b=0;b<BOARD_COLS;b++)l[a][b].unload()};this.createBoard=function(){l=[];var a=BOARD_OFFSET_X,g=BOARD_OFFSET_Y;b=GAME_STATE_NO_MOVE;e=0;c=1;h=BOARD_ROWS*BOARD_COLS;n=2;f=NUM_LIVES;w=createBitmap(s_oSpriteLibrary.getSprite("game_bg"));s_oStage.addChild(w);var p,d={};for(p=0;p<NUM_COLORS;p++)d["elem_"+p]=[p,p+1];d.invisible=
[NUM_COLORS,NUM_COLORS+1];p={images:[s_oSpriteLibrary.getSprite("elems")],frames:{width:ELEM_SIZE,height:ELEM_SIZE,regX:0,regY:0},animations:d};v=new createjs.SpriteSheet(p);for(p=0;p<BOARD_ROWS;p++){l[p]=[];for(d=0;d<BOARD_COLS;d++){var k=Math.floor(Math.random()*n);l[p][d]=new CBoardElem(p,d,a,g,k,v);a+=ELEM_SIZE}a=BOARD_OFFSET_X;g+=ELEM_SIZE}u=new CInterface(c,NUM_LIVES);t=new createjs.Shape;t.graphics.beginFill("red").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);t.alpha=0;s_oStage.addChild(t);new CHelpPanel(s_oSpriteLibrary.getSprite("bg_help"))};
this.initNextLevel=function(){b=GAME_STATE_NO_MOVE;h=BOARD_ROWS*BOARD_COLS;n<NUM_COLORS&&n++;for(var a=0;a<BOARD_ROWS;a++)for(var g=0;g<BOARD_COLS;g++){var d=Math.floor(Math.random()*n);l[a][g].reset(d)}u.refreshLevel(c)};this._findSimilarAdjacent=function(a,b,c,h,g){var d=a,e=b;do{switch(c){case 0:d=a-1;c++;if(0>d)continue;break;case 1:d=a+1;c++;if(d>=BOARD_ROWS)continue;break;case 2:d=a;e=b-1;c++;if(0>e)continue;break;case 3:if(d=a,e=b+1,c++,e>=BOARD_COLS)continue}l[d][e].getType()===h&&!1===this.findElemInArray(l[d][e],
g)&&(g.push(l[d][e]),this._findSimilarAdjacent(d,e,0,h,g))}while(4>c)};this.elemClicked=function(a,c,d){if(b===GAME_STATE_NO_MOVE){!1===s_bMobile&&this.elemOut();m=[];this._findSimilarAdjacent(a,c,0,d,m);if(1<m.length)e+=SCORE_PER_ELEM*m.length*m.length,u.refreshScore(e),!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("matching");else{f--;u.refreshLives(f);if(0===f){this.gameOver();return}this.showHurt();m.push(l[a][c])}for(a=0;a<m.length;a++)m[a].remove(),h--;this.compactGridVertically();
this.moveElemsDown()}};this.elemOver=function(a,c,d){if(b===GAME_STATE_NO_MOVE)for(k=[],this._findSimilarAdjacent(a,c,0,d,k),a=0;a<k.length;a++)k[a].highlight(!0)};this.elemOut=function(){for(var a=0;a<k.length;a++)k[a].highlight(!1)};this.findElemInArray=function(a,b){for(var c=0;c<b.length;c++)if(b[c]===a)return!0;return!1};this.compactGridVertically=function(){var a=[];g=[];q=[];for(var b=BOARD_ROWS-1;-1<b;b--)for(var c=0;c<BOARD_COLS;c++)-1===l[b][c].getType()&&!1===this.findElemInArray(c,a)&&
(this.findElemsToMoveVertically(b,c),a.push(c))};this.findElemsToMoveVertically=function(a,b){for(var c=a,d=0;-1<c;)-1!==l[c][b].getType()?g.push({row:c,col:b,type:l[c][b].getType(),dist:d}):d+=ELEM_SIZE,c--};this.moveElemsDown=function(){if(0<g.length){b=GAME_STATE_MOVE_VERTICAL;d=g.length;for(var a=0;a<g.length;a++){var c=BOARD_OFFSET_Y+g[a].row*ELEM_SIZE,h=new CMovingElem(BOARD_OFFSET_X+g[a].col*ELEM_SIZE,c,g[a].type,v);q.push(h);c+=g[a].dist;l[g[a].row][g[a].col].hide();h.moveDown(c,Math.floor((c-
BOARD_OFFSET_Y)/ELEM_SIZE),g[a].col)}}else b=GAME_STATE_NO_MOVE,q=[],this.compactGridHorizontally(),this.moveElemRight()};this.compactGridHorizontally=function(){g=[];for(var a=BOARD_COLS-1;-1<a;a--){for(var c=!0,d=0;d<BOARD_ROWS;d++)if(-1!==l[d][a].getType()){c=!1;break}c&&(b=GAME_STATE_MOVE_HORIZONTAL,this.findElemsToMoveHorizontally(a))}};this.findElemsToMoveHorizontally=function(a){for(var b=0;b<BOARD_ROWS;b++)for(var c=0;c<a;c++)if(-1!==l[b][c].getType()){var d=this.checkElemToMove(b,c);-1<d?
g[d].dist+=ELEM_SIZE:g.push({row:b,col:c,type:l[b][c].getType(),dist:ELEM_SIZE})}};this.checkElemToMove=function(a,b){for(var c=0;c<g.length;c++)if(g[c].row===a&&g[c].col===b)return c;return-1};this.moveElemRight=function(){if(0===g.length)b=GAME_STATE_NO_MOVE,q=[],0===h&&this.showNextLevel();else{d=g.length;for(var a=0;a<g.length;a++){var c=BOARD_OFFSET_X+g[a].col*ELEM_SIZE,e=new CMovingElem(c,BOARD_OFFSET_Y+g[a].row*ELEM_SIZE,g[a].type,v);q.push(e);c+=g[a].dist;l[g[a].row][g[a].col].hide();e.moveSide(c,
g[a].row,Math.floor((c-BOARD_OFFSET_X)/ELEM_SIZE))}}};this.updateElemValue=function(a,c,g,e){l[a][c].updateType(g);s_oStage.removeChild(e);d--;0===d&&(q=[],b===GAME_STATE_MOVE_VERTICAL?(b=GAME_STATE_NO_MOVE,this.compactGridHorizontally(),this.moveElemRight()):b===GAME_STATE_MOVE_HORIZONTAL&&(b=GAME_STATE_NO_MOVE,0===h&&this.showNextLevel()))};this.gameOver=function(){r=CEndPanel(s_oSpriteLibrary.getSprite("msg_box"));r.show(e)};this.showNextLevel=function(){c++;y=new CNextLevelPanel(s_oSpriteLibrary.getSprite("msg_box"));
y.show(c)};this.showHurt=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("life_lost");createjs.Tween.get(t).to({alpha:.5},300).call(function(){this.alpha=0})};this.onExit=function(){u.unload();this.unload();s_oMain.gotoMenu();$(s_oMain).trigger("restart")};this.update=function(){for(var a=0;a<q.length;a++)q[a].update(SPEED_MOVE)};s_oGame=this;BOARD_COLS=a.col;BOARD_ROWS=a.row;ELEM_SIZE=a.elem_size;NUM_COLORS=a.num_colors;SCORE_PER_ELEM=a.score_per_elem;SPEED_MOVE=a.speed_move;
NUM_LIVES=a.num_lives;this._init()}var s_oGame;
function CEndPanel(a){var b,e,d,f,h,c;this._init=function(a){b=createBitmap(a);h=new createjs.Text("","70px walibi0615bold","#000");h.x=CANVAS_WIDTH/2+2;h.y=CANVAS_HEIGHT/2-78;h.textAlign="center";f=new createjs.Text("","70px walibi0615bold","#f1e10b");f.x=CANVAS_WIDTH/2;f.y=CANVAS_HEIGHT/2-80;f.textAlign="center";e=new createjs.Text("","44px walibi0615bold","#000");e.x=CANVAS_WIDTH/2+1;e.y=CANVAS_HEIGHT/2+32;e.textAlign="center";d=new createjs.Text("","44px walibi0615bold","#f1e10b");d.x=CANVAS_WIDTH/
2;d.y=CANVAS_HEIGHT/2+30;d.textAlign="center";c=new createjs.Container;c.alpha=0;c.visible=!1;c.addChild(b,e,d,h,f);s_oStage.addChild(c)};this._initListener=function(){c.on("mousedown",this._onExit)};this.show=function(a){if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundTrackSnd.volume=0,createjs.Sound.play("gameover").addEventListener("complete",createjs.proxy(function(){s_oSoundTrackSnd.volume=.5},this));h.text=TEXT_GAMEOVER;f.text=TEXT_GAMEOVER;e.text=TEXT_SCORE+": "+a;d.text=TEXT_SCORE+": "+
a;c.visible=!0;var b=this;createjs.Tween.get(c).to({alpha:1},500).call(function(){b._initListener()});$(s_oMain).trigger("save_score",a)};this._onExit=function(){c.off("mousedown",this._onExit);s_oStage.removeChild(c);s_oGame.onExit()};this._init(a);return this}
function CBoardElem(a,b,e,d,f,h){var c,n,l,m,k,g;this._init=function(a,b,d,h,e,f){l=e;c=a;n=b;m=createSprite(f,"elem_"+e,0,0,ELEM_SIZE,ELEM_SIZE);m.stop();m.x=d;m.y=h;k=createBitmap(s_oSpriteLibrary.getSprite("highlight"));k.x=d;k.y=h;k.visible=!1;g=new createjs.Container;g.addChild(m,k);s_oStage.addChild(g);g.on("pressup",this._onElemClick);!1===s_bMobile&&(g.on("mouseover",this._onElemOver),g.on("mouseout",this._onElemOut))};this.unload=function(){g.off("pressup",this._onElemClick);!1===s_bMobile&&
(g.off("mouseover",this._onElemOver),g.off("mouseout",this._onElemOut));s_oStage.removeChild(g)};this.reset=function(a){l=a;m.gotoAndStop("elem_"+a);m.alpha=1;m.visible=!0};this.hide=function(){m.visible=!1;l=-1};this.remove=function(){m.alpha=0;l=-1};this.highlight=function(a){k.visible=a};this.updateType=function(a){l=a;m.gotoAndStop("elem_"+a);m.alpha=1;m.visible=!0};this._onElemClick=function(){s_oGame.elemClicked(c,n,l)};this._onElemOver=function(){s_oGame.elemOver(c,n,l)};this._onElemOut=function(){s_oGame.elemOut(c,
n,l)};this.getPos=function(){return{row:c,col:n}};this.getRow=function(){return c};this.getCol=function(){return n};this.getType=function(){return l};this._init(a,b,e,d,f,h);return this}
function CSpriteLibrary(){var a,b,e,d,f,h;this.init=function(c,n,l){e=b=0;d=c;f=n;h=l;a={}};this.addSprite=function(c,d){a.hasOwnProperty(c)||(a[c]={szPath:d,oSprite:new Image},b++)};this.getSprite=function(c){return a.hasOwnProperty(c)?a[c].oSprite:null};this._onSpritesLoaded=function(){f.call(h)};this._onSpriteLoaded=function(){d.call(h);++e==b&&this._onSpritesLoaded()};this.loadSprites=function(){for(var c in a)a[c].oSprite.oSpriteLibrary=this,a[c].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
a[c].oSprite.src=a[c].szPath};this.getNumSprites=function(){return b}}var CANVAS_WIDTH=640,CANVAS_HEIGHT=1136,FPS_TIME=1E3/24,DISABLE_SOUND_MOBILE=!0,STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,BOARD_COLS,BOARD_ROWS,ELEM_SIZE,NUM_COLORS,SCORE_PER_ELEM,SPEED_MOVE,NUM_LIVES,GAME_STATE_NO_MOVE=0,GAME_STATE_MOVE_VERTICAL=1,GAME_STATE_MOVE_HORIZONTAL=2,BOARD_OFFSET_X=24,BOARD_OFFSET_Y=247;
function CTweenController(a){var b=0,e=a.oNode.getX(),d=a.oNode.getY(),f=!1;this.tweenValue=function(a,c,b){return a+b*(c-a)};this.start=function(){f=!0};this.easeLinear=function(a,c,b,d){return b*a/d+c};this.easeInCubic=function(a,c,b,d){d=(a/=d)*a*a;return c+b*d};this.easeBackInQuart=function(a,b,d,e){e=(a/=e)*a;return b+d*(2*e*e+2*e*a+-3*e)};this.updateDown=function(){if(!1===f)return!1;var e;b+=s_iTimeElaps;b>=a.iDuration&&(b=a.iDuration,f=!1);e=this.easeInCubic(b,0,1,a.iDuration);a.oNode.setY(this.tweenValue(d,
a.iFinalY,e));return!0};this.updateRight=function(){if(!1===f)return!1;var d;b+=s_iTimeElaps;b>=a.iDuration&&(b=a.iDuration,f=!1);d=this.easeInCubic(b,0,1,a.iDuration);a.oNode.setX(this.tweenValue(e,a.iFinalX,d));return!0}}
function CToggle(a,b,e){var d,f,h;this._init=function(a,b,e){d=[];f=[];var m=new createjs.SpriteSheet({images:[e],frames:{width:e.width/2,height:e.height,regX:e.width/2/2,regY:e.height/2},animations:{on:[0,1],off:[1,2]}});h=s_bAudioActive?createSprite(m,"on",e.width/2/2,e.height/2,e.width/2,e.height):createSprite(m,"off",e.width/2/2,e.height/2,e.width/2,e.height);h.x=a;h.y=b;h.stop();s_oStage.addChild(h);this._initListener()};this.unload=function(){h.off("mousedown",this.buttonDown);h.off("pressup",
this.buttonRelease);s_oStage.removeChild(h)};this._initListener=function(){h.on("mousedown",this.buttonDown);h.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,e){d[a]=b;f[a]=e};this.buttonRelease=function(){h.scaleX=1;h.scaleY=1;(s_bAudioActive=!s_bAudioActive)?h.gotoAndStop("on"):h.gotoAndStop("off");d[ON_MOUSE_UP]&&d[ON_MOUSE_UP].call(f[ON_MOUSE_UP])};this.buttonDown=function(){h.scaleX=.9;h.scaleY=.9;d[ON_MOUSE_DOWN]&&d[ON_MOUSE_DOWN].call(f[ON_MOUSE_DOWN])};this._init(a,b,
e)}
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,4))})(navigator.userAgent||
navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}$(window).ready(function(){sizeHandler()});window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a=CANVAS_WIDTH,b=CANVAS_HEIGHT,e=window.innerWidth;multiplier=Math.min(window.innerHeight/b,e/a);a*=multiplier;b*=multiplier;$("#canvas").css("width",a+"px");$("#canvas").css("height",b+"px");$("#canvas").css("left",e/2-a/2+"px")}}
function createBitmap(a,b,e){var d=new createjs.Bitmap(a),f=new createjs.Shape;b&&e?f.graphics.beginFill("#fff").drawRect(0,0,b,e):f.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);d.hitArea=f;return d}function createSprite(a,b,e,d,f,h){a=null!==b?new createjs.Sprite(a,b):new createjs.Sprite(a);b=new createjs.Shape;b.graphics.beginFill("#000000").drawRect(-e,-d,f,h);a.hitArea=b;return a}
function randomFloatBetween(a,b,e){"undefined"===typeof e&&(e=2);return parseFloat(Math.min(a+Math.random()*(b-a),b).toFixed(e))}function shuffle(a){for(var b=a.length,e,d;0!==b;)d=Math.floor(Math.random()*b),--b,e=a[b],a[b]=a[d],a[d]=e;return a}function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3==a.nodeType&&(a=a.parentNode);var b=document.createEvent("MouseEvents");b.initEvent("click",!0,!0);a.dispatchEvent(b)}}};
function CTextButton(a,b,e,d,f,h,c,n){var l,m,k;this._init=function(a,b,c,d,e,f,h,n){l=[];m=[];var A=createBitmap(c),z=Math.ceil(h/30),p=new createjs.Text(d,h+"px "+e,"#000000");p.textAlign="center";p.textBaseline="middle";p.lineHeight=1;var x=p.getBounds();p.x=c.width/2+z;p.y=Math.floor(c.height/2)+x.height/3+z;d=new createjs.Text(d,h+"px "+e,f);d.textAlign="center";d.textBaseline="middle";d.lineHeight=1;x=d.getBounds();d.x=c.width/2;d.y=Math.floor(c.height/2)+x.height/3;k=new createjs.Container;
k.x=a;k.y=b;k.regX=c.width/2;k.regY=c.height/2;k.addChild(A,p,d);!1!==n&&s_oStage.addChild(k);this._initListener()};this.unload=function(){k.off("mousedown");k.off("pressup");s_oStage.removeChild(k)};this.setVisible=function(a){k.visible=a};this._initListener=function(){oParent=this;k.on("mousedown",this.buttonDown);k.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){l[a]=b;m[a]=c};this.buttonRelease=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");
k.scaleX=1;k.scaleY=1;l[ON_MOUSE_UP]&&l[ON_MOUSE_UP].call(m[ON_MOUSE_UP])};this.buttonDown=function(){k.scaleX=.9;k.scaleY=.9;l[ON_MOUSE_DOWN]&&l[ON_MOUSE_DOWN].call(m[ON_MOUSE_DOWN])};this.setPosition=function(a,b){k.x=a;k.y=b};this.setX=function(a){k.x=a};this.setY=function(a){k.y=a};this.getButtonImage=function(){return k};this.getX=function(){return k.x};this.getY=function(){return k.y};this.getSprite=function(){return k};this._init(a,b,e,d,f,h,c,n);return this}
function CPreloader(){var a;this._init=function(){this._onAllPreloaderImagesLoaded()};this._onPreloaderImagesLoaded=function(){};this._onAllPreloaderImagesLoaded=function(){a=new createjs.Text("","bold 44px Arial center","#ffffff");a.x=CANVAS_WIDTH/2-40;a.y=CANVAS_HEIGHT/2;s_oStage.addChild(a)};this.unload=function(){s_oStage.removeChild(a)};this.refreshLoader=function(b){a.text=b+"%"};this._init()}
function CNextLevelPanel(a){var b,e,d,f;this._init=function(a){e=createBitmap(a);f=new createjs.Text("","70px walibi0615bold","#000000");f.x=CANVAS_WIDTH/2+2;f.y=CANVAS_HEIGHT/2-28;f.textAlign="center";d=new createjs.Text("","70px walibi0615bold","#f1e10b");d.x=CANVAS_WIDTH/2;d.y=CANVAS_HEIGHT/2-30;d.textAlign="center";b=new createjs.Container;b.alpha=0;b.visible=!1;b.addChild(e,f,d);s_oStage.addChild(b);b.on("mousedown",this._onExit)};this.show=function(a){f.text=TEXT_LEVEL+" "+a;d.text=TEXT_LEVEL+
" "+a;b.visible=!0;createjs.Tween.get(b).to({alpha:1},500).call(function(){s_oGame.initNextLevel()})};this._onExit=function(){b.off("mousedown",this._onExit);s_oStage.removeChild(b)};this._init(a)}
function CMovingElem(a,b,e,d){var f,h,c,n,l,m,k,g,q=null;this._init=function(a,b,d,e){h=f=!1;c=a;n=b;l=d;g=createSprite(e,"elem_"+d,0,0,ELEM_SIZE,ELEM_SIZE);g.stop();g.x=a;g.y=b;s_oStage.addChild(g)};this.moveDown=function(a,b,c){n=a;m=b;k=c;this.initTween(g.x,n);f=!0};this.moveSide=function(a,b,d){c=a;m=b;k=d;this.initTween(a,g.y);h=!0};this.initTween=function(a,b){q=new CTweenController({oNode:this,iFinalX:a,iFinalY:b,iDuration:SPEED_MOVE});q.start()};this.setY=function(a){g.y=a};this.setX=function(a){g.x=
a};this.getX=function(){return g.x};this.getY=function(){return g.y};this.update=function(a){f&&!1===q.updateDown()&&(f=!1,g.y=n,s_oGame.updateElemValue(m,k,l,g));h&&!1===q.updateRight()&&(h=!1,g.x=c,s_oGame.updateElemValue(m,k,l,g))};this._init(a,b,e,d)}
function CMenu(){var a,b,e,d;this._init=function(){a=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));s_oStage.addChild(a);var f=s_oSpriteLibrary.getSprite("but_play");b=new CTextButton(CANVAS_WIDTH/2,CANVAS_HEIGHT-100,f,TEXT_PLAY,"walibi0615bold","#f1e10b",60);b.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)e=new CToggle(CANVAS_WIDTH-60,60,s_oSpriteLibrary.getSprite("audio_icon")),e.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);
d=new createjs.Shape;d.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);s_oStage.addChild(d);createjs.Tween.get(d).to({alpha:0},1E3).call(function(){d.visible=!1})};this.unload=function(){b.unload();b=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)e.unload(),e=null;s_oStage.removeChild(a);a=null};this._onButPlayRelease=function(){this.unload();s_oMain.gotoGame()};this._onAudioToggle=function(){createjs.Sound.setMute(!s_bAudioActive)};this._init()}
function CMain(a){var b=0,e=0,d=STATE_LOADING,f,h,c;this.initContainer=function(){var a=document.getElementById("canvas");s_oStage=new createjs.Stage(a);createjs.Touch.enable(s_oStage);s_iPrevTime=(new Date).getTime();s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&s_oStage.enableMouseOver(20);createjs.Ticker.addEventListener("tick",this._update);navigator.userAgent.match(/Windows Phone/i)&&(DISABLE_SOUND_MOBILE=!0);s_oSpriteLibrary=new CSpriteLibrary;h=new CPreloader;!1!==DISABLE_SOUND_MOBILE&&!1!==
s_bMobile||this._initSounds();this._loadImages()};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&(0<navigator.userAgent.indexOf("Opera")||0<navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=["mp3"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.handleFileLoad,this)),createjs.Sound.registerSound("./sounds/gameover.ogg","gameover"),createjs.Sound.registerSound("./sounds/soundtrack.ogg","soundtrack"),createjs.Sound.registerSound("./sounds/matching.ogg",
"matching"),createjs.Sound.registerSound("./sounds/life_lost.ogg","life_lost")):(createjs.Sound.alternateExtensions=["ogg"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.handleFileLoad,this)),createjs.Sound.registerSound("./sounds/gameover.mp3","gameover"),createjs.Sound.registerSound("./sounds/soundtrack.mp3","soundtrack"),createjs.Sound.registerSound("./sounds/matching.mp3","matching"),createjs.Sound.registerSound("./sounds/life_lost.mp3","life_lost")),e+=4)};this.handleFileLoad=
function(){b++;if(b===e){h.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundTrackSnd=createjs.Sound.play("soundtrack",{interrupt:createjs.Sound.INTERRUPT_ANY,loop:-1,volume:.5});this.gotoMenu()}};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("but_play","./sprites/but_play.png");s_oSpriteLibrary.addSprite("but_exit","./sprites/but_exit.png");s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_menu.jpg");s_oSpriteLibrary.addSprite("game_bg",
"./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("msg_box","./sprites/msg_box.png");s_oSpriteLibrary.addSprite("bg_help","./sprites/bg_help.png");s_oSpriteLibrary.addSprite("elems","./sprites/elems.png");s_oSpriteLibrary.addSprite("life","./sprites/life.png");s_oSpriteLibrary.addSprite("highlight","./sprites/highlight.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_icon.png");e+=s_oSpriteLibrary.getNumSprites();s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){b++;
h.refreshLoader(Math.floor(b/e*100));if(b===e){h.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundTrackSnd=createjs.Sound.play("soundtrack",{interrupt:createjs.Sound.INTERRUPT_ANY,loop:-1,volume:.5});this.gotoMenu()}};this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this.gotoMenu=function(){new CMenu;d=STATE_MENU};this.gotoGame=function(){c=new CGame(f);d=STATE_GAME;$(s_oMain).trigger("game_start")};this.gotoHelp=function(){new CHelp;
d=STATE_HELP};this._update=function(a){var b=(new Date).getTime();s_iTimeElaps=b-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=b;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);d===STATE_GAME&&c.update();s_oStage.update(a)};s_oMain=this;f=a;this.initContainer()}var s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_bMobile,s_bAudioActive=!0,s_oSoundTrackSnd,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary;