function CMovingCell(a,c,b,d){var f,h;this._init=function(a,b,c,e){f=c;c=CONFIG[s_iCurLevel].numfaces-1;c={images:[s_oSpriteLibrary.getSprite("faces")],frames:{width:34,height:34,regX:17,regY:17},animations:{green:[0],red:[1],blue:[2],yellow:[3],violet:[4],cyan:[5],star:[6],bomb:[7],clock:[8],changing:[0,c,"changing",.15]}};c=new createjs.SpriteSheet(c);9===f?(h=createSprite(c,"changing",17,17,34,34),h.gotoAndPlay("changing")):(h=createSprite(c,f,17,17,34,34),h.gotoAndStop(f));h.x=a;h.y=b;e.addChild(h)};
this.unload=function(){d.removeChild(h)};this.move=function(a,b){createjs.Tween.get(h).to({x:a,y:b},250,createjs.Ease.linear).call(function(){h.visible=!1;s_oGame.checkMatch()})};this.moveBack=function(){h.visible=!0;createjs.Tween.get(h).to({x:a,y:c},250,createjs.Ease.linear).call(function(){s_oGame.returnInPosition()})};this.fall=function(a,b,c){createjs.Tween.get(h).to({x:a,y:b},TIME_FALL*c,createjs.Ease.linear).call(function(){s_oGame.onFinishFall()})};this.fallStar=function(a,b){createjs.Tween.get(h).to({x:a,
y:b},750,createjs.Ease.bounceOut)};this.setVisible=function(a){h.visible=a};this.getType=function(){return f};this._init(a,c,b,d)}
function CModeMenu(){var a,c,b,d,f,h,m,k,l,e,g,r;this._init=function(){h=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(h);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile){var n=s_oSpriteLibrary.getSprite("audio_icon");b=CANVAS_WIDTH-n.height/2-34;d=n.height/2+7;g=new CToggle(b,d,n,s_bAudioActive);g.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);n=s_oSpriteLibrary.getSprite("music_icon");a=CANVAS_WIDTH-n.height/2-8;c=n.height/2+7;r=new CToggle(a,c,n,s_bMusicActive);r.addEventListener(ON_MOUSE_UP,
this._onMusicToggle,this)}m=new CFormatText(CANVAS_WIDTH/2,25,TEXT_SELECT_LEVEL,"#ffe400",s_oStage,"#ac5124",40);k=new CFormatText(CANVAS_WIDTH/2,460,TEXT_GAMESCORE+" "+s_iTotalScore,"#ffe400",s_oStage,"#ac5124",22);l=new CTextButton(50,460,TEXT_MENU,"#00cf0f",s_oStage,"#FFFFFF",26);l.addEventListener(ON_MOUSE_UP,this._onButMenuRelease,this);n=s_oSpriteLibrary.getSprite("spiele_logo");e=new CGfxButton(CANVAS_WIDTH-50,CANVAS_HEIGHT-43,n);e.addEventListener(ON_MOUSE_UP,this._onButSpieleRelease,this);
e.addShadow(3,2,1);f=[];for(var q=n=0,t=0;25>t;t++){0===t%5&&(n=0,q+=75);f[t+1]=new CLevelButton(120+n,25+q,t+1);f[t+1].addEventListenerWithParams(ON_MOUSE_UP,this._startLevel,this,t+1);var n=n+100,u=JSON.parse(localStorage.getItem("desertface_enable")).levelenabled[t+1];f[t+1].setActive(u);u&&(u=JSON.parse(localStorage.getItem("desertface_score")).scorelevel[t+1],f[t+1].addTextOn(TEXT_SCORE+" "+u,"center"),0<u&&(s_aHelpPanelEnabled[t+1]=!1,f[t+1].setPlayed(!0)))}f[1].setActive(!0)};this.unload=function(){l.unload();
l=null;m.unload();m=null;k.unload();k=null;e.unload();e=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)g.unload(),g=null,r.unload(),r=null;for(var a=1;26>a;a++)f[a].unload();s_oStage.removeChild(h);h=null};this._onAudioToggle=function(){s_bAudioActive=!s_bAudioActive;for(var a in s_aAudioSfx)null===s_aAudioSfx[a]||"click"!==a&&"tada"!==a&&"applause2"!==a&&"applause"!==a&&"boom"!==a&&"break"!==a&&"chime"!==a&&"loser"!==a&&"swoosh"!==a&&"tictac"!==a&&"wood"!==a||s_aAudioSfx[a].setMute(!0)};this._onMusicToggle=
function(){(s_bMusicActive=!s_bMusicActive)?s_oSoundtrack.setMute(!1):s_oSoundtrack.setMute(!0)};this._onButMenuRelease=function(){this.unload();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||!0!==s_bAudioActive||createjs.Sound.play("click");s_oMain.gotoMenu()};this._onButPlayRelease=function(){this.unload();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||createjs.Sound.play("click");s_oMain.gotoGame()};this._startLevel=function(a){this.unload();s_oMain.gotoGame(a)};this._onButSpieleRelease=function(){window.open("http://www.spiele-umsonst.de/?utm_source=desert%2Bfaces&utm_medium=game&utm_campaign=sponsoring")};
this._init()}
function CMenu(){var a,c,b,d,f,h,m,k,l,e,g,r,n,q,t,u,x;this._init=function(){f=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(f);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile){var v=s_oSpriteLibrary.getSprite("audio_icon");b=CANVAS_WIDTH-v.height/2-34;d=v.height/2+7;u=new CToggle(b,d,v,s_bAudioActive);u.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);v=s_oSpriteLibrary.getSprite("music_icon");a=CANVAS_WIDTH-v.height/2-8;c=v.height/2+7;x=new CToggle(a,c,v,s_bMusicActive);
x.addEventListener(ON_MOUSE_UP,this._onMusicToggle,this)}h=new CFormatText(CANVAS_WIDTH/2,50,TEXT_TITLE,"#ffe400",s_oStage,"#ac5124",40);m=new CTextButton(CANVAS_WIDTH/2,125,TEXT_PLAY,"#00cf0f",s_oStage,"#FFFFFF",26);m.addEventListener(ON_MOUSE_UP,this._onButPlayRelease,this);k=new CTextButton(CANVAS_WIDTH/2,175,TEXT_CREDITS,"#00cf0f",s_oStage,"#FFFFFF",26);k.addEventListener(ON_MOUSE_UP,this._onButCreditsRelease,this);l=new CTextButton(CANVAS_WIDTH/2,225,TEXT_SUBMIT,"#00cf0f",s_oStage,"#FFFFFF",
26);l.addEventListener(ON_MOUSE_UP,this._onButSubmitRelease,this);e=new CTextButton(CANVAS_WIDTH/2,275,TEXT_MORE,"#00cf0f",s_oStage,"#FFFFFF",26);e.addEventListener(ON_MOUSE_UP,this._onButMoreRelease,this);g=new CFormatText(CANVAS_WIDTH/2,460,TEXT_GAMESCORE+" "+s_iTotalScore,"#ffe400",s_oStage,"#ac5124",22);v=s_oSpriteLibrary.getSprite("spiele_logo");r=new CGfxButton(CANVAS_WIDTH-50,CANVAS_HEIGHT-43,v);r.addEventListener(ON_MOUSE_UP,this._onButSpieleRelease,this);r.addShadow(3,2,1);v=s_oSpriteLibrary.getSprite("menu_facebook");
n=new CGfxButton(24,CANVAS_HEIGHT-23,v);n.addEventListener(ON_MOUSE_UP,this._onButFacebookRelease,this);n.addShadow(3,2,1);n.setScaleOn(!1);n.addTextOn("share game on Facebook","left");v=s_oSpriteLibrary.getSprite("menu_twitter");q=new CGfxButton(61,CANVAS_HEIGHT-23,v);n.addEventListener(ON_MOUSE_UP,this._onButTwitterRelease,this);q.addShadow(3,2,1);q.setScaleOn(!1);q.addTextOn("share scores on Twitter","left");t=new createjs.Shape;t.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);
s_oStage.addChild(t);createjs.Tween.get(t).to({alpha:0},1E3).call(function(){t.visible=!1})};this.unload=function(){m.unload();m=null;k.unload();k=null;l.unload();l=null;e.unload();e=null;t.visible=!1;h.unload();h=null;g.unload();g=null;r.unload();r=null;n.unload();n=null;q.unload();q=null;if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)u.unload(),u=null,x.unload(),x=null;s_oStage.removeChild(f);s_oMenu=f=null};this._onAudioToggle=function(){s_bAudioActive=!s_bAudioActive;for(var a in s_aAudioSfx)null===
s_aAudioSfx[a]||"click"!==a&&"tada"!==a&&"applause2"!==a&&"applause"!==a&&"boom"!==a&&"break"!==a&&"chime"!==a&&"loser"!==a&&"swoosh"!==a&&"tictac"!==a&&"wood"!==a||(s_aAudioSfx[a].volume=0)};this._onMusicToggle=function(){s_bMusicActive=!s_bMusicActive;s_oSoundtrack.volume=s_bMusicActive?1:0};this._onButPlayRelease=function(){this.unload();s_oMain.goToModeMenu()};this._onButCreditsRelease=function(){this.unload();new CCreditsPanel};this._onButSubmitRelease=function(){$(s_oMain).trigger("submit_score",
s_iTotalScore)};this._onButMoreRelease=function(){window.open("http://www.spiele-umsonst.de/?utm_source=desert%2Bfaces&utm_medium=game&utm_campaign=sponsoring")};this._onButSpieleRelease=function(){window.open("http://www.spiele-umsonst.de/?utm_source=desert%2Bfaces&utm_medium=game&utm_campaign=sponsoring")};this._onButFacebookRelease=function(){window.open("http://www.facebook.com/sharer.php?u=http%3A%2F%2Fbit.ly%2F9lFSZ0&t=Desert%20Faces%20puzzle%20game")};this._onButTwitterRelease=function(){window.open("http://twitter.com/home?status=Scored%20"+
s_iTotalScore+"%20points%20in%20game%20Desert%20Faces%20http%3A%2F%2Fbit.ly%2F9lFSZ0")};s_oMenu=this;this._init()}var s_oMenu=null;
function CMain(a){var c,b=0,d=0,f=STATE_LOADING,h,m,k;this.initContainer=function(){s_oCanvas=document.getElementById("canvas");s_oStage=new createjs.Stage(s_oCanvas);createjs.Touch.enable(s_oStage);s_bMobile=jQuery.browser.mobile;!1===s_bMobile&&(s_oStage.enableMouseOver(20),$("body").on("contextmenu","#canvas",function(a){return!1}));s_iPrevTime=(new Date).getTime();createjs.Ticker.addEventListener("tick",this._update);createjs.Ticker.setFPS(30);navigator.userAgent.match(/Windows Phone/i)&&(DISABLE_SOUND_MOBILE=
!0);s_oSpriteLibrary=new CSpriteLibrary;if(null===localStorage.getItem("desertface")){localStorage.setItem("desertface",!0);s_iTotalScore=0;for(var a=1;26>a;a++)s_aLevelScore[a]=0,s_aLevelEnabled[a]=!1,s_aHelpPanelEnabled[a]=!0;s_aLevelEnabled[1]=!0;localStorage.setItem("desertface_score",JSON.stringify({scorelevel:s_aLevelScore}));localStorage.setItem("desertface_enable",JSON.stringify({levelenabled:s_aLevelEnabled}));localStorage.setItem("desertface_totalscore",0)}else for(s_iTotalScore=localStorage.getItem("desertface_totalscore"),
a=1;26>a;a++){var e=JSON.parse(localStorage.getItem("desertface_score")).scorelevel[a];s_aLevelScore[a]=e;s_aLevelEnabled[a]=JSON.parse(localStorage.getItem("desertface_enable")).levelenabled[a];s_aHelpPanelEnabled[a]=!0}m=new CPreloader};this.updateTotalScore=function(){for(var a=0,e=1;26>e;e++)a+=JSON.parse(localStorage.getItem("desertface_score")).scorelevel[e];localStorage.setItem("desertface_totalscore",a);s_iTotalScore=a};this.preloaderReady=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||
this._initSounds();this._loadImages();c=!0};this.soundLoaded=function(){b++;m.refreshLoader(Math.floor(b/d*100));b===d&&this.startGame()};this._initSounds=function(){createjs.Sound.initializeDefaultPlugins()&&(0<navigator.userAgent.indexOf("Opera")||0<navigator.userAgent.indexOf("OPR")?(createjs.Sound.alternateExtensions=["mp3"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/soundtrack.ogg","soundtrack"),createjs.Sound.registerSound("./sounds/click.ogg",
"click"),createjs.Sound.registerSound("./sounds/tada.ogg","tada"),createjs.Sound.registerSound("./sounds/applause2.ogg","applause2"),createjs.Sound.registerSound("./sounds/applause.ogg","applause"),createjs.Sound.registerSound("./sounds/boom.ogg","boom"),createjs.Sound.registerSound("./sounds/break.ogg","break"),createjs.Sound.registerSound("./sounds/chime.ogg","chime"),createjs.Sound.registerSound("./sounds/loser.ogg","loser"),createjs.Sound.registerSound("./sounds/tictac.ogg","tictac"),createjs.Sound.registerSound("./sounds/wood.ogg",
"wood")):(createjs.Sound.alternateExtensions=["ogg"],createjs.Sound.addEventListener("fileload",createjs.proxy(this.soundLoaded,this)),createjs.Sound.registerSound("./sounds/soundtrack.mp3","soundtrack"),createjs.Sound.registerSound("./sounds/click.mp3","click"),createjs.Sound.registerSound("./sounds/tada.mp3","tada"),createjs.Sound.registerSound("./sounds/applause2.mp3","applause2"),createjs.Sound.registerSound("./sounds/applause.mp3","applause"),createjs.Sound.registerSound("./sounds/boom.mp3",
"boom"),createjs.Sound.registerSound("./sounds/break.mp3","break"),createjs.Sound.registerSound("./sounds/chime.mp3","chime"),createjs.Sound.registerSound("./sounds/loser.mp3","loser"),createjs.Sound.registerSound("./sounds/swoosh.mp3","swoosh"),createjs.Sound.registerSound("./sounds/tictac.mp3","tictac"),createjs.Sound.registerSound("./sounds/wood.mp3","wood")),d+=12)};this._loadImages=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("black_panel",
"./sprites/black_panel.png");s_oSpriteLibrary.addSprite("end_panel","./sprites/end_panel.png");s_oSpriteLibrary.addSprite("pause_panel","./sprites/pause_panel.png");s_oSpriteLibrary.addSprite("bg_game","./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("but_restart","./sprites/but_restart.png");s_oSpriteLibrary.addSprite("but_pause","./sprites/but_pause.png");s_oSpriteLibrary.addSprite("audio_icon","./sprites/audio_sprites.png");s_oSpriteLibrary.addSprite("music_icon","./sprites/music_sprites.png");
s_oSpriteLibrary.addSprite("spiele_logo","./sprites/spiele_logo.png");s_oSpriteLibrary.addSprite("spiele_logo_big","./sprites/spiele_logo_big.png");s_oSpriteLibrary.addSprite("menu_facebook","./sprites/menu_facebook.png");s_oSpriteLibrary.addSprite("menu_twitter","./sprites/menu_twitter.png");s_oSpriteLibrary.addSprite("level_button","./sprites/level_button.png");s_oSpriteLibrary.addSprite("check","./sprites/check.png");s_oSpriteLibrary.addSprite("help_level2","./sprites/help_level2.png");s_oSpriteLibrary.addSprite("help_level3",
"./sprites/help_level3.png");s_oSpriteLibrary.addSprite("cell","./sprites/cell.png");s_oSpriteLibrary.addSprite("block","./sprites/block.png");s_oSpriteLibrary.addSprite("trap","./sprites/trap.png");s_oSpriteLibrary.addSprite("faces","./sprites/faces.png");s_oSpriteLibrary.addSprite("explosion_green","./sprites/explosion_green.png");s_oSpriteLibrary.addSprite("explosion_red","./sprites/explosion_red.png");s_oSpriteLibrary.addSprite("explosion_blue","./sprites/explosion_blue.png");s_oSpriteLibrary.addSprite("explosion_yellow",
"./sprites/explosion_yellow.png");s_oSpriteLibrary.addSprite("explosion_violet","./sprites/explosion_violet.png");s_oSpriteLibrary.addSprite("explosion_cyan","./sprites/explosion_cyan.png");s_oSpriteLibrary.addSprite("explosion_block","./sprites/explosion_block.png");s_oSpriteLibrary.addSprite("explosion_block","./sprites/explosion_block.png");s_oSpriteLibrary.addSprite("explosion_radial","./sprites/explosion_radial.png");s_oSpriteLibrary.addSprite("target","./sprites/target.png");d+=s_oSpriteLibrary.getNumSprites();
s_oSpriteLibrary.loadSprites()};this._onImagesLoaded=function(){b++;m.refreshLoader(Math.floor(b/d*100));b===d&&this.startGame()};this.startGame=function(){m.unload();if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)s_oSoundtrack=new createjs.Sound.play("soundtrack",{loop:-1}),s_aAudioSfx.click=null,s_aAudioSfx.tada=null,s_aAudioSfx.applause2=null,s_aAudioSfx.applause=null,s_aAudioSfx.boom=null,s_aAudioSfx["break"]=null,s_aAudioSfx.chime=null,s_aAudioSfx.loser=null,s_aAudioSfx.swoosh=null,s_aAudioSfx.tictac=
null,s_aAudioSfx.wood=null;this.gotoMenu()};this._onAllImagesLoaded=function(){};this.onAllPreloaderImagesLoaded=function(){this._loadImages()};this.gotoMenu=function(){new CMenu;f=STATE_MENU};this.goToModeMenu=function(){new CModeMenu;f=STATE_MENU};this.gotoGame=function(a){s_iCurLevel=a;k=new CGame(h,a);f=STATE_GAME;$(s_oMain).trigger("game_start")};this.gotoHelp=function(){new CHelp;f=STATE_HELP};this.stopUpdate=function(){c=!1};this.startUpdate=function(){c=!0};this._update=function(a){if(!1!==
c){var e=(new Date).getTime();s_iTimeElaps=e-s_iPrevTime;s_iCntTime+=s_iTimeElaps;s_iCntFps++;s_iPrevTime=e;1E3<=s_iCntTime&&(s_iCurFps=s_iCntFps,s_iCntTime-=1E3,s_iCntFps=0);f===STATE_GAME&&k.update();s_oStage.update(a)}};s_oMain=this;h=a;this.initContainer()}
var s_bMobile,s_bAudioActive=!0,s_bMusicActive=!0,s_aAudioSfx=[],s_aLevelScore=[],s_aLevelEnabled=[],s_aHelpPanelEnabled=[],s_iTotalScore,s_iCntTime=0,s_iTimeElaps=0,s_iPrevTime=0,s_iCntFps=0,s_iCurFps=0,s_iCurLevel,s_oDrawLayer,s_oStage,s_oMain,s_oSpriteLibrary,s_oSoundTrack,s_oCanvas,LEVEL_MATRIX=[],GOALS=[],CONFIG=[];LEVEL_MATRIX[1]=[[0,1,1,1,0],[1,1,1,1,1],[1,1,1,1,1],[1,1,1,1,1],[0,1,1,1,0]];GOALS[1]={green:0,red:15,blue:0,yellow:0,violet:0,cyan:0,star:0,block:0};
CONFIG[1]={time:8E4,numfaces:4,starallowed:!1,bomballowed:!1,clockallowed:!1,changingallowed:!1};LEVEL_MATRIX[2]=[[1,1,1,1,1,1],[1,1,1,1,1,1],[0,1,1,1,1,0],[0,1,1,1,1,0],[1,1,2,1,1,1],[1,1,1,1,1,1]];GOALS[2]={green:20,red:0,blue:0,yellow:20,violet:0,cyan:0,star:0,block:0};CONFIG[2]={time:9E4,numfaces:4,starallowed:!1,bomballowed:!0,clockallowed:!1,changingallowed:!1};LEVEL_MATRIX[3]=[[0,1,1,3,1,1,0],[0,1,1,1,1,1,0],[1,1,1,1,1,1,1],[1,1,1,1,1,1,1],[1,1,1,1,1,1,1],[0,1,1,1,1,1,0]];
GOALS[3]={green:0,red:0,blue:0,yellow:0,violet:0,cyan:0,star:1,block:0};CONFIG[3]={time:75E3,numfaces:4,starallowed:!0,bomballowed:!1,clockallowed:!1,changingallowed:!1};LEVEL_MATRIX[4]=[[0,1,1,1,1,1,0],[1,1,1,1,1,1,1],[4,4,1,1,1,4,4],[4,4,1,1,1,4,4],[0,1,1,1,1,1,0],[0,0,1,1,1,0,0]];GOALS[4]={green:0,red:0,blue:0,yellow:0,violet:0,cyan:0,star:0,block:8};CONFIG[4]={time:9E4,numfaces:4,starallowed:!1,bomballowed:!0,clockallowed:!1,changingallowed:!1};
LEVEL_MATRIX[5]=[[0,0,1,1,0,0],[0,1,1,1,3,0],[1,1,1,1,1,1],[1,1,1,1,1,1],[1,2,1,1,1,1],[1,1,1,1,1,1]];GOALS[5]={green:20,red:0,blue:20,yellow:20,violet:0,cyan:0,star:2,block:0};CONFIG[5]={time:12E4,numfaces:4,starallowed:!0,bomballowed:!0,clockallowed:!1,changingallowed:!1};LEVEL_MATRIX[6]=[[4,4,1,1,1,1,4,4],[4,4,1,1,1,1,4,4],[1,1,1,1,1,1,1,1],[1,1,1,0,0,1,1,1],[1,1,1,0,0,1,1,1],[4,1,1,1,1,1,1,4],[4,1,1,1,2,1,1,4],[4,4,1,1,1,1,4,4]];
GOALS[6]={green:0,red:50,blue:0,yellow:0,violet:0,cyan:0,star:0,block:16};CONFIG[6]={time:12E4,numfaces:4,starallowed:!1,bomballowed:!0,clockallowed:!1,changingallowed:!1};LEVEL_MATRIX[7]=[[0,0,0,1,1,1,0,0,0],[0,0,0,3,1,1,0,0,0],[0,0,1,1,1,1,1,0,0],[0,0,1,1,1,1,1,0,0],[0,4,4,4,4,4,4,4,0],[0,4,1,1,1,1,1,4,0],[1,1,1,1,1,1,1,5,1],[1,1,1,1,0,1,1,1,1]];GOALS[7]={green:0,red:0,blue:0,yellow:0,violet:0,cyan:0,star:2,block:9};CONFIG[7]={time:12E4,numfaces:4,starallowed:!0,bomballowed:!0,clockallowed:!0,changingallowed:!1};
LEVEL_MATRIX[8]=[[1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1],[0,0,0,1,1,0,0,0],[1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1]];GOALS[8]={green:0,red:25,blue:0,yellow:0,violet:25,cyan:0,star:0,block:0};CONFIG[8]={time:135E3,numfaces:5,starallowed:!1,bomballowed:!0,clockallowed:!0,changingallowed:!1};
LEVEL_MATRIX[9]=[[0,0,1,1,1,1,0,0],[0,0,1,1,1,6,0,0],[4,1,1,1,1,1,1,4],[4,1,1,1,1,1,1,4],[4,1,1,1,1,1,1,4],[4,4,4,1,1,4,4,4],[0,0,4,1,1,4,0,0],[0,0,4,4,4,4,0,0]];GOALS[9]={green:0,red:0,blue:0,yellow:0,violet:15,cyan:0,star:0,block:18};CONFIG[9]={time:12E4,numfaces:5,starallowed:!1,bomballowed:!0,clockallowed:!0,changingallowed:!0};
LEVEL_MATRIX[10]=[[0,1,1,1,1,1,1,1,1,0],[0,1,3,1,1,1,1,1,1,0],[1,1,1,4,4,7,4,1,1,1],[1,1,1,4,0,0,4,1,1,1],[1,1,1,4,4,4,4,1,1,1],[1,1,1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1,1,1],[0,1,1,1,0,0,1,1,1,0]];GOALS[10]={green:0,red:0,blue:0,yellow:0,violet:0,cyan:0,star:0,block:10};CONFIG[10]={time:15E4,numfaces:5,starallowed:!0,bomballowed:!0,clockallowed:!0,changingallowed:!0};
LEVEL_MATRIX[11]=[[0,0,0,0,0,1,1,1,1],[0,0,0,0,1,1,1,1,1],[0,0,0,1,1,1,1,1,4],[0,0,1,1,1,1,1,4,4],[0,1,1,1,1,1,4,4,0],[1,1,1,1,1,4,4,0,0],[1,1,1,1,4,4,0,0,0],[1,1,1,4,4,0,0,0,0],[1,1,4,4,0,0,0,0,0]];GOALS[11]={green:0,red:0,blue:0,yellow:0,violet:0,cyan:0,star:0,block:13};CONFIG[11]={time:9E4,numfaces:5,starallowed:!1,bomballowed:!0,clockallowed:!0,changingallowed:!0};
LEVEL_MATRIX[12]=[[3,0,0,0,0,0,0,0,3],[1,1,0,0,0,0,0,1,1],[1,1,1,0,0,0,1,1,1],[1,1,1,1,0,1,1,1,1],[1,1,1,1,3,1,1,1,1],[1,1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1,1],[0,1,1,1,1,1,1,1,0],[0,0,1,1,1,1,1,0,0]];GOALS[12]={green:0,red:0,blue:0,yellow:0,violet:0,cyan:0,star:3,block:0};CONFIG[12]={time:12E4,numfaces:5,starallowed:!0,bomballowed:!0,clockallowed:!0,changingallowed:!0};
LEVEL_MATRIX[13]=[[4,4,4,0,4,4,4,4,4,4,4],[1,1,1,0,1,1,1,1,1,1,1],[1,1,1,0,1,1,1,1,1,1,1],[1,1,1,0,1,1,1,0,1,1,1],[1,1,1,0,1,1,1,0,1,1,1],[1,1,1,1,1,1,1,0,1,1,1],[1,1,1,1,1,1,1,0,1,1,1],[4,4,4,4,4,4,4,0,4,4,4]];GOALS[13]={green:0,red:0,blue:0,yellow:0,violet:0,cyan:0,star:0,block:20};CONFIG[13]={time:14E4,numfaces:5,starallowed:!0,bomballowed:!0,clockallowed:!0,changingallowed:!0};
LEVEL_MATRIX[14]=[[0,0,0,0,0,1,1,3,1],[0,0,1,1,3,1,1,1,1],[1,1,1,1,1,1,1,1,1],[1,1,1,1,1,8,8,1,1],[1,1,1,1,1,8,8,1,1],[1,1,1,1,1,1,1,1,1],[0,0,1,1,1,1,1,1,1],[0,0,0,0,0,1,1,1,1]];GOALS[14]={green:0,red:0,blue:0,yellow:0,violet:0,cyan:0,star:2,block:0};CONFIG[14]={time:12E4,numfaces:5,starallowed:!1,bomballowed:!0,clockallowed:!0,changingallowed:!0};
LEVEL_MATRIX[15]=[[0,1,1,1,1,1,1,1,1,1,0],[1,1,1,1,1,1,1,1,1,1,1],[1,1,1,1,0,0,0,1,1,1,1],[1,1,1,0,4,4,4,0,1,1,1],[4,4,4,0,4,4,4,0,4,4,4],[4,4,4,0,4,4,4,0,4,4,4],[4,4,4,1,0,0,0,1,4,4,4],[1,1,1,1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1,1,1,1],[0,8,8,1,1,1,1,1,8,8,0]];GOALS[15]={green:0,red:0,blue:0,yellow:0,violet:0,cyan:0,star:0,block:27};CONFIG[15]={time:18E4,numfaces:5,starallowed:!1,bomballowed:!0,clockallowed:!0,changingallowed:!0};
LEVEL_MATRIX[16]=[[1,3,1,1,0,0,0,1,1,3,1],[1,1,1,1,1,0,1,1,1,1,1],[1,1,1,1,1,1,1,1,1,1,1],[8,8,8,8,8,8,8,8,8,8,8],[1,1,1,1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1,1,1,1],[1,1,1,1,1,0,1,1,1,1,1],[1,1,1,1,1,0,1,1,1,1,1]];GOALS[16]={green:0,red:0,blue:0,yellow:0,violet:15,cyan:0,star:2,block:0};CONFIG[16]={time:105E3,numfaces:5,starallowed:!1,bomballowed:!0,clockallowed:!0,changingallowed:!0};
LEVEL_MATRIX[17]=[[1,1,1,1,0,1,1,1,1],[1,1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1,1],[0,1,1,1,0,1,1,1,0],[1,1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1,1],[1,1,1,1,0,1,1,1,1]];GOALS[17]={green:0,red:0,blue:0,yellow:0,violet:0,cyan:15,star:0,block:0};CONFIG[17]={time:12E4,numfaces:6,starallowed:!1,bomballowed:!0,clockallowed:!0,changingallowed:!0};
LEVEL_MATRIX[18]=[[1,1,1,0,0,0,0,0,0,1,1,1],[1,1,1,1,1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1,1,1,1,1],[0,4,1,1,1,1,1,1,1,1,4,0],[0,4,1,1,1,1,1,1,1,1,4,0],[0,4,4,1,1,1,1,1,1,4,4,0],[1,1,4,1,1,0,0,1,1,4,1,1],[1,1,4,1,1,0,0,1,1,4,1,1],[1,1,1,0,0,0,0,0,0,1,1,1]];GOALS[18]={green:0,red:0,blue:0,yellow:0,violet:0,cyan:0,star:0,block:12};CONFIG[18]={time:9E4,numfaces:6,starallowed:!1,bomballowed:!0,clockallowed:!0,changingallowed:!0};
LEVEL_MATRIX[19]=[[1,1,1,0,0,0,0,0,1,1,1],[1,1,1,1,0,0,0,1,1,1,1],[4,4,1,1,8,8,8,1,1,4,4],[1,4,4,1,1,1,1,1,4,4,1],[1,1,4,4,1,1,1,4,4,1,1],[1,1,1,4,4,1,4,4,1,1,1],[1,1,1,0,4,4,4,0,1,1,1],[1,1,1,0,0,0,0,0,1,1,1],[1,1,1,0,0,0,0,0,1,1,1],[1,1,1,0,0,0,0,0,1,1,1]];GOALS[19]={green:0,red:0,blue:0,yellow:0,violet:0,cyan:0,star:0,block:19};CONFIG[19]={time:165E3,numfaces:6,starallowed:!1,bomballowed:!0,clockallowed:!0,changingallowed:!0};
LEVEL_MATRIX[20]=[[0,0,0,0,4,4,4,4],[0,0,0,0,4,1,1,4],[0,0,0,0,1,1,1,1],[0,4,1,1,1,1,1,1],[4,4,1,1,1,1,1,1],[1,1,1,1,1,1,4,4],[1,1,1,1,1,1,4,0],[1,1,1,1,0,0,0,0],[4,1,1,4,0,0,0,0],[4,4,4,4,0,0,0,0]];GOALS[20]={green:0,red:0,blue:0,yellow:0,violet:0,cyan:0,star:0,block:18};CONFIG[20]={time:165E3,numfaces:6,starallowed:!1,bomballowed:!0,clockallowed:!0,changingallowed:!0};
LEVEL_MATRIX[21]=[[0,1,1,1,1,1,1,1,0],[1,1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1,1],[1,1,1,1,0,1,1,1,1],[1,1,1,0,0,0,1,1,1],[1,1,1,1,0,1,1,1,1],[1,1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1,1],[0,1,1,1,1,1,1,1,0]];GOALS[21]={green:0,red:0,blue:0,yellow:0,violet:0,cyan:0,star:1,block:4};CONFIG[21]={time:18E4,numfaces:6,starallowed:!0,bomballowed:!0,clockallowed:!0,changingallowed:!0};
LEVEL_MATRIX[22]=[[0,0,0,0,4,4,0,0,0,0],[0,0,0,4,4,4,4,0,0,0],[0,0,4,4,4,4,4,4,0,0],[0,4,4,4,4,4,4,4,4,0],[1,1,1,1,0,0,1,1,1,1],[1,1,1,1,0,0,1,1,1,1],[1,1,1,8,8,8,8,1,1,1],[1,1,1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1,1,1]];GOALS[22]={green:0,red:0,blue:0,yellow:0,violet:0,cyan:0,star:0,block:30};CONFIG[22]={time:18E4,numfaces:6,starallowed:!1,bomballowed:!0,clockallowed:!0,changingallowed:!0};
LEVEL_MATRIX[23]=[[1,1,1,1,1,1,1,1,1],[1,1,4,4,4,4,4,1,1],[0,4,4,4,4,4,4,4,0],[0,0,1,1,1,1,1,0,0],[0,0,8,1,1,1,8,0,0],[0,0,8,1,1,1,8,0,0],[0,0,1,1,1,1,1,0,0],[0,4,4,4,4,4,4,4,0],[1,1,4,4,4,4,4,1,1],[1,1,1,1,1,1,1,1,1]];GOALS[23]={green:0,red:0,blue:0,yellow:0,violet:0,cyan:0,star:0,block:24};CONFIG[23]={time:165E3,numfaces:6,starallowed:!1,bomballowed:!0,clockallowed:!0,changingallowed:!0};
LEVEL_MATRIX[24]=[[1,3,1,0,0,0,0,0,0,0,1,3,1],[1,1,1,0,0,0,0,0,0,0,1,1,1],[1,1,1,0,0,0,0,0,0,0,1,1,1],[1,1,1,0,0,4,4,4,0,0,1,1,1],[1,1,1,0,0,4,1,4,0,0,1,1,1],[1,1,1,0,0,4,1,4,0,0,1,1,1],[1,1,1,4,4,4,1,4,4,4,1,1,1],[1,1,1,1,1,1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1,1,1,1,1,1]];GOALS[24]={green:0,red:0,blue:0,yellow:0,violet:0,cyan:0,star:2,block:13};CONFIG[24]={time:18E4,numfaces:6,starallowed:!0,bomballowed:!0,clockallowed:!0,changingallowed:!0};
LEVEL_MATRIX[25]=[[1,1,1,1,1,3,1,1,1,1,1,1],[1,1,1,1,1,1,1,1,1,1,1,1],[1,3,1,1,1,4,4,1,1,1,3,1],[8,1,1,0,0,4,4,0,0,1,1,8],[8,1,1,1,4,4,4,4,1,1,1,8],[8,1,1,1,4,4,4,4,1,1,1,8],[8,1,1,0,0,4,4,0,0,1,1,8],[1,1,1,1,1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1,1,1,1,1]];GOALS[25]={green:0,red:0,blue:0,yellow:0,violet:30,cyan:30,star:3,block:14};CONFIG[25]={time:24E4,numfaces:6,starallowed:!1,bomballowed:!0,clockallowed:!0,changingallowed:!0};
function CLevelButton(a,c,b){var d,f,h,m,k=[],l,e,g,r,n,q,t,u;this._init=function(a,b,c){f=!0;d=!1;l=[];e=[];g=new createjs.Container;g.x=a;g.y=b;a=s_oSpriteLibrary.getSprite("level_button");b=new createjs.SpriteSheet({images:[a],frames:{width:a.width/2,height:a.height,regX:a.width/2/2,regY:a.height/2},animations:{state_active:[0],state_disabled:[1]}});r=createSprite(b,"state_active",a.width/2/2,a.height/2,a.width/2,a.height);h=a.width;m=a.height;g.addChild(r);t=new createjs.Text(c,"bold 40px Roboto",
"#ffffff");t.textAlign="center";t.textBaseline="middle";g.addChild(t);a=s_oSpriteLibrary.getSprite("check");n=createBitmap(a);n.regX=a.width/4;n.regY=a.height/2;n.x=a.width;n.y=-a.height;n.visible=!1;g.addChild(n);c=(new createjs.Graphics).beginFill("rgba(158,158,158,0.01)").drawRect(-h/4,-m/2,h/2,m);u=new createjs.Shape(c);g.addChild(u);s_oStage.addChild(g);this._initListener()};this.unload=function(){s_bMobile?g.off("mousedown",this.buttonDown):(g.off("mousedown",this.buttonDown),g.off("mouseover",
this.buttonOver),g.off("mouseout",this.buttonOut));g.off("pressup",this.buttonRelease);s_oStage.removeChild(g)};this.setVisible=function(a){g.visible=a};this._initListener=function(){if(s_bMobile)g.on("mousedown",this.buttonDown);else g.on("mousedown",this.buttonDown),g.on("mouseover",this.buttonOver),g.on("mouseout",this.buttonOut);g.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){l[a]=b;e[a]=c};this.addEventListenerWithParams=function(a,b,c,d){l[a]=b;e[a]=c;k=d};this.addShadow=
function(a,b,e){g.shadow=new createjs.Shadow("rgba(100,100,100,0.4)",a,b,e)};this.buttonRelease=function(){f&&l[ON_MOUSE_UP]&&l[ON_MOUSE_UP].call(e[ON_MOUSE_UP],k)};this.buttonOver=function(){f&&(s_bMobile||!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||!0!==s_bAudioActive||(s_aAudioSfx.click=createjs.Sound.play("click"),s_aAudioSfx.click.addEventListener("complete",function(){s_aAudioSfx.click=null})),g.scaleX=1.1,g.scaleY=1.1);d&&q.setVisible(!0)};this.buttonOut=function(){f&&(g.scaleX=1,g.scaleY=1);
d&&q.setVisible(!1)};this.buttonDown=function(){f&&(l[ON_MOUSE_DOWN]&&l[ON_MOUSE_DOWN].call(e[ON_MOUSE_DOWN],k),!s_bMobile||!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||!0!==s_bAudioActive||(s_aAudioSfx.click=createjs.Sound.play("click"),s_aAudioSfx.click.addEventListener("complete",function(){s_aAudioSfx.click=null})))};this.addTextOn=function(a,b){d=!0;"left"===b?(q=new CFormatText(-h/4,-m/2-10,a,"#ffe400",g,"#ac5124",14),q.setAlign("left")):"center"===b&&(q=new CFormatText(0,-m/2-10,a,"#ffe400",
g,"#ac5124",14),q.setAlign("center"));q.setVisible(!1)};this.setPlayed=function(a){n.visible=a};this.setActive=function(a){(f=a)?r.gotoAndStop("state_active"):r.gotoAndStop("state_disabled")};this.setPosition=function(a,b){g.x=a;g.y=b};this.setX=function(a){g.x=a};this.setY=function(a){g.y=a};this.getButtonImage=function(){return g};this.getX=function(){return g.x};this.getY=function(){return g.y};this._init(a,c,b);return this}TEXT_GAMEOVER="Level failed!";TEXT_TIMEUP="Time is up";TEXT_RETRY="Retry";
TEXT_WIN="Level complete!";TEXT_TIMEBONUS="Time bonus:";TEXT_TOTAL="Total:";TEXT_NEXT="Next level";TEXT_TITLE="Desert Faces";TEXT_PLAY="Play";TEXT_CREDITS="Credits";TEXT_SUBMIT="Submit scores";TEXT_MORE="More games";TEXT_HOST="Host this game";TEXT_GAMESCORE="Game scores:";TEXT_RESTART="RESTART";TEXT_ISPAUSED="Game is paused";TEXT_CONTINUE="Continue";TEXT_OK="OK";TEXT_SELECT_LEVEL="Select level";TEXT_MENU="Menu";TEXT_LEVEL="Level";TEXT_SCORES="Scores:";TEXT_SCORE="Score:";TEXT_TIME="Time left:";
TEXT_GOALS="Goals:";TEXT_HELP1="Match 3 or more faces in a row. Click one face, then click another face to swap them. You can swap only nearby faces.\n\nLevel goals are displayed in the right side of the screen. First level goals - destroy 15 red faces.\n\nThe time is limited.";TEXT_HELP2="Click the bomb to explode it. That will destroy nearby faces.\nThe bombs will fall from time to time.";TEXT_HELP3="On some levels you will have to collect the treasure chests.\nTo collect a chest - move it to the bottom of field by destroying faces under it.\nWhen chest reaches one of the bottom-cells - the chest is collected.";
TEXT_HELP4="Barriers can be removed by destroying the faces in cells where barriers are located.\n\n\n\n\nBomb also can be used for destroying the barriers.\nGoal of this level is to destroy 8 barriers.";TEXT_HELP7="Click the clock to get extra 15 seconds to the time limit.";TEXT_HELP8="New face type added: violet face.\n\n\n\nDestroy 25 violet and 25 red faces to win the level.";TEXT_HELP9="Face exploder.\n\n\n\nWhen you click it - it will destroy all faces of certain type in the level.\nThe type of faces that will be destroyed is dependent on the face-type that was on face-exploder when you clicked it.";
TEXT_HELP14="Guarded cell.\n\n\n\nYou can't swap faces in such cells. You also can't explode bombs located in such cells or collected any other bonuses in these cells.";TEXT_HELP17="New face type added: cyan face.\n\n\n\nDestroy 15 cyan faces to win the level.";TEXT_CONGRATULATIONS="Congratulations!";TEXT_END_2="You finished the game! Well done!";TEXT_END_3="You can submit your scores.";TEXT_END_4="Now you can replay some levels to get more scores there. When you improve your result - you can submit your improved scores again";
TEXT_CREDITS_HEADER="Desert Faces \u00a9 2010";TEXT_CREDITS_SPONSORED="Sponsored by:";TEXT_CREDITS_DEVELOPER="Developed by: Vyacheslav Stepanov\nstepanov.vyacheslav@gmail.com\n\nMusic by: Mr. Flicker";
function CInterface(a){var c,b,d,f,h,m,k,l,e,g,r,n,q,t,u,x,v=null,J,H;this._init=function(a){H=new CFormatText(CANVAS_WIDTH/2,15,TEXT_LEVEL+" "+a,"#ffe400",s_oStage,"#ac5124",18);l=new CFormatText(77,15,TEXT_SCORES+" 000000","#ffe400",s_oStage,"#ac5124",18);a=s_oSpriteLibrary.getSprite("but_restart");e=new CGfxButton(430,18,a);e.addShadow(3,2,1);e.addEventListener(ON_MOUSE_UP,this._onButRestartRelease);e.addTextOn("Restart","bot");a=s_oSpriteLibrary.getSprite("but_pause");g=new CGfxButton(470,18,
a);g.addShadow(3,2,1);g.addEventListener(ON_MOUSE_UP,this._onButPauseRelease);g.addTextOn("Pause","bot");r=new CTextButton(50,460,TEXT_MENU,"#00cf0f",s_oStage,"#FFFFFF",26);r.addEventListener(ON_MOUSE_UP,this._onButMenuRelease,this);n=new CTextButton(460,460,TEXT_SELECT_LEVEL,"#00cf0f",s_oStage,"#FFFFFF",26);n.addEventListener(ON_MOUSE_UP,this._onButLevelMenuRelease,this);t=new CFormatText(580,100,TEXT_TIME,"#ffe400",s_oStage,"#ac5124",18);u=new CFormatText(580,125,"0:00","#ffe400",s_oStage,"#ac5124",
18);x=new CFormatText(580,170,TEXT_GOALS,"#ffe400",s_oStage,"#ac5124",18);this._setGoals();J=new createjs.Container;s_oStage.addChild(J);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)a=s_oSpriteLibrary.getSprite("audio_icon"),c=CANVAS_WIDTH-a.height/2-34,b=a.height/2+7,m=new CToggle(c,b,a,s_bAudioActive),m.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this),a=s_oSpriteLibrary.getSprite("music_icon"),d=CANVAS_WIDTH-a.height/2-8,f=a.height/2+7,k=new CToggle(d,f,a,s_bMusicActive),k.addEventListener(ON_MOUSE_UP,
this._onMusicToggle,this);a=s_oSpriteLibrary.getSprite("spiele_logo");q=new CGfxButton(CANVAS_WIDTH-50,CANVAS_HEIGHT-43,a);q.addEventListener(ON_MOUSE_UP,this._onButSpieleRelease,this);q.addShadow(3,2,1)};this.unload=function(){H.unload();H=null;l.unload();l=null;q.unload();q=null;r.unload();r=null;n.unload();n=null;e.unload();e=null;g.unload();g=null;t.unload();t=null;u.unload();u=null;x.unload();x=null;for(var a=0;a<h.length;a++)s_oStage.removeChild(h[a].image);if(!1===DISABLE_SOUND_MOBILE||!1===
s_bMobile)m.unload(),m=null,k.unload(),k=null};this.getPanelContainer=function(){return J};this.refreshScore=function(a){a+="";a=6<=a.length?a:Array(6-a.length+1).join("0")+a;l.setText(TEXT_SCORES+" "+a)};this.refreshTime=function(a){a=formatTime(a);u.setText(a)};this._setGoals=function(){h=[];0<GOALS[a].green&&h.push({type:0,num:GOALS[a].green,image:null,text:null});0<GOALS[a].red&&h.push({type:1,num:GOALS[a].red,image:null,text:null});0<GOALS[a].blue&&h.push({type:2,num:GOALS[a].blue,image:null,
text:null});0<GOALS[a].yellow&&h.push({type:3,num:GOALS[a].yellow,image:null,text:null});0<GOALS[a].violet&&h.push({type:4,num:GOALS[a].violet,image:null,text:null});0<GOALS[a].cyan&&h.push({type:5,num:GOALS[a].cyan,image:null,text:null});0<GOALS[a].star&&h.push({type:6,num:GOALS[a].star,image:null,text:null});0<GOALS[a].block&&h.push({type:7,num:GOALS[a].block,image:null,text:null});for(var b=s_oSpriteLibrary.getSprite("faces"),e=new createjs.SpriteSheet({images:[b],frames:{width:34,height:34,regX:17,
regY:17},animations:{green:[0],red:[1],blue:[2],yellow:[3],violet:[4],cyan:[5],star:[6]}}),c=0;c<h.length;c++)7===h[c].type?(b=s_oSpriteLibrary.getSprite("block"),h[c].image=createBitmap(b),h[c].image.x=560,h[c].image.y=205+36*c,h[c].image.regX=b.width/2,h[c].image.regY=b.height/2):(h[c].image=createSprite(e,h[c].type,17,17,34,34),h[c].image.gotoAndStop(h[c].type),h[c].image.x=560,h[c].image.y=205+36*c),h[c].image.scaleX=.75,h[c].image.scaleY=.75,s_oStage.addChild(h[c].image),h[c].text=new CFormatText(600,
205+36*c,"0 / "+h[c].num,"#ffe400",s_oStage,"#ac5124",14)};this.refreshGoals=function(a,c){for(var b=0;b<h.length;b++)h[b].type===a&&(h[b].text.setText(c+" / "+h[b].num),c>=h[b].num&&h[b].text.setColor("#42ff42","#008800"))};this._onButHelpRelease=function(){v=new CHelpPanel};this._onButRestartRelease=function(){s_oGame.restartGame()};this._onButPauseRelease=function(){s_oGame.pauseGame()};this._onButMenuRelease=function(){s_oGame.unload();s_oMain.gotoMenu()};this._onButLevelMenuRelease=function(){s_oGame.unload();
s_oMain.goToModeMenu()};this._onButSpieleRelease=function(){window.open("http://www.spiele-umsonst.de/?utm_source=desert%2Bfaces&utm_medium=game&utm_campaign=sponsoring")};this.onExitFromHelp=function(){v.unload()};this._onAudioToggle=function(){s_bAudioActive=!s_bAudioActive;for(var a in s_aAudioSfx)null===s_aAudioSfx[a]||"click"!==a&&"tada"!==a&&"applause2"!==a&&"applause"!==a&&"boom"!==a&&"break"!==a&&"chime"!==a&&"loser"!==a&&"swoosh"!==a&&"tictac"!==a&&"wood"!==a||s_aAudioSfx[a].setMute(!0)};
this._onMusicToggle=function(){(s_bMusicActive=!s_bMusicActive)?s_oSoundtrack.setMute(!1):s_oSoundtrack.setMute(!0)};this._onExit=function(){s_oGame.onExit()};s_oInterface=this;this._init(a);return this}var s_oInterface=null;
function CHelpPanel(a){var c,b=null,d=null,f,h,m;this._init=function(a){if(s_aHelpPanelEnabled[s_iCurLevel]){h=createBitmap(s_oSpriteLibrary.getSprite("pause_panel"));h.on("click",function(){});a.addChild(h);var l=CONFIG[s_iCurLevel].numfaces-1,e=s_oSpriteLibrary.getSprite("faces"),l=new createjs.SpriteSheet({images:[e],frames:{width:34,height:34,regX:17,regY:17},animations:{green:[0],red:[1],blue:[2],yellow:[3],violet:[4],cyan:[5],star:[6],bomb:[7],clock:[8],changing:[0,l,"changing",.15]}});if(1===
s_iCurLevel)c=new CFormatText(125,100,TEXT_HELP1,"#ffe400",a,"#ac5124",22),c.setAlign("left");else if(2===s_iCurLevel)c=new CFormatText(125,100,TEXT_HELP2,"#ffe400",a,"#ac5124",22),c.setAlign("left"),e=s_oSpriteLibrary.getSprite("help_level2"),b=createBitmap(e),b.regX=e.width/2,b.regY=e.height/2,b.x=CANVAS_WIDTH/2,b.y=CANVAS_HEIGHT/2+20,a.addChild(b);else if(3===s_iCurLevel)c=new CFormatText(125,100,TEXT_HELP3,"#ffe400",a,"#ac5124",22),c.setAlign("left"),c.setWidth(250),e=s_oSpriteLibrary.getSprite("help_level3"),
b=createBitmap(e),b.regX=e.width/2,b.regY=e.height/2,b.x=CANVAS_WIDTH/2+130,b.y=CANVAS_HEIGHT/2-30,a.addChild(b);else if(4===s_iCurLevel)c=new CFormatText(125,100,TEXT_HELP4,"#ffe400",a,"#ac5124",22),c.setAlign("left"),e=s_oSpriteLibrary.getSprite("block"),b=createBitmap(e),b.regX=e.width/2,b.regY=e.height/2,b.x=CANVAS_WIDTH/2,b.y=CANVAS_HEIGHT/2-30,a.addChild(b);else if(7===s_iCurLevel)c=new CFormatText(CANVAS_WIDTH/2,150,TEXT_HELP7,"#ffe400",a,"#ac5124",22),d=createSprite(l,8,17,17,34,34),d.gotoAndStop(8),
d.x=CANVAS_WIDTH/2,d.y=CANVAS_HEIGHT/2,a.addChild(d);else if(8===s_iCurLevel)c=new CFormatText(125,150,TEXT_HELP8,"#ffe400",a,"#ac5124",22),c.setAlign("left"),d=createSprite(l,4,17,17,34,34),d.gotoAndStop(4),d.x=CANVAS_WIDTH/2,d.y=CANVAS_HEIGHT/2-45,a.addChild(d);else if(9===s_iCurLevel)c=new CFormatText(125,100,TEXT_HELP9,"#ffe400",a,"#ac5124",22),c.setAlign("left"),d=createSprite(l,"changing",17,17,34,34),d.gotoAndPlay("changing"),d.x=CANVAS_WIDTH/2,d.y=CANVAS_HEIGHT/2-90,a.addChild(d);else if(14===
s_iCurLevel)c=new CFormatText(125,120,TEXT_HELP14,"#ffe400",a,"#ac5124",22),c.setAlign("left"),e=s_oSpriteLibrary.getSprite("trap"),b=createBitmap(e),b.regX=e.width/2,b.regY=e.height/2,b.x=CANVAS_WIDTH/2,b.y=CANVAS_HEIGHT/2-75,a.addChild(b);else if(17===s_iCurLevel)c=new CFormatText(125,120,TEXT_HELP17,"#ffe400",a,"#ac5124",22),c.setAlign("left"),d=createSprite(l,5,17,17,34,34),d.gotoAndStop(5),d.x=CANVAS_WIDTH/2,d.y=CANVAS_HEIGHT/2-70,a.addChild(d);else{s_oGame.onExitHelp();a.removeChild(h);return}f=
new CTextButton(CANVAS_WIDTH/2,370,TEXT_OK,"#00cf0f",a,"#FFFFFF",26);f.addEventListener(ON_MOUSE_UP,this._onButContinueRelease,this)}else s_oGame.onExitHelp()};this.unload=function(){c.unload();c=null;f.unload();f=null;null!==d&&(a.removeChild(d),d=null);null!==b&&(a.removeChild(b),b=null);h.off("click",function(){});a.removeChild(h)};this._onExitHelp=function(){m.unload();s_oGame._onExitHelp()};this._onButContinueRelease=function(){this.unload();s_oGame.onExitHelp()};m=this;this._init(a)}
function CGfxButton(a,c,b){var d,f,h,m,k=[],l,e,g,r,n;this._init=function(a,b,c){d=!0;f=!1;l=[];e=[];g=new createjs.Container;g.x=a;g.y=b;r=createBitmap(c);r.regX=c.width/2;r.regY=c.height/2;h=c.width;m=c.height;g.addChild(r);s_oStage.addChild(g);this._initListener()};this.unload=function(){s_bMobile?g.off("mousedown",this.buttonDown):(g.off("mousedown",this.buttonDown),g.off("mouseover",this.buttonOver),g.off("mouseout",this.buttonOut));g.off("pressup",this.buttonRelease);s_oStage.removeChild(g)};
this.setVisible=function(a){g.visible=a};this._initListener=function(){if(s_bMobile)g.on("mousedown",this.buttonDown);else g.on("mousedown",this.buttonDown),g.on("mouseover",this.buttonOver),g.on("mouseout",this.buttonOut);g.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){l[a]=b;e[a]=c};this.addEventListenerWithParams=function(a,b,c,d){l[a]=b;e[a]=c;k=d};this.addShadow=function(a,b,c){};this.buttonRelease=function(){l[ON_MOUSE_UP]&&l[ON_MOUSE_UP].call(e[ON_MOUSE_UP],k)};this.buttonOver=
function(){s_bMobile||!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||!0!==s_bAudioActive||(s_aAudioSfx.click=createjs.Sound.play("click"),s_aAudioSfx.click.addEventListener("complete",function(){s_aAudioSfx.click=null}));d&&(g.scaleX=1.1,g.scaleY=1.1);f&&n.setVisible(!0)};this.buttonOut=function(){d&&(g.scaleX=1,g.scaleY=1);f&&n.setVisible(!1)};this.buttonDown=function(){!s_bMobile||!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||!0!==s_bAudioActive||(s_aAudioSfx.click=createjs.Sound.play("click"),s_aAudioSfx.click.addEventListener("complete",
function(){s_aAudioSfx.click=null}));l[ON_MOUSE_DOWN]&&l[ON_MOUSE_DOWN].call(e[ON_MOUSE_DOWN],k)};this.setScaleOn=function(a){d=a};this.addTextOn=function(a,b){f=!0;"left"===b?(n=new CFormatText(-h/2,-m/2-10,a,"#ffe400",g,"#ac5124",14),n.setAlign("left")):"center"===b?(n=new CFormatText(0,-m/2-10,a,"#ffe400",g,"#ac5124",14),n.setAlign("center")):"bot"===b&&(n=new CFormatText(0,+m/2+12,a,"#ffe400",g,"#ac5124",14),n.setAlign("center"));n.setVisible(!1)};this.setPosition=function(a,b){g.x=a;g.y=b};this.setX=
function(a){g.x=a};this.setY=function(a){g.y=a};this.getButtonImage=function(){return g};this.getX=function(){return g.x};this.getY=function(){return g.y};this._init(a,c,b);return this}
function CGame(a,c){var b,d,f,h,m,k,l,e,g,r,n,q,t,u,x,v,J,H,A,I,K,E,y,L,M,P,G,N,O,z,Q,R,p,w,C,F,S=null,T,D,B;this._init=function(){m=h=f=d=!1;P=K=A=0;x=CONFIG[c].numfaces;v=H=v=J=0;G=CONFIG[c].time+1E3;N=TIMER_TIME;O=TIMER_CHANGING;r=[];l=[];for(var a=0;8>a;a++)l[a]=!1;0===GOALS[c].block&&(l[7]=!0);p=null;a=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(a);z=new createjs.Container;z.x=270;z.y=CANVAS_HEIGHT/2-5;s_oStage.addChild(z);Q=new createjs.Container;Q.x=270;Q.y=CANVAS_HEIGHT/
2-5;s_oStage.addChild(Q);E=LEVEL_MATRIX[c][0].length;y=LEVEL_MATRIX[c].length;this._buildLevel();a=s_oSpriteLibrary.getSprite("target");C=createBitmap(a);C.regX=a.width/2;C.regY=a.height/2;C.visible=!1;z.addChild(C);this.initialMatch();b=!1;k=[];for(var e=Object.keys(GOALS[c]).length,a=0;a<e;a++)k[a]=0;F=new CInterface(c);R=F.getPanelContainer();F.refreshTime(G-1E3);new CHelpPanel(R);this._initHammer()};this._initHammer=function(){B=new Hammer(s_oCanvas);B.get("swipe").set({direction:Hammer.DIRECTION_ALL});
B.get("swipe").set({velocity:.005});B.get("swipe").set({threshold:.1});B.on("swipeleft",function(){D._swipeControl("left")});B.on("swiperight",function(){D._swipeControl("right")});B.on("swipeup",function(){D._swipeControl("up")});B.on("swipedown",function(){D._swipeControl("down")})};this._swipeControl=function(a){if(null!==p&&!b){b=!0;switch(a){case "left":if(0===p.col||e[p.row][p.col-1].getType()===CELL_STATE_DISABLE||7===e[p.row][p.col-1].getType()||9===e[p.row][p.col-1].getType()||e[p.row][p.col-
1].getTrap()){b=!1;return}w={row:p.row,col:p.col-1,cell:null};break;case "right":if(p.col===E-1||e[p.row][p.col+1].getType()===CELL_STATE_DISABLE||7===e[p.row][p.col+1].getType()||9===e[p.row][p.col+1].getType()||e[p.row][p.col+1].getTrap()){b=!1;return}w={row:p.row,col:p.col+1,cell:null};break;case "up":if(0===p.row||e[p.row-1][p.col].getType()===CELL_STATE_DISABLE||7===e[p.row-1][p.col].getType()||9===e[p.row-1][p.col].getType()||e[p.row-1][p.col].getTrap()){b=!1;return}w={row:p.row-1,col:p.col,
cell:null};break;case "down":if(p.row===y-1||e[p.row+1][p.col].getType()===CELL_STATE_DISABLE||7===e[p.row+1][p.col].getType()||9===e[p.row+1][p.col].getType()||e[p.row+1][p.col].getTrap()){b=!1;return}w={row:p.row+1,col:p.col,cell:null}}this._swapFaces()}};this._createRandomFace=function(){var a=Math.floor(Math.random()*x);0===H&&J<GOALS[c].star&&CONFIG[c].starallowed&&2>Math.round(10*Math.random())&&(J++,H++,a=6);CONFIG[c].bomballowed&&20<v&&(v=0,a=7);if(CONFIG[c].clockallowed&&f){var b=G/1E3,e=
Math.random();1>(15>b?50*e:30>b?80*e:60>b?200*e:300*e)&&(a=8,f=!1)}CONFIG[c].changingallowed&&1.5>100*Math.random()&&h&&(a=9,h=!1);return a};this._buildLevel=function(){var a=-(LEVEL_MATRIX[c][0].length*CELL_SIZE/2)+CELL_SIZE/2,b=-(LEVEL_MATRIX[c].length*CELL_SIZE)/2+CELL_SIZE/2;e=[];for(var d=0;d<y;d++){e[d]=[];for(var g=0;g<E;g++){var f=Math.floor(Math.random()*x);LEVEL_MATRIX[c][d][g]===CELL_FILL_FACE?e[d][g]=new CCell(a+g*CELL_SIZE,b+d*CELL_SIZE,d,g,z,f,!1,!1):LEVEL_MATRIX[c][d][g]===CELL_FILL_NULL?
e[d][g]=new CCell(a+g*CELL_SIZE,b+d*CELL_SIZE,d,g,z,CELL_STATE_DISABLE,!1,!1):LEVEL_MATRIX[c][d][g]===CELL_FILL_BOMB?e[d][g]=new CCell(a+g*CELL_SIZE,b+d*CELL_SIZE,d,g,z,7,!1,!1):LEVEL_MATRIX[c][d][g]===CELL_FILL_STAR?(e[d][g]=new CCell(a+g*CELL_SIZE,b+d*CELL_SIZE,d,g,z,6,!1,!1),J++,H++,r.push({row:d,col:g})):LEVEL_MATRIX[c][d][g]===CELL_FILL_BLOCK?e[d][g]=new CCell(a+g*CELL_SIZE,b+d*CELL_SIZE,d,g,z,f,!0,!1):LEVEL_MATRIX[c][d][g]===CELL_FILL_CLOCK?e[d][g]=new CCell(a+g*CELL_SIZE,b+d*CELL_SIZE,d,g,
z,8,!1,!1):LEVEL_MATRIX[c][d][g]===CELL_FILL_CHANGE?e[d][g]=new CCell(a+g*CELL_SIZE,b+d*CELL_SIZE,d,g,z,9,!1,!1):LEVEL_MATRIX[c][d][g]===CELL_FILL_STARANDBLOCK?e[d][g]=new CCell(a+g*CELL_SIZE,b+d*CELL_SIZE,d,g,z,6,!0,!1):LEVEL_MATRIX[c][d][g]===CELL_FILL_TRAP&&(e[d][g]=new CCell(a+g*CELL_SIZE,b+d*CELL_SIZE,d,g,z,f,!1,!0))}}};this.initialMatch=function(){do{g=[];this._matchHorizontal();this._matchVertical();for(var a,b=0;b<g.length;b++)a=Math.floor(Math.random()*x),e[g[b].row][g[b].col].setType(a),
e[g[b].row][g[b].col].setToDelete(!1)}while(0<g.length);this._refreshMatrix()};this._matchHorizontal=function(){var a,b;r=[];t=[];for(var c=0;c<y;c++){b=e[c][0].getType();for(var d=a=0;d<E;d++)if(6===e[c][d].getType()&&r.push({row:c,col:d}),e[c][d].getType()===b&&d===E-1&&0<=e[c][d].getType()&&6>e[c][d].getType()){if(a++,3<=a){for(var f=0;f<a;f++)e[c][d-f].setToDelete(!0),g.push({row:c,col:d-f});t.push(a)}}else if(e[c][d].getType()===b&&d!==E-1&&0<=e[c][d].getType()&&6>e[c][d].getType())a++;else{if(3<=
a){for(f=0;f<a;f++)e[c][d-1-f].setToDelete(!0),g.push({row:c,col:d-1-f});t.push(a)}a=1;b=e[c][d].getType()}}};this._matchVertical=function(){var a,b;u=[];for(var c=0;c<E;c++){b=e[0][c].getType();for(var d=a=0;d<y;d++)if(e[d][c].getType()===b&&d===y-1&&0<=e[d][c].getType()&&6>e[d][c].getType()){if(a++,3<=a){for(var f=0;f<a;f++)e[d-f][c].getToDelete()||(e[d-f][c].setToDelete(!0),g.push({row:d-f,col:c}));u.push(a)}}else if(e[d][c].getType()===b&&d!==y-1&&0<=e[d][c].getType()&&6>e[d][c].getType())a++;
else{if(3<=a){for(f=0;f<a;f++)e[d-1-f][c].getToDelete()||(e[d-1-f][c].setToDelete(!0),g.push({row:d-1-f,col:c}));u.push(a)}a=1;b=e[d][c].getType()}}};this._refreshMatrix=function(){for(var a=0;a<g.length;a++)e[g[a].row][g[a].col].setToDelete(!1)};this._swapFaces=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||!0!==s_bAudioActive||(s_aAudioSfx.swoosh=createjs.Sound.play("swoosh"),s_aAudioSfx.swoosh.addEventListener("complete",function(){s_aAudioSfx.swoosh=null}));var a=e[p.row][p.col].getPos().x,
b=e[p.row][p.col].getPos().y,c=e[w.row][w.col].getPos().x,d=e[w.row][w.col].getPos().y;L=e[p.row][p.col].getType();M=e[w.row][w.col].getType();p.cell=new CMovingCell(a,b,L,z);w.cell=new CMovingCell(c,d,M,z);p.cell.move(c,d);w.cell.move(a,b);e[p.row][p.col].setType(CELL_STATE_INVISIBLE);e[w.row][w.col].setType(CELL_STATE_INVISIBLE)};this._checkStar=function(){for(var a=0;a<r.length;a++)if(r[a].row===y-1){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||!0!==s_bAudioActive||(s_aAudioSfx.chime=createjs.Sound.play("chime"),
s_aAudioSfx.chime.addEventListener("complete",function(){s_aAudioSfx.chime=null}));g.push({row:y-1,col:r[a].col});var b=new CMovingCell(e[y-1][r[a].col].getPos().x,e[y-1][r[a].col].getPos().y,6,z);b.fallStar(e[y-1][r[a].col].getPos().x,220);H--;this._updateScore(SCORES_FOR_STAR)}else{for(var b=!1,c=r[a].row+1;c<y;c++)if(e[c][r[a].col].getType()===CELL_STATE_DISABLE)b=!0;else{b=!1;break}b&&(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||!0!==s_bAudioActive||(s_aAudioSfx.chime=createjs.Sound.play("chime"),
s_aAudioSfx.chime.addEventListener("complete",function(){s_aAudioSfx.chime=null})),g.push({row:r[a].row,col:r[a].col}),b=new CMovingCell(e[r[a].row][r[a].col].getPos().x,e[r[a].row][r[a].col].getPos().y,6,z),b.fallStar(e[r[a].row][r[a].col].getPos().x,220),H--,this._updateScore(SCORES_FOR_STAR))}r=[]};this._checkBombArea=function(a,c){b=!0;e[a][c].setToDelete(!0);g=[];v++;for(var d=a-1;d<a+2;d++)for(var f=c-1;f<c+2;f++)0<=d&&d<y&&0<=f&&f<E&&e[d][f].getType()!==CELL_STATE_DISABLE&&(7!==e[d][f].getType()||
e[d][f].getToDelete()||D._checkBombArea(d,f),6!==e[d][f].getType()&&8!==e[d][f].getType()&&9!==e[d][f].getType()&&e[d][f].setToDelete(!0))};this._detonateBomb=function(a,b){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||!0!==s_bAudioActive||(s_aAudioSfx.boom=createjs.Sound.play("boom"),s_aAudioSfx.boom.addEventListener("complete",function(){s_aAudioSfx.boom=null}));this._checkBombArea(a,b);for(var c=0;c<y;c++)for(var d=0;d<E;d++)e[c][d].getToDelete()&&g.push({row:c,col:d});this._updateScore((g.length-
v)*SCORES_FOR_SINGLE+v*SCORES_FOR_BOMB);v=0;this._explosion()};this._checkSameFaces=function(a){for(var b=0;b<y;b++)for(var c=0;c<E;c++)e[b][c].getType()===a&&g.push({row:b,col:c})};this.checkCellClicked=function(a,c,d){if(!b)if(7===d)this._detonateBomb(a,c),C.visible=!1;else if(8===d)b=!0,G+=TIME_TO_ADD,g.push({row:a,col:c}),C.visible=!1,this._explosion();else if(9===e[a][c].getType())b=!0,g.push({row:a,col:c}),C.visible=!1,this._checkSameFaces(d),this._updateScore(g.length*SCORES_FOR_SINGLE),this._explosion();
else if(null===p)p={row:a,col:c,cell:null},C.visible=!0,C.x=e[a][c].getPos().x,C.y=e[a][c].getPos().y;else if(p.row!==a||p.col!==c)2>Math.abs(a-p.row)&&0===c-p.col||0===a-p.row&&2>Math.abs(c-p.col)?(w={row:a,col:c,cell:null},b=!0,this._swapFaces()):(p={row:a,col:c,cell:null},C.x=e[a][c].getPos().x,C.y=e[a][c].getPos().y)};this.checkMatch=function(){K++;if(2===K){g=[];e[p.row][p.col].setType(M);e[w.row][w.col].setType(L);this._matchHorizontal();this._matchVertical();if(0<g.length)this._checkStar(),
v+=g.length,this._explosion();else{!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||!0!==s_bAudioActive||(s_aAudioSfx.swoosh=createjs.Sound.play("swoosh"),s_aAudioSfx.swoosh.addEventListener("complete",function(){s_aAudioSfx.swoosh=null}));var a=e[p.row][p.col].getPos().x,c=e[p.row][p.col].getPos().y,b=e[w.row][w.col].getPos().x,d=e[w.row][w.col].getPos().y;e[p.row][p.col].setType(L);e[w.row][w.col].setType(M);p.cell.moveBack(a,c);w.cell.moveBack(b,d);e[p.row][p.col].setType(CELL_STATE_INVISIBLE);e[w.row][w.col].setType(CELL_STATE_INVISIBLE)}K=
0}};this._explosion=function(){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||!0!==s_bAudioActive||(s_aAudioSfx["break"]=createjs.Sound.play("break"),s_aAudioSfx["break"].addEventListener("complete",function(){s_aAudioSfx["break"]=null}));var a,c;n=[];for(var b=0;b<E;b++)n[b]=0;this._updateGoals();for(b=0;b<g.length;b++)a=g[b].row,c=g[b].col,n[c]++,e[a][c].setType(CELL_STATE_MATCHED);C.visible=!1;this._updateMatchScore();setTimeout(this._fallFaces,500)};this._fallFaces=function(){q=[];for(var a=0;a<E;a++)if(0<
n[a]){var c;c=!1;for(var b=y-1;0<=b;b--)e[b][a].getType()===CELL_STATE_MATCHED&&(c=!0),0<=e[b][a].getType()&&c&&q.push({jump:0,startrow:b,endrow:null,col:a,cell:new CMovingCell(e[b][a].getPos().x,e[b][a].getPos().y,e[b][a].getType(),z)});for(var d=0;d<n[a];d++)c=D._createRandomFace(),q.push({jump:0,startrow:-(d+1),endrow:null,col:a,cell:new CMovingCell(e[0][a].getPos().x,e[0][a].getPos().y-CELL_SIZE*(d+1),c,z)})}for(var g=0,a=0;a<E;a++)if(0<n[a]){for(var f=[],d=0;d<y;d++)f[d]=e[d][a].getType();c=
!1;for(b=y-1;0<=b;b--)e[b][a].getType()===CELL_STATE_MATCHED&&(c=!0),0<=e[b][a].getType()&&c&&e[b][a].setType(CELL_STATE_INVISIBLE);for(d=y-1;0<=d;d--)if(f[d]===CELL_STATE_MATCHED){q[g].endrow=d;q[g].jump=d-q[g].startrow;c=!1;for(b=y-1;0<=b;b--)if(f[b]===CELL_STATE_MATCHED&&(c=!0),0<=f[b]&&c){f[b]=CELL_STATE_MATCHED;break}g++}}for(a=0;a<q.length;a++)d=e[q[a].endrow][q[a].col].getPos().x,c=e[q[a].endrow][q[a].col].getPos().y,q[a].cell.fall(d,c,q[a].jump)};this.onFinishFall=function(){P++;if(P===q.length){for(var a=
P=0;a<q.length;a++){q[a].cell.unload();var c=q[a].endrow,d=q[a].col,f=q[a].cell.getType();e[c][d].setType(f)}this._refreshMatrix();g=[];this._matchHorizontal();this._matchVertical();this._checkStar();0<g.length?this._explosion():(null!==p&&null!==p.cell&&(p.cell.unload(),w.cell.unload()),p=w=null,b=!1);this._checkWin()}};this.printMatrix=function(){for(var a=0;a<y;a++)for(var c=0;c<E;c++)trace("["+a+"]["+c+"]="+e[a][c].getType());trace("########################")};this.returnInPosition=function(){K++;
2===K&&(e[p.row][p.col].setType(L),e[w.row][w.col].setType(M),p.cell.unload(),w.cell.unload(),p=w=null,C.visible=!1,K=0,b=!1)};this.updateGoalsForBlock=function(){k[7]++;0<GOALS[c].block?(F.refreshGoals(7,k[7]),k[7]>=GOALS[c].block&&(l[7]=!0)):l[7]=!0};this._updateGoals=function(){for(var a,b=0;b<g.length;b++)a=e[g[b].row][g[b].col].getType(),7>a&&k[a]++;0<GOALS[c].green?(F.refreshGoals(0,k[0]),k[0]>=GOALS[c].green&&(l[0]=!0)):l[0]=!0;0<GOALS[c].red?(F.refreshGoals(1,k[1]),k[1]>=GOALS[c].red&&(l[1]=
!0)):l[1]=!0;0<GOALS[c].blue?(F.refreshGoals(2,k[2]),k[2]>=GOALS[c].blue&&(l[2]=!0)):l[2]=!0;0<GOALS[c].yellow?(F.refreshGoals(3,k[3]),k[3]>=GOALS[c].yellow&&(l[3]=!0)):l[3]=!0;0<GOALS[c].violet?(F.refreshGoals(4,k[4]),k[4]>=GOALS[c].violet&&(l[4]=!0)):l[4]=!0;0<GOALS[c].cyan?(F.refreshGoals(5,k[5]),k[5]>=GOALS[c].cyan&&(l[5]=!0)):l[5]=!0;0<GOALS[c].star?(F.refreshGoals(6,k[6]),k[6]>=GOALS[c].star&&(l[6]=!0)):l[6]=!0};this._updateMatchScore=function(){for(var a=0,c=0;c<t.length;c++)for(var b=0;b<
t[c];b++)a=2<b?Math.round(a*EXTRA_FACE_MULTIPLIER):a+SCORES_FOR_SINGLE;for(c=0;c<u.length;c++)for(b=0;b<u[c];b++)a=2<b?Math.round(a*EXTRA_FACE_MULTIPLIER):a+SCORES_FOR_SINGLE;this._updateScore(a)};this._updateScore=function(a){A+=a;F.refreshScore(A)};this._checkWin=function(){if(d){for(var a=0;a<l.length;a++)if(!1===l[a])return;d=!1;I=Math.round(G/1E3*30);this.gameOver(!0)}};this.unload=function(){d=!1;F.unload();null!==S&&(S.unload(),S=null);p=null;for(var a=0;a<e.length;a++)for(var c=0;c<e[a].length;c++)e[a][c].unload();
B.off("swipeleft",function(){D._swipeControl("left")});B.off("swiperight",function(){D._swipeControl("right")});B.off("swipeup",function(){D._swipeControl("up")});B.off("swipedown",function(){D._swipeControl("down")});createjs.Tween.removeAllTweens();s_oStage.removeAllChildren()};this.restartGame=function(){b||(this.unload(),this._init())};this.pauseGame=function(){b||(d=!1,T=new CPausePanel(R),B.off("swipeleft",function(){D._swipeControl("left")}),B.off("swiperight",function(){D._swipeControl("right")}),
B.off("swipeup",function(){D._swipeControl("up")}),B.off("swipedown",function(){D._swipeControl("down")}))};this.resumeGame=function(){d=!0;T.unload();this._initHammer()};this.onNextLevel=function(a){s_aLevelScore[s_iCurLevel]=a;localStorage.setItem("desertface_score",JSON.stringify({scorelevel:s_aLevelScore}));s_oMain.updateTotalScore();this.unload();s_iCurLevel++;26===s_iCurLevel?new CEndPanel(A,I):(s_aLevelEnabled[s_iCurLevel]=!0,localStorage.setItem("desertface_enable",JSON.stringify({levelenabled:s_aLevelEnabled})),
s_oMain.gotoGame(s_iCurLevel))};this.onExit=function(){this.unload();s_oMain.gotoMenu();$(s_oMain).trigger("restart")};this.onExitHelp=function(){d=!0};this.gameOver=function(a){d=!1;if(25!==s_iCurLevel)S=new CNextLevelPanel(a,A,I,R);else s_oGame.onNextLevel(A+I)};this._timeTimer=function(){N-=s_iTimeElaps;0>N&&(N=TIMER_TIME,f=!0)};this._changingFaceTimer=function(){O-=s_iTimeElaps;0>O&&(O=TIMER_TIME,h=!0)};this.update=function(){d&&(!f&&CONFIG[c].clockallowed&&this._timeTimer(),!h&&CONFIG[c].changingallowed&&
this._changingFaceTimer(),G-=s_iTimeElaps,16E3>G&&!m&&(m=!0,!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||!0!==s_bAudioActive||(s_aAudioSfx.tictac=createjs.Sound.play("tictac"),s_aAudioSfx.tictac.addEventListener("complete",function(){s_aAudioSfx.tictac=null}))),0>G&&(G=0,d=!1,this.gameOver(!1)),F.refreshTime(G))};s_oGame=this;SCORES_FOR_SINGLE=a.scores_for_single;SCORES_FOR_BOMB=a.scores_for_bomb;SCORES_FOR_STAR=a.scores_for_star;EXTRA_FACE_MULTIPLIER=a.extra_face_multiplier;D=this;this._init()}var s_oGame;
function CFormatText(a,c,b,d,f,h,m){var k,l,e,g;this._init=function(a,c,b,d,f,h,m){k=b;g=new createjs.Container;g.x=a;g.y=c;f.addChild(g);a=m+"px";l=new createjs.Text;l.text=k;l.font="bold "+a+" Roboto";l.color=h;l.textAlign="center";l.textBaseline="middle";l.lineWidth=375;l.outline=3;g.addChild(l);e=new createjs.Text;e.text=k;e.font="bold "+a+" Roboto";e.color=d;e.textAlign="center";e.textBaseline="middle";e.lineWidth=375;g.addChild(e)};this.unload=function(){f.removeChild(g)};this.setVisible=function(a){g.visible=
a};this.isVisible=function(){return g.visible};this.setOutline=function(a){l.outline=a};this.setShadow=function(a){l.shadow=a?new createjs.Shadow("#333333",2,2,6):null};this.setAlign=function(a){l.textAlign=a;e.textAlign=a};this.setWidth=function(a){l.lineWidth=a;e.lineWidth=a};this.setText=function(a){e.text=a;l.text=a};this.setColor=function(a,c){e.color=a;l.color=c};this.getText=function(){return g};this.setPos=function(a){g.y=a};this.getPos=function(){return{x:g.x,y:g.y}};this._init(a,c,b,d,f,
h,m)}
function CEndPanel(a,c){var b,d,f,h,m,k,l,e,g,r,n,q,t,u,x,v;this._init=function(a,c){!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||!0!==s_bAudioActive||(s_aAudioSfx.tada=createjs.Sound.play("tada"),s_aAudioSfx.tada.addEventListener("complete",function(){s_aAudioSfx.tada=null}),s_aAudioSfx.applause=createjs.Sound.play("applause"),s_aAudioSfx.applause.addEventListener("complete",function(){s_aAudioSfx.applause=null}));var A=a+c;r=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(r);m=
new CFormatText(CANVAS_WIDTH/2,120,TEXT_CONGRATULATIONS,"#ffe400",s_oStage,"#ac5124",30);k=new CFormatText(CANVAS_WIDTH/2,160,TEXT_END_2,"#ffe400",s_oStage,"#ac5124",24);l=new CFormatText(CANVAS_WIDTH/2,194,TEXT_END_3,"#ffe400",s_oStage,"#ac5124",24);g=new CFormatText(CANVAS_WIDTH/2-150,260,TEXT_SCORES+" "+A,"#ffe400",s_oStage,"#ac5124",24);n=new CTextButton(CANVAS_WIDTH/2+150,260,TEXT_SUBMIT,"#00cf0f",s_oStage,"#FFFFFF",26);n.addEventListener(ON_MOUSE_UP,this._onButSubmitRelease,this);e=new CFormatText(CANVAS_WIDTH/
2,320,TEXT_END_4,"#ffe400",s_oStage,"#ac5124",18);e.setWidth(600);q=new CTextButton(150,400,TEXT_MENU,"#00cf0f",s_oStage,"#FFFFFF",26);q.addEventListener(ON_MOUSE_UP,this._onButMenuRelease,this);t=new CTextButton(460,400,TEXT_SELECT_LEVEL,"#00cf0f",s_oStage,"#FFFFFF",26);t.addEventListener(ON_MOUSE_UP,this._onButLevelMenuRelease,this);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)A=s_oSpriteLibrary.getSprite("audio_icon"),f=CANVAS_WIDTH-A.height/2-34,h=A.height/2+7,x=new CToggle(f,h,A,s_bAudioActive),
x.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this),A=s_oSpriteLibrary.getSprite("music_icon"),b=CANVAS_WIDTH-A.height/2-8,d=A.height/2+7,v=new CToggle(b,d,A,s_bMusicActive),v.addEventListener(ON_MOUSE_UP,this._onMusicToggle,this);A=s_oSpriteLibrary.getSprite("spiele_logo");u=new CGfxButton(CANVAS_WIDTH-50,CANVAS_HEIGHT-43,A);u.addEventListener(ON_MOUSE_UP,this._onButSpieleRelease,this);u.addShadow(3,2,1)};this.unload=function(){u.unload();u=null;m.unload();k.unload();l.unload();e.unload();g.unload();
n.unload();q.unload();t.unload();s_oStage.removeChild(r);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)x.unload(),x=null,v.unload(),v=null};this._onButSubmitRelease=function(){$(s_oMain).trigger("submit_score",s_iTotalScore)};this._onButMenuRelease=function(){this.unload();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||!0!==s_bAudioActive||createjs.Sound.play("click");s_oMain.gotoMenu()};this._onButLevelMenuRelease=function(){this.unload();!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||!0!==s_bAudioActive||
(s_aAudioSfx.click=createjs.Sound.play("click"),s_aAudioSfx.click.addEventListener("complete",function(){s_aAudioSfx.click=null}));s_oMain.goToModeMenu()};this._onButSpieleRelease=function(){window.open("http://www.spiele-umsonst.de/?utm_source=desert%2Bfaces&utm_medium=game&utm_campaign=sponsoring")};this._onAudioToggle=function(){s_bAudioActive=!s_bAudioActive;for(var a in s_aAudioSfx)null===s_aAudioSfx[a]||"click"!==a&&"tada"!==a&&"applause2"!==a&&"applause"!==a&&"boom"!==a&&"break"!==a&&"chime"!==
a&&"loser"!==a&&"swoosh"!==a&&"tictac"!==a&&"wood"!==a||s_aAudioSfx[a].setMute(!0)};this._onMusicToggle=function(){(s_bMusicActive=!s_bMusicActive)?s_oSoundtrack.setMute(!1):s_oSoundtrack.setMute(!0)};this._init(a,c)}
function CCreditsPanel(){var a,c,b,d,f,h,m,k,l;this._init=function(){f=createBitmap(s_oSpriteLibrary.getSprite("bg_game"));s_oStage.addChild(f);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile){var e=s_oSpriteLibrary.getSprite("audio_icon");b=CANVAS_WIDTH-e.height/2-34;d=e.height/2+7;k=new CToggle(b,d,e,s_bAudioActive);k.addEventListener(ON_MOUSE_UP,this._onAudioToggle,this);e=s_oSpriteLibrary.getSprite("music_icon");a=CANVAS_WIDTH-e.height/2-8;c=e.height/2+7;l=new CToggle(a,c,e,s_bMusicActive);l.addEventListener(ON_MOUSE_UP,
this._onMusicToggle,this)}e=s_oSpriteLibrary.getSprite("spiele_logo_big");m=new CGfxButton(CANVAS_WIDTH/2,CANVAS_HEIGHT/2-60,e);m.addEventListener(ON_MOUSE_UP,this._onButSpieleRelease,this);m.addShadow(3,2,1);h=new CTextButton(50,460,TEXT_MENU,"#00cf0f",s_oStage,"#FFFFFF",26);h.addEventListener(ON_MOUSE_UP,this._onButMenuRelease,this);_oMsgText=new CFormatText(CANVAS_WIDTH/2,50,TEXT_CREDITS_HEADER,"#ffe400",s_oStage,"#ac5124",30);_oMsgText2=new CFormatText(CANVAS_WIDTH/2,100,TEXT_CREDITS_SPONSORED,
"#ffe400",s_oStage,"#ac5124",20);_oMsgText3=new CFormatText(CANVAS_WIDTH/2,280,TEXT_CREDITS_DEVELOPER,"#ffe400",s_oStage,"#ac5124",20)};this.unload=function(){m.unload();m=null;h.unload();h=null;s_oStage.removeChild(f);if(!1===DISABLE_SOUND_MOBILE||!1===s_bMobile)k.unload(),k=null,l.unload(),l=null};this._onButMenuRelease=function(){this.unload();s_oMain.gotoMenu()};this._onButSpieleRelease=function(){window.open("http://www.spiele-umsonst.de/?utm_source=desert%2Bfaces&utm_medium=game&utm_campaign=sponsoring")};
this._onAudioToggle=function(){s_bAudioActive=!s_bAudioActive;for(var a in s_aAudioSfx)null===s_aAudioSfx[a]||"click"!==a&&"tada"!==a&&"applause2"!==a&&"applause"!==a&&"boom"!==a&&"break"!==a&&"chime"!==a&&"loser"!==a&&"swoosh"!==a&&"tictac"!==a&&"wood"!==a||s_aAudioSfx[a].setMute(!0)};this._onMusicToggle=function(){(s_bMusicActive=!s_bMusicActive)?s_oSoundtrack.setMute(!1):s_oSoundtrack.setMute(!0)};this._init()}
function CCell(a,c,b,d,f,h,m,k){var l,e,g,r,n,q,t,u,x;this._init=function(a,c,b,d,f,h,k,m){l=!1;e=k;g=m;r=h;n=new createjs.Container;n.x=a;n.y=c;0<=r&&f.addChild(n);b=s_oSpriteLibrary.getSprite("cell");d=createBitmap(b);a=b.width;c=b.height;d.regX=a/2;d.regY=c/2;n.addChild(d);e&&(b=s_oSpriteLibrary.getSprite("block"),t=createBitmap(b),t.regX=b.width/2,t.regY=b.height/2,n.addChild(t));d=CONFIG[s_iCurLevel].numfaces-1;b=s_oSpriteLibrary.getSprite("faces");b=new createjs.SpriteSheet({images:[b],frames:{width:34,
height:34,regX:17,regY:17},animations:{green:[0],red:[1],blue:[2],yellow:[3],violet:[4],cyan:[5],star:[6],bomb:[7],clock:[8],changing:[0,d,"changing",.15]}});9===r?(q=createSprite(b,"changing",17,17,34,34),q.gotoAndPlay("changing")):(q=createSprite(b,r,17,17,34,34),q.gotoAndStop(r));n.addChild(q);m?(b=s_oSpriteLibrary.getSprite("trap"),u=createBitmap(b),u.regX=b.width/2,u.regY=b.height/2,n.addChild(u)):(m=(new createjs.Graphics).beginFill("rgba(158,158,158,0.01)").drawRect(-a/2,-c/2,a,c),x=new createjs.Shape(m),
x.on("mousedown",this._onCellClick),n.addChild(x))};this.unload=function(){0<=r&&(f.removeChild(n),k||x.off("mousedown",this._onCellClick))};this.getType=function(){return r};this.setType=function(b){var d=r;r=b;-1===r?(9===d?new CParticle(a,c,q.currentFrame,f):new CParticle(a,c,d,f),e&&(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||!0!==s_bAudioActive||(s_aAudioSfx.wood=createjs.Sound.play("wood"),s_aAudioSfx.wood.addEventListener("complete",function(){s_aAudioSfx.wood=null})),new CParticle(a,c,9,f),
e=t.visible=!1,s_oGame.updateGoalsForBlock()),0<=d&&6>d||9===d?createjs.Tween.get(q).to({scaleX:.1,scaleY:.1},250).call(function(){q.gotoAndStop(r)}):q.gotoAndStop(r)):-3===r?q.gotoAndStop(r):9===r?(q.scaleX=1,q.scaleY=1,q.gotoAndPlay("changing")):(q.scaleX=1,q.scaleY=1,q.gotoAndStop(r))};this.getToDelete=function(){return l};this.setToDelete=function(a){l=a};this.getTrap=function(){return g};this.getPos=function(){return{x:a,y:c}};this._onCellClick=function(){9===r?s_oGame.checkCellClicked(b,d,q.currentFrame):
s_oGame.checkCellClicked(b,d,r)};this._init(a,c,b,d,f,h,m,k)}
function CSpriteLibrary(){var a,c,b,d,f,h;this.init=function(m,k,l){b=c=0;d=m;f=k;h=l;a={}};this.addSprite=function(b,d){a.hasOwnProperty(b)||(a[b]={szPath:d,oSprite:new Image},c++)};this.getSprite=function(b){return a.hasOwnProperty(b)?a[b].oSprite:null};this._onSpritesLoaded=function(){f.call(h)};this._onSpriteLoaded=function(){d.call(h);++b==c&&this._onSpritesLoaded()};this.loadSprites=function(){for(var b in a)a[b].oSprite.oSpriteLibrary=this,a[b].oSprite.onload=function(){this.oSpriteLibrary._onSpriteLoaded()},
a[b].oSprite.src=a[b].szPath};this.getNumSprites=function(){return c}}
var CANVAS_WIDTH=640,CANVAS_HEIGHT=480,EDGEBOARD_X=0,EDGEBOARD_Y=0,FPS_TIME=1E3/24,DISABLE_SOUND_MOBILE=!1,STATE_LOADING=0,STATE_MENU=1,STATE_HELP=1,STATE_GAME=3,ON_MOUSE_DOWN=0,ON_MOUSE_UP=1,ON_MOUSE_OVER=2,ON_MOUSE_OUT=3,ON_DRAG_START=4,ON_DRAG_END=5,CELL_FILL_NULL=0,CELL_FILL_FACE=1,CELL_FILL_BOMB=2,CELL_FILL_STAR=3,CELL_FILL_BLOCK=4,CELL_FILL_CLOCK=5,CELL_FILL_CHANGE=6,CELL_FILL_STARANDBLOCK=7,CELL_FILL_TRAP=8,CELL_STATE_MATCHED=-1,CELL_STATE_DISABLE=-2,CELL_STATE_INVISIBLE=-3,CELL_SIZE=40,TIME_FALL=
130,TIMER_TIME=2E4,TIME_TO_ADD=15E3,TIMER_CHANGING=2E4,SCORES_FOR_SINGLE,SCORES_FOR_BOMB,SCORES_FOR_STAR,EXTRA_FACE_MULTIPLIER;
function CToggle(a,c,b,d){var f,h,m,k;this._init=function(a,b,c,d){h=[];m=[];var n=new createjs.SpriteSheet({images:[c],frames:{width:c.width/4,height:c.height,regX:c.width/4/2,regY:c.height/2},animations:{state_true:[0],state_false:[1],state_true_over:[2],state_false_over:[3]}});f=d;k=createSprite(n,"state_"+f,c.width/4/2,c.height/2,c.width/4,c.height);k.x=a;k.y=b;k.stop();s_oStage.addChild(k);this._initListener()};this.unload=function(){s_bMobile?k.off("mousedown",this.buttonDown):(k.off("mousedown",
this.buttonDown),k.off("mouseover",this.buttonOver),k.off("mouseout",this.buttonOut));k.off("pressup",this.buttonRelease);s_oStage.removeChild(k)};this._initListener=function(){if(s_bMobile)k.on("mousedown",this.buttonDown);else k.on("mousedown",this.buttonDown),k.on("mouseover",this.buttonOver),k.on("mouseout",this.buttonOut);k.on("pressup",this.buttonRelease)};this.addEventListener=function(a,b,c){h[a]=b;m[a]=c};this.setActive=function(a){f=a;k.gotoAndStop("state_"+f)};this.buttonRelease=function(){f=
!f;s_bMobile?k.gotoAndStop("state_"+f):k.gotoAndStop("state_"+f+"_over");h[ON_MOUSE_UP]&&h[ON_MOUSE_UP].call(m[ON_MOUSE_UP],f)};this.buttonOver=function(){s_bMobile?k.gotoAndStop("state_"+f):(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||!0!==s_bAudioActive||(s_aAudioSfx.click=createjs.Sound.play("click"),s_aAudioSfx.click.addEventListener("complete",function(){s_aAudioSfx.click=null})),k.gotoAndStop("state_"+f+"_over"))};this.buttonOut=function(){k.gotoAndStop("state_"+f)};this.buttonDown=function(){!s_bMobile||
!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||!0!==s_bAudioActive||(s_aAudioSfx.click=createjs.Sound.play("click"),s_aAudioSfx.click.addEventListener("complete",function(){s_aAudioSfx.click=null}));h[ON_MOUSE_DOWN]&&h[ON_MOUSE_DOWN].call(m[ON_MOUSE_DOWN])};this.setPosition=function(a,b){k.x=a;k.y=b};this._init(a,c,b,d)}var s_iScaleFactor=1,s_oCanvasLeft,s_oCanvasTop;
(function(a){(jQuery.browser=jQuery.browser||{}).mobile=/android|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(ad|hone|od)|iris|kindle|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|symbian|tablet|treo|up\.(browser|link)|vodafone|wap|webos|windows (ce|phone)|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|e\-|e\/|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(di|rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|xda(\-|2|g)|yas\-|your|zeto|zte\-/i.test(a.substr(0,
4))})(navigator.userAgent||navigator.vendor||window.opera);$(window).resize(function(){sizeHandler()});function trace(a){console.log(a)}
function getSize(a){var c=a.toLowerCase(),b=window.document,d=b.documentElement;if(void 0===window["inner"+a])a=d["client"+a];else if(window["inner"+a]!=d["client"+a]){var f=b.createElement("body");f.id="vpw-test-b";f.style.cssText="overflow:scroll";var h=b.createElement("div");h.id="vpw-test-d";h.style.cssText="position:absolute;top:-1000px";h.innerHTML="<style>@media("+c+":"+d["client"+a]+"px){body#vpw-test-b div#vpw-test-d{"+c+":7px!important}}</style>";f.appendChild(h);d.insertBefore(f,b.head);
a=7==h["offset"+a]?d["client"+a]:window["inner"+a];d.removeChild(f)}else a=window["inner"+a];return a}$(window).ready(function(){sizeHandler()});window.addEventListener("orientationchange",onOrientationChange);function onOrientationChange(){window.matchMedia("(orientation: portrait)").matches&&sizeHandler();window.matchMedia("(orientation: landscape)").matches&&sizeHandler()}function getIOSWindowHeight(){return document.documentElement.clientWidth/window.innerWidth*window.innerHeight}
function getHeightOfIOSToolbars(){var a=(0===window.orientation?screen.height:screen.width)-getIOSWindowHeight();return 1<a?a:0}
function sizeHandler(){window.scrollTo(0,1);if($("#canvas")){var a;a=navigator.userAgent.match(/(iPad|iPhone|iPod)/g)?getIOSWindowHeight():getSize("Height");var c=getSize("Width"),b=Math.min(a/CANVAS_HEIGHT,c/CANVAS_WIDTH),d=CANVAS_WIDTH*b,b=CANVAS_HEIGHT*b,f=0;b<a?(f=a-b,b+=f,d+=CANVAS_WIDTH/CANVAS_HEIGHT*f):d<c&&(f=c-d,d+=f,b+=CANVAS_HEIGHT/CANVAS_WIDTH*f);var f=a/2-b/2,h=c/2-d/2,m=CANVAS_WIDTH/d;if(h*m<-EDGEBOARD_X||f*m<-EDGEBOARD_Y)b=Math.min(a/(CANVAS_HEIGHT-2*EDGEBOARD_Y),c/(CANVAS_WIDTH-2*
EDGEBOARD_X)),d=CANVAS_WIDTH*b,b*=CANVAS_HEIGHT,f=(a-b)/2,h=(c-d)/2,m=CANVAS_WIDTH/d;s_iOffsetX=-1*h*m;s_iOffsetY=-1*f*m;0<=f&&(s_iOffsetY=0);0<=h&&(s_iOffsetX=0);$("#canvas").css("width",d+"px");$("#canvas").css("height",b+"px");0>f?$("#canvas").css("top",f+"px"):$("#canvas").css("top","0px");$("#canvas").css("left",h+"px")}}
function createBitmap(a,c,b){var d=new createjs.Bitmap(a),f=new createjs.Shape;c&&b?f.graphics.beginFill("#fff").drawRect(0,0,c,b):f.graphics.beginFill("#ff0").drawRect(0,0,a.width,a.height);d.hitArea=f;return d}function createSprite(a,c,b,d,f,h){a=null!==c?new createjs.Sprite(a,c):new createjs.Sprite(a);c=new createjs.Shape;c.graphics.beginFill("#000000").drawRect(-b,-d,f,h);a.hitArea=c;return a}
function randomFloatBetween(a,c,b){"undefined"===typeof b&&(b=2);return parseFloat(Math.min(a+Math.random()*(c-a),c).toFixed(b))}function rotateVector2D(a,c){var b=c.getX()*Math.cos(a)+c.getY()*Math.sin(a),d=c.getX()*-Math.sin(a)+c.getY()*Math.cos(a);c.set(b,d)}function tweenVectorsOnX(a,c,b){return a+b*(c-a)}Array.prototype.max=function(){return Math.max.apply(null,this)};Array.prototype.min=function(){return Math.min.apply(null,this)};
function shuffle(a){for(var c=a.length,b,d;0!==c;)d=Math.floor(Math.random()*c),--c,b=a[c],a[c]=a[d],a[d]=b;return a}function bubbleSort(a){var c;do{c=!1;for(var b=0;b<a.length-1;b++)a[b]>a[b+1]&&(c=a[b],a[b]=a[b+1],a[b+1]=c,c=!0)}while(c)}function compare(a,c){return a.index>c.index?-1:a.index<c.index?1:0}function easeLinear(a,c,b,d){return b*a/d+c}function easeInQuad(a,c,b,d){return b*(a/=d)*a+c}function easeInSine(a,c,b,d){return-b*Math.cos(a/d*(Math.PI/2))+b+c}
function easeInCubic(a,c,b,d){return b*(a/=d)*a*a+c}function getTrajectoryPoint(a,c){var b=new createjs.Point,d=(1-a)*(1-a),f=a*a;b.x=d*c.start.x+2*(1-a)*a*c.traj.x+f*c.end.x;b.y=d*c.start.y+2*(1-a)*a*c.traj.y+f*c.end.y;return b}function formatTime(a){a/=1E3;var c=Math.floor(a/60);a=Math.floor(a-60*c);var b="",b=10>c?b+("0"+c+":"):b+(c+":");return 10>a?b+("0"+a):b+a}function degreesToRadians(a){return a*Math.PI/180}
function checkRectCollision(a,c){var b,d;b=getBounds(a,.9);d=getBounds(c,.98);return calculateIntersection(b,d)}function calculateIntersection(a,c){var b,d,f,h,m,k,l,e;b=a.x+(f=a.width/2);d=a.y+(h=a.height/2);m=c.x+(k=c.width/2);l=c.y+(e=c.height/2);b=Math.abs(b-m)-(f+k);d=Math.abs(d-l)-(h+e);return 0>b&&0>d?(b=Math.min(Math.min(a.width,c.width),-b),d=Math.min(Math.min(a.height,c.height),-d),{x:Math.max(a.x,c.x),y:Math.max(a.y,c.y),width:b,height:d,rect1:a,rect2:c}):null}
function getBounds(a,c){var b={x:Infinity,y:Infinity,width:0,height:0};if(a instanceof createjs.Container){b.x2=-Infinity;b.y2=-Infinity;var d=a.children,f=d.length,h,m;for(m=0;m<f;m++)h=getBounds(d[m],1),h.x<b.x&&(b.x=h.x),h.y<b.y&&(b.y=h.y),h.x+h.width>b.x2&&(b.x2=h.x+h.width),h.y+h.height>b.y2&&(b.y2=h.y+h.height);Infinity==b.x&&(b.x=0);Infinity==b.y&&(b.y=0);Infinity==b.x2&&(b.x2=0);Infinity==b.y2&&(b.y2=0);b.width=b.x2-b.x;b.height=b.y2-b.y;delete b.x2;delete b.y2}else{var k,l;a instanceof createjs.Bitmap?
(f=a.sourceRect||a.image,m=f.width*c,k=f.height*c):a instanceof createjs.Sprite?a.spriteSheet._frames&&a.spriteSheet._frames[a.currentFrame]&&a.spriteSheet._frames[a.currentFrame].image?(f=a.spriteSheet.getFrame(a.currentFrame),m=f.rect.width,k=f.rect.height,d=f.regX,l=f.regY):(b.x=a.x||0,b.y=a.y||0):(b.x=a.x||0,b.y=a.y||0);d=d||0;m=m||0;l=l||0;k=k||0;b.regX=d;b.regY=l;f=a.localToGlobal(0-d,0-l);h=a.localToGlobal(m-d,k-l);m=a.localToGlobal(m-d,0-l);d=a.localToGlobal(0-d,k-l);b.x=Math.min(Math.min(Math.min(f.x,
h.x),m.x),d.x);b.y=Math.min(Math.min(Math.min(f.y,h.y),m.y),d.y);b.width=Math.max(Math.max(Math.max(f.x,h.x),m.x),d.x)-b.x;b.height=Math.max(Math.max(Math.max(f.y,h.y),m.y),d.y)-b.y}return b}function NoClickDelay(a){this.element=a;window.Touch&&this.element.addEventListener("touchstart",this,!1)}function shuffle(a){for(var c=a.length,b,d;0<c;)d=Math.floor(Math.random()*c),c--,b=a[c],a[c]=a[d],a[d]=b;return a}
NoClickDelay.prototype={handleEvent:function(a){switch(a.type){case "touchstart":this.onTouchStart(a);break;case "touchmove":this.onTouchMove(a);break;case "touchend":this.onTouchEnd(a)}},onTouchStart:function(a){a.preventDefault();this.moved=!1;this.element.addEventListener("touchmove",this,!1);this.element.addEventListener("touchend",this,!1)},onTouchMove:function(a){this.moved=!0},onTouchEnd:function(a){this.element.removeEventListener("touchmove",this,!1);this.element.removeEventListener("touchend",
this,!1);if(!this.moved){a=document.elementFromPoint(a.changedTouches[0].clientX,a.changedTouches[0].clientY);3==a.nodeType&&(a=a.parentNode);var c=document.createEvent("MouseEvents");c.initEvent("click",!0,!0);a.dispatchEvent(c)}}};
(function(){function a(a){var d={focus:"visible",focusin:"visible",pageshow:"visible",blur:"hidden",focusout:"hidden",pagehide:"hidden"};a=a||window.event;a.type in d?document.body.className=d[a.type]:(document.body.className=this[c]?"hidden":"visible","hidden"===document.body.className?s_oMain.stopUpdate():s_oMain.startUpdate())}var c="hidden";c in document?document.addEventListener("visibilitychange",a):(c="mozHidden")in document?document.addEventListener("mozvisibilitychange",a):(c="webkitHidden")in
document?document.addEventListener("webkitvisibilitychange",a):(c="msHidden")in document?document.addEventListener("msvisibilitychange",a):"onfocusin"in document?document.onfocusin=document.onfocusout=a:window.onpageshow=window.onpagehide=window.onfocus=window.onblur=a})();
function CTextButton(a,c,b,d,f,h,m){var k,l,e,g,r,n,q;this._init=function(a,b,c,d,f,h,m){l=[];e=[];k=c;c=m+"px";q=new createjs.Text;q.text=k;q.font="bold "+c+" Roboto";q.color=h;q.textAlign="center";q.textBaseline="middle";q.lineWidth=400;q.outline=8;n=new createjs.Text;n.text=k;n.font="bold "+c+" Roboto";n.color=d;n.textAlign="center";n.textBaseline="middle";n.lineWidth=400;d=(new createjs.Graphics).beginFill("rgba(158,158,158,0.01)").drawRect(-q.getMeasuredWidth()/2,-q.getMeasuredHeight()/2-10,
q.getMeasuredWidth(),q.getMeasuredHeight()+20);r=new createjs.Shape(d);g=new createjs.Container;g.x=a;g.y=b;g.addChild(q,n,r);f.addChild(g);this._initListener()};this.unload=function(){s_bMobile?g.off("mousedown",this.buttonDown):(g.off("mousedown",this.buttonDown),g.off("mouseover",this.buttonOver),g.off("mouseout",this.buttonOut));g.off("pressup",this.buttonRelease);f.removeChild(g)};this.setVisible=function(a){g.visible=a};this._initListener=function(){if(s_bMobile)g.on("mousedown",this.buttonDown);
else g.on("mousedown",this.buttonDown),g.on("mouseover",this.buttonOver),g.on("mouseout",this.buttonOut);g.on("pressup",this.buttonRelease)};this.addEventListener=function(a,c,b){l[a]=c;e[a]=b};this.buttonRelease=function(){l[ON_MOUSE_UP]&&l[ON_MOUSE_UP].call(e[ON_MOUSE_UP])};this.buttonOver=function(){g.scaleX=1.1;g.scaleY=1.1;n.color="#ffa800";s_bMobile||!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||!0!==s_bAudioActive||(s_aAudioSfx.click=createjs.Sound.play("click"),s_aAudioSfx.click.addEventListener("complete",
function(){s_aAudioSfx.click=null}))};this.buttonOut=function(){g.scaleX=1;g.scaleY=1;n.color=d};this.buttonDown=function(){!s_bMobile||!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||!0!==s_bAudioActive||(s_aAudioSfx.click=createjs.Sound.play("click"),s_aAudioSfx.click.addEventListener("complete",function(){s_aAudioSfx.click=null}));l[ON_MOUSE_DOWN]&&l[ON_MOUSE_DOWN].call(e[ON_MOUSE_DOWN])};this.setTextPosition=function(a){n.y=a};this.setPosition=function(a,c){g.x=a;g.y=c};this.setX=function(a){g.x=a};
this.setY=function(a){g.y=a};this.getButtonImage=function(){return g};this.getX=function(){return g.x};this.getY=function(){return g.y};this._init(a,c,b,d,f,h,m);return this}
function CPreloader(){var a,c,b,d,f,h,m;this._init=function(){s_oSpriteLibrary.init(this._onImagesLoaded,this._onAllImagesLoaded,this);s_oSpriteLibrary.addSprite("bg_menu","./sprites/bg_game.jpg");s_oSpriteLibrary.addSprite("progress_bar","./sprites/progress_bar.png");s_oSpriteLibrary.loadSprites();m=new createjs.Container;s_oStage.addChild(m)};this.unload=function(){m.removeAllChildren()};this.hide=function(){var a=this;setTimeout(function(){createjs.Tween.get(h).to({alpha:1},500).call(function(){a.unload();
s_oMain.gotoMenu()})},1E3)};this._onImagesLoaded=function(){};this._onAllImagesLoaded=function(){this.attachSprites();s_oMain.preloaderReady()};this.attachSprites=function(){var k=createBitmap(s_oSpriteLibrary.getSprite("bg_menu"));m.addChild(k);k=s_oSpriteLibrary.getSprite("progress_bar");d=createBitmap(k);d.x=CANVAS_WIDTH/2-k.width/2;d.y=CANVAS_HEIGHT-170;m.addChild(d);a=k.width;c=k.height;f=new createjs.Shape;f.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(d.x,d.y,1,c);m.addChild(f);d.mask=
f;b=new createjs.Text(" ","30px Arial","#fff");b.x=CANVAS_WIDTH/2;b.y=CANVAS_HEIGHT-125;b.shadow=new createjs.Shadow("#000",2,2,2);b.textBaseline="alphabetic";b.textAlign="center";m.addChild(b);h=new createjs.Shape;h.graphics.beginFill("black").drawRect(0,0,CANVAS_WIDTH,CANVAS_HEIGHT);h.alpha=0;m.addChild(h)};this.refreshLoader=function(h){b.text=h+"%";f.graphics.clear();h=Math.floor(h*a/100);f.graphics.beginFill("rgba(255,255,255,0.01)").drawRect(d.x,d.y,h,c)};this._init()}
function CPausePanel(a){var c,b,d;this._init=function(a){var h=s_oSpriteLibrary.getSprite("pause_panel");c=createBitmap(h);c.on("mousedown",function(){});a.addChild(c);b=new CFormatText(CANVAS_WIDTH/2,CANVAS_HEIGHT/2-40,TEXT_ISPAUSED,"#ffe400",a,"#ac5124",20);d=new CTextButton(CANVAS_WIDTH/2,CANVAS_HEIGHT/2+20,TEXT_CONTINUE,"#00cf0f",a,"#FFFFFF",26);d.addEventListener(ON_MOUSE_UP,this._onButContinueRelease,this)};this.unload=function(){b.unload();b=null;d.unload();d=null;c.off("mousedown",function(){});
a.removeChild(c)};this._onButContinueRelease=function(){s_oGame.resumeGame()};this._init(a)}
function CParticle(a,c,b,d){var f=null,h;this._init=function(a,c,b,d){switch(b){case 0:b=s_oSpriteLibrary.getSprite("explosion_green");break;case 1:b=s_oSpriteLibrary.getSprite("explosion_red");break;case 2:b=s_oSpriteLibrary.getSprite("explosion_blue");break;case 3:b=s_oSpriteLibrary.getSprite("explosion_yellow");break;case 4:b=s_oSpriteLibrary.getSprite("explosion_violet");break;case 5:b=s_oSpriteLibrary.getSprite("explosion_cyan");break;case 7:b=s_oSpriteLibrary.getSprite("explosion_radial");b=
{framerate:20,images:[b],frames:{width:150,height:150,regX:75,regY:75},animations:{idle:[0,21,"stop"],stop:[22]}};b=new createjs.SpriteSheet(b);f=createSprite(b,"idle",77,40,154,182);f.on("animationend",this._onParticleEnd);f.gotoAndPlay("idle");f.x=a;f.y=c;createjs.Tween.get(f).to({alpha:0},1E3,createjs.Ease.cubicIn);d.addChild(f);return;case 8:b=s_oSpriteLibrary.getSprite("explosion_clock");break;case 9:b=s_oSpriteLibrary.getSprite("explosion_block");b={framerate:20,images:[b],frames:{width:154,
height:182,regX:77,regY:40},animations:{idle:[0,19,"stop"],stop:[20]}};b=new createjs.SpriteSheet(b);f=createSprite(b,"idle",77,40,154,182);f.on("animationend",this._onParticleEnd);f.gotoAndPlay("idle");f.x=a;f.y=c;createjs.Tween.get(f).to({alpha:0},1E3,createjs.Ease.cubicIn);d.addChild(f);return;default:return}b={framerate:20,images:[b],frames:{width:150,height:200,regX:75,regY:25},animations:{idle:[0,21,"stop"],stop:[22]}};b=new createjs.SpriteSheet(b);f=createSprite(b,"idle",75,25,150,200);f.on("animationend",
this._onParticleEnd);f.gotoAndPlay("idle");f.x=a;f.y=c;createjs.Tween.get(f).to({alpha:0},1E3,createjs.Ease.cubicIn);d.addChild(f)};this.unload=function(){null!==f&&(f.visible=!1,f.off("animationend",this._onParticleEnd),d.removeChild(f))};this._onParticleEnd=function(){"idle"===f.currentAnimation&&h.unload()};h=this;this._init(a,c,b,d)}
function CNextLevelPanel(a,c,b,d){var f,h,m,k,l,e,g,r,n,q,t,u,x;this._init=function(a,b,c,d){var I=s_oSpriteLibrary.getSprite("black_panel");h=createBitmap(I);h.on("mousedown",function(){});d.addChild(h);k=new createjs.Container;k.y=480;I=s_oSpriteLibrary.getSprite("end_panel");m=createBitmap(I);m.regX=I.width/2;m.regY=I.height/2;m.x=CANVAS_WIDTH/2;m.y=CANVAS_HEIGHT/2;k.addChild(m);a?(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||!0!==s_bAudioActive||(s_aAudioSfx.tada=createjs.Sound.play("tada"),s_aAudioSfx.tada.addEventListener("complete",
function(){s_aAudioSfx.tada=null}),s_aAudioSfx.applause2=createjs.Sound.play("applause2"),s_aAudioSfx.applause2.addEventListener("complete",function(){s_aAudioSfx.applause2=null})),l=new CFormatText(CANVAS_WIDTH/2,120,TEXT_WIN,"#ffe400",k,"#ac5124",30),e=new CFormatText(CANVAS_WIDTH/2,170,TEXT_SCORES+" "+b,"#ffe400",k,"#ac5124",20),g=new CFormatText(CANVAS_WIDTH/2,210,TEXT_TIMEBONUS+" "+c,"#ffe400",k,"#ac5124",20),f=b+c,r=new CFormatText(CANVAS_WIDTH/2,250,TEXT_TOTAL+" "+f,"#ffe400",k,"#ac5124",20),
n=new CTextButton(CANVAS_WIDTH/2,310,TEXT_NEXT,"#00cf0f",k,"#FFFFFF",26),n.addEventListener(ON_MOUSE_UP,this._onButNextRelease,this)):(!1!==DISABLE_SOUND_MOBILE&&!1!==s_bMobile||!0!==s_bAudioActive||(s_aAudioSfx.loser=createjs.Sound.play("loser"),s_aAudioSfx.loser.addEventListener("complete",function(){s_aAudioSfx.loser=null})),l=new CFormatText(CANVAS_WIDTH/2,120,TEXT_GAMEOVER,"#ffe400",k,"#ac5124",30),q=new CFormatText(CANVAS_WIDTH/2,190,TEXT_TIMEUP,"#ffe400",k,"#ac5124",22),t=new CTextButton(CANVAS_WIDTH/
2,265,TEXT_RETRY,"#00cf0f",k,"#FFFFFF",26),t.addEventListener(ON_MOUSE_UP,this._onButRetryRelease,this),u=new CTextButton(CANVAS_WIDTH/2,310,TEXT_SUBMIT,"#00cf0f",k,"#FFFFFF",26),u.addEventListener(ON_MOUSE_UP,this._onButSubmitRelease,this));x=new CTextButton(CANVAS_WIDTH/2,355,TEXT_MORE,"#00cf0f",k,"#FFFFFF",26);x.addEventListener(ON_MOUSE_UP,this._onButMoreRelease,this);d.addChild(k);this.show()};this.unload=function(){h.off("mousedown",function(){});l.unload();l=null;a?(e.unload(),e=null,g.unload(),
g=null,r.unload(),r=null,n.unload(),n=null):(q.unload(),q=null,t.unload(),t=null,u.unload(),u=null);x.unload();x=null;d.removeChild(h);d.removeChild(k)};this.show=function(a){createjs.Tween.get(k).to({y:0},500,createjs.Ease.backOut)};this._onButNextRelease=function(){createjs.Tween.get(k).to({y:480},500,createjs.Ease.backIn).call(function(){s_oGame.onNextLevel(f)})};this._onButMoreRelease=function(){window.open("http://www.spiele-umsonst.de/?utm_source=desert%2Bfaces&utm_medium=game&utm_campaign=sponsoring")};
this._onButSubmitRelease=function(){$(s_oMain).trigger("submit_score",s_iTotalScore)};this._onButRetryRelease=function(){createjs.Tween.get(k).to({y:480},500,createjs.Ease.backIn).call(function(){s_oGame.restartGame()})};this._init(a,c,b,d);return this};